"""Stage 2 English, Block B (poetry and word play), week 9, lessons 1 to 4.
Pass 2 (video pass): lessons at full depth plus videos on every lesson (two each for L1 and L4).
Video ids came from search. Transcript-checked: lOUnhSMGdOo, 5Mrb6wzbWmM, rQuWqcVzqUU. Still to check on playback: 5hGyLcNBZoM, GYIVwQdlmiw, f9fy4NREF-E.
Not yet registered in lesson_library.py. Keys use the prefix b9. Poems for reading are chosen by the parent; the example lines here are original."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

B9L1 = build(
    "s2-eng-b9-l1-rhyme-and-rhythm", "Rhyme and Rhythm",
    "Learn how rhyming words and a steady beat make a poem sound musical, and how to hear and mark both.",
    "Reading: rhyme and rhythm in poetry",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-OLC-01"],
    {"EN2-RECOM-01": "Primary. Identifies rhyme, rhyme scheme, syllables and rhythm in a poem and explains their effect.",
     "EN2-VOCAB-01": "Learns poem, verse, line, rhyme, syllable, rhythm and rhyme scheme.",
     "EN2-OLC-01": "Listens for sound patterns and reads a poem aloud with the beat."},
    "We are learning to hear rhyme and rhythm in a poem and to explain how they make it sound.",
    ["I can say what a verse and a line are.", "I can find rhyming words by their ending sounds.", "I can count syllables in a word.", "I can clap and mark the rhythm of a line.", "I can describe the rhyme scheme of a short poem."],
    ["verse", "line", "rhyme", "syllable", "rhythm", "rhyme scheme"],
    ["Paper or notebook", "Pencil", "A rhyming poem chosen by your parent"],
    "Child has read narrative texts. This lesson teaches the sound patterns of poetry from the beginning.",
    "A poem is often meant to be heard as well as read. Two sound patterns make many poems feel musical: RHYME and RHYTHM.\n\nRhyme is about matching sounds at the ends of words. Rhythm is about the beat of the words, the way strong and weak sounds fall one after another, like a drum pattern.\n\nIn this lesson you will learn the parts of a poem, how to tell whether words really rhyme, how to count syllables, how to find a rhythm, and how to describe a rhyme scheme using letters. Read aloud and tap along as you go: poems are learned with your ears.",
    [
        _step("1", "Lines and verses",
              "A poem is built from LINES. A line is one row of words. It does not have to be a full sentence, and it often stops where the poet wants a small pause.\n\nGroups of lines are called VERSES (also called stanzas). A blank space separates one verse from the next, a bit like a paragraph break in a story.\n\nExample:\nThe moon climbed over the hill,\nThe night was silver and still.\n\nThe wind tucked in the trees,\nAnd hushed the sleepy leaves.\n\nThis poem has two verses. Each verse has two lines, so the poem has four lines altogether.\n\nWhen you look at a poem, count the lines and verses first. This tells you its shape before you read a single word.",
              "Count: 'The moon climbed over the hill, / The night was silver and still.' is one verse with two lines.",
              "A verse is a group of lines. A line is one row of the poem.",
              ("A group of lines in a poem is a...", ["verse", "syllable", "title"], 0, "A verse is a group of lines separated by a space.")),
        _step("2", "What rhyme is",
              "Words RHYME when their ending sounds match, starting from the last strong vowel sound. Cat and hat rhyme. Light and night rhyme. Bake and lake rhyme.\n\nRhyme is about SOUND, not spelling. Some words are spelt differently but rhyme: blue, shoe and through. Some words are spelt alike but do not rhyme: through and tough, or cough and dough.\n\nTo test a rhyme, say both words aloud and listen. Ask: do the endings sound the same? Then check the beginnings: the first sounds must be DIFFERENT. Cat and cat do not rhyme; they are the same word.\n\nPoets often put rhyming words at the ENDS of lines, because that is where the ear expects a match.",
              "Rhyming families: -ight (light, night, flight), -ake (bake, lake, shake), -oon (moon, spoon, soon).",
              "Rhyme means matching ending sounds. Say the words aloud to test.",
              ("Which pair rhymes?", ["night, flight", "cough, dough", "cat, cap"], 0, "Night and flight end with the same sound.")),
        _step("3", "Rhyme scheme",
              "A RHYME SCHEME is the pattern of rhymes in a poem. We label it with letters. The first line's end sound is A. Every other line that rhymes with it is also A. A new end sound gets the next letter, B, and so on.\n\nExample:\nThe kite flew high in the sky, (A)\nIt danced where the seagulls fly. (A)\nThe string pulled tight in my hand, (B)\nAs I stood on the warm, soft sand. (B)\n\nThis scheme is AABB: two lines rhyme, then the next two lines rhyme.\n\nAnother common scheme is ABAB, where lines one and three rhyme, and lines two and four rhyme:\nThe river runs quickly (A)\nOver stones in the bed, (B)\nThe water goes slickly (A)\nWhere the old willows spread. (B)\n\nTo find a scheme, look only at the last word of each line. Label the first A. Ask whether each next word rhymes with an earlier one.",
              "Label: sky (A), fly (A), hand (B), sand (B) gives AABB.",
              "Label rhymes with letters: lines that rhyme share a letter.",
              ("The scheme of a poem with lines ending day, play, tree, free is...", ["AABB", "ABAB", "ABCD"], 0, "Day and play rhyme, then tree and free rhyme, so it is AABB.")),
        _step("4", "Syllables: the beats in words",
              "A SYLLABLE is a single beat of sound in a word. Every syllable has a vowel sound. You can count syllables by clapping or by putting your hand under your chin: your chin drops once for each syllable.\n\ncat: 1 syllable.\nwater: wa-ter, 2 syllables.\nbutterfly: but-ter-fly, 3 syllables.\nimagination: im-ag-i-na-tion, 5 syllables.\n\nSyllables matter because they build rhythm. A line with many short words feels different from a line with a few long ones.\n\nTry counting a line: 'The moon climbed over the hill.' The (1) moon (1) climbed (1) o-ver (2) the (1) hill (1) gives 7 syllables.\n\nCount by sound, not by letters. 'Fire' has four letters but is usually said as one or two syllables, depending on the speaker. Say it aloud and trust your ear.",
              "Clap it: pup-py (2), el-e-phant (3), chair (1).",
              "A syllable is one beat in a word. Clap to count.",
              ("How many syllables does 'butterfly' have?", ["3", "2", "4"], 0, "But-ter-fly has three beats.")),
        _step("5", "Rhythm: the beat of a line",
              "RHYTHM is the pattern of strong (loud) and weak (soft) beats in a line. Some syllables are stressed, which means you say them with more force.\n\nSay the line aloud: 'The MOON climbed O-ver the HILL.' You naturally hit MOON, O and HILL harder. Tap on those beats and the line has a swing.\n\nIn the nursery rhyme feeling of 'JACK and JILL went UP the HILL', the stresses fall in a steady pattern: that is a regular rhythm.\n\nA poet can change the rhythm to change the mood. Short, quick beats can feel like running or excitement. Long, slow beats can feel calm or sad.\n\nTo mark rhythm: write the line, underline or capitalise the stressed syllables, then tap the line. Say it twice to be sure.",
              "Mark: THE rain DRUMS on the ROOF all NIGHT: four taps.",
              "Rhythm is the pattern of strong and weak beats.",
              ("Rhythm is...", ["the pattern of strong and weak beats", "matching ending sounds", "the title of a poem"], 0, "Rhythm is the beat pattern. Matching ends are rhyme.")),
        _step("6", "Read and mark a poem",
              "Choose a short rhyming poem with your parent, ideally four to eight lines. Work through it in this order.\n\n1. Copy the poem, or draw boxes around its verses on a printed copy.\n2. Count the lines and verses.\n3. Circle the last word of each line. Label the rhyme scheme with letters.\n4. Choose two lines. Count the syllables in each and mark the stressed syllables.\n5. Read the poem aloud twice, tapping the beat. The second time, exaggerate the rhymes.\n6. Write two sentences: one about how the rhyme sounds, one about how the rhythm feels (fast, slow, bouncy, calm).\n\nModel sentences: 'The rhymes at the ends of the lines make the poem sound like a song. The short, quick beats make it feel like skipping.'",
              "Note: lines 1 and 2 rhyme (A), lines 3 and 4 rhyme (B), so the scheme is AABB.",
              "Count, label, tap, then describe.",
              ("What is the first thing to label when finding a rhyme scheme?", ["The last word of each line", "The title", "The first word of each verse"], 0, "Rhymes are found at the ends of lines.")),
    ],
    "Model answers. A verse is a group of lines. A line is one row of the poem. Words rhyme when their ending sounds match, such as night and flight; cough and dough do not rhyme. A rhyme scheme such as AABB labels which lines rhyme. A syllable is one beat in a word: butterfly has three. Rhythm is the pattern of strong and weak beats in a line. For your chosen poem, check the lines and verses are counted, the end words labelled with letters, two lines marked for syllables and stress, and two sentences describe rhyme and rhythm.",
    "1) Count the lines and verses in three short poems. 2) Sort ten words into rhyming families. 3) Find the rhyme scheme of three four-line poems. 4) Clap and count the syllables in twelve words. 5) Mark the stressed syllables in four lines. 6) Mark up your parent-chosen poem and write two sentences about its sound.",
    "Upload a photo of your marked poem, showing the labelled rhyme scheme, two lines with syllables and stress marked, and your two sentences about rhyme and rhythm.",
    CHECK,
    "Did I count the lines and verses? Did I circle the last word of every line? Did I label the rhyme scheme with letters? Did I count syllables for two lines? Did I mark the stressed syllables? Did I write one sentence about rhyme and one about rhythm?",
    [
        _q("Words rhyme when...", ["their ending sounds match", "they have the same first letter", "they have the same number of letters"], 0, "Rhyme is about matching end sounds."),
        _q("Which pair rhymes?", ["moon, spoon", "moon, mean", "moon, mood"], 0, "Moon and spoon share the same ending sound."),
        _q("A rhyme scheme of AABB means...", ["lines 1 and 2 rhyme, and lines 3 and 4 rhyme", "every line rhymes with every other line", "no lines rhyme"], 0, "Matching letters show which lines rhyme."),
        _q("How many syllables are in 'elephant'?", ["3", "2", "4"], 0, "El-e-phant has three beats."),
        _q("A stressed syllable is one that...", ["is said with more force", "is silent", "is always at the start of a word"], 0, "Stressed syllables are the stronger beats."),
        _q("A verse is...", ["a group of lines in a poem", "one word", "the last line only"], 0, "A verse groups lines together."),
        _q("Which pair does NOT rhyme?", ["cough, dough", "light, night", "bake, lake"], 0, "Cough and dough are spelt alike at the end but sound different."),
        _q("Rhythm is...", ["the beat pattern in a line", "the matching end sound", "the poem's author"], 0, "Rhythm describes strong and weak beats."),
    ],
    "Upload a photo of your marked poem and two sentences.",
    "With a parent, choose a short poem you have not seen before. Read it aloud twice, tap the beat, and find the rhyme scheme.",
    [("verse", "A group of lines in a poem, separated from the next group by a space."), ("line", "One row of words in a poem."), ("rhyme", "Words whose ending sounds match."), ("syllable", "One beat of sound in a word."), ("rhythm", "The pattern of strong and weak beats in a line."), ("rhyme scheme", "The pattern of rhymes in a poem, shown with letters such as AABB.")],
    [
        _video("POEMS for Kids: Characteristics and Elements of Poems", "lOUnhSMGdOo",
               "Listen for lines, stanzas, rhyme and rhythm. The video says stanza where this lesson says verse, and it also mentions meter, which you do not need to learn yet. Pause and clap the beat of one line.",
               "If the video does not play, say a four-line poem aloud, clap the beat and name one pair of rhyming words.",
               ("In a poem, a stanza is the same as a...", ["verse", "syllable", "title"], 0, "A stanza is another word for a verse, a group of lines.")),
        _video("How to Rhyme: A Poetry Lesson (Kenn Nesbitt)", "5hGyLcNBZoM",
               "Watch what a rhyme is and what is not a rhyme. Say each rhyming pair aloud and listen to the ending sounds.",
               "If the video does not play, write three pairs of rhyming words and one pair of words that look alike but do not rhyme.",
               ("Do two words need the same spelling to rhyme?", ["No, they need matching ending sounds", "Yes, always", "Only if they have the same letters"], 0, "Rhyme is about sound, not spelling.")),
    ],
    _sort("Rhyme families", "Which rhyming family does each word belong to? Tap a group, then Check.",
          ["-ight", "-ake", "-oon"],
          [("spoon", 2), ("night", 0), ("lake", 1), ("flight", 0), ("soon", 2), ("shake", 1), ("light", 0), ("balloon", 2), ("bake", 1)]),
    [
        _wc("Words with matching end sounds ___.", ["rhyme", "rime", "rym"], 0, "Rhyme has a silent e and a y."),
        _wc("The beat pattern in a line is its ___.", ["rhythm", "rythm", "rhythem"], 0, "Rhythm has two h letters."),
        _wc("One beat of sound in a word is a ___.", ["syllable", "sylable", "syllabel"], 0, "Syllable has double l."),
        _wc("A group of lines in a poem is a ___.", ["verse", "vers", "verce"], 0, "Verse ends with silent e."),
        _wc("Which is spelt correctly?", ["scheme", "skeme", "sheme"], 0, "Scheme starts with sch."),
    ],
    [
        {"key": "shape", "label": "Shape of the poem", "hint": "Lines and verses counted."},
        {"key": "scheme", "label": "Rhyme scheme", "hint": "End words circled and labelled with letters."},
        {"key": "beat", "label": "Syllables and stress", "hint": "Two lines counted and stress marked."},
        {"key": "describe", "label": "Describing the sound", "hint": "One sentence about rhyme and one about rhythm."},
    ],
    ["Judging rhyme by spelling instead of sound.", "Counting letters instead of syllables.", "Labelling a new letter for a word that rhymes with an earlier line.", "Treating a rhyming pair of the same word as a rhyme.", "Reading a poem silently and missing its beat."],
    [{"title": "Beat Detective", "description": "Choose two verses of a poem you like. Mark the stressed syllables, label the rhyme scheme and read it aloud to a family member.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary with the chosen poem. Check that lines and verses are counted correctly, each end word is labelled with the right letter, two lines have syllables counted and stress marked, and the descriptive sentences name an actual effect of the rhyme and rhythm. Sorter: -ight: night, flight, light. -ake: lake, shake, bake. -oon: spoon, soon, balloon.",
)

B9L2 = build(
    "s2-eng-b9-l2-writing-a-rhyming-poem", "Writing a Rhyming Poem",
    "Learn a step-by-step method for planning, drafting and polishing a short rhyming poem with a steady beat.",
    "Writing: composing a rhyming poem",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-OLC-01"],
    {"EN2-CWT-01": "Primary. Plans, drafts and revises a rhyming poem using rhyme, rhythm and precise word choice.",
     "EN2-VOCAB-01": "Uses rhyme families, precise verbs and rhyme-bank words.",
     "EN2-OLC-01": "Reads a poem aloud to test its sound and fix it."},
    "We are learning to plan and write a short rhyming poem and to fix it by reading it aloud.",
    ["I can choose a topic and collect ideas for a poem.", "I can build a rhyme bank of word families.", "I can draft a verse with a clear rhyme scheme.", "I can fix a line that does not fit the beat.", "I can write and read aloud a four to eight line poem."],
    ["topic", "rhyme bank", "draft", "stanza", "imagery", "revise"],
    ["Paper or notebook", "Pencil", "A rhyming dictionary or word list if available"],
    "Child has learned rhyme, rhythm and syllables in Lesson 1. This lesson uses them to write an original poem.",
    "Writing a rhyming poem is easier when you do not start from the first line. Many poets begin with the ideas and the rhymes, then build the lines around them.\n\nA common mistake is to pick any word that rhymes, even when it makes no sense. A poem like 'The cat sat on the mat, and then he found a bat' sounds fine but does not say anything new. Good rhyming poems let the meaning lead and use the rhyme as a helper.\n\nIn this lesson you will learn to choose a topic, build a rhyme bank, draft a verse in a set scheme, fix the beat by reading aloud, and finish a short poem you can be proud of.",
    [
        _step("1", "Choose a topic and collect ideas",
              "Start with a TOPIC you know well or can picture clearly: a storm, a pet, a beach, a favourite food, a game. A narrow topic gives more to say than a huge one. 'My dog waiting at the gate' is stronger than 'animals'.\n\nThen collect ideas before you write a single line. Use a quick web of notes.\n\nTopic: thunderstorm\nSee: dark clouds, flashes, puddles\nHear: rumble, drum, splash\nFeel: cold wind, wet hair\nDo: run, hide, jump\n\nThese words will become the pictures in your poem. Try to include at least one sound and one thing you can see.",
              "Topic web for 'beach': sand, waves, shells, salty wind, shouting seagulls.",
              "Pick a clear topic, then collect words you can see, hear, feel and do.",
              ("Which is the best poem topic?", ["My dog waiting at the gate", "Everything", "Things"], 0, "A clear, narrow topic gives more to describe.")),
        _step("2", "Build a rhyme bank",
              "A RHYME BANK is a list of words that rhyme, collected before drafting so you are never stuck at the end of a line.\n\nPick two or three important words from your topic web and find their rhyming family. Run through the alphabet to find them: for 'storm', try born, corn, dorm, form, horn, morn, norm, torn, warm. Not all will fit, but some will.\n\nFor 'night': bright, flight, fright, light, might, right, sight, tight.\nFor 'rain': drain, plain, train, stain, brain, again.\n\nCross out words that do not match your topic. Circle the best three or four in each family. These are your END words.\n\nA word that is spelt differently but sounds the same still counts. Storm and warm, for example, do not rhyme perfectly, so check by saying them aloud.",
              "Rhyme bank for 'splash': crash, flash, dash, gash, cash, trash. Best: crash, flash, dash.",
              "Collect rhyming families first, then pick the best words.",
              ("A rhyme bank is...", ["a list of rhyming words collected before drafting", "a bank that holds money", "the title of a poem"], 0, "It helps you choose end words ready for your lines.")),
        _step("3", "Draft a verse",
              "Pick a rhyme scheme. AABB is the easiest to start with: lines 1 and 2 rhyme, then lines 3 and 4 rhyme. Write your END WORDS first, then fill in each line so it makes sense.\n\nEnd words: flash, crash, rain, again.\n\nLine 1: Lightning went flash\nLine 2: With a thunder crash\nLine 3: Down came the rain\nLine 4: Again and again\n\nIt works, and it says something. Now improve the details. 'Lightning went flash' becomes 'White lightning split the sky with a flash', but be careful: changing one line can change its length and rhythm.\n\nWrite two or three versions of a tricky line. Choose the one that sounds best aloud.\n\nDo not twist a sentence into an odd shape just to make a rhyme. If a line sounds strange, try a different end word from your bank.",
              "Version 1: 'Thunder gave a crash.' Version 2: 'The thunder gave a crash.' Version 2 has a steadier beat.",
              "Write end words first, then build the line around them.",
              ("What should you do if a line sounds odd just to make a rhyme?", ["Choose a different end word", "Keep it anyway", "Delete the whole poem"], 0, "Meaning matters more than a forced rhyme.")),
        _step("4", "Fix the beat",
              "Read your verse aloud and tap the beat. Do the lines have a similar number of beats? In AABB poems, lines that rhyme together often have similar length so the pattern feels even.\n\nProblem: 'The thunder gave a very loud and scary crash.' It is too long, so it breaks the pattern.\n\nFix: 'The thunder gave a crash.'\n\nTools for fixing the beat:\n- Cut extra words, such as very, really and just.\n- Swap a long word for a short word, or a short word for a long one.\n- Change the order of words.\n- Add a word if a line feels too short.\n\nSyllable counts help. If lines 1 and 2 have 6 and 6 syllables, line 3 should sit close, say 5 to 7.\n\nAlways read the line aloud after changing it, because your ear is the best judge.",
              "Tap: 'Down CAME the RAIN' (3 beats) and 'A-GAIN and a-GAIN' (3 beats): they match.",
              "Trim and swap words until lines of a pair have a similar beat.",
              ("Which change could fix a line that is too long?", ["Cut words such as very and really", "Add more adjectives", "Remove the rhyme"], 0, "Cutting filler words shortens the line.")),
        _step("5", "Use strong pictures",
              "A poem is short, so every word counts. Replace weak, general words with words that show a clear picture. This is called using IMAGERY: language that helps the reader see, hear, smell, taste or feel.\n\nWeak: 'The rain was loud.'\nStronger: 'The rain drummed on the tin roof.'\n\nWeak: 'I felt happy.'\nStronger: 'My heart skipped like a stone on the lake.'\n\nLook for chances to use specific verbs (drummed, splashed, crept), specific nouns (tin roof, gumboots), and one comparison if you can.\n\nBut keep the rhyme and beat. After each change, read the line aloud again.\n\nOne vivid line is better than four dull lines.",
              "Swap 'went' for 'raced', 'water' for 'puddles', 'big' for 'enormous', if it still fits the beat.",
              "Choose specific words and images, then re-test the beat.",
              ("Which line shows a stronger picture?", ["The rain drummed on the tin roof.", "The rain was loud.", "It was a rainy day."], 0, "Drummed on the tin roof lets you hear and see the rain.")),
        _step("6", "Write and read your poem",
              "Now write your own poem, 4 to 8 lines, in AABB or ABAB.\n\n1. Write your topic and a mini web of ideas.\n2. Make a rhyme bank for two rhyme families.\n3. Choose your rhyme scheme and write your end words.\n4. Draft each line around its end word.\n5. Read aloud, tap the beat, and fix any line that does not match.\n6. Improve at least two lines with stronger pictures.\n7. Give your poem a title and write a neat copy.\n8. Read it aloud to someone.\n\nModel poem:\nStorm Song\nWhite lightning cracked the sky with a flash,\nThen thunder rolled with a grumbling crash.\nThe rain came tumbling down the street,\nAnd puddles splashed around my feet.\n\nYour poem does not need to match this one. It only needs to sound good when read aloud.",
              "Finished poems have a title, a clear rhyme scheme and a steady beat.",
              "Plan, bank, draft, fix, polish, read aloud.",
              ("What is the last step before sharing your poem?", ["Read it aloud to check the sound", "Erase every rhyme", "Forget the title"], 0, "Reading aloud shows whether the beat and rhymes work.")),
    ],
    "Model answers. Choose a narrow topic and collect words you can see, hear, feel and do. Build a rhyme bank of rhyming families, then pick the best end words. Draft each line around an end word and read aloud to test the beat. Trim extra words so paired lines have similar length. Use specific verbs and nouns to make pictures. Model poem: 'White lightning cracked the sky with a flash, / Then thunder rolled with a grumbling crash. / The rain came tumbling down the street, / And puddles splashed around my feet.' It uses the AABB scheme with clear images and a steady beat.",
    "1) Make topic webs for three topics. 2) Build rhyme banks for three words. 3) Fill in four lines using given end words. 4) Trim four lines that are too long. 5) Replace weak words with stronger images in four lines. 6) Write and read aloud your own four to eight line poem.",
    "Write a four to eight line rhyming poem with a title. Include your topic web and rhyme bank on the page. Upload a photo.",
    CHECK,
    "Did I choose a clear topic and collect words? Did I make a rhyme bank? Does my poem have a rhyme scheme I can name? Did I read it aloud and fix the beat? Did I use at least two strong pictures? Does it have a title? Is it neat?",
    [
        _q("A rhyme bank is...", ["a list of rhyming words to choose from", "a poem's title", "a kind of paper"], 0, "It gives you end words ready for your lines."),
        _q("Which should you do first?", ["Choose a topic and collect ideas", "Write a title", "Read the poem aloud to an audience"], 0, "Ideas come first."),
        _q("In AABB, which lines rhyme?", ["1 with 2, and 3 with 4", "1 with 3, and 2 with 4", "All four lines"], 0, "AABB pairs neighbouring lines."),
        _q("What is imagery?", ["Language that helps the reader see, hear or feel", "A kind of rhyme", "A list of syllables"], 0, "Imagery creates pictures and senses in the reader's mind."),
        _q("Which line has stronger imagery?", ["The wind howled through the empty street.", "The wind was strong.", "There was wind."], 0, "Howled through the empty street shows sound and place."),
        _q("What is a good way to fix a line that is too long?", ["Cut filler words", "Make it longer", "Remove the end word"], 0, "Trimming keeps the beat steady."),
        _q("Why read your poem aloud?", ["To check the rhyme and beat by ear", "To make it longer", "To hide mistakes"], 0, "Your ear spots lines that do not fit."),
        _q("If a rhyme sounds forced and odd, you should...", ["choose a different end word", "keep it", "stop writing"], 0, "Choose meaning first, then another rhyme."),
    ],
    "Upload a photo of your poem, topic web and rhyme bank.",
    "Read your poem to a family member. Ask them to clap the beat while you read, and fix any line where the clapping gets lost.",
    [("topic", "The subject a poem is about."), ("rhyme bank", "A list of rhyming words collected before drafting."), ("draft", "An early version of writing that can be changed."), ("stanza", "A verse; a group of lines in a poem."), ("imagery", "Descriptive language that creates pictures or senses in the reader's mind."), ("revise", "To improve the meaning or sound of writing.")],
    [
        _video("Writing Poetry for Kids - Episode 6: Rhyming", "5Mrb6wzbWmM",
               "Watch how a rhyming poem is built: choose a topic, find rhyming words and fit them into lines. Pause and name the rhyme scheme of the example, then think of a rhyming pair for your own topic.",
               "If the video does not play, choose a topic and write four rhyming words for it. Use two pairs as the end words of a four-line poem.",
               ("A good way to find a rhyming word is to...", ["run through the alphabet with the ending sound", "pick any word at random", "copy the first line"], 0, "Trying each starting letter with the same ending finds many rhymes.")),
    ],
    _sort("Weak or strong?", "Is each line weak or strong imagery? Tap a group, then Check.",
          ["Weak", "Strong"],
          [("The rain drummed on the tin roof.", 1), ("It was a wet day.", 0), ("Puddles splashed around my feet.", 1), ("The wind was loud.", 0), ("A big dog was there.", 0), ("The old dog trotted to the gate.", 1)]),
    [
        _wc("A list of rhyming words is a rhyme ___.", ["bank", "banc", "bank-"], 0, "Bank has k at the end."),
        _wc("Words that help the reader see are ___.", ["imagery", "imagry", "imagerie"], 0, "Imagery ends -ery."),
        _wc("To improve writing is to ___.", ["revise", "revize", "revice"], 0, "Revise ends -ise."),
        _wc("A group of lines in a poem is a ___.", ["stanza", "stanzer", "stansa"], 0, "Stanza ends -za."),
        _wc("Which is spelt correctly?", ["topic", "topick", "toppic"], 0, "Topic has one p."),
    ],
    [
        {"key": "plan", "label": "Plan", "hint": "A topic web and rhyme bank."},
        {"key": "draft", "label": "Draft", "hint": "Four to eight lines in a named rhyme scheme."},
        {"key": "beat", "label": "Beat fixed", "hint": "Read aloud and adjusted for a steady rhythm."},
        {"key": "pictures", "label": "Strong pictures", "hint": "At least two lines with vivid images."},
    ],
    ["Forcing a rhyme that does not make sense.", "Starting without ideas or a rhyme bank.", "Letting lines in a pair be very different lengths.", "Using weak words when a specific word is available.", "Not reading the poem aloud."],
    [{"title": "Poem Postcard", "description": "Write a four-line rhyming poem on a postcard-sized piece of paper and illustrate it. Read it aloud to someone.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that the poem has a clear topic, a named rhyme scheme with matching lines, a steady beat when read aloud, at least two strong images and a title. Sorter: Strong: rain drummed on tin roof; puddles splashed around feet; old dog trotted to the gate. Weak: it was a wet day; wind was loud; a big dog was there.",
)

B9L3 = build(
    "s2-eng-b9-l3-alliteration-and-onomatopoeia", "Alliteration and Onomatopoeia",
    "Learn two sound devices poets use, repeated starting sounds and words that imitate noises, and use them to make writing come alive.",
    "Language: alliteration and onomatopoeia",
    ["EN2-VOCAB-01", "EN2-CWT-01", "EN2-RECOM-01", "EN2-OLC-01"],
    {"EN2-VOCAB-01": "Primary. Learns and uses alliteration, onomatopoeia, consonant, sound word and sound device.",
     "EN2-CWT-01": "Writes lines and a short poem using alliteration and onomatopoeia purposefully.",
     "EN2-RECOM-01": "Identifies sound devices in poems and explains their effect.",
     "EN2-OLC-01": "Reads sound-rich lines aloud for effect."},
    "We are learning to find and use alliteration and onomatopoeia and to explain what they add to a poem.",
    ["I can explain what alliteration is.", "I can find alliteration by listening to starting sounds.", "I can explain what onomatopoeia is.", "I can say what effect a sound device has.", "I can write lines that use both devices on purpose."],
    ["alliteration", "onomatopoeia", "consonant", "sound word", "sound device", "effect"],
    ["Paper or notebook", "Pencil", "A poem or short text with sound words chosen by your parent"],
    "Child has learned rhyme and rhythm. This lesson teaches two more sound devices that are not about rhyme.",
    "Rhyme is not the only way poets play with sound. Two other devices are ALLITERATION and ONOMATOPOEIA. Both help readers hear a poem inside their heads.\n\nAlliteration repeats the same starting sound in nearby words: 'Peter picked a peck of pickled peppers.' Onomatopoeia uses words that sound like the noise they name: buzz, crash, sizzle, splash.\n\nIn this lesson you will learn how to spot each device, how to explain what it does, and how to use them on purpose rather than just piling them up.",
    [
        _step("1", "What alliteration is",
              "ALLITERATION is the repetition of the same starting SOUND in words that are close together. It usually uses the same consonant sound.\n\nThe sleepy snake slid slowly south.\nBig brown bears bounced by the bay.\n\nWe listen for the SOUND, not just the letter. 'Kind kittens' repeats the k sound. 'Cat' and 'kite' alliterate even though one begins with c and the other with k. 'Phil' and 'fish' also alliterate: the f sound is the same.\n\nA CONSONANT is a speech sound made by blocking or narrowing the air, like b, s, t, m. Vowels are a, e, i, o, u sounds. Alliteration usually uses consonants, but the repeated sound must be at the START of the words.\n\nTwo words are enough to begin. 'Silver sand' alliterates, although 'sand silver' does too.",
              "Alliteration: 'Dark dragons dived down.' The d sound repeats.",
              "Alliteration repeats a starting sound in nearby words.",
              ("Which phrase has alliteration?", ["Wild waves whispered", "Loud thunder crashed", "The big red car"], 0, "Wild waves whispered repeats the w sound.")),
        _step("2", "What alliteration does",
              "Writers use alliteration for effect. It is a tool, not a decoration. Different sounds create different moods.\n\nSoft sounds like s, sh, l, m and w can feel gentle or quiet: 'The soft sea sighed.'\n\nHard sounds like b, d, k, p and t can feel sharp or strong: 'The drum beat down the dusty track.'\n\nRepeated sounds also help us remember things, which is why slogans and tongue twisters use alliteration. They make a line catchy and fun to say.\n\nWhen you meet alliteration in a poem, ask two questions. What sound repeats? What feeling does that sound give? 'Silent, silver snow' feels hushed because the s sounds feel soft.\n\nUse alliteration sparingly. One or two moments in a poem are powerful. A line stuffed with the same sound can feel silly unless silly is what you want.",
              "Effect: 'Crash! The cold, cruel cliff crumbled.' The hard c sound feels sharp.",
              "Soft sounds can calm; hard sounds can sharpen.",
              ("Which sound feels the softest?", ["s in 'soft sea sighed'", "k in 'cracked'", "t in 'tapped'"], 0, "S sounds are gentle and flowing.")),
        _step("3", "What onomatopoeia is",
              "ONOMATOPOEIA (say on-oh-mat-oh-PEE-ah) means a word that imitates the sound it names. We also call these SOUND WORDS.\n\nExamples: buzz, hiss, splash, pop, thud, sizzle, crackle, clang, whoosh, murmur.\n\nThe word sounds like the noise. Bees buzz. Snakes hiss. Rain pitter-patters. Bacon sizzles.\n\nOnomatopoeia is found in poems, stories, comics and everyday speech. 'Boom!' and 'Crash!' are common in action. 'Murmur' and 'whisper' are quieter sound words.\n\nSome onomatopoeia words are verbs (the kettle whistled), some are nouns (a thud), and some are exclamations (Splat!). In writing, you often use them inside normal sentences.\n\nThe word is long, so learn it in parts: ono-mato-poeia. You will not need to spell it from memory in this lesson, but you should recognise it.",
              "Sound words: 'The fire crackled, the logs popped and the wind whooshed down the chimney.'",
              "Onomatopoeia words sound like the noise they describe.",
              ("Which word is onomatopoeia?", ["sizzle", "table", "pencil"], 0, "Sizzle sounds like the noise it names.")),
        _step("4", "What onomatopoeia does",
              "Onomatopoeia puts sound into the reader's ears. It makes a scene feel real and alive.\n\nCompare: 'The rain fell on the roof.' with 'The rain pattered on the roof.' The second uses a sound word, so we can hear the rain.\n\nSound words can also show mood. A loud crash suggests danger. A soft murmur suggests calm. Sharp sounds like snap and crack often feel tense. Smooth sounds like hum and purr often feel peaceful.\n\nWhere to use onomatopoeia: choose key moments where sound matters. Do not write a sound word every few words. And choose precise ones: 'thud' is not the same as 'thump', and 'splash' is different from 'plop'.\n\nYou can combine onomatopoeia with alliteration: 'The bubbling brook babbled and burbled.' Both devices are working together.",
              "Effect: 'The door creaked' tells us the door is old and the scene is eerie.",
              "Use sound words to let readers hear the scene.",
              ("Which sentence lets you hear the scene most clearly?", ["The tap dripped, plink, plink, plink.", "The tap was on.", "There was a tap."], 0, "Plink is a sound word that lets you hear the drip.")),
        _step("5", "Find them in a poem",
              "Now practise finding both devices in real text. Work in this order with a short poem or paragraph your parent chooses.\n\n1. Read it aloud once, slowly.\n2. Underline any sound words in one colour.\n3. Circle any groups of words that start with the same sound in another colour.\n4. Write each one in a table: Device, Words, Effect.\n\nExample table:\nOnomatopoeia | sizzled | lets us hear the frying pan.\nAlliteration | bright, bubbling brook | the b sound feels bouncy and cheerful.\n\nWhen you write the effect, do more than say 'it sounds good'. Say what you hear or feel: 'The hissing and whispering s sounds make the snake feel sneaky.'\n\nIf you cannot find alliteration, check the beginnings of words close together. Remember: sounds count, not just letters.",
              "Effect sentence: 'The crash of the cymbals makes the scene feel loud and exciting.'",
              "Find the device, then say what it does.",
              ("An effect sentence should...", ["say what the device makes you hear or feel", "only name the device", "copy the poem"], 0, "Effect means the impact on the reader.")),
        _step("6", "Write with sound",
              "Now use both devices on purpose.\n\n1. Write four alliteration lines about a place, animal or weather. Each line needs at least three words starting with the same sound. Model: 'Sleepy sheep strolled slowly.'\n2. Write four sentences that use a different onomatopoeia word each. Model: 'The bike chain clanked as we rattled over the bridge.'\n3. Write a six to eight line poem about a busy place such as a kitchen, a market, a storm or a train station. Use at least two alliteration moments and at least three sound words.\n4. Underline your sound words and circle your alliteration.\n5. Read the poem aloud and check the sounds sound right.\n\nModel poem start:\nMarket Morning\nWheels rumble, voices hum,\nBananas bounce in bright blue boxes.\nA coin clinks, a bell dings,\nAnd the crowd crackles with chatter.\n\nYour poem can rhyme or not; this lesson is about sound.",
              "Check: 'Wheels rumble' uses onomatopoeia, and 'bananas bounce in bright blue boxes' uses alliteration.",
              "Use sound devices in key places, then underline and circle them.",
              ("What should you do after writing your poem?", ["Mark the devices and read it aloud", "Throw it away", "Only read the title"], 0, "Marking and reading aloud checks the sounds work.")),
    ],
    "Model answers. Alliteration repeats the starting sound in nearby words, such as 'big brown bears bounced'. Onomatopoeia words imitate the sound they name, such as buzz and sizzle. Soft sounds can calm and hard sounds can sharpen the mood. Sound words let readers hear the scene. In a table, record the device, the words and the effect. Your poem should have four alliteration lines, four sound-word sentences and a six to eight line poem with at least two alliteration moments and three sound words, marked and read aloud.",
    "1) Sort twelve phrases into alliteration or not. 2) Underline the repeated sound in six alliterative lines. 3) Sort twelve words into onomatopoeia or not. 4) Make a device table for a parent-chosen poem. 5) Write four alliteration lines and four sound-word sentences. 6) Write and mark a six to eight line poem about a busy place.",
    "Upload a photo of your alliteration lines, sound-word sentences and the marked poem.",
    CHECK,
    "Does each alliteration line repeat a starting sound? Did I use a different sound word in each sentence? Does my poem have at least two alliteration moments and three sound words? Did I mark them? Did I read the poem aloud?",
    [
        _q("Alliteration is the repetition of...", ["a starting sound", "an ending sound", "a whole sentence"], 0, "Alliteration repeats the starting sound in nearby words."),
        _q("Which has alliteration?", ["Sam saw seven silver ships", "The cat sat on the mat", "Rain fell all night"], 0, "Sam saw seven silver ships repeats the s sound."),
        _q("Onomatopoeia words...", ["sound like the noise they name", "always rhyme", "are always long"], 0, "The word imitates the sound."),
        _q("Which is onomatopoeia?", ["splash", "gentle", "purple"], 0, "Splash sounds like the noise of water."),
        _q("Do cat and kite alliterate?", ["Yes, they start with the same sound", "No, the letters differ", "Only in a poem"], 0, "The sound is the same even though the letter is not."),
        _q("What do hard sounds like k and t often feel?", ["sharp or strong", "gentle", "silent"], 0, "Hard sounds can sharpen the mood."),
        _q("Why use sound words sparingly?", ["So they stand out at key moments", "Because they are banned", "Because they do not matter"], 0, "Too many sound words can lose their effect."),
        _q("A good effect sentence says...", ["what the sound makes you hear or feel", "only the device name", "the poem's length"], 0, "Effect means the impact on the reader."),
    ],
    "Upload a photo of your sound lines and marked poem.",
    "With a parent, collect ten sound words you hear in one day at home or outside. Write each in a sentence.",
    [("alliteration", "Repeating the same starting sound in words close together."), ("onomatopoeia", "A word that sounds like the noise it names."), ("consonant", "A speech sound made by blocking or narrowing the air, such as b, s or t."), ("sound word", "Another name for an onomatopoeia word, such as buzz or crash."), ("sound device", "A technique a writer uses to play with sound, such as rhyme or alliteration."), ("effect", "What a technique makes the reader hear, see or feel.")],
    [
        _video("Alliteration and Onomatopoeia Explained for Kids", "GYIVwQdlmiw",
               "Listen for what alliteration and onomatopoeia mean and how each one sounds. Pause and say one example of each, then think of a sound word you could use in your own poem.",
               "If the video does not play, write one alliteration line and one sentence with a sound word, then read both aloud.",
               ("A word that sounds like the noise it names is...", ["onomatopoeia", "alliteration", "a verse"], 0, "Onomatopoeia words imitate sounds, such as buzz and splash.")),
    ],
    _sort("Sound device", "Which device is shown in each phrase? Tap a group, then Check.",
          ["Alliteration", "Onomatopoeia"],
          [("sizzle and pop", 1), ("big brown bears", 0), ("clang, clang, clang", 1), ("slippery slimy slugs", 0), ("whoosh went the wind", 1), ("tiny tigers tiptoed", 0), ("the kettle hissed", 1), ("wild white waves", 0)]),
    [
        _wc("Repeating starting sounds is ___.", ["alliteration", "aliteration", "alitteration"], 0, "Alliteration has double l."),
        _wc("A word that sounds like a noise is ___.", ["onomatopoeia", "onomatopeia", "onamatopoeia"], 0, "Onomatopoeia has -poeia at the end."),
        _wc("A speech sound like b or s is a ___.", ["consonant", "consonent", "consanant"], 0, "Consonant ends -ant."),
        _wc("What a technique makes you feel is its ___.", ["effect", "affect", "efect"], 0, "Effect with e is the noun here."),
        _wc("Which is spelt correctly?", ["device", "devise", "divice"], 0, "The noun device ends -ice."),
    ],
    [
        {"key": "allit", "label": "Alliteration", "hint": "Four lines repeating a starting sound."},
        {"key": "sound", "label": "Sound words", "hint": "Four sentences with different onomatopoeia words."},
        {"key": "table", "label": "Device table", "hint": "Device, words and effect recorded for a poem."},
        {"key": "poem", "label": "Sound poem", "hint": "A six to eight line poem with both devices marked."},
    ],
    ["Judging alliteration by letters instead of sounds.", "Using a sound word that does not really sound like the noise.", "Stuffing every line with devices.", "Writing 'it sounds good' instead of explaining the effect.", "Forgetting to read the poem aloud."],
    [{"title": "Sound Collector", "description": "Keep a list for a day of ten sound words you hear. Write a short poem using at least five of them.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that alliteration lines repeat a starting sound in at least three words, each sound-word sentence uses a different onomatopoeia word, the table states clear effects, and the poem has at least two alliteration moments and three sound words. Sorter: Alliteration: big brown bears; slippery slimy slugs; tiny tigers tiptoed; wild white waves. Onomatopoeia: sizzle and pop; clang clang clang; whoosh went the wind; the kettle hissed.",
)

B9L4 = build(
    "s2-eng-b9-l4-spelling-homophones", "Spelling: Homophones",
    "Learn what homophones are, why spelling them by sound alone does not work, and how to choose the right one by meaning.",
    "Spelling: homophones",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-CWT-01"],
    {"EN2-SPELL-01": "Primary. Spells and chooses between common homophones using meaning and memory strategies.",
     "EN2-VOCAB-01": "Learns homophone, meaning, context, spelling strategy and common homophone pairs.",
     "EN2-CWT-01": "Uses homophones accurately in sentences and in proofreading."},
    "We are learning to choose the right spelling for words that sound the same but mean different things.",
    ["I can explain what a homophone is.", "I can use meaning to choose between homophones.", "I can make a memory trick for a hard pair.", "I can spell six common homophone pairs.", "I can proofread a paragraph for homophone mistakes."],
    ["homophone", "meaning", "context", "strategy", "proofread", "pair"],
    ["Paper or notebook", "Pencil", "A dictionary with parent help"],
    "Child has learned spelling strategies and common tricky words. This lesson focuses on sound-alike words that need meaning to be spelt correctly.",
    "English has many words that sound exactly the same but are spelt differently and mean different things. These are called HOMOPHONES. 'Homo' means same and 'phone' means sound, so a homophone is a same-sound word.\n\nExamples: sea and see, flour and flower, ate and eight.\n\nSpell-check on a computer will not always catch a homophone mistake, because both spellings are real words. 'I want too go to the see' has real words but wrong spellings. Only your understanding of the sentence can tell which one fits.\n\nThis lesson teaches you to choose by meaning, make memory tricks for hard pairs, learn a core set, and proofread for these slips.",
    [
        _step("1", "What homophones are",
              "A HOMOPHONE is a word that sounds the same as another word but has a different spelling and a different meaning.\n\nsea (the ocean) / see (to look)\nflour (used for baking) / flower (a plant that blooms)\nmeet (come together) / meat (food)\nsun (the star) / son (a boy child)\n\nBecause they sound alike, you cannot tell which to write by listening. You must think about the meaning.\n\nThere are many homophone pairs, and some come in groups of three: to, too, two; there, their, they're. Each word in the group has a different job.\n\nWhen you read a homophone, you rely on the sentence to understand it. When you write it, you must choose the right spelling yourself.",
              "Pairs: 'I can see the sea.' See means look; sea means ocean.",
              "Same sound, different spelling and meaning.",
              ("Which pair are homophones?", ["meet, meat", "cat, bat", "big, large"], 0, "Meet and meat sound the same but mean different things.")),
        _step("2", "Choose by meaning",
              "To choose the right homophone, ask: What do I mean here? Then match the meaning to the spelling.\n\nSentence: 'The ___ shone brightly.' Do I mean the star in the sky or a boy child? The star: sun.\n\nSentence: 'My ___ plays football.' A boy child: son.\n\nTest by replacing with a meaning word. 'Their' means belonging to them, so you can say 'belonging to them' in its place. 'They're' means they are. 'There' means in that place.\n\nRead the whole sentence before choosing. Look at the words around the gap: they are clues. 'Plant a ___ in the garden' needs flower, not flour.\n\nIf you are not sure, check a dictionary. Look up each word and read its meaning.",
              "Test: 'I ate eight biscuits.' Ate is the verb; eight is the number.",
              "Read the sentence and match the meaning.",
              ("Which word completes 'Plant a ___ in the garden'?", ["flower", "flour", "flowr"], 0, "A flower grows in a garden.")),
        _step("3", "Memory tricks",
              "For a hard pair, make a MNEMONIC: a short trick that links the spelling to the meaning.\n\nPiece of PIE: a piece of a cake or pie is spelt piece, with ie.\nYou HEAR with your EAR: hear has ear inside it. here is a place, like there and where.\nThe SEA has EA like ocean waves rolling: sea is the ocean. You SEE with two EEs, like two eyes: see.\nStationERY has an ER, like an envelope: paper. StationARY has an A, like stand still: not moving.\nA PRINCIPAL is your PAL; a PRINCIPLE is a rule.\n\nMake your own trick. The best tricks are silly or personal because they stick in your mind.\n\nWrite the trick next to the word on a card. Practise using it, and the trick will fade when the spelling is automatic.",
              "Trick: 'dessert' has two s because you want seconds; 'desert' has one s, like sand.",
              "Link the spelling to the meaning with a trick.",
              ("Which trick helps you spell 'hear'?", ["You hear with your ear", "Hear has two a letters", "Hear rhymes with bear"], 0, "The word ear is inside hear.")),
        _step("4", "Learn this week's pairs",
              "Learn these twelve words (six pairs): hear/here, new/knew, whole/hole, write/right, which/witch, weather/whether.\n\nhear: to listen with your ears. here: in this place.\nnew: not old. knew: past of know.\nwhole: all of something. hole: a gap or pit.\nwrite: put words on paper. right: correct, or the opposite of left.\nwhich: asks about a choice. witch: a person with magic.\nweather: rain, wind or sun. whether: if.\n\nThey look tricky because of silent letters (knew, write, whole, witch). Notice the silent letters: k in knew, w in write, w in whole, t in witch.\n\nMake a card for each: the word, the meaning, a sentence and, if useful, a memory trick. Use look, say, cover, write, check on the ones you miss.",
              "Sentence: 'I knew the new rule when I read it right here.' (knew, new, right, here)",
              "Learn pairs with meaning, sentence and trick.",
              ("Which word means 'all of something'?", ["whole", "hole", "hoal"], 0, "Whole means complete; hole means a gap.")),
        _step("5", "Proofread for homophones",
              "Spell-check cannot catch a homophone mistake, so you must read for meaning. Use this proofreading method.\n\n1. Read the paragraph slowly, one sentence at a time.\n2. For every homophone, say its meaning in your head.\n3. Ask: does this spelling match the meaning?\n4. Circle any you doubt and check by meaning, a dictionary or a trick.\n5. Read again.\n\nExample with mistakes: 'I knew the weather would change, so I ware my raincoat and hurd the thunder.'\nHere, 'ware' should be 'wore' (past of wear) and 'hurd' should be 'heard'. Even correct-looking words like 'knew' and 'weather' are checked.\n\nCheck common pairs especially: to/too/two, there/their/they're, your/you're, its/it's, no/know, one/won.\n\nOne careful read of each sentence is worth more than three fast ones.",
              "Spot: 'I want to go to, to.' Fix: 'I want to go too.'",
              "Read for meaning: does this spelling fit the sentence?",
              ("Why can spell-check miss homophone errors?", ["Both spellings are real words", "It is always wrong", "It cannot read"], 0, "A real word in the wrong place looks fine to a spell-checker.")),
        _step("6", "Practise and use them",
              "Put this week's pairs to work.\n\n1. Choose the correct spelling for ten sentences, saying the meaning each time.\n2. Make a card for each pair: word, meaning, sentence and memory trick for the hard ones.\n3. Use look, say, cover, write, check on three pairs you find hardest.\n4. Ask a parent to say ten sentences. Write each homophone from memory, then check the meaning together.\n5. Proofread the paragraph below for four homophone mistakes: 'The whole class wrote there names. I new witch one was mine, so I rote it write hear.' (Find them: whole is correct; there should be their; new should be knew; witch should be which; rote should be wrote; write should be right; hear should be here.)\n6. Write four sentences of your own, each using a different pair correctly.\n\nModel: 'I knew the weather was changing, so I wrote a note to my whole family.'",
              "Correct sentence: 'Their new neighbours knew which weather to expect.'",
              "Use meaning, practise from memory, then proofread.",
              ("What should you do before choosing a homophone?", ["Think about the meaning in the sentence", "Pick the first one you see", "Spell it by sound only"], 0, "Meaning tells you which spelling is correct.")),
    ],
    "Model answers. A homophone sounds the same as another word but has a different spelling and meaning. Choose by meaning: sea (ocean) and see (look); flour and flower; meet and meat. Memory tricks link spelling to meaning, such as 'you hear with your ear'. This week's pairs are hear/here, new/knew, whole/hole, write/right, which/witch and weather/whether. Proofreading answers: their, knew, which, wrote, right, here. Spell-check cannot catch homophone mistakes because both spellings are real words.",
    "1) Choose the right homophone for ten sentences. 2) Make cards for six pairs. 3) Make a memory trick for two hard pairs. 4) Practise three pairs with look, say, cover, write, check. 5) Complete a ten-sentence parent dictation. 6) Proofread a paragraph and write four sentences of your own.",
    "Make six homophone cards, complete the ten-sentence dictation and proofread the paragraph. Upload a photo of your work.",
    CHECK,
    "Did I choose by meaning? Did I make a card for each pair? Did I make a memory trick for hard pairs? Did I practise from memory? Did I proofread each sentence slowly? Did my own sentences use the pairs correctly?",
    [
        _q("A homophone is a word that...", ["sounds like another word but is spelt differently", "means the same as another word", "rhymes with a word"], 0, "Homophones share a sound but differ in spelling and meaning."),
        _q("Which word means 'in this place'?", ["here", "hear", "heer"], 0, "Here is a place word."),
        _q("Which word means 'not old'?", ["new", "knew", "nue"], 0, "New means recently made."),
        _q("Which completes 'I ___ the answer'?", ["knew", "new", "nu"], 0, "Knew is the past tense of know."),
        _q("Which means 'a gap or pit'?", ["hole", "whole", "hoal"], 0, "Hole means a gap; whole means all."),
        _q("Which completes 'Please ___ your name'?", ["write", "right", "rite"], 0, "Write means put words on paper."),
        _q("Which completes '___ one is yours?'", ["Which", "Witch", "Wich"], 0, "Which asks about a choice."),
        _q("Why can spell-check miss a homophone mistake?", ["Both words are real words", "It only checks capitals", "It cannot see letters"], 0, "A real word in the wrong place passes the spell-check."),
    ],
    "Upload a photo of your homophone cards, dictation and proofread paragraph.",
    "Ask a parent for three more homophone pairs. Look each up in a dictionary and write a sentence for each word.",
    [("homophone", "A word that sounds like another word but has a different spelling and meaning."), ("meaning", "What a word or sentence tells you."), ("context", "The words around a word that help show its meaning."), ("strategy", "A plan or method for doing something well."), ("proofread", "To read slowly and check for small mistakes."), ("pair", "Two things that go together, such as two homophones.")],
    [
        _video("Homophones for Kids: Grammar for Elementary Students", "rQuWqcVzqUU",
               "Listen for what a homophone is and how the same sound can have different spellings and meanings. This video uses simple examples such as nose and knows, and eight and ate. Pause and say which spelling you would use in a sentence of your own.",
               "If the video does not play, write three homophone pairs and a sentence for each word.",
               ("Homophones are words that...", ["sound the same but have different meanings and spellings", "look the same and sound different", "mean the same thing"], 0, "Homophones share a sound but not a spelling or meaning.")),
        _video("Homophones for Kids (Luke and Rover)", "f9fy4NREF-E",
               "Watch the pairs of words that sound the same and say each pair aloud. Listen for any of this week's pairs, such as hear and here, or write and right, and pause to say which meaning goes with which spelling.",
               "If the video does not play, say each of this week's six pairs aloud and give a short meaning for each word.",
               ("To choose between homophones you should think about...", ["the meaning in the sentence", "only how the word sounds", "how long the word is"], 0, "The meaning tells you which spelling fits.")),
    ],
    _sort("Choose by meaning", "Which spelling fits each meaning? Tap a group, then Check.",
          ["hear", "here"],
          [("listen with your ears", 0), ("in this place", 1), ("I can ___ the music", 0), ("Come over ___", 1), ("Did you ___ that sound?", 0), ("Put it ___ on the table", 1)]),
    [
        _wc("Which is spelt correctly?", ["whole", "hole", "hoal"], 0, "Whole means all of something."),
        _wc("Which is spelt correctly?", ["weather", "wether", "wheather"], 0, "Weather has ea."),
        _wc("Which is spelt correctly?", ["homophone", "homofone", "homophon"], 0, "Homophone has ph."),
        _wc("Which is spelt correctly?", ["which", "wich", "whitch"], 0, "Which begins wh."),
        _wc("Which is spelt correctly?", ["knew", "new", "gnew"], 0, "Knew has a silent k and means past of know."),
    ],
    [
        {"key": "choose", "label": "Choose by meaning", "hint": "Ten sentences completed correctly."},
        {"key": "cards", "label": "Homophone cards", "hint": "Six pairs with meanings and sentences."},
        {"key": "dictation", "label": "Parent dictation", "hint": "Ten sentences written from memory."},
        {"key": "proof", "label": "Proofread", "hint": "A paragraph checked for homophone mistakes."},
    ],
    ["Choosing by sound instead of meaning.", "Trusting spell-check to find homophone errors.", "Not reading the whole sentence before choosing.", "Mixing up there, their and they're.", "Forgetting silent letters in knew, write and whole."],
    [{"title": "Homophone Story", "description": "Write a short story using six homophone pairs correctly. Underline each homophone and write its meaning below.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that each homophone is chosen by meaning, cards show word, meaning and sentence, memory tricks link spelling and meaning, dictation answers are corrected and the proofread paragraph is fixed. Sorter: hear: listen with your ears; I can hear the music; Did you hear that sound. here: in this place; Come over here; Put it here on the table.",
)

LESSONS = [B9L1, B9L2, B9L3, B9L4]
