"""Stage 2 Maths, Week 2, Lesson 3 of 3: decimals (MA2-RWN-02).
Completes Week 2. Loaded automatically by _register_maths in lesson_library.py. Videos are attached in a later pass."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from lesson_library_s2_maths_w1 import _maths

M3 = _maths(build(
    "s2-math-w02-l3-decimals-tenths-hundredths", "Decimals: Tenths and Hundredths",
    "Deep in the Treasure Vault, the gold is weighed in tiny pieces. Learn tenths and hundredths so you can read every weight exactly.",
    "Number: decimals and place value",
    ["MA2-RWN-02"],
    {"MA2-RWN-02": "Primary. Represents, reads and compares decimals to 2 decimal places using tenths and hundredths, linked to money."},
    "We are learning to read, write and compare decimals with tenths and hundredths.",
    ["I can say that a tenth is one of ten equal parts.", "I can say that a hundredth is one of one hundred equal parts.", "I can read and write decimals such as 0.7 and 0.35.", "I can say what each digit is worth in a decimal.", "I can compare and order decimals."],
    ["decimal", "decimal point", "tenth", "hundredth", "place value", "compare", "order"],
    ["Paper or notebook", "Pencil", "Coins (optional)", "Ruler marked in millimetres (optional)"],
    "Child knows place value to hundreds and the idea of halves and quarters.",
    "A dollar is split into 100 cents. So one cent is one hundredth of a dollar, and 25 cents is $0.25. Money is a decimal you already use!\n\nA decimal is a way to write numbers that are smaller than a whole. The dot is called the DECIMAL POINT. Digits to the left are whole numbers. Digits to the right are parts of a whole. In this lesson you will learn tenths and hundredths, then compare decimals.",
    [
        _step("1", "Tenths",
              "Cut one whole into 10 equal parts. Each part is one TENTH. We write one tenth as 0.1 or 1/10.\n\n3 of the 10 parts is three tenths, written 0.3. All 10 parts make one whole, written 1.0.\n\nThe first digit after the decimal point is the tenths place.",
              "0.7 is 7 tenths. A ruler marked in centimetres shows tenths: each 1 mm is one tenth of 1 cm.",
              "The first digit after the point counts tenths.",
              ("Which decimal means 7 tenths?", ["0.07", "0.7", "7.0"], 1, "7 tenths is 0.7.")),
        _step("2", "Hundredths",
              "Cut one whole into 100 equal parts. Each part is one HUNDREDTH, written 0.01 or 1/100.\n\n9 hundredths is 0.09. The second digit after the decimal point is the hundredths place.\n\nMoney helps: 100 cents make $1, so 5 cents is $0.05 and 75 cents is $0.75.",
              "0.25 is 2 tenths and 5 hundredths, which is the same as 25 hundredths. 25 cents is $0.25.",
              "The second digit after the point counts hundredths.",
              ("Which decimal means 9 hundredths?", ["0.9", "0.09", "9.0"], 1, "9 hundredths is 0.09.")),
        _step("3", "Decimal place value",
              "Every digit has a value that depends on its place. In 3.47: the 3 is 3 ones, the 4 is 4 tenths (0.4) and the 7 is 7 hundredths (0.07).\n\nWe can write 3.47 = 3 + 0.4 + 0.07.\n\nZero holds a place. In 5.08 there are 0 tenths, so the 8 is 8 hundredths, not 8 tenths.",
              "In 4.63 the 6 is worth 0.6 and the 3 is worth 0.03.",
              "Say the place name for each digit, then write its value.",
              ("In 4.63, what is the digit 6 worth?", ["6", "0.6", "0.06"], 1, "The 6 is in the tenths place, so it is 6 tenths, 0.6.")),
        _step("4", "Comparing and ordering",
              "To compare decimals, start at the biggest place. Compare the ones first, then the tenths, then the hundredths.\n\nWrite both numbers with the same number of decimal places. 0.5 becomes 0.50. Now compare 0.50 and 0.45: 50 hundredths is more than 45 hundredths, so 0.5 > 0.45.\n\nA longer decimal is not always bigger. 0.45 has more digits than 0.5, but it is smaller.",
              "Order 0.3, 0.03 and 0.33: write 0.30, 0.03, 0.33. Smallest to greatest is 0.03, 0.3, 0.33.",
              "Add a zero so both have two decimal places, then compare.",
              ("Which is the greatest?", ["0.35", "0.4", "0.09"], 1, "0.4 is 0.40, which is more than 0.35.")),
    ],
    "Problem: Which is bigger, 0.5 or 0.45? Ones are both 0. Write 0.5 as 0.50. Compare tenths: 5 tenths is more than 4 tenths. So 0.50 > 0.45 and 0.5 > 0.45. Check with money: 50 cents is more than 45 cents.",
    "Work in your notebook. Part A: write as decimals: 3 tenths, 8 tenths, 4 hundredths, 7 hundredths. Part B: write 2.35 as ones, tenths and hundredths. Part C: write > or < for 0.6 and 0.59, for 0.08 and 0.1, and for 1.25 and 1.3. Part D: order from smallest to greatest: 0.45, 0.5, 0.05, 0.54. Part E: write as dollars: 75c, 5c, 120c.",
    "Stage 1 (make): draw a 10 by 10 grid for 100 hundredths and shade 0.35.\nStage 2 (record): write 0.35 as tenths and hundredths, and as money.\nStage 3 (compare): shade 0.4 on a second grid and compare it with 0.35.\nStage 4 (story): write a shopping story using three prices to compare.",
    "Write the answers in your notebook and say one place value aloud.",
    "Did I shade the grids? Did I write 0.35 as tenths and hundredths? Did I compare using the same number of decimal places? Did I write a story?",
    [
        _q("Which decimal is 7 tenths?", ["0.07", "0.7", "7.0"], 1, "7 tenths is 0.7."),
        _q("Which decimal is 9 hundredths?", ["0.9", "0.09", "9.0"], 1, "9 hundredths is 0.09."),
        _q("In 4.63, what is the digit 6 worth?", ["6", "0.6", "0.06"], 1, "Tenths place."),
        _q("In 4.63, what is the digit 3 worth?", ["3", "0.3", "0.03"], 2, "Hundredths place."),
        _q("Which is the greatest?", ["0.7", "0.65", "0.09"], 0, "0.7 is 0.70, more than 0.65."),
        _q("Which is the smallest?", ["0.4", "0.35", "0.08"], 2, "0.08 has no tenths."),
        _q("25 cents is written as ___.", ["$2.50", "$0.25", "$25.00"], 1, "25 hundredths of a dollar."),
        _q("0.5 is the same as ___.", ["0.05", "0.50", "5.0"], 1, "Adding a zero at the end does not change the value."),
        _q("One whole cut into 100 equal parts gives ___.", ["tenths", "hundredths", "halves"], 1, "100 parts are hundredths."),
        _q("Order smallest to greatest: 0.3, 0.03, 0.33", ["0.03, 0.3, 0.33", "0.3, 0.03, 0.33", "0.33, 0.3, 0.03"], 0, "0.03 < 0.30 < 0.33."),
    ],
    "Upload a photo of your shaded grids, place value work and shopping story.",
    "Find a decimal between 0.3 and 0.4 and show how you know it is between them.",
    [("decimal", "A number with a part smaller than one whole, shown with a point."), ("decimal point", "The dot that separates whole numbers from parts."), ("tenth", "One of ten equal parts."),
     ("hundredth", "One of one hundred equal parts."), ("place value", "The value a digit has because of where it is."), ("compare", "To decide which is greater or less."), ("order", "To arrange from smallest to greatest or the reverse.")],
    [],
    _sort("Tenths or hundredths?", "What do the digits show? Tap a group, then press Check.",
          ["Tenths only", "Hundredths only", "Tenths and hundredths"],
          [("0.4", 0), ("0.8", 0), ("0.6", 0), ("0.03", 1), ("0.07", 1), ("0.09", 1), ("0.25", 2), ("0.62", 2), ("0.91", 2)]),
    [
        _wc("A number with a point, like 0.5, is a ___.", ["decimal", "decimel", "desimal"], 0, "Decimal starts with dec."),
        _wc("One of one hundred equal parts is a ___.", ["hundredth", "hundreth", "hundered"], 0, "Hundredth has red."),
        _wc("To arrange numbers smallest to greatest is to ___ them.", ["order", "ordar", "ordir"], 0, "Order ends er."),
    ],
    [
        {"key": "g", "label": "Shaded grids", "hint": "Photograph both hundred grids."},
        {"key": "p", "label": "Place value", "hint": "Write 0.35 as tenths and hundredths."},
        {"key": "s", "label": "Shopping story", "hint": "Compare three prices."},
    ],
    ["Thinking 0.45 is bigger than 0.5 because 45 is bigger than 5.", "Reading 0.05 as five tenths.", "Forgetting that a zero holds a place.", "Writing 5 cents as $0.5.", "Ignoring the decimal point when comparing."],
    [{"title": "Price Detective", "description": "Find five prices in a catalogue or online shop. Write them as decimals, order them smallest to greatest, and say which digit is the tenths and which is the hundredths.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 0.3, 0.8, 0.04, 0.07. Part B: 2 ones, 3 tenths, 5 hundredths. Part C: 0.6 > 0.59; 0.08 < 0.1; 1.25 < 1.3. Part D: 0.05, 0.45, 0.5, 0.54. Part E: $0.75, $0.05, $1.20.",
), "Use money first: 100 cents in a dollar makes hundredths concrete. Ask him to say each digit's place name before comparing.")

WEEK_2_MATHS_B = [M3]
