"""Stage 2 English, Week 4 Lesson 3: Conjunctions and Complex Sentences (Language).
All written work is typed inside the lesson. Spelling (prefixes un-, re-, dis-, mis-) continues with new words.
No video is attached: none has been verified for this topic yet. Add one in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from spelling_s2_w1 import _w, _c

WORDS = ["unable", "unlucky", "reheat", "reuse", "disappear", "misplace"]

MODEL = (
    "The Lost Library Book\n\n"
    "Short sentences: Ella lost her library book. She searched her room. She searched the car. She did not find it.\n\n"
    "Joined sentences: Ella lost her library book, so she searched her room and the car. Although she looked everywhere, she did not find it. "
    "She was about to give up when she heard a rustle under the sofa cushion. Because the cushion had slipped, the book had been hiding there all along. "
    "Ella grinned and hugged it, but she promised herself she would use a bookmark next time."
)

LESSON = build(
    "s2-eng-w04-l3-conjunctions-complex-sentences",
    "Conjunctions and Complex Sentences",
    "Learn how conjunctions join ideas to make sentences that flow. Practise joining short sentences with and, but, so, because, when, although, if and while, and learn where to put the comma.",
    "Language: conjunctions and sentence structure",
    ["EN2-VOCAB-01", "EN2-CWT-01", "EN2-SPELL-01"],
    {
        "EN2-VOCAB-01": "Primary. Identifies and uses conjunctions to join clauses, and understands how they show addition, contrast, cause, time and condition.",
        "EN2-CWT-01": "Uses compound and complex sentences with correct punctuation to improve the flow and clarity of imaginative writing.",
        "EN2-SPELL-01": "Spells words with the prefixes un-, re-, dis- and mis-, keeping the base word unchanged (week 4 spelling focus).",
    },
    "We are learning to join sentences using conjunctions, to choose the right one for the meaning, and to punctuate complex sentences.",
    ["I can explain what a conjunction does.", "I can use and, but, so and or to join equal ideas.", "I can use because, when, although, if, while and after to add extra information.", "I can put a comma after a starting 'although', 'when' or 'because' clause.", "I can combine short sentences into longer ones that make sense.", "I can spell words with the prefixes un-, re-, dis- and mis-."],
    ["conjunction", "clause", "compound sentence", "complex sentence", "main clause", "subordinate clause", "comma", "prefix"],
    ["This lesson (everything you need is inside it)"],
    "Child can identify nouns, verbs and adjectives and write complete sentences with capitals and full stops (Weeks 1 and 2).",
    (
        "Why this matters. Writing made only of short sentences sounds choppy, like a robot: 'I woke up. I ate. I went out.' Conjunctions are joining words that connect ideas, show how they are related and make writing flow. Using them well also helps you give reasons, show contrast and say when things happen.\n\n"
        "What is a conjunction? A conjunction is a word that joins words, phrases or clauses. A clause is a group of words with a subject and a verb. Today we focus on joining clauses.\n\n"
        "Joining equal ideas. And, but, so and or join two main clauses of equal importance, and each part could stand alone as a sentence. A comma usually goes before the conjunction. 'It was raining, so we stayed inside.' And adds, but shows contrast, so shows result and or shows a choice.\n\n"
        "Adding extra information. Because, when, although, if, while, after, before and until begin a clause that cannot stand alone, called a subordinate clause. It depends on a main clause to make sense. 'We stayed inside because it was raining.' Because gives a reason, when and while and after and before give time, although gives contrast and if gives a condition.\n\n"
        "Where does the comma go? If the sentence starts with the conjunction, put a comma after the subordinate clause: 'Although it was late, we kept playing.' If the conjunction is in the middle, you usually do not need a comma: 'We kept playing although it was late.'\n\n"
        "Choosing well. Pick the conjunction that matches the meaning. 'I was tired, but I kept going' shows contrast. 'I was tired, so I went to bed' shows result. The wrong one changes the meaning or makes it silly. Avoid chains of and then and then, and do not overuse one conjunction.\n\n"
        "Spelling focus. Continue with the prefixes un-, re-, dis- and mis-. Add the prefix to the whole base word: unable, unlucky, reheat, reuse, disappear, misplace."
    ),
    [
        _step("1", "What a conjunction does", "A conjunction is a joining word. It connects words, phrases or clauses and shows how the ideas are related.\n\nWithout conjunctions, writing sounds choppy.", "Choppy: I was hungry. I made a sandwich. Joined: I was hungry, so I made a sandwich.", "Conjunctions join ideas and show how they relate.", ("A conjunction is...", ["A joining word", "A describing word", "A doing word"], 0, "It joins words or clauses.")),
        _step("2", "And, but, so, or", "These join two equal clauses. Use a comma before the conjunction. And adds, but shows contrast, so shows result and or shows a choice.\n\nEach clause could stand alone.", "I wanted to play outside, but it was raining. It was raining, so we stayed in.", "Join equal ideas with and, but, so or or.", ("Which shows contrast?", ["but", "and", "so"], 0, "But shows two ideas that work against each other.")),
        _step("3", "Because, when, if, while, although", "These start a subordinate clause that cannot stand alone. Because gives a reason, when and while show time, if shows a condition and although shows contrast.\n\nThe clause needs a main clause to make sense.", "We stayed inside because it was raining. Although it was cold, we went swimming.", "The extra clause needs a main clause.", ("Which word gives a reason?", ["because", "but", "or"], 0, "Because explains why.")),
        _step("4", "Commas in complex sentences", "If the sentence starts with the subordinate clause, put a comma after it. If the subordinate clause is at the end, you usually do not need one.\n\nRead it aloud and listen for the pause.", "Although it was late, we kept playing. We kept playing although it was late.", "Starting clause, then a comma.", ("Which is punctuated correctly?", ["When the bell rang, we ran outside.", "When the bell rang we ran, outside.", "When, the bell rang we ran outside."], 0, "A comma follows the starting clause.")),
        _step("5", "Choose the right conjunction", "Think about what the sentence is meant to say: addition, contrast, reason, result, time or condition. Then choose the conjunction that fits.\n\nThe wrong one changes the meaning.", "I was tired ___ I kept running. (but, because) 'But' fits because the two ideas contrast.", "Match the conjunction to the meaning.", ("Which fits? 'She studied hard ___ she passed the test.'", ["so", "although", "or"], 0, "So shows the result.")),
        _step("6", "Combine and vary", "Take short sentences and join them. Use different conjunctions so your writing does not sound repetitive.\n\nAim for a mix of short and long sentences.", "Short: The dog barked. The postman ran. Joined: When the dog barked, the postman ran.", "Mix short and joined sentences.", ("Which is a better joined sentence?", ["The dog barked and the dog barked and the dog barked.", "When the dog barked, the postman ran.", "The dog barked the postman."], 1, "It joins two ideas clearly.")),
        _step("7", "Spelling focus: more prefixes", "Add the prefix to the whole base word. Un-: unable, unlucky. Re-: reheat, reuse. Dis-: disappear. Mis-: misplace.\n\nNo letters are lost or doubled.", "un + able = unable, re + heat = reheat, dis + appear = disappear, mis + place = misplace.", "Keep the base word whole.", ("Which is spelled correctly?", ["disappear", "dissapear", "disapear"], 0, "dis + appear keeps both p letters.")),
    ],
    (
        "Look at the model, 'The Lost Library Book'. The short-sentence version is choppy: 'Ella lost her library book. She searched her room. She searched the car. She did not find it.' Now see how conjunctions join the ideas. 'Ella lost her library book, so she searched her room and the car.' So shows the result, and and joins two places. "
        "'Although she looked everywhere, she did not find it.' Although shows contrast and starts the sentence, so there is a comma after the clause. 'She was about to give up when she heard a rustle under the sofa cushion.' When shows time, and no comma is needed in the middle. "
        "'Because the cushion had slipped, the book had been hiding there all along.' Because gives the reason and, at the start, takes a comma. 'Ella grinned and hugged it, but she promised herself she would use a bookmark next time.' But shows contrast and has a comma before it. "
        "Try one together: 'It was windy. We flew our kites.' You could write: 'Although it was windy, we flew our kites.' or 'We flew our kites because it was windy.' The second one does not make sense, so the first is better. Always check that the conjunction fits the meaning."
    ),
    (
        "Type your answers in the practice boxes. Part A: type the best conjunction for each: 'I wanted to swim ___ the pool was closed.' 'She ran fast ___ she would not miss the bus.' 'We can walk ___ we can catch the bus.' Part B: join each pair using a conjunction and the correct comma: 'It was dark. We switched on the torch.' 'Dad cooked dinner. I set the table.' 'I was tired. I finished my homework.' Part C: type the correct word: un + able, re + heat, dis + appear, mis + place, un + lucky, re + use. Your parent can check your answers against the answer key."
    ),
    (
        "Read the model, then do the tasks. Everything you write goes in the boxes.\n\n" + MODEL + "\n\n"
        "Stage 1 (spot it): type three conjunctions from the joined version and say what each one shows (addition, contrast, reason, result, time or condition).\n"
        "Stage 2 (join): type a joined sentence for each pair, using a different conjunction each time and the correct comma. (a) The crowd roared. The team scored. (b) I wanted a pet. My apartment does not allow animals. (c) We can play inside. We can play outside. (d) Jo studied hard. She wanted to pass. (e) The alarm rang. Everyone left quickly.\n\n"
        "Stage 3 (fix it): rewrite this choppy paragraph as five to six sentences using at least four different conjunctions: 'It was Saturday. We went to the park. It was crowded. We found a quiet spot. We unpacked lunch. A magpie swooped. We ran.'\n"
        "Stage 4 (the comma): type four sentences about your weekend. Two must begin with a conjunction (and need a comma), and two must have the conjunction in the middle.\n"
        "Stage 5 (your own): write a short paragraph of six to eight sentences about a time you lost or found something. Use at least five different conjunctions, correct commas and a mix of short and longer sentences.\n"
        "Stage 6 (spell): type your six spelling words and the prefix in each."
    ),
    "Which conjunction did you use most, and which one would you like to use more often?", "Did I choose conjunctions that match the meaning, put commas after starting clauses, vary my conjunctions and spell my six prefix words correctly?",
    [_q("What does a conjunction do?", ["Joins words, phrases or clauses", "Names a thing", "Describes a noun", "Shows an action"], 0, "A conjunction joins ideas."), _q("Which conjunction shows contrast?", ["but", "so", "and", "because"], 0, "But shows two ideas that work against each other."), _q("Which conjunction gives a reason?", ["because", "or", "but", "and"], 0, "Because explains why."), _q("Which shows a result?", ["so", "although", "while", "or"], 0, "So shows what happened because of something."), _q("Which sentence is punctuated correctly?", ["Although it was cold, we went swimming.", "Although it was cold we went, swimming.", "Although, it was cold we went swimming.", "Although it was cold we went swimming,"], 0, "A comma follows the starting clause."), _q("Which sentence needs no comma?", ["We went swimming although it was cold.", "Although it was cold we went swimming.", "When the bell rang we left.", "Because it rained we stayed home."], 0, "The conjunction is in the middle."), _q("Which conjunction fits best? 'She was tired ___ she kept running.'", ["but", "so", "because", "or"], 0, "But shows contrast."), _q("In the model, why does the sentence 'Although she looked everywhere, she did not find it' have a comma?", ["It starts with the conjunction clause", "It is a question", "It is too short", "There is no reason"], 0, "A starting clause is followed by a comma."), _q("Which is spelled correctly?", ["unable", "unabel", "onable", "unnable"], 0, "un + able."), _q("Which is spelled correctly?", ["misplace", "misplase", "missplace", "myplace"], 0, "mis + place.")],
    "Type your answers in the practice boxes and submit them.", "Extension: take a short paragraph from a book you enjoy and find every conjunction. Say what each one shows.",
    [("conjunction", "A word that joins words, phrases or clauses"), ("clause", "A group of words with a subject and a verb"), ("compound sentence", "Two main clauses joined by and, but, so or or"), ("complex sentence", "A main clause plus a subordinate clause"), ("main clause", "A clause that can stand alone as a sentence"), ("subordinate clause", "A clause that cannot stand alone"), ("comma", "A punctuation mark that shows a short pause"), ("prefix", "Letters added to the start of a word that change its meaning")],
    [],
    _sort("What does the conjunction show?", "Sort each conjunction by what it shows.", ["Reason", "Contrast", "Time", "Condition"], [("because", 0), ("since (because)", 0), ("but", 1), ("although", 1), ("when", 2), ("while", 2), ("after", 2), ("if", 3)]),
    [_wc("Which is a conjunction?", ["because", "quickly", "table"], 0, "Because joins clauses."), _wc("Which shows a result?", ["so", "although", "or"], 0, "So shows what followed."), _wc("Which is punctuated correctly?", ["When it rained, we stayed in.", "When it rained we, stayed in.", "When, it rained we stayed in."], 0, "Comma after the starting clause."), _wc("Which is correct?", ["unable", "unabel", "onable"], 0, "un + able."), _wc("Which is correct?", ["unlucky", "unlucy", "onlucky"], 0, "un + lucky."), _wc("Which is correct?", ["reheat", "reheet", "reeheat"], 0, "re + heat."), _wc("Which is correct?", ["disappear", "dissapear", "disapear"], 0, "dis + appear."), _wc("Which means 'to put in the wrong place'?", ["misplace", "replace", "unplace"], 0, "mis- means wrongly.")],
    [{"key":"partA","label":"Part A: best conjunction","hint":"swim ___ the pool was closed; ran fast ___ she would not miss the bus; walk ___ catch the bus."}, {"key":"partB","label":"Part B: join the pairs","hint":"Join each pair with a conjunction and the correct comma."}, {"key":"partC","label":"Part C: prefixes","hint":"un+able, re+heat, dis+appear, mis+place, un+lucky, re+use."}, {"key":"stage1","label":"Spot it","hint":"Three conjunctions from the model and what each shows."}, {"key":"stage2","label":"Join the pairs","hint":"Five joined sentences with different conjunctions."}, {"key":"stage3","label":"Fix the paragraph","hint":"Rewrite the choppy paragraph with four different conjunctions."}, {"key":"stage4","label":"The comma","hint":"Four sentences about your weekend, two starting with a conjunction."}, {"key":"stage5","label":"My paragraph","hint":"Six to eight sentences with five different conjunctions."}, {"key":"spelling","label":"Spelling words","hint":"Type six words and the prefix in each."}],
    ["Using and for every join", "Forgetting the comma after a starting clause", "Choosing a conjunction that does not fit the meaning", "Writing a subordinate clause on its own as a sentence", "Losing or doubling letters when adding a prefix"],
    ["Find three sentences with conjunctions in a book and say what each shows.", "Say a sentence aloud at dinner using although, then because."],
    "Part A: but, so, or. Part B: accept any correct join with a sensible conjunction, for example: Because it was dark, we switched on the torch. Dad cooked dinner while I set the table. Although I was tired, I finished my homework. Part C: unable, reheat, disappear, misplace, unlucky, reuse. Main task: look for correct conjunction meanings (so shows result, although shows contrast, when shows time), commas after starting clauses, no comma needed in the middle, variety in the conjunctions, and a paragraph that avoids 'and then' chains. Stage 2 sample answers: (a) When the team scored, the crowd roared. (b) I wanted a pet, but my apartment does not allow animals. (c) We can play inside, or we can play outside. (d) Jo studied hard because she wanted to pass. (e) When the alarm rang, everyone left quickly. Quiz answers: joins words, phrases or clauses; but; because; so; Although it was cold, we went swimming; We went swimming although it was cold; but; it starts with the conjunction clause; unable; misplace.",
)

LESSON["spelling"] = {"focus":"More prefixes: un-, re-, dis-, mis-", "teaching":"Add the prefix to the whole base word with no letters lost or doubled. Un-: unable, unlucky. Re-: reheat, reuse. Dis-: disappear (keep both letters in appear). Mis-: misplace. Watch the double s in words such as misspell, where the base word already starts with s.", "words":[_w("unable","un-a-ble","un + able"),_w("unlucky","un-luck-y","un + lucky"),_w("reheat","re-heat","re + heat"),_w("reuse","re-use","re + use"),_w("disappear","dis-ap-pear","dis + appear"),_w("misplace","mis-place","mis + place")], "check":[_c("Which means 'to heat again'?",["reheat","misheat","unheat"],0,"Re- means again."),_c("Which is spelled correctly?",["disapear","disappear","dissapear"],1,"dis + appear.")]}
LESSON["spelling_focus"] = "Prefixes: un-, re-, dis-, mis- (more words)"
LESSON["hoard_words"] = list(WORDS)
