"""Stage 2 English, first-week Lesson 4: retelling a story aloud, and joined handwriting.
Fully taught from scratch. Videos were found via search and are checked on playback."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W2L4 = build(
    "s2-eng-w02-l4-retell-and-handwriting", "Storyteller's Voice and Joined Writing",
    "Tell a story aloud like a real storyteller, then make your handwriting flow with joined letters.",
    "Oral language and handwriting: retelling and joins",
    ["EN2-OLC-01", "EN2-HANDW-01", "EN2-SPELL-01"],
    {"EN2-OLC-01": "Primary. Retells a story aloud in order, using beginning, middle and end, sequencing words and a clear voice.",
     "EN2-HANDW-01": "Primary. Writes legibly using the NSW Foundation Font joins, with correct slope and spacing.",
     "EN2-SPELL-01": "Writes the vowel team words ai, ay, ee, ea and oa in joined handwriting."},
    "We are learning to retell a story aloud in the right order, and to write with joined letters that are neat and easy to read.",
    ["I can say what a retell is and what it leaves out.",
     "I can retell a story using beginning, middle and end.",
     "I can use sequencing words such as first, next, after that and finally.",
     "I can use my voice well: clear, steady and with expression.",
     "I can sit, hold my pencil and slope my writing correctly.",
     "I can join letters on the baseline and write words with the vowel teams ai, ay, ee, ea and oa."],
    ["retell", "sequence", "beginning", "middle", "end", "slope", "join", "legible"],
    ["A story you know (a picture book or a story from the lessons)", "Lined paper", "A pencil", "A phone or tablet to record your voice (optional)"],
    "Nothing is assumed. Child knows what a story is and can write the alphabet. Retelling and the handwriting joins are taught here from the beginning.",
    "To RETELL a story means to tell it again in your own words. You do not say every single detail. You tell only the most important parts, in the order they happened.\n\nA good retell uses three parts: the BEGINNING (who and where), the MIDDLE (the problem and what happens) and the END (how it is solved). Words like first, next, after that and finally keep the order clear.\n\nThe second half of this lesson is handwriting. In joined writing, letters in a word connect with small lines so your pencil lifts less. This makes your writing faster and neater. We use the NSW Foundation Font, which is the style taught in NSW schools.\n\nThen you will put the two skills together: write the sentences of your retell in joined handwriting.",
    [
        _step("1", "What is a retell?",
              "A retell is telling a story again, in your own words, in the right order. It is not the same as reading the story aloud, and it is not the same as making up a new story.\n\nA retell has three rules.\n1. Keep the IMPORTANT parts. The important parts are the characters, the setting and the big events.\n2. Leave out the small details. If you tell every little thing, the retell becomes as long as the story.\n3. Keep the ORDER. What happened first goes first.\n\nWhy do we practise retelling? It shows that you understood the story, and it makes you a better storyteller and a better writer.",
              "Story: Goldilocks. A short retell: A girl named Goldilocks went into the bears' house while they were out. She tried their porridge, chairs and beds. When the bears came home they found her, and she ran away. We kept the big events and left out small details such as which chair was too hard.",
              "Retell = important parts, in order, in your own words.",
              ("What should a retell leave out?", ["Small details", "The characters", "The big events"], 0, "A retell keeps the important parts and leaves out small details.")),
        _step("2", "Beginning, middle and end",
              "The easiest way to organise a retell is to use three parts.\n\nBEGINNING: say who the story is about and where it happens. Tell what the character wants or what first happens.\n\nMIDDLE: say what problem comes up and the main events that follow. This is usually the longest part.\n\nEND: say how the problem is solved and how the story finishes.\n\nA helpful trick is the three-finger retell. Hold up one finger for the beginning, two for the middle and three for the end. Say one or two sentences for each finger.",
              "Retell of the Zip story. Beginning: Zip is a robot who arrives at a new school and wants a friend. Middle: he gets the playground games wrong and the children laugh. End: Zip catches a girl who falls from the climbing frame, and the children invite him to play.",
              "Three fingers: beginning, middle, end.",
              ("What goes in the MIDDLE of a retell?", ["The problem and main events", "Only the title", "The ending"], 0, "The middle tells the problem and main events.")),
        _step("3", "Sequencing words",
              "SEQUENCING words show the order of events. They help your listener follow along. Using them is the difference between a muddled retell and a clear one.\n\nFor the beginning use: first, at the start, in the beginning, it all started when.\nFor the middle use: next, then, after that, soon, later.\nFor the end use: finally, in the end, at last.\n\nTry not to repeat 'and then' again and again. Mix your sequencing words so your retell flows.",
              "It all started when Mia heard a sound in the attic. Next, her torch stopped working. After that, she found a trunk that moved. Finally, she opened it and rescued a kitten.",
              "Use different sequencing words rather than 'and then' every time.",
              ("Which word is a good sequencing word for the END?", ["finally", "first", "next"], 0, "Finally shows the end.")),
        _step("4", "Using your voice",
              "A good storyteller uses their voice on purpose. Four things matter.\n\n1. VOLUME: loud enough for everyone to hear, but not shouting.\n2. PACE: not too fast. Slow down for important moments and pause after big events.\n3. CLEARNESS: say the ends of your words and look at your listener.\n4. EXPRESSION: change your voice to match the feeling. Whisper in a scary moment. Sound excited at the climax.\n\nBefore you tell your story, take a breath. Practise once quietly, then tell it to your listener. If you can, record yourself and listen back. Ask: did I keep the order? Did I speak clearly?",
              "Scary part: slow down and lower your voice. 'Mia... crept... up the stairs.' Exciting part: speed up a little and sound bright. 'Suddenly, the trunk flew open!'",
              "Clear, steady and expressive: volume, pace, clearness, expression.",
              ("What should you do at a scary moment in your retell?", ["Slow down and lower your voice", "Speak very fast", "Look away"], 0, "Matching your voice to the mood helps your listener feel it.")),
        _step("5", "Handwriting: sitting, holding and sloping",
              "Neat writing starts with how you sit and hold your pencil.\n\nSIT: feet flat on the floor, back straight, both arms resting on the table. Keep the page slightly tilted.\n\nHOLD: grip the pencil with your thumb and first finger, resting it on your middle finger. Keep your grip loose, because a tight grip tires your hand.\n\nSLOPE: in the NSW Foundation Font, all letters lean slightly to the right, at the same angle. Imagine all your letters are gently leaning into a breeze. Keep letters the same size and sit them on the line.\n\nWrite slowly to start. Neatness comes first, and speed comes later with practice.",
              "Slope practice: write a row of leaning strokes across the page, all leaning the same way: / / / / / / / /. Then write the word 'rain' with every letter leaning the same way.",
              "Same slope, same size, on the line.",
              ("Which way do the letters lean in the NSW Foundation Font?", ["Slightly to the right", "To the left", "Straight up and down"], 0, "Letters lean slightly to the right at the same angle.")),
        _step("6", "Joining letters on the baseline",
              "Joined writing means you connect letters in a word with small lines, so your pencil lifts less. This makes writing faster and smoother.\n\nMost letters join with a DIAGONAL join: the pencil finishes the letter with a small upward stroke that leads into the next letter. For example, in 'rain' the a and the i are joined by a small upward line, and so are the i and the n.\n\nTwo things to remember: join smoothly without lifting your pencil in the middle of a word, and lift your pencil at the end of a word before the next one.\n\nSome letters do not join forward in the usual way. In the NSW Foundation Font, the letters b, g, j, p, s and y do not join to the next letter. Lift your pencil after them. The letters o, r, v, w and x join with a straight line across the top (a horizontal join).\n\nStart by practising the joins of two letters, then three, then whole words.",
              "Practise these joins slowly: ai, ee, ea, oa, ay. Then these words: rain, train, tree, beach, boat, play. Note that in 'play' the p does not join forward and the y ends the word.",
              "Pencil down, join smoothly, lift at the end of the word.",
              ("Which letters do NOT join forward in the NSW Foundation Font?", ["b, g, j, p, s, y", "a, e, i, n", "all letters"], 0, "Those letters do not join to the next letter.")),
        _step("7", "Writing vowel team words in joined writing",
              "Now put handwriting and spelling together. The vowel teams are pairs of letters that make one sound.\n\nAI and AY both say 'ay': rain, train, play, day. AI is usually in the middle of a word and AY at the end.\nEE and EA both say 'ee': tree, feet, beach, dream.\nOA says 'oh': boat, coast, road.\n\nWrite each word three times in joined handwriting. First trace it, then copy it, then cover it and write it from memory. Check each word letter by letter.\n\nWrite neatly and slowly. A word that is spelt right but cannot be read is still hard for the reader.",
              "Row one: rain rain rain. Row two: train train train. Check: does each word lean the same way, and sit on the line?",
              "Trace, copy, cover, write, check.",
              ("Which word uses the vowel team AY?", ["play", "rain", "boat"], 0, "Play has ay.")),
        _step("8", "Putting it together: a retell in joined writing",
              "Now do both skills in one task.\n\n1. Choose a story you know well.\n2. Practise aloud using three fingers: beginning, middle, end. Use at least three sequencing words.\n3. Tell your retell aloud to a listener, using your storyteller's voice.\n4. Write your retell as three short sentences (one for each part) in joined handwriting.\n\nCheck your handwriting: same slope, same size, sitting on the line, smooth joins.\n\nFinally, ask your listener one question about your retell. If they can answer it, your retell was clear.",
              "Written retell: It all started when a robot named Zip arrived at a new school. After that, the children laughed because he did not understand their games. In the end, Zip caught a falling girl and made a friend.",
              "Tell it aloud first, then write it neatly.",
              ("What is the right order for this task?", ["Practise aloud, tell it, then write it", "Write it, then forget it", "Only write the title"], 0, "Practise aloud first, then tell it, then write it.")),
    ],
    "Story: The Lost Kite. Beginning: It all started when Sam's new red kite blew away in the wind. Middle: Next, he chased it across the park and over the creek. After that, he saw it stuck high in a tree. End: Finally, he asked his tall neighbour for help and got it back.\n\nWritten in joined handwriting (the first sentence). Notice that the letters lean the same way, the joins are smooth, and the pencil lifts only between words.\n\nVoice check: slow and quiet when the kite is stuck in the tree, then bright and relieved at the end.",
    "1) Choose a story you know. 2) Practise a three-finger retell aloud, with at least three sequencing words. 3) Tell it to someone, using your storyteller's voice. Record it if you can. 4) On lined paper, write the joins ai, ay, ee, ea, oa three times each. 5) Write the words rain, play, tree, beach and boat three times each: trace, copy, then write from memory. 6) Write your retell in three sentences in joined handwriting.",
    "Retell a story aloud, then write your retell in three sentences in joined handwriting. Upload a photo of your handwriting and a short recording of your retell if you can.",
    "What was the easiest part of the retell: beginning, middle or end? Which joins in your handwriting still feel tricky?",
    "Did I keep the order? Did I use sequencing words? Did I leave out small details? Did I speak clearly and with expression? Do my letters lean the same way and sit on the line? Are my joins smooth?",
    [
        _q("What does 'retell' mean?", ["Tell the important parts of a story again in order", "Read the whole story word for word", "Make up a new story"], 0, "A retell uses your own words and the important parts."),
        _q("Which parts does a retell have?", ["Beginning, middle and end", "Title, picture and cover", "Only the end"], 0, "Beginning, middle and end."),
        _q("Which sentence is the BEGINNING of a retell?", ["It all started when a robot arrived at school.", "Finally, the robot made a friend.", "After that, the children laughed."], 0, "It all started when is a beginning phrase."),
        _q("Which is a sequencing word for the middle?", ["after that", "in the end", "finally"], 0, "After that is a middle word."),
        _q("Read: Sam lost his kite. He chased it and found it stuck in a tree. His neighbour helped him get it back. Which is the best one-sentence retell of the END?", ["In the end, his neighbour helped Sam get the kite back.", "Sam had a red kite.", "The tree was tall."], 0, "The end tells how the problem was solved."),
        _q("What should you leave out of a retell?", ["Small details", "Characters", "The problem"], 0, "Small details are left out."),
        _q("How should you read a spooky part aloud?", ["Slow down and lower your voice", "Rush it", "Say it in a flat voice"], 0, "Matching your voice to the mood makes the retell more interesting."),
        _q("In joined writing, what do you do at the end of a word?", ["Lift your pencil", "Keep joining into the next word", "Press hard"], 0, "Lift your pencil between words."),
        _q("Which word has the vowel team AI?", ["train", "play", "boat"], 0, "Train has ai."),
        _q("Which letters lean the same way in joined writing?", ["All of them, slightly to the right", "Only the capital letters", "None of them"], 0, "The slope is the same for every letter."),
    ],
    "Upload a photo of your joined handwriting and (optional) a recording of your retell.",
    "Retell the same story a second time in half as many words. Which details did you leave out? Was your retell still clear?",
    [("retell", "To tell a story again in your own words."), ("sequence", "The order things happen in."), ("beginning", "The first part of a story."), ("middle", "The part with the problem and main events."),
     ("end", "The part where the problem is solved."), ("slope", "The lean of your letters."), ("join", "A small line connecting two letters."), ("legible", "Easy to read.")],
    [
        _video("How To Retell a Story For Kids", "w33-m8-geuM",
               "Watch how to retell a story by telling the characters, setting and big events from beginning to end. Say each part aloud with the video.",
               "Choose a story you know and say its beginning, middle and end using three fingers.",
               ("What do you tell first in a retell?", ["The characters and setting", "The ending", "The title only"], 0, "A retell starts with the characters and setting.")),
        _video("Handwriting: joining letters on the base line (NSW Foundation Font)", "GHmbMwUP9UE",
               "Watch how letters join on the baseline and how the letters lean to the right. Practise each join with your pencil as it appears.",
               "Write the joins ai, ee, ea and oa three times each.",
               ("Which way do the letters lean?", ["To the right", "To the left", "Straight"], 0, "The letters lean to the right.")),
    ],
    _sort("Retell part sorter", "Which part of a retell does each phrase or event belong to? Tap a part, then Check.",
          ["Beginning", "Middle", "End"],
          [("In the beginning", 0), ("It all started when", 0), ("Mia hears a sound in the attic", 0), ("After that", 1), ("In the middle", 1), ("Her torch stops working", 1), ("Finally", 2), ("In the end", 2), ("Mia rescues the kitten", 2)]),
    [
        _wc("A retell tells a story in your ___ words.", ["own", "borrowed", "secret"], 0, "Retell in your own words."),
        _wc("Which is a sequencing word?", ["finally", "purple", "dog"], 0, "Finally shows order."),
        _wc("Handwriting that is easy to read is ___.", ["legible", "loud", "late"], 0, "Legible means easy to read."),
        _wc("The lean of your letters is called the ___.", ["slope", "slide", "stack"], 0, "Slope is the lean."),
        _wc("Which is spelt correctly?", ["train", "trane", "trayn"], 0, "Train uses ai."),
        _wc("Which is spelt correctly?", ["beach", "beech (the sandy shore)", "beatch"], 0, "Beach uses ea."),
    ],
    [
        {"key": "retell", "label": "My retell", "hint": "Write your three-sentence retell in joined handwriting."},
        {"key": "words", "label": "Joined words", "hint": "Write rain, play, tree, beach and boat."},
        {"key": "voice", "label": "Voice check", "hint": "Which part did you tell with the most expression?"},
    ],
    ["Retelling every small detail.", "Mixing up the order of events.", "Saying 'and then' every time.", "Speaking too fast.", "Letters leaning in different directions.", "Gripping the pencil too tightly."],
    [{"title": "Storyteller Show", "description": "Retell a story to a family member and ask them to tell you the beginning, middle and end back.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check that the retell has a beginning, middle and end in order, uses at least three sequencing words, leaves out small details, and is written in three sentences. Check the handwriting for even slope, smooth joins and letters sitting on the line. Sorter: Beginning: In the beginning; It all started when; Mia hears a sound. Middle: After that; In the middle; torch stops. End: Finally; In the end; rescues the kitten.",
)

LESSONS = [W2L4]
