"""Stage 2 English, first-week Lesson 3: nouns, verbs and adjectives. Fully taught from scratch,
including the spelling rules for adding endings (nothing is assumed from earlier lessons).
Loaded before the older l2_l3 module so this version wins (same seed_key)."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W2L3 = build(
    "s2-eng-w02-l3-nouns-verbs-adjectives", "Word Class Workshop: Nouns, Verbs, Adjectives",
    "The Word Machine is jammed! Learn what each word does, sort the parts, then upgrade weak sentences into strong ones.",
    "Language: nouns, verbs and adjectives",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Uses nouns, verbs and adjectives to build precise sentences.",
     "EN2-VOCAB-01": "Learns the three word classes and the sub-types (common, proper, abstract nouns; action, saying, thinking, being verbs) and chooses stronger words.",
     "EN2-SPELL-01": "Learns and applies the rules for adding -ing, -ed, -y, -ful and -less (drop the e, double the consonant, change y to i)."},
    "We are learning to name the jobs words do in a sentence (nouns, verbs and adjectives) and to choose precise words that make our writing clear and vivid.",
    ["I can say what a noun, a verb and an adjective each do.",
     "I can tell common, proper and abstract nouns apart.",
     "I can tell action, saying, thinking and being verbs apart.",
     "I can find the verb, nouns and adjectives in a sentence.",
     "I can upgrade a weak sentence in three steps.",
     "I can add -ing, -ed, -y and -ful to a word using the spelling rules."],
    ["noun", "verb", "adjective", "common noun", "proper noun", "abstract noun", "action verb", "precise"],
    ["Paper or notebook", "Pencil", "Coloured pencils (three colours are ideal)", "A book or story you enjoy"],
    "Nothing is assumed. Child can write simple sentences. Nouns, verbs and adjectives are taught from the very beginning, and the spelling rules for endings are taught in full in the last two steps.",
    "Every word in a sentence has a job to do, just like each player on a team. Words are sorted into groups, called word classes, according to the job they do. In this lesson we learn the three most important jobs.\n\nNOUNS name things: people, places, animals, objects and ideas. VERBS tell what is happening: they show action, speech, thought or a state of being. ADJECTIVES describe nouns: they tell us more about them.\n\nGood writers choose each word on purpose. A sentence with weak words is vague: 'The big dog went to the place.' A sentence with strong words is precise, which means exact and clear: 'The enormous mastiff stalked across the playground.' Same idea, but the second one makes a picture in your head.\n\nYou will learn the three jobs one at a time, practise spotting them in sentences, and then learn a three-step method for upgrading weak sentences. The last two steps teach the spelling rules for adding endings to verbs and adjectives.",
    [
        _step("1", "Words have jobs",
              "Think of a sentence as a small machine. Each word is a part with its own job. If you take out a part, the machine stops working or works badly.\n\nTake the sentence 'The tiny robot rolled across the playground.' Remove 'rolled' and nothing is happening: 'The tiny robot across the playground.' Remove 'robot' and we do not know who: 'The tiny rolled across the playground.' Remove 'tiny' and the sentence still works, but we lose a detail.\n\nSo every sentence needs a NOUN (who or what) and a VERB (what is happening). ADJECTIVES are the extra detail that make the picture clear.\n\nLearning the names of the jobs helps you in two ways. When you READ you can see how sentences are built. When you WRITE you can choose better words, because you will know exactly which kind of word you want to improve.",
              "Machine check. 'The hungry wolf crept through the silent forest.' Who or what? wolf and forest (nouns). What is happening? crept (verb). What details? hungry and silent (adjectives).",
              "Noun = who or what. Verb = what is happening. Adjective = a detail about a noun.",
              ("Which word class tells what is happening?", ["Verb", "Noun", "Adjective"], 0, "A verb tells what is happening.")),
        _step("2", "Nouns: the naming words",
              "A NOUN names a person, place, animal, thing or idea. If you can see it, touch it, visit it or name it, it is probably a noun.\n\nThere are three kinds you need to know.\n1. COMMON NOUNS name general things: girl, city, river, dog, teacher. They do not start with a capital letter unless they begin a sentence.\n2. PROPER NOUNS name one particular person, place or thing: Mia, Sydney, the Murray River, Mr Lee. They ALWAYS start with a capital letter.\n3. ABSTRACT NOUNS name things you cannot touch or see, like ideas and feelings: kindness, courage, freedom, happiness, friendship.\n\nQuick test: can you put 'a', 'an' or 'the' in front of it and still make sense? 'The teacher' works. 'The Sydney' sounds odd, so proper nouns are an exception, but the test still catches most nouns.\n\nAbstract nouns are the trickiest. You cannot hold 'bravery' in your hand, but it is still a noun because it names something.",
              "Common: teacher, park, dog. Proper: Mr Lee, Hyde Park, Rex. Abstract: courage, friendship, joy.\n\nOne sentence with all three: 'Mia showed great courage when she walked her dog Rex to the park.' Common nouns: dog, park. Proper nouns: Mia, Rex. Abstract noun: courage.",
              "Proper nouns always get a capital letter, even in the middle of a sentence.",
              ("Which is a proper noun?", ["Brisbane", "city", "river"], 0, "Brisbane names one particular place, so it has a capital letter.")),
        _step("3", "Verbs: the action and more",
              "A VERB tells what someone or something does, says, thinks or is. Every sentence needs at least one verb. Verbs are the engine of the sentence.\n\nThere are four kinds to know.\n1. ACTION verbs show doing: run, climb, whisper, tumble.\n2. SAYING verbs show speech: shouted, murmured, announced, replied.\n3. THINKING verbs show what happens in the mind: wondered, believed, imagined, decided.\n4. BEING verbs show a state or what something is: is, are, was, were, seem.\n\nQuick test: try putting 'I' or 'he' in front of the word. 'He whispers' makes sense, so whisper is a verb. 'He table' does not, so table is not.\n\nStrong verbs make writing come alive because they show HOW something happens. 'Walked' is correct but plain. 'Crept' shows careful and quiet. 'Marched' shows firm and strong. 'Strolled' shows slow and relaxed.",
              "Action: dash, dive. Saying: whispered, yelled. Thinking: imagined, decided. Being: is, was.\n\nWeak verb to strong verb: 'The boy went into the room.' becomes 'The boy tiptoed into the room.' One word, and we picture a sneaky, quiet boy.",
              "Pick a verb that shows how the action happens.",
              ("Which is a stronger verb than 'walked'?", ["crept", "went", "got"], 0, "Crept shows how the person moved.")),
        _step("4", "Adjectives: the describing words",
              "An ADJECTIVE describes a noun. It answers questions about the noun: What KIND? (a muddy track, a grumpy troll). How MANY? (three birds, many stars). Which ONE? (that tower, the last page).\n\nAdjectives usually come BEFORE the noun: the enormous cave. They can also come AFTER a being verb: The cave was enormous.\n\nWatch out for weak adjectives like nice, good, bad and big. They are used so often that they do not paint a picture. Swap them for exact ones. Instead of a 'nice' dinner write a 'delicious' dinner. Instead of a 'big' house write a 'crumbling, three-storey' house.\n\nA good rule is that one precise adjective beats three weak ones. 'The enormous dog' tells you more than 'the big, large, huge dog'.",
              "Weak: The nice dog lived in the big house. Precise: The gentle golden retriever lived in the crumbling mansion.\n\nAdjectives after a verb: The soup was delicious. The night felt silent.",
              "Ask what kind, how many or which one to spot an adjective.",
              ("Which adjective is the most precise?", ["enormous", "big", "nice"], 0, "Enormous is more exact than big.")),
        _step("5", "Finding all three in a sentence",
              "To find the word jobs in any sentence, follow this three-step method.\n\nSTEP 1: Find the VERB. Ask: what is happening? That is your verb.\n\nSTEP 2: Find the NOUNS. Ask: who or what is doing the verb, or is having something done to it? Also look for places and things named.\n\nSTEP 3: Find the ADJECTIVES. Ask: which words describe the nouns?\n\nIt helps to mark them with colours. Underline the verb in red, circle the nouns in blue and box the adjectives in green.\n\nSome words change their job depending on how they are used. 'Light' is a noun in 'Turn on the light', a verb in 'Light the candle' and an adjective in 'a light jacket'. So always look at what the word is doing in THIS sentence, not what it did in another.",
              "'The tiny robot rolled across the noisy playground.' Step 1: verb = rolled. Step 2: nouns = robot, playground. Step 3: adjectives = tiny, noisy.",
              "The job a word does in this sentence decides its class.",
              ("In 'The brave knight raced home', which word is the verb?", ["raced", "brave", "knight"], 0, "Raced tells what is happening.")),
        _step("6", "Upgrading a weak sentence",
              "Writers upgrade sentences by swapping weak words for strong ones. Use this three-step method.\n\nSTEP 1: Replace the weak VERB with a strong one. This often makes the biggest difference. 'Went' becomes 'bounded' or 'stormed' or 'tiptoed'.\n\nSTEP 2: Make the NOUNS more specific. 'Dog' becomes 'retriever'. 'Place' becomes 'park'. 'Thing' becomes 'treasure chest'.\n\nSTEP 3: Add ONE precise ADJECTIVE (or two at most) that suits the mood.\n\nFinally, read it aloud. Does it paint a clear picture? Is it too crowded with describing words? If every noun has three adjectives, the reader gets tired. Choose words that fit the feeling you want.",
              "Weak: The man went to the shop.\nStep 1, strong verb: The man stormed into the shop.\nStep 2, specific nouns: The shopkeeper stormed into the bakery.\nStep 3, precise adjective: The grumpy shopkeeper stormed into the busy bakery.",
              "Change the verb first. It usually makes the biggest difference.",
              ("What is the FIRST step of the upgrade method?", ["Replace the weak verb", "Add five adjectives", "Delete the nouns"], 0, "A stronger verb gives the biggest improvement.")),
        _step("7", "Choosing words to match the mood",
              "Strong words are not just fancy words. They are the RIGHT words for what you want the reader to feel. The same event can feel completely different depending on your choices.\n\nFor a tense, scary moment choose sharp, quiet verbs and dark adjectives: crept, froze, gloomy, silent. For a joyful moment choose lively verbs and bright adjectives: leapt, giggled, sparkling, cheerful.\n\nBefore choosing, decide the mood. Then pick words that fit. Try changing only the verb and the adjectives and watch the whole feeling change.\n\nThis connects to your story plan. The mood you chose for your setting should guide the nouns, verbs and adjectives you use when you write it.",
              "Scary: The shadowy figure crept along the silent corridor.\nHappy: The cheerful clown skipped along the sunny corridor.\nSame sentence shape, completely different feeling.",
              "Decide the mood first, then choose the words.",
              ("Which words suit a SPOOKY night?", ["crept, gloomy, silent", "skipped, sunny, cheerful", "bounced, bright, merry"], 0, "Those words create a spooky mood.")),
        _step("8", "Spelling: adding -ing and -ed",
              "Verbs often take endings: -ing (happening now) and -ed (already happened). Sometimes the spelling of the base word changes. Learn these three rules.\n\nRULE 1, DROP THE E: if the word ends in a silent e, drop the e before adding -ing or -ed. hope + ing = hoping. bake + ed = baked (the e is already there, so just add d). \n\nRULE 2, DOUBLE THE CONSONANT: if a short word has ONE short vowel followed by ONE consonant at the end, double that consonant. run + ing = running. stop + ed = stopped. stir + ed = stirred. Check: is it a one-syllable word, with a short vowel and a single consonant at the end? If yes, double it.\n\nRULE 3, CHANGE Y TO I: if the word ends in a consonant followed by y, change y to i before adding -ed. carry + ed = carried. cry + ed = cried. BUT keep the y before -ing: carry + ing = carrying.\n\nWords with two consonants or a long vowel do NOT double: jump + ing = jumping. rain + ed = rained.",
              "hope + ing = hoping. run + ing = running. stop + ed = stopped. carry + ed = carried. carry + ing = carrying. jump + ing = jumping (two consonants, so no doubling).",
              "One short vowel + one consonant at the end? Double it.",
              ("What is stop + ed?", ["stopped", "stoped", "stopt"], 0, "stop has one short vowel and one consonant, so double the p.")),
        _step("9", "Spelling: making adjectives with -y, -ful and -less",
              "Many adjectives are made by adding an ending to a noun. Three useful endings are -y, -ful and -less.\n\n-Y means 'full of' or 'like': rain + y = rainy. mud + y = muddy (double the d because mud has one short vowel and one consonant). fun + y = funny (double the n).\n\n-FUL means 'full of': care + ful = careful. help + ful = helpful. Notice -ful has only ONE l.\n\n-LESS means 'without': care + less = careless. help + less = helpless.\n\nSo 'careful' and 'careless' are opposites. They show how one small ending changes the meaning completely.\n\nUse the Look, Say, Cover, Write, Check routine for tricky words: look at the word, say it aloud, cover it, write it from memory, then check it letter by letter.\n\nNew Word Hoard words: enormous, delicious, precise, shopkeeper, muddy, careful.",
              "mud + y = muddy. fun + y = funny. care + ful = careful. care + less = careless. help + ful = helpful.",
              "-ful has one l. Doubling happens before -y after a short vowel.",
              ("What is mud + y?", ["muddy", "mudy", "mudddy"], 0, "mud has one short vowel and one consonant, so double the d before adding -y.")),
    ],
    "Weak sentence: The dog went into the place.\n\nStep 1, strong verb: The dog bounded into the place.\nStep 2, specific nouns: The retriever bounded into the park.\nStep 3, precise adjectives: The excited golden retriever bounded into the muddy park.\n\nNow find the word jobs. Verb: bounded (what is happening?). Nouns: retriever, park (who or what; where). Adjectives: excited, golden, muddy (describing the nouns). Mood check: the lively verb and bright adjectives suit a happy scene.\n\nSpelling check: 'bounded' is bound + ed (no change). If we wrote the dog 'was running' we would double the n, because run has one short vowel and one consonant.",
    "In your notebook: 1) Sort ten words into noun, verb or adjective: whisper, mountain, brave, crept, kindness, enormous, Sydney, delicious, laughed, treasure. 2) Colour-code this sentence by underlining the verb, circling the nouns and boxing the adjectives: The grumpy troll stomped across the wooden bridge. 3) Upgrade three weak sentences using the three-step method: She went home. The big man looked at the thing. It was a nice day. 4) Write the new spelling of each: hope + ing, stop + ed, carry + ed, mud + y, care + ful.",
    "Write five sentences for the story you planned. In each, use at least one strong verb, one precise adjective and one specific noun. Underline the verbs, circle the nouns and box the adjectives in two of your sentences. Then write the mood of your story and explain why your word choices fit it.",
    "Which word class do you find easiest to upgrade: nouns, verbs or adjectives? Why? Which of your word choices are you proudest of?",
    "Did I sort the words correctly? Did I mark verbs, nouns and adjectives in two sentences? Did I use strong verbs and precise adjectives that match the mood? Did I check my endings with the spelling rules?",
    [
        _q("Which is a noun?", ["mountain", "run", "quickly"], 0, "A mountain is a thing."),
        _q("Which is a verb?", ["whisper", "brave", "happiness"], 0, "Whisper is an action."),
        _q("Which is an adjective?", ["enormous", "table", "jump"], 0, "Enormous describes a noun."),
        _q("Which is an abstract noun?", ["kindness", "book", "bike"], 0, "You cannot touch or see kindness."),
        _q("Read: 'The hungry wolf crept through the silent forest.' Which words are the adjectives?", ["hungry and silent", "wolf and forest", "crept and through"], 0, "Hungry and silent describe the nouns wolf and forest."),
        _q("Read: 'A cheerful clown skipped along the sunny path.' What is the mood?", ["Happy", "Scary", "Sad"], 0, "Cheerful, skipped and sunny create a happy mood."),
        _q("Which is the best upgrade of 'The man went to the shop'?", ["The grumpy shopkeeper stormed into the bakery.", "The man went to the shop quickly.", "The man went to the nice shop."], 0, "It uses a strong verb, specific nouns and a precise adjective."),
        _q("What is run + ing?", ["running", "runing", "runeing"], 0, "One short vowel and one consonant, so double the n."),
        _q("What is carry + ed?", ["carried", "carryed", "carred"], 0, "Change the y to i before -ed."),
        _q("What is care + ful?", ["careful", "carefull", "carful"], 0, "Keep the e and use only one l."),
    ],
    "Upload a photo of your sorted word list, your colour-coded sentence, your three upgrades and your five story sentences.",
    "Write two sentences that use the same word as a noun in the first and as a verb in the second (such as 'light' or 'watch'). Explain how you know which job it does each time.",
    [("noun", "A naming word for a person, place, thing or idea."), ("verb", "A doing, saying, thinking or being word."), ("adjective", "A word that describes a noun."),
     ("common noun", "The general name of a person, place or thing."), ("proper noun", "The name of one particular person, place or thing. It starts with a capital letter."),
     ("abstract noun", "The name of something you cannot touch, like kindness."), ("action verb", "A word that shows what someone does."), ("precise", "Exact and clear.")],
    [
        _video("Nouns, Verbs & Adjectives for Kids (Wombat School, Australian curriculum)", "984ntq-7x58",
               "Watch how to spot nouns, verbs and adjectives in simple sentences. Pause and try each example yourself.",
               "Read steps 2 to 4 and find five nouns, five verbs and five adjectives in your own book.",
               ("What does an adjective do?", ["Describes a noun", "Shows an action", "Names a person"], 0, "An adjective describes a noun.")),
        _video("Learn About Nouns, Adjectives & Verbs (StoryBots)", "_II6ySgUtWc",
               "Watch how swapping a word for a different word of the same type changes a sentence.",
               "Swap one noun, one verb and one adjective in a sentence from your book.",
               ("What is a verb?", ["A word for an action", "A person", "A place"], 0, "A verb describes an action.")),
        _video("Let's Review Nouns, Verbs and Adjectives", "U2l3BFthsD0",
               "Watch the review. Test yourself before each answer appears.",
               "Write one noun, verb and adjective sentence of your own.",
               ("A noun is a person, place or...", ["thing", "action", "colour"], 0, "A noun is a person, place or thing.")),
    ],
    _sort("Word class sorter", "Which job does each word do? Tap a job, then Check.",
          ["Noun", "Verb", "Adjective"],
          [("mountain", 0), ("Sydney", 0), ("kindness", 0), ("treasure", 0), ("whisper", 1), ("crept", 1), ("laughed", 1), ("stormed", 1), ("enormous", 2), ("delicious", 2), ("brave", 2), ("muddy", 2)]),
    [
        _wc("Which is a noun?", ["bridge", "cross", "narrow"], 0, "A bridge is a thing."),
        _wc("Which is a verb?", ["sprinted", "swift", "road"], 0, "Sprinted is an action."),
        _wc("Which is an adjective?", ["gigantic", "giant (as in a giant)", "grow"], 0, "Gigantic describes."),
        _wc("Which word needs a capital letter?", ["Australia", "country", "island"], 0, "Australia is a proper noun."),
        _wc("Which is correct?", ["stopped", "stoped", "stopt"], 0, "Double the p before -ed."),
        _wc("Which is correct?", ["hoping", "hopeing", "hopping (to hope)"], 0, "Drop the e before -ing."),
        _wc("Which is the strongest verb?", ["charged", "went", "got"], 0, "Charged shows how."),
        _wc("Which is the most precise adjective?", ["crumbling", "nice", "good"], 0, "Crumbling is specific."),
    ],
    [
        {"key": "sentences", "label": "My five sentences", "hint": "Write five sentences for your planned story."},
        {"key": "verbs", "label": "Strong verbs", "hint": "List the strong verbs you used."},
        {"key": "adjectives", "label": "Precise adjectives", "hint": "List the precise adjectives you used."},
        {"key": "upgrade", "label": "Best upgrade", "hint": "Show one weak sentence and your upgrade, with the three steps."},
    ],
    ["Calling a verb-like word a noun (running is a verb in 'she is running').", "Using weak words like nice, good and big.", "Adding too many adjectives.", "Forgetting capital letters on proper nouns.", "Forgetting to double the consonant or drop the e when adding an ending."],
    [{"title": "Word Detective", "description": "Find ten strong verbs in a book and copy the sentences.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "1) Nouns: mountain, kindness, Sydney, treasure. Verbs: whisper, crept, laughed. Adjectives: brave, enormous, delicious. 2) Verb: stomped. Nouns: troll, bridge. Adjectives: grumpy, wooden. 3) Answers vary: strong verb, specific noun and one precise adjective in each. 4) hoping, stopped, carried, muddy, careful.",
)

LESSONS = [W2L3]
