"""Stage 2 English, Block A (narrative writing), week 7, lessons 1 to 4.
Pass 1: lessons only. Videos are empty and the module is not yet registered in lesson_library.py.
Keys use the prefix a7."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A7L1 = build(
    "s2-eng-a7-l1-resolution-and-ending", "Resolution and Ending",
    "Learn how a story solves its problem and ends in a satisfying way.",
    "Reading and writing: resolution and ending",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies how a story resolves its problem and how it ends.",
     "EN2-CWT-01": "Writes a resolution and ending for an original story.",
     "EN2-VOCAB-01": "Learns the terms resolution, ending, twist, reflection and moral."},
    "We are learning how a story solves its problem and ends.",
    ["I can say what a resolution is.", "I can link the resolution to the problem.", "I can name different kinds of ending.", "I can avoid a rushed ending.", "I can write a resolution and ending."],
    ["resolution", "ending", "twist", "reflection", "moral"],
    ["Paper or notebook", "Pencil", "Your problem and tense scene from last week", "A story you are reading (your parent will help you choose)"],
    "Child knows the problem, complication and tension. Resolution and ending are taught from the beginning.",
    "The RESOLUTION is the part of a story where the problem is solved or settled. The ENDING is how the story finishes and what the reader is left with.\n\nA good resolution grows out of the problem and complication. It should feel earned, not sudden.\n\nIn this lesson you will study how stories resolve and end, then write your own.",
    [
        _step("1", "Solving the problem",
              "The resolution answers the problem. If the problem was a lost dog, the resolution is what happens about the dog.\n\nThe character should solve it using what they have learned or done. A solution that appears by magic or luck feels like a cheat.\n\nWeak: Suddenly the dog came home.\nStronger: Ella remembered the dog loved the smell of bacon. She left a trail from the park, and soon heard a bark.\n\nAsk: does the character do something to solve it?",
              "Problem: torn map. Resolution: Sam matched the pieces by the river line.",
              "The character earns the resolution.",
              ("A good resolution is...", ["earned by the character", "pure luck", "unrelated"], 0, "The character should act.")),
        _step("2", "Kinds of ending",
              "Stories end in different ways.\n\nHappy ending: the problem is solved and things are good.\nBittersweet ending: solved, but something is lost.\nOpen ending: the reader decides what happens next.\nTwist ending: a surprise changes how we see the story.\n\nThe ending should suit the mood of the story. A funny story rarely ends in sadness.\n\nChoose an ending type on purpose.",
              "Twist: the monster was only a lost puppy.",
              "Pick an ending that suits your story.",
              ("Which ending leaves the reader to decide?", ["Open", "Happy", "Twist"], 0, "An open ending leaves questions.")),
        _step("3", "Reflection and a final line",
              "Many endings include a REFLECTION: how the character feels or what they learned.\n\n'Leo smiled. He would never be afraid of the dark cellar again.'\n\nA MORAL is a lesson, as in a fable. It does not need to be stated. Let the reader work it out.\n\nFinish with a strong final line. It might return to the setting, an object or the title. Avoid 'and they lived happily ever after' and 'The End' as the only ending.",
              "Final line returning to the setting: The cellar door stayed open all that summer.",
              "End with a reflection and a memorable last line.",
              ("A reflection shows...", ["what the character feels or learned", "the title", "the author"], 0, "It shows change.")),
        _step("4", "Write your ending",
              "Write 5 to 7 sentences.\n\n1. Remind the reader of the problem in a few words.\n2. Show how the character solves it using what they know.\n3. Show how things are different now.\n4. Add a reflection.\n5. Finish with a strong final line.\n6. Do not rush. Use detail.\n\nModel: Ella laid the bacon trail from the park gate. She held her breath and listened. A bark came from the bushes. She hugged the muddy dog tight and promised never to let go again.",
              "Check your ending answers the problem.",
              "Solve, show change, reflect, finish.",
              ("Should the ending be rushed?", ["No, use detail", "Yes, one line", "Skip it"], 0, "Give it care.")),
    ],
    "Model answers. Resolution: the part where the problem is solved. Types: happy, bittersweet, open, twist. Reflection: how a character feels or what they learned. Sample ending: Ella laid the bacon trail from the park gate. She held her breath and listened. A bark came from the bushes. She hugged the muddy dog tight and promised never to let go again.",
    "1) Match three problems to resolutions. 2) Name the ending type in three stories. 3) Fix a weak lucky ending. 4) Write a reflection sentence. 5) Plan your ending. 6) Write 5 to 7 sentences.",
    "Write a 5 to 7 sentence resolution and ending for your story. Upload a photo of your writing.",
    CHECK,
    "Does the ending answer the problem? Does the character solve it? Did I show how things changed? Did I add a reflection? Is my last line strong? Is it 5 to 7 sentences?",
    [
        _q("The resolution is where the problem is...", ["solved", "introduced", "ignored"], 0, "It settles the problem."),
        _q("A good resolution is...", ["earned", "sudden luck", "unrelated"], 0, "The character acts."),
        _q("An ending that surprises is a...", ["twist", "title", "tense"], 0, "A twist surprises."),
        _q("An ending with a loss is...", ["bittersweet", "open", "happy only"], 0, "Solved, but something is lost."),
        _q("A reflection shows...", ["what the character learned", "the setting", "the author"], 0, "It shows change."),
        _q("A moral is...", ["a lesson", "a verb", "a place"], 0, "A lesson in the story."),
    ],
    "Upload a photo of your resolution and ending.",
    "Read the ending of a favourite story. What kind of ending is it, and does it answer the problem?",
    [("resolution", "The part where the problem is solved."), ("ending", "How a story finishes."), ("twist", "A surprise that changes how we see the story."), ("reflection", "How a character feels or what they learned."), ("moral", "A lesson a story teaches.")],
    [],
    _sort("Ending types", "Which kind of ending is each? Tap a group, then Check.",
          ["Happy", "Open", "Twist"],
          [("Everyone cheered and the lost dog was home.", 0), ("The friends hugged and the problem was solved.", 0), ("She wondered what lay beyond the gate.", 1), ("No one knew where the path led.", 1), ("The ghost was the caretaker all along.", 2), ("The letter had been written by Leo himself.", 2)]),
    [
        _wc("The part where the problem is solved is the ___.", ["resolution", "revolution", "relation"], 0, "Resolution."),
        _wc("A surprise ending is a ___.", ["twist", "twig", "twin"], 0, "Twist."),
        _wc("What a character learned is shown in a ___.", ["reflection", "reflexion", "refraction"], 0, "Reflection."),
        _wc("Which is spelt correctly?", ["resolution", "resolushun", "resolusion"], 0, "Ends -tion."),
        _wc("Which is spelt correctly?", ["moral", "morral", "morel"], 0, "Moral."),
    ],
    [
        {"key": "fix", "label": "Fixed weak ending", "hint": "A lucky ending made earned."},
        {"key": "reflect", "label": "Reflection", "hint": "A sentence about change."},
        {"key": "ending", "label": "My ending", "hint": "5 to 7 sentences."},
    ],
    ["A sudden lucky solution.", "Rushing the ending.", "An ending that does not answer the problem.", "Only writing The End.", "Spelling out the moral heavy-handedly."],
    [{"title": "Three Endings", "description": "Write three different endings (happy, open and twist) for the same problem.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the ending answers the problem, the character acts, change is shown, a reflection is included, the last line is strong, and it is 5 to 7 sentences. Sorter: Happy: first two. Open: next two. Twist: last two.",
)

A7L2 = build(
    "s2-eng-a7-l2-planning-a-whole-narrative", "Planning a Whole Narrative",
    "Learn to plan a complete story from orientation to resolution before you write it.",
    "Writing: planning a narrative",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01"],
    {"EN2-CWT-01": "Primary. Plans a whole narrative using a story map and paragraph plan.",
     "EN2-RECOM-01": "Identifies the stages of a narrative in a model text.",
     "EN2-VOCAB-01": "Revises the terms orientation, complication, resolution, paragraph and plan."},
    "We are learning how to plan a whole story so the writing is organised.",
    ["I can name the stages of a narrative.", "I can fill in a story map.", "I can decide what goes in each paragraph.", "I can choose where to put detail.", "I can make a plan for my story."],
    ["orientation", "complication", "resolution", "paragraph", "plan"],
    ["Paper or notebook", "Pencil", "All your work from weeks 4 to 7"],
    "Child has met each stage in earlier lessons. This lesson puts them together in a plan.",
    "Good writers plan before they write. A plan stops a story from wandering and helps you put the best detail in the right place.\n\nA narrative has stages: ORIENTATION (who, where, when), COMPLICATION (the problem and what makes it harder), and RESOLUTION (how it is solved and how it ends).\n\nIn this lesson you will make a full plan for a story you will write next lesson.",
    [
        _step("1", "The stages together",
              "Put the stages in order.\n\n1. Orientation: introduce the character, setting and mood.\n2. Problem: show what the character wants and what goes wrong.\n3. Complication: make it harder, build tension.\n4. Resolution: solve it using what the character does.\n5. Ending: show the change and finish well.\n\nOne story often has one paragraph for each stage, or more for the exciting parts.",
              "Orientation: A foggy harbour at dawn. Problem: the boat is missing.",
              "Five stages, in order.",
              ("Which stage comes first?", ["Orientation", "Resolution", "Complication"], 0, "Orientation introduces the story.")),
        _step("2", "Make a story map",
              "A story map is a simple chart.\n\nWho: the main character (and a name).\nWhere and when: the setting.\nGoal: what they want.\nProblem: what stops them.\nComplication: what makes it harder.\nSolution: how they solve it.\nChange: how they feel at the end.\n\nKeep notes short. Use words and phrases, not full sentences.\n\nChoose ideas that link. The problem should fit the setting and the character's goal.",
              "Who: Mia. Where: lighthouse. Goal: light the lamp. Problem: no matches. Complication: storm. Solution: sparks from flint. Change: braver.",
              "Short notes in each box.",
              ("Story map notes should be...", ["short", "full essays", "blank"], 0, "Use brief notes.")),
        _step("3", "Paragraph plan",
              "Next, decide what goes in each paragraph.\n\nParagraph 1: Orientation. Setting detail and the character.\nParagraph 2: The problem begins.\nParagraph 3: Complication and tension. Slow down.\nParagraph 4: Resolution.\nParagraph 5: Ending and reflection.\n\nWrite one line of notes for each. Mark where you will use show, don't tell, strong verbs, adverbial phrases and dialogue.\n\nPut the most detail in the exciting parts: the complication and tension.",
              "Para 3: storm hits, lamp rattles, heart pounding, short sentence for effect.",
              "One paragraph, one stage.",
              ("Where should you put the most detail?", ["The exciting parts", "Everywhere equally", "The title only"], 0, "Stretch the key moments.")),
        _step("4", "Check your plan",
              "Before you finish, check the plan.\n\n1. Does the character have a clear goal?\n2. Is the problem clear?\n3. Is there a complication?\n4. Does the resolution grow from the problem?\n5. Is there a change at the end?\n6. Is it a size you can finish? Small stories are often best.\n\nFix any weak parts now. It is much easier to change a plan than a full story.",
              "Too big: a trip around the world. Better: one afternoon at the beach.",
              "Check, then fix.",
              ("Is it easier to change a plan or a finished story?", ["A plan", "A finished story", "Same"], 0, "Plans are easy to change.")),
    ],
    "Model answers. Stages in order: orientation, problem, complication, resolution, ending. Story map sample: Who Mia, where lighthouse, goal light the lamp, problem no matches, complication storm, solution sparks from flint, change braver. Paragraph plan: five paragraphs, one per stage, most detail on complication and tension.",
    "1) Put five stages in order. 2) Fill in a story map. 3) Write a paragraph plan. 4) Mark where you will use techniques. 5) Check the plan. 6) Fix any weak parts.",
    "Make a story map and a five-paragraph plan for a narrative. Upload a photo of your plan.",
    CHECK,
    "Is there a clear goal? Is there a problem and a complication? Does the resolution grow from the problem? Is there a change at the end? Is each paragraph planned? Is the story small enough to finish?",
    [
        _q("Which stage comes first?", ["orientation", "resolution", "ending"], 0, "Orientation."),
        _q("A story map has...", ["short notes", "full essays", "nothing"], 0, "Short notes."),
        _q("A paragraph usually covers...", ["one stage or idea", "the whole story", "one word"], 0, "One idea per paragraph."),
        _q("Most detail goes in...", ["the exciting parts", "the title", "the first word"], 0, "Stretch key moments."),
        _q("A plan helps you...", ["stay organised", "avoid writing", "copy"], 0, "It keeps the story on track."),
        _q("A good story size is...", ["small and finishable", "enormous", "one line"], 0, "Small stories work well."),
    ],
    "Upload a photo of your story map and paragraph plan.",
    "Pick a short story from a book of your choice and make a story map for it.",
    [("orientation", "The part that introduces character, setting and time."), ("complication", "A new event that makes the problem harder."), ("resolution", "The part where the problem is solved."), ("paragraph", "A group of sentences about one idea."), ("plan", "Notes made before writing.")],
    [],
    _sort("Which stage?", "Which stage does each line belong to? Tap a group, then Check.",
          ["Orientation", "Complication", "Resolution"],
          [("A foggy harbour at dawn", 0), ("Mia lived in an old lighthouse", 0), ("A storm blew out the lamp", 1), ("The matches were wet", 1), ("Sparks from the flint lit the wick", 2), ("The ships were guided safely home", 2)]),
    [
        _wc("Notes made before writing are a ___.", ["plan", "plane", "plant"], 0, "Plan."),
        _wc("A group of sentences about one idea is a ___.", ["paragraph", "paragram", "parable"], 0, "Paragraph."),
        _wc("The introduction stage is the ___.", ["orientation", "orienteering", "origin"], 0, "Orientation."),
        _wc("Which is spelt correctly?", ["paragraph", "paragragh", "paragraf"], 0, "Paragraph has ph."),
        _wc("Which is spelt correctly?", ["complication", "complikation", "complicasion"], 0, "Ends -tion."),
    ],
    [
        {"key": "map", "label": "Story map", "hint": "Who, where, goal, problem, complication, solution, change."},
        {"key": "plan", "label": "Paragraph plan", "hint": "One line for each paragraph."},
    ],
    ["Starting to write with no plan.", "A story too big to finish.", "A plan with no complication.", "A resolution that does not fit the problem.", "Writing full sentences in the plan."],
    [{"title": "Plan Swap", "description": "Make a plan, then swap with a parent who tells you one thing to strengthen.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the plan has a goal, problem, complication, resolution and change, each paragraph has a purpose, and the story is a manageable size. Sorter: Orientation: foggy harbour, lived in lighthouse. Complication: storm blew out lamp, matches wet. Resolution: sparks lit wick, ships guided home.",
)

A7L3 = build(
    "s2-eng-a7-l3-complex-sentences", "Complex Sentences",
    "Learn how conjunctions join ideas into complex sentences that make your writing flow.",
    "Language: complex sentences",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Writes complex sentences using a range of conjunctions.",
     "EN2-VOCAB-01": "Learns the terms clause, conjunction, main clause, subordinate clause and complex sentence.",
     "EN2-RECOM-01": "Identifies clauses and conjunctions in a text."},
    "We are learning to write complex sentences that join ideas clearly.",
    ["I can say what a clause is.", "I can find the main clause.", "I can use because, although, when and if.", "I can move the extra clause to the front.", "I can write complex sentences correctly."],
    ["clause", "conjunction", "main clause", "subordinate clause", "complex sentence"],
    ["Paper or notebook", "Pencil", "A paragraph from your story"],
    "Child writes simple and compound sentences. Complex sentences are taught from the beginning.",
    "A CLAUSE is a group of words with a verb. A MAIN CLAUSE makes sense on its own: 'Mia lit the lamp.'\n\nA SUBORDINATE CLAUSE adds extra information but cannot stand alone: 'because the storm was coming'.\n\nA COMPLEX SENTENCE has a main clause and at least one subordinate clause, joined by a CONJUNCTION like because, although, when, if, while or after.\n\n'Mia lit the lamp because the storm was coming.'",
    [
        _step("1", "Main and subordinate",
              "A main clause can stand alone as a sentence.\n\nMia lit the lamp. (main clause)\n\nA subordinate clause cannot.\n\nbecause the storm was coming (not a sentence)\n\nIt needs a main clause to complete it. A good test: if it leaves you waiting for more, it is subordinate.\n\nThe conjunction starts the subordinate clause: because, although, when, if, while, after, before, until, unless.",
              "Main: The boat rocked. Subordinate: as the waves rose.",
              "The main clause stands alone.",
              ("Which can stand alone?", ["Mia lit the lamp.", "because it was dark", "although she tried"], 0, "The first is a main clause.")),
        _step("2", "Useful conjunctions",
              "Different conjunctions do different jobs.\n\nReason: because, since, as.\nTime: when, while, after, before, until.\nCondition: if, unless.\nContrast: although, even though, whereas.\n\n'Although she was scared, Mia climbed the stairs.'\n'She waited until the storm passed.'\n'If the lamp fails, the ships will be lost.'\n\nChoose the conjunction that matches what you want to say. Do not just use 'and' and 'but' every time.",
              "Contrast: Although it was late, she kept reading.",
              "Pick the right conjunction for the job.",
              ("Which conjunction shows contrast?", ["although", "because", "after"], 0, "Although shows contrast.")),
        _step("3", "Move the clause",
              "You can put the subordinate clause first or second.\n\nSecond: Mia climbed the stairs although she was scared.\nFirst: Although she was scared, Mia climbed the stairs.\n\nWhen it comes FIRST, put a COMMA after it. When it comes second, you usually do not need one.\n\nMoving the clause to the front varies your sentences and builds tension, because the reader waits for the main action.",
              "When the storm hit, the lamp went out.",
              "Clause first, then a comma.",
              ("When the extra clause comes first, you add...", ["a comma", "a question mark", "nothing"], 0, "A comma follows it.")),
        _step("4", "Write your sentences",
              "Write complex sentences for your own story.\n\n1. Write six complex sentences.\n2. Use at least four different conjunctions.\n3. Put the subordinate clause first in at least two, with a comma.\n4. Underline the conjunction in each.\n5. Check each main clause makes sense on its own.\n6. Avoid very long sentences that are hard to follow.\n\nModel: Although the wind howled, Mia kept the lamp burning until dawn.",
              "Check: Although the wind howled (subordinate), Mia kept the lamp burning (main).",
              "Different conjunctions, commas after fronted clauses.",
              ("How many conjunctions should you use?", ["A variety", "Only and", "None"], 0, "Variety makes writing flow.")),
    ],
    "Model answers. Main clause: stands alone (Mia lit the lamp). Subordinate clause: needs a main clause (because the storm was coming). Conjunctions: because, although, when, if, while, after, until. Fronted clause needs a comma. Sample: Although the wind howled, Mia kept the lamp burning until dawn.",
    "1) Sort ten clauses as main or subordinate. 2) Choose the best conjunction for six gaps. 3) Move the clause to the front in four sentences and add commas. 4) Combine four pairs of simple sentences. 5) Write six complex sentences for your story. 6) Check each one.",
    "Write six complex sentences for your story using at least four different conjunctions. Upload a photo of your writing.",
    CHECK,
    "Does each sentence have a main clause? Did I use at least four conjunctions? Did I put a comma after a fronted clause? Did I underline the conjunctions? Are the sentences clear?",
    [
        _q("A main clause...", ["can stand alone", "cannot stand alone", "has no verb"], 0, "It makes sense alone."),
        _q("A subordinate clause...", ["needs a main clause", "is a full sentence", "has no words"], 0, "It depends on a main clause."),
        _q("Although shows...", ["contrast", "time", "place"], 0, "Although shows contrast."),
        _q("Because shows...", ["reason", "contrast", "place"], 0, "Because shows reason."),
        _q("If the clause comes first you add a...", ["comma", "colon", "dash"], 0, "Comma."),
        _q("Which is a complex sentence?", ["She waited until the storm passed.", "She waited.", "The storm passed."], 0, "It has two clauses joined by until."),
    ],
    "Upload a photo of your six complex sentences.",
    "Find three complex sentences in a book of your choice and underline the conjunctions.",
    [("clause", "A group of words that contains a verb."), ("conjunction", "A word that joins clauses, such as because or although."), ("main clause", "A clause that makes sense on its own."), ("subordinate clause", "A clause that adds information and cannot stand alone."), ("complex sentence", "A sentence with a main clause and a subordinate clause.")],
    [],
    _sort("Conjunction jobs", "What job does each conjunction do? Tap a group, then Check.",
          ["Reason", "Time", "Contrast"],
          [("because", 0), ("since", 0), ("when", 1), ("until", 1), ("although", 2), ("whereas", 2)]),
    [
        _wc("A group of words with a verb is a ___.", ["clause", "clue", "claws"], 0, "Clause."),
        _wc("A joining word like because is a ___.", ["conjunction", "connection", "conclusion"], 0, "Conjunction."),
        _wc("A clause that cannot stand alone is ___.", ["subordinate", "separate", "simple"], 0, "Subordinate."),
        _wc("Which is spelt correctly?", ["although", "altho", "allthough"], 0, "Although."),
        _wc("Which is spelt correctly?", ["conjunction", "conjuntion", "conjuction"], 0, "Conjunction."),
    ],
    [
        {"key": "sentences", "label": "Six complex sentences", "hint": "At least four different conjunctions."},
        {"key": "commas", "label": "Commas", "hint": "Two sentences with the clause first."},
    ],
    ["Using only and and but.", "Forgetting the comma after a fronted clause.", "Writing a subordinate clause as a full sentence.", "Very long sentences that lose the reader.", "Using although and but together."],
    [{"title": "Conjunction Swap", "description": "Write one idea three ways using three different conjunctions, then pick the best.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check each sentence has a main clause, at least four conjunctions appear, a comma follows a fronted clause, and sentences are clear. Sorter: Reason: because, since. Time: when, until. Contrast: although, whereas.",
)

A7L4 = build(
    "s2-eng-a7-l4-spelling-suffixes-ful-less-ly", "Spelling: Suffixes -ful, -less, -ly",
    "Learn how suffixes change a word and how to spell words that use them.",
    "Spelling: suffixes",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-CWT-01"],
    {"EN2-SPELL-01": "Primary. Spells words with the suffixes -ful, -less and -ly accurately.",
     "EN2-VOCAB-01": "Uses suffixes to work out and extend word meaning.",
     "EN2-CWT-01": "Uses suffixed words correctly in sentences."},
    "We are learning how the suffixes -ful, -less and -ly change a word and how to spell them.",
    ["I can say what a suffix is.", "I can say what -ful, -less and -ly mean.", "I can change y to i before -ful, -less and -ly.", "I can spell ten suffixed words.", "I can use suffixed words in sentences."],
    ["suffix", "base word", "-ful", "-less", "-ly"],
    ["Paper or notebook", "Pencil", "A dictionary (your parent will help)"],
    "Child knows prefixes from last week. Suffixes -ful, -less and -ly are taught from the beginning.",
    "A SUFFIX is a group of letters added to the END of a base word. It changes the meaning and often the word type.\n\ncare + ful = careful\ncare + less = careless\nquick + ly = quickly\n\nSuffixes help you build new words. Some need a spelling change when you add them, and you will learn those rules today.",
    [
        _step("1", "What is a suffix?",
              "A suffix goes at the END of a word.\n\n-FUL means full of: careful, helpful, joyful.\n-LESS means without: careless, helpless, fearless.\n-LY often makes an adverb: quickly, slowly, bravely.\n\nNotice that -ful has ONE l. 'Full' has two, but the suffix -ful has one. So it is 'careful', not 'carefull'.\n\nBase word + suffix = new word.",
              "hope + ful = hopeful. hope + less = hopeless.",
              "-ful has one l.",
              ("How is the suffix -ful spelt?", ["One l", "Two l's", "Three l's"], 0, "The suffix -ful has one l.")),
        _step("2", "-ful and -less",
              "Usually you just add the suffix.\n\ncare, careful, careless. help, helpful, helpless. fear, fearful, fearless.\n\nIf the base word ends in a consonant plus y, change the y to i first.\n\nbeauty + ful = beautiful. mercy + less = merciless. pity + ful = pitiful.\n\nFor words that end in a silent e, keep the e before -ful and -less: care, careful, hope, hopeless.\n\nOpposites often come in pairs: hopeful and hopeless, careful and careless.",
              "beauty to beautiful (y to i).",
              "Change y to i. Keep silent e.",
              ("Which is spelt correctly?", ["beautiful", "beautyful", "beautifull"], 0, "Beauty changes y to i.")),
        _step("3", "The suffix -ly",
              "-LY usually turns an adjective into an adverb.\n\nquick, quickly. slow, slowly. brave, bravely. loud, loudly.\n\nIf the base word ends in y, change y to i: happy, happily. angry, angrily. easy, easily.\n\nIf it ends in le, drop the e and add y: gentle, gently. simple, simply. terrible, terribly.\n\nIf it ends in ic, add ally: basic, basically. (Public is an exception: publicly.)\n\nUse -ly adverbs to add detail to verbs: she moved silently.",
              "happy to happily. gentle to gently.",
              "y to i. le to ly.",
              ("Which is spelt correctly?", ["happily", "happyly", "happly"], 0, "Happy changes y to i.")),
        _step("4", "Practise and use them",
              "Now practise.\n\n1. Look, say, cover, write, check these ten words: careful, careless, hopeful, hopeless, beautiful, quickly, bravely, happily, gently, easily.\n2. Underline the suffix in each.\n3. Write the base word beside each.\n4. Write four sentences, each with a different suffixed word.\n5. Check by reading each aloud.\n6. Test yourself with a parent reading the words.\n\nSample: The mouse crept quietly past the sleeping cat.",
              "Sample: She carefully carried the beautiful vase.",
              "Find the suffix, check the rule, check the spelling.",
              ("What do you do for the words that end in y?", ["Change y to i", "Double the y", "Delete the word"], 0, "Change y to i.")),
    ],
    "Model answers. -ful: full of (careful, helpful). -less: without (careless, hopeless). -ly: makes an adverb (quickly, slowly). Rules: change y to i (beautiful, happily, easily); words ending le drop e and add y (gently); ful has one l. Sample sentence: The mouse crept quietly past the sleeping cat.",
    "1) Split ten words into base word and suffix. 2) Add -ful, -less or -ly to eight base words. 3) Match opposite pairs. 4) Spell ten words using look, say, cover, write, check. 5) Write four sentences. 6) Get a spelling test from a parent.",
    "Write four sentences, each with a different suffixed word, then do a ten word spelling test. Upload a photo of your sentences and your test.",
    CHECK,
    "Did I use one l in -ful? Did I change y to i where needed? Did I handle le to ly correctly? Did I use each suffix at least once? Did I check my spelling?",
    [
        _q("A suffix is added...", ["at the end of a word", "at the start", "in the middle"], 0, "Suffixes come last."),
        _q("-ful means...", ["full of", "without", "again"], 0, "Full of."),
        _q("-less means...", ["without", "full of", "again"], 0, "Without."),
        _q("Which is spelt correctly?", ["careful", "carefull", "carful"], 0, "One l in -ful."),
        _q("Which is spelt correctly?", ["beautiful", "beautyful", "beautifull"], 0, "Change y to i."),
        _q("Which is spelt correctly?", ["gently", "gentlely", "gentley"], 0, "Drop e, add y."),
        _q("Which is spelt correctly?", ["easily", "easyly", "easly"], 0, "Change y to i."),
    ],
    "Upload a photo of your four sentences and your spelling test.",
    "Look for five more words that end in -ful, -less or -ly in a book of your choice. Split each into base word and suffix.",
    [("suffix", "Letters added to the end of a word to change its meaning."), ("base word", "The word a suffix is added to."), ("-ful", "A suffix meaning full of."), ("-less", "A suffix meaning without."), ("-ly", "A suffix that often makes an adverb.")],
    [],
    _sort("Suffix sorter", "Which suffix does each word end with? Tap a group, then Check.",
          ["-ful", "-less", "-ly"],
          [("careful", 0), ("hopeful", 0), ("careless", 1), ("fearless", 1), ("quickly", 2), ("bravely", 2)]),
    [
        _wc("Letters added to the end of a word are a ___.", ["suffix", "prefix", "syllable"], 0, "Suffix."),
        _wc("The word a suffix joins is the ___ word.", ["base", "back", "big"], 0, "Base word."),
        _wc("Which is spelt correctly?", ["hopeless", "hopless", "hopelss"], 0, "Hope + less."),
        _wc("Which is spelt correctly?", ["angrily", "angryly", "angryily"], 0, "Change y to i."),
        _wc("Which is spelt correctly?", ["simply", "simplely", "simpley"], 0, "Drop e, add y."),
    ],
    [
        {"key": "split", "label": "Base word and suffix", "hint": "Ten words split into parts."},
        {"key": "sentences", "label": "Four sentences", "hint": "Four different suffixed words."},
        {"key": "test", "label": "Spelling test", "hint": "Ten words read out by a parent."},
    ],
    ["Writing carefull with two l's.", "Forgetting to change y to i.", "Writing gentlely instead of gently.", "Dropping the e in careful.", "Using an adjective where an adverb is needed."],
    [{"title": "Suffix Pairs", "description": "Make a table of ten base words and write the -ful, -less and -ly forms where they exist.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that -ful has one l, y changes to i where needed, le words end in -ly, each suffix is used, and sentences make sense. Sorter: -ful: careful, hopeful. -less: careless, fearless. -ly: quickly, bravely.",
)

LESSONS = [A7L1, A7L2, A7L3, A7L4]
