"""Stage 2 Maths, Week 1 of the programme (four 60-minute lessons). Pass 1: teaching, practice and quizzes. Videos are attached in a later pass.
Outcome codes (MA2-RWN-01, MA2-AR-01) come from nsw_outcomes.py.
Reuses the English helpers, then patches the subject-specific fields (learning area, notes, no reflection prompts).
Register WEEK_1_MATHS in lesson_library.py and raise LESSON_LIBRARY_VERSION so the library re-seeds."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc

CHECK = "Check your work against the checklist before you submit."


def _maths(lesson, check_note):
    lesson["learning_area"] = "Mathematics"
    lesson["reflection_prompts"] = []
    lesson["parent_notes"] = ("Practice lesson only. Quiz scores are formative; competency is decided by the fortnightly mini exam. "
                              "Pitched for a child who may be working near a Year 2 level in Year 3: every idea is built from the ground up, so go slowly and let him use real objects or drawings. "
                              + check_note + "\n\nAnswer key for the guided practice:\n" + lesson["parent_notes"].split("Answer key for the guided practice:\n")[-1].split("\n\nVerify")[0]
                              + "\n\nVerify the outcome mapping against the NESA Mathematics K-10 syllabus.")
    lesson["source_note"] = "Outcome codes from the NSW Mathematics K-10 Syllabus (NESA 2022), Stage 2. Parent to verify alignment on curriculum.nsw.edu.au."
    lesson["offline_alternative"] = "Complete all tasks on paper with real objects such as bundles of sticks or coins. Read the questions aloud. Videos can be skipped if the worked example is read aloud."
    return lesson


M1 = _maths(build(
    "s2-math-w01-l1-place-value-to-1000", "Place Value Builders: Ones, Tens and Hundreds",
    "The Number Vault only opens for a builder who understands where every digit lives. Build numbers up to 999, read them, write them and put them in order.",
    "Number: place value to 1000",
    ["MA2-RWN-01"],
    {"MA2-RWN-01": "Primary. Builds, reads, writes, partitions, compares and orders three-digit numbers and explains the role of zero as a place holder. This is the foundation for four- and five-digit numbers in the next lesson."},
    "We are learning how the place of a digit gives it its value in numbers up to 1000.",
    ["I can say the value of each digit in a three-digit number.", "I can build a number with hundreds, tens and ones.", "I can write a number in expanded form.", "I can explain what zero does in a number like 305.", "I can compare and order three-digit numbers using < and >."],
    ["digit", "place value", "ones", "tens", "hundreds", "expanded form", "partition", "place holder"],
    ["Paper or notebook", "Pencil", "Ten-frames or bundles of 10 sticks (optional)", "Coins or counters (optional)"],
    "Child can count to 100 and knows that ten ones make one ten.",
    "Every number is built from just ten digits: 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9. So how can we make a number as big as 742 with only ten digits? The secret is that a digit's value depends on its PLACE. The 7 in 742 is not worth 7. It is worth 700, because it sits in the hundreds place.\n\nThis idea is called PLACE VALUE. It is the most important idea in the whole of number maths, because adding, subtracting, multiplying and dividing all depend on it.\n\nIn this lesson you will start with ones and tens, which you already know, and build up to hundreds. You will make numbers, take them apart, say what each digit is worth, learn why zero matters, and put numbers in order.",
    [
        _step("1", "Digits and ones",
              "A DIGIT is a single symbol used to write numbers. There are ten of them: 0 to 9. A number can have one digit (7), two digits (42) or three digits (742).\n\nThe smallest place is the ONES place. It is the last digit on the right. If you have 6 single counters, you have 6 ones. A single object is always worth one.\n\nWe can only keep 9 ones in the ones place. When we get a tenth one, we cannot write '10 ones' as a single digit, so we swap those ten ones for one new thing in the next place along. That swap is what the next step is about.",
              "The number 8 is 8 ones. The number 25 has a 5 in the ones place, so 5 ones.",
              "The ones place is always the right-hand digit.",
              ("In the number 63, which digit is in the ones place?", ["6", "3", "63"], 1, "The right-hand digit is the ones digit.")),
        _step("2", "Tens: bundling ten ones",
              "Counting single objects gets slow, so we bundle. Ten ones are tied together to make one TEN. A ten is a single bundle that is worth ten.\n\nThe TENS place is the second digit from the right. In the number 47 there are 4 tens and 7 ones. The 4 is worth 40, not 4, because it counts bundles of ten. 40 + 7 = 47.\n\nThink of a pencil case. If 10 pencils fit in each box, then 3 full boxes and 5 loose pencils is 35 pencils. The 3 counts boxes (tens) and the 5 counts loose ones.\n\nWhen you say a two-digit number, you are saying the tens first, then the ones: 'forty-seven' means forty and seven.",
              "58 = 5 tens and 8 ones = 50 + 8. The 5 is worth 50.",
              "The same digit is worth different amounts in different places. In 55, the left 5 is worth 50 and the right 5 is worth 5.",
              ("What is the value of the 3 in 36?", ["3", "30", "300"], 1, "It is in the tens place, so it is 3 tens = 30.")),
        _step("3", "Hundreds: bundling ten tens",
              "What happens when we have 10 tens? We cannot write 10 in the tens place, so we bundle again. Ten tens make one HUNDRED. Imagine ten boxes of ten pencils packed in one big carton: that carton holds 100 pencils.\n\nThe HUNDREDS place is the third digit from the right. In 342 there are 3 hundreds, 4 tens and 2 ones. The 3 is worth 300, the 4 is worth 40 and the 2 is worth 2. 300 + 40 + 2 = 342.\n\nSo each place is worth ten times the place to its right: ones, then tens (10 times more), then hundreds (10 times more again). Counting up to 999 uses 9 hundreds, 9 tens and 9 ones. One more makes 1000.",
              "574 = 5 hundreds + 7 tens + 4 ones = 500 + 70 + 4. The 5 is worth 500.",
              "Ten ones make a ten. Ten tens make a hundred. Ten hundreds make a thousand.",
              ("How many tens are in one hundred?", ["1", "10", "100"], 1, "Ten tens make a hundred.")),
        _step("4", "Reading, writing and expanded form",
              "To READ a three-digit number say the hundreds, then 'and' (in Australia we often say it), then the tens and ones. 435 is 'four hundred and thirty-five'. To WRITE it from words, do the same in reverse: 'six hundred and eight' is 608.\n\nEXPANDED FORM writes a number as the sum of the value of each digit. 435 = 400 + 30 + 5. This is also called PARTITIONING, because we split the number into its place value parts.\n\nYou can also partition by counting hundreds, tens and ones: 435 is 4 hundreds, 3 tens and 5 ones. Both ways show the same thing.\n\nTo go from expanded form back to a number, write each part's digit in its own place: 700 + 20 + 9 = 729.",
              "Six hundred and twelve = 600 + 10 + 2 = 612. 281 = 200 + 80 + 1.",
              "Say it, write it, and split it. All three describe the same number.",
              ("What is 300 + 40 + 6?", ["346", "364", "3 046"], 0, "3 hundreds, 4 tens, 6 ones is 346.")),
        _step("5", "Zero: the place holder",
              "Zero looks like it is worth nothing, but in a number it has a very important job. It is a PLACE HOLDER: it holds a place open so the other digits stay in the right places.\n\nCompare 35 and 305. The number 35 is 3 tens and 5 ones. In 305 we need a different number: 3 hundreds, no tens and 5 ones. If we left the zero out we would get 35, which is much smaller. So the zero in 305 says 'there are no tens here'.\n\nZero also appears at the end: 450 is 4 hundreds, 5 tens and 0 ones. The zero says there are no ones, so the 5 stays in the tens place and is worth 50.\n\nA good habit: when you partition a number with a zero, write the zero part as 0, or skip it. 305 = 300 + 0 + 5 = 300 + 5.",
              "609 = 600 + 0 + 9. 570 = 500 + 70 + 0. 800 = 8 hundreds, 0 tens, 0 ones.",
              "Never leave a zero out when you write a number. It changes the value of every digit to its left.",
              ("What does the 0 mean in 407?", ["There are no tens", "There are no ones", "The number is small"], 0, "The zero is in the tens place, so there are 0 tens.")),
        _step("6", "Comparing and ordering",
              "To compare two numbers, look at the places from the LEFT. The biggest place decides first. If the hundreds digits are different, the bigger hundreds digit is the bigger number. If the hundreds match, look at the tens. If they match too, look at the ones.\n\nThe symbol > means 'is greater than' and < means 'is less than'. The open mouth faces the bigger number, like a hungry crocodile. 542 > 524 because the hundreds match (5), then 4 tens is more than 2 tens.\n\nTo order numbers, find the smallest first, then the next, and so on. Ascending order goes smallest to largest. Descending order goes largest to smallest. Always compare the hundreds first, then the tens, then the ones.\n\nOne more skill: 10 more or 10 less changes the tens digit by one. 100 more or 100 less changes the hundreds digit by one. 10 more than 347 is 357. 100 less than 347 is 247.",
              "Order 316, 361 and 136: hundreds 1 < 3, so 136 is smallest. Then 316 and 361 both have 3 hundreds, and 1 ten < 6 tens, so 316 < 361. Order: 136, 316, 361.",
              "Start from the left. The first place that is different decides the answer.",
              ("Which is greater?", ["598", "589", "They are equal"], 0, "The hundreds match, and 9 tens is more than 8 tens.")),
    ],
    "Number 538. Hundreds: 5, worth 500. Tens: 3, worth 30. Ones: 8, worth 8. Expanded form: 500 + 30 + 8. In words: five hundred and thirty-eight. Compare with 583: hundreds match (5), tens 3 < 8, so 538 < 583. 10 more than 538 is 548. 100 less than 538 is 438. Number 706: the zero means no tens, so 700 + 6 = 706, not 76.",
    "Work in your notebook. Part A (value): write the value of the underlined digit: 4 in 4_72 style, written as: the 7 in 372, the 3 in 372, the 2 in 372, the 9 in 905. Part B (build): write the number for 6 hundreds, 2 tens, 9 ones; 4 hundreds, 0 tens, 7 ones; 9 tens and 3 hundreds. Part C (expanded form): write 483, 750 and 206 in expanded form. Part D (compare): put <, > or = in 459 __ 495; 612 __ 621; 300 + 20 + 5 __ 325. Part E (order): put 807, 780, 870 and 708 in ascending order. Part F: write 10 more and 100 less than 624.",
    "Stage 1 (make): use paper, coins, bundles or drawings to build three numbers: one with a zero in the tens place, one with a zero in the ones place and one with no zeros.\nStage 2 (record): for each number write it in digits, in words and in expanded form, and say the value of each digit.\nStage 3 (compare): write two three-digit numbers of your own and compare them using < or >, then explain which place decided it.\nStage 4 (order): write five three-digit numbers of your own and order them from smallest to largest, then largest to smallest.",
    "Write the answers to each task in your notebook and say them aloud to a listener.",
    "Did I build three numbers? Did I write each in digits, words and expanded form? Did I include a number with a zero? Did I compare two numbers and name the deciding place? Did I order five numbers both ways?",
    [
        _q("What is the value of the 7 in 472?", ["7", "70", "700"], 1, "The 7 is in the tens place."),
        _q("What number is 3 hundreds, 4 tens and 6 ones?", ["346", "364", "643"], 0, "Hundreds first, then tens, then ones."),
        _q("How many tens make one hundred?", ["1", "10", "100"], 1, "Ten tens make a hundred."),
        _q("What is 400 + 60 + 2?", ["426", "462", "4 062"], 1, "4 hundreds, 6 tens, 2 ones."),
        _q("What does the zero in 305 show?", ["There are no tens", "There are no hundreds", "There are no ones"], 0, "The zero holds the tens place."),
        _q("Which number is greater?", ["598", "589", "They are equal"], 0, "Hundreds match, and 9 tens > 8 tens."),
        _q("Which list is in ascending order?", ["245, 254, 425", "425, 254, 245", "254, 245, 425"], 0, "Ascending means smallest to largest."),
        _q("What is 100 more than 347?", ["357", "447", "348"], 1, "Add 1 to the hundreds digit."),
        _q("What is 10 less than 520?", ["510", "420", "519"], 0, "Take 1 from the tens digit."),
        _q("Which number is eight hundred and six?", ["860", "806", "8 006"], 1, "8 hundreds, 0 tens, 6 ones."),
    ],
    "Upload a photo of your three built numbers (digits, words and expanded form), your comparison and your two ordered lists.",
    "Make the biggest and smallest three-digit numbers you can using the digits 2, 7 and 5 once each, and explain how you chose.",
    [("digit", "One of the ten symbols 0 to 9 used to write numbers."), ("place value", "The value a digit has because of where it sits in a number."),
     ("ones", "The right-hand place. Single items."), ("tens", "The second place. Bundles of ten."), ("hundreds", "The third place. Ten tens."),
     ("expanded form", "Writing a number as the sum of the value of its digits, like 400 + 30 + 5."), ("partition", "To split a number into parts."), ("place holder", "A zero that holds a place so other digits stay in the right places.")],
    [],
    _sort("Which place?", "In which place is the digit 5 in each number? Tap a place, then press Check.",
          ["Ones", "Tens", "Hundreds"],
          [("the 5 in 215", 0), ("the 5 in 465", 0), ("the 5 in 705", 0), ("the 5 in 152", 1), ("the 5 in 358", 1), ("the 5 in 950", 1), ("the 5 in 512", 2), ("the 5 in 583", 2), ("the 5 in 501", 2)]),
    [
        _wc("Ten tens make one ___.", ["hundred", "hundered", "hundrid"], 0, "Hundred ends in -dred."),
        _wc("Splitting a number into place value parts is called ___.", ["partitioning", "partisioning", "pertitioning"], 0, "Partition begins with part."),
        _wc("A single symbol such as 7 is a ___.", ["digit", "digget", "dijit"], 0, "Digit has a g."),
        _wc("Smallest to largest is ___ order.", ["ascending", "asending", "ascendig"], 0, "Ascending has sc in the middle."),
    ],
    [
        {"key": "n1", "label": "Number with a zero in the tens", "hint": "For example 4_7 with a zero in the middle."},
        {"key": "n2", "label": "Number with a zero in the ones", "hint": "For example 6_0 ending in zero."},
        {"key": "n3", "label": "Number with no zeros", "hint": "Any three-digit number without a zero."},
    ],
    ["Reading the digit as its face value (saying the 7 in 472 is 7 instead of 70).", "Leaving out the zero place holder (writing 35 for three hundred and five).", "Writing the digits in the wrong order when writing from words.", "Comparing from the right instead of the left.", "Mixing up < and >."],
    [{"title": "Place Value Shop", "description": "Use coins or paper money: ten 1s, ten 10s, ten 100s. Ask a family member for a number up to 999 and make it with the fewest notes.", "type": "create", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 70; 300; 2; 900 (the 9 in 905 is worth 900). Part B: 629; 407; 390 (3 hundreds + 9 tens = 390). Part C: 400 + 80 + 3; 700 + 50; 200 + 6. Part D: 459 < 495; 612 < 621; 300 + 20 + 5 = 325. Part E: 708, 780, 807, 870. Part F: 10 more than 624 is 634; 100 less is 524.",
), "Let him build with real bundles or coins first if the digits feel abstract. Many errors come from skipping the zero place holder.")


M2 = _maths(build(
    "s2-math-w01-l2-place-value-to-10000", "Bigger Numbers: Thousands and Tens of Thousands",
    "The Number Vault has a second door, and it needs thousands. Grow your place value skills to four- and five-digit numbers and learn how zero holds places in big numbers.",
    "Number: place value to tens of thousands",
    ["MA2-RWN-01"],
    {"MA2-RWN-01": "Primary. Extends place value to thousands and tens of thousands: reads, writes, partitions, orders, and adds or subtracts 1, 10, 100 and 1000. Builds directly on the three-digit foundation from the previous lesson."},
    "We are learning how place value works for numbers up to tens of thousands.",
    ["I can say the value of each digit in a four- or five-digit number.", "I can read and write numbers up to 10 000 and beyond.", "I can partition a big number in more than one way.", "I can use zero as a place holder in big numbers.", "I can say 1, 10, 100 or 1000 more or less than a number."],
    ["thousands", "ten thousands", "place value chart", "partition", "place holder", "ascending", "descending"],
    ["Paper or notebook", "Pencil", "Ruler to draw a place value chart"],
    "Child can read, write and partition three-digit numbers and knows that ten tens make a hundred.",
    "In the last lesson you learned that ten ones make a ten, ten tens make a hundred, and each new place is ten times bigger than the one before. The pattern keeps going. Ten hundreds make a THOUSAND. Ten thousands make ten thousand (10 000).\n\nBig numbers are used for real things: the number of people at a football match, the price of a car, the distance between two cities. They look scary, but they follow the same pattern as small numbers.\n\nIn this lesson you will build four-digit and five-digit numbers one place at a time, use a place value chart to organise them, learn how zero holds a place, and practise adding and subtracting 1, 10, 100 and 1000.",
    [
        _step("1", "Thousands",
              "Ten hundreds make one THOUSAND. 10 x 100 = 1 000. The THOUSANDS place is the fourth place from the right.\n\nIn 3 452 there are 3 thousands, 4 hundreds, 5 tens and 2 ones. The 3 is worth 3 000. In full: 3 000 + 400 + 50 + 2 = 3 452.\n\nWe read a four-digit number by saying the thousands first: 'three thousand, four hundred and fifty-two'. In Australian schools four-digit numbers can be written with or without a space (3452 or 3 452). Numbers with five or more digits use a space so they are easy to read: 12 345. We do not use commas.\n\nThe fourth place is built exactly like the earlier ones. The only new word is 'thousand'.",
              "6 218 = 6 thousands + 2 hundreds + 1 ten + 8 ones = 6 000 + 200 + 10 + 8.",
              "Each place is ten times bigger than the place to its right.",
              ("What is the value of the 6 in 6 702?", ["6", "600", "6 000"], 2, "It sits in the thousands place.")),
        _step("2", "Using a place value chart",
              "A PLACE VALUE CHART is a table with a column for each place: Ten thousands, Thousands, Hundreds, Tens, Ones. You write one digit in each column and the chart shows you the value of each digit.\n\nTo put 24 508 in the chart: Ten thousands 2, Thousands 4, Hundreds 5, Tens 0, Ones 8. The 0 sits in the tens column to show that there are no tens.\n\nTo read a number from the chart, read from the left. The first place says how big the number is. 24 508 is 'twenty-four thousand, five hundred and eight'.\n\nThe chart is a tool. After a few goes you will see the columns in your head and will not need to draw it.",
              "Chart for 7 063: Thousands 7, Hundreds 0, Tens 6, Ones 3. So 7 000 + 0 + 60 + 3 = 7 063.",
              "Draw the columns first, then fill in one digit per column, starting from the right.",
              ("In 24 508, which digit is in the ten thousands place?", ["2", "4", "5"], 0, "The left-most digit is the ten thousands.")),
        _step("3", "Zero in bigger numbers",
              "Zero keeps its job as a place holder in bigger numbers. In 5 080 there are 5 thousands, 0 hundreds, 8 tens and 0 ones. If you left out a zero the number would change completely: 58 is not 5 080.\n\nTo write a number from words, use a chart if you need one. 'Nine thousand and forty' has 9 thousands, 0 hundreds, 4 tens, 0 ones, so it is 9 040.\n\nWhen you say a number aloud you skip the zero places: 5 080 is 'five thousand and eighty'. But when you WRITE it, every zero must be there.\n\nA useful check: count the digits. Thousands means four digits, ten thousands means five digits.",
              "Three thousand and seven = 3 007. Twelve thousand, four hundred = 12 400.",
              "When a place is skipped in the words, it is a zero in the number.",
              ("How do you write 'four thousand and five'?", ["4 005", "4 050", "405"], 0, "4 thousands, 0 hundreds, 0 tens, 5 ones.")),
        _step("4", "Partitioning in different ways",
              "There is more than one way to split a big number. The standard way uses each place: 4 325 = 4 000 + 300 + 20 + 5.\n\nYou can also group places together. 4 325 is 43 hundreds and 25 ones, because 4 thousands and 3 hundreds make 43 hundreds. It is also 432 tens and 5 ones.\n\nThis idea is called FLEXIBLE PARTITIONING. It is useful when you add and subtract because you can choose the split that makes the sum easiest.\n\nCheck: 3 000 + 1 200 + 40 + 5 is also 4 245. Whatever way you split it, the parts must add back to the whole number.",
              "3 450 = 3 000 + 400 + 50 = 34 hundreds + 5 tens = 345 tens.",
              "The number stays the same. Only the way we split it changes.",
              ("How many hundreds are in 2 500?", ["5", "25", "250"], 1, "2 thousands is 20 hundreds, plus 5 hundreds makes 25 hundreds.")),
        _step("5", "Comparing and ordering big numbers",
              "The method is the same: start from the LEFT and find the first place that is different. For 3 405, 3 450 and 3 045: the thousands are 3, 3 and 3. Look at the hundreds: 4, 4 and 0. So 3 045 is smallest. Now compare 3 405 and 3 450: the hundreds match (4), then 0 tens < 5 tens, so 3 405 < 3 450.\n\nA number with more digits is always bigger, as long as it has no leading zeros. 10 000 is bigger than 9 999 because it has five digits.\n\nOrder from smallest (ascending) or from largest (descending), and use < and > to show the order. Write the list neatly in a line so you can check each pair.",
              "Order 4 021, 4 201, 4 012: thousands match; hundreds 0, 2, 0; so 4 201 is largest. Then 4 021 and 4 012: tens 2 > 1, so 4 021 > 4 012. Descending: 4 201, 4 021, 4 012.",
              "Check left to right: first place that is different decides.",
              ("Which is the smallest?", ["3 405", "3 450", "3 045"], 2, "The hundreds digit 0 is the smallest.")),
        _step("6", "1, 10, 100 and 1000 more or less",
              "When you add or take away one of these amounts, only one digit changes (unless you cross a boundary).\n\n1 more changes the ones digit. 10 more changes the tens digit. 100 more changes the hundreds digit. 1 000 more changes the thousands digit. The same goes for 'less'.\n\n5 207: 10 more is 5 217. 100 more is 5 307. 1 000 more is 6 207. 100 less is 5 107.\n\nSometimes you cross a boundary: 4 596 + 10 = 4 606 (the tens digit 9 becomes 0 and the hundreds digit goes up). 9 990 + 10 = 10 000. Think of a car odometer rolling over.\n\nSay the change out loud first: 'I am adding 100, so the hundreds digit goes up by one.'",
              "3 456: +1 = 3 457; +10 = 3 466; +100 = 3 556; +1 000 = 4 456. 6 800: -1 000 = 5 800.",
              "Find the place that matches the amount, then change that digit.",
              ("What is 1 000 more than 3 456?", ["3 556", "4 456", "3 466"], 1, "Add one to the thousands digit.")),
    ],
    "Number 6 207. Chart: Thousands 6, Hundreds 2, Tens 0, Ones 7. In words: six thousand, two hundred and seven. Expanded: 6 000 + 200 + 7. As hundreds: 62 hundreds and 7 ones. 10 more: 6 217. 100 more: 6 307. 1 000 less: 5 207. Comparing with 6 270: thousands and hundreds match (6, 2), tens 0 < 7, so 6 207 < 6 270.",
    "Work in your notebook. Part A (chart): draw a place value chart for 4 035, 18 260 and 7 008. Part B (value): write the value of the 4 in 4 125, 2 413 and 3 241. Part C (words to numbers): write 'five thousand, three hundred and eighty', 'nine thousand and sixty-one' and 'twenty thousand'. Part D (partition): write 5 806 two ways: standard and as hundreds and ones. Part E (order): put 7 092, 7 902, 7 029 and 7 209 in descending order. Part F (change): find 1 more, 10 more, 100 less and 1 000 more than 4 596.",
    "Stage 1 (choose): pick five four-digit or five-digit numbers (include one with a zero in the middle, and one that is 10 000 or more).\nStage 2 (chart and words): put each in a place value chart and write it in words and in expanded form.\nStage 3 (change): for each number write 10 more, 100 less and 1 000 more.\nStage 4 (order): order your five numbers from smallest to largest and write a < sign between each pair.",
    "Write the answers to each task in your notebook and say them aloud to a listener.",
    "Did I choose five numbers with a zero and one over 10 000? Did I use a chart, words and expanded form? Did I find 10 more, 100 less and 1 000 more? Did I order them with < signs?",
    [
        _q("How many hundreds make one thousand?", ["10", "100", "1 000"], 0, "Ten hundreds make a thousand."),
        _q("What is 4 000 + 300 + 20 + 5?", ["4 325", "4 235", "43 205"], 0, "Thousands, hundreds, tens, ones in order."),
        _q("What is the value of the 6 in 6 702?", ["6", "600", "6 000"], 2, "The thousands place."),
        _q("How do you write 'four thousand and five'?", ["4 005", "4 050", "405"], 0, "No hundreds, no tens, 5 ones."),
        _q("5 080 has how many tens?", ["0", "8", "80"], 1, "The tens digit is 8."),
        _q("Which is the largest?", ["3 405", "3 450", "3 045"], 1, "Hundreds match, 5 tens > 0 tens."),
        _q("What is 100 less than 5 207?", ["5 107", "4 207", "5 197"], 0, "Take 1 from the hundreds digit."),
        _q("What is 10 more than 4 596?", ["4 597", "4 606", "4 696"], 1, "The 9 tens roll over to the next hundred."),
        _q("How many hundreds are in 2 500?", ["5", "25", "250"], 1, "20 hundreds + 5 hundreds."),
        _q("Which number has five digits?", ["9 999", "10 000", "1 000"], 1, "10 000 has five digits."),
    ],
    "Upload a photo of your five numbers in charts, words and expanded form, the 10 more, 100 less and 1 000 more answers, and your ordered list.",
    "Write the largest and smallest four-digit numbers you can make with the digits 3, 0, 8 and 5, and explain why zero cannot go first.",
    [("thousands", "The fourth place from the right. Ten hundreds."), ("ten thousands", "The fifth place from the right. Ten thousands."),
     ("place value chart", "A table with a column for each place that shows the value of each digit."), ("partition", "To split a number into parts."),
     ("place holder", "A zero that keeps other digits in the right place."), ("ascending", "Smallest to largest."), ("descending", "Largest to smallest.")],
    [],
    _sort("Which place?", "In which place is the digit 4 in each number? Tap a place, then press Check.",
          ["Ones", "Tens", "Hundreds", "Thousands"],
          [("the 4 in 3 241", 3 - 3), ("the 4 in 2 054", 0), ("the 4 in 7 340", 1), ("the 4 in 1 642", 1), ("the 4 in 9 428", 2), ("the 4 in 5 401", 2), ("the 4 in 4 120", 3), ("the 4 in 4 953", 3)]),
    [
        _wc("Ten hundreds make one ___.", ["thousand", "thosand", "thousend"], 0, "Thousand has ou in the middle."),
        _wc("Largest to smallest is ___ order.", ["descending", "decending", "discending"], 0, "Descending has sc."),
        _wc("The place value ___ shows a column for each place.", ["chart", "chat", "chrat"], 0, "Chart ends -art."),
    ],
    [
        {"key": "n1", "label": "My five numbers", "hint": "Include a zero in the middle and a number over 10 000."},
        {"key": "n2", "label": "Chart", "hint": "Draw the place value column for each number."},
        {"key": "n3", "label": "Order", "hint": "List the numbers smallest to largest."},
    ],
    ["Leaving out zeros when writing a number from words.", "Writing commas or putting spaces in the wrong places.", "Forgetting that 10 more can change the hundreds digit (4 596 + 10).", "Comparing numbers by their last digit.", "Reading the digit by its face value instead of place value."],
    [{"title": "Odometer Rollover", "description": "Write five numbers close to a rollover, such as 3 998, 5 099 and 9 995. Add 1, 10 and 100 to each and record what happens to the digits.", "type": "investigation", "difficulty": "stretch", "evidence_type": "photo"}],
    "Part A: 4 035: Th 4, H 0, T 3, O 5. 18 260: TTh 1, Th 8, H 2, T 6, O 0. 7 008: Th 7, H 0, T 0, O 8. Part B: the 4 in 4 125 is 4 000; in 2 413 it is 400; in 3 241 it is 40. Part C: 5 380; 9 061; 20 000. Part D: 5 000 + 800 + 6; 58 hundreds + 6 ones. Part E (descending): 7 902, 7 209, 7 092, 7 029. Part F: 4 597; 4 606; 4 496; 5 596.",
), "The chart is the key tool this week. Watch that he writes every zero.")


M3 = _maths(build(
    "s2-math-w01-l3-addition-strategies", "Addition Toolkit: Mental and Written Strategies",
    "A pile of numbers needs adding, and a good mathematician picks the right tool for each sum. Learn four mental strategies and the written column method.",
    "Number: addition strategies",
    ["MA2-AR-01"],
    {"MA2-AR-01": "Primary. Selects and uses mental strategies (bridging ten, partitioning, rounding and adjusting) and the written column method with regrouping for addition involving two- and three-digit numbers."},
    "We are learning to choose and use strategies to add two- and three-digit numbers.",
    ["I can add by bridging to the next ten.", "I can add by partitioning into tens and ones.", "I can add by rounding and adjusting.", "I can use the column method and regroup.", "I can check an addition by estimating or reversing it."],
    ["addition", "sum", "bridge", "partition", "compensate", "regroup", "column method", "estimate"],
    ["Paper or notebook", "Pencil", "Squared paper (helps line up columns)"],
    "Child knows number facts to 20 and place value to 1000.",
    "Addition is joining two or more amounts to find a total. The answer to an addition is called the SUM. There is more than one good way to find a sum, and expert mathematicians choose the one that is easiest for the numbers in front of them.\n\nThis lesson gives you four tools. The first three are mental strategies: bridging to the next ten, partitioning and rounding then adjusting. The fourth is the written column method, which always works, even for big numbers.\n\nEvery strategy depends on place value, so use what you learned in the last two lessons. When you finish a sum, you will also learn two quick ways to check that your answer makes sense.",
    [
        _step("1", "Make ten and bridge to the next ten",
              "The easiest numbers to work with are tens. BRIDGING means adding in two jumps: first to the next ten, then the rest.\n\n28 + 7. How far is 28 from the next ten? 2. So split 7 into 2 and 5. 28 + 2 = 30. 30 + 5 = 35.\n\nThis uses number bonds. A number bond is a pair of numbers that add to a target. 2 + 8 = 10, 3 + 7 = 10, 4 + 6 = 10. Knowing these means you can bridge quickly.\n\nYou can draw it on a number line: start at 28, jump 2 to 30, then jump 5 to 35. Bridging is best when one number is just under a ten, like 28, 47 or 59.",
              "59 + 6: 59 + 1 = 60, 60 + 5 = 65.",
              "Ask: how far to the next ten? Then split the other number to match.",
              ("What is 37 + 5 using bridging?", ["42", "41", "43"], 0, "37 + 3 = 40, then 40 + 2 = 42.")),
        _step("2", "Partitioning: tens and ones",
              "PARTITIONING means splitting numbers into tens and ones, adding the tens, adding the ones, then combining.\n\n47 + 36. Split: 40 + 7 and 30 + 6. Add the tens: 40 + 30 = 70. Add the ones: 7 + 6 = 13. Combine: 70 + 13 = 83.\n\nAnother version keeps the first number whole and splits only the second: 47 + 30 = 77, then 77 + 6 = 83. It is the same answer by a shorter route.\n\nPartitioning works best when no big numbers are needed for the ones, and it works for three digits too: 235 + 142 is 200 + 100 = 300, 30 + 40 = 70, 5 + 2 = 7, so 377.",
              "52 + 36: 50 + 30 = 80, 2 + 6 = 8, so 88. 235 + 142 = 377.",
              "Add the biggest places first, then the smaller places, then combine.",
              ("What is 34 + 25?", ["59", "49", "69"], 0, "30 + 20 = 50, 4 + 5 = 9, so 59.")),
        _step("3", "Rounding and adjusting (compensation)",
              "Some numbers are very close to a friendly ten or hundred, like 9, 19, 29 or 99. Instead of adding them directly, round up, add, then adjust by taking away the extra. This is called COMPENSATION.\n\n58 + 39. 39 is 1 less than 40. So 58 + 40 = 98, then take away the extra 1 to get 97.\n\nThe rule: if you added too much, take it back. If you rounded 39 up to 40 you added 1 too many, so subtract 1 at the end.\n\nThis works for adding 9: 67 + 9 = 67 + 10 - 1 = 76. It also works for 99: 245 + 99 = 245 + 100 - 1 = 344.\n\nTo avoid mistakes, say it out loud: 'I added 1 extra, so I take 1 away.'",
              "46 + 29 = 46 + 30 - 1 = 75. 63 + 19 = 63 + 20 - 1 = 82.",
              "Round up to make the sum easy, then give back what you added too much.",
              ("What is 75 + 19?", ["94", "95", "93"], 0, "75 + 20 = 95, then take away 1 to get 94.")),
        _step("4", "The column method with regrouping",
              "For bigger numbers we write them in columns so that ones sit under ones, tens under tens and hundreds under hundreds. Always start from the right with the ones.\n\nAdd the ones. If the total is 10 or more, REGROUP: write the ones digit under the line and carry the ten to the tens column. Then add the tens (including the carried one), and do the same again with the hundreds.\n\n358 + 247. Ones: 8 + 7 = 15, write 5, carry 1 to the tens. Tens: 5 + 4 + 1 = 10, write 0, carry 1 to the hundreds. Hundreds: 3 + 2 + 1 = 6. Answer: 605.\n\nThe carry is not magic. It is the bundling you already know: ten ones are bundled into one ten and moved left. Line up the columns carefully, because crooked columns cause most mistakes.",
              "  358\n+ 247\n  605\nOnes 15 (write 5, carry 1). Tens 10 (write 0, carry 1). Hundreds 6.",
              "Start on the right. Carry when a column makes ten or more.",
              ("In 358 + 247, what do you write for the ones column?", ["15", "5 and carry 1", "1"], 1, "15 ones is 1 ten and 5 ones.")),
        _step("5", "Choosing a strategy",
              "No strategy is best for every sum. Look at the numbers before you start.\n\nIs one number just under a ten (like 28 or 59)? Try bridging. Is the sum made of friendly tens and few carries (like 34 + 25)? Try partitioning. Is one number just under a ten or a hundred (like 39 or 98)? Try rounding and adjusting. Is it a big sum with many carries? Use the column method.\n\nYou can always switch. If one strategy feels tangled, try another. Good mathematicians say, 'I used ___ because the numbers were ___.'\n\nFor each strategy, write the equation clearly. A tidy line of working helps you notice mistakes.",
              "28 + 7: bridging (28 is near 30). 63 + 39: round 39 to 40. 41 + 36: partition. 489 + 276: column method.",
              "The numbers choose the tool.",
              ("Which strategy suits 63 + 39?", ["Round 39 to 40 and adjust", "Always use columns", "Guess"], 0, "39 is one under 40, so rounding is fast.")),
        _step("6", "Checking your answer",
              "Always check. There are two quick ways.\n\nFirst, ESTIMATE: round both numbers, add, and see whether your answer is close. 358 + 247 is about 360 + 250 = 610, so 605 is sensible. If you had got 505 or 705 you would know there is an error.\n\nSecond, REVERSE it with subtraction. If 358 + 247 = 605, then 605 - 247 should be 358. Addition and subtraction undo each other, so they are inverse operations.\n\nChecking takes ten seconds and saves you from careless mistakes. Do it every time.",
              "47 + 36 = 83. Estimate: 50 + 40 = 90, close to 83. Reverse: 83 - 36 = 47. Correct.",
              "Estimate for sense, reverse for certainty.",
              ("Which operation reverses addition?", ["Subtraction", "Multiplication", "Counting"], 0, "Subtraction undoes addition.")),
    ],
    "Sum: 58 + 39. Look at the numbers: 39 is just under 40, so rounding and adjusting suits it. 58 + 40 = 98. I added 1 too many, so 98 - 1 = 97. Check by estimating: 60 + 40 = 100, so 97 is close. Check by reversing: 97 - 39 = 58. Correct. Another sum: 358 + 247. Many carries, so use columns: ones 15, write 5 carry 1; tens 10, write 0 carry 1; hundreds 6. Answer 605.",
    "Work in your notebook. Part A (bridging): 28 + 7, 59 + 6, 37 + 5, 46 + 8. Part B (partitioning): 34 + 25, 52 + 36, 235 + 142. Part C (rounding and adjusting): 46 + 29, 63 + 39, 75 + 19, 245 + 99. Part D (columns): 358 + 247, 476 + 285, 129 + 563. Part E: choose a strategy for each, name it and explain why: 41 + 38, 67 + 29, 489 + 276, 18 + 7. Part F: check two of your answers by estimating and by reversing.",
    "Stage 1 (plan): choose ten addition questions: four with two digits and no regrouping, three with two digits and regrouping, three with three digits.\nStage 2 (solve): solve each with a strategy of your choice and write the strategy name next to each.\nStage 3 (check): check every answer with an estimate or by reversing.\nStage 4 (word problem): write one addition story problem and solve it, showing your working.",
    "Write the answers to each task in your notebook and say them aloud to a listener.",
    "Did I do ten sums? Did I name the strategy for each? Did I check every answer? Did I write and solve a story problem?",
    [
        _q("What is the answer to an addition called?", ["The sum", "The difference", "The product"], 0, "A sum is the total."),
        _q("28 + 7 using bridging: 28 + 2 = 30, then?", ["30 + 5 = 35", "30 + 7 = 37", "30 + 2 = 32"], 0, "7 split into 2 and 5."),
        _q("What is 52 + 36?", ["88", "78", "98"], 0, "50 + 30 = 80, 2 + 6 = 8."),
        _q("What is 46 + 29?", ["75", "65", "85"], 0, "46 + 30 - 1 = 75."),
        _q("What is 63 + 19?", ["82", "72", "92"], 0, "63 + 20 - 1 = 82."),
        _q("In the column method, where do you start?", ["The ones column", "The hundreds column", "Anywhere"], 0, "Always start at the right."),
        _q("What is 358 + 247?", ["605", "595", "505"], 0, "Ones 15, tens 10, hundreds 6."),
        _q("What is 245 + 99?", ["344", "334", "354"], 0, "245 + 100 - 1 = 344."),
        _q("Which is a good estimate for 358 + 247?", ["610", "410", "810"], 0, "360 + 250 = 610."),
        _q("How can you check 83 = 47 + 36?", ["83 - 36 = 47", "83 + 36", "47 x 36"], 0, "Subtraction reverses addition."),
    ],
    "Upload a photo of your ten sums with the strategy named and the checks, plus your story problem.",
    "Make up three addition sums, each with the answer 100, and show a different strategy for each.",
    [("addition", "Joining amounts to find a total."), ("sum", "The answer to an addition."), ("bridge", "To add in two jumps, first to the next ten."),
     ("partition", "To split numbers into tens and ones."), ("compensate", "To round a number and then adjust the answer."),
     ("regroup", "To bundle ten of one place into one of the next place (carry)."), ("column method", "A written method that lines up digits by place value."), ("estimate", "To find an answer that is close, usually by rounding.")],
    [],
    _sort("Best strategy", "Which strategy would you choose for each sum? Tap a strategy, then press Check.",
          ["Bridge the ten", "Partition", "Round and adjust"],
          [("28 + 7", 0), ("59 + 6", 0), ("37 + 5", 0), ("34 + 25", 1), ("52 + 36", 1), ("41 + 38", 1), ("46 + 29", 2), ("63 + 39", 2), ("75 + 19", 2)]),
    [
        _wc("The answer to an addition is the ___.", ["sum", "some", "sun"], 0, "Sum is the total."),
        _wc("Carrying ten to the next column is called ___.", ["regrouping", "regrooping", "regrouting"], 0, "Regroup has a gr."),
        _wc("To find an answer that is close, you ___.", ["estimate", "estamate", "estimat"], 0, "Estimate ends -mate."),
    ],
    [
        {"key": "q", "label": "My ten questions", "hint": "Four easy, three with regrouping, three with three digits."},
        {"key": "s", "label": "Strategy for each", "hint": "Name the strategy next to each sum."},
        {"key": "w", "label": "Story problem", "hint": "Write a short story that needs an addition."},
    ],
    ["Starting at the left in the column method.", "Forgetting to add the carried ten.", "Rounding up but not taking the extra back (58 + 39 = 98).", "Lining up the columns crookedly.", "Skipping the check."],
    [{"title": "Shop Till You Add", "description": "Pick five items from a catalogue with prices under $500. Add pairs of prices and show the working.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 35, 65, 42, 54. Part B: 59, 88, 377. Part C: 75, 102, 94, 344. Part D: 605, 761, 692. Part E (suggested): 41 + 38 partition = 79; 67 + 29 round and adjust = 96; 489 + 276 columns = 765; 18 + 7 bridge = 25. Part F: any sensible estimate and a correct reverse subtraction.",
), "Encourage him to say the strategy name before solving. Columns should line up neatly; squared paper helps.")


M4 = _maths(build(
    "s2-math-w01-l4-subtraction-strategies", "Subtraction Toolkit: Mental and Written Strategies",
    "The missing numbers need finding! Learn how to find the difference by counting on, jumping back, rounding and trading, then check by adding.",
    "Number: subtraction strategies",
    ["MA2-AR-01"],
    {"MA2-AR-01": "Primary. Selects and uses mental strategies (counting on, jumping back, partitioning, rounding and adjusting) and the written column method with trading for subtraction involving two- and three-digit numbers, and checks by adding."},
    "We are learning to choose and use strategies to subtract two- and three-digit numbers.",
    ["I can find a difference by counting on.", "I can subtract by jumping back and by partitioning.", "I can subtract by rounding and adjusting.", "I can use the column method and trade.", "I can check a subtraction by adding."],
    ["subtraction", "difference", "count on", "partition", "compensate", "trade", "column method", "inverse"],
    ["Paper or notebook", "Pencil", "Squared paper"],
    "Child can add two- and three-digit numbers and knows place value to 1000.",
    "Subtraction has two meanings. It can mean TAKING AWAY: you have 63 and 28 go away. It can also mean FINDING THE DIFFERENCE: how far apart are 28 and 63? The answer to a subtraction is called the DIFFERENCE.\n\nBecause subtraction means two things, there are two kinds of strategy. When the numbers are close together (like 82 - 78), counting on is easiest. When one number is much smaller, jumping back or partitioning is easier.\n\nSubtraction is the INVERSE (the opposite) of addition. That gives you a lovely way to check every answer. This lesson gives you five tools: counting on, jumping back, partitioning, rounding and adjusting, and the written column method with trading.",
    [
        _step("1", "Counting on to find the difference",
              "When two numbers are close together, do not take away. Count on from the smaller number to the larger one and add up the jumps.\n\n82 - 78. Start at 78. Jump to 80 (2). Jump to 82 (2). Total: 4. The difference is 4.\n\nFor bigger gaps, jump in friendly steps: to the next ten, then tens, then ones. 63 - 28: from 28 to 30 is 2, from 30 to 60 is 30, from 60 to 63 is 3. Add the jumps: 2 + 30 + 3 = 35.\n\nThis is how a shopkeeper gives change: they count up from the price to the money you gave them.",
              "100 - 97: 97 to 100 is 3. 304 - 298: 298 to 300 is 2, 300 to 304 is 4, total 6.",
              "Count on when the numbers are close, or when one is just under a ten or hundred.",
              ("What is 82 - 78 by counting on?", ["4", "6", "14"], 0, "78 to 80 is 2, 80 to 82 is 2.")),
        _step("2", "Jumping back",
              "Jumping back means starting at the bigger number and moving down the number line. Take away the tens first, then the ones.\n\n87 - 23. Start at 87. Jump back 20 to 67. Jump back 3 to 64. Answer: 64.\n\nIf the ones are not enough, bridge back through a ten. 63 - 8. 63 - 3 = 60, then 60 - 5 = 55.\n\nThis is the mirror of bridging for addition. Always jump the tens first, then the ones, and write each jump down so you do not lose track.",
              "75 - 31: 75 - 30 = 45, 45 - 1 = 44. 63 - 8: 63 - 3 = 60, 60 - 5 = 55.",
              "Tens first, then ones. Bridge through the ten when needed.",
              ("What is 75 - 31?", ["44", "54", "46"], 0, "75 - 30 = 45, then 45 - 1 = 44.")),
        _step("3", "Partitioning to subtract",
              "You can split the second number into tens and ones and take each away in turn, keeping the first number whole.\n\n78 - 45. Split 45 into 40 and 5. 78 - 40 = 38. 38 - 5 = 33.\n\nThis works with three digits too: 596 - 243. Take away 200: 396. Take away 40: 356. Take away 3: 353.\n\nBe careful not to partition both numbers at once when the ones in the first number are smaller than the ones in the second. 63 - 28 would give 3 - 8, which is a problem. In that case, use jumping back, counting on or the column method instead.",
              "65 - 31: 65 - 30 = 35, 35 - 1 = 34. 596 - 243 = 353.",
              "Take away the second number in parts, biggest first.",
              ("What is 78 - 45?", ["33", "43", "23"], 0, "78 - 40 = 38, 38 - 5 = 33.")),
        _step("4", "Rounding and adjusting (compensation)",
              "If you are taking away 9, 19, 29, 39 or 99, round to the next ten or hundred, subtract, then give back what you took too much.\n\n76 - 29. 29 is 1 less than 30. 76 - 30 = 46. I took away 1 too many, so add 1 back: 47.\n\nThe rule for subtraction is the opposite of addition: when you subtract a rounded-up number you took away too much, so you ADD the extra back.\n\nCheck: 94 - 39 = 94 - 40 + 1 = 55. 245 - 99 = 245 - 100 + 1 = 146.\n\nSay it aloud: 'I took away one extra, so I add one back.'",
              "53 - 19 = 53 - 20 + 1 = 34. 94 - 39 = 55.",
              "Subtract the friendly number, then add back the extra.",
              ("What is 76 - 29?", ["47", "46", "57"], 0, "76 - 30 = 46, then add 1 to get 47.")),
        _step("5", "The column method with trading",
              "For bigger numbers, write them in columns and start with the ones on the right. If the top digit is smaller than the bottom digit, you must TRADE (also called regroup): take one ten from the next column and turn it into ten ones.\n\n542 - 267. Ones: 2 is smaller than 7, so trade. Take 1 ten from the 4 tens (leaves 3 tens) and add 10 ones to the 2 ones (makes 12). 12 - 7 = 5. Tens: 3 is smaller than 6, so trade. Take 1 hundred from the 5 hundreds (leaves 4) and add 10 tens to the 3 tens (makes 13). 13 - 6 = 7. Hundreds: 4 - 2 = 2. Answer: 275.\n\nWhen the next column is a zero (like 500 - 237) you have to trade from further along: trade a hundred into ten tens first, then a ten into ten ones.\n\nAlways subtract the bottom number from the top number, never the other way around.",
              "  542\n- 267\n  275\nOnes 12 - 7 = 5. Tens 13 - 6 = 7. Hundreds 4 - 2 = 2.",
              "Trade when the top digit is smaller than the bottom digit.",
              ("In 542 - 267, what is 12 - 7 for?", ["The ones column after trading", "The hundreds column", "The tens column"], 0, "The 2 ones become 12 after trading a ten.")),
        _step("6", "Checking by adding",
              "Subtraction and addition are INVERSE operations: one undoes the other. To check a subtraction, add the answer to the number you took away. You should get back the number you started with.\n\n542 - 267 = 275. Check: 275 + 267 = 542. It matches, so the answer is correct.\n\nYou can also estimate first. 542 - 267 is about 540 - 270 = 270, and 275 is close.\n\nChecking every answer takes ten seconds and catches almost every careless mistake. Make it a habit.",
              "63 - 28 = 35. Check: 35 + 28 = 63. Correct.",
              "Answer + number taken away = starting number.",
              ("How do you check 63 - 28 = 35?", ["35 + 28", "63 + 28", "35 - 28"], 0, "35 + 28 = 63.")),
    ],
    "Sum: 63 - 28. The numbers are not close, and 28 is just under 30. Option 1 counting on: 28 to 30 is 2, 30 to 60 is 30, 60 to 63 is 3. 2 + 30 + 3 = 35. Option 2 rounding and adjusting: 63 - 30 = 33, add 1 back = 34? Careful: 28 is 2 less than 30, so I took away 2 too many and add 2 back: 33 + 2 = 35. Check: 35 + 28 = 63. Correct. Another sum: 542 - 267 using columns with two trades gives 275.",
    "Work in your notebook. Part A (counting on): 82 - 78, 100 - 97, 304 - 298, 63 - 28. Part B (jumping back and partitioning): 75 - 31, 87 - 23, 65 - 31, 596 - 243. Part C (rounding and adjusting): 76 - 29, 94 - 39, 53 - 19, 245 - 99. Part D (columns): 542 - 267, 731 - 458, 625 - 387. Part E: choose a strategy for each, name it and explain why: 91 - 88, 84 - 52, 83 - 29, 702 - 345. Part F: check three answers by adding.",
    "Stage 1 (plan): choose ten subtraction questions: three where the numbers are close, three with two digits and a trade, four with three digits.\nStage 2 (solve): solve each with a strategy of your choice and write the strategy name next to each.\nStage 3 (check): check every answer by adding.\nStage 4 (word problem): write one story problem that needs subtraction and one that needs finding a difference, and solve both.",
    "Write the answers to each task in your notebook and say them aloud to a listener.",
    "Did I do ten sums? Did I name the strategy for each? Did I check every answer by adding? Did I write two story problems?",
    [
        _q("What is the answer to a subtraction called?", ["The difference", "The sum", "The total"], 0, "Difference."),
        _q("What is 82 - 78?", ["4", "14", "6"], 0, "Count on from 78 to 82."),
        _q("What is 75 - 31?", ["44", "54", "46"], 0, "75 - 30 - 1."),
        _q("What is 78 - 45?", ["33", "43", "23"], 0, "78 - 40 = 38, then 38 - 5."),
        _q("What is 76 - 29?", ["47", "46", "57"], 0, "76 - 30 = 46, add 1 back."),
        _q("What is 53 - 19?", ["34", "44", "33"], 0, "53 - 20 = 33, add 1 back."),
        _q("What do you do if the top digit is smaller than the bottom digit?", ["Trade from the next column", "Swap the digits", "Skip it"], 0, "Trade takes one from the next place."),
        _q("What is 542 - 267?", ["275", "285", "375"], 0, "Two trades."),
        _q("Which operation reverses subtraction?", ["Addition", "Division", "Counting"], 0, "Addition undoes subtraction."),
        _q("How do you check 63 - 28 = 35?", ["35 + 28 = 63", "63 + 28 = 91", "35 - 28 = 7"], 0, "Answer plus the number taken away."),
    ],
    "Upload a photo of your ten sums with strategy names and the adding checks, plus your two story problems.",
    "Make up three subtraction sums that each have the answer 25 and solve each a different way.",
    [("subtraction", "Taking away, or finding how far apart two numbers are."), ("difference", "The answer to a subtraction."), ("count on", "To find a difference by adding jumps from the smaller to the larger number."),
     ("partition", "To split the second number into tens and ones."), ("compensate", "To round a number and then adjust the answer."),
     ("trade", "To swap one ten for ten ones (or one hundred for ten tens) so you can subtract."), ("column method", "A written method that lines up digits by place value."), ("inverse", "The opposite operation. Addition and subtraction are inverses.")],
    [],
    _sort("Best strategy", "Which strategy would you choose for each sum? Tap a strategy, then press Check.",
          ["Count on", "Round and adjust", "Jump back or partition"],
          [("82 - 78", 0), ("100 - 97", 0), ("304 - 298", 0), ("76 - 29", 1), ("94 - 39", 1), ("53 - 19", 1), ("87 - 23", 2), ("65 - 31", 2), ("78 - 45", 2)]),
    [
        _wc("The answer to a subtraction is the ___.", ["difference", "diffrence", "diference"], 0, "Difference has ff."),
        _wc("Addition and subtraction are ___ operations.", ["inverse", "inverce", "invers"], 0, "Inverse ends -erse."),
        _wc("Swapping a ten for ten ones is called a ___.", ["trade", "trayd", "tread"], 0, "Trade."),
    ],
    [
        {"key": "q", "label": "My ten questions", "hint": "Three close, three with a trade, four with three digits."},
        {"key": "s", "label": "Strategy for each", "hint": "Name the strategy next to each sum."},
        {"key": "w", "label": "Story problems", "hint": "One take-away story and one difference story."},
    ],
    ["Subtracting the smaller digit from the larger in each column regardless of position (542 - 267 = 325).", "Forgetting to reduce the column you traded from.", "Rounding and then adjusting the wrong way.", "Not checking by adding.", "Treating a zero in the next column as if it could give a ten."],
    [{"title": "Change Maker", "description": "Pretend to run a shop. Choose five prices under $100 and work out the change from $100 by counting on. Write each count.", "type": "create", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 4, 3, 6, 35. Part B: 44, 64, 34, 353. Part C: 47, 55, 34, 146. Part D: 275, 273, 238. Part E (suggested): 91 - 88 count on = 3; 84 - 52 partition = 32; 83 - 29 round and adjust = 54; 702 - 345 columns = 357. Part F: any correct adding check, for example 275 + 267 = 542.",
), "Check that he checks by adding every time. The zero-trade case (500 - 237) is an extension if he is ready.")

WEEK_1_MATHS = [M1, M2, M3, M4]
