"""Stage 2 Maths, Week 2 of the programme. Lessons 1-2 of 4: multiplication and division facts (MA2-MR-01).
Lessons 3-4 (decimals, MA2-RWN-02) are still to be written.
Reuses the English helpers and the Week 1 Maths patcher. Videos are attached in a later pass.
Register WEEK_2_MATHS WITHOUT the _renumber step in lesson_library.py, or the w02 seed keys will be rewritten to w01."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from lesson_library_s2_maths_w1 import _maths

M1 = _maths(build(
    "s2-math-w02-l1-equal-groups-arrays", "Equal Groups and Arrays: Twos, Fives and Tens",
    "The Treasure Vault stores gems in neat rows. Learn to count equal groups fast and read arrays like a builder.",
    "Number: multiplication as equal groups",
    ["MA2-MR-01"],
    {"MA2-MR-01": "Primary. Represents multiplication as equal groups, arrays and skip counting, and learns the 2, 5 and 10 facts."},
    "We are learning to use equal groups, arrays and skip counting to find multiplication facts for 2, 5 and 10.",
    ["I can say how many are in equal groups.", "I can build and read an array.", "I can skip count by 2, 5 and 10.", "I can write a multiplication sentence.", "I can show that 3 x 5 and 5 x 3 give the same answer."],
    ["multiply", "equal groups", "array", "row", "column", "skip count", "product"],
    ["Counters, buttons or coins", "Paper or notebook", "Pencil"],
    "Child can count by ones to 100 and can add small numbers.",
    "Imagine 4 plates with 5 grapes on each plate. You could count every grape, but there is a faster way. Because every plate has the SAME number, you can multiply: 4 groups of 5 is 4 x 5 = 20.\n\nMultiplication is a quick way to add equal groups. In this lesson you will build groups with real objects, arrange them in arrays, and skip count to find answers for the 2, 5 and 10 facts.",
    [
        _step("1", "Equal groups",
              "EQUAL GROUPS means every group has the same amount. 3 bags with 4 apples in each bag is 3 groups of 4. We write it as 3 x 4 and say 'three groups of four'.\n\nTo find the answer, add the groups: 4 + 4 + 4 = 12. So 3 x 4 = 12. The answer to a multiplication is called the PRODUCT.\n\nIf the groups are not the same size, it is not a multiplication.",
              "2 plates with 5 biscuits each: 2 x 5 = 5 + 5 = 10.",
              "The first number is how many groups. The second number is how many in each group.",
              ("What is 3 groups of 4?", ["7", "12", "34"], 1, "4 + 4 + 4 = 12.")),
        _step("2", "Arrays",
              "An ARRAY puts objects in neat ROWS and COLUMNS. Rows go across. Columns go up and down.\n\nAn array with 3 rows and 5 in each row is 3 x 5 = 15. Egg cartons, chocolate blocks and window panes are all arrays.\n\nTurn the array on its side and it becomes 5 rows with 3 in each row. The total is still 15, so 3 x 5 = 5 x 3.",
              "2 rows of 6 counters is 2 x 6 = 12. Turned around it is 6 x 2 = 12.",
              "Rows go across, columns go down. Turning an array around keeps the total the same.",
              ("An array has 2 rows of 6. How many in total?", ["8", "12", "26"], 1, "2 x 6 = 12.")),
        _step("3", "Skip counting by 2, 5 and 10",
              "SKIP COUNTING means counting in jumps instead of ones.\n\nBy 2s: 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.\nBy 5s: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50.\nBy 10s: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100.\n\nTo find 6 x 5, skip count by 5 six times: 5, 10, 15, 20, 25, 30. So 6 x 5 = 30. Use your fingers to keep track of how many jumps you have made.",
              "7 x 2: 2, 4, 6, 8, 10, 12, 14, so 7 x 2 = 14. 4 x 10 = 40.",
              "Count the jumps on your fingers. The last number you say is the product.",
              ("What is 6 x 5?", ["11", "25", "30"], 2, "Skip count by 5 six times to reach 30.")),
        _step("4", "Turn-around facts and patterns",
              "Order does not change a product. 4 x 5 = 5 x 4 = 20. This is called the TURN-AROUND rule, and it halves the number of facts you must learn.\n\nPatterns help too. Every product in the 10s ends in 0. Every product in the 5s ends in 0 or 5. Every product in the 2s is even, and 2 x a number is the same as doubling it.\n\nUse the patterns to check. If you get 5 x 7 = 34, you can tell it is wrong because a 5s product cannot end in 4.",
              "5 x 8 = 40 (ends in 0). 2 x 9 = 18 (double 9). 10 x 6 = 60.",
              "Use turn-around, doubling and last-digit patterns to check your answers.",
              ("Which product could be in the 5s?", ["34", "35", "36"], 1, "Products in the 5s end in 0 or 5.")),
    ],
    "Problem: 6 bags with 5 marbles each. Groups: 6. In each: 5. 6 x 5. Skip count by 5: 5, 10, 15, 20, 25, 30. Answer: 30 marbles. Check: 5 x 6 = 30 by turn-around, and 30 ends in 0 or 5, so it fits the 5s pattern.",
    "Work in your notebook. Part A (groups): write a multiplication for 4 groups of 5, 3 groups of 2 and 5 groups of 10. Part B (arrays): draw an array for 3 x 4 and write the turn-around fact. Part C (skip count): write the 2s, 5s and 10s up to 10 jumps. Part D: find 7 x 2, 9 x 5 and 8 x 10. Part E: 6 x 5 = 5 x __ and 10 x 3 = 3 x __.",
    "Stage 1 (make): use counters to build three different arrays.\nStage 2 (record): for each, write the multiplication sentence and its turn-around.\nStage 3 (skip count): choose a 2, 5 and 10 fact and skip count to prove each.\nStage 4 (story): write a short story problem for one of your facts and solve it.",
    "Write the answers in your notebook and explain one of them aloud.",
    "Did I build three arrays? Did I write each sentence and its turn-around? Did I skip count to prove three facts? Did I write a story?",
    [
        _q("What is 3 groups of 5?", ["8", "15", "35"], 1, "5 + 5 + 5 = 15."),
        _q("What is 4 x 2?", ["6", "8", "42"], 1, "2, 4, 6, 8."),
        _q("What is 6 x 10?", ["16", "60", "66"], 1, "Six 10s is 60."),
        _q("What is 7 x 5?", ["35", "12", "75"], 0, "Skip count by 5 seven times."),
        _q("2 rows of 6 counters. How many in total?", ["8", "12", "26"], 1, "2 x 6 = 12."),
        _q("5 x 3 is the same as?", ["3 x 5", "5 + 3", "3 + 3"], 0, "Turn-around rule."),
        _q("Skip count by 5: 0, 5, 10, 15, 20, ___.", ["21", "25", "30"], 1, "Add 5 each time."),
        _q("What is 9 x 2?", ["11", "18", "29"], 1, "Double 9."),
        _q("What is 10 x 8?", ["18", "80", "88"], 1, "Eight 10s."),
        _q("What is 5 x 6?", ["11", "30", "56"], 1, "Six 5s is 30."),
    ],
    "Upload a photo of your arrays, number sentences and story problem.",
    "Find three facts in the 2s, 5s and 10s that give the same product, and explain what you notice.",
    [("multiply", "To find the total of equal groups."), ("equal groups", "Groups that all have the same number."), ("array", "Objects in rows and columns."),
     ("row", "A line going across."), ("column", "A line going up and down."), ("skip count", "Counting in jumps."), ("product", "The answer to a multiplication.")],
    [],
    _sort("Which fact family?", "Which times table does each product belong to? Tap a table, then press Check.",
          ["Twos only", "Fives", "Tens"],
          [("2 x 3 = 6", 0), ("2 x 7 = 14", 0), ("2 x 8 = 16", 0), ("5 x 4 = 20", 1), ("5 x 7 = 35", 1), ("5 x 9 = 45", 1), ("10 x 3 = 30", 2), ("10 x 7 = 70", 2), ("10 x 9 = 90", 2)]),
    [
        _wc("The answer to a multiplication is the ___.", ["product", "produck", "prodcut"], 0, "Product has duct."),
        _wc("Objects in rows and columns make an ___.", ["array", "aray", "arrey"], 0, "Array has rr."),
        _wc("Counting in jumps is ___ counting.", ["skip", "skipp", "scip"], 0, "Skip starts with sk."),
    ],
    [
        {"key": "a", "label": "My three arrays", "hint": "Draw or photograph each array."},
        {"key": "s", "label": "Sentences", "hint": "Write each fact and its turn-around."},
        {"key": "t", "label": "Story", "hint": "Write a short multiplication story."},
    ],
    ["Adding the numbers instead of multiplying (3 x 4 = 7).", "Counting unequal groups as a multiplication.", "Losing count of the jumps when skip counting.", "Thinking 3 x 5 and 5 x 3 are different.", "Mixing up rows and columns."],
    [{"title": "Egg Carton Arrays", "description": "Find three arrays around the house, such as an egg carton, a window or a chocolate block. Write the multiplication for each.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 4 x 5 = 20; 3 x 2 = 6; 5 x 10 = 50. Part B: 3 x 4 = 12 and 4 x 3 = 12. Part C: 2s up to 20, 5s up to 50, 10s up to 100. Part D: 14, 45, 80. Part E: 6; 10 x 3 = 3 x 10.",
), "Use real counters first. Let him say each skip count aloud and keep track of the jumps on his fingers.")


M2 = _maths(build(
    "s2-math-w02-l2-threes-fours-division", "Threes, Fours and Sharing: Division Facts",
    "The Treasure Vault has two more locks. Learn the 3s and 4s, then discover that division unlocks them again.",
    "Number: multiplication facts and related division",
    ["MA2-MR-01"],
    {"MA2-MR-01": "Primary. Extends multiplication to the 3s and 4s and introduces division as sharing and grouping, with fact families."},
    "We are learning the 3 and 4 facts and how division is the opposite of multiplication.",
    ["I can find 3 x and 4 x facts using skip counting or doubling.", "I can share objects equally to divide.", "I can group objects to divide.", "I can write a fact family.", "I can check a division by multiplying."],
    ["divide", "share", "group", "fact family", "inverse", "double", "quotient"],
    ["Counters or buttons", "Paper or notebook", "Pencil"],
    "Child knows the 2, 5 and 10 facts, arrays and the turn-around rule.",
    "12 biscuits shared between 3 friends. How many does each friend get? That is DIVISION. 12 divided by 3 is 4.\n\nDivision is the opposite of multiplication. If you know 3 x 4 = 12, you already know 12 / 3 = 4. In this lesson you will learn the 3 and 4 facts, then use them to solve division problems.",
    [
        _step("1", "The 3 times table",
              "Skip count by 3: 3, 6, 9, 12, 15, 18, 21, 24, 27, 30. Each jump is one more group of 3.\n\n3 x 6 means six jumps: 3, 6, 9, 12, 15, 18. So 3 x 6 = 18.\n\nAnother trick: 3 x a number is double the number plus one more of it. 3 x 4 = 4 + 4 + 4 = 12.",
              "3 x 7: 3, 6, 9, 12, 15, 18, 21. So 21.",
              "Skip count and count the jumps on your fingers.",
              ("What is 3 x 6?", ["9", "18", "36"], 1, "3, 6, 9, 12, 15, 18.")),
        _step("2", "The 4 times table",
              "4 x a number is DOUBLE and DOUBLE again. To find 4 x 6: double 6 to get 12, then double 12 to get 24.\n\nSkip counting by 4: 4, 8, 12, 16, 20, 24, 28, 32, 36, 40.\n\nUse the turn-around rule too. If you know 3 x 4 = 12, you also know 4 x 3 = 12.",
              "4 x 7: double 7 is 14, double 14 is 28. So 28.",
              "Double, then double again.",
              ("What is 4 x 4?", ["8", "16", "44"], 1, "Double 4 is 8, double 8 is 16.")),
        _step("3", "Division as sharing and grouping",
              "DIVISION has two meanings. SHARING: 12 shared into 3 equal groups gives 4 in each. GROUPING: 12 put into groups of 3 gives 4 groups.\n\nWe write 12 / 3 = 4. The answer is called the QUOTIENT.\n\nTo divide, ask: what times the small number gives the big number? For 20 / 4, ask: 4 times what is 20? 4 x 5 = 20, so 20 / 4 = 5.",
              "15 / 3 = 5 because 3 x 5 = 15.",
              "Think multiplication to solve a division.",
              ("What is 20 / 4?", ["4", "5", "6"], 1, "4 x 5 = 20.")),
        _step("4", "Fact families",
              "A FACT FAMILY uses the same three numbers. For 3, 5 and 15: 3 x 5 = 15, 5 x 3 = 15, 15 / 3 = 5 and 15 / 5 = 3.\n\nMultiplication and division are INVERSE operations: one undoes the other. This gives a quick check. If 24 / 4 = 6, then 6 x 4 should be 24.\n\nThe biggest number always comes alone in a division and as the product in a multiplication.",
              "Family for 4, 6, 24: 4 x 6 = 24, 6 x 4 = 24, 24 / 4 = 6, 24 / 6 = 4.",
              "Three numbers, four facts. Check division by multiplying.",
              ("Which fact belongs with 3 x 9 = 27?", ["27 / 3 = 9", "27 / 3 = 8", "9 / 3 = 27"], 0, "Division undoes multiplication.")),
    ],
    "Problem: 24 stickers shared equally between 4 children. 24 / 4 = ? Ask: 4 times what is 24? 4 x 6 = 24, so 24 / 4 = 6. Each child gets 6 stickers. Check: 6 x 4 = 24. Fact family: 4, 6, 24.",
    "Work in your notebook. Part A: find 3 x 7, 3 x 9, 4 x 5 and 4 x 8. Part B: share 12 counters between 3, then between 4. Part C: find 18 / 3, 28 / 4 and 32 / 4. Part D: write the fact family for 3, 8 and 24. Part E: check 20 / 4 = 5 by multiplying.",
    "Stage 1 (make): use counters to share 24 into equal groups in as many ways as you can.\nStage 2 (record): write a multiplication and a division for each way.\nStage 3 (family): write the fact family for two sets of numbers.\nStage 4 (story): write one sharing story and one grouping story and solve both.",
    "Write the answers in your notebook and say one fact family aloud.",
    "Did I share 24 in several ways? Did I write a multiplication and division for each? Did I write two fact families? Did I write two stories?",
    [
        _q("What is 3 x 6?", ["18", "9", "36"], 0, "3, 6, 9, 12, 15, 18."),
        _q("What is 4 x 7?", ["11", "24", "28"], 2, "Double 7 is 14, double again is 28."),
        _q("What is 4 x 4?", ["8", "16", "44"], 1, "Double 4, then double 8."),
        _q("What is 12 / 3?", ["3", "4", "9"], 1, "3 x 4 = 12."),
        _q("What is 20 / 4?", ["5", "4", "16"], 0, "4 x 5 = 20."),
        _q("What is 24 / 4?", ["20", "6", "8"], 1, "4 x 6 = 24."),
        _q("Which fact is in the family of 3, 5 and 15?", ["15 / 3 = 5", "15 / 5 = 10", "3 + 5 = 15"], 0, "3 x 5 = 15."),
        _q("What is 3 x 9?", ["12", "27", "39"], 1, "Nine 3s."),
        _q("What is 4 x 8?", ["32", "12", "48"], 0, "Double 8, double 16."),
        _q("What is 18 / 3?", ["5", "6", "15"], 1, "3 x 6 = 18."),
    ],
    "Upload a photo of your sharing arrangements, fact families and stories.",
    "Find a number that is in both the 3s and 4s tables below 40, and explain how you found it.",
    [("divide", "To share or group into equal parts."), ("share", "To split into equal groups."), ("group", "To make groups of a set size."),
     ("fact family", "Multiplication and division facts that use the same three numbers."), ("inverse", "The opposite operation."),
     ("double", "To multiply by 2."), ("quotient", "The answer to a division.")],
    [],
    _sort("Which table?", "Which table helps solve each division? Tap a table, then press Check.",
          ["3 times table", "4 times table"],
          [("12 / 3", 0), ("18 / 3", 0), ("27 / 3", 0), ("16 / 4", 1), ("28 / 4", 1), ("36 / 4", 1)]),
    [
        _wc("The answer to a division is the ___.", ["quotient", "qoutient", "quotent"], 0, "Quotient has uo."),
        _wc("Multiplication and division are ___ operations.", ["inverse", "inverce", "invers"], 0, "Inverse ends erse."),
        _wc("Three numbers that make four related facts are a fact ___.", ["family", "famly", "familly"], 0, "Family has mi."),
    ],
    [
        {"key": "s", "label": "Ways to share 24", "hint": "Write each multiplication and division."},
        {"key": "f", "label": "Fact families", "hint": "Write all four facts for two families."},
        {"key": "t", "label": "Stories", "hint": "One sharing and one grouping story."},
    ],
    ["Dividing the small number by the big one.", "Forgetting that division is the opposite of multiplication.", "Adding instead of doubling twice for the 4s.", "Mixing up the order in a division sentence.", "Not checking by multiplying."],
    [{"title": "Fair Share", "description": "Share 24 small items such as buttons into equal groups in as many ways as you can. Record each as a division.", "type": "create", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 21, 27, 20, 32. Part B: 12 / 3 = 4; 12 / 4 = 3. Part C: 6, 7, 8. Part D: 3 x 8 = 24, 8 x 3 = 24, 24 / 3 = 8, 24 / 8 = 3. Part E: 5 x 4 = 20.",
), "Use counters to share before writing any numbers. Say each fact family aloud.")

WEEK_2_MATHS = [M1, M2]
