"""Stage 2 English, Block A (narrative writing), week 8, lessons 1 to 4.
Pass 2 (video pass): lessons at full depth plus videos for L1, L2 and L3. L4 has no video yet.
Video ids came from search and must be checked on playback. The module is not yet registered in lesson_library.py.
Keys use the prefix a8."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A8L1 = build(
    "s2-eng-a8-l1-narrative-point-of-view", "Narrative Point of View",
    "Learn who is telling a story, how first-person and third-person narration work, and how to keep one clear point of view.",
    "Reading and writing: narrative point of view",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies who is telling a narrative and explains how the narrator affects what the reader knows.",
     "EN2-CWT-01": "Writes a short narrative moment consistently from a chosen point of view.",
     "EN2-VOCAB-01": "Learns narrator, point of view, first person, third person, pronoun and perspective."},
    "We are learning how a narrator tells a story and how the point of view changes what the reader knows and feels.",
    ["I can explain what a narrator and point of view are.", "I can recognise first-person and third-person narration.", "I can use the pronouns that match each point of view.", "I can explain what a narrator does and does not know.", "I can write a short scene from one clear point of view."],
    ["narrator", "point of view", "first person", "third person", "pronoun", "perspective"],
    ["Paper or notebook", "Pencil", "Your narrative plan or draft", "A narrative chosen by your parent"],
    "Child has planned a complete narrative. This lesson teaches point of view from the beginning before the child drafts or revises a whole story.",
    "Every story has a teller. The teller might be a character inside the story, or a voice outside the story. That teller is called the NARRATOR.\n\nPOINT OF VIEW means the position from which the reader experiences the story. It controls the words we use, the thoughts we can hear and the information we receive.\n\nCompare: 'I gripped the rail as the boat tipped.' The character tells us directly what happened. 'Mia gripped the rail as the boat tipped.' Someone outside the story tells us about Mia. Both can be good, but they give the reader a different experience.\n\nIn this lesson you will learn the two most useful narrative points of view, practise spotting them, see how the same event changes when it is retold, and choose one point of view for your own story.",
    [
        _step("1", "The narrator and point of view",
              "A NARRATOR is the voice that tells the story. It is not always the author. An author makes the story; a narrator tells it.\n\nPOINT OF VIEW is where the narrator stands in relation to the story. Imagine watching a school play. You could stand on stage as one character, or sit in the audience and watch that character. The events are the same, but what you see and say changes.\n\nA narrator can tell us actions, speech, thoughts and feelings. But the narrator has limits. A narrator inside the story can only tell us what they notice, remember or are told.\n\nAsk two questions when you read: Who is telling this story? How close is the narrator to the action?",
              "'I heard a scrape beneath the deck.' The narrator is a character who hears it. 'Mia heard a scrape beneath the deck.' The narrator is outside Mia, telling us about her.",
              "Narrator means the voice telling the story.",
              ("A narrator is...", ["the voice that tells the story", "the book cover", "every character at once"], 0, "The narrator is the voice telling the reader what happens.")),
        _step("2", "First-person point of view",
              "FIRST PERSON means a character tells the story using the pronouns I, me, my, we or our. The narrator is inside the story.\n\nFirst person can feel close and immediate because we hear the character's own thoughts.\n\n'I did not want to open the door. My hand shook on the handle.'\n\nThe reader knows what I see, hear, think and feel. The reader does NOT automatically know what another character is secretly thinking. Instead of writing 'Tom was frightened' when you are not Tom, show clues: 'Tom's eyes darted to the window.'\n\nA common mistake is swapping between I and a character name as if the narrator has stepped outside their own head. If Mia tells the story, write 'I ran', not 'Mia ran' for Mia's own action.",
              "First person: 'I tucked the map into my pocket and hoped Dad would not notice.'",
              "First person uses I, me, my, we and our.",
              ("Which sentence is in first person?", ["I held my breath.", "Leo held his breath.", "They held their breath."], 0, "I and my show that a character is telling the story.")),
        _step("3", "Third-person point of view",
              "THIRD PERSON means a narrator outside the story tells us about characters using names and pronouns such as he, she, they, him, her and their.\n\n'Mia pressed her ear against the door. She could hear the waves hammering the rocks below.'\n\nThird person lets the writer name the character and describe what the character does from the outside. It can still show one character's thoughts: 'Mia wondered whether the light would hold.' For a clear short narrative, stay close to one main character at a time.\n\nA common mistake is jumping suddenly into everyone else's private thoughts. That can confuse the reader. Choose whose thoughts the reader follows in each scene.\n\nThird person does not mean distant or boring. You can still use sensory detail, action, dialogue and feelings.",
              "Third person: 'Leo shoved the window open. Cold rain slapped his face, and he wished he had brought the torch.'",
              "Third person uses names, he, she, they, him, her and their.",
              ("Which sentence is in third person?", ["Mia clutched her coat.", "I clutched my coat.", "We clutched our coats."], 0, "Mia and her show that an outside narrator is telling the story.")),
        _step("4", "Same event, two viewpoints",
              "The point of view changes the words and the reader's closeness to a character. Read the same moment both ways.\n\nFIRST PERSON: 'I froze when the torch beam swept across the cave wall. Was that a shadow moving beside me? I pulled my jacket tight and listened.'\n\nTHIRD PERSON: 'Zara froze when the torch beam swept across the cave wall. She wondered whether the shadow beside her had moved. Pulling her jacket tight, Zara listened.'\n\nBoth versions show Zara's fear. The first version sounds like Zara is speaking to us. The second version lets the narrator call her Zara and describe her from outside.\n\nTo change a scene from first person to third person, replace I, me and my with the character's name, he, she, they, him, her or their. Then reread for every pronoun. Do not change only the first sentence.",
              "Change: 'I found my compass' becomes 'Zara found her compass.'",
              "The event can stay the same while the storyteller changes.",
              ("When changing 'I found my compass' to third person, which is correct?", ["Zara found her compass.", "Zara found my compass.", "I found her compass."], 0, "The character name and her must match the third-person point of view.")),
        _step("5", "Keep one viewpoint",
              "A clear narrative usually keeps one point of view. Switching by accident is called a POINT-OF-VIEW SHIFT. It makes the reader stop and wonder who is speaking.\n\nMixed up: 'I crept to the gate. Mia could hear her heart pounding.'\n\nIf Mia is the first-person narrator, fix it: 'I crept to the gate. I could hear my heart pounding.'\n\nIf the story is in third person, fix it: 'Mia crept to the gate. She could hear her heart pounding.'\n\nUse a quick pronoun check. Circle every I, me and my. Then circle every he, she, they, him, her and their. If both groups appear for the same main character, decide which point of view you meant and repair the sentences. Dialogue is different: characters may say I inside speech marks even in a third-person story.",
              "Third-person dialogue is fine: Mia whispered, 'I can hear something outside.' The narrator still says Mia and she outside the speech marks.",
              "Keep the narrator's pronouns consistent outside dialogue.",
              ("What is wrong with 'I ran to the shed. Leo was terrified.' if Leo is the narrator?", ["It switches from I to a name for the same narrator", "It has too many commas", "It is a list"], 0, "A first-person narrator should keep using I, me and my for their own actions.")),
        _step("6", "Choose and write",
              "Choose the point of view for the narrative you planned. First person is useful if you want the reader to feel close to one character's thoughts. Third person is useful if you want an outside narrator who can name the main character.\n\nWrite a 6 to 8 sentence scene from the most tense part of your story.\n1. Write the chosen point of view at the top: FIRST PERSON or THIRD PERSON.\n2. Begin with an action or sensory detail.\n3. Include one thought or feeling that fits the chosen narrator.\n4. Use dialogue only if it helps the scene.\n5. Check every pronoun outside dialogue.\n6. Read the scene aloud. Can the reader tell who is speaking?\n\nModel, first person: 'The floorboard groaned beneath my foot. I stopped so suddenly that the torch slipped from my hand. Somewhere upstairs, a door clicked shut. I wanted to call for Dad, but my throat had gone dry. Then I saw the muddy footprints leading to the attic stairs. I lifted the torch and followed them.'",
              "Third-person version: 'The floorboard groaned beneath Leo's foot. He stopped so suddenly that the torch slipped from his hand. Somewhere upstairs, a door clicked shut.'",
              "Choose one viewpoint and keep its pronouns consistent.",
              ("What should you check before submitting?", ["That the narrator's pronouns stay consistent", "That every sentence starts the same", "That you used the word narrator ten times"], 0, "Consistent pronouns help the reader know who is telling the story.")),
    ],
    "Model answers. Narrator: the voice telling the story. First person uses I, me and my and is told by a character in the story. Third person uses names, he, she, they, him, her and their and is told by a narrator outside the story. Change 'I found my compass' to 'Zara found her compass.' Fix the mixed viewpoint by choosing either 'I crept to the gate. I could hear my heart pounding' or 'Mia crept to the gate. She could hear her heart pounding.'",
    "1) Mark six short extracts as first or third person. 2) Underline the pronouns that reveal the point of view. 3) Retell two first-person sentences in third person. 4) Repair four accidental point-of-view shifts. 5) Read a parent-chosen narrative and identify its narrator. 6) Write a 6 to 8 sentence tense scene from one point of view.",
    "Write a 6 to 8 sentence tense scene from your narrative plan in either first or third person. Label the point of view and keep it consistent. Upload a photo of your writing.",
    CHECK,
    "Did I label first person or third person? Did I use the pronouns that match it? Did I avoid switching point of view outside dialogue? Did I include an action, sensory detail and a thought or feeling? Can a reader tell who is narrating? Did I write 6 to 8 sentences?",
    [
        _q("A narrator is...", ["the voice that tells the story", "the title", "a punctuation mark"], 0, "The narrator tells the story."),
        _q("First person uses...", ["I, me and my", "he, she and they", "only character names"], 0, "A character inside the story tells it with I, me and my."),
        _q("Third person usually uses...", ["names, he, she and they", "only I and my", "question words only"], 0, "An outside narrator uses names and third-person pronouns."),
        _q("Which is first person?", ["I pushed the gate open.", "Zara pushed the gate open.", "The gate was pushed by Zara."], 0, "I shows first person."),
        _q("Which is third person?", ["Zara pushed the gate open.", "I pushed my gate open.", "We pushed our gate open."], 0, "Zara is named by a narrator outside the story."),
        _q("What should a first-person narrator know directly?", ["What they notice, think and feel", "Every secret thought in every character", "Nothing about the setting"], 0, "A first-person narrator can tell the reader what they experience."),
        _q("What is an accidental point-of-view shift?", ["Changing narrator pronouns without meaning to", "Writing dialogue", "Adding a setting detail"], 0, "It confuses the reader about who is speaking."),
        _q("Which fixes the mixed sentence 'I ran. Zara was scared.' if Zara tells the story?", ["I ran. I was scared.", "Zara ran. I was scared.", "I ran. Zara was scared."], 0, "A first-person narrator keeps using I for their own actions and feelings."),
    ],
    "Upload a photo of your labelled 6 to 8 sentence scene.",
    "With a parent-chosen narrative, copy two sentences that show point of view. Circle the pronouns and explain whether the narrator is inside or outside the story.",
    [("narrator", "The voice that tells a story."), ("point of view", "The position from which a story is told."), ("first person", "A character tells the story using I, me and my."), ("third person", "A narrator outside the story uses names, he, she, they and related pronouns."), ("pronoun", "A word used instead of a name, such as I, she, they or our."), ("perspective", "A person's particular way of seeing or understanding events.")],
    [
        _video("Point of View for Kids: First and Third Person", "R9-ONtB1GBY",
               "Watch how clue words such as I, me and my show first person, and he, she and they show third person. Pause and say which clue words you would use in your own scene.",
               "If the video does not play, write two sentences about the same event, one with I and one with a character's name, and circle the clue words.",
               ("Clue words such as I, me and my show which point of view?", ["first person", "third person", "no point of view"], 0, "I, me and my show that a character is telling the story.")),
    ],
    _sort("Point of view", "Which point of view does each sentence use? Tap a group, then Check.",
          ["First person", "Third person"],
          [("I tucked the key into my pocket.", 0), ("We could hear the rain on the roof.", 0), ("My hands shook as I opened the letter.", 0), ("Mia tucked the key into her pocket.", 1), ("They could hear the rain on the roof.", 1), ("His hands shook as Leo opened the letter.", 1)]),
    [
        _wc("The voice that tells a story is the ___.", ["narrator", "narrationer", "narrative"], 0, "The narrator tells the story."),
        _wc("First person uses the pronoun ___.", ["I", "she", "they"], 0, "I shows first person."),
        _wc("A point-of-view ___ happens when a writer changes narrators by accident.", ["shift", "shelf", "shine"], 0, "A shift changes point of view."),
        _wc("Which is spelt correctly?", ["perspective", "perspectiv", "perspecktive"], 0, "Perspective ends -ive."),
        _wc("Which is spelt correctly?", ["pronoun", "proknown", "pronnoun"], 0, "Pronoun has one n after pro."),
    ],
    [
        {"key": "spot", "label": "Point of view spotted", "hint": "Six extracts marked first or third person."},
        {"key": "change", "label": "Viewpoint changes", "hint": "Two first-person sentences retold in third person."},
        {"key": "repair", "label": "Shifts repaired", "hint": "Four accidental point-of-view shifts fixed."},
        {"key": "scene", "label": "My narrated scene", "hint": "A labelled 6 to 8 sentence scene with consistent pronouns."},
    ],
    ["Mixing I and a character name for the same narrator.", "Telling another character's secret thoughts without clues.", "Changing point of view halfway through a short scene.", "Forgetting that dialogue can use I even in third person.", "Choosing a point of view but not checking the pronouns."],
    [{"title": "One Moment, Two Voices", "description": "Write the same three-sentence moment once in first person and once in third person. Circle the pronouns that changed.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the narrator is clear, the point of view is labelled, pronouns stay consistent outside dialogue, the scene has action and detail, and it is 6 to 8 sentences. Sorter: First person: I tucked the key; We could hear rain; My hands shook. Third person: Mia tucked the key; They could hear rain; His hands shook as Leo opened the letter.",
)

A8L2 = build(
    "s2-eng-a8-l2-editing-and-revising-a-draft", "Editing and Revising a Draft",
    "Learn how writers improve a draft in stages: revise ideas first, edit sentences next, and proofread the final copy.",
    "Writing: editing and revising a narrative",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Revises and edits a narrative draft to improve clarity, detail, structure and sentence control.",
     "EN2-RECOM-01": "Identifies strengths and improvements in a model narrative draft.",
     "EN2-VOCAB-01": "Learns draft, revise, edit, proofread, feedback and publish.",
     "EN2-SPELL-01": "Checks and corrects spelling in a final narrative copy."},
    "We are learning how to improve a draft by revising the ideas first, editing the sentences next and proofreading at the end.",
    ["I can explain the difference between drafting, revising, editing and proofreading.", "I can find one strength and one useful improvement in a draft.", "I can revise a paragraph by adding, removing, moving or replacing ideas.", "I can edit punctuation, spelling and sentence errors.", "I can make a clean final copy of part of my narrative."],
    ["draft", "revise", "edit", "proofread", "feedback", "publish"],
    ["Your narrative draft or plan", "Paper or notebook", "Pencil", "A different-coloured pencil if available", "Dictionary with parent help if needed"],
    "Child has planned or begun a narrative. Editing and revising are taught as separate processes rather than as a final checklist.",
    "Real writers do not usually produce a perfect story the first time. A first attempt is called a DRAFT. A draft is allowed to be unfinished, messy and changeable.\n\nGood writers improve a draft in an order. First they REVISE the big ideas: is the story clear, interesting and complete? Then they EDIT the sentences: are the words, punctuation and grammar accurate? Finally they PROOFREAD the finished copy: have small slips been missed?\n\nIf you hunt for spelling before you know whether a paragraph belongs in the story, you may spend time polishing a sentence you later remove. This lesson shows the order clearly, then guides you through revising and editing your own narrative.",
    [
        _step("1", "Four stages of improving writing",
              "DRAFT: the first version of writing. Its job is to get the story down.\n\nREVISE: look again at the meaning and make the writing stronger. You may add detail, remove an unneeded part, move a sentence or replace a weak idea. Think REVISION = seeing again.\n\nEDIT: correct and improve the way the sentences work. Check capitals, punctuation, spelling, grammar and word choice.\n\nPROOFREAD: read the near-final copy slowly to catch small mistakes that remain.\n\nPUBLISH: share or present the final version neatly. Publishing may mean handwriting a clean copy, typing it or reading it aloud.\n\nRevision is not the same as correcting a spelling mistake. Revision improves meaning; editing improves accuracy.",
              "Draft: 'Mia went to the beach and found a cave.' Revise: add why she went and what made the cave dangerous. Edit: check capitals, full stops and spelling.",
              "Revise ideas first, edit accuracy next, proofread last.",
              ("Which stage improves the big ideas in a story?", ["Revise", "Proofread", "Publish"], 0, "Revising improves meaning, detail and structure.")),
        _step("2", "Read like a helpful editor",
              "Before changing a draft, notice what already works. Feedback should be useful, not vague.\n\nVague: 'It is good.'\nUseful: 'The sound of the rain makes the setting feel stormy.'\n\nUse two questions.\n1. What is already helping the reader? Look for a clear action, a strong detail, believable dialogue or a useful opening.\n2. What would make the reader understand or feel more? Look for a missing reason, a rushed moment, a confusing pronoun or a weak ending.\n\nRead this draft: 'Mia went to the lighthouse. It was stormy. She needed to light it. She did. Then she went home.'\nStrength: the problem is clear: Mia needs to light the lighthouse.\nImprovement: the important action is rushed. The draft needs details about what stops Mia and how she succeeds.\n\nFeedback is a clue for the writer. The writer chooses how to use it.",
              "Useful feedback: 'Add what Mia sees when she reaches the dark stairs, so the reader can feel the danger.'",
              "Name a strength, then suggest one specific improvement.",
              ("Which feedback is most useful?", ["Add a detail about what the character sees in the cave.", "It is nice.", "Change everything."], 0, "Specific feedback tells the writer what to try.")),
        _step("3", "Revise with ARMR",
              "A simple revision tool is ARMR.\n\nADD: put in a detail, action, thought or sentence that the reader needs.\nREMOVE: take out a repeated, boring or off-topic part.\nMOVE: put an event or sentence where it makes more sense.\nREPLACE: swap a weak word or idea for a more exact one.\n\nWeak draft: 'The cave was scary. Mia went in. She was scared. Mia heard a noise. She ran.'\n\nADD a sensory detail: 'Cold water dripped from the cave roof.'\nREMOVE the repeated 'scared'.\nMOVE the noise to after Mia has stepped inside.\nREPLACE 'went' with 'edged' and 'noise' with 'a low growl'.\n\nRevised: 'Mia edged into the cave. Cold water dripped from the roof onto her neck. When a low growl rolled from the darkness, she stumbled backwards and ran.'\n\nNotice that revision changes the reader's experience, not only the spelling.",
              "Replace: 'walked' can become 'crept', 'stomped' or 'raced', depending on the action.",
              "Add, remove, move and replace to improve meaning.",
              ("Which ARMR action changes a weak word to a precise word?", ["Replace", "Move", "Remove"], 0, "Replacing improves word choice.")),
        _step("4", "Revise a whole paragraph",
              "Now watch a paragraph improve in stages.\n\nFIRST DRAFT: 'I went into the shed. It was dark. I heard something. I was scared. I found the box and got it. Then I left.'\n\nAsk the revision questions. Why does the narrator need the box? What does the shed look or sound like? What is the something? How does the narrator get out?\n\nREVISED DRAFT: 'I squeezed through the crooked shed door to find Grandad's tin box before the rain began. Dust swirled in the thin light from the window. Behind the mower, something scratched against the wall. I held my breath, reached for the box and backed towards the door. Only when I was outside did I discover that the scratching had come from a frightened possum.'\n\nThe revised version has a purpose, setting detail, tension, clear actions and a small resolution. The ideas were revised before anyone checked commas or spelling.\n\nDo not add detail everywhere. Add it where it helps the reader see, understand or feel the important moment.",
              "A useful revision question: 'What does the reader need to know right here?'",
              "Revise the important moments, not every word equally.",
              ("What was added to make the shed paragraph stronger?", ["A reason, sensory detail and a clear tense moment", "Only more full stops", "A new title"], 0, "The revision helps the reader understand and feel the scene.")),
        _step("5", "Edit after revising",
              "When the ideas are working, edit one kind of error at a time. Looking for everything at once makes errors hard to see.\n\nPASS 1: capitals and end punctuation. Check every sentence starts with a capital and ends with . ! or ?\nPASS 2: sentence sense. Read aloud. Does each sentence say what you mean? Are any sentences missing words?\nPASS 3: spelling. Circle words you are unsure of. Use a dictionary with parent help, word bank or the look, say, cover, write, check routine.\nPASS 4: special checks. Look for the grammar and punctuation you have been learning, such as consistent tense, commas after fronted clauses and pronouns that match the point of view.\n\nMessy: 'when the rain started I ran to the boat it was sinking fast'\nEdited: 'When the rain started, I ran to the boat. It was sinking fast.'\n\nEditing is not making every sentence longer. It is making each sentence clear and correct.",
              "Read aloud slowly: if you need to stop where there is no punctuation, the sentence may need a full stop or comma.",
              "Use separate editing passes so you can notice more.",
              ("What should you do before checking spelling?", ["Revise the ideas and structure", "Publish the work", "Delete every adjective"], 0, "First make sure the ideas belong and the story makes sense.")),
        _step("6", "Revise and edit your draft",
              "Use your narrative draft. If you have only a plan, write one planned paragraph first. Work in this order.\n\n1. Read the whole draft once without writing. Say the problem, complication and resolution aloud. If you cannot find one, mark where you need to revise.\n2. Write one strength and one specific improvement.\n3. Choose one paragraph to revise with ARMR. Make at least two meaningful changes, such as adding a sensory detail and replacing a weak verb.\n4. Read the revised paragraph aloud. Check that the point of view and tense stay consistent.\n5. Edit it in four passes: punctuation, sentence sense, spelling, then special checks.\n6. Write a clean final copy of that paragraph. Keep the original draft beside it so you can see what changed.\n\nModel note: 'Strength: the problem is clear. Improvement: slow down the moment the candle goes out.'\n\nWriters are not failing when they change a draft. Changing a draft is how writing becomes stronger.",
              "Revision note: Add a sound when the candle goes out; replace 'went' with 'staggered'.",
              "Revise meaning, edit accuracy, then make a clean copy.",
              ("Which order is best?", ["Draft, revise, edit, proofread, publish", "Proofread, publish, revise", "Publish, then draft"], 0, "Work on the big ideas before the final accuracy checks.")),
    ],
    "Model answers. A draft is a first version. Revise means improve ideas, detail, structure and clarity. Edit means correct sentence accuracy, punctuation, grammar, spelling and word choice. Proofread means make a slow final check. Helpful feedback names a strength and a specific next step. ARMR means add, remove, move and replace. Revised cave sentence: 'Mia edged into the cave. Cold water dripped from the roof onto her neck. When a low growl rolled from the darkness, she stumbled backwards and ran.'",
    "1) Match draft, revise, edit, proofread and publish to their meanings. 2) Give one useful strength and improvement for a short draft. 3) Use ARMR to improve four weak sentences. 4) Compare a first draft and revised paragraph, then name three changes. 5) Edit a short paragraph in separate passes. 6) Revise, edit and rewrite one paragraph of your own narrative.",
    "Choose one paragraph from your narrative. Show the original paragraph, then a revised and edited clean copy. Add a note naming two meaningful changes you made. Upload a photo of both versions.",
    CHECK,
    "Did I revise ideas before fixing spelling? Did I name one strength and one specific improvement? Did I make at least two meaningful ARMR changes? Did I check point of view and tense? Did I edit punctuation, sentence sense and spelling in separate passes? Is my final copy clear and neat?",
    [
        _q("A draft is...", ["a first version that can be changed", "a final published copy", "a spelling rule"], 0, "A draft is an early version of writing."),
        _q("To revise means to...", ["improve ideas, detail or structure", "only check spelling", "throw away every sentence"], 0, "Revision changes meaning and strength."),
        _q("To edit means to...", ["check sentence accuracy and correctness", "choose a new story topic", "draw an illustration"], 0, "Editing checks how writing works."),
        _q("ARMR stands for...", ["add, remove, move, replace", "ask, read, mark, return", "always read more rapidly"], 0, "ARMR gives four ways to revise."),
        _q("Which is useful feedback?", ["Add a detail that shows why the character is worried.", "It is fine.", "Make it better somehow."], 0, "Specific feedback gives the writer a clear next step."),
        _q("What should happen before an editing pass for spelling?", ["Revision of the big ideas", "Publishing", "Writing a title ten times"], 0, "First make sure the content and structure work."),
        _q("Which is a replacement revision?", ["Change 'went' to 'staggered'", "Put a sentence later", "Delete a repeated sentence"], 0, "Replacing swaps a weak choice for a stronger one."),
        _q("Proofreading is best done...", ["slowly, near the end", "before writing a draft", "instead of revising"], 0, "Proofreading catches small remaining errors in a near-final copy."),
    ],
    "Upload a photo of the original paragraph, clean copy and two revision notes.",
    "Ask a parent to choose one paragraph from a story you are reading. Find one revision the author might have made: a precise verb, a sensory detail, a reordered sentence or an omitted repeated idea.",
    [("draft", "An early version of writing that can be changed."), ("revise", "To improve the meaning, detail, structure or clarity of writing."), ("edit", "To check and correct how sentences work, including punctuation, grammar and spelling."), ("proofread", "To make a slow final check for small errors."), ("feedback", "Helpful information about what works and what could improve."), ("publish", "To share or present a final version of writing.")],
    [
        _video("Writing Videos for Kids - REVISION: Revising vs Editing", "nSu0lvaoSOI",
               "Listen for what revising means and how it is different from editing. Pause and say one thing you could revise in your own draft and one thing you could edit.",
               "If the video does not play, write one sentence that tells what revising is and one that tells what editing is.",
               ("Revising means to...", ["see your writing again and improve it", "only fix spelling", "throw the story away"], 0, "Revising means taking another look at the story to make it stronger.")),
    ],
    _sort("Improve the draft", "Which stage is each action part of? Tap a group, then Check.",
          ["Revise", "Edit", "Proofread"],
          [("Add a detail about the storm.", 0), ("Remove a repeated sentence.", 0), ("Check capital letters.", 1), ("Correct a comma after a fronted clause.", 1), ("Read the neat copy slowly for missed letters.", 2), ("Check every word in the final sentence.", 2)]),
    [
        _wc("The first version of writing is a ___.", ["draft", "drift", "drafted"], 0, "A draft is a first version."),
        _wc("To improve ideas and structure is to ___.", ["revise", "revize", "revice"], 0, "Revise means see and improve again."),
        _wc("To make a final slow check is to ___.", ["proofread", "proofreaded", "proof-red"], 0, "Proofread is one word."),
        _wc("Which is spelt correctly?", ["feedback", "feedbak", "feed back"], 0, "Feedback is one word."),
        _wc("Which is spelt correctly?", ["publish", "publush", "pubblish"], 0, "Publish has one b."),
    ],
    [
        {"key": "feedback", "label": "Useful feedback", "hint": "One strength and one specific improvement identified."},
        {"key": "armr", "label": "ARMR revision", "hint": "At least two meaningful changes to one paragraph."},
        {"key": "passes", "label": "Editing passes", "hint": "Punctuation, sentence sense, spelling and special checks completed."},
        {"key": "copy", "label": "Clean final copy", "hint": "A revised and edited paragraph rewritten clearly."},
    ],
    ["Correcting spelling before deciding whether the paragraph belongs.", "Giving vague feedback such as 'make it better'.", "Changing every sentence instead of improving the important parts.", "Trying to edit punctuation, grammar and spelling all at once.", "Throwing away the draft so changes cannot be seen."],
    [{"title": "Revision Detective", "description": "Copy a short weak paragraph, improve it with ARMR, and use coloured marks or labels to show one add, remove, move and replace change.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that revision happened before editing, feedback is specific, at least two meaningful changes were made, point of view and tense are consistent, editing passes were completed, and the clean copy is clearer than the draft. Sorter: Revise: add storm detail; remove repetition. Edit: check capitals; correct comma. Proofread: read neat copy slowly; check final sentence.",
)

A8L3 = build(
    "s2-eng-a8-l3-commas-in-lists-and-clauses", "Punctuation: Commas in Lists and Clauses",
    "Learn the two important jobs commas do in Stage 2 writing: separating items in a list and separating an opening clause from the main clause.",
    "Language: commas in lists and clauses",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Uses commas accurately in lists and after fronted subordinate clauses in narrative writing.",
     "EN2-VOCAB-01": "Learns comma, list, item, clause, main clause and subordinate clause.",
     "EN2-RECOM-01": "Identifies how punctuation groups ideas in a sentence."},
    "We are learning when commas separate items in a list and when a comma separates an opening clause from the main clause.",
    ["I can explain two jobs a comma can do.", "I can use commas to separate items in a list.", "I can find an opening subordinate clause and the main clause.", "I can use a comma after an opening subordinate clause.", "I can check comma use in my own narrative."],
    ["comma", "list", "item", "clause", "main clause", "subordinate clause"],
    ["Paper or notebook", "Pencil", "Your narrative draft"],
    "Child has met fronted subordinate clauses and now learns to apply comma rules from the beginning, alongside the simpler rule for lists.",
    "A comma is a small punctuation mark, but it helps readers group words and hear the shape of a sentence. It is written like this: ,\n\nIn this lesson you will learn two useful comma jobs. First, commas separate items in a LIST. Second, a comma separates an opening SUBORDINATE CLAUSE from the MAIN CLAUSE that completes the sentence.\n\nDo not put commas wherever you pause while talking. Speech pauses change from person to person. Use commas for a clear reason: to separate listed items or to show where an opening clause ends.",
    [
        _step("1", "What a comma does",
              "A comma shows a small boundary inside a sentence. It helps the reader see which words belong together. A comma is not as strong as a full stop: a full stop ends a complete sentence, while a comma usually separates parts inside one sentence.\n\nRead without commas: 'Mia packed a torch a map some rope and two apples.' The reader has to work out where each item ends.\n\nRead with commas: 'Mia packed a torch, a map, some rope and two apples.' Now the four items are clear.\n\nLater you will use a comma after an opening clause: 'When the lights went out, Mia grabbed the torch.' The comma shows that the opening time clause has finished and the main action begins.\n\nUse a comma because it has a job, not because it looks like a place to take a breath.",
              "Comma: a small mark that separates parts of a sentence. Full stop: a mark that ends a complete sentence.",
              "A comma separates parts inside a sentence.",
              ("Which mark separates parts inside a sentence?", ["A comma", "A full stop", "An apostrophe"], 0, "A comma separates parts of a sentence.")),
        _step("2", "Commas in lists",
              "A LIST names three or more items. Put commas between the items so the reader can separate them. Usually use and before the final item.\n\nNo commas: 'The wind shook the windows doors roof and trees.'\nWith commas: 'The wind shook the windows, doors, roof and trees.'\n\nEach item should be the same kind of thing. You can list nouns, actions or describing words.\nNouns: 'She packed matches, blankets, water and food.'\nActions: 'Leo climbed, slipped, grabbed the rail and shouted.'\nDescribing words: 'The cave was cold, narrow, wet and silent.'\n\nYou do not need a comma before and in the simple lists you are writing at this stage. Keep the final pair joined with and.\n\nIf there are only two items, do not use a comma: 'Mia packed a torch and a map.'",
              "List of actions: 'The dog sniffed, scratched, whined and waited.'",
              "Use commas between three or more listed items.",
              ("Which list is punctuated correctly?", ["Mia packed a torch, a map, rope and food.", "Mia packed a torch a map, rope and food.", "Mia, packed a torch, a map, rope and food."], 0, "Commas separate the list items, not the subject and verb.")),
        _step("3", "Do not split a subject and verb",
              "A common comma mistake is putting a comma between the subject and its verb. The SUBJECT is who or what the sentence is about. The VERB tells what the subject does or is. Keep them together.\n\nWrong: 'The storm, battered the lighthouse.'\nRight: 'The storm battered the lighthouse.'\n\nWrong: 'Mia and Leo, searched the beach.'\nRight: 'Mia and Leo searched the beach.'\n\nWhy is it wrong? The reader expects the verb immediately after the subject. A comma creates a break where no break belongs.\n\nA list can appear as the subject, but it still stays connected to its verb: 'Rope, food and water were in the bag.' The commas are separating list items, not separating the subject from were.",
              "Find the subject and verb: 'The old door creaked.' Subject: The old door. Verb: creaked.",
              "Never put a comma between a subject and its verb.",
              ("Which sentence is correct?", ["The waves crashed against the rocks.", "The waves, crashed against the rocks.", "The, waves crashed against the rocks."], 0, "The subject The waves stays joined to the verb crashed.")),
        _step("4", "Clauses: a quick foundation",
              "A CLAUSE is a group of words containing a verb. A MAIN CLAUSE makes sense on its own. A SUBORDINATE CLAUSE adds information but does not make a complete sentence by itself.\n\nMain clause: 'Mia grabbed the torch.' It is complete.\nSubordinate clause: 'When the lights went out.' It leaves us waiting: what happened when the lights went out?\n\nPut them together: 'When the lights went out, Mia grabbed the torch.'\n\nThe opening subordinate clause tells us time, reason, condition or contrast. It often starts with words such as when, while, before, after, because, if, unless or although.\n\nFind the verb in each part. 'When the lights went out' has went. 'Mia grabbed the torch' has grabbed. That is why there are two clauses.",
              "Time clause: 'After the rain stopped, the path shone in the moonlight.'",
              "An opening subordinate clause needs a main clause to complete it.",
              ("Which words are an opening subordinate clause?", ["When the lights went out", "Mia grabbed the torch", "The torch was bright"], 0, "It has a verb but needs a main clause to finish the idea.")),
        _step("5", "Comma after an opening clause",
              "When a subordinate clause comes BEFORE the main clause, put a comma after the opening clause.\n\nOpening clause first: 'Although the rain stung her face, Mia kept rowing.'\nMain clause first: 'Mia kept rowing although the rain stung her face.'\n\nThe meaning is similar, but the punctuation changes because the order changes. The comma marks the end of the opening clause.\n\nTry the bracket test. Put brackets around the opening information: '[Although the rain stung her face], Mia kept rowing.' The comma goes where the opening information ends.\n\nDo not add a comma simply because a sentence contains a conjunction. 'Mia kept rowing although the rain stung her face' does not need this comma because the extra clause comes second.\n\nUse fronted clauses carefully. They can build tension: 'Before the door opened, everyone held their breath.'",
              "Move it: 'Leo hid when he heard the growl.' becomes 'When he heard the growl, Leo hid.'",
              "Opening clause first: comma. Opening clause second: usually no comma.",
              ("Which sentence uses the comma correctly?", ["When the bell rang, the children ran outside.", "When the bell rang the children, ran outside.", "The children, ran outside when the bell rang."], 0, "The comma goes after the opening clause, before the main clause.")),
        _step("6", "Apply the two comma rules",
              "Now use both comma jobs in your own writing.\n\n1. Write three list sentences: one listing objects, one listing actions and one listing describing words. Use at least three items in each list.\n2. Write three sentences with an opening clause. Begin with when, after, before, if, while or although. Put the comma after the opening clause.\n3. Copy one paragraph from your narrative draft. Underline every list and draw a box around every opening clause.\n4. Add or remove commas only when you can explain the job.\n5. Read the paragraph aloud. Check that no comma splits a subject from its verb.\n\nModel list: 'Mia grabbed the torch, the map, the rope and the old key.'\nModel clause: 'Before the trapdoor slammed shut, Mia slid through the gap.'\n\nGood punctuation helps a reader travel through your story without getting lost.",
              "Fix: 'After the storm passed the beach was quiet.' becomes 'After the storm passed, the beach was quiet.'",
              "Explain the comma's job every time you use one.",
              ("What are the two comma jobs in this lesson?", ["Separate list items and end an opening clause", "Start every sentence and end every sentence", "Replace all full stops"], 0, "Commas separate list items and mark the end of an opening subordinate clause.")),
    ],
    "Model answers. A comma separates parts inside a sentence. In a list of three or more items, use commas between items: 'Mia packed a torch, a map, rope and food.' Do not put a comma between a subject and verb: 'The waves crashed against the rocks.' A main clause stands alone; an opening subordinate clause does not. Use a comma after an opening clause: 'When the bell rang, the children ran outside.' Usually do not use that comma when the subordinate clause comes second.",
    "1) Add commas to six lists. 2) Cross out commas that split subjects from verbs. 3) Identify the main and subordinate clause in six sentences. 4) Move four subordinate clauses to the front and add commas. 5) Correct a mixed punctuation paragraph. 6) Add comma checks to a paragraph of your own narrative.",
    "Write three correct list sentences and three correct opening-clause sentences. Then edit one narrative paragraph, marking each comma's job. Upload a photo of your work.",
    CHECK,
    "Did I use commas only between three or more list items? Did I leave the final pair joined with and? Did I avoid a comma between a subject and verb? Did I put a comma after every opening subordinate clause? Did I avoid adding that comma when the subordinate clause comes second? Can I explain the job of each comma?",
    [
        _q("A comma can...", ["separate parts inside a sentence", "replace every full stop", "show a question"], 0, "A comma separates parts inside a sentence."),
        _q("Which list is correct?", ["Rope, food, water and matches", "Rope food, water and matches", "Rope, food water, and matches"], 0, "Commas separate each list item before the final and."),
        _q("Which sentence wrongly splits subject and verb?", ["The dog, barked at the gate.", "The dog barked at the gate.", "The dog, the cat and the bird waited."], 0, "The dog is the subject and barked is its verb; they must stay together."),
        _q("A main clause...", ["can stand alone", "always begins with when", "has no verb"], 0, "A main clause makes complete sense on its own."),
        _q("Which opening clause needs a comma after it?", ["Before the storm arrived, Mia closed the window.", "Mia closed the window before the storm arrived.", "Mia, closed the window before the storm arrived."], 0, "The opening clause ends before the main clause begins."),
        _q("Which sentence is correct?", ["Although he was tired, Leo kept walking.", "Although he was tired Leo, kept walking.", "Leo, kept walking although he was tired."], 0, "The comma follows the opening subordinate clause."),
        _q("How many items should a list have before you use list commas?", ["Three or more", "Exactly two", "Only one"], 0, "Use list commas to separate three or more items."),
        _q("Why should you not put commas wherever you pause?", ["Pauses do not always show a punctuation job", "Commas are only for titles", "A pause is always a full stop"], 0, "Use commas for their grammar jobs, not just for speech pauses."),
    ],
    "Upload a photo of your six sentences and edited narrative paragraph.",
    "Find one list and one opening clause in a parent-chosen book. Copy each sentence, underline the listed items or opening clause, and explain why the comma is there.",
    [("comma", "A punctuation mark that separates parts inside a sentence."), ("list", "Three or more items named in a sentence."), ("item", "One thing, action or description in a list."), ("clause", "A group of words containing a verb."), ("main clause", "A clause that makes complete sense on its own."), ("subordinate clause", "A clause that adds information but needs a main clause.")],
    [
        _video("English Lesson: Commas (in lists) for Kids", "t8q2Bx8q4L0",
               "Watch how a comma separates the items in a list. This video covers lists only, so use step 5 of the lesson for the comma after an opening clause. Pause and say a list sentence of your own.",
               "If the video does not play, write a sentence that lists four things you would pack for a trip, with commas between the items.",
               ("A comma in a list is used to...", ["separate the items", "end the sentence", "show a question"], 0, "Commas separate the items in a list.")),
    ],
    _sort("Comma job", "Why is the comma used in each sentence? Tap a group, then Check.",
          ["List", "Opening clause"],
          [("Mia packed rope, food, water and matches.", 0), ("The cave was cold, wet, narrow and dark.", 0), ("Leo climbed, slipped, grabbed the rail and shouted.", 0), ("When the rain stopped, the path gleamed.", 1), ("Although she was tired, Mia kept rowing.", 1), ("Before the door opened, everyone held their breath.", 1)]),
    [
        _wc("A mark that separates parts of a sentence is a ___.", ["comma", "coma", "commer"], 0, "Comma has two m letters."),
        _wc("Three or more named things make a ___.", ["list", "listen", "least"], 0, "A list names three or more items."),
        _wc("A clause that can stand alone is a ___ clause.", ["main", "minor", "middle"], 0, "A main clause is complete."),
        _wc("Which is spelt correctly?", ["subordinate", "subordnate", "subordinet"], 0, "Subordinate has i before n."),
        _wc("Which is spelt correctly?", ["punctuation", "puncuation", "punctuashion"], 0, "Punctuation ends -tion."),
    ],
    [
        {"key": "lists", "label": "List commas", "hint": "Six lists punctuated correctly."},
        {"key": "subject", "label": "Subject and verb", "hint": "Incorrect commas crossed out and explained."},
        {"key": "clauses", "label": "Opening clauses", "hint": "Six sentences labelled and punctuated."},
        {"key": "draft", "label": "Narrative comma check", "hint": "One narrative paragraph edited with each comma's job marked."},
    ],
    ["Putting commas wherever you pause.", "Putting a comma between the subject and verb.", "Using a comma in a two-item list.", "Forgetting the comma after an opening subordinate clause.", "Adding a comma after a subordinate clause that comes second."],
    [{"title": "Comma Doctor", "description": "Correct a six-sentence punctuation paragraph. Label each comma L for list or OC for opening clause, and explain one comma you removed.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that list commas separate three or more items, no comma splits a subject and verb, opening subordinate clauses have a following comma, second-position subordinate clauses do not get that comma, and every comma has an explainable job. Sorter: List: Mia packed rope; cave was cold; Leo climbed. Opening clause: When rain stopped; Although she was tired; Before the door opened.",
)

A8L4 = build(
    "s2-eng-a8-l4-spelling-tricky-and-common-words", "Spelling: Tricky and Common Words",
    "Learn reliable ways to spell high-frequency words that do not always sound exactly as they look, then use them accurately in your own writing.",
    "Spelling: tricky and common words",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-CWT-01"],
    {"EN2-SPELL-01": "Primary. Spells selected high-frequency and commonly confused words accurately using meaningful spelling strategies.",
     "EN2-VOCAB-01": "Learns common-word, tricky word, sound, letter pattern, homophone and mnemonic.",
     "EN2-CWT-01": "Uses selected common words accurately in sentences and a narrative paragraph."},
    "We are learning how to notice the tricky parts of common words, choose a spelling strategy and use the words accurately in our own writing.",
    ["I can explain what makes a word tricky.", "I can use sound, word parts and a visual memory strategy to spell a word.", "I can choose between commonly confused words using their meaning.", "I can learn a short group of common words and check them in sentences.", "I can proofread common words in my own narrative."],
    ["common word", "tricky word", "sound", "letter pattern", "homophone", "mnemonic"],
    ["Paper or notebook", "Pencil", "Your narrative draft", "A dictionary with parent help if needed"],
    "Child has learned spelling patterns and suffix rules. This lesson teaches an explicit strategy for high-frequency words that need visual memory or meaning checks.",
    "Some words are used so often that spelling them correctly makes writing much easier to read. These are COMMON WORDS. Many common words follow patterns, but some have a part that does not sound exactly as we expect. That part can make a word TRICKY.\n\nFor example, in 'because', the middle sound can be hard to hear clearly. In 'people', the letters eo do not sound the way they do in many other words. In 'their' and 'there', the words sound alike but have different meanings.\n\nTricky words are not learned by staring at a long list. Good spellers notice the part that is difficult, choose a strategy, practise briefly from memory and use the word in a meaningful sentence. This lesson teaches that process step by step.",
    [
        _step("1", "Common words and tricky parts",
              "A COMMON WORD is a word we use often in reading and writing. Examples include because, people, friends, different, through, thought, their, there and they're.\n\nA TRICKY WORD has a part that is hard to spell by sound alone. The whole word is not necessarily tricky. Find the small part that needs extra attention.\n\nbecause: say be-cause; notice the a-u in cause.\npeople: say people; notice the e-o in the middle.\nfriends: say friends; notice ie, not ei.\ndifferent: split it dif-fer-ent; notice the double f and the ending ent.\n\nWhen you notice the exact tricky part, your brain has a smaller job. Do not just say, 'I cannot spell it.' Say, 'The tricky part is ___.'",
              "Mark the tricky part: becAUse, pEOple, frIEnds, diFFerent.",
              "Find the small part that needs special attention.",
              ("Which part of 'different' needs special attention?", ["The double f", "The first d", "The full stop"], 0, "Different has two f letters in the middle.")),
        _step("2", "Use more than one clue",
              "Strong spellers use more than one clue.\n\nSOUND: say the word slowly and listen for the parts you can hear. 'To-geth-er' helps with together.\n\nWORD PARTS: split a word into chunks. 'Sep-a-rate' has three useful chunks. 'Every-thing' contains every and thing.\n\nLETTER PATTERN: notice a group of letters that stays together. In 'thought', the ough is a pattern to remember.\n\nMEANING: use the sentence to choose a word. 'Their boat was blue' means the boat belongs to them. 'There was a boat' means in that place. 'They\'re on the boat' means they are.\n\nVISUAL MEMORY: look carefully at the word, cover it, write it from memory, then check every letter. This is not a guess. It tells you exactly what to practise next.",
              "For 'separate': say sep-a-rate, then remember that it has an a in the middle: sepArate.",
              "Sound, word parts, patterns, meaning and visual memory work together.",
              ("Which clue helps you choose between their, there and they're?", ["Meaning in the sentence", "The page number", "The title"], 0, "The words sound alike, so the sentence meaning tells you which one fits.")),
        _step("3", "Look, say, cover, write, check",
              "Use this routine for one word at a time.\n\n1. LOOK at the word. Read it slowly and circle the tricky part.\n2. SAY it in chunks or make a useful saying.\n3. COVER the word so you cannot copy it.\n4. WRITE it from memory.\n5. CHECK every letter against the model. If it is wrong, do not erase angrily. Mark the part that changed, then repeat the routine.\n\nExample with 'because'. Look: because. Mark the tricky part: becAUse. Say: 'Be-cause: a cause begins with au.' Cover. Write: because. Check b-e-c-a-u-s-e.\n\nExample with 'people'. Look: people. Mark pEOple. Say: 'People has eo in the middle.' Cover, write and check.\n\nPractise a few words well. Ten careful attempts on one word teach more than copying twenty words without looking.",
              "If you write 'becuase', compare it letter by letter with because and notice that a-u has been swapped.",
              "Cover the word before writing so memory does the work.",
              ("Why do you cover the word before writing it?", ["To practise remembering the spelling", "To make the word disappear forever", "To avoid checking it"], 0, "Covering stops copying and makes the brain retrieve the word.")),
        _step("4", "Commonly confused words",
              "Some tricky words are HOMOPHONES: they sound the same but have different spellings and meanings. Do not choose by sound. Choose by meaning.\n\nthere means in or at that place: 'Put the bag over there.'\ntheir means belongs to them: 'Their lantern was wet.'\nthey're means they are: 'They\'re waiting outside.' Try replacing it with they are.\n\nyour means belongs to you: 'Your map is on the table.'\nyou're means you are: 'You\'re carrying the map.' Try replacing it with you are.\n\nto means toward or part of an infinitive: 'We walked to the cave.'\ntoo means also or more than needed: 'Mia was too tired to run.'\ntwo means the number 2: 'Two torches lay on the shelf.'\n\nThe apostrophe in they're and you're shows missing letters. It does not make a word plural.",
              "Test: 'They\'re late' can become 'They are late', so they're is correct.",
              "Use meaning tests for words that sound alike.",
              ("Which word completes '___ waiting by the gate' ?", ["They're", "Their", "There"], 0, "They are waiting by the gate, so the contraction they're is needed.")),
        _step("5", "Learn this week's word set",
              "This week, learn these twelve words: because, people, friends, different, through, thought, enough, separate, their, there, they're and you're.\n\nSort them by strategy.\n\nTricky letter patterns: because (au), people (eo), friends (ie), different (ff), through (ough), thought (ough), enough (ough), separate (a).\n\nMeaning choices: their, there, they're, you're.\n\nYou do not need one trick for every word. Say through as through and notice the whole ough pattern. Compare thought and enough: they share letters but do not sound the same. English spelling sometimes needs visual memory as well as sound.\n\nMake a personal word card for each word you miss. On the front, write the word with its tricky part marked. On the back, write a sentence that proves its meaning. Review only the cards you need.",
              "Word card: front 'thEIR' and back 'Their boat belongs to them.'",
              "Learn a short set deeply, with the strategy that fits each word.",
              ("Which word has the same letter pattern as thought but a different sound?", ["enough", "friends", "people"], 0, "Thought and enough both contain ough, but the pattern is pronounced differently.")),
        _step("6", "Practise, test and proofread",
              "Practise the twelve words in a useful way.\n\n1. Choose six words that are hardest for you. Mark each tricky part and write the strategy you will use.\n2. Do look, say, cover, write, check twice for each chosen word.\n3. Complete these meaning checks: '___ friends were waiting ___ the gate because ___ early.' Answer: Their, there, they're. '___ carrying your torch.' Answer: You're.\n4. Ask a parent to read ten words from the set aloud in mixed order. Write them from memory, then check them together.\n5. Proofread one paragraph of your narrative. Circle every word from this week's set or any word you often miss. Check each one with a strategy, dictionary or parent help.\n6. Write two accurate sentences that use at least two words from the set each.\n\nModel: 'Because their torch had gone out, the two friends waited there until dawn.'\n\nA spelling test is useful only when you use its results. Keep a small list of words to practise next time.",
              "Sentence: 'You're different from the people who gave up, because you kept going through the rain.'",
              "Notice, practise from memory, check meaning, then use the words.",
              ("What should you do after a spelling test?", ["Use the missed words to choose what to practise next", "Forget every result", "Only copy the easy words"], 0, "Missed words show exactly what needs another practice turn.")),
    ],
    "Model answers. A common word is used often. A tricky word has a part that cannot always be spelled by sound alone. Useful strategies include sound, word parts, letter patterns, meaning and look, say, cover, write, check. Their means belongs to them; there means in that place; they're means they are; you're means you are. This week's word set is because, people, friends, different, through, thought, enough, separate, their, there, they're and you're. Model sentence: 'Because their torch had gone out, the two friends waited there until dawn.'",
    "1) Mark the tricky parts in eight common words. 2) Match five words to a useful spelling strategy. 3) Practise six words with look, say, cover, write, check. 4) Choose their, there, they're, your or you're for ten sentences and explain why. 5) Complete a mixed ten-word test with a parent. 6) Proofread one narrative paragraph and write two accurate sentences using the word set.",
    "Make a word-practice page for six difficult words, including the tricky part and strategy for each. Complete a ten-word test and proofread one narrative paragraph. Upload a photo of the page, test and corrected paragraph.",
    CHECK,
    "Did I mark the tricky part of each chosen word? Did I choose a useful strategy rather than only copying? Did I cover the word before writing it from memory? Did I use meaning to choose their, there, they're, your and you're? Did I check a paragraph from my own writing? Did I record the words I still need to practise?",
    [
        _q("A tricky word is one that...", ["has a part that may be hard to spell by sound alone", "is never used", "must be written in capitals"], 0, "Tricky words often need a visual-memory or meaning strategy."),
        _q("Which is the correct spelling?", ["because", "becuase", "becouse"], 0, "Because has a-u in the middle."),
        _q("Which word means 'belongs to them'?", ["their", "there", "they're"], 0, "Their shows possession."),
        _q("Which word can be replaced with 'they are'?", ["they're", "their", "there"], 0, "They're is short for they are."),
        _q("Which word completes 'Put the bag over ___'?", ["there", "their", "they're"], 0, "There means in that place."),
        _q("Why do you use look, say, cover, write, check?", ["To practise remembering and checking a spelling", "To copy without thinking", "To avoid writing words"], 0, "The routine makes you retrieve the word from memory and compare it carefully."),
        _q("Which word contains the same letter pattern as thought?", ["enough", "people", "different"], 0, "Both thought and enough contain ough."),
        _q("What is a useful next step after a spelling test?", ["Practise the words you missed", "Erase the test and forget it", "Only practise the words you got right"], 0, "Your errors show which word cards need another practice turn."),
    ],
    "Upload a photo of your word-practice page, ten-word test and proofread paragraph.",
    "In a parent-chosen book, find five common words that you sometimes misspell. Make a word card for each: mark the tricky part, name a strategy and use the word in a new sentence.",
    [("common word", "A word used often in reading and writing."), ("tricky word", "A word with a part that may be difficult to spell by sound alone."), ("sound", "What a word or part of a word sounds like when spoken."), ("letter pattern", "A group of letters noticed together in a word."), ("homophone", "A word that sounds like another word but has a different spelling and meaning."), ("mnemonic", "A memory aid, such as a short saying or picture clue.")],
    [],
    _sort("Choose by meaning", "Which word completes each sentence? Tap a group, then Check.",
          ["there", "their", "they're"],
          [("Put the torch over ___.", 0), ("We waited ___ until dark.", 0), ("___ boat was tied to the jetty.", 1), ("The friends packed ___ bags.", 1), ("___ ready to leave.", 2), ("I think ___ hiding in the shed.", 2)]),
    [
        _wc("Which is spelt correctly?", ["because", "becuase", "becouse"], 0, "Because has a-u in the middle."),
        _wc("Which is spelt correctly?", ["different", "diffrent", "diferent"], 0, "Different has double f."),
        _wc("Which is spelt correctly?", ["separate", "seperate", "sepparate"], 0, "Separate has an a in the middle."),
        _wc("A word that sounds the same as another but has a different meaning is a ___.", ["homophone", "homonymn", "homaphone"], 0, "Homophones sound the same."),
        _wc("A memory aid is a ___.", ["mnemonic", "pneumonic", "memoryic"], 0, "Mnemonic begins with mn."),
    ],
    [
        {"key": "parts", "label": "Tricky parts spotted", "hint": "The tricky parts marked in eight words."},
        {"key": "strategies", "label": "Strategies chosen", "hint": "A useful strategy named for six words."},
        {"key": "meaning", "label": "Meaning choices", "hint": "Their, there, they're, your and you're chosen and explained."},
        {"key": "test", "label": "Test and proofread", "hint": "A mixed ten-word test and one checked narrative paragraph."},
    ],
    ["Copying words many times without covering them.", "Trying to spell every word by sound alone.", "Choosing their, there or they're by sound instead of meaning.", "Forgetting that you're means you are.", "Ignoring misspelled words after a test."],
    [{"title": "Word Strategy Cards", "description": "Make six small word cards. Mark the tricky part, write the strategy, and add a sentence that proves the word's meaning. Test yourself tomorrow without looking.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that the tricky part is marked, a strategy fits each word, words are recalled from memory rather than copied, homophones are chosen by meaning, spelling-test errors guide further practice, and the narrative paragraph has been proofread. Sorter: there: Put the torch; waited there. their: Their boat; their bags. they're: They're ready; they're hiding.",
)

LESSONS = [A8L1, A8L2, A8L3, A8L4]
