# Stage 2 Year 3 Maths lessons 10 and 11 for Ollie. Same structure as the Cartographer quest.
# Not yet registered in LESSON_LIBRARY. No reflection prompts (parent preference).
# Resource links marked 'search' are search pages, not specific items.

MINI_LESSONS = "https://iview.abc.net.au/show/mini-lessons-maths"


def _common(**kw):
    base = {
        "library": True,
        "stage": "S2",
        "year_level": "Year 3",
        "learning_area": "Mathematics",
        "pass_mark": 0.9,
        "reflection_prompts": [],
        "accessibility_notes": "Allow real boxes, paper nets, a compass drawing and a model clock throughout. Answers can be spoken instead of written. Reduce the independent task to two parts if needed. Replay any video as often as needed.",
        "source_note": "Outcome codes checked against published NESA code lists. Parent to verify the exact outcome wording on curriculum.nsw.edu.au.",
    }
    base.update(kw)
    return base


LESSON_3D = _common(
    seed_key="s2-y3-maths-3d-shapes-box-factory-10",
    subject="3D objects: prisms, pyramids, faces, edges, vertices and nets",
    title="The Box Factory",
    child_mission="The Box Factory needs a new designer. Name each 3D shape, count its faces, edges and vertices, and unfold boxes into flat nets before the machines start.",
    duration_minutes=75,
    outcome_codes=["MA2-3DS-01", "MAO-WM-01"],
    cross_outcome_codes=[],
    outcome_notes={
        "MA2-3DS-01": "Primary. Names and describes prisms and pyramids by faces, edges and vertices and matches them to their nets (steps 1-5, quiz 1-10, sort).",
        "MAO-WM-01": "Working mathematically: builds models, tests nets by folding and explains how a shape was classified (hands-on activity, independent task, rubric).",
    },
    learning_intention="We are learning to describe prisms and pyramids by their faces, edges and vertices and to match them to nets.",
    success_criteria=[
        "I can name faces, edges and vertices.",
        "I can tell a prism from a pyramid.",
        "I can name a prism or pyramid by the shape of its base.",
        "I can count faces, edges and vertices of common solids.",
        "I can match a 3D shape to its net.",
        "I can score 90% or more on the Quest check.",
    ],
    key_vocabulary=["face", "edge", "vertex", "vertices", "prism", "pyramid", "net", "base", "cube", "cylinder", "cone", "sphere"],
    materials=["Cardboard boxes and tubes", "Scissors and tape", "Paper or card", "Ruler", "Device"],
    prior_knowledge="Child can name a cube, sphere, cone and cylinder and knows 2D shapes up to octagon.",
    common_misconceptions=[
        {"misconception": "The child counts only the faces they can see.", "fix": "Turn the shape over in your hands. Mark each face with a sticker as you count."},
        {"misconception": "The child calls a pyramid a prism because it has flat faces.", "fix": "A prism has two matching ends and rectangle sides. A pyramid comes to a point."},
        {"misconception": "The child thinks any flat pattern of the right shapes is a net.", "fix": "Fold it up. If faces overlap or leave gaps, it is not a net."},
    ],
    explicit_teaching="A FACE is a flat surface. An EDGE is where two faces meet. A VERTEX is a corner where edges meet. A PRISM has two matching end faces (its bases) joined by rectangles. We name a prism by its base, such as a triangular prism or a rectangular prism. A PYRAMID has one base and triangular faces that meet at a point. We name a pyramid by its base, such as a square pyramid. Cylinders, cones and spheres are not prisms or pyramids because they have curved surfaces. A NET is a flat pattern that folds to make a 3D shape. A cube has 6 faces, 12 edges and 8 vertices.",
    teach_steps=[
        {"icon": "📦", "title": "Faces, edges, vertices", "explain": "Faces are flat surfaces. Edges are where faces meet. Vertices are corners.\n\nTry it: put a sticker on each face of a box and count them.", "example": "A cube has 6 faces, 12 edges and 8 vertices.", "notice": "Count the hidden ones too.", "check": {"question": "How many faces does a cube have?", "options": ["4", "6", "8"], "correct_index": 1, "explanation": "A cube has 6 square faces."}},
        {"icon": "🧱", "title": "Prisms", "explain": "A prism has two matching ends joined by rectangle faces. We name it by the shape of its ends.\n\nTry it: find a box that is a rectangular prism.", "example": "A triangular prism has 2 triangle ends and 3 rectangles. It has 5 faces, 9 edges and 6 vertices.", "notice": "Same shape all the way through.", "check": {"question": "A solid has 2 triangle faces and 3 rectangle faces. What is it?", "options": ["triangular pyramid", "triangular prism", "cone"], "correct_index": 1, "explanation": "This is a triangular prism."}},
        {"icon": "🔺", "title": "Pyramids", "explain": "A pyramid has one base and triangular faces that meet at a point. We name it by its base.\n\nTry it: make a square pyramid with modelling clay.", "example": "A square pyramid has a square base and 4 triangles. It has 5 faces, 8 edges and 5 vertices.", "notice": "Pyramids come to a point.", "check": {"question": "How many vertices does a square pyramid have?", "options": ["4", "5", "8"], "correct_index": 1, "explanation": "4 base corners plus 1 point is 5 vertices."}},
        {"icon": "📐", "title": "Nets", "explain": "A net is a flat pattern that folds into a 3D shape. Different nets can make the same shape.\n\nTry it: cut open a cereal box and lay it flat.", "example": "A cube net has 6 squares. A square pyramid net has 1 square and 4 triangles.", "notice": "Faces in a net must fold without overlapping.", "check": {"question": "A square pyramid net has ___.", "options": ["1 square and 4 triangles", "6 squares", "2 triangles and 3 rectangles"], "correct_index": 0, "explanation": "Square base plus 4 triangles."}},
        {"icon": "♻️", "title": "Comparing solids", "explain": "Compare solids using faces, edges and vertices. Cylinders, cones and spheres have curved surfaces so they are not prisms or pyramids.\n\nTry it: build a table of faces, edges and vertices for four solids.", "example": "Rectangular prism: 6, 12, 8. Triangular pyramid: 4, 6, 4.", "notice": "Make a table so you do not lose count.", "check": {"question": "How many faces does a triangular pyramid have?", "options": ["3", "4", "6"], "correct_index": 1, "explanation": "1 triangle base and 3 triangle sides make 4 faces."}},
    ],
    worked_example="Describe a triangular prism. Faces: 2 triangles and 3 rectangles, so 5 faces. Edges: 3 on each triangle (6) plus 3 joining edges, so 9. Vertices: 3 on each triangle, so 6. Its net has 2 triangles and 3 rectangles in a row with the triangles attached to the sides. Compare with a triangular pyramid: 4 faces, 6 edges, 4 vertices.",
    guided_practice="Pick three boxes or containers. Name each shape, count faces, edges and vertices and sketch the net. Then fold a paper net to test it.",
    practice_questions=[
        {"q": "Faces of a rectangular prism", "a": "6"},
        {"q": "Edges of a cube", "a": "12"},
        {"q": "Vertices of a triangular prism", "a": "6"},
        {"q": "Name a solid with 1 square face and 4 triangle faces", "a": "Square pyramid"},
        {"q": "Is a cylinder a prism?", "a": "No, it has curved surfaces"},
        {"q": "Edges of a triangular pyramid", "a": "6"},
    ],
    hands_on_activity="Net lab. Carefully open a cereal box along its glued edges and lay it flat. Trace the net on card and fold it back to check it works. Then design a net for a triangular prism and a square pyramid and fold each one. Record the number of faces, edges and vertices of each solid in a table.",
    independent_task="Design a gift box for the factory. Choose a prism or pyramid and draw its net with measurements. Label the shape of each face, then build it from card. Write a table with the faces, edges and vertices of your box. Then explain why a sphere and a cylinder cannot be built from a net of flat faces only.",
    cross_curricular={"title": "Link idea", "note": "None recorded. Nets and packaging link to Technologies design work."},
    response_prompt="Label your net and show the table of faces, edges and vertices.",
    self_check="Did I fold my net to test it? Did I count the hidden faces and edges? Did I name the shape by its base?",
    rubric={"title": "What to look for", "levels": [
        {"level": "Getting started", "descriptor": "Names a cube and counts visible faces. Needs help with edges, vertices and nets."},
        {"level": "Secure", "descriptor": "Names prisms and pyramids, counts faces, edges and vertices and matches a solid to its net."},
        {"level": "Strong", "descriptor": "Designs and folds a net, explains why a net works and compares several solids in a table."},
    ]},
    interactive_activities=[{"type": "flip_cards", "title": "Quest Codex: key terms", "cards": [
        {"front": "Face", "back": "A flat surface of a 3D object."},
        {"front": "Edge", "back": "Where two faces meet."},
        {"front": "Vertex", "back": "A corner where edges meet."},
        {"front": "Prism", "back": "A solid with two matching ends joined by rectangles."},
        {"front": "Pyramid", "back": "A solid with one base and triangle faces that meet at a point."},
        {"front": "Net", "back": "A flat pattern that folds into a 3D shape."},
        {"front": "Base", "back": "The face a solid is named after."},
        {"front": "Cylinder", "back": "A solid with two circle ends and a curved side. Not a prism."},
    ]}],
    sort_activity={"title": "Prism, pyramid or neither?", "instructions": "Sort each solid.", "buckets": ["Prism", "Pyramid", "Neither"], "items": [
        {"text": "Cube", "answer": 0}, {"text": "Rectangular prism", "answer": 0}, {"text": "Triangular prism", "answer": 0}, {"text": "Square pyramid", "answer": 1},
        {"text": "Triangular pyramid", "answer": 1}, {"text": "Cylinder", "answer": 2}, {"text": "Sphere", "answer": 2}, {"text": "Cone", "answer": 2},
    ]},
    word_challenges=[
        {"question": "A flat surface of a solid is a ___.", "options": ["face", "edge", "vertex"], "correct_index": 0, "explanation": "A face is a flat surface."},
        {"question": "A corner of a solid is a ___.", "options": ["vertex", "face", "net"], "correct_index": 0, "explanation": "A vertex is a corner."},
        {"question": "A flat pattern that folds into a solid is a ___.", "options": ["net", "base", "edge"], "correct_index": 0, "explanation": "This is a net."},
        {"question": "A solid that comes to a point is a ___.", "options": ["pyramid", "prism", "cube"], "correct_index": 0, "explanation": "Pyramids come to a point."},
    ],
    planner_fields=[
        {"key": "shape", "label": "My box shape", "hint": "Name the prism or pyramid."},
        {"key": "counts", "label": "Faces, edges, vertices", "hint": "Write the three counts."},
        {"key": "net", "label": "My net", "hint": "List the faces your net needs."},
    ],
    steps=[
        {"title": "Step 1: Accept the quest", "detail": "Read your mission and accept the quest.", "duration_minutes": 5},
        {"title": "Step 2: Watch and warm up", "detail": "Watch an ABC Mini Lessons Maths episode on 3D objects, then do the net lab.", "duration_minutes": 15},
        {"title": "Step 3: Learn the skills", "detail": "Five short lessons: parts, prisms, pyramids, nets and comparing.", "duration_minutes": 15},
        {"title": "Step 4: Practise", "detail": "Flip the key-term cards, sort solids, answer word challenges and do the practice questions.", "duration_minutes": 10},
        {"title": "Step 5: Plan and build", "detail": "Fill in your planner, then complete the independent task.", "duration_minutes": 20},
        {"title": "Step 6: Clear the Quest check", "detail": "Answer the 10-question Quest check. You need 9 out of 10 to pass.", "duration_minutes": 5},
        {"title": "Step 7: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
    ],
    resources=[
        {"type": "video", "title": "ABC Mini Lessons: Maths (series page; choose a 3D object episode for Years 3-4)", "url": MINI_LESSONS, "prompt": "Pick an episode on 3D objects. Pause and try each example first."},
        {"type": "worksheet", "title": "Twinkl Australia: 3D shapes nets Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=3d+shapes+nets+year+3", "prompt": "Choose a printable worksheet. Log in to your Twinkl account to download."},
        {"type": "worksheet", "title": "Twinkl Australia: prisms and pyramids Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=prisms+and+pyramids+year+3", "prompt": "Choose a printable worksheet."},
    ],
    quiz=[
        {"question": "How many faces does a cube have?", "type": "multiple_choice", "options": ["4", "6", "8", "12"], "correct_index": 1, "explanation": "A cube has 6 faces."},
        {"question": "How many edges does a cube have?", "type": "multiple_choice", "options": ["6", "8", "12", "16"], "correct_index": 2, "explanation": "A cube has 12 edges."},
        {"question": "How many vertices does a square pyramid have?", "type": "multiple_choice", "options": ["4", "5", "6", "8"], "correct_index": 1, "explanation": "4 base corners plus the point is 5."},
        {"question": "A solid has 2 triangle faces and 3 rectangle faces. What is it?", "type": "multiple_choice", "options": ["triangular pyramid", "triangular prism", "cone", "cube"], "correct_index": 1, "explanation": "This is a triangular prism."},
        {"question": "A net of a cube has how many squares?", "type": "multiple_choice", "options": ["4", "5", "6", "8"], "correct_index": 2, "explanation": "A cube has 6 square faces."},
        {"question": "A net of a square pyramid has ___.", "type": "multiple_choice", "options": ["1 square and 4 triangles", "6 squares", "2 triangles and 3 rectangles", "2 circles"], "correct_index": 0, "explanation": "One square base and 4 triangles."},
        {"question": "How many faces does a triangular pyramid have?", "type": "multiple_choice", "options": ["3", "4", "5", "6"], "correct_index": 1, "explanation": "It has 4 triangle faces."},
        {"question": "How many vertices does a rectangular prism have?", "type": "multiple_choice", "options": ["6", "8", "10", "12"], "correct_index": 1, "explanation": "A rectangular prism has 8 vertices."},
        {"question": "We name a prism by ___.", "type": "multiple_choice", "options": ["the shape of its matching ends", "its colour", "its size", "how heavy it is"], "correct_index": 0, "explanation": "The matching end faces give the prism its name."},
        {"question": "How many edges does a triangular prism have?", "type": "multiple_choice", "options": ["6", "8", "9", "12"], "correct_index": 2, "explanation": "6 edges on the triangle ends plus 3 joining edges is 9."},
    ],
    evidence_instructions="Upload a photo of your folded gift box, its net, and your table of faces, edges and vertices.",
    parent_notes="Seven steps, about 75 minutes. Covers faces, edges, vertices, prisms, pyramids and nets. Look for: counting hidden faces, naming by base and testing a net by folding. Outcomes: MA2-3DS-01 (models and nets of prisms and pyramids) and MAO-WM-01. Video resource is a series page: choose one episode.",
    offline_alternative="Use real boxes, tubes and paper nets with a printed worksheet.",
    extension="Find three different nets for a cube. Explain why a row of 6 squares in a line cannot fold into a cube.",
    follow_up_challenges=[
        {"title": "Package hunt", "description": "Find five packages at home and name their shapes. Record faces, edges and vertices.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
        {"title": "Build a city", "description": "Build a model city from boxes and nets. Label each solid.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
    ],
)


LESSON_MAPS_ANGLES = _common(
    seed_key="s2-y3-maths-maps-angles-navigator-11",
    subject="Grid maps, directions and angles compared to a right angle",
    title="The Navigator",
    child_mission="You are the navigator on a treasure expedition. Read the grid map, steer by compass directions and make exact turns to reach the treasure.",
    duration_minutes=75,
    outcome_codes=["MA2-GM-01", "MA2-GM-03", "MAO-WM-01"],
    cross_outcome_codes=[],
    outcome_notes={
        "MA2-GM-01": "Primary. Describes position on a grid map using grid references and compass directions and follows routes (steps 1-3, quiz 1-5).",
        "MA2-GM-03": "Primary. Compares angles to a right angle and describes quarter, half and full turns (steps 4-5, quiz 6-10, sort).",
        "MAO-WM-01": "Working mathematically: plans a route, tests it and explains each turn (hands-on activity, independent task, rubric).",
    },
    learning_intention="We are learning to describe positions and routes on a grid map and to compare angles to a right angle.",
    success_criteria=[
        "I can name the eight compass directions.",
        "I can find and write a grid reference.",
        "I can give and follow directions for a route.",
        "I can say if an angle is less than, equal to or more than a right angle.",
        "I can describe quarter, half and full turns.",
        "I can score 90% or more on the Quest check.",
    ],
    key_vocabulary=["grid map", "grid reference", "compass", "north", "south", "east", "west", "route", "angle", "right angle", "quarter turn", "half turn", "clockwise"],
    materials=["Grid paper", "Pencil and ruler", "Small toy or counter", "A paper corner or set square", "Device"],
    prior_knowledge="Child knows left and right, north, south, east and west and can read a simple map.",
    common_misconceptions=[
        {"misconception": "The child reads a grid reference in the wrong order.", "fix": "In this quest, say the column letter first, then the row number: D3 is across to D, then up to 3."},
        {"misconception": "The child thinks a bigger-looking angle has longer arms and so is bigger.", "fix": "Angle size is about the opening between the arms, not their length."},
        {"misconception": "The child turns the wrong way for clockwise.", "fix": "Clockwise goes the same way as the hands of a clock."},
    ],
    explicit_teaching="A GRID MAP uses columns (letters) and rows (numbers) to describe position. A GRID REFERENCE gives the column letter first and then the row number, such as D3. A COMPASS shows the directions north, east, south and west, and the in-between directions north-east, south-east, south-west and north-west. A ROUTE is a path from one place to another described by directions and turns. An ANGLE is the amount of turn between two lines that meet. A RIGHT ANGLE is a square corner, or a quarter turn. An angle smaller than a right angle is less than a right angle. An angle larger than a right angle is more than a right angle. A half turn is 2 right angles and a full turn is 4 right angles.",
    teach_steps=[
        {"icon": "🧭", "title": "Compass directions", "explain": "North is up on most maps. East is to the right, south is down and west is to the left. In-between directions combine two, such as north-east.\n\nTry it: draw a compass rose and label all eight directions.", "example": "North-east is halfway between north and east. The opposite of north-east is south-west.", "notice": "Opposite directions are on opposite sides of the compass.", "check": {"question": "What is the opposite of north-east?", "options": ["south-west", "north-west", "south-east"], "correct_index": 0, "explanation": "The opposite of north-east is south-west."}},
        {"icon": "🗺️", "title": "Grid references", "explain": "Go across to the column letter, then up to the row number. Write the letter first, then the number.\n\nTry it: put a counter on C2 on a grid and name its reference.", "example": "The library is in column D, row 3. Its grid reference is D3.", "notice": "Across first, then up.", "check": {"question": "In the grid reference C2, what does the letter C tell you?", "options": ["the column", "the row", "the direction"], "correct_index": 0, "explanation": "The letter names the column."}},
        {"icon": "🥾", "title": "Routes and directions", "explain": "Give directions with compass directions and number of squares, such as 'go 3 squares east'.\n\nTry it: write a route from A1 to D4 and test it.", "example": "From A1: go 3 squares east, then 3 squares north to reach D4.", "notice": "Say the direction and the distance.", "check": {"question": "From B2 you go 2 squares east. Where do you end up?", "options": ["B4", "D2", "D4"], "correct_index": 1, "explanation": "Going east moves you across to column D, still in row 2."}},
        {"icon": "📐", "title": "Angles and the right angle", "explain": "A right angle is a square corner. Compare other angles by fitting a paper corner. Smaller means less than a right angle. Larger means more than a right angle.\n\nTry it: test five corners at home with a paper corner.", "example": "The corner of a book is a right angle. The hands of a clock at 2:00 make an angle less than a right angle.", "notice": "Compare the opening, not the length of the arms.", "check": {"question": "The hands of a clock at 3:00 make ___.", "options": ["less than a right angle", "a right angle", "more than a right angle"], "correct_index": 1, "explanation": "At 3:00 the hands make a right angle."}},
        {"icon": "🔄", "title": "Quarter, half and full turns", "explain": "A quarter turn is 1 right angle. A half turn is 2 right angles. A full turn is 4 right angles and brings you back to where you started.\n\nTry it: face north and make quarter turns clockwise. Say your direction each time.", "example": "Facing north, a quarter turn clockwise faces east. A half turn from east faces west.", "notice": "Clockwise follows the clock hands.", "check": {"question": "Facing east, you make a half turn. Which way do you face?", "options": ["north", "west", "south"], "correct_index": 1, "explanation": "A half turn faces the opposite direction, which is west."}},
    ],
    worked_example="The treasure map is a grid with columns A to F and rows 1 to 6. You start at B2 facing north. Go 3 squares north to B5. Make a quarter turn clockwise to face east. Go 2 squares east to D5. D5 is the treasure. Every turn was a right angle. If you made a half turn at D5, you would face west, which is 2 right angles.",
    guided_practice="On a grid, mark a start at A1 and the treasure at E4. Write a route using compass directions and squares. Test it with a counter. Then add two turns and say whether each turn is a quarter, half or full turn.",
    practice_questions=[
        {"q": "What is the opposite of south?", "a": "North"},
        {"q": "Facing north, a quarter turn clockwise faces which direction?", "a": "East"},
        {"q": "Grid reference for column B, row 4", "a": "B4"},
        {"q": "How many right angles in a half turn?", "a": "2"},
        {"q": "Is the angle on a clock at 4:00 less than, equal to or more than a right angle?", "a": "More than"},
        {"q": "From C1 go 2 squares north. Where do you end up?", "a": "C3"},
    ],
    hands_on_activity="Treasure walk. Draw a 6 by 6 grid on paper and label the columns A to F and rows 1 to 6. Place a toy at a start square and hide treasure on another. Write directions to the treasure using compass directions and squares. Swap with your parent and follow their directions. Then use a paper corner to find three angles around the house that are less than, equal to and more than a right angle.",
    independent_task="Make a treasure map. Draw a grid map with at least six landmarks and give each a grid reference. Write a route from the start to the treasure with at least four directions and two turns. Label each turn as a quarter turn, half turn or three-quarter turn. Finally find and sketch three angles from around the house and label them less than, equal to or more than a right angle.",
    cross_curricular={"title": "Link idea", "note": "None recorded. Maps link to Geography when it is covered."},
    response_prompt="Show your map with grid references, your route and the angle sketches.",
    self_check="Did I write the column letter first? Did I test my route? Did I compare angles with a paper corner?",
    rubric={"title": "What to look for", "levels": [
        {"level": "Getting started", "descriptor": "Uses north, south, east and west with support. Needs help with grid references or angles."},
        {"level": "Secure", "descriptor": "Uses all eight directions, writes grid references correctly, follows routes and compares angles to a right angle."},
        {"level": "Strong", "descriptor": "Writes accurate multi-step routes with turns, explains turns using right angles and checks with a model."},
    ]},
    interactive_activities=[{"type": "flip_cards", "title": "Quest Codex: key terms", "cards": [
        {"front": "Grid map", "back": "A map with columns and rows used to describe position."},
        {"front": "Grid reference", "back": "A letter and a number that name a square, like D3."},
        {"front": "Compass", "back": "A tool that shows north, east, south and west."},
        {"front": "Route", "back": "A path from one place to another."},
        {"front": "Angle", "back": "The amount of turn between two lines that meet."},
        {"front": "Right angle", "back": "A square corner, or a quarter turn."},
        {"front": "Half turn", "back": "Two right angles. You face the opposite way."},
        {"front": "Clockwise", "back": "The direction the hands of a clock move."},
    ]}],
    sort_activity={"title": "Compare to a right angle", "instructions": "Sort each angle.", "buckets": ["Less than a right angle", "A right angle", "More than a right angle"], "items": [
        {"text": "Corner of a book", "answer": 1}, {"text": "Clock hands at 3:00", "answer": 1}, {"text": "Clock hands at 2:00", "answer": 0}, {"text": "Slice of a pizza cut into 8", "answer": 0},
        {"text": "Laptop leaning far back", "answer": 2}, {"text": "Clock hands at 4:00", "answer": 2}, {"text": "Corner of a square", "answer": 1}, {"text": "Tip of a sharp pencil point", "answer": 0},
    ]},
    word_challenges=[
        {"question": "A square corner is a ___.", "options": ["right angle", "half turn", "route"], "correct_index": 0, "explanation": "A right angle is a square corner."},
        {"question": "A letter and a number naming a square on a map is a grid ___.", "options": ["reference", "route", "angle"], "correct_index": 0, "explanation": "This is a grid reference."},
        {"question": "The direction clock hands move is ___.", "options": ["clockwise", "north", "opposite"], "correct_index": 0, "explanation": "Clockwise follows the clock hands."},
        {"question": "A tool that shows north, south, east and west is a ___.", "options": ["compass", "ruler", "scale"], "correct_index": 0, "explanation": "A compass shows directions."},
    ],
    planner_fields=[
        {"key": "landmarks", "label": "Landmarks", "hint": "List six landmarks with their grid references."},
        {"key": "route", "label": "My route", "hint": "Write the directions and number of squares."},
        {"key": "angles", "label": "Angles at home", "hint": "List three angles you will compare."},
    ],
    steps=[
        {"title": "Step 1: Accept the quest", "detail": "Read your mission and accept the quest.", "duration_minutes": 5},
        {"title": "Step 2: Watch and warm up", "detail": "Watch an ABC Mini Lessons Maths episode on maps or angles, then do the treasure walk.", "duration_minutes": 15},
        {"title": "Step 3: Learn the skills", "detail": "Five short lessons: compass, grid references, routes, angles and turns.", "duration_minutes": 15},
        {"title": "Step 4: Practise", "detail": "Flip the key-term cards, sort angles, answer word challenges and do the practice questions.", "duration_minutes": 10},
        {"title": "Step 5: Plan and draw", "detail": "Fill in your planner, then complete the independent task on paper.", "duration_minutes": 20},
        {"title": "Step 6: Clear the Quest check", "detail": "Answer the 10-question Quest check. You need 9 out of 10 to pass.", "duration_minutes": 5},
        {"title": "Step 7: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
    ],
    resources=[
        {"type": "video", "title": "ABC Mini Lessons: Maths (series page; choose a maps or angles episode for Years 3-4)", "url": MINI_LESSONS, "prompt": "Pick an episode on position, maps or angles. Pause and try each example first."},
        {"type": "worksheet", "title": "Twinkl Australia: grid references Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=grid+references+year+3", "prompt": "Choose a printable worksheet. Log in to your Twinkl account to download."},
        {"type": "worksheet", "title": "Twinkl Australia: angles right angle Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=angles+right+angle+year+3", "prompt": "Choose a printable worksheet."},
    ],
    quiz=[
        {"question": "What is the opposite of north?", "type": "multiple_choice", "options": ["east", "south", "west", "north-east"], "correct_index": 1, "explanation": "The opposite of north is south."},
        {"question": "Facing north, you make a quarter turn clockwise. Which way do you face?", "type": "multiple_choice", "options": ["east", "south", "west", "north"], "correct_index": 0, "explanation": "A quarter turn clockwise from north faces east."},
        {"question": "Facing east, you make a half turn. Which way do you face?", "type": "multiple_choice", "options": ["north", "south", "west", "east"], "correct_index": 2, "explanation": "A half turn faces the opposite direction, which is west."},
        {"question": "The library is in column D, row 3. What is its grid reference?", "type": "multiple_choice", "options": ["3D", "D3", "DD", "33"], "correct_index": 1, "explanation": "Write the column letter first, then the row number: D3."},
        {"question": "North-east is between which two directions?", "type": "multiple_choice", "options": ["north and west", "north and east", "south and east", "south and west"], "correct_index": 1, "explanation": "North-east is halfway between north and east."},
        {"question": "A right angle is the same as a ___ turn.", "type": "multiple_choice", "options": ["quarter", "half", "full", "three-quarter"], "correct_index": 0, "explanation": "A right angle is a quarter turn."},
        {"question": "The hands of a clock at 3:00 make ___.", "type": "multiple_choice", "options": ["less than a right angle", "a right angle", "more than a right angle", "a straight line"], "correct_index": 1, "explanation": "At 3:00 the hands make a right angle."},
        {"question": "The hands of a clock at 2:00 make ___.", "type": "multiple_choice", "options": ["less than a right angle", "a right angle", "more than a right angle", "a straight line"], "correct_index": 0, "explanation": "At 2:00 the angle is smaller than a right angle."},
        {"question": "The hands of a clock at 4:00 make ___.", "type": "multiple_choice", "options": ["less than a right angle", "a right angle", "more than a right angle", "a straight line"], "correct_index": 2, "explanation": "At 4:00 the angle is larger than a right angle."},
        {"question": "How many right angles are in a half turn?", "type": "multiple_choice", "options": ["1", "2", "3", "4"], "correct_index": 1, "explanation": "A half turn is 2 right angles."},
    ],
    evidence_instructions="Upload a photo of your treasure map with grid references, your written route with turns, and sketches of three angles labelled less than, equal to or more than a right angle.",
    parent_notes="Seven steps, about 75 minutes. Covers compass directions, grid references (column letter first), routes, comparing angles with a right angle and quarter, half and full turns. Look for: correct order in grid references, clear distances in routes, and angle comparison by fitting a paper corner. Outcomes: MA2-GM-01 (grid maps and directions), MA2-GM-03 (angles) and MAO-WM-01. Video resource is a series page: choose one episode.",
    offline_alternative="Use a printed grid map and a paper corner with a real compass or a floor treasure hunt.",
    extension="Plan a route that has one quarter turn, one half turn and one three-quarter turn and still ends at the treasure.",
    follow_up_challenges=[
        {"title": "Home map", "description": "Draw a grid map of your house with grid references for five rooms.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
        {"title": "Angle hunt", "description": "Find five angles at home and compare them to a right angle with a paper corner.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
    ],
)

S2Y3_MATHS_LESSONS_6 = [LESSON_3D, LESSON_MAPS_ANGLES]
