"""Stage 2 English, Block A (narrative writing), lessons 1 to 4 of the next week.
Fully taught from scratch. Keys use the prefix a3 so the renumbering in lesson_library.py leaves them alone.
Video ids came from search and must be checked on playback."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A3L1 = build(
    "s2-eng-a3-l1-story-structure-plot-arc", "Story Structure and the Plot Arc",
    "Discover the shape every great story follows, then map the plot of a story you know.",
    "Reading and writing: narrative structure",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies the stages of a narrative and explains how they fit together in a text of the parent's choice.",
     "EN2-CWT-01": "Uses the stages of a narrative to organise ideas for writing.",
     "EN2-VOCAB-01": "Learns the terms plot, orientation, complication, climax, resolution and plot arc."},
    "We are learning how stories are built in stages, and how to show those stages as a plot arc.",
    ["I can say what a narrative is.", "I can name the stages: orientation, complication, climax and resolution.", "I can explain what happens in each stage.", "I can draw a plot arc and place events on it.", "I can map the plot of a story I have read."],
    ["narrative", "plot", "orientation", "complication", "climax", "resolution", "plot arc"],
    ["Paper or notebook", "Pencil and coloured pencils", "A story you have read or heard (your parent will help you choose)"],
    "Nothing is assumed. Child can retell a simple story. Story stages and the plot arc are taught from the beginning.",
    "A NARRATIVE is a story that tells about events happening to characters. Stories can be funny, scary, exciting or sad, but nearly all of them are built in the same stages.\n\nThe series of events in a story is called the PLOT. A good plot is not a jumble. It starts somewhere, builds up, reaches a big moment and then settles down.\n\nIn this lesson you will learn the four stages that most narratives use. You will see that the stages make the shape of an arch, called the PLOT ARC. Then you will use the arc to map a story.",
    [
        _step("1", "What is a narrative?",
              "A narrative is a made-up or true story that tells about events in order. The purpose of most narratives is to entertain the reader, and sometimes to teach something too.\n\nEvery narrative has CHARACTERS (who the story is about), a SETTING (where and when it happens) and a PLOT (what happens).\n\nThe plot is not just a list of things that happen. In a good plot, one event leads to the next, and something goes wrong that the character must deal with. Without a problem there is no story. 'Mia went to the shop and came home' is not much of a story. 'Mia went to the shop, lost her money and had to find a way to get her mum's medicine' is.",
              "Story: A boy finds a lost puppy and has to find its owner. Characters: the boy and the puppy. Setting: his street. Plot: finds puppy, searches, finds the owner.",
              "A narrative has characters, setting and a plot that includes a problem.",
              ("What is the plot of a story?", ["The series of events", "Where it happens", "Who it is about"], 0, "The plot is what happens in the story.")),
        _step("2", "Stage one: the orientation",
              "The first stage is called the ORIENTATION. It sets the scene. The word 'orient' means to find your direction, so this stage helps the reader find their way into the story.\n\nThe orientation tells us WHO the main characters are, WHERE the story is set and WHEN it happens. It often has a hook, which is an exciting first line that makes the reader want to keep going.\n\nOrientations are usually short. The writer does not tell everything at once. Just enough is given so we understand what is about to happen.\n\nExample: 'On the edge of Lantern Forest, where the trees were so tall they hid the sky, a small fox named Pip was building a boat.' We know the character, the setting and that something unusual is going on.",
              "Orientation clues: Who? Pip the fox. Where? Edge of Lantern Forest. What is odd? Building a boat in a forest.",
              "Orientation: who, where, when, plus a hook.",
              ("What does the orientation tell us?", ["Who, where and when", "How the story ends", "Only the title"], 0, "It sets the scene.")),
        _step("3", "Stage two: the complication",
              "The second stage is the COMPLICATION. This is where the problem begins and the story gets exciting.\n\nA complication is something that goes wrong, gets in the way or creates a challenge for the main character. The character wants something, but there is an obstacle.\n\nThe complication usually grows. First there is a small problem. Then things get harder, and the tension rises. Writers often use several events to build up the problem, with each one a little more serious than the last.\n\nExample: Pip finishes the boat, but the nearest river is far away. Then a storm blows in. Then the boat gets stuck in a thick bush. Each event makes the problem bigger.",
              "Complication events in order: (1) the river is far away; (2) a storm comes; (3) the boat gets stuck. The problem builds each time.",
              "Complication: the problem starts and gets bigger.",
              ("What happens in the complication?", ["A problem begins and grows", "Everything is solved", "The characters are introduced"], 0, "The complication is the problem.")),
        _step("4", "Stage three: the climax",
              "The third stage is the CLIMAX. It is the most exciting moment of the story, the high point, where the problem is at its biggest and something must happen.\n\nAt the climax the main character faces the problem head on. We wonder: will they succeed? Will they be safe? The reader is on the edge of their seat.\n\nThe climax is usually short. It is a moment of action or a big decision, not a long stretch of the story. Writers often use short sentences, strong verbs and dramatic detail to make it feel fast.\n\nExample: The river is rising, the boat is slipping, and Pip has one chance to jump. Pip leaps. That is the climax.",
              "Clue: the climax is the moment where you stop and think 'what is going to happen?' It is the peak of the tension.",
              "Climax: the biggest, most exciting moment.",
              ("Which stage is the most exciting moment?", ["The climax", "The orientation", "The title"], 0, "The climax is the high point.")),
        _step("5", "Stage four: the resolution",
              "The fourth stage is the RESOLUTION. This is where the problem is solved, or at least settled, and the story winds down.\n\nThe resolution shows what happened after the climax. It answers the reader's questions. Did the character succeed? How did they change? What happens next?\n\nA resolution does not always have a happy ending. Some stories end sadly or leave you thinking. But every resolution makes the reader feel the story has finished.\n\nOften the resolution also shows a message, called a theme, such as 'be brave' or 'friends help each other'.\n\nExample: Pip lands safely, floats down the river and meets other foxes with boats. Pip learns that asking for help is not weak.",
              "Resolution check: Is the problem solved? Do we know how the character feels? Has the story finished?",
              "Resolution: the problem is settled and the story winds down.",
              ("What does the resolution do?", ["Settles the problem", "Starts the problem", "Introduces new characters"], 0, "It ends the story.")),
        _step("6", "The plot arc",
              "We can draw the four stages as a shape called the PLOT ARC. It looks like a hill or a mountain.\n\nOn the left, the line starts low and flat. This is the orientation. Then it climbs upward as the complication builds. It reaches the very top at the climax. Then it falls down on the right side during the resolution.\n\nThe height of the line shows how much tension, or excitement, there is. Low tension at the start, rising tension in the middle, highest at the climax, and falling tension at the end.\n\nDrawing the arc helps you see the shape of a story at a glance. You can put events on the line like labels on a hill.\n\nTo draw one: 1. Draw a curved hill. 2. Label the four parts. 3. Write a short event under each part.",
              "Arc for Pip: left, low: Pip builds a boat. Climbing: river far, storm, boat stuck. Top: Pip leaps. Down: lands safely and learns a lesson.",
              "Orientation low, complication rising, climax top, resolution falling.",
              ("Where is the climax on the plot arc?", ["At the top", "At the very start", "At the very end"], 0, "The climax is the peak of the arc.")),
        _step("7", "Map a story you know",
              "Now use the arc on a real story. With your parent, choose a story you have read or heard, such as a picture book, a chapter from a novel or a short film.\n\nFollow these steps.\n1. Draw a plot arc and label the four stages.\n2. Write the orientation: who, where, when.\n3. List two or three events that build the complication.\n4. Write what happens at the climax.\n5. Write how the problem is resolved.\n6. Write one sentence to sum up the story.\n\nKeep each answer short. You are mapping, not retelling the whole story.",
              "Mapping The Three Little Pigs: Orientation: three pigs build houses. Complication: the wolf blows down two houses. Climax: the wolf tries the brick house. Resolution: the wolf runs away, the pigs are safe.",
              "Map each stage with one or two short notes.",
              ("When mapping a story, how much should you write?", ["A few short notes for each stage", "The whole story", "Nothing"], 0, "Mapping uses short notes.")),
    ],
    "Model arc for a story: Orientation: Pip the fox builds a boat at the edge of Lantern Forest. Complication: the river is far, a storm comes, the boat gets stuck. Climax: the river rises and Pip leaps. Resolution: Pip lands safely, meets other foxes and learns to ask for help. One-sentence summary: A fox learns that asking for help is brave.",
    "1) Draw a plot arc and label the four stages. 2) Choose a story with your parent and write the orientation. 3) List two events that build the complication. 4) Write what happens at the climax. 5) Write how it is resolved. 6) Sum up the story in one sentence.",
    "Draw and label a plot arc for a story you have read, with one or two short notes under each stage. Upload a photo of your arc.",
    CHECK,
    "Are all four stages labelled? Does the orientation say who, where and when? Do I have at least two events in the complication? Is the climax the most exciting moment? Does the resolution say how the problem was settled? Do I have a one-sentence summary?",
    [
        _q("What is a narrative?", ["A story", "A list", "A map"], 0, "A narrative is a story."),
        _q("Which stage sets the scene?", ["Orientation", "Climax", "Resolution"], 0, "The orientation tells who, where and when."),
        _q("Where does the problem begin?", ["The complication", "The resolution", "The title"], 0, "The complication is the problem."),
        _q("Which stage is the highest point of excitement?", ["Climax", "Orientation", "Resolution"], 0, "The climax is the peak."),
        _q("What happens in the resolution?", ["The problem is settled", "The characters are introduced", "A new problem starts"], 0, "The resolution ends the problem."),
        _q("What shape does the plot arc look like?", ["A hill", "A straight line", "A circle"], 0, "It rises and falls like a hill."),
        _q("Which comes first in a narrative?", ["Orientation", "Climax", "Resolution"], 0, "The orientation starts the story."),
        _q("Complication events usually get...", ["more serious", "less serious", "deleted"], 0, "Tension rises through the complication."),
    ],
    "Upload a photo of your labelled plot arc.",
    "Choose a second story and map it on a new arc. Compare the two arcs. How are they alike and how are they different?",
    [("narrative", "A story that tells about events happening to characters."), ("plot", "The series of events in a story."), ("orientation", "The first stage, which tells who, where and when."),
     ("complication", "The stage where the problem begins and grows."), ("climax", "The most exciting moment of the story."), ("resolution", "The stage where the problem is settled and the story ends."), ("plot arc", "A hill-shaped diagram showing the stages of a story.")],
    [
        _video("Plot Structure Song: Beginning, Middle and End", "bXG_2wxFPC0",
               "Watch and listen to the song about how a story starts, builds and ends. Notice where the problem grows and where it is solved.",
               "Say what happens in the beginning, middle and end of one story you know.",
               ("What happens in the middle of a story, according to the song?", ["The problem grows", "The story is over", "Nothing"], 0, "The middle is where the problem grows.")),
        _video("Writing a Story: Beginning, Middle, End", "cYqmNO6gr2Y",
               "Watch how a story is built from an idea, a setting and characters, then something happens in the middle and the story finishes with an ending. Notice how the three parts fit together like a jigsaw.",
               "Think of a beginning, middle and end for your own story idea.",
               ("What must happen after the beginning?", ["Something happens in the middle", "Nothing", "The title changes"], 0, "A middle with an event comes next.")),
    ],
    _sort("Stage sorter", "Which stage does each event belong to? Tap a stage, then Check.",
          ["Orientation", "Complication", "Climax", "Resolution"],
          [("Pip lives at the edge of Lantern Forest.", 0), ("A storm blows in.", 1), ("The boat gets stuck in a bush.", 1), ("Pip leaps just in time.", 2), ("Pip lands safely and learns to ask for help.", 3), ("On a sunny morning in a small village, a girl named Jo woke up.", 0)]),
    [
        _wc("The stage that sets the scene is the ___.", ["orientation", "climax", "resolution"], 0, "The orientation sets the scene."),
        _wc("The most exciting moment is the ___.", ["climax", "title", "orientation"], 0, "The climax is the peak."),
        _wc("The series of events in a story is the ___.", ["plot", "setting", "theme"], 0, "Plot means the events."),
        _wc("The problem begins in the ___.", ["complication", "orientation", "resolution"], 0, "The complication is the problem."),
        _wc("Which is spelt correctly?", ["resolution", "resalution", "resolushun"], 0, "Resolution ends -tion."),
    ],
    [
        {"key": "arc", "label": "My plot arc", "hint": "A drawing with the four stages labelled."},
        {"key": "orientation", "label": "Orientation", "hint": "Who, where and when."},
        {"key": "events", "label": "Complication and climax", "hint": "Two or more events, then the biggest moment."},
        {"key": "resolution", "label": "Resolution and summary", "hint": "How it ended, plus one sentence about the whole story."},
    ],
    ["Retelling the whole story instead of mapping it in short notes.", "Putting the climax at the end of the story.", "Writing a story with no problem.", "Mixing up the complication and the climax.", "Forgetting the orientation."],
    [{"title": "Arc a Film", "description": "Watch a short film or animation and map its plot arc.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that all four stages are labelled in the right order on a hill-shaped arc, the orientation gives who, where and when, the complication has at least two events that build, the climax is the most exciting moment, and the resolution settles the problem. Sorter: Orientation: Pip lives at the edge of Lantern Forest; On a sunny morning in a small village, a girl named Jo woke up. Complication: A storm blows in; The boat gets stuck in a bush. Climax: Pip leaps just in time. Resolution: Pip lands safely and learns to ask for help.",
)

A3L2 = build(
    "s2-eng-a3-l2-planning-a-story", "Planning a Story",
    "Make a story map so your idea is ready to write.",
    "Writing: planning a narrative",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Generates and organises ideas for a narrative using a story map before drafting.",
     "EN2-VOCAB-01": "Learns the terms brainstorm, story map, character trait, setting and solution.",
     "EN2-RECOM-01": "Uses understanding of narrative stages to plan a coherent text."},
    "We are learning how to plan a story using a story map, so we know where it is going before we write.",
    ["I can brainstorm ideas for a story.", "I can plan a character with traits.", "I can plan a setting with time, place and mood.", "I can plan a problem and a solution.", "I can complete a story map for the four stages."],
    ["brainstorm", "story map", "character trait", "setting", "mood", "problem", "solution"],
    ["Paper or notebook", "Pencil", "Your plot arc notes from the last lesson"],
    "Child knows the four stages of a narrative: orientation, complication, climax and resolution. Planning tools are taught from the beginning.",
    "Good writers plan before they write. A plan does not need to be long. It is a short set of notes that tells you who is in the story, where it happens, what goes wrong and how it ends.\n\nPlanning saves time. If you start writing with no plan, you can get stuck in the middle or forget your ending. With a plan, you always know what comes next.\n\nIn this lesson you will brainstorm ideas, choose the best ones and fill in a STORY MAP. A story map is a simple chart with a box for each part of the story.",
    [
        _step("1", "Why plan?",
              "Imagine building a Lego model without looking at the picture. You might get halfway and find you are missing a piece. Writing without a plan is the same.\n\nA plan helps you in three ways.\n1. You do not get stuck, because you already know what happens next.\n2. Your story has all four stages, with a clear problem and ending.\n3. You can spend your writing time on good words and sentences, not on working out the plot.\n\nA plan is just notes. Use words and short phrases, not full sentences. You can change your plan while you write, but it is a map to start with.",
              "Plan note: Problem: fox boat stuck. Solution: asks other foxes for help. That is enough to remind you of the main idea.",
              "A plan is short notes that guide your writing.",
              ("What is a plan?", ["Short notes to guide your writing", "The finished story", "A list of spelling words"], 0, "A plan is brief notes.")),
        _step("2", "Brainstorm ideas",
              "To BRAINSTORM means to write down lots of ideas quickly, without deciding which are good yet. Do not cross anything out. The more ideas, the better.\n\nTry a 'what if' list. What if a robot learned to paint? What if a dragon was afraid of fire? What if a girl found a door in a tree?\n\nOr try lists. List three characters, three places and three problems. Then mix and match.\n\nAfter brainstorming, CIRCLE the idea you like best. Choose one that you can finish in a short story. A giant idea with ten characters is hard to write, but a small idea told well is great.",
              "What if list: What if the moon fell into a pond? What if my dog could talk for one day? Circle: the dog who talks for one day.",
              "Brainstorm many ideas, then circle one.",
              ("When brainstorming, should you cross out ideas?", ["No, write them all down", "Yes, right away", "Only the long ones"], 0, "Brainstorming collects every idea first.")),
        _step("3", "Plan your character",
              "Every story needs a main character. Plan three things about yours.\n\n1. NAME and what they are (child, animal, robot, dragon).\n2. What they LOOK like (a few details).\n3. TRAITS, which are words that describe how they act and feel, such as brave, shy, curious, grumpy, kind or clever.\n\nTraits matter because they decide how your character handles the problem. A brave character may charge in. A shy character may hide first.\n\nGive your character a WANT, something they are trying to get. Pip the fox wants to sail down the river. The want creates the story, because the problem stops them getting it.",
              "Character plan: Pip, a small red fox with a floppy ear. Traits: curious, stubborn. Want: to sail down the river.",
              "Character: name, look, traits and a want.",
              ("What is a character trait?", ["A word describing how they act or feel", "Their address", "Their age"], 0, "Traits describe personality.")),
        _step("4", "Plan your setting",
              "The SETTING is where and when the story takes place. Plan three things.\n\nPLACE: a forest, a spaceship, a beach, a school.\nTIME: morning, midnight, summer, long ago, the future.\nMOOD: the feeling you want the reader to have, such as spooky, cheerful, tense or peaceful.\n\nThe setting can help make the problem. A storm, a desert or a dark cave can all create trouble.\n\nThink about your five senses. What can your character see, hear, smell, feel and taste there? Write down two or three details to use later. These details make your writing come alive.",
              "Setting plan: Place: Lantern Forest. Time: late afternoon. Mood: mysterious. Senses: damp moss smell, rustling leaves, dim light.",
              "Setting: place, time, mood and sense details.",
              ("Which is a mood?", ["mysterious", "forest", "midnight"], 0, "A mood is a feeling.")),
        _step("5", "Plan the problem and solution",
              "Now plan what goes wrong. The PROBLEM should fit your character's want. It can be big or small, as long as it matters in your story.\n\nThen think about the SOLUTION. How will the character solve it? The best solutions use the character's traits and show that they have learned or changed. If the solution just happens by luck, the reader feels cheated.\n\nPlan the problem to get worse before it gets better. Think of two or three events that make things harder. Then plan the big moment, the climax, where the character faces it.\n\nExample: Want: to sail the river. Problem: boat stuck. Gets worse: storm, river rising. Solution: Pip asks other foxes for help, which is hard for a stubborn character.",
              "Problem and solution link: stubborn Pip must do the thing he hates, ask for help. That is satisfying because it matches his trait.",
              "Problem fits the want. Solution uses the character's traits.",
              ("What makes a solution satisfying?", ["It uses the character's traits and effort", "It happens by luck", "Someone else does everything"], 0, "Good solutions come from the character.")),
        _step("6", "Fill in a story map",
              "A STORY MAP puts it all on one page. Draw four boxes, one for each stage.\n\nBox 1: Orientation. Character, setting and a hook.\nBox 2: Complication. Two or three events that build the problem.\nBox 3: Climax. The biggest moment.\nBox 4: Resolution. How it ends and what the character learned.\n\nWrite short notes only. Under each box, add one idea for a strong verb or a detail you want to use.\n\nCheck the map. Does the problem fit the character's want? Does it get worse before it gets solved? Is the ending clear? If yes, you are ready to write.",
              "Map: Box 1: Pip, a stubborn fox, builds a boat in Lantern Forest. Box 2: river far, storm, boat stuck. Box 3: river rises, Pip must ask for help. Box 4: foxes help, Pip learns it is brave to ask.",
              "Four boxes, short notes, check it hangs together.",
              ("How many boxes does the story map have?", ["Four", "One", "Ten"], 0, "One box for each stage.")),
        _step("7", "Check and improve your plan",
              "Good writers check their plan before they start. Ask these questions.\n\n1. Is there a clear problem that matters to the character?\n2. Does the problem get worse before it is solved?\n3. Is the climax the most exciting moment?\n4. Does the ending solve the problem in a believable way?\n5. Is the story small enough to finish?\n\nIf the story is too big, shrink it. Take out characters or events. Keep one problem, one main character and one main setting.\n\nShow your plan to someone and ask what they think will happen. If they can tell the story back to you, your plan is clear.",
              "Too big: five characters travel across three countries. Better: one girl and her dog search the park for a lost ball.",
              "Check, shrink if needed, and test it on a listener.",
              ("What should you do if your story is too big?", ["Shrink it to one problem and one main character", "Add more characters", "Write faster"], 0, "Smaller stories are easier to finish well.")),
    ],
    "Model plan. Brainstorm: robot paints, talking dog, door in a tree. Chosen: a door in a tree. Character: Zara, curious and brave, wants to find out who lives inside. Setting: her grandmother's garden, summer, mysterious. Orientation: Zara finds a tiny door in the old gum tree. Complication: the door is locked; she finds a key; the tree starts to shake. Climax: Zara steps inside and the door closes. Resolution: she meets a family of possums, helps them and is shown the way home.",
    "1) Brainstorm five story ideas with a what-if list and circle your favourite. 2) Plan your main character with name, look, two traits and a want. 3) Plan your setting with place, time, mood and two sense details. 4) Plan the problem, how it gets worse, and the solution. 5) Fill in a four-box story map. 6) Check your plan with the five questions.",
    "Complete a story map for a new story of your own. Do not write the story yet. Upload a photo of your plan.",
    CHECK,
    "Do I have a character with a want and two traits? Is the setting clear with place, time and mood? Is there a problem that gets worse? Is there a solution that uses the character's traits? Are all four boxes filled in with short notes?",
    [
        _q("What does brainstorm mean?", ["Write many ideas quickly", "Write the final story", "Check spelling"], 0, "Brainstorming collects ideas."),
        _q("Which word describes a character's personality?", ["trait", "setting", "title"], 0, "Traits describe how a character acts."),
        _q("The mood of a setting is...", ["the feeling it creates", "its size", "its name"], 0, "Mood is the feeling."),
        _q("What does a character's want create?", ["The story's problem", "The title", "The setting"], 0, "The want leads to the problem."),
        _q("A good solution should...", ["come from the character's effort", "happen by luck", "be done by someone else"], 0, "Characters should solve their own problems."),
        _q("How many stages go in the story map?", ["Four", "Two", "Eight"], 0, "One box per stage."),
        _q("Should a plan be full sentences?", ["No, short notes", "Yes, always", "Only the first box"], 0, "Plans are brief."),
        _q("If your plan is too big, you should...", ["shrink it", "add more", "give up"], 0, "Smaller stories are easier to write well."),
    ],
    "Upload a photo of your story map.",
    "Swap plans with someone and read each other's story map. Tell them what you think will happen, and ask if you got it right.",
    [("brainstorm", "To write down lots of ideas quickly."), ("story map", "A chart with a box for each part of a story."), ("character trait", "A word that describes how a character acts or feels."),
     ("setting", "Where and when a story takes place."), ("mood", "The feeling a setting or story creates."), ("problem", "What goes wrong for the main character."), ("solution", "How the problem is solved.")],
    [
        _video("How to Write an Imaginative Narrative: Planning with a Story Map", "HAVW3b7E0TI",
               "Watch how a story map is used to plan the character, the setting and the important events, including the problem and the solution. Notice how short the notes are.",
               "Start your own story map with one character and one setting.",
               ("Why is it helpful to plan before writing?", ["It helps you decide the most important parts", "It makes the story longer", "It is not helpful"], 0, "Planning helps you choose the key parts.")),
        _video("Story Elements Song", "dNzusPXfq24",
               "Listen to the song about character, setting, plot, problem and solution. Notice how each part is named.",
               "Name the character, setting, problem and solution of a story you know.",
               ("Which is NOT a story element in the song?", ["The price", "Setting", "Problem"], 0, "Price is not a story element.")),
    ],
    _sort("Plan part sorter", "Which part of the plan does each note belong to? Tap a part, then Check.",
          ["Character", "Setting", "Problem or solution"],
          [("curious and stubborn", 0), ("a small red fox", 0), ("Lantern Forest at dusk", 1), ("a mysterious mood", 1), ("the boat gets stuck", 2), ("Pip asks for help", 2)]),
    [
        _wc("To write many ideas quickly is to ___.", ["brainstorm", "edit", "proofread"], 0, "Brainstorm means to collect ideas."),
        _wc("A word describing how a character acts is a ___.", ["trait", "verb", "title"], 0, "Traits describe personality."),
        _wc("The feeling of a setting is its ___.", ["mood", "price", "height"], 0, "Mood is the feeling."),
        _wc("Which is spelt correctly?", ["character", "charachter", "carracter"], 0, "Character has ch and acter."),
        _wc("Which is spelt correctly?", ["solution", "solushion", "solutoin"], 0, "Solution ends -tion."),
    ],
    [
        {"key": "brainstorm", "label": "Brainstorm", "hint": "Five what-if ideas, with your favourite circled."},
        {"key": "character", "label": "Character plan", "hint": "Name, look, two traits and a want."},
        {"key": "setting", "label": "Setting plan", "hint": "Place, time, mood and sense details."},
        {"key": "map", "label": "Story map", "hint": "Four boxes with short notes."},
    ],
    ["Writing the whole story instead of short notes.", "Planning a story with no problem.", "Making the story too big with too many characters.", "Having a solution that happens by luck.", "Skipping the plan and getting stuck while writing."],
    [{"title": "Plan Two Endings", "description": "Plan two different endings for the same story map and choose the better one. Say why.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the plan has a main character with a want and traits, a setting with place, time and mood, a problem that builds, a solution that comes from the character, and all four story map boxes completed with short notes. Sorter: Character: curious and stubborn; a small red fox. Setting: Lantern Forest at dusk; a mysterious mood. Problem or solution: the boat gets stuck; Pip asks for help.",
)

A3L3 = build(
    "s2-eng-a3-l3-nouns-and-noun-groups", "Nouns and Noun Groups",
    "Name things precisely, then build rich noun groups that paint a picture.",
    "Language: nouns and noun groups",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Uses nouns and expanded noun groups to add detail to written sentences.",
     "EN2-VOCAB-01": "Learns the terms noun, common noun, proper noun, collective noun, abstract noun, noun group and determiner.",
     "EN2-RECOM-01": "Identifies nouns and noun groups when reading to understand description."},
    "We are learning to identify different kinds of nouns and to build noun groups that add detail to our writing.",
    ["I can say what a noun is.", "I can tell common and proper nouns apart.", "I can name collective and abstract nouns.", "I can build a noun group with a determiner, adjectives and a noun.", "I can add detail after the noun."],
    ["noun", "common noun", "proper noun", "collective noun", "abstract noun", "noun group", "determiner"],
    ["Paper or notebook", "Pencil", "A page from a story you have read"],
    "Child can read simple sentences and knows what an adjective is in a basic way. Nouns and noun groups are taught from the beginning.",
    "A NOUN is a word that names a person, place, thing or idea. Nouns are the building blocks of sentences. Every sentence has at least one noun or a word that stands in for one.\n\nThere are different kinds of nouns. Some name one particular thing, such as Sydney. Some name any thing of a type, such as city. Some name a group, such as a flock. Some name ideas you cannot touch, such as courage.\n\nWriters also build NOUN GROUPS. A noun group is a noun with extra words that tell us more about it. 'A dog' becomes 'the scruffy brown dog with the wagging tail'. Noun groups are one of the best ways to make your writing detailed and vivid.",
    [
        _step("1", "What is a noun?",
              "A noun names a person, an animal, a place, a thing or an idea.\n\nPerson: teacher, Mum, astronaut.\nAnimal: kangaroo, spider.\nPlace: beach, library, Tasmania.\nThing: pencil, bicycle, cloud.\nIdea: freedom, joy.\n\nA trick for finding nouns: try putting 'the' in front. 'The pencil' works, so pencil is a noun. 'The quickly' does not, so quickly is not.\n\nTo find nouns in a sentence, ask: who or what is this sentence about? 'The cat chased the mouse around the kitchen.' The nouns are cat, mouse and kitchen.",
              "Sentence: Mia packed her bag and walked to school. Nouns: Mia, bag, school.",
              "Nouns name people, animals, places, things and ideas.",
              ("Which word is a noun?", ["river", "quickly", "jump"], 0, "A river is a thing.")),
        _step("2", "Common and proper nouns",
              "A COMMON NOUN names any person, place or thing of a general type. It does not start with a capital letter unless it begins a sentence. Examples: girl, city, river, school, dog.\n\nA PROPER NOUN names one particular person, place or thing. It always starts with a capital letter. Examples: Sophie, Melbourne, the Murray River, Bondi Primary School, Rex.\n\nThe same thing can have both. 'Dog' is common, and 'Rex' is the proper noun for one dog. 'River' is common, and 'Murray River' is proper.\n\nProper nouns include names of people and pets, places, days, months, holidays, languages and titles of books and films.",
              "Common to proper: city to Brisbane, day to Tuesday, girl to Ava, country to Australia.",
              "Proper nouns are specific names and have capital letters.",
              ("Which is a proper noun?", ["Canberra", "city", "capital"], 0, "Canberra names one particular place.")),
        _step("3", "Collective nouns",
              "A COLLECTIVE NOUN names a group of people, animals or things as one. We use it when we think of the group as a single unit.\n\nA team of players. A class of students. A flock of birds. A herd of cattle. A pack of wolves. A bunch of grapes. A pod of dolphins. A swarm of bees. A fleet of ships.\n\nCollective nouns make writing more precise and more interesting. 'A swarm of bees' creates a better picture than 'lots of bees'.\n\nTo remember them, try matching each to its group in a list and practise saying them aloud.",
              "Instead of 'many fish' write 'a school of fish'. Instead of 'many sheep' write 'a flock of sheep'.",
              "Collective nouns name a group as one.",
              ("Which is a collective noun?", ["flock", "bird", "fly"], 0, "A flock is a group of birds.")),
        _step("4", "Abstract nouns",
              "An ABSTRACT NOUN names an idea, feeling or quality that you cannot see, touch, hear, smell or taste. A concrete noun, like table or apple, is something you can sense.\n\nAbstract nouns: happiness, courage, friendship, kindness, hunger, danger, honesty, freedom, fear.\n\nA test: can I touch it? Can I take a photo of it? If not, it is likely abstract.\n\nMany abstract nouns come from other words. Brave becomes bravery. Kind becomes kindness. Happy becomes happiness. Strong becomes strength.\n\nWriters use abstract nouns to talk about feelings and themes. 'Her courage saved them.'",
              "Concrete: apple, tree. Abstract: hunger, fear. The test: you cannot touch fear.",
              "Abstract nouns name ideas, feelings and qualities.",
              ("Which is an abstract noun?", ["courage", "table", "puppy"], 0, "Courage is a quality, not a thing you can touch.")),
        _step("5", "What is a noun group?",
              "A NOUN GROUP is a noun plus the words that give more information about it. The noun is the HEAD, which is the main word. The other words add detail.\n\nSimple noun: dog.\nNoun group: the scruffy brown dog.\n\nIn this noun group, 'dog' is the head. 'The' is a determiner. 'Scruffy' and 'brown' are adjectives that describe it.\n\nA DETERMINER is a small word that comes before the noun and tells us which one or how many. Examples: a, an, the, this, that, my, your, some, three, many.\n\nPattern: determiner + adjectives + noun. 'My' + 'old, creaky' + 'wooden gate'. Notice that the adjectives often go in a natural order, such as opinion, size, age, colour, then material: 'a lovely, big, old, red brick house'.",
              "Build up: a dog. A brown dog. The scruffy brown dog. The scruffy brown dog with floppy ears.",
              "Noun group: determiner + adjectives + noun.",
              ("In 'the tall oak tree', which word is the head?", ["tree", "tall", "the"], 0, "Tree is the main noun.")),
        _step("6", "Add detail after the noun",
              "You can also add information AFTER the noun. This is often a group of words starting with a word like with, in, on, from, of or that.\n\nThe dog with the wagging tail.\nThe girl in the red coat.\nThe house on the hill.\nThe book that I borrowed.\nThe boy who lives next door.\n\nThese add information about which one we mean, so the reader can picture it exactly.\n\nThe full noun group can have words before and after the noun: 'the scruffy brown dog with the wagging tail'.\n\nBe careful not to pile on too much. Two or three details are usually enough. Choose the details that matter most to your story.",
              "Simple: The fox ran. Detail: The small red fox with the floppy ear ran.",
              "Add words before the noun and after it for detail.",
              ("Which adds detail AFTER the noun?", ["with the wagging tail", "the scruffy", "very quickly"], 0, "With the wagging tail follows the noun.")),
        _step("7", "Use noun groups in your writing",
              "Now use noun groups to improve your own sentences. Follow these steps.\n\n1. Choose a plain sentence, such as 'The boy found a box.'\n2. Find the nouns: boy and box.\n3. Expand each into a noun group. 'The nervous young boy found a dusty wooden box with a rusty lock.'\n4. Read it aloud. Does it sound natural? Does it paint a clear picture?\n5. Check that the detail is useful. Cut anything that does not help.\n\nVary your noun groups. Not every noun needs to be long. A short noun can have a big effect after several long ones.\n\nWhen you read, look for noun groups the author uses. Notice how they help you picture the scene.",
              "Plain: The woman opened the door. Better: The tired old woman opened the creaky front door with a trembling hand.",
              "Expand nouns into noun groups, then check it sounds natural.",
              ("Why use noun groups?", ["To add clear detail", "To make sentences shorter", "To avoid nouns"], 0, "They add detail and help the reader picture things.")),
    ],
    "Model answers. Nouns in 'The teacher read a book about dolphins in the library': teacher, book, dolphins, library. Common/proper: Sydney is proper; city is common. Collective: a pod of dolphins. Abstract: kindness. Noun group: the shy young girl with a red backpack (determiner the, adjectives shy young, head noun girl, detail with a red backpack). Improved sentence: The tiny silver fish darted between the rocks.",
    "1) Find the nouns in five sentences. 2) Sort ten nouns into common and proper and add capital letters. 3) Match five collective nouns to their groups. 4) Write three abstract nouns and use each in a sentence. 5) Build a noun group for each of five plain nouns. 6) Rewrite three plain sentences using noun groups.",
    "Rewrite five plain sentences using noun groups with words before and after the noun. Underline the head noun in each. Upload a photo of your writing.",
    CHECK,
    "Did I use a determiner in each noun group? Did I add at least one adjective before the noun? Did I add detail after the noun in at least two? Are proper nouns capitalised? Do my sentences sound natural? Did I underline the head noun?",
    [
        _q("What is a noun?", ["A word that names a person, place, thing or idea", "An action word", "A describing word"], 0, "Nouns are naming words."),
        _q("Which is a proper noun?", ["Tasmania", "island", "state"], 0, "Tasmania names one particular place."),
        _q("Which is a collective noun?", ["pod", "whale", "swim"], 0, "A pod is a group of whales or dolphins."),
        _q("Which is an abstract noun?", ["friendship", "bench", "pencil"], 0, "Friendship is an idea."),
        _q("Which word is a determiner?", ["the", "happy", "jump"], 0, "The tells us which noun."),
        _q("In 'the old wooden gate', the head noun is...", ["gate", "old", "wooden"], 0, "The head is the main noun."),
        _q("Which is a noun group?", ["the shy young girl with a red backpack", "ran quickly", "very tall"], 0, "It has a head noun with extra detail."),
        _q("Proper nouns always begin with...", ["a capital letter", "a comma", "a number"], 0, "Proper nouns are capitalised."),
    ],
    "Upload a photo of your noun group sentences.",
    "Find a paragraph in a book of your choice and copy three noun groups the author used. Say what each one helps you picture.",
    [("noun", "A word that names a person, animal, place, thing or idea."), ("common noun", "A general name for a type of person, place or thing."), ("proper noun", "The specific name of a person, place or thing, written with a capital letter."),
     ("collective noun", "A noun that names a group, such as a flock."), ("abstract noun", "A noun for an idea or feeling you cannot touch."), ("noun group", "A noun with extra words that give more detail."), ("determiner", "A small word such as the, a or my that comes before a noun.")],
    [
        _video("Common and Proper Nouns for Kids", "gQsZr8yrsno",
               "Watch how common nouns name a type of person, place or thing, and proper nouns name a specific one with a capital letter. Notice the examples like dog and Fido.",
               "Think of a common noun and a proper noun for it.",
               ("What do proper nouns always begin with?", ["A capital letter", "A comma", "A small letter"], 0, "Proper nouns always have a capital letter.")),
    ],
    _sort("Noun sorter", "What kind of noun is each word? Tap a kind, then Check.",
          ["Common", "Proper", "Collective", "Abstract"],
          [("river", 0), ("teacher", 0), ("Melbourne", 1), ("Monday", 1), ("flock", 2), ("team", 2), ("courage", 3), ("happiness", 3)]),
    [
        _wc("A word that names a person, place or thing is a ___.", ["noun", "verb", "adverb"], 0, "Nouns are naming words."),
        _wc("A group of dolphins is called a ___ of dolphins.", ["pod", "herd", "bunch"], 0, "A pod is a group of dolphins."),
        _wc("The word 'the' is a ___.", ["determiner", "noun", "verb"], 0, "It comes before a noun."),
        _wc("Which is spelt correctly?", ["collective", "colective", "collectif"], 0, "Collective has two l letters."),
        _wc("Which is spelt correctly?", ["adjective", "adjecktive", "adgective"], 0, "Adjective has a j and ective."),
    ],
    [
        {"key": "nouns", "label": "Nouns I found", "hint": "Nouns from five sentences."},
        {"key": "kinds", "label": "Kinds of nouns", "hint": "Common, proper, collective and abstract examples."},
        {"key": "groups", "label": "My noun groups", "hint": "Five noun groups with the head noun underlined."},
        {"key": "sentences", "label": "Improved sentences", "hint": "Three plain sentences rewritten with noun groups."},
    ],
    ["Forgetting capital letters on proper nouns.", "Using too many adjectives so the noun group becomes clumsy.", "Confusing the head noun with an adjective.", "Thinking a collective noun is always plural.", "Leaving out the determiner."],
    [{"title": "Noun Group Hunt", "description": "Find five noun groups in a book you are reading and rewrite each one by changing the adjectives.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that nouns are correctly identified, proper nouns have capital letters, noun groups have a determiner, one or two adjectives and a head noun, some have detail after the noun, and sentences sound natural. Sorter: Common: river, teacher. Proper: Melbourne, Monday. Collective: flock, team. Abstract: courage, happiness.",
)

A3L4 = build(
    "s2-eng-a3-l4-suffixes-ful-less-ness", "Spelling: Suffixes -ful, -less and -ness",
    "Add endings to words and learn the spelling rules that keep them correct.",
    "Spelling: suffixes",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-CWT-01"],
    {"EN2-SPELL-01": "Primary. Applies spelling rules when adding the suffixes -ful, -less and -ness to base words.",
     "EN2-VOCAB-01": "Learns the terms base word, suffix, root and how suffixes change meaning and word class.",
     "EN2-CWT-01": "Uses suffixed words accurately in written sentences."},
    "We are learning how the suffixes -ful, -less and -ness change a word, and how to spell the new words correctly.",
    ["I can say what a base word and a suffix are.", "I can explain what -ful, -less and -ness mean.", "I can spell -ful with one l.", "I can change y to i before adding a suffix.", "I can spell and use words with these suffixes."],
    ["base word", "suffix", "-ful", "-less", "-ness", "noun", "adjective"],
    ["Paper or notebook", "Pencil", "Coloured pencils"],
    "Child can spell common words and knows what a noun and an adjective are in a simple way. Suffix rules are taught from the beginning.",
    "A BASE WORD is a word that can stand on its own, such as care, help or kind. A SUFFIX is a group of letters added to the END of a base word to change its meaning or job.\n\nSuffixes are powerful. One small ending can turn a noun into an adjective or an adjective into a noun. Learn a few suffixes and you can spell and understand hundreds of words.\n\nIn this lesson you will meet three suffixes: -ful, -less and -ness. You will learn what each means, and the spelling rules for adding them.",
    [
        _step("1", "Base words and suffixes",
              "A base word has a meaning on its own. Examples: care, help, kind, hope, joy.\n\nA suffix is added at the end. It changes the meaning and often the type of word.\n\ncare + ful = careful (an adjective)\nhelp + less = helpless (an adjective)\nkind + ness = kindness (a noun)\n\nWhen you meet a long word, look for the base word first, then the suffix. That makes it easier to read, to spell and to work out what it means.\n\nTo spell: say the base word, then say the suffix, then put them together.",
              "Split: thankful = thank + ful. Hopeless = hope + less. Darkness = dark + ness.",
              "Base word plus suffix makes a new word.",
              ("What is a suffix?", ["Letters added to the end of a word", "Letters at the start", "A whole sentence"], 0, "Suffixes come at the end.")),
        _step("2", "The suffix -ful",
              "The suffix -ful means FULL OF. Care + ful means full of care. Joy + ful means full of joy.\n\nAdding -ful usually turns a noun into an adjective, which is a describing word.\n\ncolour + ful = colourful\nhelp + ful = helpful\nuse + ful = useful\nthank + ful = thankful\nhope + ful = hopeful\npain + ful = painful\n\nIMPORTANT: the suffix -ful has only ONE l. It is not spelt full. Remember: a cupful is not very full, so we drop one l.\n\nAustralian spelling keeps the u in colour, so we write colourful.",
              "Check: careful (not carefull), joyful (not joyfull), wonderful (not wonderfull).",
              "-ful means full of, and has one l.",
              ("Which is spelt correctly?", ["helpful", "helpfull", "helpfal"], 0, "The suffix -ful has one l.")),
        _step("3", "The suffix -less",
              "The suffix -less means WITHOUT. Care + less means without care. Hope + less means without hope.\n\nIt also turns a noun into an adjective, and it is the opposite of -ful.\n\ncareful and careless\nhelpful and helpless\nhopeful and hopeless\nuseful and useless\nthankful and thankless\n\nOther words: fearless, endless, harmless, painless, homeless, speechless, breathless.\n\nIn -less there are two s letters. Notice that the base word does not change in most cases, so you just join the two parts.\n\nBe careful: some words ending in -less are not made from a base word you know, such as 'unless' and 'bless'. Focus on the ones that are.",
              "Pairs: fear + less = fearless (without fear). Home + less = homeless (without a home).",
              "-less means without, and has two s letters.",
              ("What does -less mean?", ["Without", "Full of", "Again"], 0, "-less means without.")),
        _step("4", "The suffix -ness",
              "The suffix -ness turns an adjective into a NOUN. It names the state or quality of being something.\n\nkind + ness = kindness (the quality of being kind)\ndark + ness = darkness\nsad + ness = sadness\nill + ness = illness\nsweet + ness = sweetness\n\nWhen the base word already ends in n, keep it and add -ness. This gives two n letters: mean + ness = meanness, clean + ness = cleanness, open + ness = openness.\n\nWords made with -ness are abstract nouns. They name an idea or feeling, such as happiness, weakness or fairness.\n\nRemember: -ness has two s letters at the end.",
              "Adjective to noun: 'The room was dark.' becomes 'The darkness frightened her.' Dark is an adjective, darkness is a noun.",
              "-ness turns an adjective into a noun.",
              ("Which word is a noun?", ["kindness", "kind", "kindly"], 0, "The suffix -ness makes a noun.")),
        _step("5", "The y to i rule",
              "When a base word ends in a CONSONANT followed by y, change the y to i before adding the suffix.\n\nbeauty + ful = beautiful\nmercy + ful = merciful\nplenty + ful = plentiful\nhappy + ness = happiness\nlazy + ness = laziness\nbusy + ness = business\nworry + less = worryless (rare)\n\nIf the y comes after a VOWEL (a, e, i, o, u), keep the y.\njoy + ful = joyful\nplay + ful = playful\nenjoy + ment = enjoyment\n\nThe test: look at the letter before y. If it is a consonant, change y to i. If it is a vowel, leave it.",
              "Beauty: the letter before y is t, a consonant, so beautiful. Joy: the letter before y is o, a vowel, so joyful.",
              "Consonant then y: change y to i. Vowel then y: keep the y.",
              ("Which is spelt correctly?", ["happiness", "happyness", "hapiness"], 0, "Change y to i before -ness.")),
        _step("6", "Silent e and tricky words",
              "With -ful and -less, you keep the silent e on the base word: care + ful = careful, hope + less = hopeless. Do not drop it.\n\nWith -ness there is nothing to drop, so just add it: polite + ness = politeness.\n\nSome words drop the silent e when a suffix starting with a vowel is added, such as -ing or -ed, but -ful, -less and -ness start with consonants, so the e stays.\n\nOther tricky words to practise: wonderful, beautiful, successful, thoughtful, truthful, thoughtless, restless, weakness, fairness, forgiveness.\n\nPractise using Look, Say, Cover, Write, Check. Look carefully at the word and say it aloud. Cover it, write it from memory, then check it letter by letter.",
              "Keep the e: care becomes careful, use becomes useful, hope becomes hopeless.",
              "Keep silent e with -ful, -less and -ness.",
              ("What happens to the silent e in care + ful?", ["It stays", "It is dropped", "It becomes i"], 0, "-ful starts with a consonant, so the e stays.")),
        _step("7", "Use suffixed words in sentences",
              "Now use your words in writing. Follow these steps.\n\n1. Choose a base word, such as help.\n2. Add each suffix that works: helpful, helpless.\n3. Decide what each word means.\n4. Write a sentence for each, and check the meaning is right.\n\nExample: 'The helpful neighbour carried the shopping.' 'The kitten was helpless in the tree.'\n\nSuffixes help your writing too. Use -ful words to describe things positively and -less words to show something is missing. Use -ness words to name feelings: 'She felt a great sadness.'\n\nProofread your sentences. Check one l in -ful, two s letters in -less and -ness, and changed y to i where needed.",
              "Sentences: The beautiful sunset filled the sky. The hopeless puppy was lost. Her kindness made everyone smile.",
              "Choose the right suffix, then proofread the spelling.",
              ("Which word means 'without fear'?", ["fearless", "fearful", "fearness"], 0, "-less means without.")),
    ],
    "Model answers. careful = care + ful (full of care). helpless = help + less (without help). kindness = kind + ness (the quality of being kind). beautiful: beauty has a consonant before y, so change y to i. happiness: happy changes y to i. joyful: joy has a vowel before y, so keep y. Sentences: The careful boy carried the cup. The hopeless dog sat alone. Her kindness helped us.",
    "1) Split ten words into base word and suffix. 2) Add -ful to five nouns. 3) Add -less to five nouns. 4) Add -ness to five adjectives. 5) Sort words that need y changed to i from those that keep y. 6) Write six sentences, using two words from each suffix.",
    "Write eight sentences using words with -ful, -less and -ness, then underline the suffix in each. Upload a photo of your writing.",
    CHECK,
    "Does every -ful word have one l? Does every -less and -ness word have two s letters? Did I change y to i where the letter before y is a consonant? Did I keep the silent e? Do my sentences make sense? Did I underline each suffix?",
    [
        _q("What does -ful mean?", ["Full of", "Without", "Again"], 0, "-ful means full of."),
        _q("What does -less mean?", ["Without", "Full of", "More"], 0, "-less means without."),
        _q("Which is spelt correctly?", ["careful", "carefull", "carful"], 0, "-ful has one l."),
        _q("Which is spelt correctly?", ["happiness", "happyness", "hapiness"], 0, "Change y to i before -ness."),
        _q("Which is spelt correctly?", ["joyful", "joiful", "joyfull"], 0, "Keep y after a vowel."),
        _q("Which word is a noun?", ["sadness", "sad", "sadly"], 0, "-ness makes a noun."),
        _q("Which means 'without hope'?", ["hopeless", "hopeful", "hopeness"], 0, "-less means without."),
        _q("Which is spelt correctly?", ["beautiful", "beautyful", "beutiful"], 0, "Beauty changes y to i."),
    ],
    "Upload a photo of your suffix sentences.",
    "Find five other words ending in -ful, -less or -ness in a book of your choice. Write the base word and the meaning of each.",
    [("base word", "A word that can stand on its own."), ("suffix", "Letters added to the end of a word to change its meaning."), ("-ful", "A suffix meaning full of."),
     ("-less", "A suffix meaning without."), ("-ness", "A suffix that makes a noun showing a state or quality."), ("noun", "A word that names a person, place, thing or idea."), ("adjective", "A word that describes a noun.")],
    [
        _video("Spelling Secrets: What Are Suffixes?", "fgQ7jurdxF4",
               "Watch how suffixes are added to the end of base words to change their meaning, for example -ed changes walk to walked. Notice that every suffix carries its own meaning.",
               "Choose a base word and say what it becomes with -ful, -less and -ness.",
               ("Where does a suffix go?", ["At the end of a word", "At the start", "In the middle"], 0, "A suffix is added to the end of a word.")),
    ],
    _sort("Suffix sorter", "Which suffix goes with each meaning or word? Tap a suffix, then Check.",
          ["-ful", "-less", "-ness"],
          [("full of care", 0), ("full of joy", 0), ("without fear", 1), ("without a home", 1), ("the quality of being kind", 2), ("the state of being dark", 2)]),
    [
        _wc("The suffix meaning full of is ___.", ["-ful", "-less", "-ness"], 0, "-ful means full of."),
        _wc("The suffix meaning without is ___.", ["-less", "-ful", "-ness"], 0, "-less means without."),
        _wc("Which is spelt correctly?", ["kindness", "kindnes", "kindnass"], 0, "-ness has two s letters."),
        _wc("Which is spelt correctly?", ["harmless", "harmles", "harmlass"], 0, "-less has two s letters."),
        _wc("Which is spelt correctly?", ["colourful", "colourfull", "colorfull"], 0, "Australian spelling keeps u, and -ful has one l."),
    ],
    [
        {"key": "split", "label": "Splitting words", "hint": "Ten words split into base word and suffix."},
        {"key": "adding", "label": "Adding suffixes", "hint": "New words with -ful, -less and -ness."},
        {"key": "rule", "label": "The y to i rule", "hint": "Words where you changed y to i, and words where you kept y."},
        {"key": "sentences", "label": "My sentences", "hint": "Eight sentences with the suffix underlined."},
    ],
    ["Spelling -ful as full.", "Forgetting to change y to i, such as happyness.", "Dropping the silent e, such as carful.", "Writing only one s in -less or -ness.", "Mixing up -ful and -less."],
    [{"title": "Suffix Word Web", "description": "Choose five base words and make a word web showing every word you can build with -ful, -less and -ness.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that -ful has one l, -less and -ness have two s letters, y is changed to i after a consonant, the silent e is kept, and sentences use the words with correct meaning. Sorter: -ful: full of care, full of joy. -less: without fear, without a home. -ness: the quality of being kind, the state of being dark.",
)

LESSONS = [A3L1, A3L2, A3L3, A3L4]
