"""Stage 2 English, Week 4 Lesson 1: Inference from Clues (Reading and comprehension).
All written work is typed inside the lesson. Spelling (prefixes un-, re-, dis-, mis-) is attached so the lesson is self-contained.
No video is attached: none has been verified for this topic yet. Add one in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from spelling_s2_w1 import _w, _c

WORDS = ["unhappy", "unlock", "redo", "replay", "disagree", "mistake"]

PASSAGE = (
    "The Mystery of the Muddy Kitchen\n\n"
    "Part 1\n"
    "Nina came downstairs on Sunday morning and stopped in the kitchen doorway. The back door was wide open, and the curtain was flapping in the cold breeze. "
    "There were muddy paw prints across the floor, and a chair lay on its side near the table. Nina's pancake plate, which she had left covered with a tea towel, was clean and empty. "
    "The tea towel was on the floor.\n\n"
    "Part 2\n"
    "Nina followed the paw prints out onto the porch. They led down the steps and across the wet grass to the shed. A small trail of crumbs and a scrap of sticky syrup-covered paper lay along the path. "
    "From inside the shed came a soft, happy purring and the faint sound of licking. Nina's big brother Sam wandered out, rubbing his eyes. 'I left the back door open for Biscuit last night,' he yawned. 'He likes to sleep in the shed.'\n\n"
    "Part 3\n"
    "Nina peeked inside. A round orange cat was curled on an old blanket, his whiskers sticky and his paws caked in mud. He opened one sleepy eye and burped. Nina burst out laughing. "
    "'Biscuit,' she said, 'you cheeky thief. I think you've had my breakfast.' Sam grinned and went to fetch a cloth and a bucket of warm water."
)

LESSON = build(
    "s2-eng-w04-l1-inference-from-clues",
    "Inference from Clues",
    "Authors do not always tell us everything. Learn to be a reading detective: combine clues in the text with what you already know to work out what is really going on.",
    "Reading and comprehension: making inferences",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {
        "EN2-RECOM-01": "Primary. Makes inferences by combining clues from the text with background knowledge, and supports them with evidence.",
        "EN2-VOCAB-01": "Uses words such as infer, inference, clue, evidence and conclusion to talk about reading.",
        "EN2-SPELL-01": "Spells words with the prefixes un-, re-, dis- and mis-, understanding that a prefix changes the meaning but not the spelling of the base word (week 4 spelling focus).",
    },
    "We are learning to make inferences by joining clues from the text with what we already know.",
    ["I can explain what an inference is.", "I can find clues in a text.", "I can use the formula: clue + what I know = inference.", "I can support an inference with evidence.", "I can spell words with the prefixes un-, re-, dis- and mis-."],
    ["infer", "inference", "clue", "evidence", "conclusion", "prefix", "base word", "background knowledge"],
    ["This lesson (everything you need is inside it)"],
    "Child can make and check predictions and ask questions as they read (Week 3 Lesson 1).",
    (
        "Why this matters. Authors often leave things out on purpose. They show you what happens and let you work out the rest. When you do this you are making an inference. It is one of the most important reading skills, because it moves you from just reading the words to really understanding the story.\n\n"
        "What is an inference? An inference is an idea you work out by joining clues in the text with what you already know. The author does not say it straight out. For example: 'Tom put on his raincoat and grabbed an umbrella.' The text does not say it is raining, but you can infer that it is, because people usually wear raincoats and carry umbrellas when it rains.\n\n"
        "The formula. Clue from the text + what I already know = inference. Say it in a full sentence: 'I infer that... because the text says... and I know that...'.\n\n"
        "Inference is not a guess. A wild guess has no support. An inference always has evidence from the text. If you cannot point to a clue, you have not made an inference yet.\n\n"
        "Different from predicting. A prediction is about what will happen next. An inference is about what is happening now or what has already happened, such as how someone feels, why something occurred or what a place is like.\n\n"
        "Spelling focus. A prefix goes at the start of a word and changes its meaning. Un- means not or the opposite (unhappy). Re- means again (redo). Dis- means not or the opposite (disagree). Mis- means wrongly or badly (mistake). The base word keeps its spelling."
    ),
    [
        _step("1", "What is an inference?", "An inference is an idea you work out by joining clues in the text with what you already know. The author does not say it directly.\n\nIt is more than a guess because it is based on evidence.", "'Tom grabbed an umbrella and a raincoat.' I infer it is raining.", "An inference is worked out, not stated.", ("An inference is...", ["An idea worked out from clues", "A wild guess", "A fact stated in the text"], 0, "You work it out from clues and what you know.")),
        _step("2", "Find the clues", "Clues can be actions, words, descriptions, pictures or what characters say. Look for small details that point to something bigger.\n\nUnderline or note the clues as you read.", "Clues in Part 1: the back door is open, muddy paw prints, a clean plate and a tea towel on the floor.", "Clues are small details that point to something bigger.", ("Which is a clue?", ["Muddy paw prints across the floor", "The title page", "The page number"], 0, "The paw prints are a detail in the story.")),
        _step("3", "Add what you know", "Your own knowledge turns a clue into an inference. Ask: what do I already know about this?\n\nPaw prints are made by animals, mud is outside, and a clean plate means the food was eaten.", "I know that animals leave paw prints and cats and dogs like food. So an animal came in and ate the pancakes.", "Clue + what you know = inference.", ("What turns a clue into an inference?", ["What you already know", "The last page", "A friend's opinion"], 0, "Background knowledge connects with the clue.")),
        _step("4", "Say it with evidence", "Use a sentence pattern to show your thinking: I infer that... because the text says... and I know that...\n\nThis shows both the clue and your knowledge.", "I infer that an animal ate the pancakes, because the text says there were paw prints and the plate was empty, and I know animals eat food when they find it.", "Always give the clue and the reason.", ("A strong inference includes...", ["A clue and a reason", "Only an opinion", "No explanation"], 0, "A strong inference gives evidence.")),
        _step("5", "Infer feelings and reasons", "You can infer how a character feels or why something happened, even when the author does not say so.\n\nLook at what they do, say and how they act.", "Sam is rubbing his eyes and yawning, so I infer he just woke up and is still sleepy.", "Actions show feelings and reasons.", ("Sam is yawning and rubbing his eyes. He is probably...", ["Tired", "Angry", "Excited"], 0, "Yawning and rubbing eyes point to tiredness.")),
        _step("6", "Spelling focus: prefixes", "A prefix is added to the start of a word and changes its meaning. Un- and dis- often mean not. Re- means again. Mis- means wrongly.\n\nThe base word does not change: un + lock = unlock, mis + take = mistake.", "un + happy = unhappy, re + do = redo, dis + agree = disagree, mis + take = mistake.", "The prefix is added; the base word stays the same.", ("What does re- mean?", ["Again", "Not", "Wrongly"], 0, "Re- means again, as in replay.")),
        _step("7", "Check your inference", "Keep reading and check your inference. If a new clue shows you were wrong, change your thinking.\n\nGood detectives update their ideas.", "I inferred an animal ate the pancakes. In Part 3 I learn it was Biscuit the cat, so my inference was correct.", "Check and update as you read.", ("If new clues show you were wrong, you should...", ["Change your inference", "Ignore the clues", "Stop reading"], 0, "Good readers update their ideas.")),
    ],
    (
        "Work through Part 1 together. Clues: the back door is wide open, the curtain flaps, there are muddy paw prints, a chair is on its side, the pancake plate is clean and empty, the tea towel is on the floor. "
        "Ask what you know: paw prints belong to animals, mud comes from outside, an empty plate means food was eaten. Inference: 'I infer that an animal came in through the open door and ate the pancakes, because the text says there are muddy paw prints and the plate is empty, and I know animals eat food they find.' "
        "Now read Part 2. New clues: prints lead to the shed, crumbs and syrup paper on the path, purring and licking from the shed, Sam says he left the door open for Biscuit. Update: Biscuit, probably a pet, ate the pancakes. "
        "Part 3 confirms it. Notice that the author never says 'the cat ate the pancakes' until the end. You worked it out from clues. Finally, infer Nina's feelings: she bursts out laughing and calls Biscuit a 'cheeky thief', so she is amused, not angry."
    ),
    (
        "Type your answers in the practice boxes. Part A: type the formula for an inference in your own words. Part B: read this and type an inference with evidence: 'Leo's hands shook as he opened the envelope. He took a deep breath and closed his eyes.' Part C: read this and type an inference: 'The playground was empty. Puddles covered the ground, and a grey sky hung low.' Part D: type the word for each: un + lock, re + play, dis + agree, mis + spell, un + happy, re + build. Your parent can check your answers against the answer key."
    ),
    (
        "Read the story one part at a time and stop at each pause to complete the stage. Everything you write goes in the boxes.\n\n" + PASSAGE + "\n\n"
        "Stage 1 (after Part 1): type three clues you found, and an inference with 'because' and 'I know that'.\n"
        "Stage 2 (after Part 2): type the new clues, then update your inference. What do you now think happened, and who was involved?\n"
        "Stage 3 (after Part 3): was your inference right? Type what you got right and anything you missed.\n"
        "Stage 4 (feelings): type an inference about how Nina feels at the end, with evidence.\n"
        "Stage 5 (your own clues): write a short paragraph of four or five sentences about a person or an animal, without saying the key fact. Give at least three clues so a reader can infer it. Then type the inference a reader should make.\n"
        "Stage 6 (spell): type your six spelling words and say what each prefix means."
    ),
    "Which clue was the most useful to you, and did any clue mislead you?", "Did I give clues and what I know, use 'I infer that... because...', update my inference as I read, write a clue paragraph and spell my six prefix words correctly?",
    [_q("What is an inference?", ["An idea worked out from clues and what you know", "A wild guess", "A word in a title", "A summary"], 0, "An inference is worked out from clues."), _q("Which is the inference formula?", ["Clue + what I know = inference", "Title + page = ending", "Question + answer = fact", "Guess + guess = inference"], 0, "Clue plus background knowledge gives an inference."), _q("What is the difference between a prediction and an inference?", ["A prediction is about what happens next; an inference is about what is happening or has happened", "There is no difference", "A prediction is always wrong", "An inference is about the title"], 0, "Predictions look ahead; inferences work out what is already there."), _q("In the story, which clue shows an animal had been in the kitchen?", ["Muddy paw prints", "A tea towel", "The curtain", "The chair"], 0, "Paw prints belong to animals."), _q("What can you infer from 'Sam was rubbing his eyes and yawning'?", ["He had just woken up", "He was angry", "He was hungry", "He was lost"], 0, "Yawning and rubbing eyes point to tiredness."), _q("Why does Nina call Biscuit a 'cheeky thief'?", ["He ate her breakfast", "He stole her toy", "He broke the door", "He ran away"], 0, "He ate her pancakes."), _q("How does Nina feel at the end?", ["Amused", "Furious", "Frightened", "Bored"], 0, "She bursts out laughing."), _q("What does the prefix dis- usually mean?", ["Not or the opposite", "Again", "Wrongly", "Very"], 0, "Dis- often means not, as in disagree."), _q("Which is spelled correctly?", ["mistake", "mistaik", "misstake", "mistak"], 0, "mis + take = mistake."), _q("Which is spelled correctly?", ["unlock", "unlok", "onlock", "unnlock"], 0, "un + lock = unlock.")],
    "Type your answers in the practice boxes and submit them.", "Extension: pick a page from a book you are reading. Find three clues about a character's feelings and write an inference for each, with evidence.",
    [("infer", "To work something out from clues and what you know"), ("inference", "An idea worked out from clues"), ("clue", "A small detail that points to something bigger"), ("evidence", "Words in the text that support your idea"), ("conclusion", "A decision you reach after thinking about the clues"), ("prefix", "Letters added to the start of a word that change its meaning"), ("base word", "The main word before a prefix or suffix is added"), ("background knowledge", "What you already know about a topic")],
    [],
    _sort("Clue, inference or question?", "Sort each statement about 'The Mystery of the Muddy Kitchen'.", ["Clue", "Inference", "Question"], [("There were muddy paw prints on the floor.", 0), ("The back door was wide open.", 0), ("An animal ate the pancakes.", 1), ("Sam has just woken up.", 1), ("Who left the door open?", 2), ("Why was the plate clean?", 2), ("Nina bursts out laughing.", 0), ("Nina is amused, not angry.", 1)]),
    [_wc("Which is a clue?", ["muddy paw prints", "a good guess", "a title"], 0, "Paw prints are a detail."), _wc("Which is correct?", ["unhappy", "onhappy", "unnhappy"], 0, "un + happy."), _wc("Which is correct?", ["redo", "reedo", "redoo"], 0, "re + do."), _wc("Which is correct?", ["replay", "repley", "reeplay"], 0, "re + play."), _wc("Which is correct?", ["disagree", "disagre", "dissagree"], 0, "dis + agree."), _wc("Which is correct?", ["mistake", "misstake", "mistaik"], 0, "mis + take."), _wc("Which means 'to spell wrongly'?", ["misspell", "respell", "unspell"], 0, "mis- means wrongly."), _wc("Which means 'to play again'?", ["replay", "misplay", "unplay"], 0, "re- means again.")],
    [{"key":"partA","label":"Part A: the formula","hint":"Explain how clues and what you know make an inference."}, {"key":"partB","label":"Part B: Leo","hint":"Leo's hands shook as he opened the envelope. What do you infer? Give evidence."}, {"key":"partC","label":"Part C: the playground","hint":"The playground was empty, with puddles and a grey sky. What do you infer?"}, {"key":"partD","label":"Part D: prefixes","hint":"un+lock, re+play, dis+agree, mis+spell, un+happy, re+build."}, {"key":"stage1","label":"After Part 1","hint":"Three clues and an inference with because and I know that."}, {"key":"stage2","label":"After Part 2","hint":"New clues and an updated inference."}, {"key":"stage3","label":"After Part 3","hint":"What you got right and what you missed."}, {"key":"stage4","label":"Nina's feelings","hint":"An inference about how Nina feels, with evidence."}, {"key":"stage5","label":"My clue paragraph","hint":"Four or five sentences with three clues, then the inference."}, {"key":"spelling","label":"Spelling words","hint":"Type six words and what each prefix means."}],
    ["Making an inference with no clue from the text", "Calling a wild guess an inference", "Giving the inference without the evidence", "Not updating an inference when new clues appear", "Changing the base word when adding a prefix"],
    ["Play 'detective' at home: describe a mystery using only clues and ask someone to infer.", "Look at a photo and list three clues about what happened before it was taken."],
    "Part A: accept any clear explanation: clues from the text plus what you already know give an inference. Part B: accept an inference such as Leo is nervous or anxious, with evidence from shaking hands, a deep breath and closed eyes, and background knowledge that people do this when worried. Part C: accept that it has been raining recently and children cannot play outside, with clue support. Part D: unlock, replay, disagree, misspell, unhappy, rebuild. Main task: look for real clues, a sentence using 'I infer that... because...' with 'I know that', a genuine update after Part 2, and a paragraph that withholds the key fact while giving three usable clues. Quiz answers: an idea worked out from clues and what you know; clue + what I know = inference; a prediction is about what happens next, an inference is about what is happening or has happened; muddy paw prints; he had just woken up; he ate her breakfast; amused; not or the opposite; mistake; unlock.",
)

LESSON["spelling"] = {"focus":"Prefixes un-, re-, dis-, mis-", "teaching":"A prefix goes at the start of a word and changes its meaning. Un- and dis- usually mean not or the opposite (unhappy, disagree). Re- means again (redo, replay). Mis- means wrongly (mistake). The base word keeps its spelling when the prefix is added.", "words":[_w("unhappy","un-hap-py","un + happy"),_w("unlock","un-lock","un + lock"),_w("redo","re-do","re + do"),_w("replay","re-play","re + play"),_w("disagree","dis-a-gree","dis + agree"),_w("mistake","mis-take","mis + take")], "check":[_c("Which means 'to play again'?",["replay","misplay","unplay"],0,"Re- means again."),_c("Which is spelled correctly?",["disagre","disagree","dissagree"],1,"dis + agree.")]}
LESSON["spelling_focus"] = "Prefixes: un-, re-, dis-, mis-"
LESSON["hoard_words"] = list(WORDS)
