"""Stage 2 English, Week 3 Lesson 3: Describing a Setting with the Senses (Writing).
All written work is typed inside the lesson. Spelling (plurals: consonant + y changes to ies) is attached so the lesson is self-contained.
Videos ULPDb7xD0S4 (descriptive writing and the senses) and NCPcEFs6Ytc (plurals with ies) found by search. Re-check in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc, _video
from spelling_s2_w1 import _w, _c

WORDS = ["babies", "stories", "puppies", "ponies", "cities", "families"]

PASSAGE = (
    "The Night Market\n\n"
    "As soon as Kai stepped through the gate, the night market came alive around him. Strings of golden lanterns swung above the stalls, throwing warm light over piles of red apples and shiny purple plums. "
    "Somewhere nearby, a drum thumped, and a seller shouted, 'Fresh bread! Hot bread!' The smell of sizzling onions and sweet, sticky honey drifted through the crowd. "
    "Kai ran his fingers along a soft woollen scarf, then flinched as a cold raindrop landed on his neck. A woman handed him a tiny paper cup. The tea was hot, sweet and a little smoky, and it warmed him all the way down."
)

LESSON = build(
    "s2-eng-w03-l3-describing-setting-senses",
    "Describing a Setting with the Senses",
    "A setting comes alive when the reader can see, hear, smell, feel and taste it. Learn to plan sensory details and turn them into a clear descriptive paragraph.",
    "Writing: descriptive settings",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {
        "EN2-CWT-01": "Primary. Plans and writes a descriptive paragraph about a setting using sensory detail, precise words and a clear order.",
        "EN2-VOCAB-01": "Chooses precise nouns, verbs and adjectives to build a vivid picture for the reader.",
        "EN2-SPELL-01": "Spells plurals of words ending in a consonant and y by changing y to i and adding es (week 3 spelling focus).",
    },
    "We are learning to describe a setting using the five senses and precise words.",
    ["I can name what a character sees, hears, smells, feels and tastes in a setting.", "I can plan sensory details under five headings.", "I can turn my plan into a clear descriptive paragraph.", "I can choose precise nouns, verbs and adjectives.", "I can spell plurals that change y to ies."],
    ["setting", "sense", "sensory", "vivid", "precise", "plural", "describe", "atmosphere"],
    ["This lesson (everything you need is inside it)"],
    "Child can use nouns, verbs and adjectives, and plan a story with a setting (Week 2).",
    (
        "Why this matters. A setting is where and when a story happens. When a writer uses the five senses, the reader feels as if they are standing right there. Sensory details are one of the best tools for making writing vivid, and you will use them in every story you write.\n\n"
        "The five senses. Sight: what can the character see, such as colours, shapes and movement? Sound: what can they hear, near and far? Smell: what can they smell? Touch: what can they feel with their skin, such as textures, temperature and wind? Taste: is there anything to taste, or a taste in the air? Not every setting needs all five, but thinking of all five gives you more ideas.\n\n"
        "Choose precise words. Replace 'nice' or 'good' with exact words: 'warm, golden light', 'sizzling onions', 'a thumping drum'. One strong detail is better than three weak ones. Strong verbs and specific nouns help too: 'lanterns swung' is clearer than 'lanterns were there'.\n\n"
        "Plan before you write. Make a table with five headings: see, hear, smell, touch, taste. Add two or three ideas under each. Then choose the best ones, put them in a sensible order (for example, from far to near, or from the moment the character arrives), and write them as sentences.\n\n"
        "The routine. 1. Picture the setting in your mind. 2. List ideas under the five senses. 3. Choose the best details. 4. Write four to six sentences in a clear order. 5. Check for precise words and for sentences that sound the same. 6. Read aloud.\n\n"
        "A quick demonstration. Plain: 'The market was busy.' Improved: 'Golden lanterns swung above the crowded stalls while a drum thumped somewhere nearby.' The second sentence uses sight and sound and tells the reader much more."
    ),
    [
        _step("1", "What is a setting?", "A setting is where and when a story happens. A good setting description helps the reader picture the place and feel the mood.\n\nThe five senses are a powerful way to build it.", "In The Night Market, the setting is a busy market after dark.", "A setting is the place and time of a story.", ("What is a setting?", ["Where and when a story happens", "The main character", "The ending"], 0, "The setting is where and when.")),
        _step("2", "Use all five senses", "Ask what the character sees, hears, smells, feels and tastes. You may not use all five in the final writing, but thinking of all five gives you more ideas.\n\nSight is not the only sense.", "See: golden lanterns. Hear: a thumping drum. Smell: sizzling onions. Touch: a soft scarf. Taste: hot, sweet tea.", "See, hear, smell, touch, taste.", ("Which sense is 'a thumping drum'?", ["Hearing", "Smell", "Taste"], 0, "A drum is heard.")),
        _step("3", "Choose precise words", "Replace weak words such as nice, good and big with exact ones. Choose specific nouns and strong verbs.\n\nOne strong detail is worth more than three weak ones.", "Plain: 'There were lights.' Precise: 'Golden lanterns swung above the stalls.'", "Be exact, not vague.", ("Which is more precise?", ["There were nice lights.", "Golden lanterns swung above the stalls.", "Lights were there."], 1, "The second sentence uses specific words.")),
        _step("4", "Plan with five headings", "Before writing, make a plan with five headings: see, hear, smell, touch, taste. Add two or three ideas to each. Then choose the best ones.\n\nPlanning stops you running out of ideas.", "See: lanterns, red apples, purple plums. Hear: drum, seller shouting. Smell: onions, honey. Touch: soft scarf, cold rain. Taste: smoky tea.", "Plan first, then choose the best.", ("Why plan with five headings?", ["To collect plenty of ideas", "To make the writing longer", "There is no reason"], 0, "A plan collects ideas for every sense.")),
        _step("5", "Put details in order", "Put your sentences in a sensible order so the reader can follow. You might go from far to near, or from the moment the character arrives. Do not jump around.\n\nStart with the biggest, clearest picture, then add smaller details.", "First the gate and the lanterns, then the drum, then the smell, then the scarf, then the tea.", "Order helps the reader follow.", ("Which order is best?", ["Arrival, then the lanterns, then the sounds", "Random order", "Ending first"], 0, "A clear order helps the reader.")),
        _step("6", "Spelling focus: plurals with ies", "When a word ends in a consonant and y, change the y to i and add -es to make it plural. If a vowel comes before the y, just add -s.\n\nbaby becomes babies, but toy becomes toys.", "baby, babies; story, stories; puppy, puppies; pony, ponies; city, cities; family, families.", "Consonant plus y: change y to ies.", ("What is the plural of story?", ["storys", "stories", "storyes"], 1, "Change y to i and add es.")),
        _step("7", "Check and improve", "Read your writing aloud. Does it use more than one sense? Are the words precise? Do too many sentences start the same way? Fix one thing.\n\nGood writers always check.", "I started three sentences with 'There was'. I will change two of them.", "Read, check and improve.", ("What should you do after writing?", ["Read it aloud and improve it", "Hand it in without reading", "Make it shorter"], 0, "Reading aloud helps you notice problems.")),
    ],
    (
        "Work through The Night Market together. List the senses. See: golden lanterns, red apples, purple plums. Hear: a drum thumping and a seller shouting. Smell: sizzling onions and sweet honey. Touch: a soft woollen scarf and a cold raindrop. Taste: hot, sweet, smoky tea. "
        "Notice the precise words: golden, thumped, sizzling, sticky, flinched. Now try a new setting: a beach in the morning. See: bright blue water, white foam. Hear: waves crashing, gulls calling. Smell: salty air. Touch: cool, wet sand. Taste: salt on lips. "
        "Then write: 'White foam raced across the cool, wet sand, and gulls called overhead. The salty air tingled on my lips as the waves crashed.' Notice that this uses four senses, precise words and a clear order."
    ),
    (
        "Type your answers in the practice boxes. Part A: read The Night Market and type one detail for each of the five senses. Part B: improve the plain sentence 'The beach was nice' by adding two senses and precise words. Part C: make a five-heading plan for a setting of your choice. Part D: type the plural of baby, story, puppy, pony, city and family. Your parent can check your answers against the answer key."
    ),
    (
        "Read the passage, then complete the stages. Everything you write goes in the boxes.\n\n" + PASSAGE + "\n\n"
        "Stage 1: type one detail from the passage for each of the five senses.\n"
        "Stage 2: type three precise words from the passage (a noun, a verb and an adjective) and say why they work.\n"
        "Stage 3: choose one setting from this list (a forest at dawn, a busy kitchen, a playground in the rain, a train station, a campsite at night) and type a five-heading plan with at least two ideas under each heading.\n"
        "Stage 4: write a descriptive paragraph of five to seven sentences using your plan. Use at least four of the five senses, at least three precise words and a clear order.\n"
        "Stage 5: check your paragraph. Type which senses you used, which words you chose carefully and one thing you improved.\n"
        "Stage 6 (spell): type your six spelling words and the plural rule."
    ),
    "Which sense did you find easiest to describe, and which was hardest?", "Did I use at least four senses, choose precise words, put the details in a sensible order, check my writing and spell my six plurals?",
    [_q("What is a setting?", ["Where and when a story happens", "Who the story is about", "How a story ends", "The title"], 0, "The setting is where and when."), _q("Which sense is 'sizzling onions' mostly about?", ["Hearing and smell", "Touch", "Taste only", "None"], 0, "Sizzling is a sound and onions have a smell."), _q("Which is a touch detail?", ["A soft woollen scarf", "A thumping drum", "Golden lanterns", "Sweet honey smell"], 0, "Soft is felt with the hand."), _q("Which sentence is most precise?", ["The market was nice.", "Golden lanterns swung above the crowded stalls.", "There were lights.", "It was good."], 1, "It uses specific words."), _q("What should you do before writing?", ["Plan under five headings", "Write the ending", "Skip planning", "Draw only"], 0, "A plan helps you collect ideas."), _q("How many senses are there to think about?", ["Three", "Four", "Five", "Six"], 2, "There are five senses."), _q("What is the plural of baby?", ["babys", "babies", "babyes", "babis"], 1, "Change y to i and add es."), _q("What is the plural of toy?", ["toies", "toys", "toyes", "toyies"], 1, "A vowel comes before the y, so just add s."), _q("What is the plural of city?", ["citys", "cities", "cityes", "citis"], 1, "Change y to i and add es."), _q("Why read your writing aloud?", ["To notice and fix problems", "To make it longer", "To use fewer words", "No reason"], 0, "You can hear what does not sound right.")],
    "Type your answers in the practice boxes and submit them.", "Extension: write a second paragraph describing the same place at a different time of day, changing at least three sensory details.",
    [("setting", "Where and when a story happens"), ("sense", "One of sight, hearing, smell, touch and taste"), ("sensory", "Related to the senses"), ("vivid", "Clear and full of life"), ("precise", "Exact and specific"), ("plural", "More than one"), ("describe", "To tell what something is like"), ("atmosphere", "The feeling or mood of a place")],
    [_video("Descriptive writing for kids", "ULPDb7xD0S4", "Watch how the five senses help to describe a place. Pick out one sentence you could borrow the idea from.", "Read the worked example aloud and list the senses used.", ("What do descriptive writers use to set a scene?", ["The five senses", "Only numbers", "Only pictures"], 0, "They use the five senses.")), _video("Plurals: change y to ies", "NCPcEFs6Ytc", "Listen for the rule about a consonant before the y. Say the rule with the video.", "Read the spelling teaching aloud and say the rule.", ("What do you change the y to?", ["i, then add es", "e, then add s", "Nothing"], 0, "Change y to i and add es."))],
    _sort("Which sense is it?", "Sort each detail from The Night Market by sense.", ["See", "Hear", "Smell", "Touch", "Taste"], [("golden lanterns", 0), ("purple plums", 0), ("a drum thumping", 1), ("a seller shouting", 1), ("sizzling onions", 2), ("sticky honey", 2), ("a soft scarf", 3), ("a cold raindrop", 3), ("hot, sweet, smoky tea", 4)]),
    [_wc("Which is correct?", ["babies", "babys", "babyes"], 0, "Change y to i and add es."), _wc("Which is correct?", ["stories", "storys", "storyes"], 0, "Change y to i and add es."), _wc("Which is correct?", ["puppies", "puppys", "puppyes"], 0, "Change y to i and add es."), _wc("Which is correct?", ["ponys", "ponies", "ponyes"], 1, "Change y to i and add es."), _wc("Which is correct?", ["cities", "citys", "cityes"], 0, "Change y to i and add es."), _wc("Which is correct?", ["families", "familys", "familyes"], 0, "Change y to i and add es."), _wc("Which plural just adds s?", ["toys", "babies", "stories"], 0, "A vowel comes before the y."), _wc("Which is a smell detail?", ["sizzling onions", "golden lanterns", "a soft scarf"], 0, "Onions have a smell.")],
    [{"key":"partA","label":"Part A: five senses","hint":"One detail for each sense from The Night Market."}, {"key":"partB","label":"Part B: improve a sentence","hint":"Improve: The beach was nice. Use two senses and precise words."}, {"key":"partC","label":"Part C: five-heading plan","hint":"See, hear, smell, touch, taste."}, {"key":"partD","label":"Part D: plurals","hint":"baby, story, puppy, pony, city, family."}, {"key":"senses","label":"Details from the passage","hint":"One for each sense."}, {"key":"precise","label":"Three precise words","hint":"A noun, a verb and an adjective, and why they work."}, {"key":"plan","label":"My setting plan","hint":"Five headings with two or more ideas each."}, {"key":"paragraph","label":"My descriptive paragraph","hint":"Five to seven sentences using at least four senses."}, {"key":"check","label":"My check","hint":"Senses used, careful words and one improvement."}, {"key":"spelling","label":"Spelling words","hint":"Type the six plurals and the rule."}],
    ["Describing only what you see", "Using vague words such as nice, good and big", "Jumping around in the order of details", "Starting every sentence the same way", "Writing storys or babys instead of stories and babies"],
    ["Sit somewhere new for two minutes and list one detail for each sense.", "Find a descriptive sentence in a book and say which senses it uses."],
    "Part A: accept sensible details, for example: golden lanterns; a thumping drum; sizzling onions; a soft scarf; hot, sweet tea. Part B: accept sentences with two senses and precise words, for example: White foam raced across the cool sand while gulls called overhead. Part C: accept a plan with at least two ideas under each of the five headings. Part D: babies, stories, puppies, ponies, cities, families. Main task: look for four or more senses, precise words, a clear order and correct plurals. Quiz answers: where and when a story happens; hearing and smell; a soft woollen scarf; Golden lanterns swung above the crowded stalls; plan under five headings; five; babies; toys; cities; to notice and fix problems.",
)

LESSON["spelling"] = {"focus":"Plurals: consonant + y changes to ies", "teaching":"When a word ends in a consonant and y, change the y to i and add -es to make it plural. If a vowel comes before the y, just add -s (toy becomes toys).", "words":[_w("babies","bab-ies","change y to ies"),_w("stories","stor-ies","change y to ies"),_w("puppies","pupp-ies","change y to ies"),_w("ponies","pon-ies","change y to ies"),_w("cities","cit-ies","change y to ies"),_w("families","famil-ies","change y to ies")], "check":[_c("Which is spelled correctly?",["babys","babies","babyes"],1,"Change y to ies."),_c("Which is spelled correctly?",["citys","cities","cityes"],1,"Change y to ies.")]}
LESSON["spelling_focus"] = "Plurals: y to ies"
LESSON["hoard_words"] = list(WORDS)
