# Stage 2 Year 3 Maths lessons 8 and 9 for Ollie. Same structure as the Cartographer quest.
# Not yet registered in LESSON_LIBRARY. No reflection prompts (parent preference).
# Resource links marked 'search' are search pages, not specific items.

MINI_LESSONS = "https://iview.abc.net.au/show/mini-lessons-maths"


def _common(**kw):
    base = {
        "library": True,
        "stage": "S2",
        "year_level": "Year 3",
        "learning_area": "Mathematics",
        "pass_mark": 0.9,
        "reflection_prompts": [],
        "accessibility_notes": "Allow paper shapes, a mirror, grid paper and counters throughout. Answers can be spoken instead of written. Reduce the independent task to two parts if needed. Replay any video as often as needed.",
        "source_note": "Outcome codes checked against published NESA code lists. Parent to verify the exact outcome wording on curriculum.nsw.edu.au.",
    }
    base.update(kw)
    return base


LESSON_SHAPES = _common(
    seed_key="s2-y3-maths-2d-shapes-tile-maker-08",
    subject="2D shapes: features, symmetry, flips, slides, turns, combining and splitting",
    title="The Tile Maker",
    child_mission="You are the royal tile maker. Sort shapes by their features, flip, slide and turn them into patterns, and split and join shapes to design a mosaic floor.",
    duration_minutes=75,
    outcome_codes=["MA2-2DS-01", "MA2-2DS-02", "MAO-WM-01"],
    cross_outcome_codes=[],
    outcome_notes={
        "MA2-2DS-01": "Primary. Compares and describes 2D shapes by sides, vertices, angles, parallel sides and symmetry (steps 1-3, quiz 1-5, 9, sort).",
        "MA2-2DS-02": "Primary. Combines and splits shapes and describes flips, slides and turns (steps 4-5, quiz 6-8, 10).",
        "MAO-WM-01": "Working mathematically: tests ideas with paper shapes, explains how shapes are joined or split, and classifies by features (hands-on activity, independent task, rubric).",
    },
    learning_intention="We are learning to describe and compare 2D shapes by their features and to flip, slide, turn, join and split shapes.",
    success_criteria=[
        "I can name polygons by their number of sides.",
        "I can describe a shape using sides, vertices, parallel sides and right angles.",
        "I can find lines of symmetry.",
        "I can tell a flip, a slide and a turn apart.",
        "I can join shapes to make new shapes and split shapes into smaller ones.",
        "I can score 90% or more on the Quest check.",
    ],
    key_vocabulary=["polygon", "side", "vertex", "vertices", "parallel", "right angle", "symmetry", "flip", "slide", "turn", "quadrilateral", "pentagon", "hexagon", "octagon"],
    materials=["Paper and scissors", "Ruler", "Small mirror", "Grid paper", "Pattern blocks or paper shapes", "Device"],
    prior_knowledge="Child can name triangles, squares, rectangles and circles and count sides and corners.",
    common_misconceptions=[
        {"misconception": "The child thinks a shape changes name when it is turned.", "fix": "Turn a square 45 degrees. It is still a square."},
        {"misconception": "The child thinks a square is not a rectangle.", "fix": "A square has four right angles and opposite sides equal, so it fits the features of a rectangle too."},
        {"misconception": "The child confuses a flip with a turn.", "fix": "Use a mirror for flips. For turns, put a pencil on the shape and spin around it."},
    ],
    explicit_teaching="A POLYGON is a closed 2D shape with straight sides. Name it by its number of sides: triangle 3, quadrilateral 4, pentagon 5, hexagon 6, octagon 8. A VERTEX is a corner. A polygon has the same number of vertices as sides. PARALLEL sides stay the same distance apart and never meet. A RIGHT ANGLE is a square corner. A LINE OF SYMMETRY splits a shape into two halves that match when folded. A square has 4 lines of symmetry. A shape can be moved in three ways: a SLIDE moves it along, a FLIP gives a mirror image, and a TURN spins it around a point. Shapes can be COMBINED to make new shapes or SPLIT into smaller shapes.",
    teach_steps=[
        {"icon": "🔷", "title": "Polygons and their sides", "explain": "Count the sides to name the polygon. The number of vertices is the same as the number of sides.\n\nTry it: cut out a triangle, pentagon and hexagon and count their vertices.", "example": "A hexagon has 6 sides and 6 vertices. An octagon has 8 sides and 8 vertices.", "notice": "Sides and vertices are always equal in a polygon.", "check": {"question": "How many sides does a pentagon have?", "options": ["4", "5", "6"], "correct_index": 1, "explanation": "Pentagons have 5 sides."}},
        {"icon": "◼️", "title": "Four-sided shapes", "explain": "Shapes with 4 sides are quadrilaterals. Squares, rectangles, rhombuses, parallelograms and trapeziums are all quadrilaterals. We tell them apart by side lengths, parallel sides and right angles.\n\nTry it: list what is the same and what is different about a square and a rectangle.", "example": "A square has 4 equal sides and 4 right angles. A rectangle has 4 right angles and opposite sides equal.", "notice": "Look at sides, angles and parallel sides.", "check": {"question": "Which quadrilateral has 4 equal sides and 4 right angles?", "options": ["rectangle", "square", "triangle"], "correct_index": 1, "explanation": "A square has 4 equal sides and 4 right angles."}},
        {"icon": "🪞", "title": "Parallel sides and symmetry", "explain": "Parallel sides are the same distance apart all the way along. A line of symmetry is a fold line that makes two halves match.\n\nTry it: fold paper shapes to find lines of symmetry.", "example": "A rectangle has 2 pairs of parallel sides and 2 lines of symmetry. A square has 4 lines of symmetry.", "notice": "Use a mirror along a fold line to test symmetry.", "check": {"question": "How many lines of symmetry does a square have?", "options": ["1", "2", "4"], "correct_index": 2, "explanation": "A square has 4 lines of symmetry."}},
        {"icon": "🔄", "title": "Flip, slide and turn", "explain": "A slide moves a shape without changing its direction. A flip makes a mirror image. A turn spins the shape around a point.\n\nTry it: use a paper triangle to slide, flip and turn across a page.", "example": "Slide a triangle to the right. Flip it over a line to get a mirror image. Turn it a quarter turn around a corner.", "notice": "The size and shape stay the same. Only the position changes.", "check": {"question": "Which move gives a mirror image?", "options": ["slide", "flip", "turn"], "correct_index": 1, "explanation": "A flip creates a mirror image."}},
        {"icon": "🧩", "title": "Join and split shapes", "explain": "Shapes can be joined along matching sides to make new shapes. A shape can also be split into smaller shapes.\n\nTry it: join two identical triangles in different ways.", "example": "Two identical right-angled triangles can join to make a rectangle. A regular hexagon splits into 6 identical triangles.", "notice": "Join sides that are the same length.", "check": {"question": "A regular hexagon is split into identical triangles from the centre. How many triangles?", "options": ["3", "4", "6"], "correct_index": 2, "explanation": "A hexagon has 6 sides, so it splits into 6 triangles."}},
    ],
    worked_example="Describe a rectangle. It has 4 sides and 4 vertices. All 4 angles are right angles. It has 2 pairs of parallel sides. Opposite sides are equal. It has 2 lines of symmetry. Compare with a square: a square has 4 equal sides and 4 lines of symmetry. Now combine two identical right-angled triangles along their longest sides to make a rectangle. Then split the rectangle along a diagonal back into 2 triangles.",
    guided_practice="Sort six paper shapes into groups by number of sides, then pick two shapes and write two things that are the same and two things that are different. Slide, flip and turn one of the shapes on grid paper.",
    practice_questions=[
        {"q": "How many vertices does an octagon have?", "a": "8"},
        {"q": "How many pairs of parallel sides does a rectangle have?", "a": "2"},
        {"q": "Name a shape with 6 sides.", "a": "Hexagon"},
        {"q": "How many lines of symmetry does an equilateral triangle have?", "a": "3"},
        {"q": "Which move turns a shape around a point?", "a": "Turn"},
        {"q": "Two identical squares joined side by side make which shape?", "a": "A rectangle"},
    ],
    hands_on_activity="Shape lab. Cut out six paper shapes: triangle, square, rectangle, pentagon, hexagon and octagon. Count the sides and vertices of each and record them in a table. Fold each shape to find lines of symmetry. Then take one shape and slide it, flip it and turn it across grid paper, drawing each position. Finally join two shapes to make a new shape and draw it.",
    independent_task="Design a mosaic floor. Use at least four different shapes. Make one repeating pattern using a slide, a flip and a turn. Label three shapes with the number of sides, vertices and lines of symmetry. Show one place where you joined two shapes to make a new one and one place where you split a shape into smaller ones.",
    cross_curricular={"title": "Link idea", "note": "None recorded. Shape patterns connect to Visual Arts pattern work."},
    response_prompt="Label each shape and show your pattern with the moves you used.",
    self_check="Did I count both sides and vertices? Did I test symmetry with a fold? Did I name each move correctly?",
    rubric={"title": "What to look for", "levels": [
        {"level": "Getting started", "descriptor": "Names common shapes and counts sides with support. Mixes up flips, slides and turns."},
        {"level": "Secure", "descriptor": "Names polygons, describes features, finds lines of symmetry and correctly performs flips, slides and turns."},
        {"level": "Strong", "descriptor": "Compares shapes using several features, designs a pattern with all three moves and explains how shapes join and split."},
    ]},
    interactive_activities=[{"type": "flip_cards", "title": "Quest Codex: key terms", "cards": [
        {"front": "Polygon", "back": "A closed 2D shape with straight sides."},
        {"front": "Vertex", "back": "A corner where two sides meet. More than one are vertices."},
        {"front": "Parallel", "back": "Lines that stay the same distance apart and never meet."},
        {"front": "Right angle", "back": "A square corner."},
        {"front": "Line of symmetry", "back": "A fold line that makes two halves match."},
        {"front": "Flip", "back": "A mirror image of a shape."},
        {"front": "Slide", "back": "Moving a shape along without turning it."},
        {"front": "Turn", "back": "Spinning a shape around a point."},
    ]}],
    sort_activity={"title": "Count the sides", "instructions": "Sort each shape by its number of sides.", "buckets": ["3 sides", "4 sides", "5 or more sides"], "items": [
        {"text": "Triangle", "answer": 0}, {"text": "Square", "answer": 1}, {"text": "Pentagon", "answer": 2}, {"text": "Rectangle", "answer": 1},
        {"text": "Hexagon", "answer": 2}, {"text": "Octagon", "answer": 2}, {"text": "Rhombus", "answer": 1}, {"text": "Right-angled triangle", "answer": 0},
    ]},
    word_challenges=[
        {"question": "A corner of a polygon is a ___.", "options": ["vertex", "side", "face"], "correct_index": 0, "explanation": "A corner is a vertex."},
        {"question": "A mirror image of a shape is a ___.", "options": ["flip", "slide", "turn"], "correct_index": 0, "explanation": "A flip makes a mirror image."},
        {"question": "A fold line that makes matching halves is a line of ___.", "options": ["symmetry", "sides", "angles"], "correct_index": 0, "explanation": "This is a line of symmetry."},
        {"question": "Lines that stay the same distance apart are ___.", "options": ["parallel", "crossing", "curved"], "correct_index": 0, "explanation": "Parallel lines never meet."},
    ],
    planner_fields=[
        {"key": "shapes", "label": "My four shapes", "hint": "List the shapes you will use."},
        {"key": "moves", "label": "My pattern moves", "hint": "Write which slide, flip and turn you will use."},
        {"key": "joinsplit", "label": "Join and split", "hint": "Describe one join and one split."},
    ],
    steps=[
        {"title": "Step 1: Accept the quest", "detail": "Read your mission and accept the quest.", "duration_minutes": 5},
        {"title": "Step 2: Watch and warm up", "detail": "Watch an ABC Mini Lessons Maths episode on 2D shapes or symmetry, then do the shape lab.", "duration_minutes": 15},
        {"title": "Step 3: Learn the skills", "detail": "Five short lessons: polygons, four-sided shapes, symmetry, moves and join and split.", "duration_minutes": 15},
        {"title": "Step 4: Practise", "detail": "Flip the key-term cards, sort shapes, answer word challenges and do the practice questions.", "duration_minutes": 10},
        {"title": "Step 5: Plan and build", "detail": "Fill in your planner, then complete the independent task on paper.", "duration_minutes": 20},
        {"title": "Step 6: Clear the Quest check", "detail": "Answer the 10-question Quest check. You need 9 out of 10 to pass.", "duration_minutes": 5},
        {"title": "Step 7: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
    ],
    resources=[
        {"type": "video", "title": "ABC Mini Lessons: Maths (series page; choose a 2D shape or symmetry episode for Years 3-4)", "url": MINI_LESSONS, "prompt": "Pick an episode on 2D shapes or symmetry. Pause and try each example first."},
        {"type": "worksheet", "title": "Twinkl Australia: 2D shapes Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=2d+shapes+year+3", "prompt": "Choose a printable worksheet. Log in to your Twinkl account to download."},
        {"type": "worksheet", "title": "Twinkl Australia: flip slide turn Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=flip+slide+turn+year+3", "prompt": "Choose a printable worksheet."},
    ],
    quiz=[
        {"question": "How many sides does a hexagon have?", "type": "multiple_choice", "options": ["5", "6", "7", "8"], "correct_index": 1, "explanation": "A hexagon has 6 sides."},
        {"question": "How many vertices does a pentagon have?", "type": "multiple_choice", "options": ["4", "5", "6", "8"], "correct_index": 1, "explanation": "A pentagon has 5 vertices."},
        {"question": "Which shape has 4 equal sides and 4 right angles?", "type": "multiple_choice", "options": ["rectangle", "square", "trapezium", "triangle"], "correct_index": 1, "explanation": "Only a square has all four sides equal and all four angles right angles."},
        {"question": "How many pairs of parallel sides does a rectangle have?", "type": "multiple_choice", "options": ["0", "1", "2", "4"], "correct_index": 2, "explanation": "Opposite sides of a rectangle are parallel, giving 2 pairs."},
        {"question": "How many sides does an octagon have?", "type": "multiple_choice", "options": ["6", "7", "8", "10"], "correct_index": 2, "explanation": "An octagon has 8 sides."},
        {"question": "A shape moves along without turning or flipping. What is this move?", "type": "multiple_choice", "options": ["flip", "slide", "turn", "split"], "correct_index": 1, "explanation": "Moving along without changing direction is a slide."},
        {"question": "Which move creates a mirror image?", "type": "multiple_choice", "options": ["slide", "flip", "turn", "shrink"], "correct_index": 1, "explanation": "A flip creates a mirror image."},
        {"question": "Two identical right-angled triangles can be joined to make which shape?", "type": "multiple_choice", "options": ["circle", "rectangle", "hexagon", "pentagon"], "correct_index": 1, "explanation": "Joined along their longest sides they can make a rectangle."},
        {"question": "How many lines of symmetry does a square have?", "type": "multiple_choice", "options": ["1", "2", "4", "8"], "correct_index": 2, "explanation": "A square has 4 lines of symmetry."},
        {"question": "A regular hexagon is split from its centre into identical triangles. How many triangles?", "type": "multiple_choice", "options": ["2", "3", "4", "6"], "correct_index": 3, "explanation": "One triangle for each of the 6 sides."},
    ],
    evidence_instructions="Upload a photo of your shape table, your mosaic floor pattern with the moves labelled, and your join and split examples.",
    parent_notes="Seven steps, about 75 minutes. Covers naming polygons, describing quadrilaterals, parallel sides, symmetry, flips, slides and turns, and joining and splitting shapes. Look for: correct vocabulary, a systematic count of sides and vertices, and a pattern that clearly shows each move. Outcomes: MA2-2DS-01, MA2-2DS-02 and MAO-WM-01. Please verify the exact outcome wording on the NSW site. Video resource is a series page: choose one episode.",
    offline_alternative="Use cut-out paper shapes, a mirror and grid paper with a printed worksheet.",
    extension="Find which shapes can tile a floor with no gaps. Explain why a circle cannot.",
    follow_up_challenges=[
        {"title": "Shape hunt", "description": "Find five polygons around the house and photograph them. Label each with its number of sides.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
        {"title": "Symmetry art", "description": "Fold paper, cut a shape and open it to make a symmetrical design. Mark the line of symmetry.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
    ],
)


LESSON_AREA = _common(
    seed_key="s2-y3-maths-area-garden-designer-09",
    subject="Area in square centimetres and square metres",
    title="The Garden Designer",
    child_mission="A new park needs a garden designer. Measure plots, count squares and work out the area of beds, paths and lawns before the diggers arrive.",
    duration_minutes=75,
    outcome_codes=["MA2-2DS-03", "MAO-WM-01"],
    cross_outcome_codes=[],
    outcome_notes={
        "MA2-2DS-03": "Primary. Measures and compares area using square centimetres and square metres and finds the area of rectangles by multiplying length and width (steps 1-5, quiz 1-10, sort).",
        "MAO-WM-01": "Working mathematically: models area with grid paper and tiles, explains the array method and checks by counting (hands-on activity, independent task, rubric).",
    },
    learning_intention="We are learning to measure and compare area using square units and to find the area of rectangles.",
    success_criteria=[
        "I can explain that area is the space inside a shape.",
        "I can count unit squares to find area.",
        "I can choose between square centimetres and square metres.",
        "I can find the area of a rectangle by multiplying length and width.",
        "I can find the area of a shape made from two rectangles.",
        "I can score 90% or more on the Quest check.",
    ],
    key_vocabulary=["area", "square centimetre", "cm2", "square metre", "m2", "unit square", "length", "width", "array", "compare"],
    materials=["Grid paper (1 cm squares)", "Ruler", "Newspaper sheets and tape (for 1 m2)", "Pencil and coloured pencils", "Device"],
    prior_knowledge="Child knows multiplication facts for 2, 3, 4, 5 and 10 and can measure length in cm and m.",
    common_misconceptions=[
        {"misconception": "The child confuses area with perimeter and adds the sides.", "fix": "Perimeter is the distance around. Area is the number of squares inside."},
        {"misconception": "The child thinks a longer shape always has the larger area.", "fix": "Count squares. A 5 by 4 rectangle has a larger area than a 6 by 3 rectangle."},
        {"misconception": "The child forgets to write square units.", "fix": "Say 'twelve square centimetres' and write 12 cm2 every time."},
    ],
    explicit_teaching="AREA is the amount of surface inside a 2D shape. We measure area by counting UNIT SQUARES that cover the shape with no gaps and no overlaps. A square with sides of 1 cm has an area of 1 square centimetre (1 cm2). A square with sides of 1 m has an area of 1 square metre (1 m2). Use cm2 for small surfaces like a stamp and m2 for large surfaces like a room. For a rectangle, the squares form an ARRAY of rows and columns. Area = length x width. A 4 by 3 rectangle has 4 x 3 = 12 squares, so its area is 12 cm2. To find the area of a shape made of two rectangles, find each area and add them.",
    teach_steps=[
        {"icon": "🟩", "title": "What is area?", "explain": "Area is the space inside a shape. Cover the shape with squares of the same size. Count them.\n\nTry it: cover a book with sticky notes and count them.", "example": "A shape covered by 10 unit squares has an area of 10 square units.", "notice": "No gaps and no overlaps.", "check": {"question": "Area measures ___.", "options": ["the distance around a shape", "the space inside a shape", "the weight of a shape"], "correct_index": 1, "explanation": "Area is the space inside."}},
        {"icon": "📏", "title": "Square centimetres and metres", "explain": "A 1 cm square has an area of 1 cm2. A 1 m square has an area of 1 m2. Use cm2 for small surfaces and m2 for large ones.\n\nTry it: tape four sheets of newspaper into about 1 m2 and stand on it.", "example": "A stamp is measured in cm2. A classroom floor is measured in m2.", "notice": "The unit name has to say square.", "check": {"question": "Which unit is best for the area of a classroom floor?", "options": ["cm2", "m2", "mL"], "correct_index": 1, "explanation": "A floor is large, so square metres are best."}},
        {"icon": "🔢", "title": "Arrays and area", "explain": "The squares in a rectangle make rows and columns. Count squares in one row, then multiply by the number of rows.\n\nTry it: draw a 6 by 4 rectangle on grid paper and find its area.", "example": "6 squares in a row and 4 rows gives 6 x 4 = 24 squares. The area is 24 cm2.", "notice": "Area = length x width.", "check": {"question": "A rectangle is 5 cm long and 3 cm wide. What is its area?", "options": ["8 cm2", "15 cm2", "16 cm2"], "correct_index": 1, "explanation": "5 x 3 = 15 cm2."}},
        {"icon": "⚖️", "title": "Compare areas", "explain": "To compare areas, find each area using the same unit. The larger number has the larger area. Shapes that look different can have the same area.\n\nTry it: draw two different rectangles that both have an area of 12 cm2.", "example": "A 5 by 4 rectangle has an area of 20 cm2. A 6 by 3 rectangle has an area of 18 cm2. So 5 by 4 is larger.", "notice": "Use the same unit when comparing.", "check": {"question": "Which has the larger area: 6 by 3 or 5 by 4?", "options": ["6 by 3", "5 by 4", "They are equal"], "correct_index": 1, "explanation": "6 x 3 = 18 and 5 x 4 = 20, so 5 by 4 is larger."}},
        {"icon": "🧩", "title": "Joined rectangles", "explain": "Split an L-shape into two rectangles, find each area, then add.\n\nTry it: draw an L-shape on grid paper and split it into two rectangles.", "example": "An L-shape is made from a 4 by 2 rectangle (8 cm2) and a 3 by 2 rectangle (6 cm2). The total area is 14 cm2.", "notice": "Split, find each area, then add.", "check": {"question": "An L-shape is made from a 4 by 2 rectangle and a 3 by 2 rectangle. What is its area?", "options": ["12 cm2", "14 cm2", "24 cm2"], "correct_index": 1, "explanation": "8 + 6 = 14 cm2."}},
    ],
    worked_example="A garden bed is 8 m long and 3 m wide. Area = 8 x 3 = 24 m2. A second bed is 6 m by 5 m. Area = 6 x 5 = 30 m2. The second bed is larger by 30 - 24 = 6 m2. For a path shaped like an L: one part is 5 m by 2 m (10 m2) and the other is 3 m by 2 m (6 m2). Total path area is 10 + 6 = 16 m2.",
    guided_practice="On grid paper, draw a 7 by 3 rectangle and find its area by counting then by multiplying. Then draw an L-shape, split it into two rectangles and find the total area.",
    practice_questions=[
        {"q": "Area of a 4 cm by 3 cm rectangle", "a": "12 cm2"},
        {"q": "Area of a square with sides of 5 cm", "a": "25 cm2"},
        {"q": "Area of a 10 m by 2 m rectangle", "a": "20 m2"},
        {"q": "A rectangle has an area of 18 cm2 and is 6 cm long. How wide is it?", "a": "3 cm"},
        {"q": "Which is larger: 5 by 4 or 6 by 3?", "a": "5 by 4"},
        {"q": "Area of an L-shape made of 4 by 2 and 3 by 2 rectangles", "a": "14 cm2"},
    ],
    hands_on_activity="Grid garden. On grid paper, draw four rectangles with different sizes. For each, count the squares, then multiply to check. Record the area in cm2. Draw two different rectangles with the same area. Then tape newspaper together to make 1 m2 and find three things at home with an area about that size, such as a doormat or a table.",
    independent_task="Design a park garden on grid paper using 1 square = 1 m2. Include a lawn, two flower beds and an L-shaped path. Label each part with its length, width and area. Find the total area of your park and say which part is the largest. Write one comparison statement and show how you know.",
    cross_curricular={"title": "Link idea", "note": "None recorded. Area and plans link to later Technologies design work."},
    response_prompt="Show the length, width and area of every part of your garden and your total.",
    self_check="Did I write square units? Did I check my multiplication by counting? Did I add all parts of the L-shape?",
    rubric={"title": "What to look for", "levels": [
        {"level": "Getting started", "descriptor": "Counts squares to find area with support. May confuse area and perimeter."},
        {"level": "Secure", "descriptor": "Uses cm2 and m2 correctly, multiplies length by width and compares areas using the same unit."},
        {"level": "Strong", "descriptor": "Finds the area of joined rectangles, works out a missing side from the area and explains the array method."},
    ]},
    interactive_activities=[{"type": "flip_cards", "title": "Quest Codex: key terms", "cards": [
        {"front": "Area", "back": "The amount of surface inside a 2D shape."},
        {"front": "Unit square", "back": "A square used to measure area, such as 1 cm by 1 cm."},
        {"front": "Square centimetre (cm2)", "back": "The area of a square with 1 cm sides."},
        {"front": "Square metre (m2)", "back": "The area of a square with 1 m sides."},
        {"front": "Array", "back": "Rows and columns of equal size."},
        {"front": "Length", "back": "How long a rectangle is."},
        {"front": "Width", "back": "How wide a rectangle is."},
        {"front": "Perimeter", "back": "The distance around a shape. This is not area."},
    ]}],
    sort_activity={"title": "cm2 or m2?", "instructions": "Choose the best unit to measure the area of each.", "buckets": ["Square centimetres (cm2)", "Square metres (m2)"], "items": [
        {"text": "Postage stamp", "answer": 0}, {"text": "Classroom floor", "answer": 1}, {"text": "Book cover", "answer": 0}, {"text": "Football field", "answer": 1},
        {"text": "Phone screen", "answer": 0}, {"text": "Basketball court", "answer": 1}, {"text": "Playground", "answer": 1}, {"text": "Sticky note", "answer": 0},
    ]},
    word_challenges=[
        {"question": "The space inside a shape is its ___.", "options": ["area", "perimeter", "volume"], "correct_index": 0, "explanation": "Area is the space inside."},
        {"question": "Area is measured in ___ units.", "options": ["square", "straight", "round"], "correct_index": 0, "explanation": "We count squares."},
        {"question": "Area of a rectangle = length x ___.", "options": ["width", "height", "sides"], "correct_index": 0, "explanation": "Area is length times width."},
        {"question": "The distance around a shape is the ___.", "options": ["perimeter", "area", "volume"], "correct_index": 0, "explanation": "Perimeter is not the same as area."},
    ],
    planner_fields=[
        {"key": "parts", "label": "My garden parts", "hint": "List the lawn, beds and path with their sizes."},
        {"key": "areas", "label": "Areas", "hint": "Write the area of each part in m2."},
        {"key": "total", "label": "Total area", "hint": "Write the total and the largest part."},
    ],
    steps=[
        {"title": "Step 1: Accept the quest", "detail": "Read your mission and accept the quest.", "duration_minutes": 5},
        {"title": "Step 2: Watch and warm up", "detail": "Watch an ABC Mini Lessons Maths episode on area, then do the grid garden activity.", "duration_minutes": 15},
        {"title": "Step 3: Learn the skills", "detail": "Five short lessons: what area is, units, arrays, comparing and joined rectangles.", "duration_minutes": 15},
        {"title": "Step 4: Practise", "detail": "Flip the key-term cards, sort cm2 and m2, answer word challenges and do the practice questions.", "duration_minutes": 10},
        {"title": "Step 5: Plan and design", "detail": "Fill in your planner, then complete the independent task on paper.", "duration_minutes": 20},
        {"title": "Step 6: Clear the Quest check", "detail": "Answer the 10-question Quest check. You need 9 out of 10 to pass.", "duration_minutes": 5},
        {"title": "Step 7: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
    ],
    resources=[
        {"type": "video", "title": "ABC Mini Lessons: Maths (series page; choose an area episode for Years 3-4)", "url": MINI_LESSONS, "prompt": "Pick an episode on area. Pause and try each example first."},
        {"type": "worksheet", "title": "Twinkl Australia: area Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=area+year+3", "prompt": "Choose a printable worksheet. Log in to your Twinkl account to download."},
        {"type": "worksheet", "title": "Twinkl Australia: area of rectangles Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=area+of+rectangles+year+3", "prompt": "Choose a printable worksheet."},
    ],
    quiz=[
        {"question": "What is the area of a rectangle that is 4 cm long and 3 cm wide?", "type": "multiple_choice", "options": ["7 cm2", "12 cm2", "14 cm2", "24 cm2"], "correct_index": 1, "explanation": "4 x 3 = 12 cm2."},
        {"question": "What is the area of a rectangle that is 6 cm long and 5 cm wide?", "type": "multiple_choice", "options": ["11 cm2", "22 cm2", "30 cm2", "36 cm2"], "correct_index": 2, "explanation": "6 x 5 = 30 cm2."},
        {"question": "What is the area of a square with sides of 4 cm?", "type": "multiple_choice", "options": ["8 cm2", "12 cm2", "16 cm2", "20 cm2"], "correct_index": 2, "explanation": "4 x 4 = 16 cm2."},
        {"question": "Which unit is best for the area of a classroom floor?", "type": "multiple_choice", "options": ["square centimetres", "square metres", "litres", "kilograms"], "correct_index": 1, "explanation": "A floor is large, so square metres are best."},
        {"question": "Which unit is best for the area of a postage stamp?", "type": "multiple_choice", "options": ["square centimetres", "square metres", "metres", "millilitres"], "correct_index": 0, "explanation": "A stamp is small, so square centimetres are best."},
        {"question": "A rectangle is 10 m long and 2 m wide. What is its area?", "type": "multiple_choice", "options": ["12 m2", "20 m2", "24 m2", "40 m2"], "correct_index": 1, "explanation": "10 x 2 = 20 m2."},
        {"question": "Which rectangle has the larger area?", "type": "multiple_choice", "options": ["5 by 4", "6 by 3", "They are equal", "You cannot tell"], "correct_index": 0, "explanation": "5 x 4 = 20 and 6 x 3 = 18, so 5 by 4 is larger."},
        {"question": "A garden is 8 m long and 3 m wide. What is its area?", "type": "multiple_choice", "options": ["11 m2", "22 m2", "24 m2", "38 m2"], "correct_index": 2, "explanation": "8 x 3 = 24 m2."},
        {"question": "An L-shape is made from a 4 by 2 rectangle and a 3 by 2 rectangle. What is its area?", "type": "multiple_choice", "options": ["12 cm2", "14 cm2", "24 cm2", "7 cm2"], "correct_index": 1, "explanation": "8 + 6 = 14 cm2."},
        {"question": "A rectangle has an area of 18 cm2 and is 6 cm long. How wide is it?", "type": "multiple_choice", "options": ["2 cm", "3 cm", "4 cm", "12 cm"], "correct_index": 1, "explanation": "6 x 3 = 18, so the width is 3 cm."},
    ],
    evidence_instructions="Upload a photo of your grid garden, the area of each part with its length and width, your total and your comparison statement.",
    parent_notes="Seven steps, about 75 minutes. Builds from counting unit squares to arrays, comparing areas and joined rectangles. Look for: square units written correctly, area kept separate from perimeter, and multiplication checked by counting. Outcomes: MA2-2DS-03 (area) and MAO-WM-01. Video resource is a series page: choose one episode.",
    offline_alternative="Use printed grid paper and tiles or sticky notes to cover real surfaces.",
    extension="Find a rectangle with area 24 cm2 in three different ways. Which has the shortest perimeter?",
    follow_up_challenges=[
        {"title": "Room area", "description": "Measure one room at home in metres and find its area in m2. Compare it to another room.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
        {"title": "Same area, different shape", "description": "Draw five different rectangles with an area of 16 cm2.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
    ],
)

S2Y3_MATHS_LESSONS_5 = [LESSON_SHAPES, LESSON_AREA]
