"""Stage 2 English, first-week Lesson 1: story elements. Fully taught from scratch (no prior knowledge assumed).
Videos verified by YouTube oEmbed on 2026-10-07. BBC Bitesize sends X-Frame-Options DENY, so it is never embedded."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W2L1 = build(
    "s2-eng-w02-l1-story-elements", "Story Architect: Characters, Setting and Plot",
    "A story has collapsed! Learn every part a story is built from, one careful step at a time, then rebuild one from its clues.",
    "Reading: story elements and narrative structure",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-RECOM-01": "Primary. Identifies characters, setting, conflict and plot structure, and supports answers with evidence from the text.",
     "EN2-VOCAB-01": "Learns and uses Tier 3 words: character, setting, plot, conflict, exposition, climax, resolution, evidence, and a bank of trait words.",
     "EN2-SPELL-01": "Learns and applies vowel team spelling (ai, ay, ee, ea, oa) with a Look, Say, Cover, Write, Check routine."},
    "We are learning to identify the parts of a story, explain how they fit together, and prove our answers with evidence from the text.",
    ["I can name the characters and explain what they are like using what they do, say and think.",
     "I can describe the setting (place, time and mood) using clue words from the text.",
     "I can say what the problem (conflict) is and what type it is.",
     "I can put the five parts of a plot in order and explain how each event causes the next.",
     "I can answer a question using the evidence pattern: answer, text says, because.",
     "I can spell story words with the vowel teams ai, ay, ee, ea and oa."],
    ["character", "trait", "setting", "mood", "plot", "conflict", "exposition", "rising action", "climax", "falling action", "resolution", "evidence"],
    ["Paper or notebook", "Pencil and coloured pencils", "A short story from any book you own (a picture book is perfect)"],
    "Nothing is assumed. Child needs to be able to read a short story. Every term used in this lesson is taught, with examples, before it is used.",
    "Every story, from a picture book to a film, is built from the same set of parts. If you know the parts, you know what to look for when you read, and you know what to build when you write.\n\nThere are three big building blocks. CHARACTERS are who the story is about. The SETTING is where and when it happens, and how it feels. The PLOT is the chain of events, and it always starts with a problem, called the CONFLICT.\n\nThe plot has a shape, a bit like a mountain. The story begins at the bottom with the EXPOSITION (we meet the characters and the setting). Then the RISING ACTION climbs as the problem grows. At the top is the CLIMAX, the most exciting moment. Then the FALLING ACTION comes down the other side, and the RESOLUTION is the flat ground at the end where the problem is solved or changed.\n\nFinally, readers do not just say what they think about a story. They PROVE it with EVIDENCE, which means pointing to the exact words or actions in the text. We will practise all of this in small steps, and every new word is explained before you need it.",
    [
        _step("1", "What is a story made of?",
              "Think about building a house. Before anyone starts, they know a house needs walls, a floor and a roof. A story works the same way. Every story needs some parts, and once you know them you can spot them anywhere.\n\nHere is the whole set, in plain words:\n- Characters: WHO the story is about.\n- Setting: WHERE and WHEN it happens.\n- Conflict: the PROBLEM.\n- Plot: the ORDER of events, from the problem starting to the problem being solved.\n\nWhy bother learning these? When you read, the parts help you understand and remember. When you write, the parts tell you what you must include. Authors use them even when they do not say so.\n\nYou can test any story with four quick questions: Who is it about? Where and when is it? What goes wrong? How does it end? If you can answer those four, you understand the story's bones.",
              "Story: 'A girl named Priya lost her dog at the beach on a stormy afternoon. She searched the sand and the rocks, and at last she found him sheltering in a cave.' Who? Priya (and her dog). Where and when? A beach, a stormy afternoon. What goes wrong? The dog is lost. How does it end? She finds him in a cave.",
              "Four questions (Who? Where and when? What goes wrong? How does it end?) unlock almost any story.",
              ("Which question helps you find the CONFLICT?", ["What goes wrong?", "Who is it about?", "Where is it?"], 0, "The conflict is the problem, so ask what goes wrong.")),
        _step("2", "Characters: who is in the story?",
              "CHARACTERS are the people, animals or creatures a story is about. The MAIN CHARACTER is the one the story follows most closely, and it is usually their problem we care about. Other characters, called supporting characters, help the main character, get in the way, or change them.\n\nAuthors rarely say outright what a character is like. Instead, they SHOW us, and we work it out. There are four clues to look for:\n1. What the character DOES (their actions).\n2. What the character SAYS (their words).\n3. What the character THINKS or FEELS.\n4. What OTHER characters say about them.\n\nWhen you meet a character, ask two questions. What do they WANT? What are they LIKE? A character who wants something and cannot easily get it is what makes a story move.",
              "In The Three Little Pigs, the characters are three pigs and a wolf. The wolf WANTS dinner. The third pig is clever, and we know it because of what he DOES: he builds his house with bricks, not straw or sticks.\n\nAnother example: 'Ben waited until everyone else had a slice before he took the smallest piece.' We are never told 'Ben is generous', but his ACTION shows it.",
              "Actions usually tell us more about a character than a label like 'nice' ever could.",
              ("'Kai said nothing, but he quietly picked up the little boy's fallen ice cream and bought him another.' What clue type is this?", ["What the character does", "What other characters say", "What the setting looks like"], 0, "Picking up the ice cream and buying another are actions.")),
        _step("3", "Traits: describing what a character is like",
              "A TRAIT is a word that describes what a character is like inside. A trait lasts: it shows up again and again across the story. Examples are brave, kind, clever, stubborn, nervous and honest.\n\nA trait is different from a FEELING. A feeling is temporary: happy, scared, angry or tired. A character might feel scared in one scene yet still be brave overall, because bravery is doing the right thing even while scared.\n\nHere is a bank of useful trait words. Positive: determined, generous, loyal, curious. Mixed or negative: selfish, careless, sneaky, impatient. Use a trait word instead of 'nice' or 'bad' because it is more exact.\n\nTo choose a trait, find an action or a quote and ask: what does this show about the person?",
              "Evidence of a trait. Action: 'Mia returned the wallet with every dollar still inside.' Trait: honest. Action: 'He kept trying the lock again and again, even after the sun went down.' Trait: determined.\n\nTrait or feeling? 'Zoe was nervous before the show' is a feeling. 'Zoe always double-checked everything twice' is a trait (careful).",
              "If it changes quickly it is probably a feeling. If it keeps showing up it is a trait.",
              ("'Omar gave away half his lunch every day.' Which trait fits best?", ["Generous", "Careless", "Sneaky"], 0, "Giving away food again and again shows generosity.")),
        _step("4", "Setting: where, when and how it feels",
              "The SETTING is the place and time of a story. The place might be a house, a jungle, a spaceship or a school. The time might be a season, a time of day or a period of history.\n\nGood settings also have a MOOD, which is the feeling a place gives the reader, such as cosy, eerie, peaceful or tense. Authors create mood with sensory details: what you can see, hear, smell, feel and taste.\n\nHow to find the setting: look for PLACE words (in the forest, at the harbour), TIME words (one winter morning, long ago, at midnight) and DESCRIBING words that create mood (silent, dusty, glowing).\n\nSetting is not just a backdrop. It can cause the problem. A storm can strand a boat. A desert can make water a treasure. When the setting changes, the story often changes too.",
              "'The fog crept over the silent harbour at dawn.' Place: a harbour. Time: dawn. Mood: quiet and mysterious. Clue words: crept, silent, fog.\n\nCompare: 'The sun sparkled on the harbour as children laughed on the pier.' Same place, completely different mood. The words the author chooses change how the place feels.",
              "Ask three things about every setting: Where? When? How does it feel?",
              ("'One winter morning, snow covered the sleeping farm.' What is the TIME?", ["One winter morning", "The farm", "Snow"], 0, "Winter morning tells us when. The farm is where.")),
        _step("5", "Conflict: the problem that starts everything",
              "Without a problem, nothing happens. A story where a boy has breakfast, walks to school and has lunch is not much of a story. The CONFLICT is the problem that gives the character something to want and something standing in the way.\n\nThere are four common types of conflict:\n1. Character against character (two people want opposite things, like the wolf and the pigs).\n2. Character against nature (a storm, a flood, a blizzard, a wild animal).\n3. Character against self (a shy child must speak up, or someone must choose between right and wrong).\n4. Character against a situation (a lost child in a crowded city, or a team that is behind on the scoreboard).\n\nTo find the conflict, ask: What does the character want, and what is stopping them? The answer to the second half is the conflict.",
              "Character against nature: a hiker is lost in a blizzard. Character against self: a shy girl must give a speech and is afraid she will freeze. Character against character: two brothers both want the last cookie. Character against situation: a boy gets separated from his class on a school trip to the city.",
              "Want plus obstacle equals conflict.",
              ("A sailor fights huge waves to reach shore. What type of conflict is this?", ["Character against nature", "Character against self", "Character against character"], 0, "The waves are a force of nature standing in the way.")),
        _step("6", "The plot mountain, part one: the climb",
              "The PLOT is the order of events in a story. Most plots follow a shape like a mountain with five parts. In this step we climb up.\n\nPART 1, EXPOSITION: the start. We meet the characters, learn the setting and see what the main character wants. It is the base camp at the bottom of the mountain.\n\nPART 2, RISING ACTION: the climb. The problem arrives and gets harder. There are usually two or three events, and each one is trickier than the last. The reader feels the tension grow.\n\nThe secret to a good plot is cause and effect. Each event happens BECAUSE of the one before it. A plot is not just a list that says 'and then... and then...'. Test it with the words because and so: 'The kite snapped free, so Sam ran after it.'",
              "The Three Little Pigs. Exposition: three pigs leave home and each builds a house, one of straw, one of sticks, one of bricks. Rising action: the wolf blows down the straw house, so the first pig runs to the stick house. The wolf blows that down too, so both pigs run to the brick house.",
              "If you cannot join two events with 'because' or 'so', a piece of the plot may be missing.",
              ("Which part of the plot introduces the characters and setting?", ["Exposition", "Climax", "Resolution"], 0, "Exposition is the opening, the base of the mountain.")),
        _step("7", "The plot mountain, part two: the peak and the descent",
              "Now we reach the top and come back down.\n\nPART 3, CLIMAX: the peak. This is the most exciting turning point, where the main character faces the problem head on. After it, nothing is the same.\n\nPART 4, FALLING ACTION: coming down the mountain. We see what happens straight after the climax, and the tension eases.\n\nPART 5, RESOLUTION: the flat ground at the end. The problem is solved, or at least changed, and we see how the character has grown. A good resolution fits the problem. If the problem was a lost dog, the ending should be about the dog.\n\nNot every story is neat. In some, the problem is changed rather than fixed, and the character learns something instead. That still counts as a resolution.",
              "The Three Little Pigs, continued. Climax: the wolf cannot blow down the brick house, so he climbs onto the roof and tries the chimney. Falling action: he falls into the pot of boiling water. Resolution: the wolf runs away and the three pigs are safe and happy in the brick house.",
              "The climax is where the problem is faced. The resolution is where the story settles down.",
              ("What happens at the CLIMAX?", ["The most exciting turning point", "We meet the characters", "The story starts again"], 0, "The climax is the high point of the mountain.")),
        _step("8", "Evidence: how to prove your answer",
              "When a question asks 'How do you know?', you need EVIDENCE. Evidence is a word, a line or an action from the text that proves your answer. It is the difference between an opinion and a reasoned answer.\n\nUse a three-part pattern:\n1. MY ANSWER: say what you think.\n2. THE TEXT SAYS (or SHOWS): give the exact words or action.\n3. BECAUSE: explain how that proves your answer.\n\nSentence starters: 'I think... The text says... This shows that...' or 'I know this because the author wrote...'.\n\nA weak answer: 'Mia was scared.' A strong answer: 'Mia was scared. The text says her hands shook and she kept looking at the door. This shows she was afraid of what would happen.' If you cannot point to it in the text, it is only a guess.",
              "Question: What kind of setting is it? Answer: The setting is lonely. Evidence: 'a single light burned in the empty street'. Because: one light and an empty street suggest there is nobody else around.",
              "Answer, text says, because: always three parts.",
              ("Which is the best EVIDENCE that a boy is tired?", ["'He yawned and rested his head on the desk.'", "I think he is tired.", "The boy is in a classroom."], 0, "Yawning and resting his head are things from the text that prove it.")),
        _step("9", "Spelling: vowel teams in story words",
              "A VOWEL TEAM is two vowels side by side that work together to make one sound. Many story words use them. Here are five teams to learn.\n\nai and ay both make the long a sound (say the letter name): rain, trail, plain, play, stay, display. A handy rule: ai usually sits in the MIDDLE of a word and ay usually comes at the END.\n\nee and ea both make the long e sound: tree, sleep, green, dream, beach, clean. These are tricky because the same sound has two spellings, so you have to learn the words.\n\noa makes the long o sound, usually in the middle: boat, road, coast, float.\n\nUse the Look, Say, Cover, Write, Check routine for any tricky word: look carefully at the word, say it aloud, cover it, write it from memory, then check it letter by letter and fix any mistakes.\n\nNew Word Hoard words: plain, trail, dream, coast, beach, display.",
              "The brave sailor reached the coast, and the trail of rain led to a dream beach. Notice ai (trail, rain), ea (dream, beach) and oa (coast).",
              "ay ends a word, ai sits in the middle.",
              ("Which is spelt correctly?", ["playn", "plain", "plane (as in simple)"], 1, "'plain' has ai in the middle. (A plane is an aeroplane.)")),
    ],
    "Read this story first. 'The Lost Kite'. One windy Saturday, Sam flew his red kite at the beach. A gust snapped the string and the kite sailed away over the sea. Sam ran along the sand, then swam out to a small boat and asked the fisher to help. Together they chased the kite and caught it as it dropped onto the waves. Sam hugged his kite and promised to hold on tighter.\n\nNow work through it using each step. CHARACTERS: Sam is the main character, and the fisher is a supporting character who helps. TRAIT with evidence: Sam is determined. The text says he ran along the sand, then swam out to the boat. This shows he would not give up. SETTING: a beach on a windy Saturday. Place: the beach. Time: Saturday. Mood: lively and breezy, from words like windy and gust. CONFLICT: Sam loses his kite when the string snaps. This is character against nature, because the wind caused it. PLOT: Exposition: Sam flies his kite at the beach. Rising action: the string snaps, so the kite sails away, so Sam runs and then swims to find help. Climax: Sam and the fisher catch the kite on the waves. Falling action: Sam hugs his kite. Resolution: Sam promises to hold on tighter, so he has learned something.",
    "In your notebook, with a short story from your own book (a picture book works well): 1) Write the four questions (Who? Where and when? What goes wrong? How does it end?) and answer each. 2) List the main character and one supporting character. 3) Choose one trait for the main character and write the action or words that prove it (answer, text says, because). 4) Write the setting: place, time, mood and two clue words. 5) Name the conflict and its type. 6) Draw a mountain and write one short sentence for each of the five plot parts. 7) Use 'because' or 'so' to link two events in your plot.",
    "Choose any short story. Draw and label a plot mountain with the five parts and a sentence for each. Make a character card (name, what they want, one trait, and the evidence that proves the trait) and a setting card (place, time, mood, two clue words). Name the conflict and its type. Then answer in the three-part evidence pattern: What was the climax, and how do you know?",
    "Which part of a story was hardest for you to find: the characters, the setting, the conflict or the climax? What helped you work it out?",
    "Does my plot mountain have all five parts in order? Do I have evidence for a character trait and for the setting? Did I name the conflict and its type? Did I use answer, text says, because?",
    [
        _q("What is the setting of a story?", ["Where and when it happens", "Who is in it", "How it ends"], 0, "Setting is place and time (and mood)."),
        _q("What is the conflict?", ["The problem the characters face", "The ending", "The title"], 0, "The conflict is the problem that drives the story."),
        _q("Which part of the plot comes first?", ["Exposition", "Climax", "Resolution"], 0, "Exposition introduces the characters and setting."),
        _q("Which part of the plot is the most exciting turning point?", ["Climax", "Exposition", "Falling action"], 0, "The climax is the peak of the mountain."),
        _q("Read: 'Lena gave her seat to an older man, then carried his heavy bag to the door.' Which trait fits best?", ["Thoughtful", "Selfish", "Lazy"], 0, "Giving up her seat and carrying the bag are thoughtful actions."),
        _q("Read: 'The old bridge groaned and the floodwater roared as Jack hung on to the rail.' What is the conflict and what is the type?", ["Jack struggles against the flood (character against nature)", "Jack argues with his friend (character against character)", "Jack is shy (character against self)"], 0, "The flood is a force of nature standing in Jack's way."),
        _q("Read: 'A single light burned in the empty street, and the wind rattled the shutters.' What mood does the setting create?", ["Lonely and eerie", "Cheerful and busy", "Warm and cosy"], 0, "A single light, empty street and rattling shutters suggest loneliness."),
        _q("Which answer uses evidence best? Question: How do you know Ava was brave?", ["The text says she walked into the dark cave to save her friend, which shows she faced her fear.", "I think Ava was brave.", "Ava is a girl in the story."], 0, "It uses answer, text says, because."),
        _q("Which is spelt correctly?", ["rane", "rain", "rayn"], 1, "'rain' has ai in the middle."),
        _q("Which is spelt correctly?", ["displai", "display", "displae"], 1, "'display' ends with ay."),
    ],
    "Upload a photo of your plot mountain, character card, setting card and evidence answer.",
    "Take a film or picture book you know and map its plot onto the five-part mountain. Is there more than one climax? Does the conflict change as the story goes on?",
    [("character", "A person, animal or creature in a story."), ("trait", "A word that describes what a character is like, such as brave or kind."),
     ("setting", "Where and when a story happens."), ("mood", "The feeling a place or story gives the reader."),
     ("plot", "The order of events in a story."), ("conflict", "The problem in a story."),
     ("exposition", "The beginning: we meet the characters and the setting."), ("rising action", "Events that make the problem grow."),
     ("climax", "The most exciting turning point."), ("falling action", "What happens straight after the climax."),
     ("resolution", "How the problem is solved or changes."), ("evidence", "Words or actions from the text that prove your answer.")],
    [
        _video("The elements of a story (Khan Academy)", "Zr1xLtSMMLo",
               "Watch how a story has exposition, conflict, rising action, climax, falling action and resolution. Pause to say each part aloud.",
               "Read steps 6 and 7 aloud and draw the plot mountain.",
               ("What happens at the climax?", ["The most exciting moment", "Characters are introduced", "The story starts again"], 0, "The climax is the high point.")),
        _video("Story Elements: Characters, Setting and Events", "1M0pFLXegG0",
               "Watch how to ask Who? Where? When? What? to find the parts of a story.",
               "Ask Who, Where, When, What about a story from your own book.",
               ("Which question finds the setting?", ["Where and when?", "Who?", "Why?"], 0, "Setting is where and when.")),
        _video("Parts of a Story Song", "urA4PNn9w9Y",
               "Watch the song and notice how character, setting and plot work together.",
               "Sing or say the three parts and give one example of each from a story you know.",
               ("Which is NOT a main story element?", ["Character", "Setting", "Page number"], 2, "Page numbers do not build a story.")),
    ],
    _sort("Story element sorter", "Which story part is each clue? Tap a part, then Check.",
          ["Character", "Setting", "Conflict", "Resolution"],
          [("a clever fox", 0), ("the shy new girl", 0), ("a stormy night in the mountains", 1), ("a deserted space station", 1), ("one winter morning", 1), ("the dragon has stolen the village's water", 2), ("the boy is lost in the forest", 2), ("the team cannot agree", 2), ("the dragon returns the water and becomes a friend", 3), ("they find the way home", 3)]),
    [
        _wc("A character is shown to be kind by their ___.", ["actions", "hair", "address"], 0, "What they do shows what they are like."),
        _wc("Conflict means ___.", ["the problem", "the ending", "the setting"], 0, "Conflict is the problem."),
        _wc("A ___ is a word that describes what a character is like inside, such as brave.", ["trait", "plot", "title"], 0, "A trait describes what a character is like."),
        _wc("Which word has the long a sound spelt ay?", ["stay", "stain", "star"], 0, "stay ends in ay."),
        _wc("Which word has the long e sound spelt ea?", ["dream", "deck", "drum"], 0, "dream uses ea."),
        _wc("Which word has oa?", ["coast", "cost", "cast"], 0, "coast uses oa."),
        _wc("The ___ is where the story ends up.", ["resolution", "exposition", "setting"], 0, "Resolution is the ending."),
    ],
    [
        {"key": "story", "label": "My story", "hint": "Title and author of the story you read."},
        {"key": "chars", "label": "Characters", "hint": "Main and supporting characters, one trait each, and the action that shows it."},
        {"key": "setting", "label": "Setting", "hint": "Place, time, mood and two clue words from the text."},
        {"key": "plot", "label": "Plot mountain", "hint": "One sentence for each of the five parts, in order."},
    ],
    ["Saying the plot when the question asks for the setting, or the reverse.", "Naming a character trait without evidence from the text.", "Listing events instead of explaining how each one causes the next.", "Mixing up a trait (lasting) with a feeling (temporary).", "Confusing ai (middle of a word) and ay (end of a word) in spelling."],
    [{"title": "Story Map", "description": "Make a poster plot mountain for a favourite film.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Teach It", "description": "Explain the five parts of a plot to a family member using a story they know.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers depend on the story chosen. Check each trait has an action as evidence in the answer, text says, because pattern; the setting has place, time, mood and clue words; the conflict is named with its type; and the plot mountain has all five parts in order with cause-and-effect links. Sort: Character: clever fox, shy new girl. Setting: stormy night, deserted space station, one winter morning. Conflict: dragon steals water, lost boy, team cannot agree. Resolution: dragon returns water, find the way home.",
)

LESSONS = [W2L1]
