"""Stage 2 English, Block A (narrative writing), week 4, lessons 1 to 4.
Pass 1: lessons written and fully taught. Videos are left empty until pass 2 (find and verify).
Not yet registered in lesson_library.py. Keys use the prefix a4."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A4L1 = build(
    "s2-eng-a4-l1-characters-and-traits", "Characters and Their Traits",
    "Learn how writers build believable characters through what they look like, say, do and feel.",
    "Reading and writing: characters",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies what a text shows about a character through description, speech, actions and feelings.",
     "EN2-CWT-01": "Writes a character description that shows traits through detail.",
     "EN2-VOCAB-01": "Learns the terms protagonist, antagonist, character trait, motivation, dialogue and evidence."},
    "We are learning how writers show what a character is like, and how to build a strong character of our own.",
    ["I can name the main character and the opposing character in a story.", "I can use trait words to describe a character.", "I can find evidence in a text that shows a trait.", "I can show a trait through actions, speech and feelings.", "I can write a short character description."],
    ["protagonist", "antagonist", "character trait", "motivation", "dialogue", "evidence"],
    ["Paper or notebook", "Pencil", "A story you are reading (your parent will help you choose)"],
    "Child knows what a narrative is and has met the word trait in the planning lesson. Everything about characters is taught from the beginning.",
    "Characters are the people, animals or creatures a story is about. A good story makes us care about its characters. We feel worried when they are in danger and glad when they succeed.\n\nWriters do not just tell us 'Max was brave'. They show us what Max does, says and feels, and we work out that he is brave. This is a skill for reading and for writing.\n\nIn this lesson you will learn the types of characters, a bank of trait words, and four ways writers show character. Then you will use them to describe a character.",
    [
        _step("1", "Types of characters",
              "The PROTAGONIST is the main character. The story follows them and we usually want them to succeed. In our fox story, Pip is the protagonist.\n\nThe ANTAGONIST is the character or force that works against the protagonist. It can be a villain, a rival, a storm or even the protagonist's own fear.\n\nSupporting characters help or get in the way. They are friends, family, helpers or guides. They are not the focus, but they make the world feel real.\n\nWhen you read, ask: who is the story about? Who or what is making it hard for them?",
              "In The Three Little Pigs: protagonists are the pigs, the antagonist is the wolf.",
              "Protagonist: main character. Antagonist: works against them.",
              ("Who is the protagonist?", ["The main character", "The villain", "The author"], 0, "The protagonist is the main character.")),
        _step("2", "Trait words",
              "A CHARACTER TRAIT is a word that describes a lasting part of a character's personality. It is not how they feel for a moment. Feelings change, but traits stay.\n\nPositive traits: brave, kind, curious, loyal, clever, honest, patient, generous.\n\nNegative traits: selfish, stubborn, jealous, lazy, rude, greedy, careless, dishonest.\n\nMixed traits can be both: determined, shy, cautious, ambitious, proud.\n\nCharacters work best when they have more than one trait and a flaw. A hero who is brave but impatient is more interesting than one who is perfect.",
              "Trait: stubborn. Feeling: embarrassed. Pip is stubborn all the time, but embarrassed only when the boat gets stuck.",
              "Traits are lasting. Feelings change.",
              ("Which is a trait, not a feeling?", ["generous", "scared today", "tired right now"], 0, "Generous describes personality.")),
        _step("3", "Four ways to show character",
              "Writers can reveal a character in four main ways. Remember them as LOOK, SAY, DO, FEEL.\n\n1. What they LOOK like and wear. 'Her hair was always neat and her shoes spotless.'\n2. What they SAY and how they say it. 'I will do it myself,' he snapped.\n3. What they DO. 'She gave her lunch to the new boy.'\n4. What they FEEL and think. 'His stomach twisted with worry, but he kept walking.'\n\nThe strongest writing uses actions and speech to show a trait, rather than just naming it. This is called SHOW, DON'T TELL, and you will practise it more in a later lesson.",
              "Tell: Mia was kind. Show: Mia saved half her sandwich for the new girl, who was sitting alone.",
              "Look, say, do, feel reveal character.",
              ("Which shows a trait through action?", ["She gave her lunch to the new boy.", "She was kind.", "Kindness is good."], 0, "The action shows kindness.")),
        _step("4", "Finding evidence",
              "When you read, you can work out a character's traits by finding EVIDENCE. Evidence is a detail in the text that supports your idea.\n\nUse this pattern: The character is ___ because ___.\n\nExample: 'Zara is curious because she opens the tiny door to see what is inside.'\n\nFirst choose a trait. Then find the line or event in the text that proves it. A good answer uses a detail from the story, not just your opinion.\n\nYou can also ask: why do they do this? The reason is called their MOTIVATION. Zara's motivation is to find out who lives in the tree.",
              "Trait: determined. Evidence: Pip tried three times to push the boat free. Motivation: Pip really wants to sail the river.",
              "Trait plus because plus evidence.",
              ("What is evidence?", ["A detail from the text that supports your idea", "Your guess", "The title"], 0, "Evidence comes from the text.")),
        _step("5", "Dialogue shows personality",
              "DIALOGUE is the words characters speak. The way someone talks tells us who they are.\n\nA polite character might say, 'Excuse me, may I please borrow that?' A grumpy character might growl, 'Give it here.'\n\nWriters pick speech verbs to add detail. Instead of said, try whispered, shouted, muttered, pleaded or announced. Each tells us how the character feels.\n\nUse a new line each time a different character speaks, and put speech inside quotation marks.\n\nExample: 'I can do it alone,' muttered Pip, kicking the boat. We learn Pip is stubborn and annoyed.",
              "Same words, different character: 'No,' she whispered. 'No!' she roared.",
              "Speech and speech verbs reveal personality.",
              ("What is dialogue?", ["The words characters speak", "A kind of setting", "The ending"], 0, "Dialogue is speech.")),
        _step("6", "Write a character description",
              "Now write a short character description of 5 to 7 sentences. Use this plan.\n\n1. Choose your character and two traits.\n2. Write one sentence about how they look, with a noun group.\n3. Write one or two sentences about what they do that shows the trait.\n4. Write one line of dialogue with a strong speech verb.\n5. Write one sentence about what they feel or want.\n6. Read it and check you SHOWED the traits and did not just name them.\n\nKeep the description focused. You are introducing someone, not telling their whole life.",
              "Model: Old Mr Tran wore the same faded green cap every day. He stopped to help every stranger with a heavy bag. 'Easy does it,' he chuckled, lifting a box. He wanted the street to feel like a family.",
              "Trait, look, action, dialogue, feeling.",
              ("How many traits should you choose?", ["Two", "Fifty", "None"], 0, "Two traits keep the description focused.")),
    ],
    "Model answers. Protagonist: the main character the story follows. Antagonist: the person or force working against them. Trait for 'She stayed behind to clean the whole kitchen alone': helpful or hard-working. Evidence sentence: Zara is curious because she opens the tiny door to see inside. Description: Tilly, the small girl with the muddy boots and wild curls, never gave up on a puzzle. She sat for an hour with one piece in her hand. 'It has to fit somewhere,' she muttered. She wanted to finish it before dinner.",
    "1) Match four characters to protagonist or antagonist. 2) Sort ten words into trait or feeling. 3) Write three sentences that show a trait through action. 4) Write an evidence sentence for a character in a story of your parent's choice. 5) Write one line of dialogue with a speech verb. 6) Write your 5 to 7 sentence character description.",
    "Write a 5 to 7 sentence description of a character of your own that shows two traits through look, say, do and feel. Upload a photo of your writing.",
    CHECK,
    "Did I choose two traits? Did I show them through actions or speech, not just name them? Did I use a noun group to describe how they look? Is there a line of dialogue in quotation marks with a strong speech verb? Is it 5 to 7 sentences?",
    [
        _q("Who is the protagonist?", ["The main character", "The helper", "The author"], 0, "The protagonist is the main character."),
        _q("The antagonist is...", ["someone or something working against the main character", "the narrator", "the setting"], 0, "The antagonist makes the problem."),
        _q("Which is a trait?", ["stubborn", "hungry", "sleepy at the moment"], 0, "Stubborn is a lasting quality."),
        _q("Which shows a trait by action?", ["He shared his toys with everyone.", "He was generous.", "Generosity is nice."], 0, "The action shows the trait."),
        _q("Evidence in a text is...", ["a detail that supports your idea", "your opinion", "the page number"], 0, "Evidence comes from the text."),
        _q("Which speech verb shows anger?", ["snapped", "whispered", "giggled"], 0, "Snapped is sharp and angry."),
        _q("Dialogue goes inside...", ["quotation marks", "brackets", "capital letters"], 0, "Speech uses quotation marks."),
        _q("Motivation is...", ["why a character does something", "where they live", "their age"], 0, "Motivation is the reason."),
    ],
    "Upload a photo of your character description.",
    "Take the same character and write a second paragraph showing them in a different situation. Do they act in the same way? Explain how their traits stay the same.",
    [("protagonist", "The main character of a story."), ("antagonist", "The character or force that works against the main character."), ("character trait", "A word describing a lasting part of someone's personality."),
     ("motivation", "The reason a character does something."), ("dialogue", "The words characters speak."), ("evidence", "A detail from a text that supports an idea.")],
    [],
    _sort("Trait or feeling sorter", "Is each word a lasting trait or a passing feeling? Tap a group, then Check.",
          ["Trait", "Feeling"],
          [("loyal", 0), ("stubborn", 0), ("generous", 0), ("curious", 0), ("nervous today", 1), ("embarrassed", 1), ("excited right now", 1), ("disappointed", 1)]),
    [
        _wc("The main character is the ___.", ["protagonist", "antagonist", "setting"], 0, "The protagonist is the main character."),
        _wc("Words characters speak are called ___.", ["dialogue", "plot", "theme"], 0, "Dialogue is speech."),
        _wc("A lasting part of personality is a ___.", ["trait", "mood", "setting"], 0, "Traits are lasting."),
        _wc("Which is spelt correctly?", ["protagonist", "protaganist", "protagonest"], 0, "Protagonist ends -ist."),
        _wc("Which is spelt correctly?", ["antagonist", "antagonest", "antaganist"], 0, "Antagonist has gon in the middle."),
    ],
    [
        {"key": "types", "label": "Protagonist and antagonist", "hint": "Who is each in a story of your parent's choice?"},
        {"key": "evidence", "label": "Evidence sentence", "hint": "The character is ___ because ___."},
        {"key": "dialogue", "label": "Dialogue line", "hint": "One line of speech with a strong speech verb."},
        {"key": "description", "label": "Character description", "hint": "5 to 7 sentences showing two traits."},
    ],
    ["Confusing a trait with a feeling.", "Telling the trait instead of showing it.", "Giving the character too many traits.", "Using said every time.", "Forgetting quotation marks around speech."],
    [{"title": "Trait Detective", "description": "Choose a character from a book you are reading and find three pieces of evidence for two traits. Write a because sentence for each.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that two traits are chosen, traits are shown through action, speech or feeling rather than only named, a noun group describes the character, dialogue has quotation marks and a strong speech verb, and the description is 5 to 7 sentences. Sorter: Trait: loyal, stubborn, generous, curious. Feeling: nervous today, embarrassed, excited right now, disappointed.",
)

A4L2 = build(
    "s2-eng-a4-l2-writing-a-strong-opening", "Writing a Strong Opening",
    "Learn the tricks writers use to hook a reader in the first few lines.",
    "Writing: narrative openings",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01"],
    {"EN2-CWT-01": "Primary. Drafts an orientation that hooks the reader and establishes character, setting and time.",
     "EN2-RECOM-01": "Analyses how published openings catch the reader's attention.",
     "EN2-VOCAB-01": "Learns the terms hook, orientation, flashback, onomatopoeia, rhetorical question and sensory detail."},
    "We are learning how to write an opening that hooks the reader and sets up the story.",
    ["I can say what a hook is.", "I can name five ways to start a story.", "I can include who, where and when in an opening.", "I can use sensory detail.", "I can write and improve my own opening."],
    ["hook", "orientation", "sensory detail", "onomatopoeia", "rhetorical question", "dialogue"],
    ["Paper or notebook", "Pencil", "Your story map from last week", "A few story openings (your parent will help you choose)"],
    "Child knows the stages of a narrative and has made a story map. Opening techniques are taught from the beginning.",
    "The first few lines of a story are the most important. A reader decides very quickly whether to keep reading. A strong opening grabs attention, which we call a HOOK, and also does the work of the ORIENTATION by telling us who, where and when.\n\nMany beginning writers start with 'One day...' or 'My name is...'. There are far more exciting ways to begin.\n\nIn this lesson you will learn five ways to hook a reader, study how to blend in the orientation details, and then write and improve your own opening.",
    [
        _step("1", "What makes a hook?",
              "A hook is the first line or two that makes the reader curious. It makes them ask a question in their head, such as 'What is happening?' or 'What will happen next?'.\n\nA weak start: 'One day a girl went to the park.' We have no reason to care.\n\nA hook: 'The swing was moving, but nobody was on it.' Now we want to know why.\n\nGood hooks create a feeling, such as mystery, danger, humour or surprise. They are short and specific. They do not explain everything at once.\n\nWhen you read a book, look at the very first sentence. Ask: does this make me want to read on? Why?",
              "Weak: It was a morning. Strong: The morning the sun forgot to rise, Ella knew something was wrong.",
              "A hook makes the reader curious.",
              ("What does a hook do?", ["Makes the reader curious", "Ends the story", "Names the characters"], 0, "A hook makes the reader want to read on.")),
        _step("2", "Start with action or sound",
              "One way to start is right in the middle of the action. Do not explain first. Drop the reader into the moment.\n\n'Pip dived under the fallen log as the thunder cracked overhead.'\n\nAnother way is to start with a sound. ONOMATOPOEIA is a word that sounds like what it means, such as crash, buzz, splash or thud.\n\n'Crash! The old gate slammed shut behind her.'\n\nAction and sound openings are fast and exciting. After the hook, add a sentence or two that tell us who and where, so the reader is not lost.",
              "Action: Max sprinted down the hallway, clutching the glowing stone. Sound: Thud, thud, thud. Something was knocking on the cellar door.",
              "Start with action or a sound, then add who and where.",
              ("Which is onomatopoeia?", ["splash", "quiet", "swimming"], 0, "Splash sounds like what it means.")),
        _step("3", "Start with a question or speech",
              "You can open with a RHETORICAL QUESTION, which is a question the writer asks without needing an answer. It makes the reader think.\n\n'Have you ever wondered what lives at the bottom of a pond?'\n\nYou can also open with DIALOGUE, so we hear a character at once.\n\n'Don't touch that button,' whispered Leo.\n\nSpeech makes the story feel alive, and the reader wonders who is speaking and why. Be careful not to start with too much talking, though. After a line or two, tell the reader where we are.\n\nWhich opening suits your story? A funny story might start with speech. A mystery might start with a question.",
              "Question: What would you do if your shadow ran away? Speech: 'You are late again,' said the old clock.",
              "A question or speech makes the reader curious.",
              ("A question the writer does not need answered is...", ["rhetorical", "literal", "silent"], 0, "Rhetorical questions make the reader think.")),
        _step("4", "Start with setting and senses",
              "You can open with a vivid description of the setting. This works best when you use SENSORY DETAIL, which is detail about what can be seen, heard, smelt, felt or tasted.\n\n'The cave smelt of damp stone and old smoke, and water dripped somewhere in the dark.'\n\nThis creates a mood. We feel the place before anything has happened.\n\nKeep it to one or two sentences. Long description at the start can bore the reader. Pick the two or three best details and then introduce the character.\n\nChoose strong nouns and verbs, not just adjectives. 'The wind hissed through the cracks' is stronger than 'The wind was very loud'.",
              "Senses: The kitchen smelt of cinnamon and burnt toast. Mum's radio crackled in the corner.",
              "Use two or three sensory details to create mood.",
              ("Sensory detail is about...", ["what you can see, hear, smell, feel or taste", "how many characters there are", "spelling"], 0, "Sensory detail uses the five senses.")),
        _step("5", "Include who, where and when",
              "A hook is not enough. The opening also has to work as an ORIENTATION. By the end of the first paragraph the reader should know three things.\n\nWHO the main character is.\nWHERE the story is set.\nWHEN it takes place, such as a time of day, season or era.\n\nYou can do this without writing a boring list. Slip the details into your sentences.\n\nInstead of 'It was winter. Sam lived in a town. He was ten,' try: 'On the coldest night of the winter, ten-year-old Sam crept through the sleeping town with a torch in his pocket.'\n\nOne sentence gave us who, where, when and a hint of a problem.",
              "Check: Who? Sam. Where? A sleeping town. When? A winter night. Hint: why is he creeping?",
              "Work who, where and when into the hook.",
              ("What three things should an opening tell us?", ["Who, where and when", "Why, how and what", "Only the title"], 0, "The orientation answers who, where and when.")),
        _step("6", "Write and improve your opening",
              "Now write an opening of 3 to 5 sentences for the story on your map.\n\n1. Choose one hook technique: action, sound, question, speech or senses.\n2. Write the hook sentence first.\n3. Add one or two sentences giving who, where and when.\n4. Add one noun group and one strong verb.\n5. Read it aloud. Would you keep reading?\n6. Try a second version with a different technique and choose the better one.\n\nDo not give away the problem or ending. Leave the reader wanting more.",
              "Version one: Splash! Pip stumbled into the creek. Version two: Pip had been building the boat for three weeks, and today it would finally float. Version two feels calmer, so choose the one that suits the story.",
              "Hook first, orientation next, try two versions.",
              ("Should the opening give away the ending?", ["No", "Yes", "Only the first line"], 0, "Leave the reader curious.")),
    ],
    "Model answers. Hook: a first line that makes the reader curious. Five techniques: action, sound, question, speech, senses. Opening A (sound): Thud, thud, thud. Something was knocking on the cellar door of the old farmhouse, and Zara was home alone. Opening B (senses): The cave smelt of damp stone and old smoke. Eleven-year-old Ravi pressed a hand against the wall and felt it humming. Both give who, where and a hint of a problem.",
    "1) Read three openings your parent chooses and say which hook each uses. 2) Rewrite 'One day a boy went to the beach' as a stronger hook. 3) Write one opening for each of three techniques. 4) Underline who, where and when in one opening. 5) Write the opening for your own story plan. 6) Write a second version and choose the better one.",
    "Write two openings of 3 to 5 sentences for your story using different hook techniques, and circle your favourite. Upload a photo of your writing.",
    CHECK,
    "Does my first line make the reader curious? Did I tell who, where and when? Did I use sensory detail or a strong verb? Did I avoid starting with 'One day'? Did I leave out the ending? Did I try two versions?",
    [
        _q("What is a hook?", ["An opening that makes the reader curious", "The last line", "A kind of noun"], 0, "A hook grabs attention."),
        _q("Which is onomatopoeia?", ["crash", "gentle", "running"], 0, "Crash sounds like its meaning."),
        _q("Which is a rhetorical question?", ["Have you ever wondered what lives in the dark?", "What time is it, Dad?", "Where is my pencil?"], 0, "It makes the reader think."),
        _q("Which opening uses sensory detail?", ["The kitchen smelt of cinnamon and burnt toast.", "It was a kitchen.", "One day I cooked."], 0, "It uses smell."),
        _q("The orientation tells us...", ["who, where and when", "the ending", "the theme"], 0, "Orientation sets the scene."),
        _q("Which is a weak opening?", ["One day a girl went to the park.", "The swing was moving, but nobody was on it.", "Crash! The gate slammed."], 0, "The first has no hook."),
        _q("How long should a setting opening be?", ["One or two sentences", "Five pages", "One word"], 0, "Keep it short."),
        _q("After a hook, you should...", ["tell who and where", "end the story", "start a new story"], 0, "Orient the reader."),
    ],
    "Upload a photo of your two openings.",
    "Collect the first lines of five books of your choice and sort them by hook technique. Which technique do you like best, and why?",
    [("hook", "An opening line that makes the reader curious."), ("orientation", "The part of a story that tells who, where and when."), ("sensory detail", "Detail about what can be seen, heard, smelt, felt or tasted."),
     ("onomatopoeia", "A word that sounds like its meaning, such as splash."), ("rhetorical question", "A question asked to make the reader think, not to get an answer."), ("dialogue", "The words characters speak.")],
    [],
    _sort("Hook sorter", "Which technique does each opening use? Tap a technique, then Check.",
          ["Action or sound", "Question or speech", "Senses"],
          [("Crash! The door burst open.", 0), ("Max sprinted down the hallway with the glowing stone.", 0), ("Have you ever heard your shadow whisper?", 1), ("'Don't touch that button,' whispered Leo.", 1), ("The cave smelt of damp stone and old smoke.", 2), ("Cold rain drummed on the tin roof and the room smelt of wet dog.", 2)]),
    [
        _wc("An opening that grabs attention is a ___.", ["hook", "theme", "title"], 0, "A hook grabs attention."),
        _wc("A word that sounds like its meaning is ___.", ["onomatopoeia", "alliteration", "setting"], 0, "Onomatopoeia imitates sounds."),
        _wc("Detail about the five senses is ___ detail.", ["sensory", "simple", "silent"], 0, "Sensory relates to the senses."),
        _wc("Which is spelt correctly?", ["orientation", "orrientation", "orientashun"], 0, "Orientation ends -tion."),
        _wc("Which is spelt correctly?", ["rhetorical", "retorical", "rhetorrical"], 0, "Rhetorical begins rh."),
    ],
    [
        {"key": "analysis", "label": "Opening analysis", "hint": "Which hook did each of three openings use?"},
        {"key": "rewrite", "label": "Rewritten hook", "hint": "A stronger start for 'One day a boy went to the beach'."},
        {"key": "versionA", "label": "Opening version one", "hint": "3 to 5 sentences with one technique."},
        {"key": "versionB", "label": "Opening version two", "hint": "A different technique, and say which you prefer."},
    ],
    ["Starting with 'One day' or 'My name is'.", "Giving the whole plot away in the first paragraph.", "Writing too much description before anything happens.", "Forgetting who, where and when.", "Using a hook that does not match the story."],
    [{"title": "Opening Remix", "description": "Take the opening of a story you know and rewrite it with a different hook technique.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the first line creates curiosity, who, where and when are included, at least one sensory detail or strong verb is used, the opening does not start with One day, and it does not give away the ending. Sorter: Action or sound: Crash! The door burst open; Max sprinted down the hallway. Question or speech: Have you ever heard your shadow whisper; Dont touch that button. Senses: The cave smelt of damp stone; Cold rain drummed on the tin roof.",
)

A4L3 = build(
    "s2-eng-a4-l3-verbs-and-verb-tense", "Verbs and Verb Tense",
    "Choose powerful verbs and keep your tense consistent so your writing is clear and strong.",
    "Language: verbs and tense",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Uses action verbs, verb groups and consistent past tense in narrative writing.",
     "EN2-VOCAB-01": "Learns the terms verb, action verb, saying verb, thinking verb, being verb, tense and verb group.",
     "EN2-RECOM-01": "Identifies verbs and tense when reading to follow when events happen."},
    "We are learning to identify verbs, choose strong ones, and keep our tense consistent in a narrative.",
    ["I can say what a verb is.", "I can tell action, saying, thinking and being verbs apart.", "I can use past, present and future tense.", "I can make a verb group with a helping verb.", "I can keep my narrative in the past tense."],
    ["verb", "action verb", "saying verb", "thinking verb", "being verb", "tense", "verb group"],
    ["Paper or notebook", "Pencil", "A paragraph from a story you have read"],
    "Child knows what a verb is as a doing word in a basic way. Verb types, tense and verb groups are taught from the beginning.",
    "A VERB is a word that tells what someone or something does, thinks, says or is. Every sentence needs at least one verb. Without a verb, it is not a full sentence.\n\nIn a narrative, verbs drive the action. The right verb can replace three or four weaker words. 'Ran' is fine, but 'sprinted', 'bolted' or 'scrambled' tell us much more.\n\nVerbs also show TENSE, which tells us when something happens. In this lesson you will learn the main kinds of verbs, how tense works, and how to keep it consistent.",
    [
        _step("1", "What is a verb?",
              "A verb is the word that tells what is happening in a sentence. Ask: what is the subject doing, thinking, saying or being?\n\n'Ella kicked the ball.' Kicked is the verb.\n'The baby slept.' Slept is the verb.\n'The sky is grey.' Is is the verb.\n\nA trick: try putting 'I' or 'we' before the word. 'I jump' works, so jump is a verb. 'I table' does not.\n\nSentences can have more than one verb. 'Pip jumped and landed safely.' Jumped and landed are both verbs.",
              "Find the verbs: The dog barked and chased the cat. Barked, chased.",
              "A verb tells what someone does, thinks, says or is.",
              ("Which word is a verb?", ["leapt", "leaf", "lovely"], 0, "Leapt tells what someone did.")),
        _step("2", "Four kinds of verbs",
              "There are four main kinds of verb.\n\nACTION verbs tell what someone does. Examples: run, climb, throw, crept, dived.\n\nSAYING verbs show how someone speaks. Examples: whispered, shouted, replied, muttered.\n\nTHINKING and FEELING verbs show what happens inside. Examples: wondered, knew, hoped, feared, loved.\n\nBEING and HAVING verbs say what something is or has. Examples: is, was, are, were, has, had, seems.\n\nGood narratives use a mix. Action verbs move the plot along, saying verbs show character, thinking verbs show feelings, and being verbs set the scene.",
              "Pip crept (action) to the log and whispered (saying). He wondered (thinking) if the boat was safe. It was (being) too heavy.",
              "Action, saying, thinking and being verbs.",
              ("Which is a saying verb?", ["muttered", "jumped", "was"], 0, "Muttered shows how someone spoke.")),
        _step("3", "Choose strong verbs",
              "Weak verbs like went, got, looked and said often need more words to explain. Strong verbs say it all at once.\n\nwent: marched, crept, trudged, raced, strolled\nlooked: peered, glanced, stared, spotted, glared\nsaid: whispered, bellowed, replied, pleaded, snapped\nhit: smashed, tapped, thumped, struck\n\nChoose the verb that fits the mood. 'Crept' is sneaky. 'Stomped' is angry. 'Skipped' is happy.\n\nDo not use a fancy verb just because it is fancy. Choose the one that gives the best picture.",
              "Weak: She went to the door slowly. Strong: She crept to the door.",
              "Strong verbs replace weak verbs and extra words.",
              ("Which is a stronger verb than 'went'?", ["marched", "go", "did"], 0, "Marched gives a clearer picture.")),
        _step("4", "Past, present and future tense",
              "TENSE tells us when something happens.\n\nPAST tense: it already happened. 'Pip jumped.' Many past tense verbs end in -ed, but some are irregular: ran, saw, went, took.\n\nPRESENT tense: it is happening now. 'Pip jumps.'\n\nFUTURE tense: it will happen later. 'Pip will jump.'\n\nMost narratives are told in the PAST tense, as if the events have already happened. 'The wind howled and the door creaked open.'\n\nSome stories use present tense for a fast, immediate feeling. 'The wind howls and the door creaks open.' Whichever you choose, you must stay with it.",
              "Past: She opened the box. Present: She opens the box. Future: She will open the box.",
              "Tense shows when it happens. Narratives are usually past tense.",
              ("Which sentence is past tense?", ["The boy climbed the tree.", "The boy climbs the tree.", "The boy will climb the tree."], 0, "Climbed is past tense.")),
        _step("5", "Irregular verbs and verb groups",
              "Many common verbs do not take -ed in the past tense. They are IRREGULAR.\n\nrun, ran. see, saw. go, went. take, took. buy, bought. think, thought. fall, fell. give, gave. catch, caught.\n\nWatch for mistakes such as 'runned', 'seed' and 'goed'. Say the sentence aloud. If it sounds wrong, check the verb.\n\nA VERB GROUP is a main verb with a helping verb before it. Examples: was running, had finished, will climb, could see, might have fallen.\n\n'Pip was building a boat.' The verb group was building tells us the action was in progress.\n'The storm had passed.' Had passed shows it was finished earlier.\n\nThe helping verb carries the tense.",
              "Wrong: Yesterday I runned home. Right: Yesterday I ran home. Group: Zara was walking when she saw the door.",
              "Learn irregular past forms. A verb group has a helping verb.",
              ("Which is the correct past tense of 'catch'?", ["caught", "catched", "catchd"], 0, "Catch is irregular.")),
        _step("6", "Keep your tense consistent",
              "A common mistake is switching tense by accident in the middle of a story. 'Pip walked to the river and sees the boat.' Walked is past and sees is present.\n\nFix it: 'Pip walked to the river and saw the boat.'\n\nHow to check your work:\n1. Decide your tense before you start, usually past.\n2. Underline every verb when you proofread.\n3. Check each underlined verb matches.\n\nThere is one exception. Dialogue can use any tense because it is what the character says. 'I will go home,' she said. Said is past, will go is future, and that is fine.\n\nConsistent tense makes your writing clear and professional.",
              "Mixed: The wolf huffed and puffs. Fixed: The wolf huffed and puffed.",
              "Pick a tense and keep it, except inside dialogue.",
              ("Which tense do most narratives use?", ["Past", "Future", "None"], 0, "Narratives are mostly past tense.")),
    ],
    "Model answers. Verbs: The dog barked and chased the cat (barked, chased). Strong verb swaps: went to crept, looked to peered, said to pleaded. Past tense: ran, saw, went, took, bought, thought. Verb groups: was running, had finished, will climb. Fixed sentence: Pip walked to the river and saw the boat. Short paragraph: The storm broke over Lantern Forest. Pip crouched beneath a log and listened. He had never heard thunder so loud.",
    "1) Underline the verbs in five sentences. 2) Sort ten verbs into action, saying, thinking and being. 3) Replace weak verbs with strong ones in five sentences. 4) Write the past tense of ten verbs, including irregular ones. 5) Fix five sentences that mix tense. 6) Write a paragraph of five sentences in past tense and underline each verb.",
    "Write a five-sentence narrative paragraph in the past tense using at least four strong verbs and one verb group. Underline every verb. Upload a photo of your writing.",
    CHECK,
    "Did I stay in the past tense? Did I use at least four strong verbs? Did I use one verb group? Did I spell the irregular verbs correctly? Did I underline every verb? Does each sentence make sense?",
    [
        _q("What is a verb?", ["A word that tells what someone does, thinks, says or is", "A naming word", "A describing word"], 0, "A verb is the action or state word."),
        _q("Which is a thinking verb?", ["wondered", "shouted", "kicked"], 0, "Wondered is something done in the mind."),
        _q("Which is a stronger verb than 'looked'?", ["peered", "did", "was"], 0, "Peered gives a clearer picture."),
        _q("Which sentence is present tense?", ["She opens the box.", "She opened the box.", "She will open the box."], 0, "Opens is present tense."),
        _q("What is the past tense of 'run'?", ["ran", "runned", "running"], 0, "Run is irregular."),
        _q("Which is a verb group?", ["was building", "big boat", "very quickly"], 0, "A helping verb plus a main verb."),
        _q("Which sentence mixes tense?", ["Pip walked to the river and sees the boat.", "Pip walked to the river and saw the boat.", "Pip walks to the river and sees the boat."], 0, "Walked is past and sees is present."),
        _q("Tense can change inside...", ["dialogue", "the title", "the first word"], 0, "Characters can speak in any tense."),
    ],
    "Upload a photo of your past tense paragraph with verbs underlined.",
    "Choose a page from a book of your choice and find ten verbs. Sort them into action, saying, thinking and being, and say which kind the author uses most.",
    [("verb", "A word that tells what someone does, thinks, says or is."), ("action verb", "A verb that tells what someone does."), ("saying verb", "A verb that shows how someone speaks."),
     ("thinking verb", "A verb that shows what someone thinks or feels."), ("being verb", "A verb that says what something is or has."), ("tense", "The form of a verb that shows when something happens."), ("verb group", "A main verb with a helping verb, such as was running.")],
    [],
    _sort("Verb type sorter", "What kind of verb is each word? Tap a type, then Check.",
          ["Action", "Saying", "Thinking", "Being"],
          [("sprinted", 0), ("climbed", 0), ("whispered", 1), ("bellowed", 1), ("wondered", 2), ("hoped", 2), ("was", 3), ("seems", 3)]),
    [
        _wc("A word that tells what someone does is a ___.", ["verb", "noun", "article"], 0, "Verbs tell what is happening."),
        _wc("The form of a verb that shows when is called ___.", ["tense", "theme", "title"], 0, "Tense shows time."),
        _wc("The past tense of 'think' is ___.", ["thought", "thinked", "thunk"], 0, "Think is irregular."),
        _wc("Which is spelt correctly?", ["caught", "cought", "caugt"], 0, "Caught has augh."),
        _wc("Which is spelt correctly?", ["bought", "bougt", "bawt"], 0, "Bought has ough."),
    ],
    [
        {"key": "verbs", "label": "Verbs I found", "hint": "Verbs from five sentences."},
        {"key": "strong", "label": "Strong verb swaps", "hint": "Five weak verbs replaced with strong ones."},
        {"key": "tense", "label": "Tense fixes", "hint": "Five mixed sentences corrected."},
        {"key": "paragraph", "label": "Past tense paragraph", "hint": "Five sentences with verbs underlined."},
    ],
    ["Switching between past and present tense.", "Adding -ed to irregular verbs, such as runned.", "Using the same weak verb again and again.", "Forgetting the helping verb in a verb group.", "Underlining nouns instead of verbs."],
    [{"title": "Verb Makeover", "description": "Take a paragraph you wrote earlier and swap at least five weak verbs for strong ones, then check the tense.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that verbs are correctly underlined, strong verbs replace weak ones, irregular past tense forms are spelt correctly, the paragraph stays in the past tense apart from dialogue, and at least one verb group is used. Sorter: Action: sprinted, climbed. Saying: whispered, bellowed. Thinking: wondered, hoped. Being: was, seems.",
)

A4L4 = build(
    "s2-eng-a4-l4-handwriting-joining-letters", "Handwriting: Joining Letters Fluently",
    "Practise the joins that make your writing fast, neat and easy to read.",
    "Handwriting: joined writing",
    ["EN2-HANDW-01", "EN2-SPELL-01", "EN2-CWT-01"],
    {"EN2-HANDW-01": "Primary. Forms and joins letters fluently with correct size, slope and spacing.",
     "EN2-SPELL-01": "Practises accurate spelling of common words while handwriting.",
     "EN2-CWT-01": "Presents written work neatly and legibly."},
    "We are learning how to join letters so our handwriting is fluent, neat and easy to read.",
    ["I can sit and hold my pencil comfortably.", "I can make the four main kinds of joins.", "I can keep my letters the same size and slope.", "I can space words evenly.", "I can copy a passage in neat joined writing."],
    ["join", "ascender", "descender", "slope", "spacing", "fluent", "legible"],
    ["Lined paper or handwriting book", "A sharp pencil", "An eraser", "A sentence or short passage chosen by your parent"],
    "Child can form all letters and write short sentences by hand. Joining and the common joins are taught from the beginning.",
    "Handwriting is a skill that gets easier with practice. Joined writing is faster than printing because the pencil stays on the page for longer, and it helps you write long pieces without getting tired.\n\nThe goal is not perfect writing. The goal is LEGIBLE writing, which means someone else can read it easily, and FLUENT writing, which means it flows smoothly.\n\nIn this lesson you will check your posture, learn the main joins, practise size, slope and spacing, and then copy a passage carefully.",
    [
        _step("1", "Posture and pencil grip",
              "Good handwriting starts with your body.\n\nSit with your back straight and feet flat on the floor. Keep both forearms on the table. Your paper should be tilted slightly. Right-handed writers tilt the page to the left. Left-handed writers tilt it to the right.\n\nHold the pencil between your thumb and first finger, resting on your middle finger. Keep a loose grip, not a squeeze. Your fingers should not turn white.\n\nHold the pencil about two finger-widths above the tip. Rest your hand lightly on the side. Take a breath and shake out your hand if it feels tight.\n\nWarm up by drawing loops, waves and zig-zags across a line.",
              "Checklist: back straight, feet flat, relaxed grip, paper tilted. Warm-up: a row of loops and a row of waves.",
              "Sit tall, relax your grip, warm up first.",
              ("How tight should you grip the pencil?", ["Loosely", "As tight as possible", "With a fist"], 0, "A loose grip prevents tired hands.")),
        _step("2", "Letter formation and the baseline",
              "Before joining, each letter must be formed correctly. Most letters start at the top and move down and around. Start in the right place every time.\n\nWrite on the BASELINE, the line your letters sit on. Short letters, like a, c, e, m, n, o, r, s, u, v, w, x and z, fit in the middle zone.\n\nASCENDERS go up above the middle: b, d, f, h, k, l, t. DESCENDERS go below the line: g, j, p, q, y.\n\nLetters with tall parts should all reach the same height. Tails should drop the same distance below. Even sizing makes your writing look tidy at a glance.",
              "Ascenders: b, d, f, h, k, l, t. Descenders: g, j, p, q, y. Middle zone: a, c, e, i, m, n, o, r, s, u, v, w, x, z.",
              "Sit letters on the baseline and keep sizes even.",
              ("Which letter has a descender?", ["g", "b", "a"], 0, "G drops below the line.")),
        _step("3", "The main joins",
              "Joins are small connecting strokes between letters. Four kinds are the most useful.\n\n1. DIAGONAL join from the baseline up to the next letter. Used in words like in, it, up, ill, ham.\n2. HORIZONTAL join, a flat stroke, from letters like o, r, v and w. Used in words like on, was, ran, we.\n3. Join to a round letter such as a, c, d, g, o, q. Go back over the top of the first letter, as in 'ad', 'ca', 'go'.\n4. Join to a tall letter such as b, h, k, l, t. Make the stroke go up to the tall part, as in 'at', 'ell', 'ab'.\n\nSome letters are not joined, such as the next letter after j, y, g and others in your school's style. Follow the style your parent uses, and be consistent.\n\nPractise joins in small groups: 'ai', 'ea', 'ou', 'th', 'ing'.",
              "Practise: in, on, at, ed, ing. Then words: nothing, rolling, wonder.",
              "Diagonal, horizontal, to round, to tall.",
              ("What is a join?", ["A connecting stroke between letters", "A kind of paper", "A pencil"], 0, "Joins connect letters.")),
        _step("4", "Size, slope and spacing",
              "Three things make writing look neat.\n\nSIZE: keep all the middle letters the same height and all ascenders the same height. Do not make words grow bigger or smaller across a line.\n\nSLOPE: all letters should lean the same way and the same amount. Draw light parallel slope lines if it helps. Do not mix upright and slanted letters.\n\nSPACING: leave a gap about the width of a small letter 'o' between words. Letters inside a word should be close, and words should be clearly apart. Too much or too little space makes reading harder.\n\nCheck by holding your page at arm's length. Does it look even and tidy?",
              "Spacing test: put your finger or a small 'o' between words. If it fits, the gap is right.",
              "Same size, same slope, even spaces.",
              ("How big should the gap between words be?", ["About the width of a small o", "As big as a hand", "No gap"], 0, "A letter-o gap is a good guide.")),
        _step("5", "Practise common word patterns",
              "Practise joined writing on patterns that appear in lots of words.\n\n-ing: sing, running, jumping.\n-ed: walked, helped, played.\n-ight: night, light, right.\n-ful: careful, helpful, hopeful.\n-ness: kindness, darkness.\n\nWrite each pattern three times, then write two words using it. Say the word aloud as you write, and check your spelling at the same time.\n\nWork slowly at first. Speed comes later. Aim for smooth, steady strokes, not scribbles. If a join goes wrong, rub it out and try again, because your hand learns the right movement through correct practice.",
              "One practice line: night night night, light, fright. Then: The bright light shone all night.",
              "Practise patterns slowly, then in words.",
              ("Should you write fast at first?", ["No, go slowly and correctly", "Yes, as fast as possible", "Only on Fridays"], 0, "Accuracy comes before speed.")),
        _step("6", "Copy a passage neatly",
              "Now copy a short passage of 4 to 6 sentences chosen by your parent. It could be from a favourite book or a poem.\n\nFollow these steps.\n1. Warm up with loops and waves.\n2. Read the passage twice. Notice the capital letters and punctuation.\n3. Write the first line slowly with joined letters.\n4. Keep your size, slope and spacing the same all the way down the page.\n5. Check the spelling against the original.\n6. Compare your first line and last line. Do they look the same?\n\nPick your neatest line and mark it with a star. This shows your best work so you can aim to match it next time.",
              "Marking your work: a star next to the neatest line, and a small tick above any join you want to practise again.",
              "Read, copy slowly, check, star your best line.",
              ("What should you do after copying?", ["Check spelling and mark your neatest line", "Throw it away", "Start again without looking"], 0, "Checking and marking helps you improve.")),
    ],
    "Model answers. Ascenders: b, d, f, h, k, l, t. Descenders: g, j, p, q, y. Check that letters sit on the baseline, ascenders are the same height, slope is consistent, spaces between words are about the width of a small o, and common joins such as in, on, at, ed and ing are smooth. The copied passage should match the original with correct spelling and punctuation.",
    "1) Check your posture and warm up with loops and waves. 2) Write a line of each practice join: in, on, at, ed, ing. 3) Write three lines of the patterns -ing, -ed, -ight. 4) Write the sentence 'The bright light shone all night' three times, getting neater each time. 5) Copy a passage of 4 to 6 sentences. 6) Star your neatest line.",
    "Copy a short passage of 4 to 6 sentences in joined writing, star your neatest line, and upload a photo.",
    CHECK,
    "Do my letters sit on the baseline? Are tall letters and short letters the same size throughout? Do all letters slope the same way? Are spaces between words even? Are my joins smooth? Is my spelling the same as the original? Did I star my neatest line?",
    [
        _q("Where should the page be tilted for a right-handed writer?", ["To the left", "To the right", "Not at all"], 0, "Right-handed writers tilt the page left."),
        _q("Which letter has an ascender?", ["d", "a", "u"], 0, "D has a tall stroke."),
        _q("Which letter has a descender?", ["p", "o", "e"], 0, "P drops below the line."),
        _q("A join is...", ["a connecting stroke between letters", "a gap", "a mistake"], 0, "Joins connect letters."),
        _q("Legible writing is writing that...", ["others can read easily", "is very fast", "is very small"], 0, "Legible means readable."),
        _q("Spaces between words should be about...", ["the width of a small o", "a whole line", "zero"], 0, "A small o is a good guide."),
        _q("Slope should be...", ["the same throughout", "different each word", "upright then slanted"], 0, "Keep the slope consistent."),
        _q("Which comes first when learning to join?", ["Accuracy", "Speed", "Decoration"], 0, "Accuracy first, then speed."),
    ],
    "Upload a photo of your copied passage.",
    "Write a short note to someone in your family in your neatest joined writing and give it to them.",
    [("join", "A connecting stroke between two letters."), ("ascender", "A letter part that goes up above the middle zone."), ("descender", "A letter part that goes down below the baseline."),
     ("slope", "The lean of your letters."), ("spacing", "The gaps between letters and words."), ("fluent", "Smooth and flowing."), ("legible", "Easy for others to read.")],
    [],
    _sort("Letter shape sorter", "Does each letter have an ascender, a descender or neither? Tap a group, then Check.",
          ["Ascender", "Descender", "Neither"],
          [("b", 0), ("h", 0), ("t", 0), ("g", 1), ("y", 1), ("p", 1), ("a", 2), ("m", 2), ("o", 2)]),
    [
        _wc("A connecting stroke between letters is a ___.", ["join", "gap", "dot"], 0, "Joins connect letters."),
        _wc("Writing that others can read easily is ___.", ["legible", "tiny", "loud"], 0, "Legible means readable."),
        _wc("Letters like b, d and h have an ___.", ["ascender", "descender", "accent"], 0, "Ascenders go up."),
        _wc("Which is spelt correctly?", ["legible", "legibel", "ledgible"], 0, "Legible ends -ible."),
        _wc("Which is spelt correctly?", ["fluent", "flooent", "fluant"], 0, "Fluent has ue in the middle."),
    ],
    [
        {"key": "warmup", "label": "Warm-up and joins", "hint": "Loops, waves and a line of each join."},
        {"key": "patterns", "label": "Word patterns", "hint": "Three lines of -ing, -ed and -ight words."},
        {"key": "sentence", "label": "Practice sentence", "hint": "The same sentence written three times."},
        {"key": "passage", "label": "Copied passage", "hint": "4 to 6 sentences in neat joined writing with a star on your best line."},
    ],
    ["Gripping the pencil too tightly.", "Letters of different sizes in the same word.", "Mixing upright and sloping letters.", "Writing words too close together.", "Rushing and skipping the joins."],
    [{"title": "Neat Note", "description": "Write a short note or card in your neatest joined writing and compare it to your first line from today.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that letters sit on the baseline, ascenders and descenders are consistent, slope is even, spaces between words are about the width of a small o, common joins are smooth, and the copied passage matches the original. Sorter: Ascender: b, h, t. Descender: g, y, p. Neither: a, m, o.",
)

LESSONS = [A4L1, A4L2, A4L3, A4L4]
