"""Stage 2 English, Week 3 Lesson 4: Write, Edit and Present a Short Story (Writing and editing).
All written work is typed inside the lesson. Spelling reviews the week 3 rules so the lesson is self-contained.
Video ULPDb7xD0S4 (descriptive writing for kids) was found by search and is reused as a writing prompt. Re-check in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc, _video
from spelling_s2_w1 import _w, _c

WORDS = ["stopped", "baking", "happiest", "faster", "stories", "cities"]

MODEL = (
    "The Lantern Keeper\n\n"
    "Beginning: On the edge of a quiet harbour town lived Ravi, who looked after the old lighthouse lantern. Every evening he climbed the winding stairs, polished the glass and lit the flame. "
    "Tonight, a thick grey fog rolled in, and the cold, salty air stung his cheeks.\n\n"
    "Middle: Ravi heard a faint bell far out at sea. A fishing boat was lost! He lit the lantern, but the fog swallowed the beam. He ran down to the shore, grabbed the biggest bell he could find and rang it as loudly as he could. "
    "Out of the mist came a small, answering clang, then another, closer each time.\n\n"
    "End: The boat slid out of the fog and bumped gently against the dock. The fishermen cheered, and one of them shook Ravi's hand. 'Your bell was the sound that saved us,' he said. "
    "Ravi smiled all the way back up the stairs, knowing that on foggy nights both light and sound could bring people home."
)

LESSON = build(
    "s2-eng-w03-l4-write-edit-present-story",
    "Write, Edit and Present a Short Story",
    "Bring the skills from the last three weeks together. Plan a short story, write it with a clear beginning, middle and end, edit it with a checklist, and share it aloud.",
    "Writing: planning, drafting and editing a narrative",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {
        "EN2-CWT-01": "Primary. Plans, drafts, edits and shares a short narrative with a clear structure, sensory detail and precise words.",
        "EN2-RECOM-01": "Uses story structure and reader-focused questions to check that the story makes sense and holds attention.",
        "EN2-VOCAB-01": "Chooses precise nouns, verbs and adjectives, and uses comparing words accurately.",
        "EN2-SPELL-01": "Reviews the week 3 spelling rules: -ing and -ed, -er and -est, and plurals with ies.",
    },
    "We are learning to write a short story from a plan, and to edit it using a checklist.",
    ["I can plan a story with a beginning, middle and end.", "I can write a draft with a problem and a solution.", "I can use at least two senses and precise words.", "I can edit my work for capitals, full stops, spelling and word choice.", "I can read my story aloud clearly."],
    ["draft", "edit", "proofread", "checklist", "structure", "problem", "solution", "publish"],
    ["This lesson (everything you need is inside it)"],
    "Child has completed Weeks 1 to 3: story elements, story mountain, word jobs, senses, comparing words and suffix rules.",
    (
        "Why this matters. Good writing comes in stages. Writers plan, draft, edit and share. Rushing straight to the final copy usually leads to muddled stories, missing full stops and spelling mistakes. Working in stages helps you make a story that is clear, interesting and neat.\n\n"
        "Plan. Use a simple story mountain: setting and character, problem, getting worse, solution, ending. Decide your main character, where they are and what goes wrong. Choose how it will be fixed. A small, clear problem is better than a huge, tangled one.\n\n"
        "Draft. Write your first version following your plan. Aim for three short paragraphs: beginning, middle and end. Use at least two senses to bring the setting to life. Choose strong verbs and adjectives. Do not stop to fix everything; get the story down first.\n\n"
        "Edit. Editing means making your writing better. Use a checklist: Does it start with a capital letter and end with a full stop in every sentence? Do I have a problem and a solution? Did I use at least two senses? Have I replaced weak words such as nice and went? Have I used any comparing words correctly? Are my spelling rules right: -ing and -ed, -er and -est, ies plurals? Read it aloud to hear mistakes.\n\n"
        "Present. Share your story aloud. Speak clearly at a steady pace, pause at full stops and use your voice to show feelings. If you copy it out in neat joined handwriting, keep letter sizes even and leave finger-width gaps.\n\n"
        "A quick demonstration. First draft: 'It was foggy. Ravi went down to the sea. He rang a bell. The boat came back.' After editing: 'A thick grey fog rolled in. Ravi ran to the shore, grabbed the biggest bell he could find and rang it as loudly as he could.' The second version uses precise verbs, an adjective phrase and sense detail."
    ),
    [
        _step("1", "Plan first", "Planning saves time. Use a story mountain: character and setting, problem, it gets worse, solution, ending.\n\nDecide who, where, what goes wrong and how it is fixed.", "Ravi, a lantern keeper. Problem: a boat is lost in fog. Solution: ringing a bell. Ending: the boat is safe.", "Plan the mountain before you write.", ("Why plan first?", ["To keep the story clear", "To make the story longer", "There is no reason"], 0, "A plan keeps the story clear.")),
        _step("2", "A clear problem and solution", "Every story needs a problem the character must fix. Make it small and clear. Show how the character solves it using their own actions.\n\nThe solution should fit the problem.", "Problem: fog hides the light. Solution: Ravi uses sound instead.", "Problem, then a fitting solution.", ("A good solution...", ["Fits the problem", "Has nothing to do with it", "Appears from nowhere"], 0, "The solution should fit the problem.")),
        _step("3", "Write the draft", "Write your first version in three short paragraphs: beginning, middle, end. Get the ideas down. Do not stop to fix every word.\n\nYou will improve it later.", "Beginning: Ravi and the fog. Middle: the lost boat and the bell. End: the rescue.", "First get it down, then improve.", ("What is a draft?", ["A first version", "A final copy", "A plan"], 0, "A draft is a first version.")),
        _step("4", "Add senses and precise words", "Choose at least two senses and replace weak words. Use strong verbs, such as ran, grabbed, rang, instead of went and did.\n\nOne vivid detail is better than three vague ones.", "'The cold, salty air stung his cheeks' uses touch and taste. 'Rang' is stronger than 'did'.", "Senses and strong words make it vivid.", ("Which verb is strongest?", ["went", "grabbed", "did"], 1, "Grabbed tells exactly what happened.")),
        _step("5", "Edit with a checklist", "Check one thing at a time: capitals and full stops, a clear problem and solution, senses, precise words, spelling rules.\n\nReading aloud helps you hear missing words.", "I found two sentences with no full stop and one 'went' to change to 'hurried'.", "Check one thing at a time.", ("Which is a good way to find mistakes?", ["Read it aloud", "Hand it in", "Skip checking"], 0, "Reading aloud helps you hear mistakes.")),
        _step("6", "Review the week 3 spelling rules", "Review three rules. -ing and -ed: stop becomes stopped, bake becomes baking. -er and -est: fast becomes faster, happy becomes happiest. Plurals: story becomes stories, city becomes cities.\n\nUse the rule that fits each word.", "stopped (double p), baking (drop e), happiest (y to i), faster (just add), stories (y to ies), cities (y to ies).", "Use the rule that fits the word.", ("What is the plural of city?", ["citys", "cities", "cityes"], 1, "Change y to ies.")),
        _step("7", "Present your story", "Read your story aloud with a clear voice and steady pace. Look up at your listener and pause at full stops.\n\nThen ask for one thing they liked and one question they have.", "I read slowly, paused at full stops, and my listener liked the fog.", "Share with a clear voice.", ("What helps a listener follow?", ["A steady pace and pauses", "Reading very fast", "Whispering"], 0, "A steady pace and pauses help.")),
    ],
    (
        "Study the model, The Lantern Keeper. Plan: character Ravi, setting a harbour town, problem a boat lost in fog, solution a loud bell, ending the boat arrives safely. Beginning: sets up who, where and the foggy evening with sense detail (cold, salty air). "
        "Middle: shows the problem (the fog swallows the beam) and Ravi's action (he rings the bell). End: the boat is saved and Ravi learns something. Now edit a weak draft: 'Ravi went to the sea. It was foggy. He did a bell.' "
        "Improve: 'Ravi ran to the shore through the thick grey fog and rang the bell as loudly as he could.' We replaced weak verbs, added adjectives and a sense detail, and fixed the missing words."
    ),
    (
        "Type your answers in the practice boxes. Part A: type a five-point story-mountain plan for a story of your own choice. Part B: improve this weak draft: 'The dog went to the park. It was nice. He did a run.' Use a precise verb, two adjectives and one sense. Part C: type the correct form: stop + ed, bake + ing, happy + est, fast + er, story (plural), city (plural). Your parent can check your answers against the answer key."
    ),
    (
        "Read the model story, then write your own. Everything you write goes in the boxes.\n\n" + MODEL + "\n\n"
        "Stage 1 (plan): type a five-point story-mountain plan: character and setting, problem, it gets worse, solution, ending. Choose your own idea or one of these: a lost kitten in a storm, a school lost property mystery, a boat race with a surprise, a sleepover that goes wrong.\n"
        "Stage 2 (draft): write three short paragraphs: beginning, middle and end. Aim for ten to fourteen sentences. Include at least two senses, one comparing word and one -ing word.\n"
        "Stage 3 (edit): use the checklist. Type the changes you made: at least two weak words you replaced, one sentence you fixed and one spelling you corrected.\n"
        "Stage 4 (final copy): type your improved story.\n"
        "Stage 5 (present): read your story aloud to a listener. Type one thing they liked and one question they had.\n"
        "Stage 6 (spell): type your six spelling words and the rule for each."
    ),
    "Which stage of writing was most useful today: planning, drafting or editing, and why?", "Did I plan before writing, include a problem and solution, use senses and precise words, edit with the checklist, read aloud and spell the six words using the rules?",
    [_q("What are the stages of writing used today?", ["Plan, draft, edit, present", "Draft only", "Copy, paste, stop", "Read, sleep, write"], 0, "Writers plan, draft, edit and present."), _q("What is a draft?", ["A first version of writing", "A final copy", "A title", "A list of spellings"], 0, "A draft is a first version."), _q("What does a story need in its middle?", ["A problem and the character's action", "Only the title", "A new setting every sentence", "Nothing"], 0, "The middle shows the problem and what the character does."), _q("Which is a strong verb?", ["went", "did", "hurried", "was"], 2, "Hurried is exact."), _q("Which sentence uses a sense?", ["Ravi was there.", "The cold, salty air stung his cheeks.", "It happened.", "He did it."], 1, "It uses touch and taste."), _q("What should you check when you edit?", ["Capitals, full stops, word choice and spelling", "Only the title", "Nothing", "Only the handwriting"], 0, "Editing checks several things."), _q("What is the correct spelling when you add -ed to stop?", ["stoped", "stopped", "stopt", "stopd"], 1, "Double the p."), _q("What is the correct superlative of happy?", ["happyest", "happiest", "hapiest", "happist"], 1, "Change y to i and add -est."), _q("What is the plural of story?", ["storys", "stories", "storyes", "storeys"], 1, "Change y to ies."), _q("How should you present your story aloud?", ["Clearly, at a steady pace, with pauses", "As fast as you can", "In a whisper", "Without looking up"], 0, "A steady pace helps your listener.")],
    "Type your answers in the practice boxes and submit them.", "Extension: write a short sequel in which the same character faces a new problem, and compare it with the first story.",
    [("draft", "A first version of your writing"), ("edit", "To improve your writing"), ("proofread", "To check for spelling and punctuation mistakes"), ("checklist", "A list of things to check"), ("structure", "The order and parts of a story"), ("problem", "What goes wrong in a story"), ("solution", "How the problem is fixed"), ("publish", "To share your finished work")],
    [_video("Descriptive writing for kids", "ULPDb7xD0S4", "Watch for the sense details and precise words. Pick one idea to use in your story.", "Read the model story again and pick one sense detail to borrow.", ("What helps a reader picture a scene?", ["Sensory detail and precise words", "Longer sentences only", "Fewer words"], 0, "Sensory detail and precise words paint a picture."))],
    _sort("Which stage of writing is it?", "Sort each action into the stage of writing it belongs to.", ["Plan", "Draft", "Edit", "Present"], [("Draw a story mountain", 0), ("Choose the problem and solution", 0), ("Write three short paragraphs", 1), ("Get the ideas down", 1), ("Replace 'went' with a strong verb", 2), ("Check full stops and capitals", 2), ("Read it aloud to a listener", 3), ("Ask for one thing they liked", 3)]),
    [_wc("Which is correct?", ["stopped", "stoped", "stopt"], 0, "Double the p."), _wc("Which is correct?", ["baking", "bakeing", "bakking"], 0, "Drop the e."), _wc("Which is correct?", ["happiest", "happyest", "hapiest"], 0, "Change y to i."), _wc("Which is correct?", ["faster", "fastter", "fastar"], 0, "Just add -er."), _wc("Which is correct?", ["stories", "storys", "storyes"], 0, "Change y to ies."), _wc("Which is correct?", ["citys", "cities", "cityes"], 1, "Change y to ies."), _wc("Which is the strongest verb?", ["grabbed", "got", "did"], 0, "Grabbed is exact."), _wc("Which is the draft stage?", ["Writing the first version", "Reading it aloud", "Choosing a title"], 0, "The draft is the first version.")],
    [{"key":"partA","label":"Part A: story plan","hint":"Five points: character and setting, problem, it gets worse, solution, ending."}, {"key":"partB","label":"Part B: improve the draft","hint":"Improve: The dog went to the park. It was nice. He did a run."}, {"key":"partC","label":"Part C: spelling rules","hint":"stop+ed, bake+ing, happy+est, fast+er, story plural, city plural."}, {"key":"plan","label":"My story plan","hint":"The five-point story mountain."}, {"key":"draft","label":"My draft","hint":"Three paragraphs with at least two senses."}, {"key":"edits","label":"My edits","hint":"Two weak words replaced, one sentence fixed, one spelling corrected."}, {"key":"final","label":"My final story","hint":"Type the improved version."}, {"key":"feedback","label":"Listener feedback","hint":"One thing they liked and one question they had."}, {"key":"spelling","label":"Spelling words","hint":"Type the six words and the rule for each."}],
    ["Starting to write with no plan", "A story with no clear problem or solution", "Using weak words such as nice, went and did", "Skipping the edit stage", "Forgetting capital letters and full stops"],
    ["Write a short story each week using the same plan, draft, edit, present routine.", "Read a favourite story and map its problem and solution."],
    "Part A: accept a clear plan with all five points. Part B: accept improvements with a precise verb, two adjectives and a sense, for example: The cheerful dog raced across the grassy park, and the cool wind tingled on his fur. Part C: stopped, baking, happiest, faster, stories, cities. Main task: look for a planned structure, a problem with a fitting solution, at least two senses, precise words, a real edit (not just copying), and honest feedback. Quiz answers: plan, draft, edit, present; a first version of writing; a problem and the character's action; hurried; The cold, salty air stung his cheeks; capitals, full stops, word choice and spelling; stopped; happiest; stories; clearly, at a steady pace, with pauses.",
)

LESSON["spelling"] = {"focus":"Week 3 review: suffixes, -er/-est and ies plurals", "teaching":"Use the rule that fits the word. Double the last letter after one short vowel (stop becomes stopped). Drop a silent e before -ing (bake becomes baking). Change y to i before -est (happy becomes happiest). Just add -er to many words (fast becomes faster). Change y to ies for consonant plus y plurals (story becomes stories, city becomes cities).", "words":[_w("stopped","stop-p-ed","double the p"),_w("baking","bak-ing","drop the e"),_w("happiest","happ-i-est","change y to i"),_w("faster","fast-er","just add -er"),_w("stories","stor-ies","change y to ies"),_w("cities","cit-ies","change y to ies")], "check":[_c("Which is spelled correctly?",["stoped","stopped","stopt"],1,"Double the p."),_c("Which is spelled correctly?",["citys","cities","cityes"],1,"Change y to ies.")]}
LESSON["spelling_focus"] = "Week 3 review: suffixes, -er/-est, ies"
LESSON["hoard_words"] = list(WORDS)
