"""Stage 2 English, first-week Lesson 2: planning a story. Fully taught from scratch.
Loaded before the older l2_l3 module so this version wins (same seed_key)."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W2L2 = build(
    "s2-eng-w02-l2-story-planning", "Story Mountain: Plan Before You Write",
    "The Plot Mountain is waiting! Learn how real authors plan, then plan an original story step by step so nothing falls off the cliff.",
    "Writing: planning a narrative",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Plans a narrative using brainstorming, a character card, a setting card and a five-part story mountain.",
     "EN2-VOCAB-01": "Learns and uses planning words: brainstorm, protagonist, obstacle, sensory, cause and effect, draft.",
     "EN2-SPELL-01": "Applies vowel team spelling and the Look, Say, Cover, Write, Check routine to planning words."},
    "We are learning to plan a story with a beginning, middle and end before we write it, so that the story holds together.",
    ["I can brainstorm ideas and choose the best one using three questions.",
     "I can create a main character with a trait, a want and an obstacle.",
     "I can describe a setting using place, time, mood and the five senses.",
     "I can fill in a five-part story mountain with short phrases.",
     "I can check my plan with because and so, and choose a strong ending.",
     "I can spell my planning words correctly."],
    ["plan", "brainstorm", "protagonist", "obstacle", "sensory", "cause and effect", "resolution", "draft"],
    ["Paper or notebook", "Pencil", "Coloured pencils", "A timer (a phone or kitchen timer is fine)"],
    "Nothing is assumed. Child can write simple sentences. The story parts (character, setting, conflict, plot) are explained briefly again here so this lesson stands on its own.",
    "A plan is a short map of your story, made BEFORE you write it. Authors plan because a story that is made up as you go often wanders, forgets its problem or ends suddenly. A plan does not need to be long or neat. It is for you, not for marking.\n\nA good story plan answers four questions. WHO is the story about, and what do they want? WHERE and WHEN does it happen? WHAT goes wrong? HOW does it end?\n\nThose answers go onto a story mountain. A story mountain is a drawing with five boxes: the introduction (also called exposition), the rising action, the climax, the falling action and the resolution. The introduction is at the bottom of the mountain, the climax is the peak, and the resolution is flat ground at the end.\n\nWhen you write from a plan, you can put all your effort into good sentences instead of wondering what comes next. We will take it one step at a time: ideas, character, setting, the mountain, then checking.",
    [
        _step("1", "What a plan is and why we plan",
              "Imagine setting off on a long bush walk with no map. You might get there, but you might also get lost. A plan is your map. It tells you where the story starts, what the big moments are and where it finishes.\n\nA plan is made of SHORT PHRASES, not full sentences. Instead of writing 'Mia hears a strange sound coming from the attic in the middle of the night', you write 'Mia hears sound in attic, midnight'. This saves time and keeps your best sentences for the real writing, which is called the DRAFT (the first full version).\n\nPlanning has five jobs, which become the steps of this lesson: find an idea, build a character, build a setting, fill the mountain and check it. Do them in order and the story almost writes itself.",
              "Without a plan: 'Once there was a girl who went to the shop and then there was a dog and then it was night.' The story wanders. With a plan: 'Girl wants to find lost dog. Searches park, creek, old shed. Finds dog stuck in a fence. Frees him.' We already know where it is going.",
              "A plan is short, rough and just for you.",
              ("Which is the best way to write a plan?", ["Short phrases in each box", "Perfect full sentences", "A whole page for each part"], 0, "A plan uses short phrases because it is a guide for you.")),
        _step("2", "Brainstorming: collecting ideas fast",
              "A BRAINSTORM is a quick list of ideas where you do NOT judge or cross anything out. The aim is quantity first. Good ideas often hide behind silly ones.\n\nHow to brainstorm: 1) Set a timer for two minutes. 2) Write every idea that comes, even if it seems strange. 3) Keep your pencil moving. 4) Stop when the timer rings.\n\nA helpful trick is the WHAT IF question. 'What if a lighthouse keeper found a message in a bottle?' 'What if the school bus could fly?' 'What if a robot started at our school?' One what-if question gives you a character, a setting and a problem all in one go.\n\nAnother trick is to start from something you know: a place you love, an animal you like, a time you felt scared or proud. Real feelings make stories feel real.",
              "Two-minute brainstorm: lost puppy; haunted library; robot at school; storm at sea; talking tree; kid who can hear animals; missing birthday cake; treasure under the oval; what if the moon fell into the lake?",
              "Do not judge while brainstorming. Choose afterwards.",
              ("What is the rule while you brainstorm?", ["Write ideas without judging them", "Only write perfect ideas", "Stop after one idea"], 0, "Brainstorming is about collecting lots of ideas first.")),
        _step("3", "Choosing your best idea",
              "After brainstorming, you CHOOSE. Ask three questions of each idea:\n1. Does it have a clear PROBLEM? (If nothing goes wrong, there is no story.)\n2. Can I tell it in about one page? (Small ideas told well beat huge ideas rushed.)\n3. Do I CARE about it? (If you are excited, the reader will be too.)\n\nCircle the idea that answers yes to all three. If two ideas tie, pick the one with the stronger problem.\n\nWatch out for ideas that are too big, like 'a journey around the whole world' or 'a war between planets'. They sound exciting but need too many events. Shrink them: 'a boy who gets lost in one enormous airport' has the same adventure feeling in a much smaller space.",
              "From the brainstorm: 'robot at school' has a clear problem (it does not know the rules), fits on one page, and sounds fun. 'A journey around the world' is too big. Choice: robot at school.",
              "Clear problem, one page, I care: three questions, one winner.",
              ("Which idea is the best size for a one-page story?", ["A girl loses her key on the way home", "A war between three planets", "A trip around the whole world"], 0, "The small idea has a clear problem and can be finished in a page.")),
        _step("4", "Your main character: trait, want and obstacle",
              "The main character is called the PROTAGONIST. A story needs a character who WANTS something. A character who wants nothing makes a boring story.\n\nBuild your protagonist with a CHARACTER CARD of four things:\n1. NAME.\n2. TRAITS: one or two words for what they are like inside, such as curious, careful, brave, stubborn.\n3. WANT: what they are trying to get or do.\n4. OBSTACLE: whatever makes it hard. An OBSTACLE is something in the way. It might be a person, a place, a rule or even the character's own fear.\n\nThe want and the obstacle together create the plot. Choose traits you can SHOW through actions: a careful boy checks the lock three times. Showing is stronger than telling.",
              "Character card. Name: Zip. Traits: curious, polite. Want: to make a friend at school. Obstacle: he is a robot who does not understand jokes or playground rules.\n\nAnother card. Name: Mia. Traits: curious, brave. Want: to find the source of a strange sound in the attic. Obstacle: it is midnight and her torch has flat batteries.",
              "Want plus obstacle equals story.",
              ("What does a protagonist need in order to make a story?", ["A want and an obstacle", "A long name", "Lots of friends"], 0, "A want with something in the way creates the plot.")),
        _step("5", "Your setting: place, time, mood and the five senses",
              "The setting is where and when the story happens. A strong setting also has a MOOD, which is the feeling it gives the reader, such as eerie, cosy or tense.\n\nBuild a SETTING CARD with four parts: PLACE, TIME, MOOD and two SENSORY DETAILS. SENSORY means using the five senses: what can the character see, hear, smell, feel or taste?\n\nPick details that match the mood. For an eerie attic you might choose: SEE dusty trunks and cobwebs; HEAR creaking boards; FEEL a cold draught. For a happy picnic you would choose very different details: SEE bright rugs; SMELL fresh sandwiches.\n\nThe setting can also help cause the problem. A storm makes it harder to catch a runaway kite. A crowded market makes it easier to get lost.",
              "Setting card. Place: attic. Time: midnight. Mood: eerie. See: dusty trunks and cobwebs. Hear: floorboards creaking. Feel: cold air on her neck.\n\nSecond card. Place: school playground. Time: lunchtime. Mood: noisy and busy. Hear: shouting and skipping ropes. Smell: cut oranges.",
              "Choose details that match the mood you want.",
              ("Which details make an EERIE attic?", ["Creaking boards and cobwebs", "Bright sunshine and music", "A cheerful kitchen"], 0, "Creaking boards and cobwebs match an eerie mood.")),
        _step("6", "Filling in the story mountain",
              "Now draw a mountain with five labelled boxes and fill each with a short phrase.\n\n1. INTRODUCTION (exposition): who, where, when, and what they want. This is the base of the mountain.\n2. RISING ACTION: the first obstacle and then things getting harder. Aim for TWO or THREE events, each more difficult than the last.\n3. CLIMAX: the peak. The biggest, most exciting moment, where the character faces the problem head on.\n4. FALLING ACTION: what happens straight after, as things calm down.\n5. RESOLUTION: how it ends, and what the character learns or how they have changed.\n\nTip: fill in the CLIMAX first, then the introduction. When you know the big moment, the rest is easier to build.",
              "Mountain for Mia. Introduction: Mia hears a sound in the attic at midnight. Rising action: her torch fails; she finds a trunk that moves. Climax: she opens the trunk and a kitten leaps out. Falling action: she carries the kitten downstairs. Resolution: Mia keeps the kitten and feels proud of being brave.",
              "Five boxes, short phrases, two or three events in the middle.",
              ("What goes in the RISING ACTION box?", ["Events as the problem grows", "The ending", "The title"], 0, "Rising action is where things get harder.")),
        _step("7", "Cause and effect: checking the chain",
              "A plan is not just a list of events. Each event should CAUSE the next one. This is called CAUSE AND EFFECT.\n\nTest with two joining words. BECAUSE: 'The torch failed BECAUSE the batteries were flat.' SO: 'Mia heard a sound, SO she climbed the stairs.' Read down your mountain and try to join every box to the next with because or so.\n\nIf you cannot, something is missing or the events are random. For example, 'Mia hears a sound. Then she goes to the beach.' does not link. Fix it by adding the missing step or changing the event so it follows from the one before.\n\nEvents that are linked make a reader think 'Of course!' or 'Oh no!' instead of 'Why did that happen?'",
              "Check: Mia hears a sound, SO she climbs to the attic. Her torch fails, BECAUSE the batteries are flat, SO she must go on in the dark. She finds a moving trunk, SO she opens it. Every link works.",
              "If you cannot join two events with because or so, a piece is missing.",
              ("Which pair is linked by cause and effect?", ["Mia heard a sound, so she climbed the stairs.", "Mia heard a sound. Pizza is round.", "The attic was dusty. Then it was Tuesday."], 0, "The second event follows because of the first.")),
        _step("8", "Choosing a strong ending",
              "The ending is where many young writers lose their way. A strong ending has three features:\n1. The character SOLVES the problem by their own action (not by luck, magic or someone else).\n2. It matches the problem from the introduction. If the problem was a lost kitten, the ending is about the kitten.\n3. It shows a change or a lesson, even a small one, such as feeling braver.\n\nAvoid weak endings: 'and then it was all a dream', 'and everything was fine', 'then they woke up' and 'a magic fairy fixed everything'. They cheat the reader out of the climax.\n\nTry a quick ending test: finish this sentence. 'The problem is solved because my character ______.' If you can fill the gap with an action, the ending is strong.",
              "Weak: Mia heard a noise. Then she woke up and it was a dream. Strong: Mia heard a noise, opened the trunk herself and rescued the kitten. The problem is solved because Mia opened the trunk.",
              "The character should solve the problem, not luck.",
              ("Which ending is stronger?", ["Mia opens the trunk and rescues the kitten", "Then it was all a dream"], 0, "The character acts to solve the problem.")),
        _step("9", "Final checks and spelling your planning words",
              "Before you write, run one last check, called a BEGINNING, MIDDLE and END check. Beginning: do I know who, where and what they want? Middle: are there two or three events, each harder than the last? End: does the climax face the problem and does the resolution feel finished?\n\nThen read your plan aloud. If it sounds like a story, it is ready.\n\nSpelling matters too, so write your word list first. Use the vowel teams you know: plain, trail, dream, coast. For tricky words use Look, Say, Cover, Write, Check. 'Character' has ch making a k sound. 'Beginning' has a double n because begin + ning doubles the n after a short vowel. 'Adventure' ends in -ure.\n\nNew Word Hoard words: character, beginning, adventure, mystery, obstacle, climax.",
              "character: ch-a-r-a-c-t-e-r. Memory trick: ch says k, like in chorus. beginning: begin + n + ing, so two n letters in the middle.",
              "Write your word list first so your story can flow later.",
              ("How many n letters are in 'beginning'?", ["3", "2", "1"], 1, "begin + ning doubles the n, giving three n letters in total: be-gi-nn-ing has n, n, n. Count: b-e-g-i-n-n-i-n-g.")),
    ],
    "Idea chosen from a brainstorm: What if a robot arrived at school? CHARACTER CARD. Name: Zip. Traits: curious, polite. Want: to make a friend. Obstacle: he does not understand jokes or playground rules. SETTING CARD. Place: school playground. Time: lunchtime. Mood: noisy and busy. Senses: shouting and skipping ropes (hear), cut oranges (smell).\n\nSTORY MOUNTAIN. Introduction: Zip arrives at school and wants a friend. Rising action: he tries to join a game and gets it wrong, so the children laugh; he repeats a joke wrongly, so they are confused. Climax: a girl falls from the climbing frame, so Zip uses his strong arms to catch her. Falling action: the children cheer and crowd around him. Resolution: Zip is invited to play and learns that kindness is a language everyone understands.\n\nCHECKS. Cause and effect: every box joins with because or so. Ending: Zip solves the problem himself by catching the girl, and it matches the want (a friend).",
    "In your notebook: 1) Set a timer for two minutes and brainstorm six what-if ideas. 2) Choose your best using the three questions (clear problem, one page, I care). 3) Fill in a character card (name, two traits, want, obstacle). 4) Fill in a setting card (place, time, mood, two sensory details). 5) Draw a mountain and fill in the five boxes with short phrases. 6) Join each box to the next using because or so. 7) Finish the sentence 'The problem is solved because my character ______.'",
    "Plan one complete original story. Create the brainstorm, character card, setting card and a full story mountain. Write one sentence about how your ending solves the problem, and check the whole chain with because and so. Do not write the story yet: the next lessons are for drafting.",
    "Which part of planning was easiest for you, and which part needs more thinking? How did the story mountain help?",
    "Did I brainstorm and then choose using the three questions? Does my character have a want and an obstacle? Does my setting use the senses? Is every box on my mountain filled? Can I join the events with because or so? Does my character solve the problem?",
    [
        _q("What is a brainstorm?", ["A quick list of ideas with no judging", "A final draft", "A spelling list"], 0, "A brainstorm collects ideas fast."),
        _q("Which three questions help you CHOOSE an idea?", ["Clear problem? One page? Do I care?", "Is it long? Is it silly? Is it famous?", "Is it scary? Is it new? Is it loud?"], 0, "Choose an idea with a clear problem, a small size and something you care about."),
        _q("Zip is a robot who wants a friend but does not understand jokes. What is Zip's OBSTACLE?", ["He does not understand jokes", "He wants a friend", "He is at school"], 0, "The obstacle is whatever makes it hard to get what he wants."),
        _q("Which goes in the INTRODUCTION box?", ["Characters, setting and what the character wants", "The ending", "The climax"], 0, "The introduction sets up who, where, when and the want."),
        _q("Which details match an EERIE midnight attic?", ["Creaking floorboards and cold air", "Bright sunshine and birdsong", "Cheerful music and sweets"], 0, "The details match the mood."),
        _q("Which pair is linked by cause and effect? ", ["The torch failed because the batteries were flat.", "The torch was red. Tuesday is a day.", "She smiled. The sea has fish."], 0, "The word because shows one thing caused the other."),
        _q("Read the plan. Introduction: Jo wants to win the sack race. Rising action: she trips and her shoelace snaps. Climax: she kicks off her shoes and races barefoot. Resolution: she wins. Which event is the CLIMAX?", ["She races barefoot", "Her shoelace snaps", "She wins"], 0, "The climax is the biggest moment where she faces the problem."),
        _q("Which is the strongest ending?", ["Jo solves the problem by racing barefoot and wins", "Jo wakes up and it was a dream", "A fairy makes Jo win"], 0, "The character solves the problem through her own action."),
        _q("Which is spelt correctly?", ["begining", "beginning", "beggining"], 1, "Double the n."),
        _q("Which is spelt correctly?", ["adventure", "advencher", "adventur"], 0, "adventure ends in -ure."),
    ],
    "Upload a photo of your brainstorm, character card, setting card and story mountain.",
    "Plan the same story twice with two different endings. Which is stronger and why? Use the ending test to decide.",
    [("plan", "Deciding what to write before you write."), ("brainstorm", "A fast list of ideas with no judging."), ("protagonist", "The main character."),
     ("obstacle", "Something in the way of what the character wants."), ("sensory", "Using the five senses: see, hear, smell, feel, taste."),
     ("cause and effect", "One event causes the next."), ("resolution", "How the problem is solved or changes."), ("draft", "A first full version of your writing.")],
    [
        _video("Plot Mountain! The Plot Diagram Song (Scratch Garden)", "NpWHZJZQDSE",
               "Watch the five stages of the plot mountain. Pause after each stage and say what would go there in your own story.",
               "Draw the mountain on paper and write the five labels in order.",
               ("Which stage comes right after the climax?", ["Falling action", "Rising action", "Introduction"], 0, "After the climax the story comes down the mountain.")),
    ],
    _sort("Plan part sorter", "Which part of the plan does each idea belong to? Tap a part, then Check.",
          ["Character", "Setting", "Obstacle", "Ending"],
          [("a curious robot named Zip", 0), ("a brave girl who wants to find a kitten", 0), ("a noisy playground at lunchtime", 1), ("midnight in a dusty attic", 1), ("the torch has no batteries", 2), ("he does not understand jokes", 2), ("Zip is invited to play", 3), ("Mia keeps the kitten", 3)]),
    [
        _wc("A protagonist is the ___.", ["main character", "setting", "ending"], 0, "Protagonist means main character."),
        _wc("An obstacle is something that ___.", ["is in the way", "ends a story", "is a place"], 0, "It blocks what the character wants."),
        _wc("Sensory details use the ___.", ["five senses", "alphabet", "calendar"], 0, "See, hear, smell, feel, taste."),
        _wc("Which spelling is correct?", ["character", "karacter", "charactor"], 0, "ch makes a k sound."),
        _wc("A draft is a ___ version.", ["first", "final", "last"], 0, "A draft is the first version."),
        _wc("A plan should be written in ___.", ["short phrases", "long paragraphs", "perfect sentences"], 0, "A plan is for you."),
    ],
    [
        {"key": "ideas", "label": "Brainstorm", "hint": "Six what-if ideas, with your best one circled."},
        {"key": "character", "label": "Character", "hint": "Name, two traits, want and obstacle."},
        {"key": "setting", "label": "Setting", "hint": "Place, time, mood and two sensory details."},
        {"key": "mountain", "label": "Story mountain", "hint": "Five short phrases, one per part."},
    ],
    ["Writing the story instead of planning it.", "A character with no want.", "A plan where events do not cause each other.", "An ending where luck, a dream or magic solves the problem.", "Choosing an idea that is far too big for one page."],
    [{"title": "Plan Swap", "description": "Swap plans with a family member and ask them to tell the story back.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check the idea was chosen with the three questions, the character has a trait, want and obstacle, the setting uses at least two senses and a mood, the mountain has five parts, and the events connect with because or so. Sort: Character: robot Zip, brave girl. Setting: playground, attic. Obstacle: torch, jokes. Ending: invited to play, keeps kitten.",
)

LESSONS = [W2L2]
