"""Stage 2 English, Week 2 Lesson 3: Nouns, verbs and adjectives (Language).
All writing is completed inside the lesson. This lesson is self-contained, including spelling.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc, _video
from spelling_s2_w1 import _w, _c

WORDS = ["rain", "today", "sleep", "clean", "float", "please"]

TEXT = (
    "The Rainy Race\n\n"
    "On a wet morning, Mia carried her small blue boat to the creek. Her cheerful dog, Max, ran beside her. "
    "A strong wind blew across the water, but Mia carefully placed the boat on the waves. The bright sail caught the wind and the boat raced quickly downstream. "
    "Mia laughed as Max splashed through the shallow water."
)

LESSON = build(
    "s2-eng-w02-l3-nouns-verbs-adjectives", "Nouns, Verbs and Adjectives",
    "Words have different jobs. Learn to identify naming words, doing words and describing words, then use them to make your own writing clearer and more interesting.",
    "Language: grammar and vocabulary", ["EN2-VOCAB-01", "EN2-CWT-01", "EN2-SPELL-01"],
    {
        "EN2-VOCAB-01": "Primary. Identifies and uses nouns, verbs and adjectives to understand and choose precise words.",
        "EN2-CWT-01": "Uses word choices to add detail and clarity in a planned narrative.",
        "EN2-SPELL-01": "Spells words with vowel teams ai, ay, ee, ea and oa (week 2 spelling focus).",
    },
    "We are learning to identify nouns, verbs and adjectives and choose them carefully in our writing.",
    ["I can find nouns, verbs and adjectives in a sentence.", "I can explain the job each word type does.", "I can choose precise verbs and adjectives to improve a sentence.", "I can build a clear sentence with a noun, verb and adjective.", "I can spell words with vowel teams ai, ay, ee, ea and oa."],
    ["noun", "verb", "adjective", "precise", "sentence", "subject", "action", "describe"],
    ["This lesson (everything you need is inside it)"],
    "Child can identify character, setting and plot, and can plan short story events (Week 2 Lessons 1 and 2).",
    (
        "Why this matters. Writers choose words on purpose. A noun tells the reader who or what is in the story. A verb makes the action move. An adjective helps the reader picture it. When you can notice these jobs, you can make your own sentences clearer, stronger and more interesting.\n\n"
        "The three word jobs. A noun is a naming word: a person, place, animal, object or idea. A verb is a doing or being word: it tells what happens or what something is. An adjective is a describing word: it tells more about a noun. In the sentence 'The tiny bird flew', bird is the noun, flew is the verb and tiny is the adjective.\n\n"
        "How to find them. First, look for who or what the sentence is about; that is often a noun. Next ask, 'What is it doing?' The answer is the verb. Then ask, 'What kind?' or 'Which one?' The answers are often adjectives. Some words can have different jobs in different sentences, so always check the job it is doing there.\n\n"
        "Choosing strong words. Instead of the weak verb 'went', a character might raced, crept, trudged or skipped. Instead of only saying 'a dog', you might write 'a muddy, excited dog'. Do not pile on adjectives; choose one or two that create the clearest picture.\n\n"
        "The routine. 1. Read the whole sentence. 2. Circle the noun or nouns. 3. Underline the verb. 4. Put a box around the adjective or adjectives. 5. Check that every adjective describes a noun. 6. Read it aloud to hear whether the sentence makes sense.\n\n"
        "A quick demonstration. In 'The bright sail caught the wind', sail and wind are nouns because they name things. Caught is the verb because it tells what happened. Bright is the adjective because it describes the sail."
    ),
    [
        _step("1", "Nouns name things", "A noun is a naming word. It can name a person, place, animal, object or idea. You can often put 'the' or 'a' before a noun.\n\nAsk: who or what is this sentence about?", "Mia, creek, dog, boat, water and wind are nouns.", "A noun names a person, place, animal, object or idea.", ("Which word is a noun?", ["jump", "shiny", "creek"], 2, "Creek names a place.")),
        _step("2", "Verbs show action", "A verb tells what someone or something does, or sometimes what it is. It makes a sentence move.\n\nAsk: what is happening?", "Mia carried the boat. Max ran. The wind blew. The boat raced.", "A verb tells the action or state of being.", ("Which word is a verb?", ["dog", "ran", "wet"], 1, "Ran tells what the dog did.")),
        _step("3", "Adjectives describe nouns", "An adjective gives more information about a noun. It can tell size, colour, number, feeling, shape or quality.\n\nAsk: what kind, which one or how many?", "A small blue boat: small and blue describe the noun boat.", "An adjective describes a noun.", ("Which word is an adjective?", ["blue", "boat", "floated"], 0, "Blue describes the boat.")),
        _step("4", "Find the jobs in a sentence", "Read the whole sentence before sorting words. A sentence can have more than one noun and more than one adjective, but it needs a verb.\n\nUse the three questions: who or what, what happens, what kind?", "In 'Her cheerful dog ran beside her', dog is a noun, ran is a verb and cheerful is an adjective.", "Find the noun first, then the verb, then its describing words.", ("In 'The bright sail caught the wind', which word is the verb?", ["bright", "sail", "caught"], 2, "Caught tells what the sail did.")),
        _step("5", "Make your verbs precise", "Precise means exact. Strong verbs let the reader see the action. Replace a weak verb only when the new verb matches what really happened.\n\nRead your sentence aloud: does the verb make the action clear?", "Instead of 'Max went through the water', write 'Max splashed through the water.'", "A precise verb creates a clearer picture.", ("Which verb gives the clearest picture?", ["went", "did", "splashed"], 2, "Splashed tells us exactly how Max moved.")),
        _step("6", "Spelling focus: vowel teams", "This week's words use vowel teams: rain (ai), today (ay), sleep (ee), clean (ea), float (oa) and please (ea).\n\nRemember: ai usually sits in the middle; ay usually sits at the end.", "r-ai-n, tod-ay, sl-ee-p, cl-ea-n, fl-oa-t, pl-ea-se.", "Spot the vowel team and spell it as one sound.", ("Which vowel team is in 'float'?", ["ea", "oa", "ai"], 1, "Float has the vowel team oa.")),
        _step("7", "Improve a sentence", "Start with a simple sentence, then choose one precise verb and one or two helpful adjectives. Keep the meaning clear.\n\nGood writers revise: they read, choose and check.", "Plain: 'The dog went in the water.' Improved: 'The cheerful dog splashed into the shallow water.'", "Use adjectives and verbs to help a reader see the action.", ("Which sentence is clearer?", ["The dog went in water.", "The cheerful dog splashed into the shallow water.", "The dog did a thing."], 1, "The second sentence uses a precise verb and useful adjectives.")),
    ],
    "Read: 'The small blue boat floated slowly across the creek.' Ask who or what? Boat and creek are nouns. What happened? Floated is the verb. What kind boat? Small and blue are adjectives. Slowly tells how it floated, so it is not one of today's three word jobs. Now improve 'Mia went to the creek.' Choose a precise verb: 'Mia hurried to the creek.' Add a helpful adjective: 'Mia hurried to the sparkling creek.' Check that sparkling describes creek and hurried tells Mia's action.",
    "Type your answers in the practice boxes. Part A: copy three nouns, three verbs and three adjectives from The Rainy Race. Part B: label the word jobs in: 'The strong wind blew across the water.' Part C: improve 'The dog went to the boat' with one precise verb and two useful adjectives. Part D: type the vowel team in rain, today, sleep, clean, float and please. Your parent can check the answer key.",
    "Read the text, then complete all stages in the boxes.\n\n" + TEXT + "\n\nStage 1: type four nouns, four verbs and four adjectives from the text.\nStage 2: copy one sentence and label its nouns, verb and adjectives.\nStage 3: improve this plain sentence: 'Mia went to the creek.' Include one precise verb and two adjectives.\nStage 4: write two original sentences for your own story plan. Each must have a noun, a verb and at least one adjective. Label the word jobs in each.\nStage 5: type your six spelling words and mark the vowel team in each.",
    "Which word job was easiest to find today, and how did the three questions help you?", "Did I find nouns, verbs and adjectives correctly, choose precise words, write clear sentences and spell the vowel-team words?",
    [_q("What does a noun do?", ["Names a person, place, animal, object or idea", "Shows an action", "Describes a noun", "Ends a sentence"], 0, "A noun is a naming word."), _q("What does a verb do?", ["Names something", "Shows an action or state", "Describes a noun", "Shows a full stop"], 1, "A verb tells what happens or what something is."), _q("What does an adjective do?", ["Shows an action", "Names a place", "Describes a noun", "Connects two sentences"], 2, "An adjective describes a noun."), _q("Which is the noun in 'The bright sail caught the wind'?", ["bright", "sail", "caught", "the"], 1, "Sail names a thing."), _q("Which is the verb in 'Max splashed through the water'?", ["Max", "through", "splashed", "water"], 2, "Splashed tells what Max did."), _q("Which adjective describes boat in 'a small blue boat'?", ["small and blue", "a", "boat", "none"], 0, "Small and blue both describe boat."), _q("Which is the most precise verb?", ["went", "moved", "raced", "did"], 2, "Raced tells exactly how something moved."), _q("Which word is a noun?", ["carefully", "cheerful", "creek", "quickly"], 2, "Creek names a place."), _q("Which vowel team is in 'clean'?", ["ai", "ay", "ea", "oa"], 2, "Clean has ea."), _q("Which sentence has a noun, verb and adjective?", ["The dog.", "The muddy dog splashed.", "Quickly and slowly.", "To the creek."], 1, "Dog is the noun, muddy is the adjective and splashed is the verb.")],
    "Type your answers in the practice boxes and submit them.", "Extension: rewrite three plain sentences from a book or your own work with more precise verbs and helpful adjectives. Explain which word you changed and why.",
    [("noun", "A word that names a person, place, animal, object or idea"), ("verb", "A word that tells an action or state of being"), ("adjective", "A word that describes a noun"), ("precise", "Exact and clear"), ("sentence", "A group of words that expresses a complete idea"), ("subject", "Who or what a sentence is about"), ("action", "What happens"), ("describe", "To tell more about something")],
    [_video("Nouns, verbs and adjectives: word jobs", "mN2hO5R76Vg", "Watch for the naming, doing and describing words. Pause after each example and name the word job.", "Read the worked example aloud and sort the words there instead.", ("Which word type names things?", ["Noun", "Verb", "Adjective"], 0, "Nouns name things."))],
    _sort("Sort the word jobs", "Put each word from The Rainy Race into noun, verb or adjective.", ["Noun", "Verb", "Adjective"], [("Mia", 0), ("creek", 0), ("boat", 0), ("wind", 0), ("carried", 1), ("ran", 1), ("blew", 1), ("splashed", 1), ("wet", 2), ("small", 2), ("blue", 2), ("cheerful", 2)]),
    [_wc("Which is a noun?", ["sail", "quickly", "bright"], 0, "Sail names a thing."), _wc("Which is a verb?", ["water", "ran", "small"], 1, "Ran is an action."), _wc("Which is an adjective?", ["blue", "boat", "floated"], 0, "Blue describes a noun."), _wc("Which vowel team is in rain?", ["ai", "ay", "ee"], 0, "Rain has ai."), _wc("Which is correct?", ["todai", "today", "todey"], 1, "Today ends with ay."), _wc("Which is correct?", ["sleep", "slep", "sleepe"], 0, "Sleep has ee."), _wc("Which is correct?", ["clene", "clean", "cleen"], 1, "Clean has ea."), _wc("Which is correct?", ["float", "flote", "floet"], 0, "Float has oa.")],
    [{"key":"partA","label":"Part A: word hunt","hint":"Three nouns, three verbs and three adjectives from The Rainy Race."}, {"key":"partB","label":"Part B: label the sentence","hint":"The strong wind blew across the water."}, {"key":"partC","label":"Part C: improve it","hint":"Improve: The dog went to the boat."}, {"key":"partD","label":"Part D: vowel teams","hint":"Mark the vowel team in rain, today, sleep, clean, float and please."}, {"key":"hunt","label":"Nouns, verbs and adjectives","hint":"Four of each from the text."}, {"key":"label","label":"Label one sentence","hint":"Copy one sentence and label nouns, verb and adjectives."}, {"key":"improve","label":"Improve Mia's sentence","hint":"Use one precise verb and two adjectives."}, {"key":"write","label":"Two original story sentences","hint":"Include and label a noun, verb and adjective in each."}, {"key":"spelling","label":"Spelling words","hint":"Type the six words and mark the vowel team."}],
    ["Calling every describing word a noun", "Choosing the nearest word instead of asking what job it does", "Adding many adjectives that do not help the picture", "Using a weak verb when an exact one is available", "Spelling ai, ay, ee, ea or oa incorrectly"],
    ["Read a page of your current book and collect five nouns, verbs and adjectives.", "Use three precise verbs in your next story plan."],
    "Part A: nouns may include Mia, morning, boat, creek, dog, Max, wind, water, sail, waves; verbs include carried, ran, blew, placed, caught, raced, laughed, splashed; adjectives include wet, small, blue, cheerful, strong, bright, shallow. Part B: wind and water are nouns; blew is the verb; strong describes wind. Part C: accept any clear improvement with a precise verb and two useful adjectives, for example: 'The muddy dog raced to the small blue boat.' Part D: rain (ai), today (ay), sleep (ee), clean (ea), float (oa), please (ea). Main task: accept correct examples from the text and original sentences with correctly identified word jobs. Quiz answers: naming word; action/state; describes a noun; sail; splashed; small and blue; raced; creek; ea; The muddy dog splashed.",
)

LESSON["spelling"] = {"focus":"Vowel teams ai, ay, ee, ea, oa", "teaching":"Two vowels can work as a team to make one sound. In this list, ai is in rain, ay ends today, ee is in sleep, ea is in clean and please, and oa is in float.", "words":[_w("rain","r-ai-n","ai is in the middle"),_w("today","tod-ay","ay is at the end"),_w("sleep","sl-ee-p","ee makes long e"),_w("clean","cl-ea-n","ea makes long e"),_w("float","fl-oa-t","oa makes long o"),_w("please","pl-ea-se","ea makes long e")], "check":[_c("Which vowel team is in float?",["oa","ea","ai"],0,"Float has oa."),_c("Which is spelled correctly?",["plese","please","pleaze"],1,"Please has ea.")]}
LESSON["spelling_focus"] = "Vowel teams ai, ay, ee, ea, oa"
LESSON["hoard_words"] = list(WORDS)
