"""Stage 2 English, Block A (narrative writing), week 6, lessons 1 to 4.
Pass 1: lessons only. Videos are empty and the module is not yet registered in lesson_library.py.
Keys use the prefix a6."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A6L1 = build(
    "s2-eng-a6-l1-problem-and-complication", "Problem and Complication",
    "Learn how a story's problem drives the plot and how a complication makes it harder.",
    "Reading and writing: problem and complication",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies the problem and complications in a story and how they build the plot.",
     "EN2-CWT-01": "Plans and writes a problem and complication for an original story.",
     "EN2-VOCAB-01": "Learns the terms problem, complication, obstacle, goal and consequence."},
    "We are learning how a problem and complications make a story exciting.",
    ["I can name the problem in a story.", "I can say what the character wants.", "I can name a complication.", "I can explain why complications keep a story moving.", "I can write a problem and complication of my own."],
    ["problem", "complication", "goal", "obstacle", "consequence"],
    ["Paper or notebook", "Pencil", "Your story map and plot arc", "A story you are reading (your parent will help you choose)"],
    "Child has met the plot arc and the stages of a narrative. The problem and complication are taught from the beginning.",
    "A story needs something to go wrong. Without a PROBLEM there is nothing to worry about and nothing to solve. The problem is what the main character must deal with.\n\nOnce the character starts to deal with it, things often get harder. This is the COMPLICATION. A complication is a new event that makes the problem bigger or the solution harder.\n\nIn this lesson you will find problems and complications in stories, and then write your own.",
    [
        _step("1", "Goal and problem",
              "Most stories begin with a character who WANTS something. This is the GOAL. It might be to find a lost pet, win a race or make a friend.\n\nThe PROBLEM is whatever stops the character from reaching the goal. It can be a person, a place, an event or something inside the character, such as fear.\n\nGoal: Pip wants to sail his boat down the river.\nProblem: The boat has a hole in it.\n\nA good problem matters to the character and is not too easy to fix. Ask: what does the character want, and what stands in the way?",
              "Goal: win the school race. Problem: a twisted ankle the day before.",
              "Goal is what they want. Problem is what stops them.",
              ("What is a goal?", ["What the character wants", "The ending", "The setting"], 0, "The goal is what the character wants.")),
        _step("2", "Types of problem",
              "Problems come in a few common types.\n\nCharacter against character: a rival, a bully, a villain.\nCharacter against nature: a storm, a flood, getting lost.\nCharacter against self: fear, shyness, a bad temper.\nCharacter against a puzzle: a mystery, a missing object, a locked door.\n\nThe type affects the kind of story. A character against nature feels like an adventure. A character against self often makes a thoughtful story.\n\nChoose a problem that suits your mood and setting. A spooky setting suits a mystery.",
              "A girl is afraid of the dark but must cross the cellar to find the missing key: character against self and puzzle.",
              "Problems can come from people, nature, the self or a puzzle.",
              ("A storm is which type?", ["Against nature", "Against self", "Against character"], 0, "A storm is a force of nature.")),
        _step("3", "What is a complication?",
              "A COMPLICATION is something extra that makes the problem harder just when the character thinks they are getting somewhere.\n\nProblem: Pip's boat has a hole.\nHe patches it with mud and tries again.\nComplication: A sudden storm arrives, and the patch washes away.\n\nComplications raise the stakes. They give the reader something to worry about. Stories often have two or three of them.\n\nA complication is not just more of the same. It is a new obstacle that makes the character think again.",
              "Problem: lost dog. First try: search the park. Complication: it begins to rain and the paw prints wash away.",
              "A complication makes the problem harder.",
              ("What does a complication do?", ["Makes the problem harder", "Solves the problem", "Ends the story"], 0, "Complications add difficulty.")),
        _step("4", "Causes and consequences",
              "Good plots link events in a chain. One event causes the next, and each choice has a CONSEQUENCE.\n\nPip uses mud to patch the hole (choice). The mud is not strong enough (consequence). The storm washes it away (complication). Now he must find a new way (new problem).\n\nWhen you plan, use the word BECAUSE or SO to link events. 'The boat leaked, so Pip patched it. The patch was weak, so it washed away.'\n\nIf events do not link, the story feels like a list of random things. A chain keeps the reader following.",
              "Chain: She skipped breakfast, so she was late. Because she was late, she missed the bus.",
              "Link events with because and so.",
              ("Which word links cause and effect?", ["because", "banana", "beside"], 0, "Because shows a cause.")),
        _step("5", "Plan your problem and complication",
              "Now plan the middle of a story of your own.\n\n1. Write your character and their goal.\n2. Write the main problem.\n3. Write the character's first attempt to solve it.\n4. Write a complication that makes it harder.\n5. Link them with because or so.\n6. Write 4 to 6 sentences telling this part of the story.\n\nDo not solve the problem yet. Leave it unresolved so the reader wants to read on.",
              "Model: Ella wanted to get her kite out of the tall tree. She tried to climb it, but the branch was wet, so she slipped. Then the wind rose and the kite tore free and floated over the fence.",
              "Goal, problem, attempt, complication.",
              ("Should you solve the problem now?", ["No, leave it open", "Yes, at once", "Only in the title"], 0, "The solution belongs near the end.")),
    ],
    "Model answers. Goal: what the character wants. Problem: what stops them. Complication: a new event that makes it harder. Example chain: The boat leaked, so Pip patched it with mud. The patch was weak, so a storm washed it away. Paragraph: Ella wanted to get her kite out of the tall tree. She tried to climb it, but the branch was wet, so she slipped. Then the wind rose and the kite tore free and floated over the fence.",
    "1) Name the goal and problem in a story your parent chooses. 2) Sort six problems into types. 3) Add a complication to three problems. 4) Write two cause and effect sentences. 5) Plan your character, goal, problem and complication. 6) Write 4 to 6 sentences telling this part.",
    "Write a 4 to 6 sentence paragraph with a goal, a problem, a first attempt and a complication. Do not solve the problem. Upload a photo of your writing.",
    CHECK,
    "Does my character have a goal? Is there a clear problem? Did I include a first attempt? Did I add a complication that makes it harder? Did I link events with because or so? Did I leave it unsolved?",
    [
        _q("A goal is...", ["what the character wants", "the setting", "the title"], 0, "A goal is what they want."),
        _q("A problem is...", ["what stops the character reaching the goal", "a kind of verb", "the last line"], 0, "It stands in the way."),
        _q("A complication...", ["makes the problem harder", "solves the problem", "names the author"], 0, "It raises the difficulty."),
        _q("A storm is a problem against...", ["nature", "self", "a friend"], 0, "A storm is nature."),
        _q("Fear of the dark is a problem against...", ["self", "nature", "a puzzle only"], 0, "The fear is inside the character."),
        _q("Which word links events?", ["because", "beside", "between"], 0, "Because shows cause."),
        _q("When do you solve the problem?", ["Near the end", "In the first line", "Never"], 0, "Solution comes late."),
    ],
    "Upload a photo of your problem and complication paragraph.",
    "Take a favourite story and list the problem and every complication in order. How many are there?",
    [("problem", "What stops the character reaching their goal."), ("complication", "A new event that makes the problem harder."), ("goal", "What the main character wants."), ("obstacle", "Something that gets in the way."), ("consequence", "What happens because of a choice or event.")],
    [],
    _sort("Problem or solution", "Is each idea a problem, a complication or a goal? Tap a group, then Check.",
          ["Goal", "Problem", "Complication"],
          [("to find the lost key", 0), ("to win the race", 0), ("the door is locked", 1), ("a twisted ankle", 1), ("a storm washes the clues away", 2), ("the map is torn in half", 2)]),
    [
        _wc("What a character wants is the ___.", ["goal", "glossary", "gap"], 0, "Goal."),
        _wc("A new event that makes things harder is a ___.", ["complication", "conclusion", "comma"], 0, "Complication."),
        _wc("Something that gets in the way is an ___.", ["obstacle", "orientation", "option"], 0, "Obstacle."),
        _wc("Which is spelt correctly?", ["complication", "complicashun", "complicasion"], 0, "Ends -tion."),
        _wc("Which is spelt correctly?", ["consequence", "consiquence", "consequense"], 0, "Consequence ends -ence."),
    ],
    [
        {"key": "story", "label": "Goal and problem", "hint": "From a story your parent chooses."},
        {"key": "chain", "label": "Cause and effect", "hint": "Two sentences using because or so."},
        {"key": "paragraph", "label": "My paragraph", "hint": "Goal, problem, attempt and complication."},
    ],
    ["A story with no real problem.", "Solving the problem too soon.", "A complication that is just more of the same.", "Events that do not link.", "Forgetting what the character wants."],
    [{"title": "Problem Pairs", "description": "Write three different problems and a complication for each, using a different problem type every time.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that there is a clear goal, a problem, a first attempt, a complication that makes things harder, events linked by cause, and no solution yet. Sorter: Goal: find the lost key, win the race. Problem: the door is locked, a twisted ankle. Complication: storm washes clues away, map torn in half.",
)

A6L2 = build(
    "s2-eng-a6-l2-building-tension", "Building Tension",
    "Learn how writers slow down the action and use language to make readers feel suspense.",
    "Writing: building tension",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01"],
    {"EN2-CWT-01": "Primary. Builds tension through sentence length, detail, pacing and word choice.",
     "EN2-RECOM-01": "Identifies the techniques an author uses to create suspense.",
     "EN2-VOCAB-01": "Learns the terms tension, suspense, pace, short sentence and cliffhanger."},
    "We are learning how to build tension so the reader is desperate to find out what happens.",
    ["I can say what tension is.", "I can slow the pace with detail.", "I can use short sentences for impact.", "I can use senses and thoughts to build suspense.", "I can write a tense scene."],
    ["tension", "suspense", "pace", "short sentence", "cliffhanger"],
    ["Paper or notebook", "Pencil", "Your problem and complication from last lesson"],
    "Child knows about problem, complication and show, don't tell. Tension techniques are taught from the beginning.",
    "TENSION is the feeling of worry and excitement as the reader waits to find out what will happen. SUSPENSE is another word for it.\n\nWriters build tension on purpose. They slow down the moment just before something happens, they use the senses, and they play with sentence length.\n\nIn this lesson you will learn four techniques and then write a tense scene.",
    [
        _step("1", "Slow down the moment",
              "The key technique is to stretch time. When something big is about to happen, do not rush. Describe each small step.\n\nRushed: 'He opened the door and saw a shadow.'\n\nSlowed: 'Leo reached for the handle. It was cold. He turned it, a centimetre at a time. The door creaked open, just a crack.'\n\nThe reader waits with the character. The PACE of the story is how fast or slow events move. Slow pace builds tension.\n\nThis only works at the key moment. If everything is slow, the story drags.",
              "Stretching: One step. Another step. The stairs groaned.",
              "Slow the pace at the key moment.",
              ("How do you build tension?", ["Slow down the key moment", "Rush through it", "Skip it"], 0, "Stretching time builds tension.")),
        _step("2", "Short sentences",
              "Long sentences let the reader relax. Short sentences hit hard.\n\nMix them. Use a longer sentence with detail, then a very short one.\n\n'The cellar stairs wound down into darkness, and each step seemed to take longer than the last. Then the light went out.'\n\nOr even shorter: 'Silence. Then, a scratch.'\n\nA one-word or two-word sentence is called a short sentence for effect. Use it once or twice only. If every sentence is short, it loses its power.",
              "Long then short: He crept down the long, dark corridor, listening to every sound. Footsteps.",
              "Mix long and short sentences.",
              ("Which sentence adds suspense?", ["Then, a scratch.", "The weather was nice.", "He had lunch."], 0, "The short line is tense.")),
        _step("3", "Senses and thoughts",
              "Tension grows when the reader feels what the character feels.\n\nSounds are very powerful. A drip. A creak. A whisper that stops.\nTouch: cold fingers, a prickle on the neck.\nThoughts: 'What was that?' 'Was someone there?'\n\nUse a question in the character's head to show worry. Do not overuse it.\n\nShow the body: 'His heart hammered. He held his breath.' Use fresh details, not the same ones every time.",
              "Sound plus thought: A floorboard creaked above. Had he locked the back door?",
              "Use sounds, touch and worried thoughts.",
              ("Which is a worried thought?", ["Was someone there?", "It was Tuesday.", "The sky was blue."], 0, "A worried question builds tension.")),
        _step("4", "Word choice and cliffhangers",
              "Choose strong verbs and precise words to build tension. 'Crept', 'lurked', 'flickered' and 'gripped' are better than 'went', 'was' and 'held'.\n\nA CLIFFHANGER ends a part of the story at the most exciting point, leaving the reader desperate to find out what happens.\n\n'The door swung open. Behind it, something moved.'\n\nUse cliffhangers at the end of a chapter or scene. Stop before you answer the question.\n\nFor tension, the order of information matters. Hold back the big reveal until after the build-up.",
              "Cliffhanger: The handle turned slowly. And then it stopped.",
              "Strong verbs build tension. A cliffhanger ends on the peak.",
              ("A cliffhanger ends...", ["at an exciting point", "with a happy ending", "with a recap"], 0, "It stops at the most exciting moment.")),
        _step("5", "Write a tense scene",
              "Now write 6 to 8 sentences of a tense scene. Use the complication from your last lesson if you want.\n\n1. Choose the moment just before something happens.\n2. Slow it down with small steps.\n3. Use at least two senses.\n4. Include one worried thought.\n5. Use one very short sentence.\n6. End with a cliffhanger.\n\nRead it aloud and slow down on the slow parts. Does it make you want to know what happens next?",
              "Model: Mia crept along the dark hallway. One step. Another. The air smelt of damp earth. Somewhere ahead, something scratched against wood. Was it the cat? The handle began to turn.",
              "Slow, sense, thought, short, cliffhanger.",
              ("How should a tense scene end?", ["With a cliffhanger", "With a recap", "With the title"], 0, "It stops at the peak.")),
    ],
    "Model answers. Tension: worry and excitement while waiting for what happens. Pace: how fast events move. Slowing: Leo reached for the handle. It was cold. He turned it, a centimetre at a time. Short sentence for effect: Silence. Then, a scratch. Cliffhanger: The handle turned slowly. And then it stopped. Sample scene: Mia crept along the dark hallway. One step. Another. The air smelt of damp earth. Somewhere ahead, something scratched against wood. Was it the cat? The handle began to turn.",
    "1) Rewrite a rushed sentence by slowing it down in three steps. 2) Write one long sentence and one short one for effect. 3) Write two senses and one worried thought for a dark place. 4) Write a cliffhanger for a closed door. 5) Plan a tense scene. 6) Write a 6 to 8 sentence tense scene.",
    "Write a 6 to 8 sentence tense scene that ends in a cliffhanger. Upload a photo of your writing.",
    CHECK,
    "Did I slow down the key moment? Did I use at least two senses? Did I use a worried thought? Did I include one short sentence for effect? Did I end with a cliffhanger? Is it 6 to 8 sentences?",
    [
        _q("Tension is...", ["worry and excitement while waiting", "a kind of noun", "a title"], 0, "Tension is suspense."),
        _q("Pace is...", ["how fast events move", "the setting", "the narrator"], 0, "Pace is speed."),
        _q("Slowing the moment makes tension...", ["grow", "vanish", "end"], 0, "It builds tension."),
        _q("A short sentence for effect should be used...", ["once or twice", "in every line", "never"], 0, "Use sparingly."),
        _q("Which is a strong verb?", ["lurked", "was", "did"], 0, "Lurked is vivid."),
        _q("A cliffhanger ends...", ["at the peak of excitement", "with a joke", "with the answer"], 0, "It leaves the question open."),
        _q("Which sense is powerful for tension?", ["sound", "none", "only taste"], 0, "Sounds are very effective."),
    ],
    "Upload a photo of your tense scene.",
    "Read a tense page from a book of your choice. Find one place where the author slows down time and one short sentence for effect.",
    [("tension", "A feeling of worry and excitement while waiting for what happens."), ("suspense", "Another word for tension in a story."), ("pace", "How fast or slow events move."), ("short sentence", "A very brief sentence used for effect."), ("cliffhanger", "An ending at an exciting point that leaves the reader wondering.")],
    [],
    _sort("Tension or calm", "Does each sentence build tension or feel calm? Tap a group, then Check.",
          ["Tense", "Calm"],
          [("Footsteps. Closer now.", 0), ("The handle began to turn.", 0), ("A shadow slid across the wall.", 0), ("The sun shone on the garden.", 1), ("They ate lunch by the creek.", 1), ("The children played happily.", 1)]),
    [
        _wc("A feeling of worried waiting is ___.", ["tension", "tenses", "tennis"], 0, "Tension."),
        _wc("How fast events move is the ___.", ["pace", "place", "page"], 0, "Pace."),
        _wc("An exciting ending that leaves a question is a ___.", ["cliffhanger", "cliffnote", "clipboard"], 0, "Cliffhanger."),
        _wc("Which is spelt correctly?", ["suspense", "suspence", "suspens"], 0, "Suspense ends -ense."),
        _wc("Which is spelt correctly?", ["flickered", "flikered", "flickerd"], 0, "Flickered has ck."),
    ],
    [
        {"key": "slow", "label": "Slowed moment", "hint": "A rushed sentence stretched into three steps."},
        {"key": "cliff", "label": "Cliffhanger", "hint": "A cliffhanger for a closed door."},
        {"key": "scene", "label": "Tense scene", "hint": "6 to 8 sentences ending in a cliffhanger."},
    ],
    ["Rushing the key moment.", "Making every sentence short.", "Explaining what is behind the door too soon.", "Using the same body clues every time.", "Ending with a solution instead of a cliffhanger."],
    [{"title": "Stretch the Moment", "description": "Choose a short action, such as opening a letter, and stretch it into a tense six-sentence moment.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the key moment is slowed down with small steps, at least two senses are used, there is a worried thought, one short sentence for effect appears, the scene ends on a cliffhanger, and it is 6 to 8 sentences. Sorter: Tense: Footsteps. Closer now; The handle began to turn; A shadow slid across the wall. Calm: The sun shone on the garden; They ate lunch by the creek; The children played happily.",
)

A6L3 = build(
    "s2-eng-a6-l3-adjectives-and-noun-group-detail", "Adjectives and Noun-Group Detail",
    "Learn how adjectives and noun groups paint precise pictures without overloading a sentence.",
    "Language: adjectives and noun groups",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Expands noun groups with adjectives, nouns, and prepositional phrases for precise description.",
     "EN2-VOCAB-01": "Learns the terms adjective, noun group, determiner, classifier, and prepositional phrase.",
     "EN2-RECOM-01": "Identifies noun groups and the detail they add in a text."},
    "We are learning to build detailed noun groups that give a clear picture.",
    ["I can say what an adjective does.", "I can build a noun group with several parts.", "I can add detail after the noun.", "I can order adjectives naturally.", "I can improve my own sentences."],
    ["adjective", "noun group", "determiner", "classifier", "prepositional phrase"],
    ["Paper or notebook", "Pencil", "A paragraph from a story you have read"],
    "Child has met noun groups in the nouns lesson. Adjectives and extended noun groups are taught from the beginning.",
    "An ADJECTIVE describes a noun. It tells us what something is like: a tall tree, a cold wind, a frightened child.\n\nA NOUN GROUP is a noun with all the words that describe it. 'The tall tree' and 'the tall tree beside the river' are both noun groups.\n\nGood description does not mean piling on adjectives. It means choosing the right ones and placing detail around the noun in a useful order.",
    [
        _step("1", "What adjectives do",
              "Adjectives answer questions about a noun: What kind? How many? Which one? How big?\n\nWhat kind: a mysterious letter.\nHow many: three hungry crows.\nWhich: that broken window.\nHow big: an enormous cave.\n\nThey can come before the noun or after a verb such as is or seemed. 'The night was silent.'\n\nSimple adjectives like nice, good and big are weak. Look for more precise ones: charming, delicious, enormous.",
              "Find the adjective: The icy wind howled. Icy.",
              "Adjectives describe nouns.",
              ("Which word is an adjective?", ["enormous", "enormously", "enormity"], 0, "Enormous describes a noun.")),
        _step("2", "Parts of a noun group",
              "A noun group can have several parts.\n\nDETERMINER: the, a, my, those, three.\nADJECTIVE: old, rusty, small.\nCLASSIFIER: a noun or word that says what kind. In 'garden gate', garden is a classifier.\nHEAD NOUN: the main word. In 'the old wooden gate', gate is the head noun.\n\nExample: those three rusty garden gates. Determiner, number, adjective, classifier, head noun.\n\nYou do not need all parts every time. Choose what makes the picture clear.",
              "The old wooden gate: determiner the, adjective old, classifier wooden, head noun gate.",
              "A noun group has a head noun and describing words.",
              ("In 'the rusty gate', the head noun is...", ["gate", "the", "rusty"], 0, "Gate is the main word.")),
        _step("3", "Detail after the noun",
              "You can add detail AFTER the noun with a prepositional phrase. This starts with a word like in, on, with, beside, behind or under.\n\n'The cottage beside the river'\n'A girl with curly red hair'\n'The box under the bed'\n\nThis lets you give more information without a long string of adjectives before the noun.\n\nCompare: 'The old, small, dusty, cracked, brown box' (too many) with 'The small box with a cracked lid' (clear).",
              "The dog with the muddy paws raced across the clean floor.",
              "Add detail after the noun with a prepositional phrase.",
              ("Which is a prepositional phrase?", ["beside the river", "very tall", "ran quickly"], 0, "It begins with beside.")),
        _step("4", "Order and choice",
              "When you use several adjectives, there is a natural order in English: opinion, size, age, colour, material, then the noun.\n\nA lovely small old red wooden boat. That sounds natural.\nA wooden red old small lovely boat. That sounds odd.\n\nUsually two adjectives are enough. Choose ones that add something new.\n\nAlso avoid repeating weak adjectives. Instead of 'a very big dog', try 'an enormous dog'. A strong adjective replaces very plus a weak one.",
              "Better: a tiny, ancient book. Not: a very small, very old book.",
              "Use two strong adjectives, not five weak ones.",
              ("How many adjectives are usually enough?", ["Two", "Eight", "Zero"], 0, "Two well-chosen ones work best.")),
        _step("5", "Improve your sentences",
              "Now improve a plain paragraph.\n\n1. Write four plain sentences about a place or character.\n2. Improve each noun group using one of the ideas: a precise adjective, a classifier, or a prepositional phrase.\n3. Underline each noun group.\n4. Check that no noun group has more than three describing words before the noun.\n5. Read it aloud for flow.\n\nModel: The dog ran. The scruffy brown dog from next door raced across the damp grass.",
              "Check: the scruffy brown dog (adjectives) from next door (prepositional phrase).",
              "Precise adjective, classifier, detail after the noun.",
              ("What should you do after you improve a noun group?", ["Read it aloud", "Delete it", "Add ten adjectives"], 0, "Reading aloud checks the flow.")),
    ],
    "Model answers. Adjective: a word that describes a noun. Noun group: a noun with the words that describe it. In 'the old wooden gate', the determiner is the, adjective old, classifier wooden, head noun gate. Detail after the noun: the cottage beside the river. Improved sentence: The scruffy brown dog from next door raced across the damp grass.",
    "1) Find the adjectives in six sentences. 2) Label the parts of three noun groups. 3) Add a prepositional phrase to four nouns. 4) Order five sets of adjectives naturally. 5) Replace very plus a weak adjective with a strong one in five phrases. 6) Improve a four-sentence paragraph.",
    "Rewrite four plain sentences with detailed noun groups, using at least one classifier and one prepositional phrase. Underline each noun group. Upload a photo of your writing.",
    CHECK,
    "Did I use precise adjectives? Did I use a classifier? Did I use a prepositional phrase after a noun? Do my adjectives follow a natural order? Did I avoid too many adjectives? Did I underline each noun group?",
    [
        _q("An adjective describes a...", ["noun", "verb", "full stop"], 0, "Adjectives describe nouns."),
        _q("The head noun in 'the old wooden gate' is...", ["gate", "old", "wooden"], 0, "Gate is the main word."),
        _q("A classifier says...", ["what kind of thing it is", "how fast", "when"], 0, "For example, garden in garden gate."),
        _q("Which is a prepositional phrase?", ["under the bed", "very big", "quickly ran"], 0, "It starts with under."),
        _q("Which order sounds natural?", ["a small old red boat", "a red old small boat", "a boat red small old"], 0, "Size, age, colour, then noun."),
        _q("Which replaces 'very big'?", ["enormous", "bigger", "big"], 0, "Enormous is a strong adjective."),
        _q("A noun group is...", ["a noun with its describing words", "a list of verbs", "a title"], 0, "A noun plus detail."),
    ],
    "Upload a photo of your improved sentences.",
    "Choose a page from a book of your choice and find three noun groups with detail after the noun. Copy them and underline the head nouns.",
    [("adjective", "A word that describes a noun."), ("noun group", "A noun with all the words that describe it."), ("determiner", "A word like the, a, my or three that comes before a noun."), ("classifier", "A word that says what kind of thing a noun is, such as garden in garden gate."), ("prepositional phrase", "A phrase that begins with a word like in, on or beside.")],
    [],
    _sort("Noun group parts", "Which part of the noun group is each word? Tap a group, then Check.",
          ["Determiner", "Adjective", "Head noun"],
          [("the", 0), ("those", 0), ("rusty", 1), ("enormous", 1), ("gate", 2), ("cave", 2)]),
    [
        _wc("A word that describes a noun is an ___.", ["adjective", "adverb", "article"], 0, "Adjective."),
        _wc("A noun with its describing words is a noun ___.", ["group", "gap", "grid"], 0, "Noun group."),
        _wc("The main word in a noun group is the ___ noun.", ["head", "hand", "heavy"], 0, "Head noun."),
        _wc("Which is spelt correctly?", ["enormous", "enormus", "enormouse"], 0, "Enormous ends -ous."),
        _wc("Which is spelt correctly?", ["mysterious", "mistereous", "mysterius"], 0, "Mysterious ends -ious."),
    ],
    [
        {"key": "parts", "label": "Noun group parts", "hint": "Labelled parts of three noun groups."},
        {"key": "order", "label": "Adjective order", "hint": "Five sets in natural order."},
        {"key": "paragraph", "label": "Improved sentences", "hint": "Four sentences with underlined noun groups."},
    ],
    ["Using too many adjectives before the noun.", "Using vague adjectives like nice and good.", "Putting adjectives in an unnatural order.", "Using very plus a weak adjective.", "Forgetting detail can come after the noun."],
    [{"title": "Noun Group Builder", "description": "Start with a plain noun, such as cat, and build it into a rich noun group in five steps, adding one part each time.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that adjectives are precise, a classifier and a prepositional phrase are used, adjectives follow a natural order, no noun group is overloaded, and noun groups are underlined. Sorter: Determiner: the, those. Adjective: rusty, enormous. Head noun: gate, cave.",
)

A6L4 = build(
    "s2-eng-a6-l4-spelling-prefixes-un-re-dis", "Spelling: Prefixes un-, re-, dis-",
    "Learn how prefixes change a word's meaning and how to spell words that use them.",
    "Spelling: prefixes",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-CWT-01"],
    {"EN2-SPELL-01": "Primary. Spells words with the prefixes un-, re- and dis- accurately.",
     "EN2-VOCAB-01": "Uses prefixes to work out and extend word meaning.",
     "EN2-CWT-01": "Uses prefixed words correctly in sentences."},
    "We are learning how the prefixes un-, re- and dis- change the meaning of a word and how to spell them.",
    ["I can say what a prefix is.", "I can say what un-, re- and dis- mean.", "I can add a prefix without changing the spelling of the base word.", "I can spell ten prefixed words.", "I can use prefixed words in sentences."],
    ["prefix", "base word", "un-", "re-", "dis-"],
    ["Paper or notebook", "Pencil", "A dictionary (your parent will help)"],
    "Child has seen prefixes and suffixes in earlier spelling work. The prefixes un-, re- and dis- are taught from the beginning.",
    "A PREFIX is a group of letters added to the start of a word to change its meaning. The word it joins is called the BASE WORD.\n\nun + happy = unhappy\nre + build = rebuild\ndis + appear = disappear\n\nPrefixes are useful because they help you work out new words and spell them. When you add a prefix, the spelling of the base word does not change.",
    [
        _step("1", "What is a prefix?",
              "A prefix goes at the START of a word. It cannot stand alone.\n\nThe base word is the word you start with. 'Happy' is the base word in 'unhappy'.\n\nPrefixes change meaning. 'Happy' and 'unhappy' are opposites. 'Build' and 'rebuild' are not opposites, but 'rebuild' means to build again.\n\nAsk: what is the base word, and what does the prefix do to it?",
              "unlock: prefix un-, base word lock. replay: prefix re-, base word play.",
              "A prefix is added at the start to change the meaning.",
              ("Where does a prefix go?", ["At the start of a word", "At the end", "In the middle"], 0, "A prefix goes at the start.")),
        _step("2", "The prefix un-",
              "UN- usually means not or the opposite of.\n\nhappy, unhappy. fair, unfair. kind, unkind. lock, unlock. tidy, untidy. usual, unusual.\n\nNotice the spelling: the base word keeps all its letters. 'Un' + 'usual' = unusual, with one n from un and the u from usual. 'Un' + 'necessary' = unnecessary, with two n letters.\n\nDo not drop or double any letters. Just join the two parts.",
              "un + tidy = untidy. un + natural = unnatural (nn).",
              "un- means not or the opposite. Keep every letter.",
              ("What does un- usually mean?", ["Not", "Again", "Before"], 0, "Un- means not or opposite.")),
        _step("3", "The prefix re-",
              "RE- usually means again or back.\n\nbuild, rebuild. write, rewrite. play, replay. fill, refill. turn, return. pay, repay.\n\nThe spelling stays the same. 're' + 'appear' = reappear (pp).\n\nWhen a word starts with e, be careful: 're' + 'enter' = reenter or re-enter. A hyphen can help show the two parts. Many dictionaries use re-enter.\n\nPractise with a short sentence: 'I will rewrite my story and read it again.'",
              "re + start = restart. re + think = rethink.",
              "re- means again or back.",
              ("What does re- mean?", ["Again", "Not", "Under"], 0, "Re- means again or back.")),
        _step("4", "The prefix dis-",
              "DIS- usually means not, the opposite of, or to take away.\n\nagree, disagree. appear, disappear. like, dislike. obey, disobey. connect, disconnect. honest, dishonest.\n\nWatch for the double s. 'dis' + 'satisfied' = dissatisfied, with ss. 'dis' + 'appear' = disappear, with one s and one p pair.\n\nTrap: not every word that starts with dis is a prefixed word. Disaster and discuss do not break into a prefix and a base word that you know. Check by asking: is there a base word left?",
              "dis + appear = disappear. dis + satisfied = dissatisfied.",
              "dis- means not, opposite, or remove.",
              ("Which is spelt correctly?", ["disappear", "dissapear", "disapear"], 0, "Dis + appear.")),
        _step("5", "Practise and use them",
              "Now practise.\n\n1. Look, say, cover, write, check these ten words: unhappy, unfair, untidy, unusual, rebuild, rewrite, reappear, disagree, disappear, dislike.\n2. Underline the prefix in each.\n3. Write the base word beside each.\n4. Write four sentences, each using a different prefixed word.\n5. Check by reading each sentence aloud.\n6. Test yourself with a parent reading the words.\n\nWhen you meet a new long word, look for a prefix first. It can help you read and spell it.",
              "Sentence: The magician made the rabbit disappear, then made it reappear.",
              "Find the prefix, keep the base word, check the spelling.",
              ("What should you do when you meet a new word?", ["Look for a prefix and a base word", "Skip it", "Guess the first letter"], 0, "Splitting a word helps you read and spell it.")),
    ],
    "Model answers. A prefix is added at the start of a base word to change its meaning. un-: not or opposite (unhappy, unfair, untidy, unusual, unnecessary). re-: again or back (rebuild, rewrite, reappear, return). dis-: not, opposite, remove (disagree, disappear, dislike, dissatisfied). Sample sentence: The magician made the rabbit disappear, then made it reappear.",
    "1) Split ten words into prefix and base word. 2) Add un-, re- or dis- to eight base words. 3) Match five prefixed words to their meanings. 4) Spell ten words with look, say, cover, write, check. 5) Write four sentences. 6) Get a spelling test from a parent.",
    "Write four sentences, each with a different prefixed word, then do a ten word spelling test. Upload a photo of your sentences and your test.",
    CHECK,
    "Did I keep every letter of the base word? Did I spell the double letters correctly (unnecessary, dissatisfied)? Did I use each prefix at least once? Did I use four different prefixed words in my sentences? Did I check my spelling?",
    [
        _q("A prefix is added...", ["at the start of a word", "at the end", "in the middle"], 0, "Prefixes come first."),
        _q("un- usually means...", ["not", "again", "over"], 0, "Un- means not."),
        _q("re- usually means...", ["again", "not", "under"], 0, "Re- means again."),
        _q("dis- usually means...", ["not or opposite", "again", "before"], 0, "Dis- means not or opposite."),
        _q("Which is spelt correctly?", ["unnecessary", "unecessary", "unnessary"], 0, "Un + necessary."),
        _q("Which is spelt correctly?", ["disappear", "dissapear", "disapear"], 0, "Dis + appear."),
        _q("Which is spelt correctly?", ["dissatisfied", "disatisfied", "dissatisfyed"], 0, "Dis + satisfied."),
        _q("When you add a prefix, the base word...", ["keeps its spelling", "loses a letter", "changes completely"], 0, "Keep all the letters."),
    ],
    "Upload a photo of your four sentences and your spelling test.",
    "Look for five more words that begin with un-, re- or dis- in a book of your choice. Split each into prefix and base word.",
    [("prefix", "Letters added to the start of a word to change its meaning."), ("base word", "The word a prefix is added to."), ("un-", "A prefix meaning not or the opposite of."), ("re-", "A prefix meaning again or back."), ("dis-", "A prefix meaning not, the opposite of, or remove.")],
    [],
    _sort("Prefix sorter", "Which prefix does each word start with? Tap a group, then Check.",
          ["un-", "re-", "dis-"],
          [("unhappy", 0), ("unusual", 0), ("rebuild", 1), ("rewrite", 1), ("disagree", 2), ("disappear", 2)]),
    [
        _wc("Letters added to the start of a word are a ___.", ["prefix", "suffix", "syllable"], 0, "Prefix."),
        _wc("The word a prefix is added to is the ___ word.", ["base", "back", "big"], 0, "Base word."),
        _wc("Which is spelt correctly?", ["unnatural", "unatural", "unnatrual"], 0, "Un + natural."),
        _wc("Which is spelt correctly?", ["dislike", "dislik", "dyslike"], 0, "Dis + like."),
        _wc("Which is spelt correctly?", ["reappear", "reapear", "reappeer"], 0, "Re + appear."),
    ],
    [
        {"key": "split", "label": "Prefix and base word", "hint": "Ten words split into parts."},
        {"key": "sentences", "label": "Four sentences", "hint": "Four different prefixed words."},
        {"key": "test", "label": "Spelling test", "hint": "Ten words read out by a parent."},
    ],
    ["Dropping a letter from the base word.", "Missing the double n in unnecessary.", "Writing dissapear instead of disappear.", "Confusing un- with in-.", "Thinking every word starting with dis is a prefixed word."],
    [{"title": "Prefix Hunt", "description": "Hunt through a book for ten words with un-, re- or dis-, and make a table of prefix, base word and meaning.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that base words keep all their letters, double letters are correct (unnecessary, unnatural, dissatisfied), each prefix is used, and sentences make sense. Sorter: un-: unhappy, unusual. re-: rebuild, rewrite. dis-: disagree, disappear.",
)

LESSONS = [A6L1, A6L2, A6L3, A6L4]
