# Stage 2 Year 3 Maths lessons 4 and 5 for Ollie. Same structure as the Cartographer quest.
# Not yet registered in LESSON_LIBRARY. No reflection prompts (parent preference).
# Resource links marked 'search' are search pages, not specific items.

MINI_LESSONS = "https://iview.abc.net.au/show/mini-lessons-maths"


def _common(**kw):
    base = {
        "library": True,
        "stage": "S2",
        "year_level": "Year 3",
        "learning_area": "Mathematics",
        "pass_mark": 0.9,
        "reflection_prompts": [],
        "accessibility_notes": "Allow paper strips, counters or real objects throughout. Answers can be spoken instead of written. Reduce the independent task to two parts if needed. Replay any video as often as needed.",
        "source_note": "Outcome codes checked against published NESA code lists. Parent to verify the exact outcome wording on curriculum.nsw.edu.au.",
    }
    base.update(kw)
    return base


LESSON_FRACTIONS = _common(
    seed_key="s2-y3-maths-fractions-pizza-04",
    subject="Partitioned fractions: halves, quarters, eighths, thirds and fifths",
    title="The Pizza Kitchen",
    child_mission="🍕 You run the busiest pizza kitchen in town. Cut pizzas into equal slices, share toppings fairly and work out who gets the biggest slice.",
    duration_minutes=75,
    outcome_codes=["MA2-PF-01", "MAO-WM-01"],
    cross_outcome_codes=[],
    outcome_notes={
        "MA2-PF-01": "Primary. Names and writes unit fractions and other fractions of a whole, finds a fraction of a collection, compares fractions and recognises simple equivalent fractions (steps 1-5, quiz 1-10).",
        "MAO-WM-01": "Working mathematically: models fractions with paper folding and drawings, and explains comparisons (hands-on activity, independent task, rubric).",
    },
    learning_intention="We are learning to name and write fractions of a whole and of a collection, and to compare simple fractions.",
    success_criteria=[
        "I can say why equal parts are needed for fractions.",
        "I can read and write fractions using numerator and denominator.",
        "I can find a fraction of a small collection.",
        "I can compare fractions with the same numerator or the same denominator.",
        "I can show that 1/2 equals 2/4 and 4/8.",
        "I can score 90% or more on the Quest check.",
    ],
    key_vocabulary=["fraction", "equal parts", "half", "quarter", "eighth", "third", "fifth", "numerator", "denominator", "equivalent", "collection"],
    materials=["Paper circles or rectangles (6)", "Scissors and crayons", "Counters (20)", "Ruler", "Device"],
    prior_knowledge="Child can share a whole into two equal parts and name a half and a quarter.",
    common_misconceptions=[
        {"misconception": "The child thinks parts do not need to be equal, so any cut makes quarters.", "fix": "Cut one pizza into four unequal parts and four equal parts. Ask which gives a fair share."},
        {"misconception": "The child thinks 1/8 is bigger than 1/4 because 8 is bigger than 4.", "fix": "Fold two identical papers, one into 4 and one into 8. Compare the sizes of a single part."},
        {"misconception": "The child reads 3/4 as 3 and 4 separately.", "fix": "Say it as 3 of 4 equal parts. The bottom number names the parts, the top number counts them."},
    ],
    explicit_teaching="A FRACTION is an equal part of a whole or a collection. The parts must be EQUAL. The DENOMINATOR (bottom number) says how many equal parts the whole is split into. The NUMERATOR (top number) says how many of those parts we are talking about. So 3/4 means 3 of 4 equal parts. A unit fraction has a numerator of 1, like 1/2, 1/4 and 1/8. The more equal parts a whole is split into, the smaller each part is. We can find a fraction of a collection by sharing it into equal groups. For 1/4 of 12, share 12 into 4 equal groups. Each group has 3, so 1/4 of 12 is 3. Fractions that show the same amount are EQUIVALENT. For example, 1/2 = 2/4 = 4/8.",
    teach_steps=[
        {"icon": "🍕", "title": "Equal parts", "explain": "A fraction needs EQUAL parts. If a pizza is cut into 2 equal parts, each part is a half. 4 equal parts make quarters. 8 equal parts make eighths.\n\nTry it: fold paper into 2, 4 and 8 equal parts.", "example": "A pizza cut into 4 equal slices has quarters. One slice is one quarter, written 1/4.", "notice": "If the parts are not equal, they are not fractions.", "check": {"question": "A pizza is cut into 4 equal pieces. What is each piece called?", "options": ["one half", "one quarter", "one eighth"], "correct_index": 1, "explanation": "4 equal parts are quarters."}},
        {"icon": "🔢", "title": "Reading fractions", "explain": "The bottom number (denominator) tells how many equal parts in all. The top number (numerator) tells how many parts we have.\n\nTry it: shade 3 of 8 equal parts and write the fraction.", "example": "3/4 means 3 of 4 equal parts. 5/8 means 5 of 8 equal parts.", "notice": "Bottom = parts in the whole. Top = parts we are counting.", "check": {"question": "A pizza is cut into 8 equal slices and you eat 5. What fraction did you eat?", "options": ["5/8", "8/5", "3/8"], "correct_index": 0, "explanation": "5 of 8 equal slices is 5/8."}},
        {"icon": "🫒", "title": "Fractions of a collection", "explain": "We can find a fraction of a group of things. Share the group equally. The denominator tells how many groups to make.\n\nTry it: put 12 counters into 4 equal groups.", "example": "1/4 of 12: share 12 into 4 groups of 3, so 1/4 of 12 is 3. 3/4 of 12 is 3 groups, which is 9.", "notice": "Divide by the denominator, then multiply by the numerator.", "check": {"question": "What is 1/5 of 20?", "options": ["4", "5", "15"], "correct_index": 0, "explanation": "20 shared into 5 equal groups is 4 in each group."}},
        {"icon": "⚖️", "title": "Comparing fractions", "explain": "When the numerators are the same, the bigger denominator means smaller parts. So 1/2 > 1/4 > 1/8. When the denominators are the same, the bigger numerator is bigger. So 5/8 > 3/8.\n\nTry it: compare 1/3 and 1/6 by folding paper.", "example": "1/3 > 1/6, because thirds are bigger parts than sixths. 5/8 > 3/8 because 5 eighths is more than 3 eighths.", "notice": "More parts in the whole means smaller parts.", "check": {"question": "Which is larger?", "options": ["1/3", "1/6", "They are equal"], "correct_index": 0, "explanation": "A third is bigger than a sixth."}},
        {"icon": "🔄", "title": "Equivalent fractions", "explain": "Different fractions can show the same amount. If you cut each half into two, you get quarters. If you cut each quarter into two, you get eighths.\n\nTry it: fold a paper in half, shade it, then fold again and again. Count the shaded parts each time.", "example": "1/2 = 2/4 = 4/8.", "notice": "The shaded amount does not change when we cut it into more parts.", "check": {"question": "1/2 equals how many eighths?", "options": ["2/8", "4/8", "8/8"], "correct_index": 1, "explanation": "One half is 4 of 8 equal parts."}},
    ],
    worked_example="A pizza is cut into 8 equal slices and 3 are eaten. EATEN: 3/8. LEFT: 5/8. The kitchen has 12 olives. 1/4 of the olives go on pizza A: 12 shared into 4 groups is 3. 3/4 of the olives: 3 groups of 3 is 9. COMPARE: is 1/2 or 3/8 bigger? 1/2 = 4/8, and 4/8 > 3/8, so 1/2 is bigger.",
    guided_practice="A pizza is cut into 8 equal slices. Shade 3/8. Then find 1/2 of 16 pepperoni slices and 1/4 of 16. Which gives more pepperoni?",
    practice_questions=[
        {"q": "Write the fraction: 2 out of 5 equal parts shaded.", "a": "2/5"},
        {"q": "1/2 of 18", "a": "9"},
        {"q": "1/4 of 16", "a": "4"},
        {"q": "3/4 of 8", "a": "6"},
        {"q": "Which is bigger, 1/4 or 1/8?", "a": "1/4"},
        {"q": "What fraction is the same as 2/4?", "a": "1/2"},
    ],
    hands_on_activity="Fold-and-cut. Take 3 identical paper rectangles. Fold the first into halves, the second into quarters and the third into eighths. Cut along the folds. Label each piece with its fraction. Line up one piece from each and compare their sizes. Then show that 2 quarters covers the same area as 1 half, and 4 eighths covers the same area as 1 half.",
    independent_task="Design three pizzas. Pizza 1 is cut into halves, pizza 2 into quarters and pizza 3 into eighths. Colour toppings: shade 1/2 of pizza 1, 3/4 of pizza 2 and 5/8 of pizza 3, and write each fraction. Then count 12 olives and place 1/4 on one pizza and 1/2 on another. Finish by writing one comparison, such as 1/2 is larger than 3/8, and show how you know using a drawing.",
    cross_curricular={"title": "Link idea", "note": "None recorded. Fractions link to later Measurement and Data work."},
    response_prompt="Label every pizza with its fractions and show the drawing for your comparison.",
    self_check="Are my parts equal? Does my fraction match what I shaded? Did I check the collection answers by sharing?",
    rubric={"title": "What to look for", "levels": [
        {"level": "Getting started", "descriptor": "Names halves and quarters with support. Cuts unequal parts or confuses numerator and denominator."},
        {"level": "Secure", "descriptor": "Draws equal parts, writes correct fractions, finds a fraction of a collection and compares fractions with the same numerator or denominator."},
        {"level": "Strong", "descriptor": "Shows equivalent fractions with a model, explains comparisons using drawings and creates their own fraction problem."},
    ]},
    interactive_activities=[{"type": "flip_cards", "title": "Quest Codex: key terms", "cards": [
        {"front": "🍕 Fraction", "back": "An equal part of a whole or a collection."},
        {"front": "⬇️ Denominator", "back": "The bottom number. How many equal parts the whole is split into."},
        {"front": "⬆️ Numerator", "back": "The top number. How many parts we are counting."},
        {"front": "½ Half", "back": "One of two equal parts. Written 1/2."},
        {"front": "¼ Quarter", "back": "One of four equal parts. Written 1/4."},
        {"front": "🔸 Eighth", "back": "One of eight equal parts. Written 1/8."},
        {"front": "🔄 Equivalent", "back": "Fractions that show the same amount, like 1/2 and 2/4."},
        {"front": "🫒 Collection", "back": "A group of objects. A fraction of a collection means sharing it equally."},
    ]}],
    sort_activity={"title": "Bigger or smaller than a half?", "instructions": "Sort each fraction by comparing it to one half.", "buckets": ["Less than 1/2", "Equal to 1/2", "More than 1/2"], "items": [
        {"text": "1/4", "answer": 0}, {"text": "2/4", "answer": 1}, {"text": "3/4", "answer": 2}, {"text": "3/8", "answer": 0},
        {"text": "4/8", "answer": 1}, {"text": "5/8", "answer": 2}, {"text": "1/3", "answer": 0}, {"text": "2/3", "answer": 2},
    ]},
    word_challenges=[
        {"question": "The bottom number of a fraction is the ___.", "options": ["denominator", "numerator", "product"], "correct_index": 0, "explanation": "The denominator tells how many equal parts are in the whole."},
        {"question": "The top number of a fraction is the ___.", "options": ["numerator", "denominator", "difference"], "correct_index": 0, "explanation": "The numerator counts the parts."},
        {"question": "Fractions that show the same amount are ___.", "options": ["equivalent", "unequal", "inverse"], "correct_index": 0, "explanation": "1/2 and 2/4 are equivalent."},
        {"question": "Parts of a fraction must be ___.", "options": ["equal", "different", "small"], "correct_index": 0, "explanation": "Fractions need equal parts."},
    ],
    planner_fields=[
        {"key": "p1", "label": "🍕 Pizza 1 (halves)", "hint": "Write the fraction you shade."},
        {"key": "p2", "label": "🍕 Pizza 2 (quarters)", "hint": "Write the fraction you shade."},
        {"key": "p3", "label": "🍕 Pizza 3 (eighths)", "hint": "Write the fraction you shade."},
        {"key": "olives", "label": "🫒 Olive plan", "hint": "Write how many olives are in each fraction of the 12."},
    ],
    steps=[
        {"title": "📜 Step 1: Accept the quest", "detail": "Read your mission and accept the quest.", "duration_minutes": 5},
        {"title": "🎬 Step 2: Watch and warm up", "detail": "Watch an ABC Mini Lessons Maths episode on fractions, then do the fold-and-cut activity.", "duration_minutes": 15},
        {"title": "📖 Step 3: Learn the skills", "detail": "Five short lessons: equal parts, reading fractions, collections, comparing and equivalent fractions.", "duration_minutes": 15},
        {"title": "🔍 Step 4: Practise", "detail": "Flip the key-term cards, sort the fractions, answer word challenges and do the practice questions.", "duration_minutes": 10},
        {"title": "🗝️ Step 5: Plan and cook", "detail": "Fill in your planner, then complete the independent task on paper.", "duration_minutes": 20},
        {"title": "🛡️ Step 6: Clear the Quest check", "detail": "Answer the 10-question Quest check. You need 9 out of 10 to pass.", "duration_minutes": 5},
        {"title": "🏆 Step 7: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
    ],
    resources=[
        {"type": "video", "title": "ABC Mini Lessons: Maths (series page; choose a fractions episode for Years 3-4)", "url": MINI_LESSONS, "prompt": "Pick an episode on fractions. Pause and try each example first."},
        {"type": "worksheet", "title": "Twinkl Australia: fractions Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=fractions+year+3", "prompt": "Choose a printable worksheet. Log in to your Twinkl account to download."},
        {"type": "worksheet", "title": "Twinkl Australia: fractions of a collection Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=fractions+of+a+collection+year+3", "prompt": "Choose a printable worksheet."},
        {"type": "worksheet", "title": "ChalkBee: MA2-PF-01 free printable worksheets", "url": "https://chalkbee.com/au/nsw/ma2-pf-01", "prompt": "Free worksheets matched to this outcome."},
    ],
    quiz=[
        {"question": "A cake is cut into 2 equal parts. What is each part called?", "type": "multiple_choice", "options": ["one half", "one quarter", "one third", "one whole"], "correct_index": 0, "explanation": "2 equal parts are halves."},
        {"question": "In the fraction 3/8, what is the denominator?", "type": "multiple_choice", "options": ["3", "8", "11", "5"], "correct_index": 1, "explanation": "The denominator is the bottom number."},
        {"question": "A pizza has 8 equal slices and 3 are eaten. What fraction is left?", "type": "multiple_choice", "options": ["3/8", "5/8", "8/3", "1/8"], "correct_index": 1, "explanation": "8 slices minus 3 eaten leaves 5, so 5/8."},
        {"question": "What is 1/4 of 20?", "type": "multiple_choice", "options": ["4", "5", "10", "16"], "correct_index": 1, "explanation": "20 shared into 4 equal groups is 5 each."},
        {"question": "What is 3/4 of 12?", "type": "multiple_choice", "options": ["3", "6", "9", "12"], "correct_index": 2, "explanation": "1/4 of 12 is 3, so 3/4 is 9."},
        {"question": "Which is the largest fraction?", "type": "multiple_choice", "options": ["1/2", "1/4", "1/8", "1/3"], "correct_index": 0, "explanation": "With the same numerator, the smaller denominator is the bigger fraction."},
        {"question": "Which fraction is equal to 2/4?", "type": "multiple_choice", "options": ["1/2", "1/4", "3/4", "2/8"], "correct_index": 0, "explanation": "2 of 4 equal parts is one half."},
        {"question": "Which is greater, 3/8 or 5/8?", "type": "multiple_choice", "options": ["3/8", "5/8", "They are equal"], "correct_index": 1, "explanation": "The denominators are the same, so the larger numerator is larger."},
        {"question": "Ollie eats 2/5 of a chocolate bar. What fraction is left?", "type": "multiple_choice", "options": ["2/5", "3/5", "5/2", "1/5"], "correct_index": 1, "explanation": "5/5 minus 2/5 is 3/5."},
        {"question": "What is 1/10 of 50?", "type": "multiple_choice", "options": ["5", "10", "40", "500"], "correct_index": 0, "explanation": "50 shared into 10 equal groups is 5 each."},
    ],
    evidence_instructions="Upload a photo of your three pizzas with fractions labelled, your olive groups, your comparison drawing and your fold-and-cut pieces.",
    parent_notes="Seven steps, about 75 minutes. Builds fractions from equal parts, then numerator and denominator, fractions of a collection, comparing and equivalent fractions. Look for: equal parts, correct fraction notation, collection answers found by sharing, and a drawing that supports each comparison. Outcomes: MA2-PF-01 (partitioned fractions) and MAO-WM-01. No cross-curricular outcome recorded. Video resource is a series page: choose one episode.",
    offline_alternative="Use real food such as a pizza, a slice of bread or a chocolate bar, plus a printed worksheet.",
    extension="Find 2/3 of 12 and 3/5 of 20. Write two fractions that equal 3/4 using a drawing.",
    follow_up_challenges=[
        {"title": "Fair share dinner", "description": "Cut a real food into equal parts and take a photo showing the fractions. Label each part.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
        {"title": "Fraction hunt", "description": "Find five fractions at home on packaging, clocks or measuring cups. Record where you found them.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
    ],
)


LESSON_LENGTH_MASS = _common(
    seed_key="s2-y3-maths-length-mass-explorer-05",
    subject="Measurement: length (m, cm, mm) and mass (kg, g)",
    title="The Explorer's Toolkit",
    child_mission="🧭 An expedition is about to leave, and the explorer's kit must be measured and weighed perfectly. Measure ropes, trails and supplies, and pack the backpack without going over the limit.",
    duration_minutes=75,
    outcome_codes=["MA2-GM-02", "MA2-NSM-01", "MAO-WM-01"],
    cross_outcome_codes=[],
    outcome_notes={
        "MA2-GM-02": "Primary. Measures and estimates lengths in metres, centimetres and millimetres and chooses a suitable unit (steps 1-3, quiz 1-5, sort).",
        "MA2-NSM-01": "Primary. Estimates, measures and compares masses using kilograms and grams (steps 4-5, quiz 6-10).",
        "MAO-WM-01": "Working mathematically: estimates before measuring, selects tools and units, and records results (hands-on activity, independent task, rubric).",
    },
    learning_intention="We are learning to estimate, measure and compare lengths in metres, centimetres and millimetres and masses in kilograms and grams.",
    success_criteria=[
        "I can choose a sensible unit to measure a length.",
        "I can measure to the nearest millimetre with a ruler.",
        "I can change between metres, centimetres and millimetres.",
        "I can estimate and weigh objects in grams and kilograms.",
        "I can change between kilograms and grams and compare masses.",
        "I can score 90% or more on the Quest check.",
    ],
    key_vocabulary=["length", "metre", "centimetre", "millimetre", "mass", "kilogram", "gram", "estimate", "measure", "compare", "scale"],
    materials=["Ruler with millimetres", "Tape measure or metre ruler", "Kitchen scales", "Five household objects to measure and weigh", "Paper and pencil", "Device"],
    prior_knowledge="Child can measure with a ruler to the nearest centimetre and knows that 100 cm is a metre.",
    common_misconceptions=[
        {"misconception": "The child starts measuring at the end of the ruler rather than at zero.", "fix": "Show that zero is where the object begins. Practise lining objects up at zero."},
        {"misconception": "The child reads 1 m 40 cm as 140 m or 1,040 cm.", "fix": "Write 1 m = 100 cm. Then 1 m 40 cm = 100 cm + 40 cm = 140 cm."},
        {"misconception": "The child thinks mass and weight words mean the same size in kilograms and grams, so 1,100 g seems smaller than 1 kg.", "fix": "Write 1 kg = 1,000 g. 1,100 g is 100 g more than 1 kg."},
    ],
    explicit_teaching="LENGTH tells how long something is. We use millimetres (mm) for very small lengths, centimetres (cm) for everyday objects and metres (m) for large distances. 1 cm = 10 mm and 1 m = 100 cm. MASS tells how much matter is in an object. We use grams (g) for light objects and kilograms (kg) for heavier ones. 1 kg = 1,000 g. Always ESTIMATE first, then MEASURE using a scale or ruler, then COMPARE with your estimate. Choose a unit that fits the size of the object.",
    teach_steps=[
        {"icon": "🔍", "title": "Choose the unit", "explain": "Pick the unit that fits the object. Use mm for very tiny things, cm for things you hold, and m for rooms and trails.\n\nTry it: choose a unit for the width of your thumbnail, a pencil and a bedroom.", "example": "A grain of rice is about 6 mm. A pencil is about 18 cm. A bedroom is about 4 m long.", "notice": "A good unit gives a number that is easy to say and picture.", "check": {"question": "Which unit best measures the length of a classroom?", "options": ["millimetres", "centimetres", "metres"], "correct_index": 2, "explanation": "A classroom is large, so metres are sensible."}},
        {"icon": "📏", "title": "Reading a ruler", "explain": "Line one end of the object up with 0. Read the number at the other end. The small lines are millimetres: there are 10 between each centimetre.\n\nTry it: measure a pencil to the nearest millimetre.", "example": "An object that is 6 cm and 3 small lines long is 6 cm 3 mm, which is 63 mm.", "notice": "1 cm = 10 mm. Multiply centimetres by 10 to get millimetres.", "check": {"question": "How many millimetres are in 4 cm?", "options": ["4", "40", "400"], "correct_index": 1, "explanation": "4 x 10 = 40 mm."}},
        {"icon": "🧩", "title": "Changing units", "explain": "1 m = 100 cm. To change metres to centimetres, multiply by 100. Mixed lengths such as 2 m 30 cm become 230 cm.\n\nTry it: write 1 m 40 cm in centimetres.", "example": "3 m = 300 cm. 2 m 30 cm = 200 cm + 30 cm = 230 cm.", "notice": "Compare lengths in the same unit.", "check": {"question": "3 m is how many centimetres?", "options": ["30", "300", "3,000"], "correct_index": 1, "explanation": "3 x 100 = 300 cm."}},
        {"icon": "⚖️", "title": "Mass in grams and kilograms", "explain": "Mass is measured with scales. Light things like a paperclip are measured in grams. Heavier things like a bag of rice are measured in kilograms. 1 kg = 1,000 g.\n\nTry it: weigh five objects and record the mass in grams.", "example": "A bag of sugar is often 1 kg, which is 1,000 g. A small apple is about 150 g.", "notice": "Read the scale carefully. Check what each mark is worth.", "check": {"question": "1 kg is equal to how many grams?", "options": ["10", "100", "1,000"], "correct_index": 2, "explanation": "1 kg = 1,000 g."}},
        {"icon": "🧮", "title": "Estimate, measure, compare", "explain": "Estimate first. Then measure, record and compare with your estimate. To compare masses, use the same unit. 2 kg 250 g = 2,000 g + 250 g = 2,250 g.\n\nTry it: estimate which of three objects is heaviest, then weigh them.", "example": "1 kg 500 g = 1,000 g + 500 g = 1,500 g, which is more than 1,200 g.", "notice": "Estimating makes you a better measurer because you notice mistakes.", "check": {"question": "2 kg 250 g is how many grams?", "options": ["2,250 g", "2,025 g", "250 g"], "correct_index": 0, "explanation": "2,000 g + 250 g = 2,250 g."}},
    ],
    worked_example="The explorer has a rope that is 3 m 20 cm long. 3 m 20 cm = 300 cm + 20 cm = 320 cm. Another rope is 3 m 5 cm = 305 cm. 320 cm - 305 cm = 15 cm, so the first rope is 15 cm longer. The backpack has 2 kg 300 g (2,300 g) of food and 1 kg 800 g (1,800 g) of water. 2,300 + 1,800 = 4,100 g, which is 4 kg 100 g.",
    guided_practice="The explorer needs a rope of at least 4 m. Rope A is 385 cm and rope B is 4 m 10 cm. Which rope is long enough? Then weigh two objects and find the total mass in grams and kilograms.",
    practice_questions=[
        {"q": "6 cm in millimetres", "a": "60 mm"},
        {"q": "450 cm in metres and centimetres", "a": "4 m 50 cm"},
        {"q": "3 kg 400 g in grams", "a": "3,400 g"},
        {"q": "5,200 g in kilograms and grams", "a": "5 kg 200 g"},
        {"q": "1 m - 35 cm", "a": "65 cm"},
        {"q": "2 kg - 750 g", "a": "1,250 g"},
    ],
    hands_on_activity="Expedition table. Choose five household objects. For each, estimate the length in cm and the mass in grams, then measure the length with a ruler and weigh each object on kitchen scales. Record your estimate, measurement and difference in a table. Order the objects from shortest to longest and from lightest to heaviest.",
    independent_task="Pack the explorer's backpack. Measure and weigh five items and record them in a table. Find the total mass in grams and in kilograms. The backpack can carry a maximum of 5 kg. Does it fit? If not, which item would you remove? Then measure two trails (use string or steps) in cm and m, and write which is longer by how much.",
    cross_curricular={"title": "Link idea", "note": "None recorded. Measuring skills support later Science and Technology investigations."},
    response_prompt="Show your table, your total mass and your working for the trail comparison.",
    self_check="Did I estimate first? Did I start at zero? Did I use the same unit when comparing? Does my total make sense?",
    rubric={"title": "What to look for", "levels": [
        {"level": "Getting started", "descriptor": "Measures to the nearest centimetre or kilogram with support and needs help converting units."},
        {"level": "Secure", "descriptor": "Chooses a suitable unit, measures accurately, converts between units and records and compares with the same unit."},
        {"level": "Strong", "descriptor": "Estimates sensibly, explains why a unit is suitable, solves multi-step comparison problems and checks totals."},
    ]},
    interactive_activities=[{"type": "flip_cards", "title": "Quest Codex: key terms", "cards": [
        {"front": "📏 Millimetre", "back": "A very small unit of length. 10 mm = 1 cm."},
        {"front": "📏 Centimetre", "back": "A unit of length for everyday objects. 100 cm = 1 m."},
        {"front": "📏 Metre", "back": "A unit of length for rooms, trails and distances."},
        {"front": "⚖️ Mass", "back": "How much matter an object has. We measure it with scales."},
        {"front": "⚖️ Gram", "back": "A unit of mass for light objects."},
        {"front": "⚖️ Kilogram", "back": "A unit of mass for heavier objects. 1 kg = 1,000 g."},
        {"front": "🔮 Estimate", "back": "A careful guess made before measuring."},
        {"front": "🧮 Compare", "back": "Say which is longer, shorter, heavier or lighter, using the same unit."},
    ]}],
    sort_activity={"title": "Pick the unit", "instructions": "Choose the best unit to measure each length.", "buckets": ["Millimetres", "Centimetres", "Metres"], "items": [
        {"text": "Thickness of a leaf", "answer": 0}, {"text": "Length of a pencil", "answer": 1}, {"text": "Height of a house", "answer": 2}, {"text": "Length of a swimming pool", "answer": 2},
        {"text": "Width of a fingernail", "answer": 1}, {"text": "Length of an eraser", "answer": 1}, {"text": "Thickness of a coin", "answer": 0}, {"text": "Length of a football field", "answer": 2},
    ]},
    word_challenges=[
        {"question": "There are 10 millimetres in one ___.", "options": ["centimetre", "metre", "kilogram"], "correct_index": 0, "explanation": "10 mm = 1 cm."},
        {"question": "There are 1,000 grams in one ___.", "options": ["kilogram", "centimetre", "metre"], "correct_index": 0, "explanation": "1 kg = 1,000 g."},
        {"question": "How much matter an object has is its ___.", "options": ["mass", "length", "time"], "correct_index": 0, "explanation": "Mass is measured in grams and kilograms."},
        {"question": "A careful guess before measuring is an ___.", "options": ["estimate", "answer", "inverse"], "correct_index": 0, "explanation": "An estimate helps check the measurement."},
    ],
    planner_fields=[
        {"key": "items", "label": "🎒 My five items", "hint": "List the five items and your estimate for each."},
        {"key": "mass", "label": "⚖️ Total mass", "hint": "Write the total mass in grams and in kilograms."},
        {"key": "trail", "label": "🧭 Trail plan", "hint": "Write how you will measure the two trails."},
    ],
    steps=[
        {"title": "📜 Step 1: Accept the quest", "detail": "Read your mission and accept the quest.", "duration_minutes": 5},
        {"title": "🎬 Step 2: Watch and warm up", "detail": "Watch an ABC Mini Lessons Maths episode on length or mass, then complete the expedition table.", "duration_minutes": 15},
        {"title": "📖 Step 3: Learn the skills", "detail": "Five short lessons: units, reading a ruler, changing units, mass and estimating.", "duration_minutes": 15},
        {"title": "🔍 Step 4: Practise", "detail": "Flip the key-term cards, sort lengths by unit, answer word challenges and do the practice questions.", "duration_minutes": 10},
        {"title": "🗝️ Step 5: Plan and pack", "detail": "Fill in your planner, then complete the independent task on paper.", "duration_minutes": 20},
        {"title": "🛡️ Step 6: Clear the Quest check", "detail": "Answer the 10-question Quest check. You need 9 out of 10 to pass.", "duration_minutes": 5},
        {"title": "🏆 Step 7: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
    ],
    resources=[
        {"type": "video", "title": "ABC Mini Lessons: Maths (series page; choose a length or mass episode for Years 3-4)", "url": MINI_LESSONS, "prompt": "Pick an episode on measuring length or mass. Pause and try each example first."},
        {"type": "worksheet", "title": "Twinkl Australia: length m cm mm Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=length+metres+centimetres+millimetres+year+3", "prompt": "Choose a printable worksheet. Log in to your Twinkl account to download."},
        {"type": "worksheet", "title": "Twinkl Australia: mass kilograms grams Year 3 (search)", "url": "https://www.twinkl.com.au/search?q=mass+kilograms+grams+year+3", "prompt": "Choose a printable worksheet."},
    ],
    quiz=[
        {"question": "Which unit is best for the thickness of a 20-cent coin?", "type": "multiple_choice", "options": ["metres", "centimetres", "millimetres", "kilometres"], "correct_index": 2, "explanation": "A coin is very thin, so millimetres are best."},
        {"question": "How many millimetres are in 5 cm?", "type": "multiple_choice", "options": ["5", "50", "500", "15"], "correct_index": 1, "explanation": "5 x 10 = 50 mm."},
        {"question": "How many centimetres are in 2 m?", "type": "multiple_choice", "options": ["20", "200", "2,000", "12"], "correct_index": 1, "explanation": "2 x 100 = 200 cm."},
        {"question": "1 m 40 cm is the same as ___.", "type": "multiple_choice", "options": ["140 cm", "1,040 cm", "104 cm", "14 cm"], "correct_index": 0, "explanation": "100 cm + 40 cm = 140 cm."},
        {"question": "Which is longer?", "type": "multiple_choice", "options": ["1 m", "95 cm", "They are the same", "You cannot tell"], "correct_index": 0, "explanation": "1 m = 100 cm, which is more than 95 cm."},
        {"question": "1 kg is how many grams?", "type": "multiple_choice", "options": ["10 g", "100 g", "1,000 g", "10,000 g"], "correct_index": 2, "explanation": "1 kg = 1,000 g."},
        {"question": "3 kg is how many grams?", "type": "multiple_choice", "options": ["300 g", "3,000 g", "30 g", "3,100 g"], "correct_index": 1, "explanation": "3 x 1,000 = 3,000 g."},
        {"question": "2 kg 500 g is the same as ___.", "type": "multiple_choice", "options": ["2,500 g", "2,050 g", "250 g", "25,000 g"], "correct_index": 0, "explanation": "2,000 g + 500 g = 2,500 g."},
        {"question": "Which unit is best for the mass of a paperclip?", "type": "multiple_choice", "options": ["kilograms", "grams", "metres", "litres"], "correct_index": 1, "explanation": "A paperclip is very light, so grams are best."},
        {"question": "Which is the heaviest?", "type": "multiple_choice", "options": ["900 g", "1 kg", "1,100 g", "850 g"], "correct_index": 2, "explanation": "1 kg = 1,000 g, so 1,100 g is the heaviest."},
    ],
    evidence_instructions="Upload a photo of your expedition table, your packed backpack total in grams and kilograms with your decision about the 5 kg limit, and your trail comparison working.",
    parent_notes="Seven steps, about 75 minutes. Covers choosing units, reading a ruler to the millimetre, converting between m, cm and mm, mass in g and kg, and estimating then measuring. Look for: estimates before measures, starting at zero, correct conversions, and accurate totals. Outcomes: MA2-GM-02 (length), MA2-NSM-01 (mass), MAO-WM-01. Capacity and volume belong to MA2-3DS-02 and time to MA2-NSM-02, covered in later lessons. Video resource is a series page: choose one episode.",
    offline_alternative="Use a printed ruler and a printed worksheet. Use string for trails and a kitchen scale for mass.",
    extension="Measure the perimeter of a table in cm. Find an item that weighs about 500 g and one that weighs about 2 kg.",
    follow_up_challenges=[
        {"title": "Height chart", "description": "Measure the heights of five family members in cm and order them. Convert each to metres and centimetres.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
        {"title": "Heavier than a kilogram", "description": "Find five items at home that are heavier than 1 kg and five that are lighter. Weigh them and record the mass.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
    ],
)

S2Y3_MATHS_LESSONS_3 = [LESSON_FRACTIONS, LESSON_LENGTH_MASS]
