"""Stage 2 English, Week 2 Lesson 4: Retelling a story aloud and joined handwriting (Oral language and handwriting).
The oral retelling is done aloud with a parent; the child types a retelling script and a self-check, and copies a joined-handwriting sentence on paper.
Video jpOvY9gcHMc (retelling with beginning, middle and end) found by search. Re-check in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc, _video
from spelling_s2_w1 import _w, _c

WORDS = ["stay", "paint", "tree", "reach", "coat", "seat"]

STORY = (
    "The Paper Boat\n\n"
    "Nina folded a paper boat on a rainy afternoon and carried it to the puddle by the gate. She placed it gently on the water, and it floated like a tiny ship. "
    "Then a gust of wind pushed the boat towards the drain. Nina gasped. She grabbed a long stick and reached out as far as she could, but the boat spun away. "
    "Her brother Tom lay flat on the path, hooked the stick under the boat and pulled it back just in time. Nina hugged him. They dried the boat on a seat in the sun and promised to sail it again tomorrow."
)

LESSON = build(
    "s2-eng-w02-l4-retell-and-handwriting",
    "Retelling a Story Aloud and Joined Handwriting",
    "Tell a story in your own words so that a listener can follow it, then practise forming neat, joined letters in the words you are learning to spell.",
    "Oral language and handwriting",
    ["EN2-OLC-01", "EN2-RECOM-01", "EN2-HANDW-01", "EN2-SPELL-01"],
    {
        "EN2-OLC-01": "Primary. Retells a narrative aloud in order, using a clear voice and linking words.",
        "EN2-RECOM-01": "Identifies the main events of a narrative and puts them in order.",
        "EN2-HANDW-01": "Writes legible joined letters, with consistent size and spacing.",
        "EN2-SPELL-01": "Spells words with vowel teams ai, ay, ee, ea and oa (week 2 spelling focus).",
    },
    "We are learning to retell a story clearly in order, and to write joined letters neatly.",
    ["I can retell the main events of a story in the right order.", "I can use linking words such as first, then, next and finally.", "I can speak clearly, at a good pace and with expression.", "I can form joined letters with the right size and spacing.", "I can spell words with vowel teams ai, ay, ee, ea and oa."],
    ["retell", "sequence", "linking word", "expression", "pace", "joined writing", "spacing", "legible"],
    ["This lesson", "Pencil and lined paper for handwriting", "A listener, such as a parent"],
    "Child can identify the five parts of a story mountain and has practised noun, verb and adjective work (Week 2 Lessons 1 to 3).",
    (
        "Why this matters. Retelling shows that you really understood a story. It also trains you to speak clearly and organise ideas, which helps when you write stories of your own. Joined handwriting is a different skill, but it matters for the same reason: a neat, quick, legible hand lets your ideas reach the reader without effort.\n\n"
        "How to retell. A retelling is not a copy of the story word for word. It is the main events in your own words, in order. Start with who and where, then tell the problem, then how it was solved, and finish with how it ended. Use linking words: first, then, next, after that, finally. Leave out small details that do not change the story.\n\n"
        "How to sound good. Speak at a steady pace, not too fast. Use a clear voice and look at your listener. Pause at full stops. Change your voice a little for exciting parts. Practise once quietly before you tell the story to someone.\n\n"
        "Joined handwriting. In joined writing, letters in a word connect with small lead-in and lead-out strokes. Keep letters the same size, sit tall letters on the line, and leave a finger-width gap between words. Vowel teams such as ai, ay, ee, ea and oa join smoothly, so they are good for practice. Slow, neat writing is better than fast, messy writing.\n\n"
        "The routine. 1. Read or listen to the story. 2. List the five main events. 3. Practise your retelling quietly. 4. Retell it aloud to your listener. 5. Type your retelling script and self-check. 6. Copy the handwriting sentence on paper in joined letters.\n\n"
        "A quick demonstration. 'First, Nina floated her paper boat in a puddle. Then the wind pushed it towards a drain. Next, her brother Tom hooked it back with a stick. Finally, they dried it in the sun.' That is a retelling: short, in order, with linking words."
    ),
    [
        _step("1", "What is a retelling?", "A retelling tells the main events of a story in your own words and in the right order. It does not copy the story word for word, and it does not include every small detail.\n\nThink of it as a short, clear map of the story.", "The story is a page long, but the retelling can be four sentences.", "A retelling is short, in your own words and in order.", ("A good retelling...", ["Copies every word", "Gives the main events in order", "Skips the ending"], 1, "A retelling gives the main events in order.")),
        _step("2", "Find the main events", "Read the story, then ask: who is it about, what is the problem, what happens next and how does it end? Choose the events that change the story. Leave out small details.\n\nFive events are usually enough.", "Nina floats her boat. The wind pushes it towards the drain. Nina's stick cannot reach. Tom saves it. They dry it and plan to sail again.", "Choose the events that change the story.", ("Which is a main event?", ["Nina saw a puddle by the gate", "Tom hooks the boat back with a stick", "It is a rainy afternoon"], 1, "Tom saving the boat changes the story.")),
        _step("3", "Use linking words", "Linking words show the order of events: first, then, next, after that, finally. They help your listener follow the story.\n\nUse a different linking word for each event.", "First... Then... Next... Finally...", "Linking words show the order.", ("Which word ends a retelling?", ["First", "Finally", "Then"], 1, "Finally shows the last event.")),
        _step("4", "Speak so people can follow", "Speak clearly, at a steady pace, and look at your listener. Pause at full stops. Use a little expression for exciting parts, such as when the boat nearly goes down the drain.\n\nPractise quietly first.", "Slow and clear is better than fast and mumbled.", "Clear voice, steady pace, expression.", ("Which is the best pace?", ["Very fast", "Steady", "Whispering"], 1, "A steady pace helps the listener follow.")),
        _step("5", "Joined handwriting", "In joined writing, each letter connects to the next with a small stroke. Keep letters the same size, start tall letters at the top line, and leave a finger-width gap between words.\n\nGo slowly and make each join neat.", "Practise: stay, paint, tree, reach, coat, seat. Notice how ay, ai, ee, ea and oa join.", "Neat joins, even size, even spacing.", ("What should be between words?", ["No gap", "A finger-width gap", "A very large gap"], 1, "A finger-width gap keeps words separate.")),
        _step("6", "Spelling focus: vowel teams", "This lesson's words are stay (ay), paint (ai), tree (ee), reach (ea), coat (oa) and seat (ea).\n\nRemember: ay at the end, ai in the middle.", "st-ay, p-ai-nt, tr-ee, r-ea-ch, c-oa-t, s-ea-t.", "Spot the vowel team and spell it as one sound.", ("Which vowel team is in 'coat'?", ["oa", "ea", "ai"], 0, "Coat has oa.")),
        _step("7", "Check yourself", "After your retelling, ask: did I include who, where, the problem and the ending? Did I use linking words? Was I clear? After handwriting, check size, joins and spacing.\n\nChoose one thing to do better next time.", "Self-check: 'My events were in order, but I spoke too quickly at the end.'", "Check, then choose one thing to improve.", ("Why self-check?", ["To find one thing to improve", "To make it longer", "There is no reason"], 0, "A self-check shows what to improve next time.")),
    ],
    "Retell 'The Paper Boat' together. Events: 1. Nina floats her paper boat in the puddle. 2. The wind pushes it towards the drain. 3. Nina's stick cannot reach it. 4. Tom hooks it back. 5. They dry it and plan to sail it again. Script: 'First, Nina floated her paper boat in a puddle. Then the wind pushed it towards a drain. Next, Nina tried to reach it with a stick, but she could not. Finally, her brother Tom hooked it back, and they dried it in the sun.' Check: who, where, problem, ending, linking words. All present.",
    "Type your answers in the practice boxes. Part A: list the five main events of 'The Paper Boat'. Part B: type four sentences retelling it with first, then, next and finally. Part C: type the vowel team in stay, paint, tree, reach, coat and seat. Then retell the story aloud to a listener. Your parent can check your answers against the answer key.",
    "Read the story, then complete the stages.\n\n" + STORY + "\n\nStage 1 (plan): type the five main events in order.\nStage 2 (script): type your retelling in five or six sentences using linking words.\nStage 3 (aloud): retell the story aloud to a listener. Do not read your script word for word; use it only if you forget.\nStage 4 (self-check): type what went well and one thing to improve in your speaking.\nStage 5 (handwriting): on lined paper, copy this sentence three times in joined letters: 'Please stay and paint the tree.' Then type whether your size, joins and spacing were neat.\nStage 6 (spell): type your six spelling words and underline the vowel team in each.",
    "What was the hardest part of retelling a story aloud, and how did you handle it?", "Did I give the main events in order, use linking words, speak clearly, write neat joins and spell my six words with their vowel teams?",
    [_q("What is a retelling?", ["The main events in your own words, in order", "A copy of the story", "A new story", "A poem"], 0, "A retelling gives the main events in your own words."), _q("Which linking word starts a retelling?", ["Finally", "First", "Next", "Then"], 1, "First starts it."), _q("Which is a main event in 'The Paper Boat'?", ["The weather is rainy", "Tom hooks the boat back", "There is a gate", "Nina is wearing a coat"], 1, "Tom rescuing the boat changes the story."), _q("What is the problem in the story?", ["The boat is heading for the drain", "Nina is hungry", "It stops raining", "Tom is lost"], 0, "The wind pushes the boat towards the drain."), _q("How does the problem get solved?", ["Tom hooks it back with a stick", "The rain stops", "Nina buys a new boat", "It sinks"], 0, "Tom pulls it back with the stick."), _q("Which pace is best for retelling?", ["Very fast", "Steady", "Silent", "Very slow with long gaps"], 1, "Steady is best."), _q("What should you do at a full stop?", ["Pause", "Shout", "Speed up", "Stop speaking"], 0, "A short pause helps your listener."), _q("What is joined handwriting?", ["Letters connected within a word", "Capital letters only", "Printing", "Drawing"], 0, "The letters connect with small strokes."), _q("Which vowel team is in 'paint'?", ["ay", "ee", "ai", "oa"], 2, "Paint has ai."), _q("Which word has the vowel team ee?", ["seat", "tree", "reach", "coat"], 1, "Tree has ee.")],
    "Type your answers in the practice boxes and submit them. Complete the aloud retelling and the handwriting on paper.", "Extension: retell a favourite book to a family member in under one minute, and write one joined sentence about it.",
    [("retell", "To tell a story again in your own words"), ("sequence", "The order in which things happen"), ("linking word", "A word that shows order, such as first or finally"), ("expression", "Using your voice to show feeling"), ("pace", "How fast you speak"), ("joined writing", "Letters connected with small strokes"), ("spacing", "The gaps between letters and words"), ("legible", "Neat enough to read easily")],
    [_video("Retelling a story with a beginning, middle and end", "jpOvY9gcHMc", "Watch how the story is retold using a beginning, a middle and an end. Notice the characters and the setting.", "Read the worked example aloud and practise the retelling from it.", ("What three parts does a retelling have?", ["Beginning, middle and end", "Title, picture and cover", "Question, answer and score"], 0, "A retelling has a beginning, a middle and an end."))],
    _sort("Is it a main event or a small detail?", "Sort each item from 'The Paper Boat' into the parts of a retelling.", ["Main event", "Small detail"], [("Nina floats her boat in a puddle", 0), ("The wind pushes the boat towards the drain", 0), ("Nina cannot reach it with the stick", 0), ("Tom hooks the boat back", 0), ("It is a rainy afternoon", 1), ("The puddle is by the gate", 1), ("The boat is made of paper", 1), ("They dry the boat on a seat", 1)]),
    [_wc("Which linking word shows the last event?", ["First", "Finally", "Next"], 1, "Finally is last."), _wc("Which is correct?", ["stai", "stay", "stey"], 1, "Stay ends with ay."), _wc("Which is correct?", ["paint", "payn", "peint"], 0, "Paint has ai."), _wc("Which is correct?", ["tre", "tree", "trea"], 1, "Tree has ee."), _wc("Which is correct?", ["reech", "reach", "reeche"], 1, "Reach has ea."), _wc("Which is correct?", ["cote", "coat", "coet"], 1, "Coat has oa."), _wc("Which is correct?", ["seat", "seet", "sete"], 0, "Seat has ea."), _wc("Which is neat joined writing?", ["Even size and spacing", "Letters of different sizes", "No spaces"], 0, "Even size and spacing make writing legible.")],
    [{"key":"partA","label":"Part A: main events","hint":"Five events from The Paper Boat, in order."}, {"key":"partB","label":"Part B: four-sentence retell","hint":"Use first, then, next and finally."}, {"key":"partC","label":"Part C: vowel teams","hint":"Type the vowel team in stay, paint, tree, reach, coat and seat."}, {"key":"events","label":"My five events","hint":"The main events in order."}, {"key":"script","label":"My retelling script","hint":"Five or six sentences with linking words."}, {"key":"speaking","label":"Speaking self-check","hint":"What went well, and one thing to improve."}, {"key":"handwriting","label":"Handwriting check","hint":"Were your size, joins and spacing neat? Which line was best?"}, {"key":"spelling","label":"Spelling words","hint":"Type the six words and mark the vowel team."}],
    ["Copying the story word for word", "Including every small detail", "Leaving out the ending", "Speaking too fast or too quietly", "Letters that change size, or words with no gaps"],
    ["Retell a family story aloud in five sentences.", "Write a joined-handwriting sentence about your day each evening this week."],
    "Part A: Nina floats her boat in a puddle; the wind pushes it towards the drain; Nina's stick cannot reach it; Tom hooks it back; they dry it and plan to sail it again. Part B: accept four sentences in order using first, then, next and finally. Part C: stay (ay), paint (ai), tree (ee), reach (ea), coat (oa), seat (ea). Main task: accept five correct events in order, a script with linking words that covers the problem and the ending, and honest self-checks. For handwriting, look for even size, neat joins and finger-width gaps. Quiz answers: main events in own words; First; Tom hooks the boat back; boat heads for the drain; Tom hooks it back with a stick; Steady; Pause; Letters connected within a word; ai; tree.",
)

LESSON["spelling"] = {"focus":"Vowel teams ai, ay, ee, ea, oa", "teaching":"Two vowels can work as a team to make one sound. In this list, ay ends stay, ai is in paint, ee is in tree, ea is in reach and seat, and oa is in coat.", "words":[_w("stay","st-ay","ay is at the end"),_w("paint","p-ai-nt","ai is in the middle"),_w("tree","tr-ee","ee makes long e"),_w("reach","r-ea-ch","ea makes long e"),_w("coat","c-oa-t","oa makes long o"),_w("seat","s-ea-t","ea makes long e")], "check":[_c("Which vowel team is in coat?",["oa","ea","ai"],0,"Coat has oa."),_c("Which is spelled correctly?",["stai","stay","stey"],1,"Stay ends with ay.")]}
LESSON["spelling_focus"] = "Vowel teams ai, ay, ee, ea, oa"
LESSON["hoard_words"] = list(WORDS)
