"""Stage 2 English, Weeks 1-2 of the program (60-minute lessons). Week 1 = lessons 1-4.
Not registered in LESSON_LIBRARY yet. Outcome codes come from nsw_outcomes_stage2_verified.py."""

def _q(q, opts, idx, why):
    return {"question": q, "type": "multiple_choice", "options": opts, "correct_index": idx, "explanation": why}


def _step(icon, title, explain, example, notice, chk):
    q, opts, idx, why = chk
    return {"icon": icon, "title": title, "explain": explain, "example": example, "notice": notice,
            "check": {"question": q, "options": opts, "correct_index": idx, "explanation": why}}


def build(key, title, mission, subject, codes, notes, intention, criteria, vocab, materials, prior,
          teaching, steps, worked, guided, independent, response, selfcheck, quiz, evidence, extension, cards):
    return {
        "seed_key": key, "library": True, "stage": "S2", "year_level": "Stage 2", "learning_area": "English",
        "subject": subject, "title": title, "child_mission": mission, "duration_minutes": 60, "pass_mark": 0.9,
        "outcome_codes": codes, "outcome_notes": notes, "learning_intention": intention,
        "success_criteria": criteria + ["I can score 90% or more on the Quest check."],
        "key_vocabulary": vocab, "materials": materials, "prior_knowledge": prior, "explicit_teaching": teaching,
        "teach_steps": steps, "worked_example": worked, "guided_practice": guided, "independent_task": independent,
        "response_prompt": response, "self_check": selfcheck,
        "accessibility_notes": "Allow dictation or typing. Break the written task into two sittings. Reduce the length by a third if needed.",
        "interactive_activities": [{"type": "flip_cards", "title": "Quest Codex: key terms",
                                    "cards": [{"front": f, "back": b} for f, b in cards]}],
        "steps": [
            {"title": "Step 1: Accept the quest", "detail": "Read your mission.", "duration_minutes": 5},
            {"title": "Step 2: Learn the map", "detail": "Four short lessons, each with an example and a quick try.", "duration_minutes": 20},
            {"title": "Step 3: Practise", "detail": "Flip the key-term cards and work through the guided practice.", "duration_minutes": 10},
            {"title": "Step 4: Apply it", "detail": "Complete the independent task.", "duration_minutes": 15},
            {"title": "Step 5: Quest check", "detail": "Answer the 10-question check. You need 9 out of 10.", "duration_minutes": 5},
            {"title": "Step 6: Hand it in", "detail": "Check your work and submit your evidence.", "duration_minutes": 5},
        ],
        "resources": [], "quiz": quiz,
        "reflection_prompts": ["What was the trickiest part today?", "What will you do differently next time?"],
        "evidence_instructions": evidence,
        "parent_notes": "Practice lesson only. Quiz scores are formative; competency is decided by the fortnightly mini exam. Check the written task against the success criteria.",
        "source_note": "Outcome codes from the NSW English K-10 Syllabus (NESA 2022), Stage 2. Parent to verify alignment on curriculum.nsw.edu.au.",
        "offline_alternative": "Complete all written tasks on paper and read the questions aloud.",
        "extension": extension, "follow_up_challenges": [],
    }


L1 = build(
    "s2-eng-w01-l1-spelling-strategies", "Spelling Detective: Four Strategies",
    "A tricky word has escaped the page! Learn four detective strategies to catch it and spell it right.",
    "Spelling: select, apply and describe strategies",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-HANDW-01"],
    {"EN2-SPELL-01": "Primary. Learns, applies and describes four strategies (quiz and word log).",
     "EN2-VOCAB-01": "Meets prefixes, suffixes and base words and uses them to understand words.",
     "EN2-HANDW-01": "Copies the word log in neat joined handwriting."},
    "We are learning to choose and use spelling strategies to spell tricky words.",
    ["I can break a word into sounds and into syllables.", "I can find the base word, prefix and suffix in a word.",
     "I can use Look, Say, Cover, Write, Check to learn a word.", "I can describe which strategy I used."],
    ["syllable", "base word", "prefix", "suffix", "strategy"],
    ["Paper or notebook", "Pencil", "Your own writing for tricky words"],
    "Child can write simple sentences.",
    "Good spellers use strategies instead of guessing. Four strategies: (1) sound it out, (2) clap the syllables, (3) find the word parts, (4) Look, Say, Cover, Write, Check for tricky words.",
    [
        _step("1", "Sound it out", "Say the word slowly and write a letter or letters for each sound. Some sounds need two letters, like sh, ch and th.",
              "chimp has four sounds: ch - i - m - p.", "Count sounds, not letters.",
              ("How many sounds are in 'ship'?", ["2", "3", "4"], 1, "sh - i - p is three sounds.")),
        _step("2", "Clap the syllables", "A syllable is one beat in a word. Clap as you say it and spell one beat at a time.",
              "fan-tas-tic has three syllables.", "Every syllable has a vowel sound.",
              ("How many syllables are in 'butterfly'?", ["2", "3", "4"], 1, "but-ter-fly has three beats.")),
        _step("3", "Find the word parts", "A base word carries the main meaning. A prefix goes at the front (un-, re-). A suffix goes at the end (-ing, -ed).",
              "unhappy = un + happy. jumping = jump + ing.", "The base word is the part that can stand alone.",
              ("What is the base word in 'replaying'?", ["re", "play", "ing"], 1, "re + play + ing: play is the base word.")),
        _step("4", "Look, Say, Cover, Write, Check", "For tricky words that do not follow the rules, look at the word, say it, cover it, write it from memory and check it.",
              "Tricky words: because, friend, said, again, people.", "Always check against the real word.",
              ("In Look, Say, Cover, Write, Check, what comes right after Cover?", ["Check", "Write", "Look"], 1, "You write it from memory, then check.")),
    ],
    "Word: unfriendly. Word parts: un + friend + ly. Syllables: un-friend-ly (3). Tricky part: 'ie' in friend. Look, Say, Cover, Write, Check for 'friend'.",
    "Take the words 'replaying' and 'because'. For each, say which strategy helps most and why.",
    "Find 10 words you misspelt in recent writing (or use: because, friend, said, again, people, would, could, through, favourite, beautiful). For each, write the word using the best strategy and note which strategy you used. Then copy your best five words in neat joined handwriting.",
    "Which strategy did you use most, and why did it work?",
    "Did I write 10 words, name a strategy for each, and write five in joined handwriting?",
    [
        _q("Which strategy breaks a word into beats?", ["Syllables", "Prefixes", "Capital letters", "Full stops"], 0, "Clapping beats finds the syllables."),
        _q("Which word contains the base word 'happy'?", ["unhappy", "hippo", "happen", "hope"], 0, "un + happy."),
        _q("How many sounds are in 'stamp'?", ["3", "4", "5"], 2, "s - t - a - m - p."),
        _q("How many syllables are in 'elephant'?", ["2", "3", "4"], 1, "el-e-phant."),
        _q("Which is spelt correctly?", ["freind", "friend", "frend"], 1, "friend has ie, then nd."),
        _q("Which is spelt correctly?", ["becuase", "because", "becaus"], 1, "because: be-cause."),
        _q("What is the suffix in 'playing'?", ["play", "ing", "pl"], 1, "A suffix goes at the end."),
        _q("What is the prefix in 'unlock'?", ["lock", "un", "ock"], 1, "A prefix goes at the front."),
        _q("Which strategy suits a tricky word like 'said'?", ["Look, Say, Cover, Write, Check", "Clap the syllables", "Guess it"], 0, "Tricky words need memory practice."),
        _q("What does 'unlock' mean?", ["to lock again", "to open a lock", "a big lock"], 1, "The prefix un- means not or the opposite."),
    ],
    "Upload a photo of your word log showing your 10 words, the strategy for each and five words in joined handwriting.",
    "Choose a longer word such as 'unforgettable' and explain every strategy you could use on it.",
    [("syllable", "One beat in a word."), ("base word", "The main part of a word that can stand alone."),
     ("prefix", "A word part added to the front."), ("suffix", "A word part added to the end."),
     ("strategy", "A method you choose to solve a problem.")],
)

L2 = build(
    "s2-eng-w01-l2-sentence-builder", "Sentence Builder: Punctuation Power",
    "The Sentence Bridge has holes in it! Use capital letters, full stops, commas and apostrophes to repair every plank.",
    "Creating written texts: sentences and punctuation",
    ["EN2-CWT-01", "EN2-SPELL-01", "EN2-HANDW-01"],
    {"EN2-CWT-01": "Primary. Writes and punctuates complete sentences.",
     "EN2-SPELL-01": "Spells contractions correctly.",
     "EN2-HANDW-01": "Writes the final paragraph in legible joined handwriting."},
    "We are learning to write complete sentences and punctuate them correctly.",
    ["I can tell a complete sentence from a fragment.", "I can use capital letters and the right end mark.",
     "I can use commas in a list.", "I can use an apostrophe in a contraction."],
    ["sentence", "fragment", "capital letter", "comma", "apostrophe", "contraction"],
    ["Paper or notebook", "Pencil"], "Child can write several words in a line.",
    "A complete sentence tells us who or what, and what happened, and makes sense on its own. It starts with a capital letter and ends with a full stop, question mark or exclamation mark. Commas separate items in a list. An apostrophe in a contraction shows missing letters.",
    [
        _step("1", "Complete sentences", "A sentence needs a who or what and a doing word, and must make sense alone. A fragment is missing a part.",
              "Complete: The girl ran home. Fragment: Under the table.", "Ask: who or what, and what happened?",
              ("Which is a complete sentence?", ["Running down the hill.", "The girl ran home.", "Under the table."], 1, "It has a who and an action.")),
        _step("2", "Capitals and end marks", "Begin every sentence with a capital letter. Use a full stop for a statement, a question mark for a question and an exclamation mark for strong feeling. Names of people and places also need capitals.",
              "Where did you put my hat?", "The end mark matches the job of the sentence.",
              ("Which end mark fits: 'Where did you put my hat'?", [".", "?", "!"], 1, "It is a question.")),
        _step("3", "Commas in a list", "Use commas to separate three or more items. The last two items are usually joined by 'and' with no comma.",
              "We bought apples, pears and plums.", "Commas separate; 'and' joins the last two.",
              ("Which is punctuated correctly?", ["We bought apples, pears and plums.", "We bought, apples pears, and plums."], 0, "Commas go between items.")),
        _step("4", "Apostrophes in contractions", "An apostrophe replaces missing letters when two words are squashed together.",
              "don't = do not. she's = she is.", "The apostrophe goes where the letters were.",
              ("'can't' is short for which words?", ["can not", "cat not", "cant"], 0, "The apostrophe replaces 'no'.")),
    ],
    "Fix: 'last week mia and dan went to brisbane they packed a hat a towel and a drink' becomes 'Last week Mia and Dan went to Brisbane. They packed a hat, a towel and a drink.'",
    "Fix this: 'my sister cant swim but she loves the beach' (answer: My sister can't swim, but she loves the beach.) Write your own fix for a similar sentence.",
    "Write a paragraph of six sentences about a day at the beach or the bush. Include one question, one list with commas and two contractions. Copy it out in neat joined handwriting.",
    "Which punctuation mark was the hardest to remember, and what helped?",
    "Does every sentence start with a capital and end with a mark? Did I include a list and two contractions?",
    [
        _q("Which is a complete sentence?", ["The boy kicked the ball.", "Over the fence.", "Running fast."], 0, "It says who and what happened."),
        _q("Which is written correctly?", ["My sister lives in Sydney.", "my sister lives in sydney.", "My sister lives in sydney."], 0, "Capitals for the start and the place."),
        _q("Which end mark fits: 'Are you coming to the park'?", [".", "?", "!"], 1, "It asks a question."),
        _q("What does the apostrophe in 'she's' show?", ["Missing letters (she is)", "A list", "A question"], 0, "she is becomes she's."),
        _q("Which list is correct?", ["I packed a hat, a towel and a drink.", "I packed, a hat a towel, and a drink."], 0, "Commas between items."),
        _q("'didn't' is short for:", ["did not", "did now", "didn"], 0, "The apostrophe replaces 'o'."),
        _q("Which is a fragment?", ["It was raining.", "Because it was raining.", "The rain fell."], 1, "It does not make sense on its own."),
        _q("Which has correct capitals?", ["Last week Mia and Dan went to Brisbane.", "last week mia and dan went to brisbane."], 0, "Capitals for the first word, names and places."),
        _q("Which end mark fits: 'Stop right there'?", ["!", "?", ","], 0, "A strong command can take an exclamation mark."),
        _q("Which is correct?", ["We can't wait.", "We cant wait.", "We ca'nt wait."], 0, "The apostrophe replaces the o."),
    ],
    "Upload a photo of your six-sentence paragraph in joined handwriting.",
    "Write a seven-item list inside one sentence and explain where each comma goes.",
    [("sentence", "A group of words that makes sense on its own."), ("fragment", "A group of words missing a part of a sentence."),
     ("capital letter", "Used at the start of sentences and for names."), ("comma", "Separates items in a list."),
     ("apostrophe", "Shows missing letters in a contraction."), ("contraction", "Two words squashed into one.")],
)

L3 = build(
    "s2-eng-w01-l3-reading-expression", "Voice of the Storyteller: Reading with Expression",
    "The lighthouse story needs a voice! Read aloud with accuracy, pace and expression so listeners feel every wave.",
    "Reading fluency and comprehension",
    ["EN2-REFLU-01", "EN2-RECOM-01", "EN2-OLC-01"],
    {"EN2-REFLU-01": "Primary. Practises accuracy, pace, phrasing and expression.",
     "EN2-RECOM-01": "Answers literal and inferential questions on a short passage.",
     "EN2-OLC-01": "Reads aloud to a listener and discusses how it sounded."},
    "We are learning to read aloud smoothly and with expression and to understand what we read.",
    ["I can read words accurately and fix mistakes.", "I can use punctuation to guide my voice.",
     "I can read in meaningful phrases.", "I can answer questions about what I read."],
    ["fluency", "expression", "phrasing", "pace", "punctuation"],
    ["A book or short text of his choice", "A device to record (optional)", "A listener"],
    "Child can read simple chapter-book text.",
    "Fluent reading has four parts: accuracy (right words), pace (not too fast or slow), phrasing (reading in chunks) and expression (voice shows meaning). Punctuation tells your voice what to do: a comma is a short pause, a full stop is a longer pause, a question mark makes the voice rise, an exclamation mark adds strong feeling.",
    [
        _step("1", "Accuracy", "Read every word as printed. If a word does not make sense, stop, go back and fix it.",
              "Read 'quiet' not 'quite' when the sentence is about silence.", "Good readers check that it makes sense.",
              ("A word you read does not make sense. What should you do?", ["Go back and re-read", "Keep going", "Skip the page"], 0, "Self-correcting is a strong reading habit.")),
        _step("2", "Pace and phrasing", "Read at a talking pace and group words into chunks that belong together.",
              "Every evening / Mr Bell climbed the steps / to the top.", "Chunks follow the meaning.",
              ("What is phrasing?", ["Reading in meaningful chunks", "Reading as fast as possible", "Reading silently"], 0, "Phrasing groups words by meaning.")),
        _step("3", "Punctuation signals", "Commas, full stops, question marks and exclamation marks tell your voice when to pause, drop, rise or show feeling.",
              "Where are you going? (voice rises)", "Punctuation is a set of reading instructions.",
              ("What does your voice do at a question mark?", ["Rises", "Drops lower", "Stops completely"], 0, "Questions usually rise at the end.")),
        _step("4", "Expression", "Let your voice show feelings. Use loud and soft, fast and slow, to match the story.",
              "Whispered: 'Be quiet, someone is coming.'", "Match the voice to the meaning.",
              ("Which words should be read softly?", ["'Whisper', she said", "'Look out!' he shouted"], 0, "Whispering matches a soft voice.")),
    ],
    "Passage: Every evening, Mr Bell climbed the 112 steps to the top of the lighthouse. He polished the great glass lens until it gleamed. Then he lit the lamp, and its beam swept across the dark water to warn the ships. Read it in three chunks, pausing at each comma and full stop.",
    "Read the passage aloud twice. First go for accuracy, then for expression. Then answer: why did Mr Bell light the lamp?",
    "Choose a page from your own book. Read it aloud three times to a listener or record it. After each read, rate your accuracy, pace and expression from 1 to 3. Write two sentences on what improved.",
    "Which of the four parts of fluency is your strongest, and which will you work on?",
    "Did I read three times, rate each, and write two sentences on what improved?",
    [
        _q("What does a comma tell your voice to do?", ["Pause briefly", "Stop for a long time", "Shout"], 0, "A comma is a short pause."),
        _q("What does your voice do at a question mark?", ["Rises", "Falls", "Stays flat"], 0, "Questions usually rise."),
        _q("What is phrasing?", ["Reading in meaningful chunks", "Reading very fast", "Reading word by word"], 0, "Chunks follow meaning."),
        _q("Passage: 'Every evening, Mr Bell climbed the 112 steps to the top of the lighthouse.' How many steps did he climb?", ["12", "112", "211"], 1, "The text says 112 steps."),
        _q("Passage: 'He polished the great glass lens until it gleamed.' What does 'gleamed' suggest?", ["Shone brightly", "Broke", "Went dark"], 0, "To gleam is to shine."),
        _q("Passage: 'Then he lit the lamp, and its beam swept across the dark water to warn the ships.' Why did he light the lamp?", ["To warn ships", "To read a book", "To cook dinner"], 0, "The beam warns the ships."),
        _q("What happens first in the passage?", ["He climbs the steps", "He lights the lamp", "He polishes the lens"], 0, "He climbs, polishes, then lights the lamp."),
        _q("You read a word that makes no sense. What do you do?", ["Go back and fix it", "Ignore it", "Stop reading"], 0, "Self-correct."),
        _q("Which part of fluency is about your voice showing feeling?", ["Expression", "Accuracy", "Pace"], 0, "Expression is the feeling in your voice."),
        _q("What does an exclamation mark add?", ["Strong feeling", "A question", "A list"], 0, "It shows strong feeling or force."),
    ],
    "Upload a short recording or a photo of your rating table and two sentences.",
    "Read a poem aloud and plan where to pause, speed up and slow down.",
    [("fluency", "Reading smoothly and with understanding."), ("expression", "Using your voice to show meaning and feeling."),
     ("phrasing", "Reading in meaningful chunks."), ("pace", "The speed of your reading."),
     ("punctuation", "Marks that guide pauses and voice.")],
)

L4 = build(
    "s2-eng-w01-l4-show-dont-tell", "Paint with Words: Show, Don't Tell",
    "A blank page is waiting! Use senses, strong verbs and precise noun groups to paint a place so clearly that your reader steps inside.",
    "Creating written texts: imaginative description",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01", "EN2-HANDW-01"],
    {"EN2-CWT-01": "Primary. Writes an imaginative description of a place and a character.",
     "EN2-VOCAB-01": "Chooses precise Tier 2 words including strong verbs.",
     "EN2-SPELL-01": "Proofreads and corrects spelling using strategies.",
     "EN2-HANDW-01": "Writes the final copy in neat joined handwriting."},
    "We are learning to show feelings and places with precise words instead of telling.",
    ["I can show a feeling rather than name it.", "I can use at least three senses.", "I can use strong verbs.", "I can build a precise noun group."],
    ["show, don't tell", "senses", "strong verb", "noun group", "precise"],
    ["Paper or notebook", "Pencil", "Coloured pencils"], "Child can write several connected sentences.",
    "Telling names a feeling: She was scared. Showing lets the reader work it out: Her hands trembled and she held her breath. Writers also use the five senses, strong verbs (trudged, not walked) and noun groups with adjectives (the rusty, creaking gate).",
    [
        _step("1", "Show, don't tell", "Instead of naming a feeling, describe what the body does or what the character notices.",
              "Tell: He was nervous. Show: He wiped his sweaty palms on his shorts.", "The reader works out the feeling.",
              ("Which sentence shows rather than tells?", ["She was happy.", "She grinned and skipped down the path."], 1, "It shows actions.")),
        _step("2", "Use the senses", "Describe what you see, hear, smell, taste and feel.",
              "The salty smell of the sea drifted over the rocks.", "Pick three senses at least.",
              ("Which sense is used: 'the salty smell of the sea'?", ["Sight", "Smell", "Hearing"], 1, "Smell.")),
        _step("3", "Strong verbs", "A strong verb carries more meaning than a plain one plus an adverb.",
              "walked slowly and heavily becomes trudged.", "One strong verb beats two weak words.",
              ("Which verb means to walk slowly and heavily?", ["skipped", "trudged", "dashed"], 1, "Trudged.")),
        _step("4", "Precise noun groups", "Add describing words before a noun to be precise.",
              "the rusty, creaking gate", "Precise describing words help the reader picture it.",
              ("Which noun group is most precise?", ["a gate", "the gate", "the rusty, creaking gate"], 2, "It gives two details.")),
    ],
    "Plain: The old house was scary. Better: A cold draught whistled through the broken window, and the staircase groaned as Ella crept upward.",
    "Rewrite 'The forest was quiet and dark' using two senses and one strong verb.",
    "Write 8 to 10 sentences describing a place at night (a beach, the bush, a haunted house, a city street). Use at least three senses, two strong verbs and two precise noun groups. Show one feeling without naming it. Proofread with spelling strategies, then copy it out in joined handwriting.",
    "Which sentence are you proudest of, and which technique did it use?",
    "Did I use three senses, two strong verbs and two precise noun groups? Did I show a feeling?",
    [
        _q("Which sentence shows rather than tells?", ["Her hands trembled and she held her breath.", "She was scared."], 0, "It shows actions and body language."),
        _q("Which sense: 'the salty smell of the sea'?", ["Smell", "Hearing", "Sight"], 0, "Smell."),
        _q("Which strong verb means to walk slowly and heavily?", ["trudged", "skipped", "dashed"], 0, "Trudged."),
        _q("Which noun group is most precise?", ["the rusty, creaking gate", "the gate", "a gate"], 0, "More detail."),
        _q("Which sentence uses sound?", ["The floorboards groaned under his feet.", "The floor was brown."], 0, "Groaned is a sound."),
        _q("'His face went red and he stared at the floor' shows which feeling?", ["Embarrassed", "Excited", "Sleepy"], 0, "The actions show embarrassment."),
        _q("Which word is a strong verb for 'said quietly'?", ["whispered", "talked", "spoke"], 0, "Whispered."),
        _q("Why do writers describe a setting?", ["To help readers picture and feel it", "To make the story longer", "To fill the page"], 0, "Description builds a picture."),
        _q("Which is 'telling'?", ["He was angry.", "He slammed the door and clenched his fists."], 0, "Telling names the feeling."),
        _q("Which replaces 'ran quickly'?", ["sprinted", "ran", "went"], 0, "Sprinted."),
    ],
    "Upload a photo of your final description in joined handwriting. Highlight the senses and strong verbs.",
    "Write the same place in the morning and compare the atmosphere.",
    [("show, don't tell", "Describe actions and details instead of naming a feeling."), ("senses", "Sight, sound, smell, taste and touch."),
     ("strong verb", "A verb with a precise meaning, like trudged."), ("noun group", "A noun with describing words, like the rusty gate."),
     ("precise", "Exact and clear.")],
)

WEEK_1 = [L1, L2, L3, L4]
