"""Stage 2 English, plan week 3, lesson 4: readers theatre and punctuating dialogue.
Fully taught from scratch. Videos were found via search and are checked on playback."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W3L4 = build(
    "s2-eng-w03-l4-readers-theatre-and-dialogue", "Readers Theatre: Dialogue Aloud",
    "Perform a script with your voice, then learn how to write what characters say with speech marks.",
    "Speaking and writing: readers theatre and dialogue",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Reads a script aloud with expression, and writes dialogue with correct speech marks, capital letters, commas and end punctuation.",
     "EN2-VOCAB-01": "Learns the terms script, narrator, dialogue, speech marks, speech verb, expression and stage direction.",
     "EN2-SPELL-01": "Spells speech verbs: whispered, shouted, replied, exclaimed, asked and announced."},
    "We are learning to read a script aloud with expression, and to write what characters say using speech marks.",
    ["I can say what readers theatre is and name the parts of a script.",
     "I can read aloud with expression, using my voice and face.",
     "I can use punctuation clues to know how to say a line.",
     "I can put speech marks around the exact words a character says.",
     "I can place commas, capital letters and end punctuation in dialogue.",
     "I can use a new line for each new speaker and choose strong speech verbs."],
    ["readers theatre", "script", "narrator", "dialogue", "speech marks", "speech verb", "expression", "stage direction"],
    ["Paper or notebook", "Pencil", "A friend or family member to read with", "A short story with dialogue"],
    "Nothing is assumed. Child can read short sentences aloud and write several sentences. Scripts and speech marks are taught from the beginning.",
    "READERS THEATRE is a way of performing a story or play by reading it aloud from a script. There are no costumes or sets. Everything depends on your voice and your face.\n\nA SCRIPT shows who says each line. In a story, what characters say is called DIALOGUE, and we put it inside SPEECH MARKS so the reader can tell who is speaking.\n\nIn this lesson you will perform a script with expression, then turn part of a story into dialogue with correct punctuation. The two skills fit together: a performer shows how a line is said, and a writer shows it with punctuation and strong speech verbs.",
    [
        _step("1", "What is readers theatre?",
              "Readers theatre is a style of performance where actors read from a script. There are no costumes, no props and not much movement. The audience listens, so the VOICE and FACE do all the work.\n\nThe script has different parts. A NARRATOR tells the parts of the story that are not spoken. CHARACTERS say their own lines. Each reader takes one or more parts.\n\nYou can do readers theatre with a picture book, a poem or a short play. Readers hold the script and look up at the audience between lines.\n\nReading this way builds fluency, which means reading smoothly and with expression, and it is a lot of fun.",
              "One book, three readers: one is the narrator, one is the cat and one is the dog. Each reads only their part. Together they perform the whole story.",
              "Voice and face tell the story.",
              ("What does readers theatre rely on most?", ["Voice and face", "Costumes", "A big stage"], 0, "There are no costumes or sets.")),
        _step("2", "How a script looks",
              "A script is set out in a special way.\n\n- Each line starts with the NAME of the speaker, followed by a colon.\n- You do NOT use speech marks in a script. The name tells you who is speaking.\n- A new speaker starts on a new line.\n- STAGE DIRECTIONS tell the reader how to say the line or what to do. They are written in brackets, often in italics: (whispering), (laughing).\n\nExample:\nNARRATOR: The wind howled across the park.\nSAM: (shouting) My kite! It's gone!\nMUM: (calmly) Don't worry, we'll find it.\n\nWhen you read, you say the name only in your head. You read just the words after the colon.",
              "Script: SAM: (shouting) My kite! It's gone! You read: 'My kite! It's gone!' in a loud, worried voice. You do not say SAM or the brackets.",
              "Name, colon, words. Directions in brackets.",
              ("Do scripts use speech marks?", ["No, the speaker's name is used instead", "Yes, always", "Only for questions"], 0, "Scripts show speakers with names.")),
        _step("3", "Reading with expression",
              "Expression means making your reading sound alive. You can change four things in your voice.\n\nVOLUME: loud or soft.\nPACE: fast or slow.\nTONE: happy, angry, scared, calm.\nPITCH: high or low.\n\nYour FACE and BODY help too. Raise your eyebrows when you are surprised. Look worried when you are scared.\n\nAlso use PAUSES. Stop for a moment at a full stop. Pause longer before something dramatic.\n\nAsk yourself: how does this character feel? A scared character might speak quietly and quickly. A giant might speak slowly in a deep voice.",
              "The line 'I can hear footsteps.' can be read in a whisper (scared), a shout (excited) or slowly (suspicious). The words are the same, but the feeling is different.",
              "Change volume, pace, tone and pitch to match the feeling.",
              ("Which is NOT a way to change your voice?", ["Changing your name", "Volume", "Pace"], 0, "Name is not part of the voice.")),
        _step("4", "Punctuation tells you how to read",
              "Punctuation gives clues about how to say a line.\n\nFull stop (.): stop and take a breath.\nComma (,): short pause.\nQuestion mark (?): voice goes up at the end.\nExclamation mark (!): say it with strong feeling, louder or more excited.\nThree dots (...): a trailing pause, maybe unsure or mysterious.\nBold or CAPITAL letters: stress this word.\n\nRead these aloud:\n'Hello.' (calm)\n'Hello?' (unsure)\n'Hello!' (excited)\n'Hello...' (nervous)\n\nOne word, four different meanings, just by changing the punctuation.",
              "'You found it' and 'You found it!' and 'You found it?' all say different things. The punctuation tells you the mood.",
              "Read the punctuation, then perform it.",
              ("What does an exclamation mark tell you?", ["Say it with strong feeling", "Whisper", "Skip the line"], 0, "It signals strong feeling.")),
        _step("5", "Dialogue in a story",
              "In a story, we do not use a script layout. Instead, the exact words a character says are put inside SPEECH MARKS. These are also called quotation marks or inverted commas. They look like this: \" \".\n\nThink of them as a door. The opening speech marks open the door to the character's words. The closing speech marks shut it.\n\nOnly the words that are actually SPOKEN go inside. 'Sam said that he was cold' has no speech marks, because it tells about the speech. 'I'm cold,' said Sam has speech marks because they are his exact words.\n\nThe part that tells who is speaking, like 'said Sam', is called the speech tag or reporting clause. It stays outside the speech marks.",
              "Inside the marks: \"Look at the sky,\" said Mia. Outside: said Mia. Not speech: Mia said the sky looked pretty.",
              "Only spoken words go inside the speech marks.",
              ("Which words go inside speech marks?", ["The exact words spoken", "The speaker's name", "The whole page"], 0, "Speech marks hold the exact words.")),
        _step("6", "Punctuating dialogue correctly",
              "Follow these four rules.\n\n1. The first spoken word starts with a CAPITAL letter. \"Look out!\" shouted Tom.\n2. If the speech tag comes AFTER the speech, put a comma (or ? or !) INSIDE the closing marks. \"I'm hungry,\" said Ben. \"Where are you going?\" asked Mum.\n3. If the tag comes BEFORE the speech, put a comma after the tag, then open the marks. Ben said, \"I'm hungry.\" The full stop goes inside the marks.\n4. Start a NEW LINE every time a new person speaks.\n\nExample:\n\"Where is my kite?\" asked Sam.\n\"It's up in the tree,\" said Mum.\n\nNotice how the question mark and the comma sit inside the speech marks, and each speaker has their own line.",
              "Correct: \"I can see it,\" whispered Mia. Wrong: \"I can see it\", whispered Mia. The comma must be inside the marks. Correct: Mia whispered, \"I can see it.\"",
              "Capital, punctuation inside, new speaker new line.",
              ("Where does the comma go in: 'I'm tired' said Dad?", ["Inside the closing speech marks", "Outside the closing speech marks", "At the start"], 0, "The comma goes inside the speech marks.")),
        _step("7", "Strong speech verbs",
              "The word 'said' is useful, but it can get boring. A SPEECH VERB tells how someone spoke, so the reader can hear the voice.\n\nQuiet: whispered, muttered, murmured.\nLoud: shouted, yelled, called, exclaimed.\nAnswering or asking: replied, asked, wondered.\nOther: announced, groaned, giggled, sighed.\n\n'Come here!' shouted Mum. 'I'm scared,' whispered Ben. 'Where are we going?' asked Mia.\n\nYou can also add an adverb: 'Please help,' whispered Ben nervously.\n\nDo not change every 'said'. A mix is best. Choose a strong verb when the way something is said matters.\n\nPractise spelling: whispered, shouted, replied, exclaimed, asked, announced. Use Look, Say, Cover, Write, Check.",
              "Weak: 'Stop!' said Tom. Strong: 'Stop!' shouted Tom. Weak: 'I'm scared,' said Ben. Strong: 'I'm scared,' whispered Ben.",
              "Choose a speech verb that shows the voice.",
              ("Which speech verb shows a quiet voice?", ["whispered", "shouted", "yelled"], 0, "Whispered means spoken softly.")),
        _step("8", "From story to script",
              "You can turn a story into a script. Follow these steps.\n\n1. Find the spoken words. They are inside speech marks.\n2. Find who says each one.\n3. Write the speaker's name and a colon, then the words, without speech marks.\n4. Turn the speech verb or adverb into a stage direction in brackets.\n5. Put the other parts, such as description, into the NARRATOR's lines.\n\nStory: \"Look at the sky,\" whispered Mia. Sam gasped. \"It's a dragon!\"\n\nScript:\nMIA: (whispering) Look at the sky.\nNARRATOR: Sam gasped.\nSAM: (excited) It's a dragon!\n\nYou can also go the other way, from a script back to a story. Add speech marks and a speech tag.",
              "Story: \"Where is my kite?\" asked Sam. Script: SAM: (worried) Where is my kite? Script back to story: \"Where is my kite?\" asked Sam worriedly.",
              "Story to script: names and brackets. Script to story: speech marks and tags.",
              ("In a script, where does the way of speaking go?", ["In brackets as a stage direction", "In speech marks", "At the end"], 0, "Stage directions are in brackets.")),
        _step("9", "Rehearse and perform",
              "Now perform your own readers theatre.\n\n1. Choose a short script or turn a page of a story into a script, with a narrator and at least two characters.\n2. Mark up your script. Underline words to stress, add pauses with a slash (/), and note the feelings in brackets.\n3. Practise on your own, then with a partner. Read it three times, getting better each time.\n4. Perform it for an audience. Look up between lines, speak clearly, and use your voice and face.\n5. Ask for feedback. What did they hear? Which line was best? What could be even better?\n\nIf you perform alone, you can play all parts and change your voice for each character.",
              "Mark-up: SAM: (shouting) My KITE! / It's gone! The capital letters show a stressed word, and the slash marks a pause.",
              "Mark up, practise three times, then perform.",
              ("What should you do before performing?", ["Mark up your script and practise", "Read it once quickly", "Skip practice"], 0, "Practice improves expression.")),
    ],
    "Model script: NARRATOR: The wind howled across Pelican Park. SAM: (shouting) My kite! It's gone! MUM: (calmly) Don't worry, Sam. We'll find it.\n\nModel dialogue: \"My kite! It's gone!\" shouted Sam.\n\"Don't worry,\" said Mum calmly. \"We'll find it.\"\n\nCheck: capital letter at the start of each speech, comma or ! inside the speech marks, tag outside, new line for a new speaker, and a strong speech verb (shouted). Readers theatre check: clear voice, expression that matches the feeling, pauses, looking up.",
    "1) Read the script aloud with a partner or by yourself, changing your voice for each character. 2) Rewrite four lines of dialogue from a book, adding the correct speech marks, capital letters and commas. 3) Change 'said' to a strong speech verb in five sentences. 4) Turn four lines of dialogue into a script. 5) Write a short conversation of six lines between two characters, with a new line for each speaker. 6) Practise spelling: whispered, shouted, replied, exclaimed, asked, announced.",
    "Write a six-line conversation between two characters with correct speech marks, then perform it aloud. Upload a photo of your writing, or a recording of your performance.",
    "Which line did you perform best? Which punctuation mark helped you most? What speech verb did you choose and why?",
    "Does each spoken sentence start with a capital letter? Are speech marks around only the spoken words? Is the comma, question mark or exclamation mark inside the speech marks? Did I start a new line for each speaker? Did I use at least two strong speech verbs? Did I spell them correctly?",
    [
        _q("What is readers theatre?", ["Reading a script aloud with expression", "Silent reading", "Drawing a picture"], 0, "It is performing by reading aloud."),
        _q("What does a narrator do?", ["Tells the parts that are not spoken", "Plays every character", "Only reads the title"], 0, "The narrator tells the story between lines."),
        _q("Which punctuation mark means say it with strong feeling?", ["!", ".", ","], 0, "An exclamation mark shows strong feeling."),
        _q("What goes inside speech marks?", ["The exact words spoken", "The speaker's name", "The whole story"], 0, "Speech marks surround spoken words."),
        _q("Which is punctuated correctly?", ["\"I'm cold,\" said Ben.", "\"I'm cold\", said Ben.", "I'm cold, said Ben."], 0, "The comma goes inside the speech marks."),
        _q("Which sentence needs NO speech marks?", ["Ben said that he was cold.", "\"I'm cold,\" said Ben.", "\"Brr!\" said Ben."], 0, "It reports the speech without the exact words."),
        _q("When do you start a new line in dialogue?", ["When a new person speaks", "After every word", "Never"], 0, "New speaker, new line."),
        _q("Which speech verb shows a quiet voice?", ["whispered", "shouted", "bellowed"], 0, "Whispered is quiet."),
        _q("Which is spelt correctly?", ["exclaimed", "exclamed", "exclaimd"], 0, "Exclaim + ed has an i."),
        _q("In a script, how do you show how to say a line?", ["A stage direction in brackets", "Speech marks", "A new title"], 0, "Stage directions go in brackets."),
    ],
    "Upload a photo of your dialogue writing, or a recording of your performance.",
    "Rewrite your conversation as a script, then perform it with a partner. Which version is easier to perform and which is easier to read?",
    [("readers theatre", "A performance where actors read from a script, using voice and face."), ("script", "A written text for performing, showing who says each line."), ("narrator", "The speaker who tells the parts of a story that are not dialogue."),
     ("dialogue", "The words that characters say."), ("speech marks", "Marks that surround the exact words a person says."), ("speech verb", "A verb that shows how something is said, such as whispered or shouted."),
     ("expression", "Using your voice and face to show feeling."), ("stage direction", "A note in brackets that tells the reader how to say a line.")],
    [
        _video("Readers Theater: Who Is Sleeping", "Jbgj3qldLYw",
               "Watch how readers choose parts, such as a narrator and animal characters, change their voices and add sounds to make the story fun. Notice how each part is read.",
               "Choose a part and say one line in a character voice.",
               ("What did the readers do to make the story fun?", ["Changed their voices for each character", "Read in silence", "Left out the characters"], 0, "They used different voices.")),
        _video("How To Use Speech Marks", "u6pkcdEylTE",
               "Watch the rules for speech marks: put the exact words inside, start with a capital letter, put the comma or question mark inside, and use a new line for each speaker.",
               "Write two lines of dialogue using the rules you saw.",
               ("What must the first spoken word begin with?", ["A capital letter", "A comma", "A number"], 0, "Speech starts with a capital letter.")),
    ],
    _sort("Punctuation sorter", "Which job does each mark do? Tap a job, then Check.",
          ["Voice goes up", "Strong feeling", "Stop and breathe"],
          [("?", 0), ("Is it a dragon?", 0), ("!", 1), ("Look out!", 1), (".", 2), ("We went home.", 2)]),
    [
        _wc("Readers theatre uses your voice and ___.", ["face", "costume", "stage"], 0, "Voice and face tell the story."),
        _wc("The speaker who tells the non-spoken parts is the ___.", ["narrator", "actor", "author"], 0, "The narrator tells the story."),
        _wc("Spoken words go inside ___ marks.", ["speech", "dot", "star"], 0, "Speech marks surround spoken words."),
        _wc("A stage direction is written in ___.", ["brackets", "capitals only", "red"], 0, "Directions go in brackets."),
        _wc("Which is spelt correctly?", ["whispered", "wispered", "whisperd"], 0, "Whisper + ed."),
        _wc("Which is spelt correctly?", ["announced", "anounced", "announsed"], 0, "Announce + d."),
    ],
    [
        {"key": "dialogue", "label": "My dialogue", "hint": "Six lines between two characters, with speech marks."},
        {"key": "script", "label": "My script", "hint": "The same lines as a script with names and brackets."},
        {"key": "markup", "label": "My mark-up", "hint": "Which words did you stress and where did you pause?"},
        {"key": "spelling", "label": "Spelling words", "hint": "whispered, shouted, replied, exclaimed, asked, announced."},
    ],
    ["Putting the comma outside the closing speech marks.", "Putting speech marks around words that were not spoken.", "Not starting a new line for a new speaker.", "Forgetting the capital letter at the start of speech.", "Reading everything in the same flat voice.", "Using speech marks in a script."],
    [{"title": "Readers Theatre Performance", "description": "Perform your script for someone. Use a different voice for each character, and look up between lines.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check that dialogue has speech marks only around spoken words, a capital at the start of each speech, commas or end punctuation inside the closing marks, tags outside, a new line for each speaker, and at least two strong speech verbs spelt correctly. The script should use names, colons and brackets, with no speech marks. Sorter: Voice goes up: ? and Is it a dragon? Strong feeling: ! and Look out! Stop and breathe: . and We went home.",
)

LESSONS = [W3L4]
