"""Stage 2 English, Block A (narrative writing), week 5, lessons 1 to 4.
Pass 1: lessons only. Videos are empty and the module is not yet registered in lesson_library.py.
Keys use the prefix a5."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A5L1 = build(
    "s2-eng-a5-l1-setting-and-atmosphere", "Setting and Atmosphere",
    "Learn how writers use place, time and the senses to create a mood.",
    "Reading and writing: setting",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies how a text uses setting details to create mood.",
     "EN2-CWT-01": "Writes a setting description using sensory detail and precise language.",
     "EN2-VOCAB-01": "Learns the terms setting, atmosphere, mood, sensory detail and noun group."},
    "We are learning how writers build a setting and create an atmosphere that makes the reader feel something.",
    ["I can say what a setting is.", "I can name the mood of a setting.", "I can use the five senses in description.", "I can choose words that match the mood.", "I can write a short setting description."],
    ["setting", "atmosphere", "mood", "sensory detail", "noun group"],
    ["Paper or notebook", "Pencil", "A story you are reading (your parent will help you choose)"],
    "Child has met the words setting and sensory detail in the opening lesson. Everything about setting and atmosphere is taught from the beginning.",
    "The SETTING of a story is where and when it happens. It can be a place, such as a forest or a classroom, and a time, such as midnight or a hot summer afternoon.\n\nGood writers also create an ATMOSPHERE. That is the feeling a place gives you, such as peaceful, spooky, busy or lonely. The reader feels it before any character does anything.\n\nIn this lesson you will learn how settings are built from details, how word choice sets the mood, and then you will write your own.",
    [
        _step("1", "Where and when",
              "Every story has a setting. It answers two questions: WHERE are we, and WHEN is it?\n\nWhere can be big (a country, a city) or small (a kitchen, a cave). When can be a time of day, a season, or a period in history.\n\nThe setting matters because it affects what can happen. A story on a desert island has different problems from a story in a school.\n\nWhen you read, look for clues. Words like 'dusty attic', 'midwinter' or 'busy market' tell you about the setting without a label.",
              "Where: an old lighthouse. When: a stormy night in autumn.",
              "Setting is where and when.",
              ("What does setting tell us?", ["Where and when", "Who and why", "The ending"], 0, "Setting is the place and time.")),
        _step("2", "Atmosphere and mood",
              "ATMOSPHERE is the feeling a setting creates. MOOD is the feeling the reader gets. The two work together.\n\nA dark forest with creaking branches creates a spooky atmosphere. A sunny beach with laughing children creates a happy one.\n\nThe same place can have different atmospheres. A school hall is cheerful during a concert and eerie when it is empty at night.\n\nBefore you write, decide the mood you want: calm, tense, cheerful, gloomy, mysterious. Every detail you choose should help build that one feeling.",
              "Same house. Mood A: golden light spilled from the windows. Mood B: one shutter banged in the dark.",
              "Choose one mood and make every detail fit it.",
              ("Which detail suits a spooky mood?", ["A shutter banging in the dark", "Children laughing", "A warm bakery smell"], 0, "The banging shutter is eerie.")),
        _step("3", "The five senses",
              "The strongest descriptions use SENSORY DETAIL. Think about all five senses, not only sight.\n\nSee: shadows stretched across the floor.\nHear: the floorboards groaned.\nSmell: the air smelt of damp wool.\nFeel: a cold draught brushed her neck.\nTaste: the air tasted of salt.\n\nYou do not need all five every time. Pick two or three that suit your mood. Sound and smell often make a place feel real very fast.\n\nAsk: if I were standing here, what would I notice first?",
              "Kitchen: the smell of toast (smell), the radio crackling (hearing), the warm tiles (feel).",
              "Use two or three senses, not just sight.",
              ("Which is a sound detail?", ["The floorboards groaned.", "The room was big.", "It was green."], 0, "Groaned is a sound.")),
        _step("4", "Precise words and noun groups",
              "Strong settings use precise nouns and verbs, and noun groups with detail.\n\nVague: 'There was a big old building.'\nPrecise: 'A crumbling stone mill leaned over the river.'\n\nA NOUN GROUP is a noun with words that describe it, such as 'the crumbling stone mill'.\n\nPick verbs that give the place life. 'Mist crept across the paddock' is stronger than 'There was mist in the paddock'.\n\nAvoid too many adjectives in a row. Two good ones are better than five weak ones.",
              "Weak: It was a nice beach. Strong: Waves folded over the pale sand and gulls wheeled above the rocks.",
              "Precise nouns and lively verbs build atmosphere.",
              ("Which is the more precise?", ["A crumbling stone mill", "A big old thing", "A nice place"], 0, "Precise words give a clear picture.")),
        _step("5", "Write a setting description",
              "Now write 4 to 6 sentences describing a setting for a story.\n\n1. Choose the place and time.\n2. Choose one mood.\n3. Write down two or three sensory details that fit it.\n4. Write your first sentence with a noun group.\n5. Use at least one strong verb.\n6. Do not name the mood. Let the details show it.\n\nRead it aloud. Does it make you feel the mood?",
              "Model: Late afternoon light slanted through the dusty attic window. Boxes leaned in towers against the wall. Somewhere above, a loose tile tapped in the wind, and the air smelt of old paper.",
              "Place, mood, senses, precise words.",
              ("Should you name the mood?", ["No, show it with details", "Yes, always", "Only at the end"], 0, "Details show the mood.")),
    ],
    "Model answers. Setting: where and when a story happens. Atmosphere: the feeling a place creates. Spooky details: a banging shutter, dark corridor, groaning floorboards. Cheerful details: sunshine, laughter, a warm smell of baking. Sample description: Late afternoon light slanted through the dusty attic window. Boxes leaned in towers against the wall. Somewhere above, a loose tile tapped in the wind, and the air smelt of old paper.",
    "1) Say the setting of a story your parent chooses. 2) Write the mood of three short settings. 3) Write one sentence for each of three senses about the same place. 4) Turn a vague sentence into a precise one. 5) Write your 4 to 6 sentence setting description.",
    "Write a 4 to 6 sentence description of a setting that creates one mood. Do not name the mood. Upload a photo of your writing.",
    CHECK,
    "Did I say where and when? Did I choose one mood? Did I use two or three senses? Did I use a noun group and a strong verb? Did I avoid naming the mood? Is it 4 to 6 sentences?",
    [
        _q("Setting is...", ["where and when a story happens", "who the hero is", "how it ends"], 0, "Setting is place and time."),
        _q("Atmosphere is...", ["the feeling a place creates", "a type of noun", "the title"], 0, "Atmosphere is the feeling."),
        _q("Which detail suits a cheerful mood?", ["Sunshine and laughter", "A creaking door", "A cold empty hall"], 0, "Sunshine and laughter are cheerful."),
        _q("How many senses can you use?", ["Up to five", "Only one", "Exactly ten"], 0, "There are five senses."),
        _q("A noun group is...", ["a noun with describing words", "a group of verbs", "a full stop"], 0, "A noun group adds detail to a noun."),
        _q("Which is more precise?", ["A crumbling stone mill", "A big building", "A thing"], 0, "Precise words give a clear picture."),
        _q("Should every detail fit the mood?", ["Yes", "No", "Only the first"], 0, "Details should build one mood."),
    ],
    "Upload a photo of your setting description.",
    "Rewrite your setting with the opposite mood. Which details did you change?",
    [("setting", "Where and when a story happens."), ("atmosphere", "The feeling a place creates."), ("mood", "The feeling the reader gets from a text."), ("sensory detail", "Detail about what can be seen, heard, smelt, felt or tasted."), ("noun group", "A noun with words that describe it.")],
    [],
    _sort("Mood sorter", "Which mood does each detail build? Tap a mood, then Check.",
          ["Spooky", "Cheerful"],
          [("a shutter banging in the dark", 0), ("mist creeping along the empty path", 0), ("an owl's eyes glowing in the trees", 0), ("golden sunshine on the garden", 1), ("children laughing by the creek", 1), ("the smell of warm bread", 1)]),
    [
        _wc("The place and time of a story is the ___.", ["setting", "plot", "theme"], 0, "Setting is place and time."),
        _wc("The feeling a place creates is ___.", ["atmosphere", "alphabet", "adverb"], 0, "Atmosphere is the feeling."),
        _wc("Detail about the five senses is ___ detail.", ["sensory", "silent", "simple"], 0, "Sensory relates to the senses."),
        _wc("Which is spelt correctly?", ["atmosphere", "atmosfere", "atmospher"], 0, "Atmosphere ends -phere."),
        _wc("Which is spelt correctly?", ["mysterious", "misterious", "mysterius"], 0, "Mysterious has -ious."),
    ],
    [
        {"key": "senses", "label": "Three senses", "hint": "One sentence each about the same place."},
        {"key": "precise", "label": "Precise sentence", "hint": "A vague sentence made precise."},
        {"key": "description", "label": "Setting description", "hint": "4 to 6 sentences with one mood."},
    ],
    ["Naming the mood instead of showing it.", "Using only sight.", "Mixing moods in one description.", "Using vague words like nice and big.", "Too much description before anything happens."],
    [{"title": "Mood Swap", "description": "Describe the same place twice, once cheerful and once spooky, and underline the details you changed.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that where and when are clear, one mood is built through details, two or three senses are used, at least one noun group and strong verb appear, the mood is not named, and it is 4 to 6 sentences. Sorter: Spooky: shutter banging, mist along the empty path, owl's eyes. Cheerful: golden sunshine, children laughing, warm bread.",
)

A5L2 = build(
    "s2-eng-a5-l2-show-dont-tell", "Show, Don't Tell",
    "Learn how to turn flat statements into writing that lets the reader see and feel.",
    "Writing: show, don't tell",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01"],
    {"EN2-CWT-01": "Primary. Rewrites telling sentences as showing sentences using action, speech, senses and detail.",
     "EN2-RECOM-01": "Identifies telling and showing in a text.",
     "EN2-VOCAB-01": "Learns the terms telling, showing, body language, strong verb and figurative."},
    "We are learning how to show feelings and ideas through details instead of just telling the reader.",
    ["I can tell a telling sentence from a showing sentence.", "I can show a feeling through body language.", "I can show a feeling through action and speech.", "I can add a sensory detail.", "I can rewrite a paragraph by showing."],
    ["telling", "showing", "body language", "strong verb", "detail"],
    ["Paper or notebook", "Pencil", "A story you are reading (your parent will help you choose)"],
    "Child has met look, say, do, feel in the characters lesson. Show, don't tell is taught here from the beginning.",
    "TELLING says what is true: 'Zara was nervous.' It is quick, but the reader feels nothing.\n\nSHOWING gives the reader details so they work it out: 'Zara's hands shook as she gripped the edge of the stage.' Now the reader sees it and feels it.\n\nShowing does not mean using more words everywhere. Use it for the moments that matter most: big feelings, key traits and important places.",
    [
        _step("1", "Telling and showing",
              "Compare these two sentences.\n\nTelling: The boy was angry.\nShowing: The boy slammed his book shut and stormed out.\n\nThe second sentence never uses the word angry, but we know. Writers trust the reader to work it out.\n\nA good test: if you can write 'because' and a feeling word in your head, ask yourself what the body, face, voice or actions would be doing.\n\nTelling is not wrong. Short telling sentences are useful for facts. But key moments need showing.",
              "Tell: She was tired. Show: Her eyelids drooped and she dragged her feet up the stairs.",
              "Showing uses details instead of naming the feeling.",
              ("Which sentence shows?", ["He slammed the door and stomped away.", "He was angry.", "Anger is bad."], 0, "Slamming and stomping show anger.")),
        _step("2", "Body language",
              "BODY LANGUAGE is what the body does when a person feels something. It is the easiest way to show.\n\nNervous: hands shaking, biting a lip, shifting from foot to foot.\nHappy: grinning, bouncing, eyes sparkling.\nSad: slumped shoulders, tears, staring at the floor.\nScared: heart pounding, frozen, wide eyes.\nAngry: clenched fists, scowl, stomping.\n\nAvoid overusing the same ones. Sweaty palms and thumping hearts get tired quickly. Look for fresh details of your own.",
              "Excited: Mia bounced on her toes and could not stop smiling.",
              "Body details show feelings.",
              ("Which shows sadness?", ["Slumped shoulders and staring at the floor", "Bouncing and grinning", "Clenched fists"], 0, "Slumped shoulders show sadness.")),
        _step("3", "Actions and speech",
              "You can also show a feeling through what a character DOES and SAYS.\n\nAction: 'He kept checking the clock every few seconds.' We know he is impatient.\n\nSpeech: ''I'm fine,' she said, in a voice barely above a whisper.' We know she is not fine.\n\nChoose speech verbs and actions that match the feeling. The reader reads the clue and decides.\n\nOne action or one line of speech is often enough. You do not need to explain it afterwards.",
              "Do not write: 'He was impatient because he kept checking the clock.' Just write the checking.",
              "Let actions and speech carry the feeling.",
              ("Do you need to explain the clue afterwards?", ["No, trust the reader", "Yes, always", "Only for adults"], 0, "Let the reader work it out.")),
        _step("4", "Senses and figurative touches",
              "Senses can show feelings too. A nervous child might notice every tiny sound. A sad child might not notice the sunshine at all.\n\nYou can add a comparison to make a detail vivid: 'Her stomach felt like a washing machine.' Use these sparingly, and make them fresh and sensible.\n\nChoose strong verbs. 'Gulped', 'trembled', 'snatched' and 'hunched' show much more than 'was' or 'felt'.\n\nRead your sentence and ask: could a reader see a film of this?",
              "Telling: He felt scared. Showing: He gulped, and every creak of the floor made him flinch.",
              "Senses and strong verbs help you show.",
              ("Which verb shows more?", ["trembled", "was", "felt"], 0, "Trembled gives an image.")),
        _step("5", "Rewrite a paragraph",
              "Take this telling paragraph.\n\n'Sam was nervous. He was in a dark room. He was scared of the noise.'\n\nRewrite it by showing.\n\n1. Pick the feeling you want to show.\n2. Add one body clue.\n3. Add one sense (sound or touch).\n4. Add one action.\n5. Use at least one strong verb.\n6. Remove the feeling words if you can.\n\nModel: Sam pressed his back against the wall. Somewhere above, a floorboard creaked. He held his breath and gripped the torch with both hands.",
              "Notice: no sentence says nervous or scared, but the reader knows.",
              "Choose the feeling, add clues, remove the label.",
              ("What do you remove when you show?", ["The feeling word", "All the verbs", "The characters"], 0, "The feeling word can be replaced by clues.")),
    ],
    "Model answers. Telling: The boy was angry. Showing: The boy slammed his book shut and stormed out. Body language for scared: heart pounding, frozen, wide eyes. Rewrite: Sam pressed his back against the wall. Somewhere above, a floorboard creaked. He held his breath and gripped the torch with both hands.",
    "1) Sort six sentences into telling or showing. 2) Write one body clue for each of five feelings. 3) Write one action and one line of speech that show impatience. 4) Rewrite five telling sentences as showing sentences. 5) Rewrite the Sam paragraph in your own words. 6) Rewrite a telling paragraph from your own story.",
    "Rewrite a 3 sentence telling paragraph as a 5 to 6 sentence showing paragraph without using the feeling word. Upload a photo of your writing.",
    CHECK,
    "Did I remove the feeling word? Did I use a body clue? Did I add an action or a sense? Did I use a strong verb? Does the reader still know the feeling? Is it 5 to 6 sentences?",
    [
        _q("Which is telling?", ["She was nervous.", "Her hands shook.", "She bit her lip."], 0, "It names the feeling."),
        _q("Which is showing?", ["He slammed the door.", "He was cross.", "He felt cross."], 0, "The action shows anger."),
        _q("Body language is...", ["what the body does when we feel something", "a foreign language", "a spelling rule"], 0, "Body language shows feelings."),
        _q("Which verb shows more?", ["flinched", "felt", "was"], 0, "Flinched creates an image."),
        _q("Should you explain every clue?", ["No", "Yes", "Only in the title"], 0, "Trust the reader."),
        _q("When should you use showing most?", ["For key moments", "For every sentence", "Never"], 0, "Show the moments that matter."),
        _q("Which shows a sad feeling?", ["Her shoulders slumped as she stared at the floor.", "She was sad.", "Sadness is a feeling."], 0, "The details show sadness."),
    ],
    "Upload a photo of your showing paragraph.",
    "Choose a paragraph from a book of your choice and underline one place where the writer shows a feeling instead of naming it.",
    [("telling", "Naming a feeling or fact directly."), ("showing", "Using details so the reader works out the feeling."), ("body language", "What the body does when a person feels something."), ("strong verb", "A precise verb that gives a clear picture."), ("detail", "A small piece of information that adds to a picture.")],
    [],
    _sort("Telling or showing", "Is each sentence telling or showing? Tap a group, then Check.",
          ["Telling", "Showing"],
          [("Zara was nervous.", 0), ("The cat was hungry.", 0), ("He felt happy.", 0), ("Her hands shook as she gripped the stage.", 1), ("The cat circled the empty bowl and howled.", 1), ("He grinned and bounced on his toes.", 1)]),
    [
        _wc("Naming a feeling directly is ___.", ["telling", "showing", "rhyming"], 0, "Telling names it."),
        _wc("Using details so the reader works it out is ___.", ["showing", "telling", "copying"], 0, "Showing uses details."),
        _wc("What the body does to show a feeling is ___ language.", ["body", "book", "blue"], 0, "Body language."),
        _wc("Which is spelt correctly?", ["nervous", "nervus", "nervious"], 0, "Nervous ends -ous."),
        _wc("Which is spelt correctly?", ["trembled", "trembeled", "tremled"], 0, "Trembled ends -bled."),
    ],
    [
        {"key": "body", "label": "Body clues", "hint": "One body clue for each of five feelings."},
        {"key": "rewrite", "label": "Five rewrites", "hint": "Five telling sentences made showing."},
        {"key": "paragraph", "label": "Showing paragraph", "hint": "5 to 6 sentences without the feeling word."},
    ],
    ["Using the feeling word anyway.", "Using the same body clue every time.", "Showing everything, so the story drags.", "Explaining the clue afterwards.", "Using weak verbs like was and felt."],
    [{"title": "Feeling Detective", "description": "Write five showing sentences for five feelings and ask someone at home to guess each one.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the feeling word is removed, at least one body clue, action or sense is used, a strong verb appears, the feeling is still clear, and the paragraph is 5 to 6 sentences. Sorter: Telling: Zara was nervous; The cat was hungry; He felt happy. Showing: Her hands shook; The cat circled the empty bowl; He grinned and bounced.",
)

A5L3 = build(
    "s2-eng-a5-l3-adverbs-and-adverbial-phrases", "Adverbs and Adverbial Phrases",
    "Learn how adverbs and adverbial phrases tell us how, when, where and why.",
    "Language: adverbs",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Uses adverbs and adverbial phrases to add detail about manner, time, place and reason.",
     "EN2-VOCAB-01": "Learns the terms adverb, adverbial phrase, manner, time, place and reason.",
     "EN2-RECOM-01": "Identifies adverbs and adverbial phrases in a text."},
    "We are learning to use adverbs and adverbial phrases to give more detail about verbs.",
    ["I can say what an adverb does.", "I can find adverbs of manner, time and place.", "I can build an adverbial phrase.", "I can use a comma after an opening phrase.", "I can add adverbs to my own sentences."],
    ["adverb", "adverbial phrase", "manner", "time", "place", "reason"],
    ["Paper or notebook", "Pencil", "A paragraph from a story you have read"],
    "Child knows what a verb is from the verb lesson. Adverbs and adverbial phrases are taught from the beginning.",
    "An ADVERB is a word that tells us more about a verb. It answers questions such as how, when, where or how often something happens.\n\n'She walked quietly.' Quietly tells us how she walked.\n\nAn ADVERBIAL PHRASE is a group of words that does the same job. 'She walked with great care.' With great care tells us how.\n\nAdverbs and phrases make sentences more precise, and they let you vary where sentences begin.",
    [
        _step("1", "What adverbs do",
              "Adverbs add detail to verbs. Find the verb first, then ask a question about it.\n\n'The dog barked loudly.' Barked how? Loudly.\n'We will leave soon.' Leave when? Soon.\n'He looked outside.' Looked where? Outside.\n\nMany adverbs of manner end in -ly: slowly, carefully, bravely. But not all do. Fast, hard, well and never are adverbs too.\n\nAdverbs can also change adjectives or other adverbs, such as 'very tall' and 'really quickly'.",
              "Find the adverb: The wind howled fiercely. Fiercely.",
              "Adverbs tell how, when, where or how often.",
              ("Which word is an adverb?", ["slowly", "slow", "slower"], 0, "Slowly tells how an action happens.")),
        _step("2", "Manner, time and place",
              "Three types are the most useful.\n\nMANNER tells how: gently, eagerly, quickly, well.\nTIME tells when or how often: yesterday, soon, always, never, suddenly.\nPLACE tells where: here, there, outside, upstairs, nearby.\n\nWhen you write, check what your sentence is missing. 'The bird flew.' Add manner: 'The bird flew gracefully.' Add place: 'The bird flew overhead.' Add time: 'Suddenly, the bird flew.'\n\nDo not use too many. One good adverb is better than three.",
              "Manner: carefully. Time: tomorrow. Place: inside.",
              "Manner, time and place.",
              ("Which tells when?", ["yesterday", "gently", "upstairs"], 0, "Yesterday is a time adverb.")),
        _step("3", "Adverbial phrases",
              "An adverbial phrase is a group of words that does the job of an adverb.\n\nManner: with a trembling hand, in a hurry, as quietly as a mouse.\nTime: after the storm, at midnight, for three hours.\nPlace: behind the old shed, in the dark cave, across the river.\nReason: because of the fog, to find food.\n\n'After the storm, the farmers repaired the fence.' After the storm tells when.\n'Behind the shed, a small light flickered.' Behind the shed tells where.\n\nPhrases let you add more detail than a single word.",
              "Find the phrase: She crept across the creaking floor. Across the creaking floor (place).",
              "A phrase can do the job of an adverb.",
              ("Which is an adverbial phrase of place?", ["behind the old shed", "quickly", "yesterday"], 0, "It tells where.")),
        _step("4", "Moving adverbials and commas",
              "Adverbs and phrases can move. This helps you vary how your sentences begin.\n\nEnd: 'The wolf crept through the trees.'\nStart: 'Through the trees, the wolf crept.'\nStart: 'Silently, the wolf crept.'\n\nWhen an adverbial begins a sentence, put a COMMA after it, especially when it is more than one word.\n\n'At dawn, the birds began to sing.'\n'Without a sound, she slipped out.'\n\nDo not begin every sentence the same way. Mix your starts to make your writing flow.",
              "Same idea, three ways: The rain stopped at noon. At noon, the rain stopped. Suddenly, the rain stopped.",
              "Move the adverbial and add a comma after it at the start.",
              ("What follows an opening adverbial?", ["A comma", "A full stop", "A question mark"], 0, "Use a comma after an opening adverbial.")),
        _step("5", "Use them in your writing",
              "Now improve a short narrative paragraph.\n\n1. Write three short plain sentences about a character in a place.\n2. Add one adverb of manner to one sentence.\n3. Add one adverbial phrase of place to another.\n4. Start one sentence with an adverbial of time and add a comma.\n5. Underline each adverb and adverbial in a different colour.\n6. Read it aloud for flow.\n\nModel: Pip stood by the river. He hesitated. Pip stood by the river. After a long pause, he stepped carefully onto the first stone.",
              "Check: the comma comes after 'After a long pause'.",
              "Add detail, vary starts, add commas.",
              ("How many adverbials must a sentence have?", ["As many as it needs, but not too many", "Always ten", "None"], 0, "Use them to add useful detail.")),
    ],
    "Model answers. Adverb: a word that tells more about a verb. Manner: quietly, bravely. Time: soon, never, yesterday. Place: here, outside, nearby. Phrases: with a trembling hand (manner); after the storm (time); behind the old shed (place); because of the fog (reason). Example: After a long pause, he stepped carefully onto the first stone.",
    "1) Find the adverb in six sentences. 2) Sort ten adverbs into manner, time and place. 3) Add an adverb to five plain sentences. 4) Write one adverbial phrase of time, place and manner. 5) Move an adverbial to the start of three sentences and add commas. 6) Write a five-sentence paragraph with two adverbs and two adverbial phrases.",
    "Write a five-sentence narrative paragraph with at least two adverbs and two adverbial phrases, with a comma after each opening adverbial. Upload a photo of your writing.",
    CHECK,
    "Did I use at least two adverbs? Did I use at least two adverbial phrases? Did I add a comma after each opening adverbial? Did I start sentences in different ways? Did I underline them? Is it five sentences?",
    [
        _q("An adverb tells us more about a...", ["verb", "title", "full stop"], 0, "Adverbs add detail to verbs."),
        _q("Which is an adverb of manner?", ["carefully", "tomorrow", "upstairs"], 0, "It tells how."),
        _q("Which is an adverb of time?", ["suddenly", "quietly", "outside"], 0, "It tells when."),
        _q("Which is an adverb of place?", ["nearby", "slowly", "soon"], 0, "It tells where."),
        _q("Which is an adverbial phrase?", ["across the river", "quickly", "jumped"], 0, "It is a group of words that tells where."),
        _q("What follows an opening adverbial?", ["a comma", "a colon", "nothing"], 0, "Use a comma."),
        _q("Do all adverbs end in -ly?", ["No", "Yes", "Only in stories"], 0, "Fast, well and never are adverbs."),
    ],
    "Upload a photo of your paragraph with adverbs underlined.",
    "Pick a page from a book of your choice and find five adverbs or adverbial phrases. Say whether each shows how, when or where.",
    [("adverb", "A word that tells more about a verb."), ("adverbial phrase", "A group of words that does the job of an adverb."), ("manner", "How something happens."), ("time", "When or how often something happens."), ("place", "Where something happens."), ("reason", "Why something happens.")],
    [],
    _sort("Adverb sorter", "Does each word or phrase tell how, when or where? Tap a group, then Check.",
          ["How", "When", "Where"],
          [("gently", 0), ("with great care", 0), ("yesterday", 1), ("after the storm", 1), ("upstairs", 2), ("behind the shed", 2)]),
    [
        _wc("A word that tells more about a verb is an ___.", ["adverb", "article", "adjective"], 0, "Adverbs add detail to verbs."),
        _wc("A group of words doing the job of an adverb is an ___ phrase.", ["adverbial", "alphabetical", "abstract"], 0, "Adverbial phrase."),
        _wc("After an opening adverbial, use a ___.", ["comma", "colon", "dash"], 0, "Comma after an opening adverbial."),
        _wc("Which is spelt correctly?", ["suddenly", "sudenly", "suddenley"], 0, "Suddenly has dd."),
        _wc("Which is spelt correctly?", ["carefully", "carefuly", "carefulley"], 0, "Carefully is careful plus ly."),
    ],
    [
        {"key": "added", "label": "Adverbs added", "hint": "Five plain sentences improved."},
        {"key": "phrases", "label": "Adverbial phrases", "hint": "One each of time, place and manner."},
        {"key": "paragraph", "label": "Paragraph", "hint": "Five sentences with two adverbs and two phrases."},
    ],
    ["Forgetting the comma after an opening adverbial.", "Using too many adverbs.", "Starting every sentence the same way.", "Thinking all adverbs end in -ly.", "Using adverbs instead of stronger verbs."],
    [{"title": "Sentence Stretch", "description": "Take five plain sentences and expand each with an adverb and an adverbial phrase.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that at least two adverbs and two adverbial phrases are used, commas follow opening adverbials, sentence starts vary, and the paragraph is five sentences. Sorter: How: gently, with great care. When: yesterday, after the storm. Where: upstairs, behind the shed.",
)

A5L4 = build(
    "s2-eng-a5-l4-synonyms-for-said-and-walked", "Vocabulary: Synonyms for Said and Walked",
    "Build a bank of precise words to replace overused ones in your writing.",
    "Vocabulary: synonyms",
    ["EN2-VOCAB-01", "EN2-CWT-01", "EN2-SPELL-01"],
    {"EN2-VOCAB-01": "Primary. Learns synonyms and shades of meaning for said and walked.",
     "EN2-CWT-01": "Uses precise verbs to improve narrative writing.",
     "EN2-SPELL-01": "Spells a bank of new vocabulary accurately."},
    "We are learning to choose precise synonyms for said and walked so our writing is clear and interesting.",
    ["I can say what a synonym is.", "I can name five synonyms for said.", "I can name five synonyms for walked.", "I can choose a synonym that fits the mood.", "I can spell my new words."],
    ["synonym", "shades of meaning", "precise", "thesaurus", "overused"],
    ["Paper or notebook", "Pencil", "A thesaurus or online thesaurus (your parent will help)"],
    "Child has met strong verbs in the verbs lesson. Synonyms and shades of meaning are taught from the beginning.",
    "A SYNONYM is a word with a similar meaning to another word. 'Big' and 'huge' are synonyms.\n\nSynonyms rarely mean exactly the same. They have SHADES OF MEANING. 'Tiptoed' and 'stomped' both mean walked, but they tell us very different things.\n\nWriters often use said and walked again and again. They are fine sometimes, but a precise synonym shows the character's feeling and the mood.",
    [
        _step("1", "What is a synonym?",
              "A synonym is a word that means nearly the same as another word.\n\nhappy: glad, cheerful, delighted.\nsmall: tiny, little, miniature.\nlook: glance, stare, peer.\n\nTo find synonyms, ask: what other word could I use here? You can also use a THESAURUS, a book or website that lists synonyms.\n\nBut be careful. Check the new word fits the sentence and means what you want. Always say the sentence aloud.",
              "Said: replied, announced, whispered. Walked: strolled, marched, crept.",
              "Synonyms have similar meanings.",
              ("A synonym is a word that...", ["has a similar meaning", "has the opposite meaning", "sounds the same"], 0, "Synonyms mean nearly the same.")),
        _step("2", "Synonyms for said",
              "Said is not a bad word. But it tells us nothing about how the words were spoken. Here are groups by feeling.\n\nQuiet: whispered, murmured, muttered, mumbled.\nLoud: shouted, yelled, bellowed, roared, called.\nAngry: snapped, growled, snarled, barked.\nHappy: laughed, giggled, cheered, sang.\nSad or scared: sobbed, stammered, whimpered, pleaded.\nNeutral: replied, answered, asked, explained, announced.\n\nChoose the verb that matches the feeling. 'I hate you,' she snarled. This tells us the tone.\n\nDo not overdo it. A plain said is still useful when the speech is the important part.",
              "'Get out!' he roared. 'Please,' she whimpered.",
              "Match the speech verb to the feeling.",
              ("Which shows an angry voice?", ["snapped", "whispered", "giggled"], 0, "Snapped is sharp and angry.")),
        _step("3", "Synonyms for walked",
              "Walked tells us the character moved on foot, but not how. Choose a verb that shows how they move.\n\nSlow: strolled, wandered, ambled, trudged, plodded, dawdled.\nFast: marched, hurried, raced, dashed, strode.\nQuiet: crept, tiptoed, sneaked, slipped.\nHeavy or tired: stomped, trudged, shuffled, staggered.\nProud or happy: strutted, skipped, paraded.\n\nEach verb creates a different picture. 'He trudged up the hill' makes us feel he is tired. 'He skipped up the hill' makes us feel he is joyful.",
              "Same hill, two moods: She trudged up the hill. She skipped up the hill.",
              "Walking verbs show how a character moves and feels.",
              ("Which means to walk quietly?", ["tiptoed", "stomped", "marched"], 0, "Tiptoed is quiet.")),
        _step("4", "Shades of meaning",
              "Words in a group are not identical. Put them on a scale from weak to strong.\n\nSpoke loudly: called, shouted, yelled, bellowed.\nMoved slowly: strolled, ambled, trudged, crawled.\nAngry: annoyed, cross, furious, enraged.\n\nThe words get stronger along the line. Choose the one that fits the moment. Using the strongest word every time wears it out.\n\nA good way to check: could someone act it out? You can act out 'tiptoed' and 'stomped', and they look very different.",
              "Scale: cross, angry, furious. A late bus makes you cross. A broken toy might make you furious.",
              "Order synonyms from weak to strong.",
              ("Which is the strongest?", ["furious", "cross", "annoyed"], 0, "Furious is the strongest.")),
        _step("5", "Use and spell your words",
              "Now build your own word bank.\n\n1. Choose five synonyms for said and five for walked.\n2. Write a short meaning for each in your own words.\n3. Look, say, cover, write, check each spelling.\n4. Write five sentences, using one new word in each.\n5. Read your sentences aloud. Does each word fit?\n6. Circle your two favourites.\n\nWatch the spelling of tricky words such as: whispered, murmured, strolled, bellowed, tiptoed, staggered.",
              "Example: 'Quiet!' the teacher announced. The boy tiptoed past the sleeping dog.",
              "Pick, define, spell, use.",
              ("How should you check a spelling?", ["Look, say, cover, write, check", "Guess", "Skip it"], 0, "This method helps you remember.")),
    ],
    "Model answers. Synonym: a word with a similar meaning. Said groups: whispered (quiet), bellowed (loud), snapped (angry), sobbed (sad). Walked groups: strolled (slow), marched (fast), crept (quiet), stomped (heavy). Scale for angry: annoyed, cross, angry, furious. Example sentences: 'Quiet!' the teacher announced. The boy tiptoed past the sleeping dog.",
    "1) Match five synonyms to said and five to walked. 2) Sort ten words into quiet, loud or angry. 3) Order three scales from weak to strong. 4) Rewrite five sentences replacing said or walked. 5) Practise the spelling of six tricky words. 6) Write five sentences using five new words.",
    "Write five sentences using five new synonyms (at least two for said and two for walked), and circle your favourite. Upload a photo of your writing.",
    CHECK,
    "Did I use five new words? Did each word fit the feeling? Did I use at least two for said and two for walked? Did I spell them correctly? Did I read the sentences aloud?",
    [
        _q("A synonym is...", ["a word with a similar meaning", "an opposite", "a rhyme"], 0, "Synonyms mean nearly the same."),
        _q("Which means said loudly?", ["bellowed", "murmured", "mumbled"], 0, "Bellowed is loud."),
        _q("Which means walked quietly?", ["crept", "stomped", "marched"], 0, "Crept is quiet."),
        _q("Which means walked tiredly?", ["trudged", "strutted", "skipped"], 0, "Trudged is slow and heavy."),
        _q("A book of synonyms is a...", ["thesaurus", "dictionary of rhymes", "atlas"], 0, "A thesaurus lists synonyms."),
        _q("Which is the strongest?", ["furious", "annoyed", "cross"], 0, "Furious is the strongest."),
        _q("Should you always use the strongest word?", ["No", "Yes", "Only in titles"], 0, "Choose the word that fits."),
    ],
    "Upload a photo of your five sentences.",
    "Start a personal word bank page of synonyms for another overused word, such as nice, big or went, and add to it each week.",
    [("synonym", "A word with a similar meaning to another word."), ("shades of meaning", "Small differences in meaning between similar words."), ("precise", "Exact and clear."), ("thesaurus", "A book or website that lists synonyms."), ("overused", "Used too often.")],
    [],
    _sort("Speech verb sorter", "Which feeling does each word show? Tap a group, then Check.",
          ["Quiet", "Loud", "Angry"],
          [("whispered", 0), ("murmured", 0), ("bellowed", 1), ("yelled", 1), ("snapped", 2), ("growled", 2)]),
    [
        _wc("A word with a similar meaning is a ___.", ["synonym", "symbol", "syllable"], 0, "Synonym."),
        _wc("A book that lists synonyms is a ___.", ["thesaurus", "timetable", "telephone"], 0, "Thesaurus."),
        _wc("Which is spelt correctly?", ["whispered", "wispered", "whisperd"], 0, "Whispered starts wh."),
        _wc("Which is spelt correctly?", ["bellowed", "belowed", "bellowd"], 0, "Bellowed has ll."),
        _wc("Which is spelt correctly?", ["tiptoed", "tiptowed", "tipptoed"], 0, "Tiptoed is tiptoe plus d."),
    ],
    [
        {"key": "said", "label": "Said words", "hint": "Five synonyms with meanings."},
        {"key": "walked", "label": "Walked words", "hint": "Five synonyms with meanings."},
        {"key": "sentences", "label": "Five sentences", "hint": "One new word in each."},
    ],
    ["Using a synonym that does not fit.", "Using the strongest word every time.", "Misspelling tricky words like whispered.", "Never using plain said.", "Copying from a thesaurus without checking the meaning."],
    [{"title": "Word Bank", "description": "Make a poster of synonyms for said and walked, grouped by feeling, and use it for your next story.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that five synonyms are used, each fits the feeling, at least two are for said and two for walked, spelling is correct, and meanings are in the child's own words. Sorter: Quiet: whispered, murmured. Loud: bellowed, yelled. Angry: snapped, growled.",
)

LESSONS = [A5L1, A5L2, A5L3, A5L4]
