"""Stage 2 English, Week 1 of the program (four 60-minute lessons).
Outcome codes come from nsw_outcomes_stage2_verified.py.
This module also raises LESSON_LIBRARY_VERSION to 14 so the library re-seeds; fold that into lesson_library.py when convenient."""
import sys


def _q(q, opts, idx, why):
    return {"question": q, "type": "multiple_choice", "options": opts, "correct_index": idx, "explanation": why}


def _step(icon, title, explain, example, notice, chk):
    q, opts, idx, why = chk
    return {"icon": icon, "title": title, "explain": explain, "example": example, "notice": notice,
            "check": {"question": q, "options": opts, "correct_index": idx, "explanation": why}}


def _video(title, vid, prompt, offline, chk):
    q, opts, idx, why = chk
    return {"type": "video", "title": title, "url": f"https://www.youtube.com/watch?v={vid}",
            "embed_url": f"https://www.youtube-nocookie.com/embed/{vid}", "prompt": prompt,
            "offline_alternative": offline,
            "check": {"question": q, "options": opts, "correct_index": idx, "explanation": why}}


def _article(title, url):
    return {"type": "article", "title": title, "url": url}


def _sort(title, instr, buckets, items):
    return {"title": title, "instructions": instr, "buckets": buckets, "items": [{"text": t, "answer": a} for t, a in items]}


def _wc(q, opts, idx, why):
    return {"question": q, "options": opts, "correct_index": idx, "explanation": why}


def build(key, title, mission, subject, codes, notes, intention, criteria, vocab, materials, prior,
          teaching, steps, worked, guided, independent, response, selfcheck, quiz, evidence, extension, cards,
          resources, sort_activity, word_challenges, planner, mistakes, challenges, answer_key):
    lesson = {
        "seed_key": key, "library": True, "stage": "S2", "year_level": "Stage 2", "learning_area": "English",
        "subject": subject, "title": title, "child_mission": mission, "duration_minutes": 60, "pass_mark": 0.9,
        "outcome_codes": codes, "outcome_notes": notes, "learning_intention": intention,
        "success_criteria": criteria + ["I can score 90% or more on the Quest check."],
        "key_vocabulary": vocab, "materials": materials, "prior_knowledge": prior,
        "explicit_teaching": teaching + "\n\nCommon mistakes to watch for:\n" + "\n".join("- " + m for m in mistakes),
        "teach_steps": steps, "worked_example": worked, "guided_practice": guided, "independent_task": independent,
        "response_prompt": response, "self_check": selfcheck,
        "accessibility_notes": "Allow dictation or typing. Break the written task into two sittings. Reduce the length by a third if needed. Pause the videos as often as you like.",
        "interactive_activities": [{"type": "flip_cards", "title": "Quest Codex: key terms",
                                    "cards": [{"front": f, "back": b} for f, b in cards]}],
        "sort_activity": sort_activity, "word_challenges": word_challenges,
        "steps": [
            {"title": "Step 1: Accept the quest", "detail": "Read your mission and the learning goals.", "duration_minutes": 5},
            {"title": "Step 2: Learn the map", "detail": "Six short lessons, each with a full explanation, examples and a quick try.", "duration_minutes": 20},
            {"title": "Step 3: Practise the craft", "detail": "Watch the videos and answer the checks, flip the key-term cards, then complete the sorting and word challenges.", "duration_minutes": 10},
            {"title": "Step 4: Apply it", "detail": "Work through the guided practice, plan, then complete the independent task.", "duration_minutes": 15},
            {"title": "Step 5: Quest check", "detail": "Answer the 10-question check. You need 9 out of 10.", "duration_minutes": 5},
            {"title": "Step 6: Hand it in", "detail": "Check your work against the success criteria and submit your evidence.", "duration_minutes": 5},
        ],
        "resources": resources, "quiz": quiz,
        "reflection_prompts": ["What was the trickiest part today?", "What will you do differently next time?"],
        "evidence_instructions": evidence,
        "parent_notes": "Practice lesson only. Quiz scores are formative; competency is decided by the fortnightly mini exam. Check the written task against the success criteria. Video check questions test the main idea so they can be answered if a video is unavailable.\n\nAnswer key for the guided practice:\n" + answer_key + "\n\nVerify the outcome mapping against the NESA English K-10 syllabus.",
        "source_note": "Outcome codes from the NSW English K-10 Syllabus (NESA 2022), Stage 2. Parent to verify alignment on curriculum.nsw.edu.au.",
        "offline_alternative": "Complete all written tasks on paper and read the questions aloud. Videos can be skipped if the worked example is read aloud.",
        "extension": extension, "follow_up_challenges": challenges,
    }
    if planner:
        lesson["planner_fields"] = planner
    return lesson


L1 = build(
    "s2-eng-w01-l1-spelling-strategies", "Spelling Detective: Four Strategies",
    "A tricky word has escaped the page! Learn the detective's toolkit, then catch ten real words and prove how you did it.",
    "Spelling: select, apply and describe strategies",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-HANDW-01"],
    {"EN2-SPELL-01": "Primary. Learns, applies and describes four strategies (quiz, sort and word log).",
     "EN2-VOCAB-01": "Uses prefixes, suffixes and base words to work out word meanings.",
     "EN2-HANDW-01": "Copies the word log in neat joined handwriting."},
    "We are learning to choose and use spelling strategies to spell tricky words.",
    ["I can break a word into sounds and into syllables.", "I can find the base word, prefix and suffix in a word.",
     "I can add a suffix and apply the drop-e, doubling and y-to-i rules.", "I can use Look, Say, Cover, Write, Check and a memory trick for tricky words.",
     "I can describe which strategy I used and why."],
    ["syllable", "phoneme", "digraph", "base word", "prefix", "suffix", "strategy", "mnemonic"],
    ["Paper or notebook", "Pencil", "Your own writing for tricky words"],
    "Child can write simple sentences and knows the alphabet sounds.",
    "English spelling is not random. It follows three layers: sounds (how a word is said), word parts (what a word means and is built from) and history (why some words look odd). Good spellers use all three, and choose the one that fits.\n\nThe toolkit: (1) sound it out for regular words, (2) split into syllables for long words, (3) use word parts for words built from a base, prefix and suffix, (4) Look, Say, Cover, Write, Check plus a memory trick for words that break the rules.\n\nSpelling is also a thinking skill. When you can say 'I used syllables because the word is long' you are no longer guessing, you are choosing a tool.",
    [
        _step("1", "Sound it out: phonemes and digraphs", "A phoneme is one sound. Words are built from phonemes, and we write each one with a letter or a group of letters. A digraph is two letters that make one sound: sh (ship), ch (chop), th (thin), ng (ring), ck (duck), ph (phone).\n\nMany sounds can be spelled more than one way. The long 'a' sound can be a_e (cake), ai (rain) or ay (play). The long 'e' can be ee (tree), ea (leaf) or y (happy). When the sound has options, try each on paper and ask, 'Which one looks right?'.\n\nTry this: say the word slowly, hold up a finger for each sound, then write one letter group per finger. The number of sounds is not always the number of letters.",
              "ship: sh - i - p (3 sounds, 4 letters). chimp: ch - i - m - p (4 sounds). thing: th - i - ng (3 sounds, 5 letters). train: t - r - ai - n (4 sounds).",
              "Sound it out works best for words that are spelt the way they sound. It fails for words like 'said' or 'friend'.",
              ("How many sounds are in 'ship'?", ["2", "3", "4"], 1, "sh - i - p is three sounds.")),
        _step("2", "Syllables and the double letter rule", "A syllable is one beat in a word, and every syllable has a vowel sound. Say the word and tap your chin: it drops once for each syllable. Then spell one syllable at a time.\n\nWatch for double consonants in the middle. When a short vowel is followed by two consonants, the syllable break often sits between them: rab-bit, rib-bon, lad-der, mit-ten, sum-mer. If you hear a short vowel and then another syllable, try a double letter.\n\nCompound words are two whole words joined together: sun + shine = sunshine, foot + ball = football. Spell each part, then join them.",
              "fan-tas-tic (3). but-ter-fly (3). rab-bit (2, double b). sun-shine (2, compound). un-for-get-ta-ble (5).",
              "Writing one chunk at a time makes any long word manageable.",
              ("How many syllables are in 'butterfly'?", ["2", "3", "4"], 1, "but-ter-fly has three beats.")),
        _step("3", "Prefixes: word parts at the front", "A base word is the main part of a word and can often stand alone. A prefix is added to the front and changes the meaning, but it never changes how the base word is spelt.\n\nuseful prefixes: un- (not, opposite): unhappy, unlock. re- (again): replay, rewrite. dis- (not, apart): disagree, disappear. mis- (wrongly): misread, mistake. pre- (before): preview, preheat. Notice that you simply add the prefix and keep every letter: dis + appear = disappear (two p's), mis + spell = misspell (two s's).\n\nKnowing prefixes helps you with meaning too. If you know un- means not, you can work out what 'unbreakable' means even if you have never seen it.",
              "un + happy = unhappy. re + build = rebuild. dis + appear = disappear. mis + spell = misspell. pre + view = preview.",
              "When the prefix ends in the same letter that the base word starts with, you get a double letter: mis + spell.",
              ("What is the base word in 'replaying'?", ["re", "play", "ing"], 1, "re + play + ing: play is the base word.")),
        _step("4", "Suffixes and the three adding rules", "A suffix is added to the end of a base word. Common suffixes: -ing and -ed (tense), -ful (full of), -less (without), -ly (in a way), -er (one who), -ness (state of).\n\nSometimes you must change the base word first. Rule 1, drop the e: if a base word ends in a silent e and the suffix starts with a vowel, drop the e. hope + ing = hoping, make + ing = making. Rule 2, double the letter: if a one-syllable word has one short vowel and one final consonant, double the consonant before -ing or -ed. hop + ing = hopping, sit + ing = sitting. Rule 3, change y to i: if a word ends in consonant + y, change the y to i before most suffixes. happy + ness = happiness, carry + ed = carried.\n\nIf the suffix starts with a consonant (-ful, -less, -ly), you usually leave the base word alone: hope + ful = hopeful, care + less = careless.",
              "hope + ing = hoping (drop e). hop + ing = hopping (double p). happy + ness = happiness (y to i). careful, careless (no change).",
              "Before adding a suffix ask: does it start with a vowel? Does the word end in e, a single consonant after a short vowel, or consonant + y?",
              ("What is the correct spelling of hope + ing?", ["hopeing", "hoping", "hopping"], 1, "Drop the silent e: hoping. Hopping is from hop.")),
        _step("5", "Look, Say, Cover, Write, Check, and memory tricks", "Some words break the rules, such as said, friend, because and people. The strategy for these is to learn the shape of the word. Look at the word and find the tricky part. Say it out loud, sometimes in a silly way (Wed-nes-day). Cover it. Write it from memory. Check it, and if it is wrong, fix only the wrong part and try again.\n\nA memory trick, also called a mnemonic, makes the tricky part stick. Because: Big Elephants Can Always Understand Small Elephants. Friend: you are a friend to the end. Necessary: one collar and two sleeves (one c, two s). Piece: a piece of pie.\n\nPractise a word three days in a row and it will move to long-term memory.",
              "said: s - ai - d (the tricky part is ai). friend: fr - ie - nd (the tricky part is ie). because: be + cause, with the mnemonic Big Elephants Can Always Understand Small Elephants.",
              "Circle the tricky part in colour. Your eyes will remember where the surprise is.",
              ("In Look, Say, Cover, Write, Check, what comes right after Cover?", ["Check", "Write", "Look"], 1, "You write it from memory, then check.")),
        _step("6", "Choosing the right strategy and proofreading", "A detective does not use every tool every time. Use this thinking order.\n\nFirst, is it a short regular word? Sound it out. Second, is it long? Split into syllables. Third, can you see a prefix, suffix or compound? Use the word parts and the adding rules. Fourth, does it break the rules? Use Look, Say, Cover, Write, Check and a memory trick.\n\nWhen you proofread, read your writing slowly, one word at a time, with a finger or ruler. Underline any word that does not look right, try it two ways on scrap paper, and check a dictionary or a book. Never ask 'Is this right?' without trying to fix it first.",
              "'unforgettable': long word, so syllables (un-for-get-ta-ble); prefix un-; base word forget, and the t doubles in forgettable (forget + able with a stressed final syllable). Strategies used: word parts, then syllables.",
              "Naming your strategy makes you a better speller, because you can reuse it on the next word.",
              ("Which strategy suits a tricky word like 'said'?", ["Look, Say, Cover, Write, Check", "Clap the syllables", "Guess it"], 0, "Tricky words need memory practice.")),
    ],
    "Word: unfriendly. Step 1, is it regular? No: the ie is tricky. Step 2, is it long? Yes, three syllables: un-friend-ly. Step 3, word parts: un + friend + ly. The base word is friend and the suffix -ly needs no change. Step 4, tricky part: ie in friend. I use Look, Say, Cover, Write, Check for 'friend' with the trick 'a friend to the end'. Then I add un on the front and ly on the end. Strategy log: word parts, syllables, then memory for the tricky middle.",
    "Work in your notebook. Part A, split into syllables and write the number: elephant, adventure, wonderful, understand. Part B, find prefix, base and suffix: replaying, unhappily, misspelling, carefully. Part C, add the suffix using the right rule: hope + ing, hop + ing, happy + ness, carry + ed, care + less. Part D, choose a strategy for each word and say why: said, because, favourite, beautiful. Check Part A and B against the answer key your parent has.",
    "Stage 1 (plan): choose 10 words you misspelt in recent writing, or use: because, friend, said, again, people, would, could, through, favourite, beautiful.\nStage 2 (apply): for each word write it using the best strategy and note the strategy beside it (sounds, syllables, parts or LSCWC). Circle the tricky part and add one memory trick for the three hardest.\nStage 3 (handwriting): copy your best five words in neat joined handwriting.\nStage 4 (reflect): write two sentences on which strategy you used most and why.",
    "Which strategy did you use most, and why did it work for those words?",
    "Did I write 10 words, name a strategy for each, circle the tricky part, write three memory tricks, write five in joined handwriting and explain my choice?",
    [
        _q("Which strategy breaks a word into beats?", ["Syllables", "Prefixes", "Capital letters", "Full stops"], 0, "Clapping beats finds the syllables."),
        _q("Which word contains the base word 'happy'?", ["unhappy", "hippo", "happen", "hope"], 0, "un + happy."),
        _q("How many sounds are in 'stamp'?", ["3", "4", "5"], 2, "s - t - a - m - p."),
        _q("How many syllables are in 'elephant'?", ["2", "3", "4"], 1, "el-e-phant."),
        _q("Which is spelt correctly?", ["freind", "friend", "frend"], 1, "friend has ie, then nd."),
        _q("Which is spelt correctly?", ["becuase", "because", "becaus"], 1, "because: be-cause."),
        _q("What is the suffix in 'playing'?", ["play", "ing", "pl"], 1, "A suffix goes at the end."),
        _q("What is the prefix in 'unlock'?", ["lock", "un", "ock"], 1, "A prefix goes at the front."),
        _q("Which strategy suits a tricky word like 'said'?", ["Look, Say, Cover, Write, Check", "Clap the syllables", "Guess it"], 0, "Tricky words need memory practice."),
        _q("What does 'unlock' mean?", ["to lock again", "to open a lock", "a big lock"], 1, "The prefix un- means not or the opposite."),
    ],
    "Upload a photo of your word log showing your 10 words, the strategy for each, circled tricky parts, three memory tricks and five words in joined handwriting.",
    "Choose a longer word such as 'unforgettable' and explain every strategy you could use on it.",
    [("syllable", "One beat in a word."), ("phoneme", "One sound in a word."), ("digraph", "Two letters that make one sound, like sh."),
     ("base word", "The main part of a word that can stand alone."),
     ("prefix", "A word part added to the front, like un- or re-."), ("suffix", "A word part added to the end, like -ing or -ful."),
     ("mnemonic", "A memory trick, like Big Elephants Can Always Understand Small Elephants."), ("strategy", "A method you choose to solve a problem.")],
    [
        _video("Syllables, prefixes and suffixes for kids (Kids Academy)", "Qz0LWrJDfx0",
               "Watch how to find syllables and how prefixes and suffixes change a word. Then answer the question below.",
               "Re-read steps 2, 3 and 4 and clap the syllables in five words from your book.",
               ("What does a prefix do to a word?", ["Adds to the front and can change the meaning", "Adds a full stop", "Takes letters away"], 0, "A prefix goes at the front of a base word and changes its meaning.")),
        _video("Prefixes and suffixes grammar lesson", "jujRYzE9Cxs",
               "Watch how to spot the root word, prefix and suffix. Notice how finding the base word helps you spell the rest.",
               "Find five words in your book that end in -ing or -ed and write the base word for each.",
               ("Which word is the root (base) word in 'jumping'?", ["jump", "ing", "ju"], 0, "Jump is the base word; -ing is the suffix.")),
        _video("Affixes review: prefixes and suffixes in reading and spelling", "-HFr8rT_Zd8",
               "Watch how meaningful word parts connect to meaning, and think about words you could build.",
               "Write three words for each of the prefixes un-, re- and dis-.",
               ("How can knowing word parts help you spell and read?", ["You can work out hard words from parts you know", "You never need a dictionary", "All words are short"], 0, "Word parts let you build and decode longer words.")),
    ],
    _sort("Strategy sorter", "Which strategy helps most with each word? Tap a strategy, then press Check.",
          ["Sounds", "Syllables", "Word parts", "Look-Say-Cover-Write-Check"],
          [("chimp", 0), ("strong", 0), ("trick", 0), ("fantastic", 1), ("adventure", 1), ("wonderful", 1), ("unhappy", 2), ("replaying", 2), ("careful", 2), ("misspell", 2), ("said", 3), ("because", 3), ("friend", 3), ("people", 3)]),
    [
        _wc("The prefix in 'rewrite' is ___.", ["re", "write", "rew"], 0, "Re- means again."),
        _wc("Careful means full of ___.", ["care", "fun", "fear"], 0, "The suffix -ful means full of."),
        _wc("Hopeless means ___ hope.", ["with", "without", "more"], 1, "The suffix -less means without."),
        _wc("Which word has a prefix that means 'not'?", ["unkind", "kindly", "kinder"], 0, "Un- means not."),
        _wc("Which is spelt correctly?", ["hopping (from hop)", "hoping (from hop)", "hopeing"], 0, "A short one-syllable word doubles the consonant: hop + ping."),
        _wc("happy + ness = ___", ["happiness", "happyness", "happines"], 0, "Change the y to i before the suffix."),
        _wc("Which word needs two s letters?", ["misspell", "mispell", "misspel"], 0, "mis + spell keeps every letter."),
        _wc("Which memory trick helps with 'because'?", ["Big Elephants Can Always Understand Small Elephants", "Because is easy", "Cats are small"], 0, "The first letters spell because."),
    ],
    [
        {"key": "words", "label": "My ten words", "hint": "Write the ten words you will practise."},
        {"key": "hardest", "label": "Hardest word", "hint": "Which word is the trickiest and which part is tricky?"},
        {"key": "strategy", "label": "Strategy plan", "hint": "Which strategy will you use for the hardest word and why?"},
        {"key": "trick", "label": "Memory trick", "hint": "Invent a memory trick for your hardest word."},
    ],
    ["Counting letters instead of sounds (ship has three sounds).", "Guessing a spelling instead of choosing a strategy.", "Forgetting the adding rules: hope + ing is hoping, hop + ing is hopping.", "Skipping the Check step of Look, Say, Cover, Write, Check."],
    [{"title": "Word Wall", "description": "Make a word wall of 10 tricky words with the tricky part in a different colour.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Spelling Teacher", "description": "Teach a family member one strategy using three words and ask them to spell each one.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Part A: ele-phant 3 (el-e-phant), ad-ven-ture 3, won-der-ful 3, un-der-stand 3. Part B: re + play + ing; un + happy + ly (happily, y to i); mis + spell + ing; care + ful + ly. Part C: hoping, hopping, happiness, carried, careless. Part D (suggested): said, because: LSCWC and a memory trick; favourite: syllables fav-our-ite; beautiful: syllables beau-ti-ful or beauty + ful.",
)

L2 = build(
    "s2-eng-w01-l2-sentence-builder", "Sentence Builder: Punctuation Power",
    "The Sentence Bridge has holes in it! Learn how a sentence is built, then repair broken sentences and write your own with power.",
    "Creating written texts: sentences and punctuation",
    ["EN2-CWT-01", "EN2-SPELL-01", "EN2-HANDW-01"],
    {"EN2-CWT-01": "Primary. Writes and punctuates complete sentences.",
     "EN2-SPELL-01": "Spells contractions correctly.",
     "EN2-HANDW-01": "Writes the final paragraph in legible joined handwriting."},
    "We are learning to write complete sentences and punctuate them correctly.",
    ["I can tell a complete sentence from a fragment and a run-on.", "I can choose between a statement, question, command and exclamation.",
     "I can use capital letters for names, places and days.", "I can use commas in a list and after an opening phrase.", "I can use an apostrophe in a contraction."],
    ["sentence", "fragment", "run-on", "subject", "verb", "capital letter", "proper noun", "comma", "apostrophe", "contraction"],
    ["Paper or notebook", "Pencil"], "Child can write several words in a line.",
    "A complete sentence needs two things: a subject (who or what the sentence is about) and a verb (what the subject does or is), and it must make sense on its own. Anything less is a fragment. Two sentences stuck together without punctuation is a run-on.\n\nPunctuation is a set of road signs for the reader. The capital letter says 'a sentence starts here'. The end mark says 'it stops here'. Commas say 'slow down' and apostrophes say 'letters are missing'. Without them, a reader has to guess where ideas begin and end.\n\nGood writers also vary their sentences: short ones for impact, longer ones with a comma and a joining word (and, but, so, because) to add detail.",
    [
        _step("1", "Complete sentences: subject and verb", "The subject is who or what the sentence is about. The verb is what the subject does or is. A sentence must have both, and it must express a complete thought.\n\nA fragment is missing the subject, the verb or the complete thought. 'Running down the hill' has no subject. 'The girl on the bike' has no verb. 'Because it was raining' is not finished, so we wait for more.\n\nTo test a sentence ask two questions: Who or what? What happened or what is it? If both are answered and it feels finished, it is a sentence.",
              "Complete: The girl ran home. Fragment (no subject): Ran home. Fragment (no verb): The girl on the bike. Fragment (unfinished): Because it was raining.",
              "To fix a fragment, add the missing part: Because it was raining, we stayed inside.",
              ("Which is a complete sentence?", ["Running down the hill.", "The girl ran home.", "Under the table."], 1, "It has a who and an action.")),
        _step("2", "Four types of sentence", "A statement tells something and ends with a full stop. A question asks something and ends with a question mark. A command tells someone to do something and ends with a full stop (or an exclamation mark if it is strong). An exclamation shows strong feeling and ends with an exclamation mark.\n\nChoose the end mark by thinking about the job of the sentence and the voice you would use. Use exclamation marks sparingly, because if every sentence shouts, none of them stands out.\n\nAlso watch for run-on sentences. 'We went to the beach it was sunny' needs either a full stop or a joining word: We went to the beach, and it was sunny.",
              "Statement: The tide is coming in. Question: Where did you put my hat? Command: Pack your bag. Exclamation: What a huge wave!",
              "If you can answer it, it was a question. If you would shout it, think of an exclamation mark.",
              ("Which end mark fits: 'Where did you put my hat'?", [".", "?", "!"], 1, "It is a question.")),
        _step("3", "Capital letters", "Use a capital letter for: the first word of every sentence; the word I; proper nouns such as names of people (Mia), places (Brisbane, Australia), days (Tuesday), months (April) and special events (Christmas); and the main words in a title.\n\nA proper noun names one particular person, place or thing. A common noun names a general kind, so it has no capital: city, girl, river. 'Brisbane' is a proper noun but 'city' is common.",
              "Last Tuesday Mia and Dan took a train to Brisbane. We saw the river from the city.",
              "Capital letters help the reader find the beginning of sentences and the important names.",
              ("Which needs a capital letter?", ["morning", "Tuesday", "lunch"], 1, "Days of the week are proper nouns.")),
        _step("4", "Commas: lists and openers", "Use commas to separate three or more items in a list. Put commas between all the items except the last two, which are joined by 'and'.\n\nUse a comma after an opening word or phrase that comes before the main part of the sentence. This is often a time or place: Suddenly, the lights went out. After lunch, we went to the park. At the top of the hill, a castle stood.\n\nA comma also goes before a joining word like 'but' or 'so' when it joins two full sentences: She wanted to swim, but the water was cold.",
              "We bought apples, pears and plums. Mia packed a hat, a towel, sunscreen and a drink. After school, we went to the beach.",
              "Commas separate; 'and' joins the last two.",
              ("Which is punctuated correctly?", ["We bought apples, pears and plums.", "We bought, apples pears, and plums."], 0, "Commas go between items.")),
        _step("5", "Apostrophes in contractions", "A contraction squashes two words into one. The apostrophe goes exactly where the letters were taken out. do not becomes don't (o is missing), she is becomes she's (i is missing), we will becomes we'll (wi is missing), can not becomes can't (no is missing).\n\nBe careful with its and it's. It's always means 'it is' or 'it has'. Its (no apostrophe) shows ownership: The dog wagged its tail. If you can say 'it is' in its place, use it's.\n\nContractions make writing sound like talking, so they suit dialogue and friendly writing. In very formal writing we often write the full words.",
              "don't = do not. she's = she is. can't = cannot. we'll = we will. it's raining (it is). The bird flapped its wings (ownership).",
              "The apostrophe replaces the missing letters, not the space.",
              ("'can't' is short for which words?", ["can not", "cat not", "cant"], 0, "The apostrophe replaces 'no'.")),
        _step("6", "Proofreading with CUPS", "Good writers check their own work. Use CUPS and look at your writing four times, one job at a time.\n\nC is for Capitals: does every sentence start with one, and every name? U is for Understanding: does each sentence make sense, and is each one complete? P is for Punctuation: is there an end mark, commas in lists and apostrophes in contractions? S is for Spelling: underline words that do not look right and fix them.\n\nRead your writing aloud. Your ear catches fragments and run-ons that your eyes miss.",
              "Draft: 'last week mia and dan went to brisbane they packed a hat a towel and a drink'. C: Last, Mia, Dan, Brisbane, They. U: two ideas, so split them. P: full stop after Brisbane, commas in the list, full stop at the end. S: all correct.",
              "Check one thing at a time. You will find more mistakes than checking everything at once.",
              ("In CUPS, what does the P check?", ["Punctuation", "Pictures", "Paragraphs"], 0, "P is for Punctuation.")),
    ],
    "Draft: 'last week mia and dan went to brisbane they packed a hat a towel and a drink'. Fixed: 'Last week Mia and Dan went to Brisbane. They packed a hat, a towel and a drink.' Thinking: C, five capitals needed (Last, Mia, Dan, Brisbane, They). U, the draft is a run-on, two ideas stuck together, so I add a full stop. P, I add commas between the list items and a full stop at the end. S, no spelling mistakes.",
    "Fix each in your notebook using CUPS. 1) my sister cant swim but she loves the beach. 2) we saw a seal a penguin and a whale at the zoo. 3) after lunch we went to the park it was hot. 4) is that your dogs ball. 5) running down the hill. 6) the bird flapped its wings and its time to fly. Then write one sentence of each type: a statement, a question, a command and an exclamation about the beach.",
    "Stage 1 (plan): choose a topic, a day at the beach or the bush, and list five things you would see or do.\nStage 2 (write): write a paragraph of six sentences. Include one question, one list with commas, one opening phrase with a comma, two contractions and two proper nouns.\nStage 3 (proofread): check with CUPS, one letter at a time.\nStage 4 (handwriting): copy it out in neat joined handwriting.",
    "Which punctuation mark was the hardest to remember, and what helped?",
    "Does every sentence start with a capital and end with a mark? Did I include a list, a question, an opener with a comma and two contractions? Did I check with CUPS?",
    [
        _q("Which is a complete sentence?", ["The boy kicked the ball.", "Over the fence.", "Running fast."], 0, "It says who and what happened."),
        _q("Which is written correctly?", ["My sister lives in Sydney.", "my sister lives in sydney.", "My sister lives in sydney."], 0, "Capitals for the start and the place."),
        _q("Which end mark fits: 'Are you coming to the park'?", [".", "?", "!"], 1, "It asks a question."),
        _q("What does the apostrophe in 'she's' show?", ["Missing letters (she is)", "A list", "A question"], 0, "she is becomes she's."),
        _q("Which list is correct?", ["I packed a hat, a towel and a drink.", "I packed, a hat a towel, and a drink."], 0, "Commas between items."),
        _q("'didn't' is short for:", ["did not", "did now", "didn"], 0, "The apostrophe replaces 'o'."),
        _q("Which is a fragment?", ["It was raining.", "Because it was raining.", "The rain fell."], 1, "It does not make sense on its own."),
        _q("Which has correct capitals?", ["Last week Mia and Dan went to Brisbane.", "last week mia and dan went to brisbane."], 0, "Capitals for the first word, names and places."),
        _q("Which end mark best fits a shouted warning: 'Watch out'?", ["!", "?", ","], 0, "A strong warning takes an exclamation mark."),
        _q("Which is correct?", ["We can't wait.", "We cant wait.", "We ca'nt wait."], 0, "The apostrophe replaces the o."),
    ],
    "Upload a photo of your six-sentence paragraph in joined handwriting and your CUPS checks.",
    "Write a seven-item list inside one sentence and explain where each comma goes.",
    [("sentence", "A group of words with a subject and verb that makes sense on its own."), ("fragment", "A group of words missing a part of a sentence."),
     ("run-on", "Two sentences stuck together with no punctuation."),
     ("subject", "Who or what the sentence is about."), ("verb", "The doing or being word."),
     ("capital letter", "Used at the start of sentences and for names."), ("proper noun", "The name of a particular person, place or day."),
     ("comma", "Separates items in a list and follows openers."), ("apostrophe", "Shows missing letters in a contraction."),
     ("contraction", "Two words squashed into one.")],
    [
        _video("Capital letters, commas and full stops", "2-ybEW_4Oyo",
               "Watch how capital letters, commas and full stops are used. Notice the different jobs of commas.",
               "Re-read steps 1 to 4 above and punctuate a short paragraph from your book.",
               ("What does a full stop show?", ["The end of a sentence", "The start of a sentence", "A list"], 0, "A full stop marks the end of a sentence.")),
        _video("Capital letters and punctuation marks, including apostrophes", "5y7tlRn55uE",
               "Watch the parts on commas in lists and on apostrophes for contractions.",
               "Write ten contractions with their long forms, such as can't and cannot.",
               ("What do apostrophes do in contractions?", ["Take the place of missing letters", "Show a question", "Start a sentence"], 0, "They stand for the letters that were left out.")),
    ],
    _sort("Punctuation sorter", "Which end mark does each sentence need? Tap one, then press Check.",
          ["Full stop", "Question mark", "Exclamation mark"],
          [("The cat sat on the mat", 0), ("We went to the park after school", 0), ("Pack your bag for camp", 0), ("Where is my lunchbox", 1), ("Can you help me find my shoes", 1), ("What time does the bus leave", 1), ("Why is the sky red tonight", 1), ("Look out for the snake", 2), ("I won the race", 2), ("Help, the boat is sinking", 2), ("What a gigantic wave", 2)]),
    [
        _wc("Which contraction means 'we will'?", ["we'll", "were", "we'd"], 0, "we will becomes we'll."),
        _wc("Which contraction means 'could not'?", ["couldn't", "could'nt", "couldnt"], 0, "The apostrophe replaces the o."),
        _wc("Which needs a capital letter?", ["Tuesday", "morning", "lunch"], 0, "Days of the week are proper nouns."),
        _wc("Which is a fragment?", ["Over the bridge.", "We crossed the bridge.", "Dan ran."], 0, "It has no who or what and no action."),
        _wc("Which is correct? The dog wagged ___ tail.", ["its", "it's"], 0, "Its shows ownership; it's means it is."),
        _wc("Which has the comma in the right place?", ["After lunch, we played cricket.", "After, lunch we played cricket.", "After lunch we, played cricket."], 0, "A comma follows the opening phrase."),
        _wc("Which is a run-on?", ["We went to the beach it was sunny", "We went to the beach, and it was sunny.", "It was sunny."], 0, "Two ideas with no punctuation or joining word."),
        _wc("Which is a command?", ["Pack your bag.", "I packed my bag.", "Did you pack your bag?"], 0, "It tells someone to do something."),
    ],
    [
        {"key": "topic", "label": "My topic", "hint": "A day at the beach or the bush: where and when?"},
        {"key": "list", "label": "My list", "hint": "Five things you would see or do (these become your comma list)."},
        {"key": "question", "label": "My question", "hint": "Write one question a character could ask."},
        {"key": "opener", "label": "My opener", "hint": "Write an opening phrase with a comma, such as 'At the top of the hill,'."},
    ],
    ["Starting a sentence without a capital or forgetting names.", "Joining two ideas without any end mark (a run-on sentence).", "Writing 'cant' or 'dont' without the apostrophe.", "Mixing up its (ownership) and it's (it is)."],
    [{"title": "Punctuation Hunt", "description": "Find five sentences in a book with different end marks. Copy them and explain why each mark was used.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Fix the Sign", "description": "Write a short letter with no punctuation, swap with a family member and see if they can add it.", "type": "create", "difficulty": "stretch", "evidence_type": "photo"}],
    "1) My sister can't swim, but she loves the beach. 2) We saw a seal, a penguin and a whale at the zoo. 3) After lunch, we went to the park. It was hot. (or ...park, and it was hot.) 4) Is that your dog's ball? (ownership: dog's ball; the apostrophe of possession is an extension) 5) Running down the hill is a fragment: add a subject, e.g. The boy was running down the hill. 6) The bird flapped its wings, and it's time to fly. Sentence types: any correct statement, question, command and exclamation.",
)

L3 = build(
    "s2-eng-w01-l3-reading-expression", "Voice of the Storyteller: Reading with Expression",
    "The lighthouse story needs a voice! Train your reading voice like an actor, then show you understand every line.",
    "Reading fluency and comprehension",
    ["EN2-REFLU-01", "EN2-RECOM-01", "EN2-OLC-01"],
    {"EN2-REFLU-01": "Primary. Practises accuracy, pace, phrasing and expression.",
     "EN2-RECOM-01": "Answers literal and inferential questions on a short passage.",
     "EN2-OLC-01": "Reads aloud to a listener and discusses how it sounded."},
    "We are learning to read aloud smoothly and with expression and to understand what we read.",
    ["I can read words accurately and fix mistakes.", "I can use punctuation to guide my voice.",
     "I can read in meaningful phrases at a talking pace.", "I can show a character's feelings with my voice.", "I can answer literal and inference questions about what I read."],
    ["fluency", "accuracy", "expression", "phrasing", "pace", "punctuation", "infer", "literal"],
    ["A book or short text of his choice", "A device to record (optional)", "A listener"],
    "Child can read simple chapter-book text.",
    "Fluent reading has four parts: accuracy (reading the right words), pace (a talking speed), phrasing (reading in chunks that belong together) and expression (a voice that shows meaning and feeling). Fluency matters because when you do not have to think hard about each word, your brain is free to think about the meaning.\n\nPunctuation tells your voice what to do. A comma is a short pause, a full stop is a longer pause, a question mark makes the voice rise, an exclamation mark adds strong feeling, and quotation marks mean a character is speaking, so change your voice.\n\nReading aloud is also a way to check your understanding. If you cannot read a sentence smoothly, you may not have understood it. Good readers also ask two kinds of question: literal (the answer is stated in the text) and inference (you work it out from clues plus what you already know).",
    [
        _step("1", "Accuracy and self-correcting", "Accuracy means reading the words that are really on the page. Strong readers notice when something is wrong and fix it. They use three checks: Does it make sense? Does it sound right? Does it look right (do the letters match)?\n\nWhen you meet a hard word, use your tools: split it into syllables, look for a prefix or suffix, read to the end of the sentence and come back, or think what word would fit the story.\n\nSelf-correcting is not a mistake, it is a skill. When you notice and fix an error, you are reading like an expert.",
              "The text says 'The keeper was quiet.' You read 'quite' and the sentence sounds odd. You stop, look again at the letters (qui-et), fix it and carry on.",
              "Going back to fix a word is a strength, not a weakness.",
              ("A word you read does not make sense. What should you do?", ["Go back and re-read", "Keep going", "Skip the page"], 0, "Self-correcting is a strong reading habit.")),
        _step("2", "Pace: not too fast, not too slow", "A good pace sounds like natural talking. If you read too fast, listeners cannot follow and you may skip punctuation. If you read too slowly, the sentence falls apart and meaning is lost.\n\nVary your pace on purpose: slow down for important or scary moments, speed up for exciting action, and pause before a surprise.\n\nA quick test is to read a sentence aloud, then say it the way you would tell a friend. If the two sound different, your reading pace needs adjusting.",
              "Slow: The door creaked open... and there, in the shadows, stood a figure. Fast: He ran down the steps, along the path, and across the sand!",
              "Pace is a tool: slow builds tension, fast builds excitement.",
              ("Which pace suits a scary, quiet moment?", ["Slow", "Very fast", "Skip it"], 0, "Slowing down builds suspense.")),
        _step("3", "Phrasing: reading in chunks", "Phrasing means reading words in meaningful groups rather than one at a time. Phrases follow the meaning: who, what they did, where or when.\n\nTo find the chunks, look for punctuation and for small words that begin a new idea (and, but, when, to, in). Mark a slash at each natural pause and read each chunk in one smooth breath.\n\nWhen you read in chunks, your voice rises and falls like speech and your listener hears the meaning, not a list of words.",
              "Every evening / Mr Bell climbed the 112 steps / to the top of the lighthouse. / He polished the great glass lens / until it gleamed.",
              "Chunks follow the meaning and the punctuation.",
              ("What is phrasing?", ["Reading in meaningful chunks", "Reading as fast as possible", "Reading silently"], 0, "Phrasing groups words by meaning.")),
        _step("4", "Punctuation as instructions", "Each punctuation mark is an instruction from the author. A comma is a quick breath. A full stop is a longer stop and a drop in the voice. A question mark lifts the voice at the end. An exclamation mark adds energy or volume. Three dots (...) mean a slow trailing off or suspense. Quotation marks mean a character is speaking, so change your voice.\n\nThe words around the quote also give clues about the voice. 'she whispered', 'he bellowed' and 'they giggled' tell you exactly how to say the words.\n\nBefore you read a page aloud, scan it for punctuation and speaking words. You will already know where your voice needs to change.",
              "'Where are you going?' (voice rises) 'Run!' he shouted. (strong, urgent) He waited, listened, and then ran. (short pauses at commas)",
              "Pause at a comma, stop at a full stop, rise at a question.",
              ("What does your voice do at a question mark?", ["Rises", "Drops lower", "Stops completely"], 0, "Questions usually rise at the end.")),
        _step("5", "Expression: bring the characters to life", "Expression is how your voice shows meaning and feeling. Change four things: volume (loud or soft), speed (fast or slow), pitch (high or low) and tone (the feeling, such as scared, cross or excited).\n\nBefore you read dialogue, ask three questions. Who is speaking? How are they feeling? How would that voice sound? Then give each character a slightly different voice so listeners can tell them apart.\n\nNarration (the parts that are not speech) usually has a steady storyteller voice, with expression added where the action or emotion rises.",
              "Soft and slow (whispered): 'Be quiet, someone is coming.' Loud and fast (excited): 'We found it! We found the treasure!'",
              "Match your voice to the meaning of the words.",
              ("Which words should be read softly?", ["'Whisper', she said", "'Look out!' he shouted"], 0, "Whispering matches a soft voice.")),
        _step("6", "Understanding: literal and inference questions", "Reading is not just saying the words. Good readers understand and remember what they read. Literal questions ask for facts the text states directly, such as who, what, where and how many. You can point to the answer in the text.\n\nInference questions ask you to work something out from clues. The text does not say it outright. You use the clues plus what you already know. A good answer starts with 'I think... because the text says...'.\n\nWhen you finish a passage, retell it in your own words in order: beginning, middle and end. If you can retell it, you understood it.",
              "Passage: 'He polished the great glass lens until it gleamed.' Literal: What did he polish? (the lens). Inference: Why does he polish it? (so the light shines brightly, because the text says it gleamed and later that the beam warns ships.)",
              "Literal answers are found in the text; inference answers are built from clues.",
              ("Which is an inference question?", ["Why did Mr Bell polish the lens?", "How many steps did Mr Bell climb?", "What did Mr Bell light?"], 0, "The text does not say why; you work it out from the clues.")),
    ],
    "Passage: Every evening, Mr Bell climbed the 112 steps to the top of the lighthouse. He polished the great glass lens until it gleamed. Then he lit the lamp, and its beam swept across the dark water to warn the ships. Tonight, the wind howled and the waves crashed against the rocks. Mr Bell held the rail tightly, but he did not stop climbing. Somewhere out in the storm, a small boat was searching for the light.\n\nPhrasing: Every evening, / Mr Bell climbed the 112 steps / to the top of the lighthouse. Expression: read 'the wind howled and the waves crashed' with a rising, urgent voice; slow down for 'but he did not stop climbing'. Literal question: how many steps did he climb? (112.) Inference question: why did Mr Bell keep climbing in the storm? (because a boat out in the storm needed the light.)",
    "Part A (phrasing): copy the first two sentences of the passage and put a slash at each natural pause. Part B (punctuation): list each punctuation mark in the passage and say what your voice does for each. Part C (expression): read the last two sentences three times, each time changing your volume, speed or tone, and say which version sounded best. Part D (understanding): write one literal question and one inference question about the passage, with answers.",
    "Stage 1 (choose): pick a page from your own book, about 100 words.\nStage 2 (read): read it aloud three times to a listener or record it.\nStage 3 (rate): after each read, rate your accuracy, pace, phrasing and expression from 1 to 3.\nStage 4 (reflect): write two sentences on what improved, and write one literal and one inference question about your passage with the answers. Then retell the passage in three sentences: beginning, middle, end.",
    "Which of the four parts of fluency is your strongest, and which will you work on?",
    "Did I read three times, rate each, write two sentences on what improved, write two questions and retell the passage in three sentences?",
    [
        _q("What does a comma tell your voice to do?", ["Pause briefly", "Stop for a long time", "Shout"], 0, "A comma is a short pause."),
        _q("What does your voice do at a question mark?", ["Rises", "Falls", "Stays flat"], 0, "Questions usually rise."),
        _q("What is phrasing?", ["Reading in meaningful chunks", "Reading very fast", "Reading word by word"], 0, "Chunks follow meaning."),
        _q("Passage: 'Every evening, Mr Bell climbed the 112 steps to the top of the lighthouse.' How many steps did he climb?", ["12", "112", "211"], 1, "The text says 112 steps."),
        _q("Passage: 'He polished the great glass lens until it gleamed.' What does 'gleamed' suggest?", ["Shone brightly", "Broke", "Went dark"], 0, "To gleam is to shine."),
        _q("Passage: 'Then he lit the lamp, and its beam swept across the dark water to warn the ships.' Why did he light the lamp?", ["To warn ships", "To read a book", "To cook dinner"], 0, "The beam warns the ships."),
        _q("What happens first in the passage?", ["He climbs the steps", "He lights the lamp", "He polishes the lens"], 0, "He climbs, polishes, then lights the lamp."),
        _q("You read a word that makes no sense. What do you do?", ["Go back and fix it", "Ignore it", "Stop reading"], 0, "Self-correct."),
        _q("Which part of fluency is about your voice showing feeling?", ["Expression", "Accuracy", "Pace"], 0, "Expression is the feeling in your voice."),
        _q("What does an exclamation mark add?", ["Strong feeling", "A question", "A list"], 0, "It shows strong feeling or force."),
    ],
    "Upload a short recording or a photo of your rating table, your two sentences, your two questions and your three-sentence retell.",
    "Read a poem aloud and plan where to pause, speed up and slow down.",
    [("fluency", "Reading smoothly and with understanding."), ("accuracy", "Reading the words that are on the page."), ("expression", "Using your voice to show meaning and feeling."),
     ("phrasing", "Reading in meaningful chunks."), ("pace", "The speed of your reading."),
     ("punctuation", "Marks that guide pauses and voice."), ("literal", "A question whose answer is stated in the text."), ("infer", "Work out something using clues in the text.")],
    [
        _video("Punctuation Celebration (read aloud)", "RgGrNL82r4I",
               "Listen to how the reader's voice changes with punctuation. Notice the pauses, the rises and the feeling.",
               "Read a page aloud and mark each comma with a short pause and each question mark with a rise.",
               ("Which part of fluency is shown when a reader's voice changes with the meaning?", ["Expression", "Spelling", "Handwriting"], 0, "Expression shows meaning through the voice.")),
        _video("Punctuation and grammar for kids (read aloud)", "2zNAQW5jPwI",
               "Listen to the read-aloud and notice how the narrator treats each punctuation mark.",
               "Choose a short text and read it with a pause at every punctuation mark.",
               ("What should a reader do at a full stop?", ["Pause and let the idea finish", "Speed up", "Skip it"], 0, "A full stop is a longer pause.")),
        _article("Fluency practice: reading with expression (Reading Universe)", "https://readinguniverse.org/resources/video/fluency/fluency-practice-reading-with-expression"),
    ],
    _sort("Voice sorter", "How should your voice sound for each line? Tap one, then press Check.",
          ["Soft and slow", "Loud and fast", "Rising (a question)"],
          [("'Be quiet, the baby is sleeping,' she whispered.", 0), ("The candle flickered in the dark, silent room.", 0), ("'I think I heard something,' he murmured.", 0), ("'Run! The tide is coming in!'", 1), ("'We won! We actually won!'", 1), ("'Look out behind you!' she screamed.", 1), ("'Where did you hide the key?'", 2), ("'Are you coming to the beach with us?'", 2), ("'Did you see that?'", 2)]),
    [
        _wc("The wind howled and the sea ___ against the cliff.", ["crashed", "sat", "smiled"], 0, "Crashed paints a strong sound picture."),
        _wc("A reader who skips punctuation will ___.", ["miss the pauses and feeling", "read faster and better", "learn spelling"], 0, "Punctuation guides pauses and feeling."),
        _wc("If someone 'murmured', their voice was ___.", ["quiet and low", "loud", "high and squeaky"], 0, "Murmured means spoke quietly."),
        _wc("To 'infer' means to ___.", ["work out using clues", "copy a word", "read quickly"], 0, "Infer means working something out from clues."),
        _wc("A 'literal' question has an answer that is ___.", ["stated in the text", "hidden in clues", "never found"], 0, "Literal means you can point to it."),
        _wc("If a character 'bellowed', your voice should be ___.", ["loud and deep", "whispery", "silent"], 0, "Bellowed means shouted in a deep, loud voice."),
    ],
    [
        {"key": "book", "label": "My book", "hint": "Title and the page you chose."},
        {"key": "goal", "label": "My fluency goal", "hint": "Which of accuracy, pace, phrasing or expression will you work on?"},
        {"key": "chunks", "label": "Chunks", "hint": "Copy one sentence from your page and mark the phrases with slashes."},
    ],
    ["Reading so fast the meaning is lost.", "Reading word by word with no chunks.", "Ignoring punctuation marks when reading aloud.", "Not stopping to fix a word that does not make sense."],
    [{"title": "Radio Voice", "description": "Record yourself reading a page like a radio announcer. Share it with a family member and ask which part sounded best.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"},
     {"title": "Character Voices", "description": "Read a scene from a book giving each character a different voice. Write how you chose each voice.", "type": "create", "difficulty": "stretch", "evidence_type": "audio"}],
    "Part A (example): Every evening, / Mr Bell climbed the 112 steps / to the top of the lighthouse. / He polished the great glass lens / until it gleamed. Part B: comma = short pause; full stop = longer pause and falling voice; any exclamation or question marks if used. Part C: any sensible comparison of volume, speed or tone. Part D: literal e.g. How many steps did he climb? (112). Inference e.g. Why did he keep climbing in the storm? (a boat needed the light).",
)

L4 = build(
    "s2-eng-w01-l4-show-dont-tell", "Paint with Words: Show, Don't Tell",
    "A blank page is waiting! Learn the writer's paint box, then use it to build a place so real your reader steps inside.",
    "Creating written texts: imaginative description",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01", "EN2-HANDW-01"],
    {"EN2-CWT-01": "Primary. Plans, writes and revises an imaginative description of a place.",
     "EN2-VOCAB-01": "Chooses precise Tier 2 words including strong verbs.",
     "EN2-SPELL-01": "Proofreads and corrects spelling using strategies.",
     "EN2-HANDW-01": "Writes the final copy in neat joined handwriting."},
    "We are learning to show feelings and places with precise words instead of telling.",
    ["I can show a feeling rather than name it.", "I can use at least three senses.", "I can use strong verbs.", "I can build a precise noun group.", "I can use a simile and revise my work."],
    ["show, don't tell", "senses", "strong verb", "noun group", "precise", "simile", "atmosphere", "revise"],
    ["Paper or notebook", "Pencil", "Coloured pencils"], "Child can write several connected sentences.",
    "Telling names a feeling or fact: 'She was scared.' Showing lets the reader work it out: 'Her hands trembled and she held her breath.' When you show, the reader does some of the thinking, and that is why the writing feels alive.\n\nWriters use five tools. First, body language and actions (trembled, clenched). Second, the five senses: sight, sound, smell, taste and touch. Third, strong verbs, which say more than a plain verb plus an adverb (trudged, not walked slowly). Fourth, noun groups with precise describing words (the rusty, creaking gate). Fifth, figurative language such as similes (as cold as ice).\n\nYou do not need to show everything. Tell the simple facts, such as time and place, and show the moments that matter. Revising is where you find the telling and change it to showing.",
    [
        _step("1", "Show, don't tell: the feeling ladder", "Instead of naming a feeling, describe what the body does, what the character thinks or says, or what they notice. Use this ladder from the inside out: body (sweaty palms, racing heart), action (pacing, hugging, slamming), words or thoughts ('What if I fail?'), and what they notice (the ticking clock).\n\nTry this: take the word 'nervous' and ask, what does a nervous person do? They fidget, sweat, stammer or check the clock. Use one or two of those and never write the feeling word.\n\nA warning: do not show everything. Use showing for the key moment of feeling, and use a short telling sentence to move the story on.",
              "Tell: He was nervous. Show: He wiped his sweaty palms on his shorts and checked the clock again. Tell: She was happy. Show: She grinned and skipped down the path, humming.",
              "The reader works out the feeling, so you never write the feeling word.",
              ("Which sentence shows rather than tells?", ["She was happy.", "She grinned and skipped down the path."], 1, "It shows actions.")),
        _step("2", "The five senses", "Sight is the sense we use most, but sound, smell, taste and touch make a place feel real. Aim for at least three senses in a description.\n\nSight: colour, shape, size, light (a pale, silver moon). Sound: loud, soft, sharp, rhythmic (waves hissed on the sand). Smell: fresh, smoky, salty, sour (smoke curled in the air). Touch: texture, temperature, weight (cold, damp sand). Taste: sweet, bitter, salty (the sea spray tasted of salt).\n\nTip: close your eyes and imagine the place. Write what you notice for each sense, then pick the best details for your writing.",
              "The salty smell of the sea drifted over the rocks, waves hissed on the sand, and a cold wind pricked her cheeks. (smell, sound, touch)",
              "Pick three senses at least, and not just sight.",
              ("Which sense is used: 'the salty smell of the sea'?", ["Sight", "Smell", "Hearing"], 1, "Smell.")),
        _step("3", "Strong verbs and verb ladders", "A strong verb carries more meaning than a plain verb plus an adverb. One strong verb is shorter and clearer than two weak words.\n\nBuild verb ladders. Walk: stroll, trudge, march, tiptoe, stagger. Say: whisper, mutter, bellow, shriek, announce. Look: glance, stare, peek, gaze, glare. Run: dash, sprint, bolt, scramble. Each rung has a slightly different feeling, so choose the one that matches the mood.\n\nAvoid overusing the same verb. If you wrote 'said' five times, replace some with stronger choices.",
              "walked slowly and heavily becomes trudged. said quietly becomes whispered. ran quickly becomes sprinted. looked angrily becomes glared.",
              "Ask: is there one word that says it better?",
              ("Which verb means to walk slowly and heavily?", ["skipped", "trudged", "dashed"], 1, "Trudged.")),
        _step("4", "Precise nouns and noun groups", "A noun group is a noun with describing words around it. Make your writing precise in two ways: choose a specific noun (terrier instead of dog, cottage instead of house) and add describing words before or after it.\n\nUse words that paint exact pictures instead of vague ones like nice, big or good. Replace 'big' with enormous, towering or vast; replace 'nice' with welcoming, peaceful or sparkling.\n\nNoun groups can also carry details after the noun: the gate, rusty and creaking, hung from one hinge.",
              "the rusty, creaking gate. a cold, silent darkness. the enormous, moss-covered rock. a shaggy terrier with muddy paws.",
              "Precise describing words help the reader picture it exactly.",
              ("Which noun group is most precise?", ["a gate", "the gate", "the rusty, creaking gate"], 2, "It gives two details.")),
        _step("5", "Similes: comparing to paint a picture", "A simile compares two things using 'like' or 'as'. It helps the reader picture something by linking it to something they already know.\n\nA good simile is fresh and fits the mood. 'As white as snow' is worn out. 'The moon hung like a thin silver coin' is more original. Do not use too many similes: one or two well-chosen ones are enough.\n\nYou can build a simile with a template: [the thing] was as [adjective] as [something]. Or: [the thing] [verb] like [something].",
              "The waves rolled in like sleepy giants. The cave was as dark as the inside of a boot. Her laugh sounded like tiny bells.",
              "The best similes link something new to something familiar.",
              ("Which sentence contains a simile?", ["The waves rolled in like sleepy giants.", "The waves rolled in."], 0, "It compares using 'like'.")),
        _step("6", "Revising: from telling to showing", "Revising means making your writing better after the first draft. Read your draft and underline every telling sentence (names a feeling or says 'it was...'). Then ask: which one is the key moment? Rewrite that one using body, senses and strong verbs.\n\nUse this revising checklist: Did I show at least one feeling without naming it? Did I use three senses? Are my verbs strong? Are my noun groups precise? Did I include a simile? Are there any vague words (nice, big, good)? Then proofread for capitals, punctuation and spelling.\n\nRead the best sentence aloud. If it makes you see or feel something, keep it.",
              "Draft: The old house was scary. It was dark and I was frightened. Revised: A cold draught whistled through the broken window, and the staircase groaned as Ella crept upward. Her heart thudded like a drum.",
              "Revising is where good writing is made.",
              ("What is the first step in revising a draft?", ["Underline the telling sentences", "Copy it out neatly", "Add a title"], 0, "Find the telling sentences so you can change them.")),
    ],
    "Plain draft: The old house was scary. It was dark and I was frightened. Revised: A cold draught whistled through the broken window, and the staircase groaned as Ella crept upward. Her heart thudded like a drum. Notice: no feeling word, three senses (touch: cold draught; sound: whistled, groaned, thudded; sight: broken window), strong verbs (whistled, groaned, crept, thudded), noun groups (a cold draught, the broken window), and a simile (like a drum).",
    "Part A (show): turn five telling sentences into showing sentences: 1) She was angry. 2) The boy was tired. 3) The room was messy. 4) He was excited. 5) The beach was beautiful. Part B (verbs): replace the underlined plain verb in each with a strong verb: The dog (ran) across the park. She (said) the secret. He (walked) up the hill. Part C (senses): write one sentence each for sound, smell and touch for a market. Part D (simile): write two similes about a storm.",
    "Stage 1 (plan): choose a place at night, such as a beach, the bush, a haunted house or a city street, and fill in the planner.\nStage 2 (write): write 8 to 10 sentences describing it. Use at least three senses, two strong verbs, two precise noun groups and one simile. Show one feeling without naming it.\nStage 3 (revise and proofread): underline telling sentences and change one to showing, then check capitals, end marks and spelling using your strategies.\nStage 4 (handwriting): copy it out in neat joined handwriting.",
    "Which sentence are you proudest of, and which technique did it use?",
    "Did I use three senses, two strong verbs, two precise noun groups and a simile? Did I show a feeling without naming it? Did I revise?",
    [
        _q("Which sentence shows rather than tells?", ["Her hands trembled and she held her breath.", "She was scared."], 0, "It shows actions and body language."),
        _q("Which sense: 'the salty smell of the sea'?", ["Smell", "Hearing", "Sight"], 0, "Smell."),
        _q("Which strong verb means to walk slowly and heavily?", ["trudged", "skipped", "dashed"], 0, "Trudged."),
        _q("Which noun group is most precise?", ["the rusty, creaking gate", "the gate", "a gate"], 0, "More detail."),
        _q("Which sentence uses sound?", ["The floorboards groaned under his feet.", "The floor was brown."], 0, "Groaned is a sound."),
        _q("'His face went red and he stared at the floor' shows which feeling?", ["Embarrassed", "Excited", "Sleepy"], 0, "The actions show embarrassment."),
        _q("Which word is a strong verb for 'said quietly'?", ["whispered", "talked", "spoke"], 0, "Whispered."),
        _q("Why do writers describe a setting?", ["To help readers picture and feel it", "To make the story longer", "To fill the page"], 0, "Description builds a picture."),
        _q("Which is 'telling'?", ["He was angry.", "He slammed the door and clenched his fists."], 0, "Telling names the feeling."),
        _q("Which replaces 'ran quickly'?", ["sprinted", "ran", "went"], 0, "Sprinted."),
    ],
    "Upload a photo of your final description in joined handwriting. Highlight the senses, strong verbs and simile.",
    "Write the same place in the morning and compare the atmosphere.",
    [("show, don't tell", "Describe actions and details instead of naming a feeling."), ("senses", "Sight, sound, smell, taste and touch."),
     ("strong verb", "A verb with a precise meaning, like trudged."), ("noun group", "A noun with describing words, like the rusty gate."),
     ("simile", "A comparison using 'like' or 'as'."), ("precise", "Exact and clear."), ("atmosphere", "The feeling a writer creates in a scene."), ("revise", "To change a draft to make it better.")],
    [
        _video("Show, Don't Tell (author Victoria J. Coe)", "WYAg1FU-zHQ",
               "A children's author explains show, don't tell. Listen for how she shows a brave or nervous character.",
               "Re-read the worked example and underline the actions that show the feeling.",
               ("What does 'show, don't tell' ask a writer to do?", ["Show what is happening instead of just stating it", "Write shorter sentences", "Use more adjectives only"], 0, "Show events and feelings through actions and details.")),
        _video("Using writing tools to add description (powerful verbs, sensory language)", "9VC2BRog7KI",
               "Watch how adjectives, powerful verbs and sensory language make golden sentences.",
               "Write five plain sentences and upgrade each with a strong verb and a sense.",
               ("Why do writers use powerful (strong) verbs?", ["They give a clearer, more vivid picture", "They make the sentence shorter", "They replace punctuation"], 0, "Strong verbs say more with fewer words.")),
        _video("Show, Don't Tell writing technique (EasyTeaching)", "-U1pBoBOj9w",
               "Watch how telling sentences are changed into showing sentences. Compare each pair.",
               "Take three telling sentences from your own writing and rewrite them as showing sentences.",
               ("When a writer 'tells', what are they doing?", ["Stating information plainly", "Describing every sense", "Using a simile"], 0, "Telling simply states the information.")),
    ],
    _sort("Show or tell?", "Is each sentence showing or telling? Tap one, then press Check.",
          ["Telling", "Showing"],
          [("The boy was nervous.", 0), ("She was very sad.", 0), ("The cave was scary.", 0), ("He was angry with his brother.", 0), ("The beach was beautiful.", 0),
           ("The boy wiped his sweaty palms and checked the clock again.", 1), ("Tears slid down her cheeks as she hugged the empty box.", 1),
           ("A cold, silent darkness swallowed the cave.", 1), ("He slammed the door and clenched his fists.", 1), ("Her laugh bubbled out like tiny bells.", 1)]),
    [
        _wc("The mouse ___ across the kitchen floor on tiny feet.", ["scurried", "went", "moved"], 0, "Scurried is a precise, strong verb."),
        _wc("The old floorboards ___ under his feet.", ["groaned", "were", "stayed"], 0, "Groaned adds a sound."),
        _wc("Which is the most precise noun group?", ["the crumbling, moss-covered wall", "a wall", "the wall"], 0, "It adds detail."),
        _wc("Which sentence uses touch?", ["The sand was cool and damp between my toes.", "The sand was there.", "I saw sand."], 0, "Cool and damp describe touch."),
        _wc("Which is a simile?", ["The moon hung like a silver coin.", "The moon was big.", "The moon rose."], 0, "It compares using 'like'."),
        _wc("Which strong verb best replaces 'looked angrily'?", ["glared", "saw", "watched"], 0, "Glared shows anger."),
        _wc("Which sentence shows a feeling without naming it?", ["Her knees shook and her voice came out as a squeak.", "She felt scared.", "She was scared."], 0, "The actions show she is scared."),
        _wc("Which vague word could be replaced with 'enormous'?", ["big", "red", "quick"], 0, "Enormous is a precise word for very big."),
    ],
    [
        {"key": "place", "label": "My place", "hint": "Where is it and what time is it?"},
        {"key": "senses", "label": "My senses", "hint": "Write one detail for each of three senses."},
        {"key": "verbs", "label": "Strong verbs", "hint": "List two strong verbs you will use."},
        {"key": "feeling", "label": "Feeling to show", "hint": "What feeling will you show without naming it, and how?"},
        {"key": "simile", "label": "My simile", "hint": "Write one simile you could use."},
    ],
    ["Naming the feeling instead of showing it (writing 'she was scared').", "Using only sight and forgetting sound, smell and touch.", "Using a plain verb plus an adverb instead of one strong verb.", "Using vague words like nice, big or good, and using a simile that is worn out."],
    [{"title": "Telling to Showing", "description": "Take five 'telling' sentences from your own writing and rewrite each as a 'showing' sentence.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Sense Walk", "description": "Sit outside for five minutes and write one detail for each of the five senses. Turn them into three sentences.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A (examples): 1) Her jaw clenched and she stamped upstairs. 2) The boy's eyelids drooped and he dragged his feet. 3) Socks, books and crumbs covered every inch of the floor. 4) He bounced on his toes and could not stop grinning. 5) Golden light danced on the waves and the sand glittered. Part B (examples): sprinted or dashed; whispered or muttered; trudged or strolled. Part C and D: any suitable sensory sentences and two sensible similes.",
)

WEEK_1 = [L1, L2, L3, L4]


def _set_library_version(version=14):
    for name, mod in list(sys.modules.items()):
        if name.split(".")[-1] == "lesson_library" and hasattr(mod, "LESSON_LIBRARY_VERSION"):
            if mod.LESSON_LIBRARY_VERSION < version:
                mod.LESSON_LIBRARY_VERSION = version


_set_library_version()
