"""Stage 2 English, Week 1 of the program (four 60-minute lessons).
Outcome codes come from nsw_outcomes_stage2_verified.py.
This module also raises LESSON_LIBRARY_VERSION to 13 so the library re-seeds; fold that into lesson_library.py when convenient."""
import sys


def _q(q, opts, idx, why):
    return {"question": q, "type": "multiple_choice", "options": opts, "correct_index": idx, "explanation": why}


def _step(icon, title, explain, example, notice, chk):
    q, opts, idx, why = chk
    return {"icon": icon, "title": title, "explain": explain, "example": example, "notice": notice,
            "check": {"question": q, "options": opts, "correct_index": idx, "explanation": why}}


def _video(title, vid, prompt, offline, chk):
    q, opts, idx, why = chk
    return {"type": "video", "title": title, "url": f"https://www.youtube.com/watch?v={vid}",
            "embed_url": f"https://www.youtube-nocookie.com/embed/{vid}", "prompt": prompt,
            "offline_alternative": offline,
            "check": {"question": q, "options": opts, "correct_index": idx, "explanation": why}}


def _article(title, url):
    return {"type": "article", "title": title, "url": url}


def build(key, title, mission, subject, codes, notes, intention, criteria, vocab, materials, prior,
          teaching, steps, worked, guided, independent, response, selfcheck, quiz, evidence, extension, cards,
          resources, sort_activity, word_challenges, planner, mistakes, challenges):
    lesson = {
        "seed_key": key, "library": True, "stage": "S2", "year_level": "Stage 2", "learning_area": "English",
        "subject": subject, "title": title, "child_mission": mission, "duration_minutes": 60, "pass_mark": 0.9,
        "outcome_codes": codes, "outcome_notes": notes, "learning_intention": intention,
        "success_criteria": criteria + ["I can score 90% or more on the Quest check."],
        "key_vocabulary": vocab, "materials": materials, "prior_knowledge": prior,
        "explicit_teaching": teaching + "\n\nCommon mistakes to watch for:\n" + "\n".join("- " + m for m in mistakes),
        "teach_steps": steps, "worked_example": worked, "guided_practice": guided, "independent_task": independent,
        "response_prompt": response, "self_check": selfcheck,
        "accessibility_notes": "Allow dictation or typing. Break the written task into two sittings. Reduce the length by a third if needed. Pause the videos as often as you like.",
        "interactive_activities": [{"type": "flip_cards", "title": "Quest Codex: key terms",
                                    "cards": [{"front": f, "back": b} for f, b in cards]}],
        "sort_activity": sort_activity, "word_challenges": word_challenges,
        "steps": [
            {"title": "Step 1: Accept the quest", "detail": "Read your mission and the learning goals.", "duration_minutes": 5},
            {"title": "Step 2: Learn the map", "detail": "Four short lessons, each with an explanation, examples and a quick try.", "duration_minutes": 15},
            {"title": "Step 3: Practise the craft", "detail": "Watch the two videos and answer the checks, flip the key-term cards, then complete the sorting and word challenges.", "duration_minutes": 15},
            {"title": "Step 4: Apply it", "detail": "Plan, then complete the independent task.", "duration_minutes": 15},
            {"title": "Step 5: Quest check", "detail": "Answer the 10-question check. You need 9 out of 10.", "duration_minutes": 5},
            {"title": "Step 6: Hand it in", "detail": "Check your work against the success criteria and submit your evidence.", "duration_minutes": 5},
        ],
        "resources": resources, "quiz": quiz,
        "reflection_prompts": ["What was the trickiest part today?", "What will you do differently next time?"],
        "evidence_instructions": evidence,
        "parent_notes": "Practice lesson only. Quiz scores are formative; competency is decided by the fortnightly mini exam. Check the written task against the success criteria. Video check questions are about the main idea so they can be answered if a video is unavailable; use the offline alternative if needed. Verify the outcome mapping against the NESA English K-10 syllabus.",
        "source_note": "Outcome codes from the NSW English K-10 Syllabus (NESA 2022), Stage 2. Parent to verify alignment on curriculum.nsw.edu.au.",
        "offline_alternative": "Complete all written tasks on paper and read the questions aloud. Videos can be skipped if the worked example is read aloud.",
        "extension": extension, "follow_up_challenges": challenges,
    }
    if planner:
        lesson["planner_fields"] = planner
    return lesson


def _sort(title, instr, buckets, items):
    return {"title": title, "instructions": instr, "buckets": buckets, "items": [{"text": t, "answer": a} for t, a in items]}


def _wc(q, opts, idx, why):
    return {"question": q, "options": opts, "correct_index": idx, "explanation": why}


L1 = build(
    "s2-eng-w01-l1-spelling-strategies", "Spelling Detective: Four Strategies",
    "A tricky word has escaped the page! Learn four detective strategies to catch it, then use them on ten real words.",
    "Spelling: select, apply and describe strategies",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-HANDW-01"],
    {"EN2-SPELL-01": "Primary. Learns, applies and describes four strategies (quiz, sort and word log).",
     "EN2-VOCAB-01": "Uses prefixes, suffixes and base words to work out word meanings.",
     "EN2-HANDW-01": "Copies the word log in neat joined handwriting."},
    "We are learning to choose and use spelling strategies to spell tricky words.",
    ["I can break a word into sounds and into syllables.", "I can find the base word, prefix and suffix in a word.",
     "I can use Look, Say, Cover, Write, Check to learn a word.", "I can describe which strategy I used and why."],
    ["syllable", "base word", "prefix", "suffix", "strategy", "phoneme"],
    ["Paper or notebook", "Pencil", "Your own writing for tricky words"],
    "Child can write simple sentences and knows the alphabet sounds.",
    "Good spellers do not guess. They choose a strategy that suits the word.\n\nStrategy 1, sound it out: say the word slowly and write a letter or letters for each sound (phoneme). Strategy 2, syllables: clap the beats and spell one beat at a time. Strategy 3, word parts: find the base word and any prefix (front) or suffix (end). Strategy 4, Look, Say, Cover, Write, Check: for tricky words that do not follow the rules, learn the shape of the word and test your memory.\n\nNo single strategy works for every word. 'Chimp' works well by sounds, 'fantastic' by syllables, 'unhappy' by word parts and 'friend' by memory. Choosing the right tool is the skill.",
    [
        _step("1", "Sound it out", "Every word is made of sounds, called phonemes. Say the word slowly, stretch each sound, and write the letter or letters for it. Some sounds need two letters together, like sh, ch, th and ng.\n\nPut a finger up for each sound as you say it. The number of sounds is not always the number of letters. 'Ship' has four letters but only three sounds.",
              "chimp: ch - i - m - p (four sounds, five letters). thing: th - i - ng (three sounds, five letters).",
              "Count sounds, not letters. Letter pairs like sh and ch count as one sound.",
              ("How many sounds are in 'ship'?", ["2", "3", "4"], 1, "sh - i - p is three sounds.")),
        _step("2", "Clap the syllables", "A syllable is one beat in a word, and every syllable has a vowel sound. Clap or tap your chin as you say the word. Then write one beat at a time so a long word does not feel scary.\n\nThis strategy is best for long words, because small chunks are easier to spell than one big word.",
              "fan-tas-tic (3). but-ter-fly (3). un-for-get-ta-ble (5). dog (1).",
              "If you put your hand under your chin, it drops once for each syllable.",
              ("How many syllables are in 'butterfly'?", ["2", "3", "4"], 1, "but-ter-fly has three beats.")),
        _step("3", "Find the word parts", "A base word carries the main meaning. A prefix is added to the front and changes the meaning: un- means not (unhappy), re- means again (replay), dis- means not or apart (disagree). A suffix is added to the end: -ing, -ed, -ful (full of), -less (without), -ly.\n\nIf you can spell the base word and the parts, you can spell lots of words that look hard.",
              "unhappy = un + happy. jumping = jump + ing. careful = care + ful. replaying = re + play + ing.",
              "The base word is the part that can stand alone. Some base words change a little, such as happy becoming happiness.",
              ("What is the base word in 'replaying'?", ["re", "play", "ing"], 1, "re + play + ing: play is the base word.")),
        _step("4", "Look, Say, Cover, Write, Check", "Some words do not follow the rules, so you have to learn how they look. Look at the word and notice the tricky part. Say it out loud. Cover it. Write it from memory. Check it against the real word. If you made a mistake, fix only the wrong part and try again.\n\nPractise a word three days in a row and it will stay in your memory.",
              "Tricky words: because, friend, said, again, people, would, could.",
              "Circle the tricky part, such as the ie in friend.",
              ("In Look, Say, Cover, Write, Check, what comes right after Cover?", ["Check", "Write", "Look"], 1, "You write it from memory, then check.")),
    ],
    "Word: unfriendly. Sounds: un-fr-ie-nd-l-y. Word parts: un + friend + ly. Syllables: un-friend-ly (3). Tricky part: ie in friend, so I use Look, Say, Cover, Write, Check for 'friend', then add un and ly. Strategy log: word parts first, then memory for the tricky middle.",
    "Take 'replaying' and 'because'. For each, say which strategy helps most and why, and write the word using that strategy. Then try 'careful' and 'beautiful' with word parts and syllables. Check each against a dictionary or book.",
    "Stage 1 (plan): choose 10 words you misspelt in recent writing, or use: because, friend, said, again, people, would, could, through, favourite, beautiful.\nStage 2 (apply): for each word write it using the best strategy and note the strategy beside it (sounds, syllables, parts or LSCWC). Circle the tricky part.\nStage 3 (handwriting): copy your best five words in neat joined handwriting.\nStage 4 (reflect): write two sentences on which strategy you used most and why.",
    "Which strategy did you use most, and why did it work for those words?",
    "Did I write 10 words, name a strategy for each, circle the tricky part, write five in joined handwriting and explain my choice?",
    [
        _q("Which strategy breaks a word into beats?", ["Syllables", "Prefixes", "Capital letters", "Full stops"], 0, "Clapping beats finds the syllables."),
        _q("Which word contains the base word 'happy'?", ["unhappy", "hippo", "happen", "hope"], 0, "un + happy."),
        _q("How many sounds are in 'stamp'?", ["3", "4", "5"], 2, "s - t - a - m - p."),
        _q("How many syllables are in 'elephant'?", ["2", "3", "4"], 1, "el-e-phant."),
        _q("Which is spelt correctly?", ["freind", "friend", "frend"], 1, "friend has ie, then nd."),
        _q("Which is spelt correctly?", ["becuase", "because", "becaus"], 1, "because: be-cause."),
        _q("What is the suffix in 'playing'?", ["play", "ing", "pl"], 1, "A suffix goes at the end."),
        _q("What is the prefix in 'unlock'?", ["lock", "un", "ock"], 1, "A prefix goes at the front."),
        _q("Which strategy suits a tricky word like 'said'?", ["Look, Say, Cover, Write, Check", "Clap the syllables", "Guess it"], 0, "Tricky words need memory practice."),
        _q("What does 'unlock' mean?", ["to lock again", "to open a lock", "a big lock"], 1, "The prefix un- means not or the opposite."),
    ],
    "Upload a photo of your word log showing your 10 words, the strategy for each, circled tricky parts and five words in joined handwriting.",
    "Choose a longer word such as 'unforgettable' and explain every strategy you could use on it.",
    [("syllable", "One beat in a word."), ("phoneme", "One sound in a word."), ("base word", "The main part of a word that can stand alone."),
     ("prefix", "A word part added to the front, like un- or re-."), ("suffix", "A word part added to the end, like -ing or -ful."),
     ("strategy", "A method you choose to solve a problem.")],
    [
        _video("Syllables, prefixes and suffixes for kids (Kids Academy)", "Qz0LWrJDfx0",
               "Watch how to find syllables and how prefixes and suffixes change a word. Then answer the question below.",
               "Re-read the four steps above and clap the syllables in five words from your book.",
               ("What does a prefix do to a word?", ["Adds to the front and can change the meaning", "Adds a full stop", "Takes letters away"], 0, "A prefix goes at the front of a base word and changes its meaning.")),
        _video("Prefixes and suffixes grammar lesson", "jujRYzE9Cxs",
               "Watch how to spot the root word, prefix and suffix. Notice how spelling the suffix helps you focus on the base word.",
               "Find five words in your book that end in -ing or -ed and write the base word for each.",
               ("Which word is the root (base) word in 'jumping'?", ["jump", "ing", "ju"], 0, "Jump is the base word; -ing is the suffix.")),
        _article("Spelling strategies for kids (playlist)", "https://www.youtube.com/playlist?list=PLXptQXQyXxHsXpKBMGDSmaa1SW3QwMuaL"),
    ],
    _sort("Strategy sorter", "Which strategy helps most with each word? Tap a strategy, then press Check.",
          ["Sounds", "Syllables", "Word parts", "Look-Say-Cover-Write-Check"],
          [("chimp", 0), ("strong", 0), ("fantastic", 1), ("adventure", 1), ("unhappy", 2), ("replaying", 2), ("careful", 2), ("said", 3), ("because", 3), ("friend", 3)]),
    [
        _wc("The prefix in 'rewrite' is ___.", ["re", "write", "rew"], 0, "Re- means again."),
        _wc("Careful means full of ___.", ["care", "fun", "fear"], 0, "The suffix -ful means full of."),
        _wc("Hopeless means ___ hope.", ["with", "without", "more"], 1, "The suffix -less means without."),
        _wc("Which word has a prefix that means 'not'?", ["unkind", "kindly", "kinder"], 0, "Un- means not."),
    ],
    [
        {"key": "words", "label": "My ten words", "hint": "Write the ten words you will practise."},
        {"key": "hardest", "label": "Hardest word", "hint": "Which word is the trickiest and which part is tricky?"},
        {"key": "strategy", "label": "Strategy plan", "hint": "Which strategy will you use for the hardest word and why?"},
    ],
    ["Counting letters instead of sounds (ship has three sounds).", "Guessing a spelling instead of choosing a strategy.", "Forgetting that a word can have both a prefix and a suffix.", "Skipping the Check step of Look, Say, Cover, Write, Check."],
    [{"title": "Word Wall", "description": "Make a word wall of 10 tricky words with the tricky part in a different colour.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Spelling Teacher", "description": "Teach a family member one strategy using three words and ask them to spell each one.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
)

L2 = build(
    "s2-eng-w01-l2-sentence-builder", "Sentence Builder: Punctuation Power",
    "The Sentence Bridge has holes in it! Use capital letters, end marks, commas and apostrophes to repair every plank and write your own sentences.",
    "Creating written texts: sentences and punctuation",
    ["EN2-CWT-01", "EN2-SPELL-01", "EN2-HANDW-01"],
    {"EN2-CWT-01": "Primary. Writes and punctuates complete sentences.",
     "EN2-SPELL-01": "Spells contractions correctly.",
     "EN2-HANDW-01": "Writes the final paragraph in legible joined handwriting."},
    "We are learning to write complete sentences and punctuate them correctly.",
    ["I can tell a complete sentence from a fragment.", "I can use capital letters and the right end mark.",
     "I can use commas in a list.", "I can use an apostrophe in a contraction."],
    ["sentence", "fragment", "capital letter", "comma", "apostrophe", "contraction", "proper noun"],
    ["Paper or notebook", "Pencil"], "Child can write several words in a line.",
    "A complete sentence has a subject (who or what) and a verb (what happened), and makes sense on its own. It starts with a capital letter and ends with a full stop, question mark or exclamation mark.\n\nCapital letters are also used for proper nouns: names of people, places, days and months. Commas separate three or more items in a list. An apostrophe in a contraction takes the place of missing letters.\n\nPunctuation is like road signs for a reader: it tells them when to stop, slow down and what tone to use. Without it, writing is hard to follow.",
    [
        _step("1", "Complete sentences", "A complete sentence needs a who or what and a doing word, and must make sense on its own. A fragment is a group of words that is missing one of those parts, so it leaves you waiting for more.\n\nTest it: read the words and ask, 'Who or what? What happened?' If you cannot answer both, it is a fragment.",
              "Complete: The girl ran home. Fragment: Under the table. Fragment: Because it was raining.",
              "A sentence starting with 'because' needs a second part, such as 'Because it was raining, we stayed inside.'",
              ("Which is a complete sentence?", ["Running down the hill.", "The girl ran home.", "Under the table."], 1, "It has a who and an action.")),
        _step("2", "Capitals and end marks", "Begin every sentence with a capital letter. Use a full stop for a statement, a question mark for a question and an exclamation mark for strong feeling or a command.\n\nAlso use capitals for proper nouns, such as Mia, Brisbane, Tuesday and April.",
              "Where did you put my hat? I found it under the bed. Watch out!",
              "The end mark matches the job of the sentence.",
              ("Which end mark fits: 'Where did you put my hat'?", [".", "?", "!"], 1, "It is a question.")),
        _step("3", "Commas in a list", "Use commas to separate three or more items in a list. The last two items are usually joined by 'and', with no comma before it.\n\nA comma also gives the reader a short pause, which helps long sentences make sense.",
              "We bought apples, pears and plums. Mia packed a hat, a towel, sunscreen and a drink.",
              "Commas separate; 'and' joins the last two.",
              ("Which is punctuated correctly?", ["We bought apples, pears and plums.", "We bought, apples pears, and plums."], 0, "Commas go between items.")),
        _step("4", "Apostrophes in contractions", "A contraction squashes two words into one. The apostrophe goes exactly where the letters were taken out.\n\nContractions make writing sound like speech, so use them in dialogue and friendly writing. Be careful: 'its' (belonging to it) has no apostrophe, but 'it's' means 'it is'.",
              "don't = do not. she's = she is. can't = cannot. we'll = we will.",
              "The apostrophe replaces the missing letters, not the space.",
              ("'can't' is short for which words?", ["can not", "cat not", "cant"], 0, "The apostrophe replaces 'no'.")),
    ],
    "Fix: 'last week mia and dan went to brisbane they packed a hat a towel and a drink' becomes 'Last week Mia and Dan went to Brisbane. They packed a hat, a towel and a drink.' Notice: capitals on Last, Mia, Dan, Brisbane and They; a full stop to split two ideas; commas in the list.",
    "Fix this: 'my sister cant swim but she loves the beach' (answer: My sister can't swim, but she loves the beach.) Then fix: 'we saw a seal a penguin and a whale at the zoo' and write one sentence of your own with a list and a contraction.",
    "Stage 1 (plan): choose a topic, a day at the beach or the bush, and list five things you would see or do.\nStage 2 (write): write a paragraph of six sentences. Include one question, one list with commas, two contractions and two proper nouns.\nStage 3 (proofread): tick each sentence for a capital, an end mark and sense.\nStage 4 (handwriting): copy it out in neat joined handwriting.",
    "Which punctuation mark was the hardest to remember, and what helped?",
    "Does every sentence start with a capital and end with a mark? Did I include a list, a question and two contractions?",
    [
        _q("Which is a complete sentence?", ["The boy kicked the ball.", "Over the fence.", "Running fast."], 0, "It says who and what happened."),
        _q("Which is written correctly?", ["My sister lives in Sydney.", "my sister lives in sydney.", "My sister lives in sydney."], 0, "Capitals for the start and the place."),
        _q("Which end mark fits: 'Are you coming to the park'?", [".", "?", "!"], 1, "It asks a question."),
        _q("What does the apostrophe in 'she's' show?", ["Missing letters (she is)", "A list", "A question"], 0, "she is becomes she's."),
        _q("Which list is correct?", ["I packed a hat, a towel and a drink.", "I packed, a hat a towel, and a drink."], 0, "Commas between items."),
        _q("'didn't' is short for:", ["did not", "did now", "didn"], 0, "The apostrophe replaces 'o'."),
        _q("Which is a fragment?", ["It was raining.", "Because it was raining.", "The rain fell."], 1, "It does not make sense on its own."),
        _q("Which has correct capitals?", ["Last week Mia and Dan went to Brisbane.", "last week mia and dan went to brisbane."], 0, "Capitals for the first word, names and places."),
        _q("Which end mark best fits a shouted warning: 'Watch out'?", ["!", "?", ","], 0, "A strong warning takes an exclamation mark."),
        _q("Which is correct?", ["We can't wait.", "We cant wait.", "We ca'nt wait."], 0, "The apostrophe replaces the o."),
    ],
    "Upload a photo of your six-sentence paragraph in joined handwriting.",
    "Write a seven-item list inside one sentence and explain where each comma goes.",
    [("sentence", "A group of words that makes sense on its own."), ("fragment", "A group of words missing a part of a sentence."),
     ("capital letter", "Used at the start of sentences and for names."), ("proper noun", "The name of a particular person, place or day."),
     ("comma", "Separates items in a list."), ("apostrophe", "Shows missing letters in a contraction."),
     ("contraction", "Two words squashed into one.")],
    [
        _video("Capital letters, commas and full stops", "2-ybEW_4Oyo",
               "Watch how capital letters, commas and full stops are used. Notice the three jobs of commas.",
               "Re-read the four steps above and punctuate a short paragraph from your book.",
               ("What does a full stop show?", ["The end of a sentence", "The start of a sentence", "A list"], 0, "A full stop marks the end of a sentence.")),
        _video("Capital letters and punctuation marks, including apostrophes", "5y7tlRn55uE",
               "Watch the parts on commas in lists and on apostrophes for contractions.",
               "Write ten contractions with their long forms, such as can't and cannot.",
               ("What do apostrophes do in contractions?", ["Take the place of missing letters", "Show a question", "Start a sentence"], 0, "They stand for the letters that were left out.")),
        _article("Punctuation and sentences for kids (playlist)", "https://www.youtube.com/playlist?list=PLXFdetbvRMow"),
    ],
    _sort("Punctuation sorter", "Which end mark does each sentence need? Tap one, then press Check.",
          ["Full stop", "Question mark", "Exclamation mark"],
          [("The cat sat on the mat", 0), ("We went to the park after school", 0), ("Where is my lunchbox", 1), ("Can you help me find my shoes", 1), ("What time does the bus leave", 1), ("Look out for the snake", 2), ("I won the race", 2), ("Help, the boat is sinking", 2)]),
    [
        _wc("Which contraction means 'we will'?", ["we'll", "were", "we'd"], 0, "we will becomes we'll."),
        _wc("Which contraction means 'could not'?", ["couldn't", "could'nt", "couldnt"], 0, "The apostrophe replaces the o."),
        _wc("Which needs a capital letter?", ["Tuesday", "morning", "lunch"], 0, "Days of the week are proper nouns."),
        _wc("Which is a fragment?", ["Over the bridge.", "We crossed the bridge.", "Dan ran."], 0, "It has no who or what and no action."),
    ],
    [
        {"key": "topic", "label": "My topic", "hint": "A day at the beach or the bush: where and when?"},
        {"key": "list", "label": "My list", "hint": "Five things you would see or do (these become your comma list)."},
        {"key": "question", "label": "My question", "hint": "Write one question a character could ask."},
    ],
    ["Starting a sentence without a capital or forgetting names.", "Using a comma before 'and' at the end of every list (not needed here).", "Writing 'cant' or 'dont' without the apostrophe.", "Joining two ideas without any end mark (a run-on sentence)."],
    [{"title": "Punctuation Hunt", "description": "Find five sentences in a book with different end marks. Copy them and explain why each mark was used.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Fix the Sign", "description": "Write a short letter with no punctuation, swap with a family member and see if they can add it.", "type": "create", "difficulty": "stretch", "evidence_type": "photo"}],
)

L3 = build(
    "s2-eng-w01-l3-reading-expression", "Voice of the Storyteller: Reading with Expression",
    "The lighthouse story needs a voice! Read aloud with accuracy, pace and expression so listeners feel every wave.",
    "Reading fluency and comprehension",
    ["EN2-REFLU-01", "EN2-RECOM-01", "EN2-OLC-01"],
    {"EN2-REFLU-01": "Primary. Practises accuracy, pace, phrasing and expression.",
     "EN2-RECOM-01": "Answers literal and inferential questions on a short passage.",
     "EN2-OLC-01": "Reads aloud to a listener and discusses how it sounded."},
    "We are learning to read aloud smoothly and with expression and to understand what we read.",
    ["I can read words accurately and fix mistakes.", "I can use punctuation to guide my voice.",
     "I can read in meaningful phrases.", "I can answer questions about what I read."],
    ["fluency", "expression", "phrasing", "pace", "punctuation", "infer"],
    ["A book or short text of his choice", "A device to record (optional)", "A listener"],
    "Child can read simple chapter-book text.",
    "Fluent reading has four parts: accuracy (reading the right words), pace (not too fast or slow), phrasing (reading in chunks that belong together) and expression (a voice that shows meaning and feeling).\n\nPunctuation tells your voice what to do: a comma is a short pause, a full stop is a longer pause, a question mark makes the voice rise, an exclamation mark adds strong feeling, and quotation marks signal a character speaking.\n\nFluent reading is not only about speed. Reading too fast makes it hard to understand, and reading word by word makes it hard to follow. The goal is to read the way you would speak, so your listener understands and enjoys the story.\n\nGood readers also understand what they read. Literal questions have answers stated in the text. Inference questions ask you to work something out from clues.",
    [
        _step("1", "Accuracy", "Read every word as printed. If a word does not make sense, stop, go back and fix it. This is called self-correcting, and strong readers do it all the time.\n\nWhen you meet a hard word, break it into syllables, look for word parts or read on to the end of the sentence for clues.",
              "Read 'quiet' not 'quite' when the sentence is about silence.",
              "Good readers check that it makes sense, sounds right and looks right.",
              ("A word you read does not make sense. What should you do?", ["Go back and re-read", "Keep going", "Skip the page"], 0, "Self-correcting is a strong reading habit.")),
        _step("2", "Pace and phrasing", "Pace is the speed of your reading, and a good pace sounds like talking. Phrasing means reading groups of words together, rather than one word at a time.\n\nLook for natural chunks: who did it, what they did, where or when. A small slash in your head can help you chunk the sentence.",
              "Every evening / Mr Bell climbed the steps / to the top of the lighthouse.",
              "Chunks follow the meaning.",
              ("What is phrasing?", ["Reading in meaningful chunks", "Reading as fast as possible", "Reading silently"], 0, "Phrasing groups words by meaning.")),
        _step("3", "Punctuation signals", "Commas, full stops, question marks and exclamation marks tell your voice when to pause, drop, rise or show feeling. Quotation marks tell you that a character is speaking, so change your voice.\n\nPunctuation is a set of reading instructions from the author. Follow them and you will sound like a storyteller.",
              "Where are you going? (voice rises) Run! (strong, urgent voice) He waited, listened, and then ran. (short pauses at commas)",
              "Pause at a comma, stop at a full stop.",
              ("What does your voice do at a question mark?", ["Rises", "Drops lower", "Stops completely"], 0, "Questions usually rise at the end.")),
        _step("4", "Expression", "Let your voice show feelings. Use loud and soft, fast and slow, high and low, to match the story. Whispering, shouting, excited and scared voices all help the listener picture the scene.\n\nBefore reading, ask: how does this character feel? How should my voice sound?",
              "Whispered: 'Be quiet, someone is coming.' Excited: 'We found it!'",
              "Match the voice to the meaning of the words.",
              ("Which words should be read softly?", ["'Whisper', she said", "'Look out!' he shouted"], 0, "Whispering matches a soft voice.")),
    ],
    "Passage: Every evening, Mr Bell climbed the 112 steps to the top of the lighthouse. He polished the great glass lens until it gleamed. Then he lit the lamp, and its beam swept across the dark water to warn the ships. Read it in three chunks, pausing at each comma and full stop. Literal question: how many steps did he climb? (112, stated.) Inference question: why does a lighthouse keeper polish the lens? (so the light shines brightly; the text hints with 'gleamed' and 'warn the ships'.)",
    "Read the passage aloud twice. First go for accuracy, then for expression. Then answer: why did Mr Bell light the lamp? Next, find one literal answer and one inference answer in the text.",
    "Stage 1 (choose): pick a page from your own book, about 100 words.\nStage 2 (read): read it aloud three times to a listener or record it.\nStage 3 (rate): after each read, rate your accuracy, pace and expression from 1 to 3.\nStage 4 (reflect): write two sentences on what improved, and write one literal and one inference question about your passage with the answers.",
    "Which of the four parts of fluency is your strongest, and which will you work on?",
    "Did I read three times, rate each, write two sentences on what improved, and write two questions?",
    [
        _q("What does a comma tell your voice to do?", ["Pause briefly", "Stop for a long time", "Shout"], 0, "A comma is a short pause."),
        _q("What does your voice do at a question mark?", ["Rises", "Falls", "Stays flat"], 0, "Questions usually rise."),
        _q("What is phrasing?", ["Reading in meaningful chunks", "Reading very fast", "Reading word by word"], 0, "Chunks follow meaning."),
        _q("Passage: 'Every evening, Mr Bell climbed the 112 steps to the top of the lighthouse.' How many steps did he climb?", ["12", "112", "211"], 1, "The text says 112 steps."),
        _q("Passage: 'He polished the great glass lens until it gleamed.' What does 'gleamed' suggest?", ["Shone brightly", "Broke", "Went dark"], 0, "To gleam is to shine."),
        _q("Passage: 'Then he lit the lamp, and its beam swept across the dark water to warn the ships.' Why did he light the lamp?", ["To warn ships", "To read a book", "To cook dinner"], 0, "The beam warns the ships."),
        _q("What happens first in the passage?", ["He climbs the steps", "He lights the lamp", "He polishes the lens"], 0, "He climbs, polishes, then lights the lamp."),
        _q("You read a word that makes no sense. What do you do?", ["Go back and fix it", "Ignore it", "Stop reading"], 0, "Self-correct."),
        _q("Which part of fluency is about your voice showing feeling?", ["Expression", "Accuracy", "Pace"], 0, "Expression is the feeling in your voice."),
        _q("What does an exclamation mark add?", ["Strong feeling", "A question", "A list"], 0, "It shows strong feeling or force."),
    ],
    "Upload a short recording or a photo of your rating table, your two sentences and your two questions.",
    "Read a poem aloud and plan where to pause, speed up and slow down.",
    [("fluency", "Reading smoothly and with understanding."), ("expression", "Using your voice to show meaning and feeling."),
     ("phrasing", "Reading in meaningful chunks."), ("pace", "The speed of your reading."),
     ("punctuation", "Marks that guide pauses and voice."), ("infer", "Work out something using clues in the text.")],
    [
        _video("Punctuation Celebration (read aloud)", "RgGrNL82r4I",
               "Listen to how the reader's voice changes with punctuation. Notice the pauses, the rises and the feeling.",
               "Read a page aloud and mark each comma with a short pause and each question mark with a rise.",
               ("Which part of fluency is shown when a reader's voice changes with the meaning?", ["Expression", "Spelling", "Handwriting"], 0, "Expression shows meaning through the voice.")),
        _video("Punctuation and grammar for kids (read aloud)", "2zNAQW5jPwI",
               "Listen to the read-aloud and notice how the narrator treats each punctuation mark.",
               "Choose a short text and read it with a pause at every punctuation mark.",
               ("What should a reader do at a full stop?", ["Pause and let the idea finish", "Speed up", "Skip it"], 0, "A full stop is a longer pause.")),
        _article("Fluency practice: reading with expression (Reading Universe)", "https://readinguniverse.org/resources/video/fluency/fluency-practice-reading-with-expression"),
    ],
    _sort("Voice sorter", "How should your voice sound for each line? Tap one, then press Check.",
          ["Soft and slow", "Loud and fast", "Rising (a question)"],
          [("'Be quiet, the baby is sleeping,' she whispered.", 0), ("The candle flickered in the dark, silent room.", 0), ("'Run! The tide is coming in!'", 1), ("'We won! We actually won!'", 1), ("'Where did you hide the key?'", 2), ("'Are you coming to the beach with us?'", 2)]),
    [
        _wc("The wind howled and the sea ___ against the cliff.", ["crashed", "sat", "smiled"], 0, "Crashed paints a strong sound picture."),
        _wc("A reader who skips punctuation will ___.", ["miss the pauses and feeling", "read faster and better", "learn spelling"], 0, "Punctuation guides pauses and feeling."),
        _wc("If someone 'murmured', their voice was ___.", ["quiet and low", "loud", "high and squeaky"], 0, "Murmured means spoke quietly."),
        _wc("To 'infer' means to ___.", ["work out using clues", "copy a word", "read quickly"], 0, "Infer means working something out from clues."),
    ],
    [
        {"key": "book", "label": "My book", "hint": "Title and the page you chose."},
        {"key": "goal", "label": "My fluency goal", "hint": "Which of accuracy, pace, phrasing or expression will you work on?"},
    ],
    ["Reading so fast the meaning is lost.", "Reading word by word with no chunks.", "Ignoring punctuation marks when reading aloud.", "Not stopping to fix a word that does not make sense."],
    [{"title": "Radio Voice", "description": "Record yourself reading a page like a radio announcer. Share it with a family member and ask which part sounded best.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"},
     {"title": "Character Voices", "description": "Read a scene from a book giving each character a different voice. Write how you chose each voice.", "type": "create", "difficulty": "stretch", "evidence_type": "audio"}],
)

L4 = build(
    "s2-eng-w01-l4-show-dont-tell", "Paint with Words: Show, Don't Tell",
    "A blank page is waiting! Use senses, strong verbs and precise noun groups to paint a place so clearly that your reader steps inside.",
    "Creating written texts: imaginative description",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01", "EN2-HANDW-01"],
    {"EN2-CWT-01": "Primary. Plans, writes and revises an imaginative description of a place.",
     "EN2-VOCAB-01": "Chooses precise Tier 2 words including strong verbs.",
     "EN2-SPELL-01": "Proofreads and corrects spelling using strategies.",
     "EN2-HANDW-01": "Writes the final copy in neat joined handwriting."},
    "We are learning to show feelings and places with precise words instead of telling.",
    ["I can show a feeling rather than name it.", "I can use at least three senses.", "I can use strong verbs.", "I can build a precise noun group."],
    ["show, don't tell", "senses", "strong verb", "noun group", "precise", "atmosphere"],
    ["Paper or notebook", "Pencil", "Coloured pencils"], "Child can write several connected sentences.",
    "Telling names a feeling or fact: 'She was scared.' Showing lets the reader work it out: 'Her hands trembled and she held her breath.' Showing is more interesting because the reader does some of the thinking.\n\nWriters use four tools. First, body language and actions (trembled, clenched). Second, the five senses: sight, sound, smell, taste and touch. Third, strong verbs, which say more than a plain verb plus an adverb (trudged, not walked slowly). Fourth, noun groups with precise describing words (the rusty, creaking gate).\n\nYou do not need to show everything. Tell the simple facts, such as time and place, and show the moments that matter. Revising is where you find the telling and change it to showing.",
    [
        _step("1", "Show, don't tell", "Instead of naming a feeling, describe what the body does, what the character thinks or what they notice. Readers can work out the feeling for themselves, which makes the writing more powerful.\n\nTry this: take the word 'nervous' and ask, what does a nervous person do? They fidget, sweat, stammer or check the clock.",
              "Tell: He was nervous. Show: He wiped his sweaty palms on his shorts and checked the clock again.",
              "Never write the feeling word, and the reader still knows.",
              ("Which sentence shows rather than tells?", ["She was happy.", "She grinned and skipped down the path."], 1, "It shows actions.")),
        _step("2", "Use the senses", "Describe what you see, hear, smell, taste and feel. Using three or more senses helps the reader step inside the scene.\n\nSound and smell are often forgotten, but they make a place feel real.",
              "The salty smell of the sea drifted over the rocks, and waves hissed on the sand.",
              "Pick at least three senses.",
              ("Which sense is used: 'the salty smell of the sea'?", ["Sight", "Smell", "Hearing"], 1, "Smell.")),
        _step("3", "Strong verbs", "A strong verb carries more meaning than a plain verb plus an adverb. One strong verb is shorter and clearer than two weak words.\n\nBuild a collection: trudged, dashed, tiptoed, stomped, drifted, whispered, bellowed.",
              "walked slowly and heavily becomes trudged. said quietly becomes whispered. ran quickly becomes sprinted.",
              "Ask: is there one word that says it better?",
              ("Which verb means to walk slowly and heavily?", ["skipped", "trudged", "dashed"], 1, "Trudged.")),
        _step("4", "Precise noun groups", "A noun group is a noun with describing words around it. Add adjectives and details before the noun, or after it, to be precise.\n\nUse words that paint exact pictures instead of vague ones like nice, big or good.",
              "the rusty, creaking gate. a cold, silent darkness. the enormous, moss-covered rock.",
              "Precise describing words help the reader picture it exactly.",
              ("Which noun group is most precise?", ["a gate", "the gate", "the rusty, creaking gate"], 2, "It gives two details.")),
    ],
    "Plain: The old house was scary. Better: A cold draught whistled through the broken window, and the staircase groaned as Ella crept upward. Notice: no feeling word, three senses (touch, sound, sight), strong verbs (whistled, groaned, crept) and noun groups (a cold draught, the broken window).",
    "Rewrite 'The forest was quiet and dark' using two senses and one strong verb. Then change 'She was angry' into a showing sentence without using the word angry. Check that your sentences use precise words.",
    "Stage 1 (plan): choose a place at night, such as a beach, the bush, a haunted house or a city street, and fill in the planner.\nStage 2 (write): write 8 to 10 sentences describing it. Use at least three senses, two strong verbs and two precise noun groups. Show one feeling without naming it.\nStage 3 (proofread): use your spelling strategies, then check capitals and end marks.\nStage 4 (handwriting): copy it out in neat joined handwriting.",
    "Which sentence are you proudest of, and which technique did it use?",
    "Did I use three senses, two strong verbs and two precise noun groups? Did I show a feeling without naming it?",
    [
        _q("Which sentence shows rather than tells?", ["Her hands trembled and she held her breath.", "She was scared."], 0, "It shows actions and body language."),
        _q("Which sense: 'the salty smell of the sea'?", ["Smell", "Hearing", "Sight"], 0, "Smell."),
        _q("Which strong verb means to walk slowly and heavily?", ["trudged", "skipped", "dashed"], 0, "Trudged."),
        _q("Which noun group is most precise?", ["the rusty, creaking gate", "the gate", "a gate"], 0, "More detail."),
        _q("Which sentence uses sound?", ["The floorboards groaned under his feet.", "The floor was brown."], 0, "Groaned is a sound."),
        _q("'His face went red and he stared at the floor' shows which feeling?", ["Embarrassed", "Excited", "Sleepy"], 0, "The actions show embarrassment."),
        _q("Which word is a strong verb for 'said quietly'?", ["whispered", "talked", "spoke"], 0, "Whispered."),
        _q("Why do writers describe a setting?", ["To help readers picture and feel it", "To make the story longer", "To fill the page"], 0, "Description builds a picture."),
        _q("Which is 'telling'?", ["He was angry.", "He slammed the door and clenched his fists."], 0, "Telling names the feeling."),
        _q("Which replaces 'ran quickly'?", ["sprinted", "ran", "went"], 0, "Sprinted."),
    ],
    "Upload a photo of your final description in joined handwriting. Highlight the senses and strong verbs.",
    "Write the same place in the morning and compare the atmosphere.",
    [("show, don't tell", "Describe actions and details instead of naming a feeling."), ("senses", "Sight, sound, smell, taste and touch."),
     ("strong verb", "A verb with a precise meaning, like trudged."), ("noun group", "A noun with describing words, like the rusty gate."),
     ("precise", "Exact and clear."), ("atmosphere", "The feeling a writer creates in a scene.")],
    [
        _video("Show, Don't Tell (author Victoria J. Coe)", "WYAg1FU-zHQ",
               "A children's author explains show, don't tell. Listen for how she shows a brave or nervous character.",
               "Re-read the worked example and underline the actions that show the feeling.",
               ("What does 'show, don't tell' ask a writer to do?", ["Show what is happening instead of just stating it", "Write shorter sentences", "Use more adjectives only"], 0, "Show events and feelings through actions and details.")),
        _video("Using writing tools to add description (powerful verbs, sensory language)", "9VC2BRog7KI",
               "Watch how adjectives, powerful verbs and sensory language make golden sentences.",
               "Write five plain sentences and upgrade each with a strong verb and a sense.",
               ("Why do writers use powerful (strong) verbs?", ["They give a clearer, more vivid picture", "They make the sentence shorter", "They replace punctuation"], 0, "Strong verbs say more with fewer words.")),
        _article("Show, Don't Tell writing technique (EasyTeaching)", "https://www.youtube.com/watch?v=-U1pBoBOj9w"),
    ],
    _sort("Show or tell?", "Is each sentence showing or telling? Tap one, then press Check.",
          ["Telling", "Showing"],
          [("The boy was nervous.", 0), ("She was very sad.", 0), ("The cave was scary.", 0), ("He was angry with his brother.", 0),
           ("The boy wiped his sweaty palms and checked the clock again.", 1), ("Tears slid down her cheeks as she hugged the empty box.", 1),
           ("A cold, silent darkness swallowed the cave.", 1), ("He slammed the door and clenched his fists.", 1)]),
    [
        _wc("The mouse ___ across the kitchen floor on tiny feet.", ["scurried", "went", "moved"], 0, "Scurried is a precise, strong verb."),
        _wc("The old floorboards ___ under his feet.", ["groaned", "were", "stayed"], 0, "Groaned adds a sound."),
        _wc("Which is the most precise noun group?", ["the crumbling, moss-covered wall", "a wall", "the wall"], 0, "It adds detail."),
        _wc("Which sentence uses touch?", ["The sand was cool and damp between my toes.", "The sand was there.", "I saw sand."], 0, "Cool and damp describe touch."),
    ],
    [
        {"key": "place", "label": "My place", "hint": "Where is it and what time is it?"},
        {"key": "senses", "label": "My senses", "hint": "Write one detail for each of three senses."},
        {"key": "verbs", "label": "Strong verbs", "hint": "List two strong verbs you will use."},
        {"key": "feeling", "label": "Feeling to show", "hint": "What feeling will you show without naming it, and how?"},
    ],
    ["Naming the feeling instead of showing it (writing 'she was scared').", "Using only sight and forgetting sound, smell and touch.", "Using a plain verb plus an adverb instead of one strong verb.", "Using vague words like nice, big or good."],
    [{"title": "Telling to Showing", "description": "Take five 'telling' sentences from your own writing and rewrite each as a 'showing' sentence.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Sense Walk", "description": "Sit outside for five minutes and write one detail for each of the five senses. Turn them into three sentences.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
)

WEEK_1 = [L1, L2, L3, L4]


def _set_library_version(version=13):
    for name, mod in list(sys.modules.items()):
        if name.split(".")[-1] == "lesson_library" and hasattr(mod, "LESSON_LIBRARY_VERSION"):
            if mod.LESSON_LIBRARY_VERSION < version:
                mod.LESSON_LIBRARY_VERSION = version


_set_library_version()
