"""Stage 2 English, Block B (poetry and word play), week 10, lessons 1 to 4.
Pass 1 (writing pass): four lessons at full depth, taught from scratch. Videos and links are attached in pass 2 (lesson_library_s2_english_b_wk10_pass2).
Registered in lesson_library.py. Keys use the prefix b10. Poems for reading are chosen by the parent; the example lines here are original."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

B10L1 = build(
    "s2-eng-b10-l1-imagery-and-the-senses", "Imagery and the Senses",
    "Learn how poets use the five senses to paint pictures in a reader's mind, and use sensory detail in your own writing.",
    "Reading: imagery and the senses",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-CWT-01", "EN2-OLC-01"],
    {"EN2-RECOM-01": "Primary. Identifies imagery in a poem, names the sense it appeals to and explains its effect.",
     "EN2-VOCAB-01": "Learns imagery, sense, sensory detail, visual, specific and vivid.",
     "EN2-CWT-01": "Writes a short poem using sensory detail drawn from a planned place.",
     "EN2-OLC-01": "Listens to and reads sensory lines aloud, noticing the pictures they make."},
    "We are learning how poets use the five senses to make a reader see, hear, smell, taste and feel a moment.",
    ["I can explain what imagery is.", "I can name the five senses a poet can use.", "I can tell a general line from a specific, vivid one.", "I can find imagery in a line and name its sense.", "I can write a short poem with at least four senses."],
    ["imagery", "sense", "sensory detail", "visual", "specific", "vivid"],
    ["Paper or notebook", "Pencil", "Coloured pencils", "A poem chosen by your parent"],
    "Child has met imagery briefly while writing a rhyming poem. This lesson teaches it properly, sense by sense.",
    "Close your eyes and think about a bakery in the morning. What do you notice? Perhaps the warm smell of bread, the clink of a till, the soft crust under your fingers.\n\nYou did not see any of that. Your mind made it from the idea. A poet can do the same thing to a reader using only words. When words make a picture, a sound, a smell, a taste or a feeling appear in your mind, that is called IMAGERY.\n\nIn this lesson you will learn the five senses a poet can use, how to tell a dull line from a vivid one, how to spot imagery in a poem and explain what it does, and how to plan and write your own sensory poem.",
    [
        _step("1", "What imagery is",
              "IMAGERY is language that helps a reader sense something in their imagination. The word has 'image' inside it, which means picture, but imagery is not only about pictures. It can be about sounds, smells, tastes and touch too.\n\nPoets use imagery because a poem is short. A poet cannot spend three pages describing a beach. Instead, a few well-chosen words must make you feel you are standing on it.\n\nCompare:\nGeneral: 'The kitchen was nice.'\nImagery: 'The kitchen smelt of toast and warm butter, and the window was fogged with steam.'\n\nThe first line tells you an opinion. The second line lets you step inside the room. You can smell it and almost see it. That is the difference imagery makes.\n\nRemember: imagery SHOWS the reader the moment instead of just telling them what to think about it.",
              "General: 'The park was busy.' Imagery: 'Scooters rattled past the swings while a dog barked at the pigeons.'",
              "Imagery is language that makes the reader see, hear, smell, taste or feel something in their mind.",
              ("Imagery is language that...", ["makes the reader sense something in their mind", "always rhymes", "counts syllables"], 0, "Imagery creates sensory pictures in the reader's imagination.")),
        _step("2", "The five senses",
              "A poet can use five senses. Each one is a different door into the reader's mind.\n\nSIGHT (visual imagery): what we see. Colours, shapes, sizes, light, movement. 'A crooked yellow moon hung over the roofs.'\n\nSOUND: what we hear. Loud and soft sounds, voices, music, silence. 'The gate groaned, then slammed.'\n\nSMELL: what we can smell. Food, flowers, smoke, rain on dry ground. 'The air smelt of cut grass and petrol.'\n\nTASTE: what we taste. Sweet, sour, salty, bitter, spicy. 'The lemon was so sour it made my eyes squeeze shut.'\n\nTOUCH: what we feel on our skin. Hot, cold, rough, smooth, soft, sticky, wet. 'The wet sand was cold and gritty between my toes.'\n\nMost poems use only two or three senses. Sight is used the most, so a poem that includes smell, sound or touch often feels fresh and surprising.",
              "Sight: bright. Sound: hum. Smell: smoky. Taste: salty. Touch: prickly.",
              "There are five senses: sight, sound, smell, taste and touch.",
              ("Which line uses the sense of touch?", ["The blanket was rough and scratchy against my chin.", "The siren wailed down the street.", "The soup smelt of garlic."], 0, "Rough and scratchy describe how something feels on the skin.")),
        _step("3", "General words and specific words",
              "Imagery works best when the words are SPECIFIC. A specific word names exactly what something is. A general word could mean many things.\n\nGeneral: bird. Specific: magpie.\nGeneral: tree. Specific: gnarled gum tree.\nGeneral: walked. Specific: trudged.\nGeneral: noise. Specific: clatter.\n\nA VIVID line is one that is full of life and easy to picture. You make a line vivid by choosing specific nouns, strong verbs and exact describing words.\n\nWeak: 'A bird made a noise in the tree.'\nVivid: 'A magpie warbled in the gnarled gum.'\n\nNotice that the vivid line is not much longer. It is just more exact. Try this when you write: find your most general word and ask, 'What exactly is it?' Then swap it for a more precise word.\n\nBe careful not to pile on too many describing words. One strong image works better than five weak ones.",
              "Swap: 'The animal ran' becomes 'The kelpie bolted'. 'Food' becomes 'warm sausage rolls'.",
              "Choose specific, exact words to make a line vivid.",
              ("Which is the most specific?", ["kelpie", "dog", "animal"], 0, "Kelpie names a particular breed, so it paints a clearer picture.")),
        _step("4", "Finding imagery in a poem",
              "When you read a poem, you can hunt for imagery in three moves.\n\n1. Find the line that makes a picture, sound, smell, taste or feeling appear in your mind.\n2. Name the sense it uses.\n3. Explain the effect: what does it make you feel or understand?\n\nExample line: 'The night air was thick with the smell of frying onions.'\nSense: smell.\nEffect: it tells us the street is full of cooking and makes the scene feel warm, crowded and real.\n\nNotice that the effect sentence says more than 'it sounds nice'. It names what the reader pictures and feels. Use words such as 'makes me feel', 'helps me picture' or 'shows that'.\n\nSome lines use more than one sense at once: 'The warm, golden crust crackled as I broke it.' Warm and golden are sight and touch. Crackled is sound. You can name them all.\n\nWhen you read aloud, slow down at lines that have a lot of imagery. They are the parts the poet wants you to notice.",
              "Line: 'Cold rain needled my cheeks.' Sense: touch. Effect: it shows the rain is sharp and uncomfortable.",
              "Find the line, name the sense, explain the effect.",
              ("An effect sentence should say...", ["what the reader pictures or feels", "only the name of the sense", "how many words are in the line"], 0, "Effect explains what the imagery does for the reader.")),
        _step("5", "Planning a sensory poem",
              "Before writing, plan with a SENSE CHART. First choose a place you can picture clearly: a beach, a market, a kitchen at dinnertime, a bus stop in the rain, a campsite at night.\n\nDraw a chart with five boxes and write specific words in each:\n\nPlace: campsite at night\nSight: orange embers, black tree shapes, a torch beam\nSound: crackling fire, a distant owl, a zip being pulled\nSmell: woodsmoke, damp canvas, toasted marshmallow\nTaste: sweet, sticky marshmallow, hot chocolate\nTouch: warm hands, cold nose, scratchy sleeping bag\n\nYou do not have to use every box. Choose the three or four best images, the ones that are most surprising or most exact.\n\nPlaces you have really been work best, because real details are easier to find. If you cannot remember a smell, think of the most likely one and test it: would someone really smell this here?",
              "Place: kitchen at dinnertime. Smell: sizzling garlic. Sound: clattering pots. Touch: hot steam.",
              "Plan with a sense chart before you write.",
              ("What should you do first when planning a sensory poem?", ["Choose a place you can picture clearly", "Write the title in capitals", "Count the syllables"], 0, "A clear place gives you real details for each sense.")),
        _step("6", "Write your sensory poem",
              "Now write a poem of six to ten lines. It does not have to rhyme. Use this order.\n\n1. Choose a place and make a sense chart.\n2. Choose at least four senses.\n3. Write one or two lines for each sense, using specific words and strong verbs.\n4. Read the poem aloud. Slow down at the best images.\n5. Replace any general word with a more exact one.\n6. Give it a title and write a neat copy.\n7. Underline each image and label the sense in the margin.\n\nModel poem:\nCampfire\nOrange embers blink in the dark.\nA log cracks and spits a spark.\nWoodsmoke curls into my hair.\nMy marshmallow bubbles, sticky and sweet,\nand the cold creeps up through my feet.\n\nYour poem should paint your own place. It does not need to copy the model, and the best lines are the ones that only you could write.",
              "Check: 'Woodsmoke curls into my hair' uses smell. 'Orange embers blink' uses sight.",
              "Plan, write, read aloud, then label the senses.",
              ("What should you do at the end of your poem?", ["Label the sense used in each image", "Cross out all the images", "Skip the title"], 0, "Labelling shows you have used different senses on purpose.")),
    ],
    "Model answers. Imagery is language that makes the reader see, hear, smell, taste or feel something in their mind. The five senses are sight, sound, smell, taste and touch. Specific words (magpie, trudged, clatter) are more vivid than general ones (bird, walked, noise). To analyse imagery: find the line, name the sense, explain the effect. Plan with a sense chart for a place you can picture. Model poem: 'Orange embers blink in the dark. / A log cracks and spits a spark. / Woodsmoke curls into my hair. / My marshmallow bubbles, sticky and sweet, / and the cold creeps up through my feet.' It uses sight, sound, smell, taste and touch.",
    "1) Name the sense in ten lines. 2) Sort twelve phrases by sense. 3) Turn six general words into specific words. 4) Make a sense chart for two places. 5) Pick a poem chosen by your parent, find three images, name each sense and explain the effect. 6) Write and label a six to ten line sensory poem.",
    "Upload a photo of your sense chart and your labelled sensory poem.",
    CHECK,
    "Did I choose a place I can picture? Did I make a sense chart? Does my poem use at least four senses? Did I use specific words? Did I read it aloud? Did I label the senses? Does it have a title?",
    [
        _q("Imagery is...", ["language that helps the reader sense something in their mind", "a pattern of rhyming words", "the title of a poem"], 0, "Imagery makes a reader see, hear, smell, taste or feel."),
        _q("How many senses can a poet use?", ["five", "three", "ten"], 0, "Sight, sound, smell, taste and touch."),
        _q("Which line uses the sense of smell?", ["The air smelt of rain on hot bitumen.", "The door slammed shut.", "The sand was rough and cool."], 0, "Smelt of rain on hot bitumen appeals to smell."),
        _q("Which word is the most specific?", ["trudged", "went", "moved"], 0, "Trudged shows how the person walked."),
        _q("Which sentence best explains an effect?", ["It makes me picture a cold, windy beach.", "It is a good line.", "It has seven words."], 0, "An effect names what the reader pictures or feels."),
        _q("Why is a sense chart useful?", ["It collects exact details before you write", "It checks your spelling", "It counts the syllables"], 0, "Planning gives you strong images to choose from."),
        _q("A vivid line is...", ["full of life and easy to picture", "always very long", "written in capital letters"], 0, "Vivid means clear and full of life."),
        _q("'The wet sand was cold and gritty' appeals mostly to which sense?", ["touch", "taste", "smell"], 0, "Cold and gritty describe how sand feels on the skin."),
    ],
    "Upload a photo of your sense chart and sensory poem.",
    "With a parent, sit somewhere new for two minutes and write one specific detail for each of the five senses.",
    [("imagery", "Language that helps the reader see, hear, smell, taste or feel something in their mind."), ("sense", "One of the ways we notice the world: sight, sound, smell, taste and touch."), ("sensory detail", "A detail that appeals to one of the senses."), ("visual", "To do with seeing."), ("specific", "Exact and precise, not general."), ("vivid", "Full of life and easy to picture.")],
    [],
    _sort("Which sense?", "Which sense does each phrase use? Tap a group, then Check.",
          ["Sight", "Sound", "Smell", "Taste", "Touch"],
          [("golden light on the wall", 0), ("leaves crunching underfoot", 1), ("the scent of fresh bread", 2), ("sour lemon juice", 3), ("rough bark scratching my palm", 4), ("a gleaming silver spoon", 0), ("a whispering breeze", 1), ("smoky campfire air", 2), ("sweet, sticky honey", 3), ("icy water on my toes", 4)]),
    [
        _wc("Language that makes pictures in the mind is ___.", ["imagery", "imagry", "imagerie"], 0, "Imagery ends -ery."),
        _wc("Sight, sound, smell, taste and touch are the five ___.", ["senses", "sences", "sensus"], 0, "Senses ends -ses."),
        _wc("Exact and precise means ___.", ["specific", "specifick", "pacific"], 0, "Specific begins spec."),
        _wc("Full of life and easy to picture means ___.", ["vivid", "vivvid", "vived"], 0, "Vivid has two v letters and one d."),
        _wc("Which is spelt correctly?", ["sensory", "sensary", "sensery"], 0, "Sensory ends -ory."),
    ],
    [
        {"key": "chart", "label": "Sense chart", "hint": "A place and specific words for each sense."},
        {"key": "senses", "label": "Four senses", "hint": "At least four senses used in the poem."},
        {"key": "specific", "label": "Specific words", "hint": "General words swapped for exact ones."},
        {"key": "label", "label": "Labelled poem", "hint": "Images underlined and senses named."},
    ],
    ["Thinking imagery only means pictures.", "Using general words such as nice, good and big.", "Listing the senses without showing a real place.", "Piling on too many describing words in one line.", "Writing 'it sounds good' instead of explaining the effect."],
    [{"title": "Five Senses Walk", "description": "Go for a walk with a family member and write one line for each sense. Turn your five lines into a short poem.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that the sense chart gives specific details for a real place, the poem uses at least four senses, general words have been replaced with exact ones, and each image is labelled with the correct sense. Sorter: Sight: golden light on the wall; a gleaming silver spoon. Sound: leaves crunching underfoot; a whispering breeze. Smell: the scent of fresh bread; smoky campfire air. Taste: sour lemon juice; sweet, sticky honey. Touch: rough bark scratching my palm; icy water on my toes.",
)

B10L2 = build(
    "s2-eng-b10-l2-free-verse-and-haiku", "Free Verse and Haiku",
    "Learn that poems do not have to rhyme, how line breaks shape free verse, and how to write a haiku by counting syllables.",
    "Writing: free verse and haiku",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01", "EN2-OLC-01"],
    {"EN2-CWT-01": "Primary. Plans, drafts and revises a free verse poem and a haiku, using line breaks and syllable counts for effect.",
     "EN2-RECOM-01": "Identifies free verse and haiku and explains how their forms differ from rhyming poems.",
     "EN2-VOCAB-01": "Learns free verse, line break, haiku, syllable, form and concise.",
     "EN2-OLC-01": "Reads free verse aloud, pausing at line breaks."},
    "We are learning how free verse and haiku work and how to write one of each.",
    ["I can explain what free verse is.", "I can choose where to break a line and say why.", "I can explain what a haiku is.", "I can count syllables to write a 5-7-5 haiku.", "I can write one free verse poem and two haiku."],
    ["free verse", "line break", "haiku", "syllable", "form", "concise"],
    ["Paper or notebook", "Pencil", "A free verse poem or haiku chosen by your parent"],
    "Child has learned rhyme, rhythm, syllables and imagery. This lesson uses them in two forms that do not rely on rhyme.",
    "So far, many of the poems you have studied rhymed and kept a steady beat. That is one way to build a poem, but not the only way.\n\nFree verse is a kind of poem with no regular rhyme and no regular beat. The poet decides the length of every line. A haiku is the opposite kind of challenge: a tiny poem with strict rules about its syllables.\n\nIn this lesson you will learn how each form works, why line breaks matter so much, how to count syllables to build a haiku, and how to write one free verse poem and two haiku of your own.",
    [
        _step("1", "What free verse is",
              "FREE VERSE is poetry that does not follow a set rhyme scheme or a regular rhythm. The poet is 'free' to decide how long each line is, how many lines there are, and where the pauses fall.\n\nFree verse is still poetry, not just a paragraph cut into pieces. A good free verse poem is full of careful choices: strong images, exact words and lines that are broken in the right places.\n\nExample:\nThe bus stops.\nDoors sigh open.\nA tired man steps out\ninto the rain.\n\nThere is no rhyme and the lines are different lengths. But every line has a job. 'The bus stops.' is short and sudden. 'into the rain' sits alone to leave the reader with a picture.\n\nFree verse is a good form when you want to describe a real moment simply and clearly, without bending your words to fit a rhyme.",
              "Not free verse: a paragraph that is just chopped up. Free verse: lines chosen on purpose for effect.",
              "Free verse has no set rhyme or beat, but every line is a careful choice.",
              ("Free verse is a poem that...", ["has no set rhyme scheme or regular rhythm", "must have four lines", "must rhyme in pairs"], 0, "The poet chooses the shape of free verse.")),
        _step("2", "Line breaks",
              "A LINE BREAK is where one line ends and the next begins. In free verse, line breaks are the poet's main tool because there is no rhyme to mark the ends of lines.\n\nA line break makes the reader pause, even for a tiny moment. You can use this to:\n- put a strong word at the end of a line so it stands out,\n- slow the reader down on a quiet or important moment,\n- make a very short line for a sudden event,\n- split a long thought into small pictures.\n\nCompare:\nProse: The wind blew the washing off the line and it landed in the mud.\n\nFree verse:\nThe wind snatched\nthe washing\noff the line\nand dropped it\nin the mud.\n\nIn the poem, 'snatched' stands out at the end of the first line, and 'in the mud' lands with a thump at the end.\n\nTo test your line breaks, read the poem aloud and pause at the end of each line. If a pause feels strange or weakens the line, try a different break.",
              "Break test: 'I walked slowly / through the quiet / empty hall.' Each break holds a small picture.",
              "Break lines so strong words stand out and pauses feel right.",
              ("Why are line breaks important in free verse?", ["They control pauses and show which words matter", "They make the poem rhyme", "They count syllables"], 0, "Line breaks shape how the poem is read and heard.")),
        _step("3", "Writing free verse",
              "Free verse is easiest to write about one small moment. Follow these steps.\n\n1. Choose one moment: stepping off a bus, finding a shell, a dog shaking itself dry.\n2. Write what you see, hear and feel in plain sentences. Use specific words.\n3. Cut every word that does not help the picture, such as very, really, just and a lot.\n4. Break your sentences into lines. Put your best word at the end of a line.\n5. Read it aloud and adjust the breaks until the pauses feel right.\n6. Add a title that gives a small clue but does not explain the poem.\n\nDraft sentence: 'The dog came out of the water and shook itself and the water went everywhere.'\nCut and break:\nThe dog bounds from the sea,\nshakes,\nand the whole beach\nis raining.\n\nNotice how 'shakes,' sits alone on its own line, so the reader feels the shake. You can also make a free verse poem tell a tiny story in just a few lines.",
              "Cut: 'The very big wave really crashed' becomes 'The wave crashed'.",
              "Choose one moment, cut extra words, then break lines for effect.",
              ("What should you cut when you tighten a free verse draft?", ["Words that do not help the picture", "Every verb", "The title"], 0, "Short, exact poems need no filler.")),
        _step("4", "What a haiku is",
              "A HAIKU is a tiny poem that began in Japan hundreds of years ago. A haiku is built from three lines. In English, we usually follow a 5-7-5 pattern of SYLLABLES.\n\nLine 1: 5 syllables\nLine 2: 7 syllables\nLine 3: 5 syllables\n\nThat makes seventeen syllables in total. A haiku does not usually rhyme.\n\nTraditional haiku are about nature and capture one moment, in the present tense, as if it is happening right now. They often show a tiny change or surprise in the last line.\n\nExample:\nRain taps on the roof,\npuddles gather in the lane,\na frog starts to sing.\n\nCount line 2: pud-dles (2) gath-er (2) in (1) the (1) lane (1) = 7.\n\nNote: Japanese haiku count sounds in a different way, so the 5-7-5 pattern in English is a guide, and some English poets bend it. In this lesson we will use 5-7-5 so you can practise counting.",
              "Haiku: 'Morning mist lifts slow, / a spider's silver necklace / glitters on the fence.' It is 5-7-5.",
              "A haiku has three lines of 5, 7 and 5 syllables and shows one moment.",
              ("A haiku in English usually has...", ["three lines of 5, 7 and 5 syllables", "four rhyming lines", "ten lines"], 0, "The 5-7-5 pattern is the usual guide.")),
        _step("5", "Counting and fitting syllables",
              "To write a haiku you must count syllables carefully. Say each word aloud and clap or tap each beat.\n\nrain (1), puddle (2), frog (1), glitters (2), morning (2), spider's (2), silver (2), necklace (2), blossom (2), butterfly (3).\n\nHow to build a haiku:\n1. Choose a nature moment: a cat in the sun, a storm, a leaf falling.\n2. Write what you notice in plain words.\n3. Count each line on your fingers.\n4. If a line is too long, swap a long word for a short one or cut a word.\n5. If a line is too short, add a describing word or use a longer word.\n6. Read it aloud. The last line should feel like a small surprise or a quiet ending.\n\nExample fix:\nToo long: 'The very small kitten is sleeping in the sun.' (11 syllables)\nFixed to 5: 'Kitten naps in sun.'\nCount: Kit-ten (2) naps (3) in (4) sun (5). Yes, five.\n\nAlways count by sound, not by letters.",
              "Count: 'Frost on the window' = Frost (1) on (2) the (3) win (4) dow (5) = 5.",
              "Count with your fingers, then swap words to fit.",
              ("How many syllables are in 'butterfly'?", ["3", "2", "4"], 0, "But-ter-fly has three beats.")),
        _step("6", "Write free verse and haiku",
              "Now write three poems.\n\nPoem 1: a free verse poem of six to ten lines about one small moment. Cut extra words, use strong images and choose your line breaks on purpose.\n\nPoems 2 and 3: two haiku about nature, each with 5-7-5 syllables. Count them on your fingers and write the count beside each line.\n\nModel free verse:\nBus Stop\nCold metal bench.\nMy breath\nis a small cloud\nthat vanishes.\nA horn somewhere,\nthe hiss of brakes,\nand the number 12\nswings round the corner,\nbright as a lit window.\n\nModel haiku:\nMorning mist lifts slow,\na spider's silver necklace\nglitters on the fence.\n\nRead all three poems aloud. Check that your free verse has good pauses and that both haiku have the right syllable counts.",
              "Haiku check: 5 syllables, 7 syllables, 5 syllables.",
              "Write one free verse poem and two haiku, then read and count.",
              ("What should you do after writing a haiku?", ["Count the syllables in each line", "Add a rhyme", "Make it longer"], 0, "Counting checks that the 5-7-5 pattern is right.")),
    ],
    "Model answers. Free verse has no set rhyme or regular rhythm, but each line is chosen for effect. Line breaks control pauses and make important words stand out. A haiku has three lines of 5, 7 and 5 syllables and shows one moment, often in nature. Model free verse: 'Cold metal bench. / My breath / is a small cloud / that vanishes. ...' Model haiku: 'Morning mist lifts slow, (5) / a spider's silver necklace (7) / glitters on the fence. (5)' Counting check: Rain taps on the roof (5), puddles gather in the lane (7), a frog starts to sing (5).",
    "1) Decide whether six poems are free verse or haiku. 2) Count the syllables in twelve words. 3) Rewrite three prose sentences as free verse lines. 4) Fix three haiku lines that are too long or too short. 5) Read a free verse poem or haiku chosen by your parent and describe its form. 6) Write one free verse poem and two haiku.",
    "Upload a photo of your free verse poem and two haiku, with syllable counts written beside the haiku.",
    CHECK,
    "Is my free verse about one moment? Did I cut extra words? Did I choose my line breaks on purpose? Does each haiku have 5, 7 and 5 syllables? Did I count by sound? Did I read all three aloud? Do they have titles?",
    [
        _q("Free verse is...", ["poetry with no set rhyme scheme or regular rhythm", "poetry with exactly five lines", "poetry that always rhymes"], 0, "Free verse lets the poet choose the shape."),
        _q("A line break is...", ["where one line ends and the next begins", "a blank page", "a rhyming word"], 0, "Line breaks control pauses."),
        _q("A haiku usually has...", ["three lines of 5, 7 and 5 syllables", "two lines of ten syllables", "four lines that rhyme"], 0, "The 5-7-5 pattern is the usual guide."),
        _q("How many syllables are in 'silver'?", ["2", "1", "3"], 0, "Sil-ver has two beats."),
        _q("A haiku is usually about...", ["one moment, often in nature", "a long story", "a list of facts"], 0, "Haiku capture a single moment."),
        _q("What is a good way to tighten free verse?", ["Cut words that do not help the picture", "Add rhymes", "Write longer lines"], 0, "Free verse works best when concise."),
        _q("Which line has 5 syllables?", ["Kitten naps in sun", "The kitten is sleeping", "A kitten sleeps in the warm sun"], 0, "Kit-ten naps in sun has five beats."),
        _q("Does a haiku usually rhyme?", ["No", "Always", "Only the last line"], 0, "Haiku are usually unrhymed."),
    ],
    "Upload a photo of your free verse poem and two haiku with syllable counts.",
    "Write a haiku about each season, then read them to a family member.",
    [("free verse", "Poetry with no set rhyme scheme or regular rhythm."), ("line break", "The place where one line of a poem ends and the next begins."), ("haiku", "A short poem of three lines, usually 5, 7 and 5 syllables, about one moment."), ("syllable", "One beat of sound in a word."), ("form", "The shape or pattern of a poem."), ("concise", "Using only the words that are needed.")],
    [],
    _sort("Which form?", "Which form does each clue describe? Tap a group, then Check.",
          ["Haiku", "Free verse"],
          [("Three lines of 5, 7 and 5 syllables", 0), ("Lines can be any length", 1), ("Usually about one moment in nature", 0), ("Line breaks are chosen for effect", 1), ("Seventeen syllables in total", 0), ("No set number of syllables", 1), ("Usually has exactly three lines", 0), ("May have only one word on a line", 1)]),
    [
        _wc("A short Japanese poem of three lines is a ___.", ["haiku", "hiku", "haikoo"], 0, "Haiku has a, i, k, u."),
        _wc("Poetry with no set rhyme or rhythm is free ___.", ["verse", "vers", "verce"], 0, "Verse ends with silent e."),
        _wc("Where one line ends and the next begins is a line ___.", ["break", "brake", "breck"], 0, "Break has ea."),
        _wc("Using only the words needed is ___.", ["concise", "consise", "concice"], 0, "Concise ends -cise."),
        _wc("Which is spelt correctly?", ["syllable", "sylable", "syllabel"], 0, "Syllable has double l."),
    ],
    [
        {"key": "free", "label": "Free verse", "hint": "One moment, tight words and purposeful line breaks."},
        {"key": "haiku1", "label": "First haiku", "hint": "5-7-5 syllables with counts shown."},
        {"key": "haiku2", "label": "Second haiku", "hint": "5-7-5 syllables with counts shown."},
        {"key": "aloud", "label": "Read aloud", "hint": "Pauses and counts checked by ear."},
    ],
    ["Thinking free verse is just a paragraph chopped into lines.", "Counting letters instead of syllables in a haiku.", "Adding rhymes to a haiku.", "Writing about too many things instead of one moment.", "Breaking lines in places that weaken the poem."],
    [{"title": "Haiku Postcards", "description": "Write three haiku on postcard-sized paper, one for each of three different places, and illustrate them.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that the free verse poem describes one moment and uses purposeful line breaks, and that each haiku has three lines of 5, 7 and 5 syllables, shown by counts beside each line. Sorter: Haiku: three lines of 5, 7 and 5 syllables; usually about one moment in nature; seventeen syllables in total; usually has exactly three lines. Free verse: lines can be any length; line breaks are chosen for effect; no set number of syllables; may have only one word on a line.",
)

B10L3 = build(
    "s2-eng-b10-l3-similes-and-metaphors", "Similes and Metaphors",
    "Learn how comparisons help readers picture things in new ways, how a simile differs from a metaphor, and how to write fresh ones.",
    "Language: similes and metaphors",
    ["EN2-VOCAB-01", "EN2-RECOM-01", "EN2-CWT-01", "EN2-OLC-01"],
    {"EN2-VOCAB-01": "Primary. Learns and uses figurative language, simile, metaphor, comparison, literal and cliche.",
     "EN2-RECOM-01": "Identifies similes and metaphors in sentences and poems and explains what they show.",
     "EN2-CWT-01": "Writes original similes and metaphors and uses them in a short poem.",
     "EN2-OLC-01": "Reads comparisons aloud and talks about the picture each one makes."},
    "We are learning how similes and metaphors compare two things and how to write fresh comparisons of our own.",
    ["I can explain what figurative language is.", "I can find a simile by its word like or as.", "I can find a metaphor that says one thing is another.", "I can explain what two things are being compared and why.", "I can write original similes and metaphors."],
    ["figurative language", "simile", "metaphor", "comparison", "literal", "cliche"],
    ["Paper or notebook", "Pencil", "A poem with comparisons chosen by your parent"],
    "Child has met imagery and sensory detail. This lesson teaches two kinds of comparison that make imagery stronger.",
    "Suppose you want to tell someone how quiet a library was. You could say 'It was very quiet.' But you could also say 'The library was as quiet as a sleeping cat.' Now your reader pictures something calm and soft.\n\nThat second sentence compares two different things to help you imagine the first one. Writers do this all the time. Comparisons are one of the most powerful tools in poetry.\n\nIn this lesson you will learn the difference between literal and figurative language, how similes and metaphors work, how to make comparisons fresh instead of tired, and how to explain what a comparison shows.",
    [
        _step("1", "Literal and figurative language",
              "LITERAL language means exactly what the words say. 'It was raining heavily.' means rain was falling hard.\n\nFIGURATIVE LANGUAGE uses words in a creative way to make a picture or feeling, and it is not meant to be taken word for word. 'It was raining cats and dogs' does not mean animals fell from the sky.\n\nTwo important kinds of figurative language are the SIMILE and the METAPHOR. Both are COMPARISONS: they describe one thing by saying it is like another.\n\nLiteral: 'The boy was very tall.'\nFigurative: 'The boy was a lighthouse in the crowd.'\n\nThe figurative sentence does not mean the boy is a building. It means he stood up above everyone and was easy to spot. When you read figurative language, ask: What two things are being compared? What do they have in common?",
              "Literal: 'My feet were cold.' Figurative: 'My feet were blocks of ice.'",
              "Figurative language uses creative comparisons, not literal meaning.",
              ("'The boy was a lighthouse in the crowd' is...", ["figurative language", "literal language", "a list"], 0, "The boy is not really a lighthouse; it is a comparison.")),
        _step("2", "Similes",
              "A SIMILE compares two different things using the word LIKE or AS.\n\nThe baby's fingers were as tiny as grains of rice.\nThe truck roared like an angry bull.\nHer laugh was like a bucket of silver coins tipped on the floor.\n\nEvery simile has three parts:\n1. The thing being described (the baby's fingers).\n2. The comparison word (as ... as, or like).\n3. The thing it is compared to (grains of rice).\n\nThe two things are very different, but they share one quality. Fingers and rice grains do not look alike overall, but both are tiny. The simile picks out that one shared quality.\n\nTo spot a simile, look for like or as. Be careful: not every sentence with like is a simile. 'I like pizza' uses like to mean enjoy. 'The pizza was like a hot, cheesy sun' is a simile.",
              "Simile: 'The moon was like a pale coin.' Shared quality: round and shining.",
              "A simile compares two things using like or as.",
              ("Which sentence is a simile?", ["The wind howled like a hungry wolf.", "The wind howled all night.", "I like the wind."], 0, "It compares wind to a wolf using like.")),
        _step("3", "Metaphors",
              "A METAPHOR also compares two different things, but it does not use like or as. It says that one thing IS the other.\n\nThe classroom was a beehive.\nTime is a thief.\nThe moon is a silver coin.\nMy bike is a rocket.\n\nOf course the classroom is not really a beehive. The metaphor says it so confidently that we see the busy, buzzing noise and movement straight away.\n\nSimile: The classroom was LIKE a beehive.\nMetaphor: The classroom WAS a beehive.\n\nThe metaphor is more direct and often feels stronger. A simile politely says 'it is like'. A metaphor boldly says 'it is'.\n\nSometimes a metaphor uses a verb instead of is: 'The sun painted the clouds pink.' The sun did not hold a brush, but the verb 'painted' compares the sunrise to painting.\n\nTo check, ask: Does it use like or as? If yes, it is a simile. If it says one thing is another without like or as, it is a metaphor.",
              "Metaphor: 'The lake was a mirror.' Shared quality: smooth and reflective.",
              "A metaphor says one thing is another, without like or as.",
              ("Which sentence is a metaphor?", ["The lake was a mirror.", "The lake was like a mirror.", "The lake was calm."], 0, "It says the lake is a mirror without using like or as.")),
        _step("4", "Making fresh comparisons",
              "Some comparisons have been used so often that they no longer surprise us. These are called CLICHES: 'as white as snow', 'as quick as a flash', 'as busy as a bee'. They are not wrong, but they do not make a reader see anything new.\n\nTo write a fresh comparison, follow these steps.\n\n1. Choose the thing you want to describe: a thunderstorm.\n2. Choose the quality you want to show: loud and angry.\n3. Brainstorm other things with that quality: a slammed door, a growling dog, a drum solo, a giant clearing his throat.\n4. Choose the one that surprises you but still fits: 'The thunder was a giant clearing his throat.'\n5. Test it: does it help the reader picture the storm?\n\nA good comparison is surprising and accurate. If it is surprising but does not fit, the reader will be confused. If it fits but is a cliche, the reader will skim over it.\n\nSpecific comparisons are usually stronger. 'Her voice was like a small bell at the end of a long hallway' is stronger than 'Her voice was like music'.",
              "Cliche: 'as cold as ice'. Fresh: 'as cold as a bathroom tile in winter'.",
              "Pick a quality, brainstorm, then choose a surprising but fitting comparison.",
              ("Which is a cliche?", ["as quick as a flash", "as quick as a dropped plate", "as quick as a startled gecko"], 0, "As quick as a flash is used very often.")),
        _step("5", "Explaining a comparison",
              "When you read a comparison in a poem, you can explain it in three parts.\n\n1. What two things are being compared?\n2. What do they have in common?\n3. What does this help the reader picture or feel?\n\nExample: 'The playground at lunch was a box of jumping beans.'\n1. Compared: the playground, a box of jumping beans.\n2. In common: lots of small things bouncing and moving about all the time.\n3. Effect: it helps us picture a noisy, busy, bouncing crowd of children.\n\nYou can write this as a sentence: 'The metaphor compares the playground to a box of jumping beans to show that the children were bouncing and moving everywhere.'\n\nUse linking words such as 'to show', 'which helps us picture' and 'because both'. Always say the shared quality. Never write only 'it makes the poem better' or 'it is a good comparison'.",
              "Explain: 'as tiny as grains of rice' compares fingers and rice to show that the fingers are very small.",
              "Name the two things, the shared quality and the effect.",
              ("A good explanation of a comparison names...", ["the two things and what they share", "only the author", "the number of words"], 0, "You must say what the two things have in common.")),
        _step("6", "Write your comparisons",
              "Now write your own.\n\n1. Write four similes about things around you, using like or as. Avoid cliches.\n2. Write four metaphors. Each says that one thing is another.\n3. Pick one simile and one metaphor and explain each in three parts: the two things, the shared quality and the effect.\n4. Write a poem of six to eight lines about a place or object using at least two similes and two metaphors.\n5. Read it aloud and underline the comparisons.\n\nModel poem:\nThe Creek\nThe creek is a silver ribbon\nunwinding through the gum trees.\nIt chuckles like a baby\nover smooth, brown stones.\nThe sun is a spotlight\nand the ripples are tiny stars\nthat blink as if they are shy.\n\nNotice that every comparison picks one quality and does not explain it too much. Trust the reader to work it out.",
              "Check: 'The creek is a silver ribbon' is a metaphor. 'It chuckles like a baby' is a simile.",
              "Write similes and metaphors, explain two, then use them in a poem.",
              ("What should you do after writing your poem?", ["Underline the comparisons and read aloud", "Delete the metaphors", "Add more cliches"], 0, "Underlining and reading aloud checks your comparisons.")),
    ],
    "Model answers. Literal language means what it says; figurative language uses creative comparison. A simile compares two things using like or as, such as 'The truck roared like an angry bull.' A metaphor says one thing is another, such as 'The classroom was a beehive.' Cliches such as 'as quick as a flash' are overused; fresh comparisons are surprising but accurate. To explain a comparison, name the two things, what they share and the effect. Model poem: 'The creek is a silver ribbon / unwinding through the gum trees. / It chuckles like a baby ...' Sorter: Simile: snow like a white blanket; voice as soft as velvet; ran like the wind; clouds like cotton wool. Metaphor: moon is a silver coin; classroom was a zoo; time is a thief; bike is a rocket.",
    "1) Sort ten sentences into literal or figurative. 2) Underline the like or as in six similes. 3) Turn four similes into metaphors. 4) Replace three cliches with fresh comparisons. 5) Choose three comparisons from a text selected by your parent and explain each. 6) Write four similes, four metaphors and a short poem using them.",
    "Upload a photo of your similes, metaphors, two explanations and your comparison poem.",
    CHECK,
    "Did I use like or as in each simile? Does each metaphor say one thing is another? Did I avoid cliches? Did I explain two comparisons using the two things, shared quality and effect? Does my poem have at least two similes and two metaphors? Did I underline them and read aloud?",
    [
        _q("A simile compares two things using...", ["like or as", "rhyme", "capital letters"], 0, "Similes use like or as."),
        _q("A metaphor...", ["says one thing is another without like or as", "always uses like", "is a type of rhyme"], 0, "Metaphors state the comparison directly."),
        _q("Which is a simile?", ["Her smile was as bright as the sun.", "Her smile was the sun.", "She smiled brightly."], 0, "It uses as ... as."),
        _q("Which is a metaphor?", ["Time is a thief.", "Time passed like a train.", "Time passed slowly."], 0, "It says time is a thief."),
        _q("A cliche is...", ["a comparison used so often it is no longer fresh", "a new idea", "a rhyming pair"], 0, "Cliches are overused."),
        _q("'The wind howled like a wolf' compares...", ["wind and a wolf", "wind and rain", "a wolf and a dog"], 0, "The two things are the wind and a wolf."),
        _q("When explaining a comparison, you should name...", ["what the two things share", "how many words it has", "the poet's age"], 0, "The shared quality is the key idea."),
        _q("'My feet were blocks of ice' is...", ["figurative language", "literal language", "a list"], 0, "Feet are not really ice; it is a comparison."),
    ],
    "Upload a photo of your similes, metaphors, explanations and poem.",
    "With a parent, find three comparisons in everyday speech or a favourite book and decide whether each is a simile or a metaphor.",
    [("figurative language", "Language that uses words creatively and is not meant word for word."), ("simile", "A comparison of two different things using like or as."), ("metaphor", "A comparison that says one thing is another."), ("comparison", "Showing how two things are alike."), ("literal", "Meaning exactly what the words say."), ("cliche", "A phrase or comparison used so often that it has lost its freshness.")],
    [],
    _sort("Simile or metaphor?", "Is each sentence a simile or a metaphor? Tap a group, then Check.",
          ["Simile", "Metaphor"],
          [("The moon is a silver coin.", 1), ("The snow was like a white blanket.", 0), ("Her voice was as soft as velvet.", 0), ("The classroom was a zoo.", 1), ("He ran like the wind.", 0), ("Time is a thief.", 1), ("My bike is a rocket.", 1), ("The clouds were like cotton wool.", 0)]),
    [
        _wc("A comparison using like or as is a ___.", ["simile", "similie", "simily"], 0, "Simile ends -ile."),
        _wc("A comparison that says one thing is another is a ___.", ["metaphor", "metafor", "metaphore"], 0, "Metaphor has ph."),
        _wc("Meaning exactly what the words say is ___.", ["literal", "litteral", "literel"], 0, "Literal has one t."),
        _wc("An overused comparison is a ___.", ["cliche", "clishay", "cleesh"], 0, "Cliche begins cl."),
        _wc("Which is spelt correctly?", ["figurative", "figurativ", "figerative"], 0, "Figurative ends -ive."),
    ],
    [
        {"key": "simile", "label": "Similes", "hint": "Four original similes with like or as."},
        {"key": "metaphor", "label": "Metaphors", "hint": "Four original metaphors."},
        {"key": "explain", "label": "Explanations", "hint": "Two comparisons explained in three parts."},
        {"key": "poem", "label": "Comparison poem", "hint": "At least two similes and two metaphors, underlined."},
    ],
    ["Thinking every sentence with like is a simile.", "Writing cliches such as as white as snow.", "Comparing two things that share nothing.", "Taking a metaphor literally.", "Not saying what the two things have in common."],
    [{"title": "Comparison Collector", "description": "Collect six comparisons from books, songs or conversation. Label each as a simile or metaphor and write what it compares.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that similes use like or as, metaphors say one thing is another, cliches are avoided, explanations name the two things, the shared quality and the effect, and the poem has at least two of each comparison. Sorter: Simile: the snow was like a white blanket; her voice was as soft as velvet; he ran like the wind; the clouds were like cotton wool. Metaphor: the moon is a silver coin; the classroom was a zoo; time is a thief; my bike is a rocket.",
)

B10L4 = build(
    "s2-eng-b10-l4-vocabulary-word-roots", "Vocabulary: Word Roots",
    "Learn what a word root is, study common Greek and Latin roots, and use them to work out the meaning of unfamiliar words.",
    "Vocabulary: word roots",
    ["EN2-VOCAB-01", "EN2-SPELL-01", "EN2-CWT-01"],
    {"EN2-VOCAB-01": "Primary. Learns roots, prefixes and suffixes and uses word parts to work out meanings.",
     "EN2-SPELL-01": "Spells words built from roots by spelling each part.",
     "EN2-CWT-01": "Uses root words accurately in sentences."},
    "We are learning that many English words are built from roots and that knowing the roots helps us work out new words.",
    ["I can explain what a root is.", "I can name the meanings of port, scope and graph.", "I can name the meanings of aqua, bio and phon.", "I can split an unfamiliar word into parts and guess its meaning.", "I can use root words in my own sentences."],
    ["root", "prefix", "suffix", "Greek", "Latin", "decode"],
    ["Paper or notebook", "Pencil", "A dictionary with parent help", "Index cards"],
    "Child has learned prefixes and suffixes. This lesson teaches roots, the central part of a word that carries its core meaning.",
    "Here is a puzzle. You may never have heard the word 'portable' before. But if you know that 'port' means carry and that '-able' means able to be, you can guess that portable means able to be carried.\n\nMany English words are built from small parts, and one of those parts is the ROOT: the central piece that carries the main meaning. English borrowed a huge number of roots from two ancient languages, Latin and Greek.\n\nIn this lesson you will learn what a root is, meet six common roots and the words they build, combine roots with prefixes and suffixes, and practise decoding unfamiliar words like a detective.",
    [
        _step("1", "What a root is",
              "A ROOT is the central part of a word that carries its main meaning. Other word parts attach to it.\n\nA PREFIX is a part added to the front of a word, such as un-, re- or dis-. A SUFFIX is a part added to the end, such as -ful, -less or -able.\n\nSo a word can be built like this:\nprefix + root + suffix\n\nExample: transportable\ntrans- (across) + port (carry) + -able (able to be)\nMeaning: able to be carried across.\n\nMany roots come from LATIN, the language of ancient Rome, or GREEK, the language of ancient Greece. A root is not always a word you can use by itself. 'Port' on its own is a harbour in English, but in the words transport and portable it means carry, which is its older Latin meaning.\n\nKnowing roots is like having a set of keys. One root can open the meaning of dozens of words.",
              "Split: portable = port + able.",
              "A root carries the core meaning; prefixes and suffixes add to it.",
              ("The root of a word is...", ["the central part that carries its main meaning", "the last letter", "always a whole word"], 0, "Roots hold the core meaning.")),
        _step("2", "The roots port, scope and graph",
              "Meet three roots.\n\nPORT (Latin) means CARRY.\ntransport: carry across.\nimport: carry in.\nexport: carry out.\nportable: able to be carried.\nporter: a person who carries luggage.\n\nSCOPE (Greek) means LOOK AT or SEE.\ntelescope: a tool for looking at faraway things (tele means far).\nmicroscope: a tool for looking at very small things (micro means small).\nperiscope: a tool for looking around (peri means around).\n\nGRAPH (Greek) means WRITE or DRAW.\nautograph: your own writing (auto means self).\nphotograph: a picture drawn with light (photo means light).\nparagraph: a unit of writing (para means beside, from an old way of marking text).\n\nNotice that the same roots appear again and again. When you see one in a new word, think of its meaning first.\n\nSpelling tip: spell each part separately. micro + scope = microscope.",
              "Words: export = ex (out) + port (carry). Telescope = tele (far) + scope (look).",
              "port means carry, scope means look at, graph means write or draw.",
              ("The root scope means...", ["look at", "carry", "write"], 0, "Scope comes from a Greek word for look at.")),
        _step("3", "The roots aqua, bio and phon",
              "Meet three more roots.\n\nAQUA (Latin) means WATER.\naquarium: a place or tank for water animals.\naquatic: living or happening in water.\naqueduct: a channel that carries water (duct means lead).\n\nBIO (Greek) means LIFE.\nbiology: the study of life (-ology means study of).\nbiography: the written story of a person's life (bio + graph).\nbiome: a large area of life, such as a desert or a rainforest.\n\nPHON (Greek) means SOUND.\nphone: a device for sending sound (short for telephone).\nmicrophone: a tool that makes small sounds bigger (micro means small).\nsaxophone: a musical instrument named for its inventor, Mr Sax, with phone for sound.\nphonics: learning the sounds of letters.\n\nNow you know six roots. Write each on a card with its meaning and two example words. Cards help you remember them.\n\nSpelling tips: aquarium has a q followed by u. Biography has bio, then graph with ph, then y. Phone starts with ph.",
              "Words: aquatic = aqua + tic. Biology = bio + ology. Microphone = micro + phone.",
              "aqua means water, bio means life, phon means sound.",
              ("The root bio means...", ["life", "water", "sound"], 0, "Bio comes from the Greek word for life.")),
        _step("4", "Building words from parts",
              "You can build and take apart words by joining parts.\n\ntele (far) + scope (look) = telescope\nmicro (small) + scope = microscope\ntele + phone (sound) = telephone\nmicro + phone = microphone\nauto (self) + graph (write) = autograph\nphoto (light) + graph = photograph\nbio (life) + graph = biography\nbio + logy (study) = biology\n\nNotice that some word parts such as tele, micro, photo and auto are like prefixes: they come at the start. Others, like graph and scope, can also come at the end of a word.\n\nTo take a word apart, look for parts you already know. Draw a line between them. Say each part and its meaning, then put the meanings together.\n\nExample: 'periscope'. Peri means around, scope means look. So a periscope is a tool for looking around, such as from a submarine.\n\nAlways put the meanings back together in a smooth sentence so the meaning makes sense.",
              "Build: aqua + rium = aquarium, a place for water.",
              "Join word parts and read their meanings together.",
              ("What does telephone mean if tele means far and phone means sound?", ["far sound", "near light", "write across"], 0, "A telephone carries sound from far away.")),
        _step("5", "Decoding an unfamiliar word",
              "When you meet a word you do not know, you can DECODE it, which means to work out its meaning from its parts. Follow these steps.\n\n1. Cover the ending and the beginning and look for a root you know.\n2. Split the word into parts with lines.\n3. Say the meaning of each part.\n4. Put the meanings together to make a guess.\n5. Check the guess against the sentence it was in.\n6. Check a dictionary to be sure.\n\nExample: 'The explorer carried a portable stove.'\nport + able = able to be carried. Does it fit the sentence? Yes, the explorer carried it.\n\nExample: 'The aquatic plants floated at the edge of the pond.'\naqua + tic = to do with water. It fits, because the pond is water.\n\nBe careful! A root only helps when the word really contains it. 'Portrait' looks as if it contains port, but it comes from a different root and does not mean carry. That is why step 5 and step 6 matter: check the sentence and a dictionary.",
              "Decode: 'biography' = bio (life) + graph (write) = writing about a life.",
              "Split, say the meanings, join them, then check with the sentence and a dictionary.",
              ("What should you do after guessing a meaning from roots?", ["Check it against the sentence and a dictionary", "Never check", "Guess a new word"], 0, "Checking proves your guess is right.")),
        _step("6", "Practise and use roots",
              "Now put the roots to work.\n\n1. Make a root card for each of the six roots: port, scope, graph, aqua, bio and phon. Write its meaning and at least three words.\n2. Build five new words by joining parts, such as tele + scope.\n3. Decode these words: portable, periscope, autograph, aquatic, biology, microphone. Write each as parts, meanings and a final definition.\n4. Write six sentences, each using one of the decoded words.\n5. Find two more words at home or in a book that contain one of the roots. Write them and their meanings.\n6. Choose three words from your cards and practise spelling them using look, say, cover, write, check.\n\nModel decode:\nmicrophone = micro (small) + phone (sound). A microphone is a tool that picks up small sounds and makes them bigger.\nModel sentence: 'The singer held a microphone close to her mouth.'\n\nRemember: always check your guess against the sentence and a dictionary.",
              "Model: 'The biography told the story of a famous scientist's life.'",
              "Make cards, build and decode words, then write your own sentences.",
              ("A good way to remember roots is to...", ["make cards with meanings and examples", "never write them down", "only read them once"], 0, "Cards help you revise and use roots.")),
    ],
    "Model answers. A root is the central part of a word that carries its main meaning; prefixes and suffixes attach to it. Port means carry (transport, import, export, portable). Scope means look at (telescope, microscope, periscope). Graph means write or draw (autograph, photograph, paragraph, biography). Aqua means water (aquarium, aquatic). Bio means life (biology, biography). Phon means sound (phone, microphone). To decode a word: split it, say the meanings, join them, check with the sentence and a dictionary. Portrait looks as if it contains port but does not mean carry. Sorter: port: transport, import, export, portable. scope: telescope, microscope, periscope. graph: autograph, paragraph, photograph.",
    "1) Match six roots to their meanings. 2) Sort twelve words by root. 3) Build five words by joining parts. 4) Decode six words. 5) Write six sentences using decoded words. 6) Find two extra words in a text and decode them.",
    "Upload a photo of your six root cards, your decoded words and your six sentences.",
    CHECK,
    "Did I make a card for each root? Did I split each word into parts? Did I write the meaning of each part? Did I check my guesses with a sentence and a dictionary? Did I use the decoded words in sentences? Did I spell each part correctly?",
    [
        _q("A root is...", ["the central part of a word that carries its main meaning", "a letter at the end", "a kind of sentence"], 0, "Roots hold the core meaning."),
        _q("The root port means...", ["carry", "look", "water"], 0, "Port means carry."),
        _q("The root graph means...", ["write or draw", "sound", "life"], 0, "Graph means write or draw."),
        _q("The root aqua means...", ["water", "life", "sound"], 0, "Aqua means water."),
        _q("A telescope is a tool for...", ["looking at faraway things", "carrying water", "writing letters"], 0, "Tele means far and scope means look."),
        _q("Biology is the study of...", ["life", "sound", "water"], 0, "Bio means life."),
        _q("A microphone is a tool for...", ["making small sounds bigger", "looking at tiny things", "carrying people"], 0, "Micro means small and phone means sound."),
        _q("Why check a root guess against a dictionary?", ["Some words only look as if they contain a root", "Dictionaries are boring", "Roots never help"], 0, "A word like portrait does not come from the carry root."),
    ],
    "Upload a photo of your root cards, decoded words and sentences.",
    "Hunt for two words with each of this week's roots in books or on labels at home. Add them to your cards.",
    [("root", "The central part of a word that carries its main meaning."), ("prefix", "A word part added to the front of a word."), ("suffix", "A word part added to the end of a word."), ("Greek", "An ancient language that gave English many word roots."), ("Latin", "The language of ancient Rome that gave English many word roots."), ("decode", "To work out the meaning of a word from its parts.")],
    [],
    _sort("Which root?", "Which root does each word contain? Tap a group, then Check.",
          ["port (carry)", "scope (look)", "graph (write or draw)"],
          [("transport", 0), ("telescope", 1), ("autograph", 2), ("import", 0), ("microscope", 1), ("paragraph", 2), ("portable", 0), ("periscope", 1), ("photograph", 2), ("export", 0)]),
    [
        _wc("A place for water animals is an ___.", ["aquarium", "acquarium", "aqarium"], 0, "Aquarium starts aqu."),
        _wc("The study of life is ___.", ["biology", "bialogy", "biolagy"], 0, "Biology ends -ology."),
        _wc("A tool for looking at tiny things is a ___.", ["microscope", "microscop", "mikroscope"], 0, "Microscope ends -scope."),
        _wc("A picture made with light is a ___.", ["photograph", "fotograph", "photograf"], 0, "Photograph has ph twice."),
        _wc("Which is spelt correctly?", ["telephone", "telefone", "telephon"], 0, "Telephone has ph and silent e."),
    ],
    [
        {"key": "cards", "label": "Root cards", "hint": "Six roots with meanings and example words."},
        {"key": "build", "label": "Built words", "hint": "Five new words made by joining parts."},
        {"key": "decode", "label": "Decoded words", "hint": "Six words split into parts and defined."},
        {"key": "sentences", "label": "Sentences", "hint": "Six sentences using the decoded words."},
    ],
    ["Thinking a root is always a whole word.", "Guessing a meaning without checking the sentence.", "Assuming any word containing port means carry.", "Forgetting to spell each part separately.", "Mixing up the roots scope and graph."],
    [{"title": "Root Detective", "description": "Find ten words in books or around the house that contain this week's roots. Decode each and make a poster.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the root cards give the correct meaning (port carry, scope look at, graph write or draw, aqua water, bio life, phon sound), built words are real words, decoded words are split into parts with correct meanings and checked against a sentence, and each sentence uses a word correctly. Sorter: port: transport, import, portable, export. scope: telescope, microscope, periscope. graph: autograph, paragraph, photograph.",
)

LESSONS = [B10L1, B10L2, B10L3, B10L4]
