"""Stage 2 Maths, Week 3 of the programme. Three lessons: addition and subtraction strategies (MA2-AR-01).
Loaded automatically by _register_maths in lesson_library.py. Videos are attached in a later pass."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from lesson_library_s2_maths_w1 import _maths

M1 = _maths(build(
    "s2-math-w03-l1-mental-strategies", "Mental Strategies: Partition, Bridge and Adjust",
    "The Treasure Vault door has a timer. Crack the sums in your head with three clever strategies before the lock resets.",
    "Number: mental addition and subtraction",
    ["MA2-AR-01"],
    {"MA2-AR-01": "Primary. Selects and uses mental strategies (partitioning, bridging ten, adjusting near numbers, counting on) for addition and subtraction with two-digit numbers."},
    "We are learning to choose and use mental strategies to add and subtract two-digit numbers.",
    ["I can add by partitioning into tens and ones.", "I can bridge to the next ten.", "I can add a near number by adjusting.", "I can subtract by counting on.", "I can say why I chose a strategy."],
    ["partition", "bridge", "adjust", "strategy", "count on", "near number", "mental"],
    ["Paper or notebook", "Pencil", "Number line (optional)"],
    "Child can add and subtract within 100 and knows place value to hundreds.",
    "A shopkeeper adds 49 cents and 34 cents in her head in two seconds. She does not line up columns. She thinks: 49 is almost 50, so 50 + 34 = 84, then take 1 back to make 83.\n\nThere is more than one way to add and subtract in your head. In this lesson you will learn four strategies and practise choosing the one that fits the numbers.",
    [
        _step("1", "Partitioning",
              "PARTITION means to split numbers into tens and ones. To add 47 + 36: split into 40 + 7 and 30 + 6. Add the tens: 40 + 30 = 70. Add the ones: 7 + 6 = 13. Put them together: 70 + 13 = 83.\n\nThis works well when the ones do not make a big jump.",
              "34 + 25: 30 + 20 = 50 and 4 + 5 = 9, so 59.",
              "Tens first, ones second, then combine.",
              ("What is 36 + 27?", ["53", "63", "73"], 1, "30 + 20 = 50 and 6 + 7 = 13. 50 + 13 = 63.")),
        _step("2", "Bridging ten",
              "To BRIDGE a ten, add enough to reach the next ten, then add what is left. For 68 + 7: 68 needs 2 more to reach 70. 7 is 2 and 5. So 68 + 2 = 70, then 70 + 5 = 75.\n\nThis strategy is quick when you add a one-digit number to a number that ends in 6, 7, 8 or 9.",
              "47 + 8: 47 + 3 = 50, then 50 + 5 = 55.",
              "Make a friendly ten first.",
              ("What is 47 + 8?", ["54", "55", "56"], 1, "47 + 3 = 50, then 50 + 5 = 55.")),
        _step("3", "Adjusting near numbers",
              "A NEAR NUMBER is just below or above a friendly number such as 20, 30 or 100. Round it, calculate, then ADJUST.\n\nFor 58 + 19: add 20 instead, 58 + 20 = 78, then take 1 away because 19 is 1 less than 20. Answer: 77.\n\nFor 99 + 26: add 100, 100 + 26 = 126, then take 1 away: 125.",
              "54 + 29: 54 + 30 = 84, then minus 1 is 83.",
              "If you added too much, take it back. If you added too little, add it on.",
              ("What is 99 + 26?", ["115", "125", "135"], 1, "100 + 26 = 126, minus 1 is 125.")),
        _step("4", "Subtracting by counting on",
              "When two numbers are close, COUNT ON from the smaller to the larger. For 82 - 47: from 47 count on 3 to reach 50. From 50 count on 30 to reach 80. Count on 2 more to reach 82. Add the jumps: 3 + 30 + 2 = 35.\n\nSo 82 - 47 = 35. You can check by adding: 35 + 47 = 82.",
              "100 - 47: 47 to 50 is 3, 50 to 100 is 50. So 53.",
              "Jump to a friendly ten, then in big steps, then the last bit.",
              ("What is 82 - 47?", ["35", "45", "25"], 0, "3 + 30 + 2 = 35.")),
    ],
    "Problem: 62 + 39. 39 is a near number: it is 1 less than 40. 62 + 40 = 102. Take 1 away: 101. Check by partitioning: 60 + 30 = 90 and 2 + 9 = 11. 90 + 11 = 101. Both strategies agree.",
    "Work in your notebook. Part A (partition): 34 + 25, 47 + 36, 58 + 27. Part B (bridge ten): 69 + 6, 78 + 5, 87 + 8. Part C (near numbers): 39 + 45, 68 + 29, 99 + 34. Part D (count on): 70 - 26, 91 - 54, 100 - 63. Part E: 98 + 45 and say which strategy you used.",
    "Stage 1 (choose): write ten different sums with two-digit numbers.\nStage 2 (strategy): beside each, write the strategy you will use.\nStage 3 (solve): solve each in your head, then write the answer.\nStage 4 (prove): choose two sums and solve them a second way to check.",
    "Write the answers in your notebook and explain one strategy aloud.",
    "Did I write ten sums? Did I name a strategy for each? Did I check two sums a second way? Can I explain why I chose each strategy?",
    [
        _q("What is 36 + 27?", ["53", "63", "73"], 1, "50 + 13 = 63."),
        _q("What is 58 + 19?", ["67", "77", "79"], 1, "58 + 20 = 78, minus 1."),
        _q("What is 47 + 8?", ["54", "55", "56"], 1, "47 + 3 = 50, then 5 more."),
        _q("What is 82 - 47?", ["35", "45", "25"], 0, "Count on: 3 + 30 + 2."),
        _q("What is 63 - 28?", ["35", "45", "41"], 0, "63 - 30 = 33, then add 2."),
        _q("What is 99 + 26?", ["115", "125", "135"], 1, "100 + 26 = 126, minus 1."),
        _q("What is 100 - 47?", ["63", "57", "53"], 2, "3 to reach 50, then 50 more."),
        _q("What is 54 + 29?", ["83", "73", "85"], 0, "54 + 30 = 84, minus 1."),
        _q("To add 49 you can add 50 and then ___.", ["add 1", "take away 1", "take away 10"], 1, "49 is 1 less than 50."),
        _q("What is 72 - 38?", ["34", "44", "36"], 0, "72 - 40 = 32, then add 2."),
    ],
    "Upload a photo of your ten sums with the strategy beside each one.",
    "Find a sum where two different strategies are equally quick, and explain which one you prefer and why.",
    [("partition", "To split a number into tens and ones."), ("bridge", "To add up to the next ten, then add the rest."), ("adjust", "To fix an answer after using a rounded number."),
     ("strategy", "A plan for solving a problem."), ("count on", "To count up from the smaller number to the larger."), ("near number", "A number just below or above a friendly number."), ("mental", "Done in your head.")],
    [],
    _sort("Which strategy fits best?", "Which strategy would you use for each sum? Tap a strategy, then press Check.",
          ["Partition", "Bridge ten", "Near number"],
          [("34 + 25", 0), ("42 + 36", 0), ("51 + 27", 0), ("67 + 5", 1), ("78 + 6", 1), ("89 + 7", 1), ("45 + 29", 2), ("62 + 39", 2), ("33 + 19", 2)]),
    [
        _wc("To split a number into tens and ones is to ___ it.", ["partition", "partision", "partishun"], 0, "Partition ends tion."),
        _wc("A plan for solving a problem is a ___.", ["strategy", "stratagy", "stratergy"], 0, "Strategy has teg."),
        _wc("To fix an answer after rounding you ___ it.", ["adjust", "ajust", "adjost"], 0, "Adjust has dj."),
    ],
    [
        {"key": "s", "label": "Ten sums and strategies", "hint": "Photograph your list."},
        {"key": "c", "label": "Second-way checks", "hint": "Show two sums solved two ways."},
        {"key": "e", "label": "Explanation", "hint": "Write why you picked a strategy."},
    ],
    ["Forgetting to adjust after rounding a near number.", "Adjusting in the wrong direction.", "Adding the tens but forgetting the ones.", "Adding instead of counting on for a subtraction.", "Using one strategy for every sum."],
    [{"title": "Shop Till You Drop", "description": "Pick five items from a catalogue priced under $100. Add pairs of prices in your head, naming the strategy. Check two with a second strategy.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 59, 83, 85. Part B: 75, 83, 95. Part C: 84, 97, 133. Part D: 44, 37, 37. Part E: 143 (98 + 2 = 100, then 100 + 43).",
), "Let him talk through the thinking before writing anything. A number line is fine as support, but try each strategy without paper first.")


M2 = _maths(build(
    "s2-math-w03-l2-written-addition", "Written Addition with Regrouping",
    "The Treasure Vault ledger holds big numbers. Learn to add in columns so no coin is ever lost.",
    "Number: written addition",
    ["MA2-AR-01"],
    {"MA2-AR-01": "Primary. Uses the column algorithm for addition of two- and three-digit numbers, regrouping ones and tens, and checks by estimating."},
    "We are learning to add two- and three-digit numbers in columns and regroup when a column has ten or more.",
    ["I can line up ones, tens and hundreds.", "I can add the ones column first.", "I can regroup ten ones as one ten.", "I can regroup tens as hundreds.", "I can estimate to check my answer."],
    ["column", "regroup", "ones", "tens", "hundreds", "estimate", "sum"],
    ["Squared or lined paper", "Pencil", "Place value blocks (optional)"],
    "Child knows place value to hundreds and can add small numbers mentally.",
    "A vault keeper counts 148 gold coins in one chest and 27 in another. Counting every coin would take forever. Adding in columns gives the total in seconds.\n\nThe column method lines up ones with ones, tens with tens and hundreds with hundreds. You always start with the ones. When a column adds to ten or more, you REGROUP.",
    [
        _step("1", "Line up the columns",
              "Write the bigger number on top. Put ones under ones, tens under tens and hundreds under hundreds. Draw a line and write the plus sign.\n\nAdd the ONES column first, then the tens, then the hundreds.\n\nWhen no column makes ten or more, just write each total underneath.",
              "123 + 45: ones 3 + 5 = 8, tens 2 + 4 = 6, hundreds 1. The sum is 168.",
              "Ones first, always. Neat columns prevent mistakes.",
              ("What is 123 + 45?", ["158", "168", "178"], 1, "3 + 5 = 8, 2 + 4 = 6, hundreds 1.")),
        _step("2", "Regroup the ones",
              "When the ones add to ten or more, REGROUP: write the ones digit and move one ten to the tens column.\n\n148 + 27: ones 8 + 7 = 15. Write 5 in the ones column and regroup 1 ten. Tens: 4 + 2 + 1 = 7. Hundreds: 1. The sum is 175.\n\nWrite the small 1 above the tens column so you do not forget it.",
              "359 + 36: ones 9 + 6 = 15, write 5 and regroup 1. Tens 5 + 3 + 1 = 9. Hundreds 3. Sum 395.",
              "Write the regrouped ten above the tens column.",
              ("What is 145 + 38?", ["173", "183", "193"], 1, "5 + 8 = 13, write 3 regroup 1. 4 + 3 + 1 = 8. Hundreds 1.")),
        _step("3", "Regroup twice",
              "Sometimes you regroup in the ones AND the tens column.\n\n367 + 485: ones 7 + 5 = 12, write 2 regroup 1. Tens 6 + 8 + 1 = 15, write 5 regroup 1 hundred. Hundreds 3 + 4 + 1 = 8. The sum is 852.\n\nWork one column at a time and add the regrouped digit every time.",
              "578 + 264: 8 + 4 = 12 (2, regroup 1), 7 + 6 + 1 = 14 (4, regroup 1), 5 + 2 + 1 = 8. Sum 842.",
              "One column at a time. Never skip the regrouped digit.",
              ("What is 378 + 245?", ["513", "623", "633"], 1, "8 + 5 = 13, 7 + 4 + 1 = 12, 3 + 2 + 1 = 6.")),
        _step("4", "Estimate to check",
              "An ESTIMATE is a rough answer. Round each number to the nearest ten or hundred, then add.\n\nFor 367 + 485, round to 370 + 490 = 860. The exact answer 852 is close, so it is sensible.\n\nIf your exact answer is far from the estimate, look for a missing regrouped digit.",
              "298 + 403: round to 300 + 400 = 700. The exact answer is 701.",
              "Estimate first, solve second, compare third.",
              ("Estimate 298 + 403 by rounding to the nearest hundred.", ["600", "700", "800"], 1, "300 + 400 = 700.")),
    ],
    "Problem: 256 students in Year 3 and 189 in Year 4. How many altogether? Estimate: 260 + 190 = 450. Ones: 6 + 9 = 15, write 5, regroup 1. Tens: 5 + 8 + 1 = 14, write 4, regroup 1. Hundreds: 2 + 1 + 1 = 4. Sum 445. It is close to 450, so it is sensible.",
    "Work in your notebook. Part A: 123 + 45 and 236 + 52. Part B: 148 + 27, 359 + 36 and 287 + 135. Part C: 467 + 385 and 578 + 264. Part D: estimate then solve 312 + 489. Part E: 256 students and 189 students. How many altogether?",
    "Stage 1 (set up): write six addition problems of your own in columns.\nStage 2 (estimate): write a rounded estimate beside each.\nStage 3 (solve): solve each, writing small regrouped digits.\nStage 4 (story): write a story problem that needs regrouping and solve it.",
    "Write the answers in your notebook and explain one regrouping aloud.",
    "Did I line up the columns? Did I estimate every sum? Did I write the regrouped digits? Did I write a story?",
    [
        _q("What is 145 + 38?", ["173", "183", "193"], 1, "5 + 8 = 13."),
        _q("What is 256 + 127?", ["373", "383", "393"], 1, "6 + 7 = 13, 5 + 2 + 1 = 8, 2 + 1 = 3."),
        _q("What is 378 + 245?", ["513", "623", "633"], 1, "Regroup twice."),
        _q("What is 409 + 356?", ["755", "765", "865"], 1, "9 + 6 = 15, 0 + 5 + 1 = 6, 4 + 3 = 7."),
        _q("6 ones + 7 ones = 13 ones. What do you write in the ones column?", ["13", "3 and regroup 1 ten", "1 and regroup 3"], 1, "13 ones is 1 ten and 3 ones."),
        _q("What is 587 + 246?", ["823", "833", "843"], 1, "7 + 6 = 13, 8 + 4 + 1 = 13, 5 + 2 + 1 = 8."),
        _q("What is 99 + 99?", ["188", "198", "199"], 1, "9 + 9 = 18, 9 + 9 + 1 = 19."),
        _q("Estimate 298 + 403 to the nearest hundred.", ["600", "700", "800"], 1, "300 + 400."),
        _q("What is 234 + 567?", ["791", "801", "811"], 1, "4 + 7 = 11, 3 + 6 + 1 = 10, 2 + 5 + 1 = 8."),
        _q("What is 675 + 189?", ["854", "864", "874"], 1, "5 + 9 = 14, 7 + 8 + 1 = 16, 6 + 1 + 1 = 8."),
    ],
    "Upload a photo of your six column additions, estimates and story problem.",
    "Find two three-digit numbers that add to exactly 1000 and show how you know.",
    [("column", "A line of digits going down."), ("regroup", "To exchange ten of one place for one of the next place."), ("ones", "The place for single units."),
     ("tens", "The place for groups of ten."), ("hundreds", "The place for groups of one hundred."), ("estimate", "A rough answer."), ("sum", "The answer to an addition.")],
    [],
    _sort("How many regroups?", "How many times do you regroup in each sum? Tap a group, then press Check.",
          ["No regrouping", "Regroup once", "Regroup twice"],
          [("123 + 45", 0), ("241 + 36", 0), ("312 + 85", 0), ("148 + 27", 1), ("236 + 58", 1), ("453 + 29", 1), ("367 + 485", 2), ("578 + 264", 2), ("289 + 147", 2)]),
    [
        _wc("To exchange ten ones for one ten is to ___.", ["regroup", "regrup", "regroop"], 0, "Regroup has oup."),
        _wc("A rough answer is an ___.", ["estimate", "estimat", "estamate"], 0, "Estimate ends mate."),
        _wc("The answer to an addition is the ___.", ["sum", "summ", "som"], 0, "Sum has u."),
    ],
    [
        {"key": "c", "label": "Column additions", "hint": "Photograph your six sums with regrouped digits."},
        {"key": "e", "label": "Estimates", "hint": "Show the rounded estimate for each."},
        {"key": "s", "label": "Story", "hint": "Write a story that needs regrouping."},
    ],
    ["Starting with the hundreds column.", "Forgetting the regrouped digit.", "Writing both digits of 13 in the ones column.", "Misaligning columns.", "Not checking against an estimate."],
    [{"title": "Sports Crowd", "description": "Find the crowd sizes for two sporting matches. Add them using the column method and estimate to check.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 168, 288. Part B: 175, 395, 422. Part C: 852, 842. Part D: estimate 800, answer 801. Part E: 445 students.",
), "Use squared paper so the columns stay straight. Use place value blocks if regrouping feels abstract.")


M3 = _maths(build(
    "s2-math-w03-l3-written-subtraction", "Written Subtraction with Exchanging",
    "The Treasure Vault spends gold on repairs. Learn to subtract in columns and exchange when you need more ones.",
    "Number: written subtraction",
    ["MA2-AR-01"],
    {"MA2-AR-01": "Primary. Uses the column algorithm for subtraction of two- and three-digit numbers, exchanging tens for ones and hundreds for tens, including across zero, and checks by adding."},
    "We are learning to subtract two- and three-digit numbers in columns and exchange when a digit is too small.",
    ["I can line up the columns and subtract the ones first.", "I can exchange one ten for ten ones.", "I can exchange one hundred for ten tens.", "I can subtract across a zero.", "I can check by adding."],
    ["subtract", "exchange", "difference", "column", "inverse", "check", "zero"],
    ["Squared or lined paper", "Pencil", "Place value blocks (optional)"],
    "Child can add in columns with regrouping and knows place value to hundreds.",
    "A vault has 304 gold coins and 157 are spent on repairs. You cannot take 7 ones from 4 ones. So you must exchange.\n\nColumn subtraction works like column addition but backwards. Start with the ones. When the top digit is smaller than the bottom digit, EXCHANGE one ten for ten ones, or one hundred for ten tens.",
    [
        _step("1", "Subtract with no exchange",
              "Write the bigger number on top. Subtract the ones, then the tens, then the hundreds.\n\n468 - 215: ones 8 - 5 = 3, tens 6 - 1 = 5, hundreds 4 - 2 = 2. The difference is 253.\n\nThe answer to a subtraction is called the DIFFERENCE.",
              "87 - 34: 7 - 4 = 3 and 8 - 3 = 5. The difference is 53.",
              "Subtract each column. The top number always comes first.",
              ("What is 78 - 35?", ["43", "53", "113"], 0, "8 - 5 = 3, 7 - 3 = 4.")),
        _step("2", "Exchange a ten",
              "If the top ones digit is smaller than the bottom ones digit, EXCHANGE one ten for 10 ones.\n\n53 - 28: 3 ones is not enough to take 8. Take 1 ten from the 5 tens, leaving 4 tens. Add 10 ones to the 3 ones to make 13. Now 13 - 8 = 5 and 4 - 2 = 2. The difference is 25.\n\nCheck by adding: 25 + 28 = 53.",
              "62 - 18: 12 - 8 = 4 and 5 - 1 = 4. The difference is 44.",
              "Cross out the tens digit, write one less, and add ten to the ones.",
              ("What is 85 - 37?", ["48", "52", "58"], 0, "15 - 7 = 8 and 7 - 3 = 4.")),
        _step("3", "Exchange a hundred and subtract across zero",
              "You can exchange a hundred for ten tens too. For 523 - 267: ones 3 is too small, so exchange a ten, giving 13 - 7 = 6. Now tens are 1, too small for 6, so exchange a hundred, giving 11 - 6 = 5. Hundreds 4 - 2 = 2. The difference is 256.\n\nWhen the tens digit is ZERO, as in 304 - 157, exchange from the hundreds first: 3 hundreds becomes 2 hundreds and 10 tens. Take 1 ten for the ones, leaving 9 tens and 14 ones. 14 - 7 = 7, 9 - 5 = 4, 2 - 1 = 1. The difference is 147.",
              "500 - 243: 4 hundreds, 9 tens and 10 ones. 10 - 3 = 7, 9 - 4 = 5, 4 - 2 = 2. The difference is 257.",
              "With a zero, exchange from the next column over, then move down one column at a time.",
              ("What is 523 - 267?", ["246", "256", "266"], 1, "13 - 7 = 6, 11 - 6 = 5, 4 - 2 = 2.")),
        _step("4", "Check by adding",
              "Addition and subtraction are inverse operations. Add the difference to the number you took away. You should get back the number you started with.\n\nFor 304 - 157 = 147, check 147 + 157 = 304. It works.\n\nIf the check does not match, find which column went wrong and try again.",
              "91 - 45 = 46 because 46 + 45 = 91.",
              "Difference plus the taken-away number equals the start.",
              ("Which addition checks 91 - 45 = 46?", ["46 + 45 = 91", "91 + 45 = 46", "46 + 91 = 45"], 0, "The difference plus the part taken away makes the whole.")),
    ],
    "Problem: A vault has 304 coins and spends 157. How many are left? Ones: 4 is too small and tens is 0, so exchange a hundred: 2 hundreds, 10 tens. Take a ten: 9 tens and 14 ones. 14 - 7 = 7, 9 - 5 = 4, 2 - 1 = 1. Answer 147. Check: 147 + 157 = 304.",
    "Work in your notebook. Part A: 78 - 35 and 96 - 52. Part B: 53 - 28, 82 - 47 and 71 - 39. Part C: 345 - 128, 523 - 267 and 640 - 285. Part D: 304 - 157 and 500 - 243. Part E: check your answer to 500 - 243 by adding.",
    "Stage 1 (set up): write six subtractions of your own in columns, including two with a zero.\nStage 2 (solve): solve each, showing the exchanges.\nStage 3 (check): check each answer by adding.\nStage 4 (story): write a story problem that needs an exchange and solve it.",
    "Write the answers in your notebook and explain one exchange aloud.",
    "Did I put the bigger number on top? Did I show each exchange? Did I check every answer by adding? Did I write a story?",
    [
        _q("What is 85 - 37?", ["48", "52", "58"], 0, "15 - 7 = 8."),
        _q("What is 62 - 18?", ["44", "54", "46"], 0, "12 - 8 = 4, 5 - 1 = 4."),
        _q("What is 345 - 128?", ["217", "227", "223"], 0, "15 - 8 = 7, 3 - 2 = 1, 3 - 1 = 2."),
        _q("What is 523 - 267?", ["246", "256", "266"], 1, "Exchange twice."),
        _q("What is 400 - 165?", ["235", "245", "335"], 0, "Exchange across zero: 10 - 5 = 5, 9 - 6 = 3, 3 - 1 = 2."),
        _q("What is 706 - 358?", ["348", "352", "448"], 0, "16 - 8 = 8, 9 - 5 = 4, 6 - 3 = 3."),
        _q("What is 90 - 46?", ["44", "54", "56"], 0, "10 - 6 = 4, 8 - 4 = 4."),
        _q("Which addition checks 91 - 45 = 46?", ["46 + 45 = 91", "91 + 45 = 46", "46 + 91 = 45"], 0, "Inverse operation."),
        _q("What is 612 - 385?", ["227", "237", "327"], 0, "12 - 5 = 7, 0 - 8 needs an exchange: 10 - 8 = 2, 5 - 3 = 2."),
        _q("1 hundred is the same as how many tens?", ["1", "10", "100"], 1, "10 tens make 1 hundred."),
    ],
    "Upload a photo of your six column subtractions, checks and story problem.",
    "Find a three-digit subtraction that needs exchanging in the ones and the tens columns, and show your check.",
    [("subtract", "To take one number away from another."), ("exchange", "To swap one of a place for ten of the next place down."), ("difference", "The answer to a subtraction."),
     ("column", "A line of digits going down."), ("inverse", "The opposite operation."), ("check", "To test that an answer is right."), ("zero", "The digit that holds an empty place.")],
    [],
    _sort("How many exchanges?", "What does each subtraction need? Tap a group, then press Check.",
          ["No exchange", "Exchange once", "Exchange across zero"],
          [("87 - 34", 0), ("59 - 16", 0), ("468 - 215", 0), ("62 - 18", 1), ("71 - 39", 1), ("453 - 128", 1), ("304 - 157", 2), ("500 - 243", 2), ("805 - 368", 2)]),
    [
        _wc("The answer to a subtraction is the ___.", ["difference", "diference", "differance"], 0, "Difference has ff."),
        _wc("To swap one ten for ten ones is to ___.", ["exchange", "exchang", "exchenge"], 0, "Exchange ends ange."),
        _wc("Addition and subtraction are ___ operations.", ["inverse", "inverce", "invers"], 0, "Inverse ends erse."),
    ],
    [
        {"key": "s", "label": "Column subtractions", "hint": "Photograph your six with exchanges shown."},
        {"key": "c", "label": "Checks", "hint": "Show the addition check for each."},
        {"key": "t", "label": "Story", "hint": "Write a story that needs an exchange."},
    ],
    ["Subtracting the smaller digit from the larger whatever the position.", "Forgetting to reduce the tens or hundreds after exchanging.", "Getting stuck when the tens digit is zero.", "Putting the smaller number on top.", "Not checking by adding."],
    [{"title": "Spend and Save", "description": "Pretend you have $500. List three purchases and subtract each in columns. Check every answer by adding.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 43, 44. Part B: 25, 35, 32. Part C: 217, 256, 355. Part D: 147, 257. Part E: 257 + 243 = 500.",
), "Use place value blocks to show exchanging, especially across a zero. Always finish with the adding check.")

WEEK_3_MATHS = [M1, M2, M3]
