"""Stage 2 English, Week 2, Lessons 2 and 3. Videos verified by YouTube oEmbed on 2026-10-07. Not yet registered in lesson_library.py."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W2L2 = build(
    "s2-eng-w02-l2-story-planning", "Story Mountain: Plan Before You Write",
    "The Plot Mountain is waiting! Plan an original story step by step so nothing falls off the cliff.",
    "Writing: planning a narrative",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Plans a narrative using a plot structure, character and setting.",
     "EN2-VOCAB-01": "Uses plot terms and chooses precise words for characters and settings.",
     "EN2-SPELL-01": "Applies vowel team spelling and strategies to plan words."},
    "We are learning to plan a story with a beginning, middle and end before we write it.",
    ["I can generate ideas and choose the best one.", "I can plan the five parts of a plot on a story mountain.",
     "I can create a main character with a want and a problem.", "I can describe a setting with sensory details.", "I can spell my planning words correctly."],
    ["plan", "brainstorm", "protagonist", "obstacle", "sensory", "orientation", "complication", "draft"],
    ["Paper or notebook", "Pencil", "Coloured pencils"],
    "Child knows the parts of a story from Lesson 1 of this week. All planning steps are taught here.",
    "Planning is what separates a story that holds together from one that wanders. A plan does not have to be long. It answers four questions: Who is the story about and what do they want? Where and when does it happen? What goes wrong? How does it end?\n\nThe story mountain turns those answers into five boxes: introduction (exposition), rising action, climax, falling action and resolution. When you write from a plan you spend your energy on good sentences, not on wondering what comes next.\n\nGood planners also decide on one big idea first. A small idea told well beats a huge idea rushed.",
    [
        _step("1", "Generating ideas: brainstorm and choose", "A brainstorm is a fast list of ideas with no judging. Set a timer for two minutes and write every idea that comes: characters, places, problems.\n\nThen choose by asking: Which idea can I tell in one page? Which idea do I care about? Which has a clear problem?\n\nA useful trick is the what if question. What if a lighthouse keeper found a message in a bottle? What if the school bus flew? One what if gives you a character, a setting and a problem in one go.",
              "Brainstorm: lost puppy, haunted library, robot at school, storm at sea. Choose: robot at school, because the problem is clear (it does not know the rules) and I can finish it in a page.",
              "One strong what if beats five weak ideas.",
              ("What is a brainstorm?", ["A quick list of ideas with no judging", "A final copy", "A spelling test"], 0, "Brainstorming collects ideas fast.")),
        _step("2", "The main character: want and problem", "The main character (protagonist) needs two things: a want and a problem standing in the way. A character who wants nothing makes a boring story.\n\nGive your character a name, one or two traits and one want. Then add an obstacle: something that makes getting it hard. The want and the obstacle together create the plot.\n\nChoose traits you can show through actions: a careful boy double-checks the lock three times.",
              "Mia (curious, brave) wants to find the source of a strange sound in the attic. Obstacle: it is night and her torch is flat.",
              "Want plus obstacle equals story.",
              ("What does a main character need to make a story?", ["A want and an obstacle", "A long name", "Lots of friends"], 0, "A want with something in the way creates the plot.")),
        _step("3", "Setting with the five senses", "A strong setting uses the senses: what can the character see, hear, smell, feel and taste? Choose three senses and a mood word for the place.\n\nPlan the setting before you write: place, time, weather and mood. Then pick two sensory details that match the mood. A creepy attic: dust, creaking boards, a chilly draught.\n\nSetting can also help the problem. A storm makes the lost kite harder to catch.",
              "Place: attic. Time: midnight. Mood: eerie. See: dusty trunks and cobwebs. Hear: floorboards creaking. Feel: cold air on her neck.",
              "Pick details that match the mood.",
              ("Which detail makes an eerie attic?", ["Creaking boards and cobwebs", "Bright sunshine and music", "A cheerful kitchen"], 0, "The details match an eerie mood.")),
        _step("4", "Filling the story mountain", "Draw a mountain with five labels. Introduction: who, where, when, and the want. Rising action: the first obstacle and things getting harder (two or three events). Climax: the biggest moment, where the character faces the problem. Falling action: what happens straight after. Resolution: how it ends and what the character learns.\n\nWrite only a short phrase in each box. The plan is for you, not for marking.\n\nCheck that each event causes the next. Use because and so to test it: Mia hears a sound, so she climbs the stairs.",
              "Introduction: Mia hears a sound in the attic at midnight. Rising: torch fails; she finds a trunk that moves. Climax: she opens it and a kitten leaps out. Falling: she carries it downstairs. Resolution: Mia keeps the kitten and is proud of being brave.",
              "If you cannot join two events with because or so, something is missing.",
              ("What goes in the rising action?", ["Events as the problem grows", "The ending", "The title"], 0, "Rising action builds the problem.")),
        _step("5", "Beginning, middle and end checks", "Before you write, test the plan. Beginning: do I know who, where and what they want? Middle: are there two or three events, each harder than the last? End: does the climax solve or change the problem, and does the resolution feel finished?\n\nA common problem is an ending that says 'and then it was all a dream' or 'and everything was fine'. Aim for an ending where the character does something to solve the problem.\n\nRead your plan aloud. If it sounds like a story, it is ready.",
              "Test: Mia solves the problem herself by opening the trunk. That is a strong ending because she acts.",
              "The character should solve the problem, not luck.",
              ("Which ending is stronger?", ["Mia opens the trunk and rescues the kitten", "Then it was all a dream"], 0, "The character acts to solve the problem.")),
        _step("6", "Spelling: plan words", "Spell the words you will use. Try vowel teams: plain, trail, dream, coast. For tricky words use Look, Say, Cover, Write, Check: character (ch makes a k sound), beginning (double n), ending, adventure.\n\nKeep a list of planning words on the side of your page. It saves stopping to wonder how to spell a word while you write.\n\nNew Word Hoard words: character, beginning, adventure, mystery, obstacle, climax.",
              "character: ch-a-r-a-c-t-e-r. Memory trick: Ch says k, like in chorus.",
              "Write the word list first so your story can flow.",
              ("How many n letters are in 'beginning'?", ["2", "3", "1"], 0, "begin + ning doubles the n.")),
    ],
    "Idea: What if a robot arrived at school? Character: Zip, a curious robot who wants to make a friend. Obstacle: he does not understand jokes. Setting: school playground at lunch, noisy, smells of cut oranges. Mountain: Introduction, Zip arrives and wants a friend. Rising: he tries to join a game and fails; he repeats a joke wrongly. Climax: a child falls; Zip uses his arms to catch her. Falling: the children cheer. Resolution: Zip is invited to play.",
    "In your notebook: 1) Brainstorm six what if ideas in two minutes and circle your best. 2) Write a character card (name, two traits, want, obstacle). 3) Write a setting card (place, time, mood, two sensory details). 4) Draw a story mountain and fill the five boxes with short phrases. 5) Check each event with because or so.",
    "Plan a complete original story. Create the brainstorm, character card, setting card and a full story mountain. Write one sentence on how your ending solves the problem. Do not write the story yet: the next lessons are for drafting.",
    "Which part of the plan did you find easiest, and which needs more thinking?",
    "Did I brainstorm and choose? Does my character have a want and an obstacle? Does the setting use the senses? Is every box on my mountain filled? Does my ending solve the problem?",
    [
        _q("What is a brainstorm?", ["A quick list of ideas", "A final draft", "A spelling list"], 0, "It collects ideas."),
        _q("Which makes a character interesting?", ["A want and an obstacle", "A long name", "A pet"], 0, "Want plus obstacle creates a story."),
        _q("What goes in the introduction?", ["Characters, setting and the want", "The ending", "The climax"], 0, "The introduction orients the reader."),
        _q("What is the climax?", ["The biggest moment", "The first event", "The title"], 0, "It is the turning point."),
        _q("Which sense detail suits a stormy sea?", ["Waves crashing, cold spray", "Warm sun, birdsong", "Quiet classroom"], 0, "They match the mood."),
        _q("Which linking word tests cause and effect?", ["because", "purple", "under"], 0, "Because shows that one event causes another."),
        _q("Which ending is stronger?", ["The character solves the problem", "It was all a dream", "And then it ended"], 0, "The character acts."),
        _q("Which is spelt correctly?", ["begining", "beginning", "beggining"], 1, "Double the n."),
        _q("Which is spelt correctly?", ["adventure", "advencher", "adventur"], 0, "adventure ends in -ure."),
        _q("How long should a plan be?", ["Short phrases in each box", "A full page per box", "No plan"], 0, "A plan is for you, so phrases are enough."),
    ],
    "Upload a photo of your brainstorm, character card, setting card and story mountain.",
    "Plan the same story twice with two different endings. Which is stronger and why?",
    [("plan", "Deciding what to write before you write."), ("brainstorm", "A fast list of ideas."), ("protagonist", "The main character."),
     ("obstacle", "Something in the way of what the character wants."), ("sensory", "Using the five senses."), ("orientation", "The start: who, where and when."),
     ("complication", "The problem that begins the action."), ("draft", "A first version of your writing.")],
    [
        _video("Plot Mountain! The Plot Diagram Song (Scratch Garden)", "NpWHZJZQDSE",
               "Watch the five stages of the plot mountain. Pause after each stage and say what would go there in your own story.",
               "Draw the mountain on paper and write the five labels in order.",
               ("Which stage comes right after the climax?", ["Falling action", "Rising action", "Introduction"], 0, "After the climax the story comes down the mountain.")),
    ],
    _sort("Plan part sorter", "Which part of the plan does each idea belong to? Tap a part, then Check.",
          ["Character", "Setting", "Obstacle", "Ending"],
          [("a curious robot named Zip", 0), ("a brave girl who wants to find a kitten", 0), ("a noisy playground at lunchtime", 1), ("midnight in a dusty attic", 1), ("the torch has no batteries", 2), ("he does not understand jokes", 2), ("Zip is invited to play", 3), ("Mia keeps the kitten", 3)]),
    [
        _wc("A protagonist is the ___.", ["main character", "setting", "ending"], 0, "Protagonist means main character."),
        _wc("An obstacle is something that ___.", ["is in the way", "ends a story", "is a place"], 0, "It blocks what the character wants."),
        _wc("Sensory details use the ___.", ["five senses", "alphabet", "calendar"], 0, "See, hear, smell, feel, taste."),
        _wc("Which spelling is correct?", ["character", "karacter", "charactor"], 0, "ch makes a k sound."),
        _wc("A draft is a ___ version.", ["first", "final", "last"], 0, "A draft is the first version."),
        _wc("A plan should be written in ___.", ["short phrases", "long paragraphs", "perfect sentences"], 0, "A plan is for you."),
    ],
    [
        {"key": "ideas", "label": "Brainstorm", "hint": "Six what if ideas."},
        {"key": "character", "label": "Character", "hint": "Name, two traits, want and obstacle."},
        {"key": "setting", "label": "Setting", "hint": "Place, time, mood and two sensory details."},
        {"key": "mountain", "label": "Story mountain", "hint": "Five short phrases, one per part."},
    ],
    ["Writing the story instead of planning it.", "A character with no want.", "A plan where events do not cause each other.", "An ending where luck solves the problem."],
    [{"title": "Plan Swap", "description": "Swap plans with a family member and ask them to tell the story back.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check the character has a want and an obstacle, the setting uses at least two senses, the mountain has five parts, and the events connect with because or so. Sort: Character: robot Zip, brave girl. Setting: playground, attic. Obstacle: torch, jokes. Ending: invited to play, keeps kitten.",
)

W2L3 = build(
    "s2-eng-w02-l3-nouns-verbs-adjectives", "Word Class Workshop: Nouns, Verbs, Adjectives",
    "The Word Machine is jammed! Learn the three word jobs, sort them, and then upgrade weak sentences into strong ones.",
    "Language: nouns, verbs and adjectives",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Uses nouns, verbs and adjectives to build precise sentences.",
     "EN2-VOCAB-01": "Chooses stronger words for nouns, verbs and adjectives.",
     "EN2-SPELL-01": "Applies suffix rules when making adjectives and verbs."},
    "We are learning to identify and choose nouns, verbs and adjectives to make our writing precise.",
    ["I can identify common, proper and abstract nouns.", "I can identify action, saying, thinking and being verbs.",
     "I can use adjectives to describe a noun precisely.", "I can upgrade a weak sentence with stronger words.", "I can spell adjectives and verbs with -ing, -ed, -y and -ful endings."],
    ["noun", "verb", "adjective", "common noun", "proper noun", "abstract noun", "action verb", "precise"],
    ["Paper or notebook", "Pencil"], "Child can write simple sentences. The three word classes are taught from scratch.",
    "Every word in a sentence has a job. Nouns name people, places and things. Verbs say what is happening. Adjectives describe nouns. Good writers choose each word on purpose.\n\nA sentence with weak words is vague: 'The big dog went to the place.' A sentence with strong words is precise: 'The enormous mastiff stalked across the playground.'\n\nThis lesson teaches the three jobs, then shows how to upgrade weak words. This is the first step to vivid writing in the story you planned.",
    [
        _step("1", "Nouns: naming words", "A noun names a person, place, animal, thing or idea. A common noun names a general kind: girl, city, river. A proper noun names one particular person, place or thing and starts with a capital: Mia, Sydney, the Murray River.\n\nAbstract nouns name things you cannot touch: bravery, kindness, freedom, happiness.\n\nTest: can you put 'the' or 'a' in front of it? If so, it is probably a noun.",
              "Common: teacher, park. Proper: Mr Lee, Hyde Park. Abstract: courage, friendship.",
              "Proper nouns always get a capital letter.",
              ("Which is a proper noun?", ["Brisbane", "city", "river"], 0, "Brisbane names one particular place.")),
        _step("2", "Verbs: the action", "A verb tells what someone or something does or is. Action verbs show doing: run, whisper, climb. Saying verbs show speech: shouted, murmured. Thinking verbs show thought: wondered, believed. Being verbs show a state: is, are, was, were.\n\nVerbs are the engine of a sentence, and every sentence needs one. Strong verbs replace weak ones: not 'walked', but 'strolled', 'crept' or 'marched'.\n\nTest: can you put 'I' or 'he' in front of it and make a sensible sentence?",
              "Action: dash, dive. Saying: whispered, yelled. Thinking: imagined, decided. Being: is, was.",
              "Pick a verb that shows how the action happens.",
              ("Which is a stronger verb than 'walked'?", ["crept", "went", "got"], 0, "Crept shows how the person moved.")),
        _step("3", "Adjectives: describing words", "An adjective describes a noun. It answers: what kind? how many? which one? Examples: tall tower, three birds, the muddy track.\n\nPut adjectives before the noun or after a verb of being: The sky is cloudy.\n\nAvoid weak adjectives like nice, good and big. Choose specific ones: enormous, delicious, grumpy.",
              "The nice dog became the gentle, golden retriever. The big house became the crumbling, three-storey mansion.",
              "One precise adjective is better than three weak ones.",
              ("Which adjective is most precise?", ["enormous", "big", "nice"], 0, "Enormous is specific.")),
        _step("4", "Spotting all three in a sentence", "To find the word jobs, first find the verb (what is happening?), then ask who or what is doing it (noun), then see what describes the nouns (adjectives).\n\nIn 'The tiny robot rolled across the noisy playground', the verb is rolled, the nouns are robot and playground, and the adjectives are tiny and noisy.\n\nSome words change job depending on how they are used. 'Light' is a noun in 'Turn on the light', a verb in 'Light the candle' and an adjective in 'a light jacket'.",
              "The hungry wolf crept through the silent forest. Verb: crept. Nouns: wolf, forest. Adjectives: hungry, silent.",
              "The job a word does in the sentence decides its class.",
              ("In 'The brave knight raced home', which word is the verb?", ["raced", "brave", "knight"], 0, "Raced is the action.")),
        _step("5", "Upgrading a weak sentence", "Take a weak sentence and improve it in three steps. Step 1: replace the weak verb with a strong one. Step 2: make the noun more specific. Step 3: add one precise adjective.\n\nDo not add too many. If every noun has three adjectives the reader gets tired. Choose words that fit the mood of the story.",
              "Weak: The man went to the shop. Strong: The grumpy shopkeeper stormed into his shop.",
              "Change the verb first. It often makes the biggest difference.",
              ("What is the first step to upgrade a sentence?", ["Replace a weak verb", "Add five adjectives", "Delete the noun"], 0, "A strong verb gives the biggest improvement.")),
        _step("6", "Spelling: endings on verbs and adjectives", "Verbs and adjectives take endings. Use the rules from Week 1. Drop the silent e: hope + ing = hoping. Double the final consonant after a short vowel: run + ing = running. Change y to i: carry + ed = carried.\n\nMany adjectives are made from nouns with endings: -y (rainy, muddy), -ful (careful, helpful), -less (careless). Note that mud + y = muddy (doubled d).\n\nNew Word Hoard words: enormous, delicious, precise, shopkeeper, muddy, careful.",
              "stir + ed = stirred. fun + y = funny. care + ful = careful.",
              "Ask: short vowel, one consonant? Double it.",
              ("What is mud + y?", ["muddy", "mudy", "mudddy"], 0, "Double the d after a short vowel.")),
    ],
    "Weak sentence: The dog went into the place. Step 1, strong verb: The dog bounded into the place. Step 2, specific nouns: The retriever bounded into the park. Step 3, precise adjective: The excited golden retriever bounded into the muddy park. Nouns: retriever, park. Verb: bounded. Adjectives: excited, golden, muddy.",
    "In your notebook: 1) Sort ten words into noun, verb or adjective: whisper, mountain, brave, crept, kindness, enormous, Sydney, delicious, laughed, treasure. 2) Underline the verb, circle the nouns and box the adjectives: The grumpy troll stomped across the wooden bridge. 3) Upgrade three weak sentences: She went home. The big man looked at the thing. It was a nice day. 4) Write three ing/ed words using the spelling rules.",
    "Write five sentences for your planned story, using at least two strong verbs, two precise adjectives and two specific nouns in each. Underline the verbs, circle the nouns and box the adjectives in two of them.",
    "Which word class do you find easiest to upgrade: nouns, verbs or adjectives? Why?",
    "Did I sort the words correctly? Did I mark verbs, nouns and adjectives? Did I use strong verbs and precise adjectives? Are my spellings right?",
    [
        _q("Which is a noun?", ["mountain", "run", "quickly"], 0, "A mountain is a thing."),
        _q("Which is a verb?", ["whisper", "brave", "happiness"], 0, "Whisper is an action."),
        _q("Which is an adjective?", ["enormous", "table", "jump"], 0, "Enormous describes a noun."),
        _q("Which is a proper noun?", ["Sydney", "city", "road"], 0, "It names one particular place."),
        _q("Which is an abstract noun?", ["kindness", "book", "bike"], 0, "You cannot touch kindness."),
        _q("Which verb is strongest?", ["stormed", "went", "moved"], 0, "Stormed shows how."),
        _q("In 'The tiny robot rolled home', the adjective is:", ["tiny", "robot", "rolled"], 0, "Tiny describes the robot."),
        _q("What is mud + y?", ["muddy", "mudy", "mudey"], 0, "Double the d."),
        _q("What is run + ing?", ["running", "runing", "runeing"], 0, "Double the n."),
        _q("What is care + ful?", ["careful", "carefull", "carful"], 0, "Keep the e and use one l."),
    ],
    "Upload a photo of your sorted word list, your marked sentence, your three upgrades and your five story sentences.",
    "Write one sentence where the same word is a noun, then a verb in the next sentence. Explain how you know.",
    [("noun", "A naming word."), ("verb", "A doing, saying, thinking or being word."), ("adjective", "A word that describes a noun."),
     ("common noun", "The general name of a person, place or thing."), ("proper noun", "The name of one particular person, place or thing."),
     ("abstract noun", "A thing you cannot touch, like kindness."), ("action verb", "A word that shows what someone does."), ("precise", "Exact and clear.")],
    [
        _video("Nouns, Verbs & Adjectives for Kids (Wombat School, Australian curriculum)", "984ntq-7x58",
               "Watch how to spot nouns, verbs and adjectives in simple sentences. Pause and try each example yourself.",
               "Read steps 1 to 3 and find five nouns, five verbs and five adjectives in your own book.",
               ("What does an adjective do?", ["Describes a noun", "Shows an action", "Names a person"], 0, "An adjective describes a noun.")),
        _video("Learn About Nouns, Adjectives & Verbs (StoryBots)", "_II6ySgUtWc",
               "Watch how swapping a word for a different word of the same type changes a sentence.",
               "Swap one noun, one verb and one adjective in a sentence from your book.",
               ("What is a verb?", ["A word for an action", "A person", "A place"], 0, "A verb describes an action.")),
        _video("Let's Review Nouns, Verbs and Adjectives", "U2l3BFthsD0",
               "Watch the review. Test yourself before each answer appears.",
               "Write one noun, verb and adjective sentence of your own.",
               ("A noun is a person, place or...", ["thing", "action", "colour"], 0, "A noun is a person, place or thing.")),
    ],
    _sort("Word class sorter", "Which job does each word do? Tap a job, then Check.",
          ["Noun", "Verb", "Adjective"],
          [("mountain", 0), ("Sydney", 0), ("kindness", 0), ("treasure", 0), ("whisper", 1), ("crept", 1), ("laughed", 1), ("stormed", 1), ("enormous", 2), ("delicious", 2), ("brave", 2), ("muddy", 2)]),
    [
        _wc("Which is a noun?", ["bridge", "cross", "narrow"], 0, "A bridge is a thing."),
        _wc("Which is a verb?", ["sprinted", "swift", "road"], 0, "Sprinted is an action."),
        _wc("Which is an adjective?", ["gigantic", "giant (as in a giant)", "grow"], 0, "Gigantic describes."),
        _wc("Which word needs a capital?", ["Australia", "country", "island"], 0, "Proper noun."),
        _wc("Which is correct?", ["stopped", "stoped", "stopt"], 0, "Double the p before -ed."),
        _wc("Which is correct?", ["hoping", "hopeing", "hopping (to hope)"], 0, "Drop the e."),
        _wc("Which is the strongest verb?", ["charged", "went", "got"], 0, "Charged shows how."),
        _wc("Which is the most precise adjective?", ["crumbling", "nice", "good"], 0, "Crumbling is specific."),
    ],
    [
        {"key": "sentences", "label": "My five sentences", "hint": "Write five sentences for your planned story."},
        {"key": "verbs", "label": "Strong verbs", "hint": "List the strong verbs you used."},
        {"key": "adjectives", "label": "Precise adjectives", "hint": "List the precise adjectives you used."},
        {"key": "upgrade", "label": "Best upgrade", "hint": "Show one weak sentence and your upgrade."},
    ],
    ["Calling a verb-like word a noun (running is a verb in 'she is running').", "Using weak words like nice, good and big.", "Adding too many adjectives.", "Forgetting capital letters on proper nouns."],
    [{"title": "Word Detective", "description": "Find ten strong verbs in a book and copy the sentences.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "1) Nouns: mountain, kindness, Sydney, treasure. Verbs: whisper, crept, laughed. Adjectives: brave, enormous, delicious. 2) Verb: stomped. Nouns: troll, bridge. Adjectives: grumpy, wooden. 3) Answers vary: strong verb, specific noun and one precise adjective in each. 4) Sample: running, carried, stopped.",
)

LESSONS = [W2L2, W2L3]
