"""Stage 2 Maths, Week 4 of the programme. Three lessons: multiplication and division facts for 6, 7, 8 and 9, then problem solving (MA2-MR-01).
Loaded automatically by _register_maths in lesson_library.py. Videos are attached in a later pass."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from lesson_library_s2_maths_w1 import _maths

M1 = _maths(build(
    "s2-math-w04-l1-sixes-and-eights", "Sixes and Eights: Doubling Strategies",
    "The Treasure Vault has two heavy doors marked 6 and 8. Doubling is the key that opens both.",
    "Number: multiplication facts and related division",
    ["MA2-MR-01"],
    {"MA2-MR-01": "Primary. Learns the 6 and 8 multiplication facts with doubling and splitting strategies, and the related division facts."},
    "We are learning the 6 and 8 times tables using doubling and splitting strategies.",
    ["I can find a 6 fact by doubling a 3 fact.", "I can find a 6 fact by adding a 5 fact and one more group.", "I can find an 8 fact by doubling three times.", "I can use 10 x a number minus 2 x a number for 8s.", "I can write the related division fact."],
    ["double", "product", "factor", "strategy", "quotient", "times table", "related fact"],
    ["Paper or notebook", "Pencil", "Counters (optional)"],
    "Child knows the 2, 3, 4, 5 and 10 facts and understands division as the opposite of multiplication.",
    "You already know the 3s and 4s. A 6 fact is just a 3 fact doubled. An 8 fact is a 4 fact doubled, or a 2 fact doubled three times.\n\nYou do not have to memorise every fact from scratch. In this lesson you will build the 6 and 8 facts from facts you already know, then use them to divide.",
    [
        _step("1", "Sixes by doubling threes",
              "6 is double 3, so 6 x a number is double 3 x that number.\n\nFor 6 x 4: 3 x 4 = 12, then double 12 to get 24. For 6 x 7: 3 x 7 = 21, double 21 = 42. For 6 x 8: 3 x 8 = 24, double 24 = 48.\n\nThe 6s table is 6, 12, 18, 24, 30, 36, 42, 48, 54, 60.",
              "6 x 7: 3 x 7 = 21 and 21 + 21 = 42.",
              "Find the 3 fact, then double it.",
              ("What is 6 x 7?", ["36", "42", "48"], 1, "3 x 7 = 21 and double 21 is 42.")),
        _step("2", "Sixes as fives plus one more",
              "6 is also 5 + 1. So 6 x a number is 5 x the number plus one more of the number.\n\nFor 6 x 6: 5 x 6 = 30, plus 6 gives 36. For 6 x 9: 5 x 9 = 45, plus 9 gives 54.\n\nUse whichever strategy feels quicker. Check one with the other.",
              "6 x 8: 5 x 8 = 40 and 40 + 8 = 48. This matches the doubling answer.",
              "Do the 5 fact, then add one more group.",
              ("What is 6 x 9?", ["54", "56", "63"], 0, "5 x 9 = 45, plus 9 is 54.")),
        _step("3", "Eights by doubling three times",
              "8 is double double double 1. To find 8 x a number, double the number, double again, then double again.\n\nFor 8 x 6: 6 doubled is 12, doubled is 24, doubled is 48. For 8 x 7: 7, 14, 28, 56.\n\nThe 8s table is 8, 16, 24, 32, 40, 48, 56, 64, 72, 80.",
              "8 x 4: 4, 8, 16, 32. So 8 x 4 = 32.",
              "Double, double, double.",
              ("What is 8 x 7?", ["54", "56", "64"], 1, "7, 14, 28, 56.")),
        _step("4", "Eights from tens, and division",
              "8 is 10 take away 2. So 8 x a number is 10 x the number minus 2 x the number.\n\nFor 8 x 9: 10 x 9 = 90 and 2 x 9 = 18, so 90 - 18 = 72. For 8 x 8: 80 - 16 = 64.\n\nEvery fact gives a division fact. 6 x 7 = 42 so 42 / 6 = 7 and 42 / 7 = 6. 8 x 6 = 48 so 48 / 8 = 6.",
              "48 / 6: ask 6 times what is 48? 6 x 8 = 48, so 8.",
              "Division is multiplication backwards.",
              ("What is 8 x 9?", ["72", "81", "64"], 0, "90 - 18 = 72.")),
    ],
    "Problem: 6 x 8. Double strategy: 3 x 8 = 24, double 24 = 48. Fives strategy: 5 x 8 = 40, plus 8 = 48. Both give 48. Related division: 48 / 6 = 8 and 48 / 8 = 6.",
    "Work in your notebook. Part A (double the 3 fact): 6 x 4, 6 x 5, 6 x 7. Part B (5 fact plus one more): 6 x 6, 6 x 8, 6 x 9. Part C (double three times): 8 x 3, 8 x 6, 8 x 7. Part D (10 take away 2): 8 x 9 and 8 x 8. Part E (division): 42 / 6, 48 / 8, 54 / 6.",
    "Stage 1 (build): make a table of the 6s and the 8s up to 10 x each.\nStage 2 (strategy): beside four facts, write the strategy you used.\nStage 3 (check): solve two facts in a second way to prove them.\nStage 4 (story): write one story problem for a 6 fact and one for an 8 fact and solve both.",
    "Write the answers in your notebook and explain one strategy aloud.",
    "Did I make both tables? Did I name a strategy for four facts? Did I check two a second way? Did I write two stories?",
    [
        _q("What is 6 x 6?", ["30", "36", "42"], 1, "5 x 6 = 30, plus 6."),
        _q("What is 6 x 8?", ["42", "48", "54"], 1, "3 x 8 = 24, doubled is 48."),
        _q("What is 6 x 3?", ["18", "24", "9"], 0, "Three 6s is 18."),
        _q("What is 8 x 4?", ["24", "32", "36"], 1, "4, 8, 16, 32."),
        _q("What is 8 x 8?", ["56", "64", "72"], 1, "80 - 16 = 64."),
        _q("What is 8 x 5?", ["35", "40", "45"], 1, "Eight 5s is 40."),
        _q("What is 48 / 6?", ["6", "7", "8"], 2, "6 x 8 = 48."),
        _q("What is 56 / 8?", ["6", "7", "8"], 1, "8 x 7 = 56."),
        _q("6 x 7 is double which fact?", ["3 x 7", "6 x 3", "7 x 7"], 0, "6 is double 3."),
        _q("What is 8 x 9?", ["72", "81", "64"], 0, "90 - 18 = 72."),
    ],
    "Upload a photo of your 6s and 8s tables, strategies and story problems.",
    "Find a number that is in both the 6s and 8s tables below 60, and explain how you found it.",
    [("double", "To multiply by 2."), ("product", "The answer to a multiplication."), ("factor", "A number you multiply to make a product."),
     ("strategy", "A plan for solving a problem."), ("quotient", "The answer to a division."), ("times table", "A list of multiples of one number."), ("related fact", "A fact that uses the same three numbers.")],
    [],
    _sort("Which table?", "Which times table does each fact come from? Tap a table, then press Check.",
          ["6 times table", "8 times table"],
          [("6 x 7 = 42", 0), ("6 x 9 = 54", 0), ("6 x 5 = 30", 0), ("6 x 6 = 36", 0), ("6 x 8 = 48", 0), ("8 x 7 = 56", 1), ("8 x 4 = 32", 1), ("8 x 9 = 72", 1), ("8 x 8 = 64", 1)]),
    [
        _wc("To multiply by 2 is to ___.", ["double", "dubble", "doble"], 0, "Double has ou."),
        _wc("The answer to a multiplication is the ___.", ["product", "produck", "prodcut"], 0, "Product has duct."),
        _wc("A plan for solving a problem is a ___.", ["strategy", "stratagy", "stratergy"], 0, "Strategy has teg."),
    ],
    [
        {"key": "t", "label": "My 6s and 8s tables", "hint": "Photograph both tables."},
        {"key": "s", "label": "Strategies", "hint": "Show four facts with the strategy named."},
        {"key": "p", "label": "Stories", "hint": "One story for a 6 fact and one for an 8 fact."},
    ],
    ["Mixing up the 6 and 8 tables.", "Forgetting to double the answer when using the 3 fact.", "Doubling only twice for 8s.", "Subtracting the wrong amount in the 10 take away 2 strategy.", "Not using related division facts."],
    [{"title": "Doubling Cards", "description": "Make flash cards for the 6s and 8s. On the back write the doubling strategy for each. Quiz a family member.", "type": "create", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 24, 30, 42. Part B: 36, 48, 54. Part C: 24, 48, 56. Part D: 72, 64. Part E: 7, 6, 9.",
), "Ask him to explain the strategy before he states the answer. Build the facts from known facts rather than drilling by rote.")


M2 = _maths(build(
    "s2-math-w04-l2-sevens-and-nines", "Sevens and Nines: Splitting and Patterns",
    "Two last locks on the Vault door: the 7 and the 9. Splitting and patterns will crack both.",
    "Number: multiplication facts and related division",
    ["MA2-MR-01"],
    {"MA2-MR-01": "Primary. Learns the 7 and 9 multiplication facts with splitting, turn-around and pattern strategies, and the related division facts."},
    "We are learning the 7 and 9 times tables using splitting, turn-around facts and patterns.",
    ["I can split a 7 fact into a 5 fact and a 2 fact.", "I can use turn-around facts to find the 7s I already know.", "I can find a 9 fact using 10 x a number minus the number.", "I can spot the digit patterns in the 9s.", "I can write the related division fact."],
    ["split", "turn-around", "pattern", "product", "factor", "quotient", "digit"],
    ["Paper or notebook", "Pencil", "Counters (optional)"],
    "Child knows the 2, 3, 4, 5, 6, 8 and 10 facts.",
    "Only a handful of facts are left. 7 x 2, 7 x 3, 7 x 4, 7 x 5, 7 x 6 and 7 x 10 are already in the tables you know, just turned around. The new 7 facts are 7 x 7, 7 x 8 and 7 x 9.\n\nThe 9s have the best patterns of all. You will learn to find any 9 fact quickly and check it with a digit trick.",
    [
        _step("1", "Sevens by splitting",
              "Split 7 into 5 + 2. Then 7 x a number is the 5 fact plus the 2 fact.\n\nFor 7 x 6: 5 x 6 = 30 and 2 x 6 = 12, so 30 + 12 = 42. For 7 x 8: 5 x 8 = 40 and 2 x 8 = 16, so 40 + 16 = 56.\n\nThe 7s table is 7, 14, 21, 28, 35, 42, 49, 56, 63, 70.",
              "7 x 4: 5 x 4 = 20 and 2 x 4 = 8, so 28.",
              "Split 7 into 5 and 2, solve each, then add.",
              ("What is 7 x 6?", ["36", "42", "49"], 1, "30 + 12 = 42.")),
        _step("2", "Sevens and turn-around facts",
              "You already know most of the 7 facts because order does not matter. 7 x 3 = 3 x 7 = 21 and 7 x 4 = 4 x 7 = 28. 7 x 6 = 6 x 7 = 42.\n\nOnly three 7 facts are new: 7 x 7 = 49, 7 x 8 = 56 and 7 x 9 = 63. And 7 x 8 is the same as 8 x 7 from last lesson.\n\nDivision: 49 / 7 = 7, 56 / 7 = 8 and 63 / 7 = 9.",
              "7 x 7: 5 x 7 = 35 and 2 x 7 = 14, so 49.",
              "Use turn-around first, then split the rest.",
              ("What is 7 x 7?", ["42", "49", "56"], 1, "35 + 14 = 49.")),
        _step("3", "Nines from tens",
              "9 is 10 take away 1. So 9 x a number is 10 x the number minus the number.\n\nFor 9 x 6: 10 x 6 = 60, minus 6 gives 54. For 9 x 8: 80 - 8 = 72. For 9 x 7: 70 - 7 = 63.\n\nThe 9s table is 9, 18, 27, 36, 45, 54, 63, 72, 81, 90.",
              "9 x 9: 90 - 9 = 81.",
              "Tens fact, then take away the number.",
              ("What is 9 x 7?", ["56", "63", "72"], 1, "70 - 7 = 63.")),
        _step("4", "Patterns in the nines",
              "Look at the 9s: 18, 27, 36, 45, 54, 63, 72, 81, 90. The digits in every product add up to 9. 3 + 6 = 9, 5 + 4 = 9, 7 + 2 = 9.\n\nThe tens digit is always one less than the number you multiply by. For 9 x 4 the tens digit is 3, and the ones digit is 6 because 3 + 6 = 9. So 9 x 4 = 36.\n\nUse the digit rule to check your answers.",
              "9 x 7: tens digit 6, ones digit 3 (6 + 3 = 9). So 63.",
              "Tens digit is one less, and the digits add to 9.",
              ("Which product of 9 has digits that add to 9?", ["36", "38", "42"], 0, "3 + 6 = 9.")),
    ],
    "Problem: 7 x 8. Split: 5 x 8 = 40 and 2 x 8 = 16. 40 + 16 = 56. Check with turn-around: 8 x 7 = 56 by doubling three times (7, 14, 28, 56). Division: 56 / 7 = 8 and 56 / 8 = 7.",
    "Work in your notebook. Part A (split 7): 7 x 4, 7 x 6, 7 x 8. Part B: 7 x 7, 7 x 9, 7 x 5. Part C (10 take away 1): 9 x 3, 9 x 6, 9 x 8. Part D: 9 x 9 and 9 x 7, showing the tens minus the number. Part E (division): 56 / 7, 72 / 9, 63 / 7.",
    "Stage 1 (build): make a table of the 7s and the 9s up to 10 x each.\nStage 2 (patterns): circle the digit patterns in the 9s and write what you notice.\nStage 3 (check): solve three facts in two ways.\nStage 4 (story): write one story problem for a 7 fact and one for a 9 fact and solve both.",
    "Write the answers in your notebook and show the 9s digit rule aloud.",
    "Did I make both tables? Did I find the patterns in the 9s? Did I check three facts two ways? Did I write two stories?",
    [
        _q("What is 7 x 6?", ["36", "42", "49"], 1, "30 + 12 = 42."),
        _q("What is 7 x 8?", ["54", "56", "63"], 1, "40 + 16 = 56."),
        _q("What is 7 x 9?", ["56", "63", "72"], 1, "35 + 28 = 63."),
        _q("What is 7 x 7?", ["42", "49", "56"], 1, "35 + 14 = 49."),
        _q("What is 9 x 6?", ["54", "56", "63"], 0, "60 - 6 = 54."),
        _q("What is 9 x 8?", ["64", "72", "81"], 1, "80 - 8 = 72."),
        _q("What is 9 x 9?", ["72", "81", "90"], 1, "90 - 9 = 81."),
        _q("What is 63 / 9?", ["6", "7", "8"], 1, "9 x 7 = 63."),
        _q("What is 49 / 7?", ["6", "7", "8"], 1, "7 x 7 = 49."),
        _q("Which product of 9 has digits that add to 9?", ["36", "38", "42"], 0, "3 + 6 = 9."),
    ],
    "Upload a photo of your 7s and 9s tables, the 9s patterns and your story problems.",
    "Explain why the digits in the 9s products always add to 9, or find the one product where they do not look like they do.",
    [("split", "To break a number into two parts."), ("turn-around", "Changing the order of a multiplication without changing the product."), ("pattern", "A rule that repeats."),
     ("product", "The answer to a multiplication."), ("factor", "A number you multiply to make a product."), ("quotient", "The answer to a division."), ("digit", "One of the symbols 0 to 9 used to write numbers.")],
    [],
    _sort("Which table?", "Which times table does each fact come from? Tap a table, then press Check.",
          ["7 times table", "9 times table"],
          [("7 x 6 = 42", 0), ("7 x 8 = 56", 0), ("7 x 9 = 63", 0), ("7 x 4 = 28", 0), ("9 x 5 = 45", 1), ("9 x 7 = 63", 1), ("9 x 8 = 72", 1), ("9 x 3 = 27", 1)]),
    [
        _wc("A rule that repeats is a ___.", ["pattern", "patern", "pattren"], 0, "Pattern has tt."),
        _wc("One of the symbols 0 to 9 is a ___.", ["digit", "digit", "dijit"], 0, "Digit starts with dig."),
        _wc("To break a number into two parts is to ___ it.", ["split", "splitt", "spilt"], 0, "Split has pl."),
    ],
    [
        {"key": "t", "label": "My 7s and 9s tables", "hint": "Photograph both tables."},
        {"key": "p", "label": "9s patterns", "hint": "Show the digit patterns you found."},
        {"key": "s", "label": "Stories", "hint": "One story for a 7 fact and one for a 9 fact."},
    ],
    ["Confusing 7 x 8 with 7 x 7.", "Forgetting to subtract in the 10 take away 1 strategy.", "Not using turn-around facts for the 7s.", "Thinking the 9s digit rule works for numbers beyond 10 x 9.", "Mixing up multiplication and division facts."],
    [{"title": "Nine Patterns", "description": "Write the 9s table in a column and look for every pattern you can find. Write a sentence for each one.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 28, 42, 56. Part B: 49, 63, 35. Part C: 27, 54, 72. Part D: 81, 63. Part E: 8, 8, 9.",
), "The 9s patterns are a real surprise for most children. Let him discover them rather than telling him.")


M3 = _maths(build(
    "s2-math-w04-l3-multiplication-problems", "Multiplication and Division Problems",
    "The Vault keeper leaves puzzles on the door. Use your tables to decide whether to multiply or divide, and to work out leftovers.",
    "Number: multiplicative problem solving",
    ["MA2-MR-01"],
    {"MA2-MR-01": "Primary. Chooses multiplication or division to solve word problems, finds unknowns in number sentences, solves two-step problems, and interprets remainders."},
    "We are learning to choose multiplication or division, solve two-step problems and handle remainders.",
    ["I can tell when a problem needs multiplying and when it needs dividing.", "I can find a missing number in a number sentence.", "I can solve a two-step problem.", "I can find a remainder.", "I can check by using the opposite operation."],
    ["remainder", "equal groups", "number sentence", "unknown", "two-step", "multiplication", "division"],
    ["Paper or notebook", "Pencil", "Counters (optional)"],
    "Child knows the times tables to 10 x 10 and the related division facts.",
    "A baker puts 6 cakes in each box and has 8 boxes. How many cakes? Then she has 50 cakes to put into boxes of 8. How many boxes can she fill, and how many cakes are left?\n\nOne story needs multiplying. The other needs dividing, and it has a leftover. In this lesson you will learn to read a problem carefully, decide what to do, and check your answer.",
    [
        _step("1", "Multiply or divide?",
              "Ask: do I know the size of each group and how many groups? Then MULTIPLY to find the total. Do I know the total and need to share it or group it? Then DIVIDE.\n\n7 rows of 8 chairs: total is unknown, so 7 x 8 = 56. 48 pencils into 6 equal boxes: each box is unknown, so 48 / 6 = 8.\n\nSketching a quick picture helps you see which one it is.",
              "5 bags of 8 marbles: 5 x 8 = 40. 45 stickers shared between 9 children: 45 / 9 = 5.",
              "Total unknown means multiply. Sharing a total means divide.",
              ("There are 7 rows of 8 chairs. How many chairs?", ["15", "56", "54"], 1, "7 x 8 = 56.")),
        _step("2", "Find the missing number",
              "Sometimes a number is missing from the sentence: 9 x ? = 63. Ask yourself: 9 times what is 63? Or turn it into a division: 63 / 9 = 7.\n\n? x 6 = 36 is the same as 36 / 6 = 6. 63 / ? = 7 is the same as 63 / 7 = 9.\n\nPut your answer back in to check.",
              "8 x ? = 56: think 56 / 8 = 7. Check 8 x 7 = 56.",
              "Use the related fact to find the unknown.",
              ("9 x ? = 63. What is the missing number?", ["6", "7", "8"], 1, "63 / 9 = 7.")),
        _step("3", "Two-step problems",
              "Some problems need two steps. Solve the first, then use the answer in the second.\n\n4 boxes with 8 cards each, then 5 cards are given away. Step 1: 4 x 8 = 32. Step 2: 32 - 5 = 27.\n\nWrite each step as its own number sentence so you can check your working.",
              "3 packs of 9 stickers and 6 more: 3 x 9 = 27, then 27 + 6 = 33.",
              "Two steps, two number sentences.",
              ("5 boxes of 6 pens, then 4 pens are lost. How many pens are left?", ["24", "26", "30"], 1, "5 x 6 = 30, then 30 - 4 = 26.")),
        _step("4", "Remainders",
              "Sometimes a total does not share equally. The leftover is the REMAINDER.\n\n23 sweets shared among 5 children: 5 x 4 = 20, which is the closest without going over. Each child gets 4, and 23 - 20 = 3 are left over. We write 23 / 5 = 4 remainder 3.\n\nCheck: 5 x 4 = 20 and 20 + 3 = 23.",
              "34 / 5: 5 x 6 = 30, remainder 4. So 6 remainder 4.",
              "Find the closest fact without going over, then subtract.",
              ("23 sweets are shared equally among 5 children. How many are left over?", ["2", "3", "4"], 1, "5 x 4 = 20 and 23 - 20 = 3.")),
    ],
    "Problem: 29 cards are put into groups of 4. How many full groups? Use the 4s table: 4 x 7 = 28, which is the closest without going over. 7 full groups. 29 - 28 = 1 card is left over. So 29 / 4 = 7 remainder 1. Check: 4 x 7 = 28 and 28 + 1 = 29.",
    "Work in your notebook. Part A: write a number sentence and solve: 6 bags of 8 oranges; 54 shared between 9; 7 rows of 9. Part B: find the missing number: 8 x ? = 56, ? x 6 = 36, 63 / ? = 7. Part C: two-step: 4 boxes of 8 cards then 5 given away; 3 packs of 9 stickers and 6 more. Part D: remainders: 34 / 5, 50 / 8, 40 / 7. Part E: write your own two-step story and solve it.",
    "Stage 1 (collect): write four multiplication stories and four division stories.\nStage 2 (solve): write a number sentence for each and solve it.\nStage 3 (extend): make one story a two-step problem and one a remainder problem.\nStage 4 (check): check every answer with the opposite operation.",
    "Write the answers in your notebook and explain one story aloud.",
    "Did I write eight stories? Did I write a number sentence for each? Did I make a two-step and a remainder problem? Did I check every answer?",
    [
        _q("There are 7 rows of 8 chairs. How many chairs?", ["15", "56", "54"], 1, "7 x 8."),
        _q("48 pencils are put into 6 equal boxes. How many in each box?", ["7", "8", "9"], 1, "48 / 6 = 8."),
        _q("9 x ? = 63. What is the missing number?", ["6", "7", "8"], 1, "63 / 9 = 7."),
        _q("Which problem needs division?", ["4 bags of 6 apples: how many apples?", "24 apples shared equally between 4 bags: how many in each?", "6 apples and 4 apples: how many altogether?"], 1, "A total is shared into equal groups."),
        _q("23 sweets are shared equally among 5 children. How many are left over?", ["2", "3", "4"], 1, "5 x 4 = 20, and 23 - 20 = 3."),
        _q("5 boxes of 6 pens, then 4 are lost. How many are left?", ["24", "26", "30"], 1, "30 - 4 = 26."),
        _q("How many 8s are in 72?", ["8", "9", "10"], 1, "8 x 9 = 72."),
        _q("6 x 7 = 42, so 42 / 7 = ?", ["6", "7", "35"], 0, "Related fact."),
        _q("Each ticket costs $7. How much for 8 tickets?", ["$54", "$56", "$15"], 1, "7 x 8 = 56."),
        _q("29 cards are put into groups of 4. How many full groups?", ["6", "7", "8"], 1, "4 x 7 = 28."),
    ],
    "Upload a photo of your eight stories, number sentences and checks.",
    "Write a division problem where the remainder is bigger than you expect, and explain why a remainder can never be as big as the number you divide by.",
    [("remainder", "What is left over after sharing equally."), ("equal groups", "Groups that all have the same number."), ("number sentence", "A sentence written with numbers and symbols."),
     ("unknown", "A number we do not know yet."), ("two-step", "A problem that needs two calculations."), ("multiplication", "Finding the total of equal groups."), ("division", "Sharing or grouping into equal parts.")],
    [],
    _sort("Multiply or divide?", "Which operation solves each story? Tap a group, then press Check.",
          ["Multiply", "Divide"],
          [("5 bags of 8 marbles: how many marbles?", 0), ("7 rows of 6 chairs: how many chairs?", 0), ("9 packs of 4 pens: how many pens?", 0), ("30 lollies shared between 6 friends: how many each?", 1), ("56 eggs put into cartons of 8: how many cartons?", 1), ("45 stickers shared between 9 children: how many each?", 1)]),
    [
        _wc("What is left over after sharing is the ___.", ["remainder", "remainder", "reminder"], 0, "Remainder has main."),
        _wc("A number we do not know yet is the ___.", ["unknown", "unknone", "unowned"], 0, "Unknown starts with un."),
        _wc("A problem needing two calculations is ___.", ["two-step", "two-stepp", "too-step"], 0, "Two-step uses two."),
    ],
    [
        {"key": "s", "label": "Eight stories", "hint": "Photograph your stories with number sentences."},
        {"key": "t", "label": "Two-step and remainder", "hint": "Show one of each."},
        {"key": "c", "label": "Checks", "hint": "Show the opposite-operation check."},
    ],
    ["Multiplying when the problem needs dividing.", "Forgetting the second step.", "Ignoring the remainder or making it bigger than the divisor.", "Not checking with the opposite operation.", "Mixing up which number is the total."],
    [{"title": "Party Planner", "description": "Plan a party for 8 guests. Work out how many packets of snacks you need if each packet has 6 pieces and each guest gets 5. Record each step.", "type": "investigation", "difficulty": "medium", "evidence_type": "photo"}],
    "Part A: 6 x 8 = 48; 54 / 9 = 6; 7 x 9 = 63. Part B: 7, 6, 9. Part C: 27, 33. Part D: 6 r 4, 6 r 2, 5 r 5. Part E: answers vary; check the number sentences.",
), "Have him sketch each story before choosing the operation. Ask him what the remainder means in the story.")

WEEK_4_MATHS = [M1, M2, M3]
