"""Stage 2 English, Week 3 Lesson 1: Predicting and Questioning (Reading and comprehension).
All written work is typed inside the lesson. Spelling (suffixes -ing and -ed) is attached so the lesson is self-contained.
Videos PCtWPYF3y2U (Khan Academy Kids, predictions) and Sd1FlXxpVIw (Reading Rockets, questions before, during and after) found by search. Re-check in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc, _video
from spelling_s2_w1 import _w, _c

WORDS = ["jumping", "jumped", "hopping", "baking", "baked", "stopped"]

PASSAGE = (
    "The Box in the Attic\n\n"
    "Part 1\n"
    "On a rainy Saturday, Zara was helping Grandpa tidy the attic. Behind a pile of old coats she found a small tin box with a rusty lock. A faded card was tied to it with string. It said: 'Open when you are ready for an adventure.' "
    "Grandpa laughed softly. 'I haven't seen that box for fifty years,' he said. 'I lost the key long ago.'\n\n"
    "Part 2\n"
    "Zara turned the box over in her hands. On the lid was a tiny carved star. She had seen a star like that before, but where? She hurried downstairs and stopped in front of the old clock in the hall. In the middle of its face was the very same star. "
    "Zara carefully pushed it, and the star clicked. A little door swung open at the back of the clock, and something silver fell into her hand.\n\n"
    "Part 3\n"
    "It was a key. Zara raced back upstairs, and the key turned with a creak. Inside the box lay a bundle of letters and a hand-drawn map with a red cross under a big oak tree. 'Your grandmother and I buried a time capsule there,' Grandpa whispered. "
    "The rain had stopped, so they grabbed a spade and went out to the garden to find it."
)

LESSON = build(
    "s2-eng-w03-l1-predicting-questioning",
    "Predicting and Questioning",
    "Good readers think ahead and ask questions as they read. Learn to make smart predictions from clues, check them as the story unfolds, and ask questions before, during and after reading.",
    "Reading and comprehension: predicting and questioning",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {
        "EN2-RECOM-01": "Primary. Uses clues from the text to predict what will happen, checks predictions as reading continues, and asks questions about a text.",
        "EN2-VOCAB-01": "Uses words such as predict, clue, evidence, question and revise to talk about reading.",
        "EN2-SPELL-01": "Spells words with the suffixes -ing and -ed, applying the rules for dropping e and doubling the final consonant (week 3 spelling focus).",
    },
    "We are learning to make predictions using clues from the text, and to ask questions before, during and after reading.",
    ["I can make a prediction and give evidence from the text.", "I can check my prediction and change it when I learn more.", "I can ask questions before, during and after reading.", "I can tell the difference between a question answered in the text and one that needs thinking.", "I can add -ing and -ed to words using the spelling rules."],
    ["predict", "prediction", "clue", "evidence", "question", "revise", "suffix", "inference"],
    ["This lesson (everything you need is inside it)"],
    "Child can name story elements, plan a story mountain and use nouns, verbs and adjectives (Weeks 1 and 2).",
    (
        "Why this matters. Strong readers do not just let the words go past. They think ahead, wonder about what is happening and check their ideas as they read. This keeps your mind switched on, helps you remember the story and prepares you to notice how authors build suspense, which you will use when you write your own stories.\n\n"
        "Predicting. A prediction is a smart guess about what will happen next, based on clues. It is not a wild guess. Clues come from the title, the pictures, the words, the setting, what characters say and do, and what you already know. Say your prediction in a full sentence and give your evidence: 'I predict that... because the text says...'.\n\n"
        "Changing your mind. A reader keeps checking. When new information appears, you can confirm your prediction (it was right), or revise it (change it because you now know more). Revising is a sign of a good reader, not a mistake.\n\n"
        "Questioning. Good readers ask questions at every stage. Before reading: What might this be about? During reading: Why did the character do that? What might happen next? After reading: What did I learn? What would I change? Some answers are right there in the text. Others need you to think and use clues, which is called making an inference.\n\n"
        "The routine. 1. Look at the title and any pictures, and make a first prediction. 2. Read a little and stop at a good pause point. 3. Check your prediction, confirm or revise it, and make a new one. 4. Ask one question about the text. 5. Keep going. 6. At the end, look back at your predictions and ask what you learned.\n\n"
        "A quick demonstration. Title: 'The Box in the Attic'. Prediction: 'I predict the box will hold something old and important, because it is in an attic and it is locked.' Question: 'Why was the box hidden?'"
    ),
    [
        _step("1", "What is a prediction?", "A prediction is a smart guess about what will happen next, based on clues. A good reader uses the title, the pictures, the setting and what characters say and do.\n\nA prediction is different from a wild guess because it has evidence.", "The title is 'The Box in the Attic', so I predict the box will hold something old and special.", "A prediction uses clues, not luck.", ("A good prediction is based on...", ["Clues from the text", "A random guess", "The last page only"], 0, "A prediction uses clues.")),
        _step("2", "Give evidence", "Say your prediction in a full sentence and use the word because. The evidence is the clue from the text that made you think it.\n\nThe pattern is: I predict that... because...", "I predict that Zara will find a key, because Grandpa says it was lost long ago and she has just seen a star on the lid.", "Predict, then prove with evidence.", ("Which word links a prediction to evidence?", ["because", "but", "and"], 0, "Because gives the reason.")),
        _step("3", "Confirm or revise", "As you read on, check each prediction. If you were right, you confirm it. If the story went another way, you revise it, which means you change it using what you now know.\n\nThen make a new prediction.", "I predicted the box would hold treasure. The text says it holds letters and a map. I revise: it holds memories and clues to a time capsule.", "Confirm or revise as you read.", ("What does revise mean?", ["Change your idea using new information", "Stop reading", "Copy the text"], 0, "Revising means changing your idea when you learn more.")),
        _step("4", "Ask questions before, during and after", "Before: What might this be about? During: Why did she do that? What might happen next? After: What did I learn? What was the big idea?\n\nYou can write your questions on sticky notes or say them aloud.", "During Part 1: Why does Grandpa laugh softly? During Part 2: Why does the star look familiar?", "Ask questions at every stage.", ("Which is a question to ask during reading?", ["Why did the character do that?", "What is the title?", "Where is the cover?"], 0, "A during-reading question helps you understand what is happening.")),
        _step("5", "Right there or think about it?", "Some questions have answers right there in the text, such as 'What colour was the box?'. Others need you to think and join clues, such as 'How does Grandpa feel about the box?'.\n\nThe second kind asks you to make an inference.", "Right there: The box was tin. Think about it: Grandpa probably feels fond and surprised, because he laughs softly and hasn't seen it for fifty years.", "Some answers are in the text; some need clues.", ("Which needs an inference?", ["What was the box made of?", "How does Grandpa feel about the box?", "What day was it?"], 1, "You have to join clues to work out how he feels.")),
        _step("6", "Spelling focus: -ing and -ed", "Three rules help when adding -ing or -ed. Just add: jump becomes jumping and jumped. Drop the silent e: bake becomes baking and baked. Double the last letter after one short vowel: hop becomes hopping, stop becomes stopped.\n\nSay the word and listen for a short vowel before the end.", "jump + ing = jumping, bake - e + ing = baking, hop + p + ing = hopping.", "Just add, drop the e, or double the last letter.", ("Which is spelled correctly?", ["baking", "bakeing", "bakking"], 0, "Drop the silent e before adding -ing.")),
        _step("7", "Look back at your predictions", "When you finish, look back at your predictions. Which were right? Which did you revise? What clues did you miss? This helps you become better at predicting next time.\n\nThen ask an after-reading question, such as what you learned.", "I predicted a key, and I was right. I did not predict the time capsule, so I revised my idea at the end.", "Reflect on your predictions to improve.", ("Why look back at predictions?", ["To see what clues you used or missed", "To make the story shorter", "There is no reason"], 0, "Looking back helps you notice clues.")),
    ],
    (
        "Work through Part 1 together. Stop at the end and ask: what clues do I have? The box is old and rusty, the card says 'Open when you are ready for an adventure', and Grandpa lost the key long ago. "
        "Prediction: 'I predict that Zara will find the key, because the box is locked and she is curious.' Question: 'Why did Grandpa lose the key?' Now read Part 2. Zara sees a carved star on the lid, then finds the same star on the clock. "
        "Check the prediction: she is getting closer to the key, so it is confirmed so far. New prediction: 'I predict that the star on the clock hides the key, because it matches the lid.' Read on and check: the star clicked and a silver key fell out. Confirmed. "
        "Now ask what the box holds. Prediction: 'I predict that the box will hold something that links Grandpa and Grandma, because the box is old and he says 'I haven't seen it for fifty years'.' Part 3 shows letters and a map. Confirm part of the prediction, and revise the rest: there is also a time capsule."
    ),
    (
        "Type your answers in the practice boxes. Part A: read Part 1 of 'The Box in the Attic' and type a prediction with a because sentence. Part B: type one question you would ask during reading, and say whether the answer is right there or needs thinking. Part C: read Part 2 and type whether your prediction was confirmed or revised. Part D: type the word for each: jump + ing, bake + ed, hop + ing, stop + ed, plan + ed, make + ing. Your parent can check your answers against the answer key."
    ),
    (
        "Read the story one part at a time and stop at each pause to complete the stage. Everything you write goes in the boxes.\n\n" + PASSAGE + "\n\n"
        "Stage 1 (before reading): type a prediction from the title and one question.\n"
        "Stage 2 (after Part 1): type a prediction with 'because' and the clue that you used.\n"
        "Stage 3 (after Part 2): say whether you confirmed or revised your prediction, and type a new one.\n"
        "Stage 4 (after Part 3): look back over your three predictions. Type which was right, which you revised and what you learned.\n"
        "Stage 5 (questions): type one right-there question and one think-about-it question for the story. Give the answer to each.\n"
        "Stage 6 (spell): type your six spelling words and say which rule each one uses."
    ),
    "What clues helped you most when you made your predictions, and did you ever change your mind?", "Did I give predictions with 'because', confirm or revise them, ask questions before, during and after reading, and spell my six words using the rules?",
    [_q("What is a prediction?", ["A smart guess about what happens next using clues", "A summary", "A fact", "The ending"], 0, "A prediction is a smart guess from clues."), _q("Which sentence is the best prediction?", ["I predict she will find the key because the box is locked.", "Something will happen.", "The box is tin.", "It was raining."], 0, "It gives a prediction and evidence."), _q("What does it mean to revise a prediction?", ["Change it using new information", "Delete the story", "Skip the ending", "Read faster"], 0, "Revising means changing your idea when you learn more."), _q("Which question is asked before reading?", ["What might this story be about?", "What did I learn?", "Why did she turn the key?", "How did it end?"], 0, "A before-reading question looks ahead from the title or cover."), _q("In the story, where does Zara find the key?", ["In the garden", "Behind the old clock", "Under the box", "In Grandpa's pocket"], 1, "The star on the clock opens a door with the key behind it."), _q("What clue shows Zara will find the key?", ["The carved star on the lid", "The rain", "The old coats", "The spade"], 0, "The star matches the clock."), _q("Which question needs an inference?", ["What was the box made of?", "How does Grandpa feel when he sees the box?", "What day was it?", "Who found the box?"], 1, "You use clues to work out his feelings."), _q("Which is spelled correctly?", ["hoping (hopping)", "hopping", "hoppping", "hopeing"], 1, "Double the p before adding -ing."), _q("Which is spelled correctly?", ["baking", "bakeing", "bakking", "bakng"], 0, "Drop the silent e before adding -ing."), _q("Which is spelled correctly?", ["stoped", "stopt", "stopped", "stopd"], 2, "Double the p before adding -ed.")],
    "Type your answers in the practice boxes and submit them.", "Extension: choose a book you are reading. Write three predictions at different points, and note which you confirmed and which you revised.",
    [("predict", "To make a smart guess about what will happen next"), ("prediction", "A smart guess based on clues"), ("clue", "A hint in the text or pictures"), ("evidence", "Words in the text that support your idea"), ("question", "Something you ask to understand more"), ("revise", "To change your idea after learning more"), ("suffix", "Letters added to the end of a word, such as -ing or -ed"), ("inference", "An idea you work out by joining clues")],
    [_video("Making Predictions (Khan Academy Kids)", "PCtWPYF3y2U", "Watch how pictures and words give clues. Listen for the word because.", "Read the worked example aloud and practise predicting from it.", ("What is a prediction?", ["An educated guess about what happens next", "A summary", "The end of a story"], 0, "A prediction is an educated guess based on the story.")), _video("Asking questions before, during and after reading (Reading Rockets)", "Sd1FlXxpVIw", "Watch the students ask questions at different times. Think of your own question for each stage.", "Read the teaching section aloud and write a question for each stage.", ("When can readers ask questions?", ["Before, during and after reading", "Only at the end", "Never"], 0, "Readers ask questions at every stage."))],
    _sort("Prediction, question or evidence?", "Sort each statement about 'The Box in the Attic'.", ["Prediction", "Question", "Evidence"], [("I think Zara will find the key.", 0), ("I predict the box holds something special.", 0), ("Why did Grandpa lose the key?", 1), ("What might the map lead to?", 1), ("The text says the box has a rusty lock.", 2), ("There is a star on the lid and on the clock.", 2), ("I predict the clock hides something.", 0), ("Why is the star familiar?", 1)]),
    [_wc("Which is a clue?", ["a carved star", "a guess", "a sticker"], 0, "A carved star is detail in the text."), _wc("Which is correct?", ["jumping", "jumpping", "jumpeing"], 0, "Just add -ing."), _wc("Which is correct?", ["jumpd", "jumped", "jumpt"], 1, "Just add -ed."), _wc("Which is correct?", ["hoping (for hop)", "hopping", "hopeing"], 1, "Double the p."), _wc("Which is correct?", ["baking", "bakeing", "bakeng"], 0, "Drop the e."), _wc("Which is correct?", ["baked", "bakked", "bakeed"], 0, "bake already ends in e so just add d."), _wc("Which is correct?", ["stoped", "stopped", "stopt"], 1, "Double the p."), _wc("Which is a question?", ["Why did she hurry downstairs?", "She hurried downstairs.", "Hurry up!"], 0, "It asks something.")],
    [{"key":"partA","label":"Part A: prediction","hint":"Predict what will happen after Part 1, with a because sentence."}, {"key":"partB","label":"Part B: a question","hint":"Type one question and say if it is right there or think about it."}, {"key":"partC","label":"Part C: confirm or revise","hint":"After Part 2, was your prediction confirmed or revised?"}, {"key":"partD","label":"Part D: suffixes","hint":"jump+ing, bake+ed, hop+ing, stop+ed, plan+ed, make+ing."}, {"key":"before","label":"Before reading","hint":"A prediction from the title and one question."}, {"key":"part1","label":"After Part 1","hint":"Prediction with because, and your clue."}, {"key":"part2","label":"After Part 2","hint":"Confirmed or revised? Then a new prediction."}, {"key":"part3","label":"After Part 3","hint":"Look back: what was right, revised and learned?"}, {"key":"questions","label":"Two questions","hint":"One right-there and one think-about-it, with answers."}, {"key":"spelling","label":"Spelling words","hint":"Type six words and the rule for each."}],
    ["Predicting with no clue from the text", "Sticking with a prediction when the text shows it was wrong", "Asking only questions that have yes or no answers", "Writing a prediction without because", "Adding -ing to a word without dropping e or doubling the last letter"],
    ["Predict what will happen in the next chapter of your book and check tomorrow.", "Write three questions about a film before you watch it."],
    "Part A: accept any sensible prediction with a because, for example: I predict Zara will find the key, because the box is locked and she is curious. Part B: accept any real question, correctly labelled; for example 'Why did Grandpa lose the key?' needs thinking. Part C: accept confirmed or revised if the reasoning is clear. Part D: jumping, baked, hopping, stopped, planned, making. Main task: look for evidence in each prediction, honest confirm/revise decisions and one question of each type. Quiz answers: smart guess from clues; I predict she will find the key because the box is locked; change it using new information; What might this story be about; Behind the old clock; The carved star; How does Grandpa feel; hopping; baking; stopped.",
)

LESSON["spelling"] = {"focus":"Suffixes -ing and -ed", "teaching":"There are three rules. Just add -ing or -ed to most words (jump becomes jumping, jumped). Drop the silent e (bake becomes baking, baked). Double the last letter when a short vowel comes before one final consonant (hop becomes hopping, stop becomes stopped).", "words":[_w("jumping","jump-ing","just add -ing"),_w("jumped","jump-ed","just add -ed"),_w("hopping","hop-p-ing","double the p"),_w("baking","bak-ing","drop the e"),_w("baked","bak-ed","bake ends in e so add d"),_w("stopped","stop-p-ed","double the p")], "check":[_c("Which is spelled correctly?",["hoping","hopping","hopeing"],1,"For hop, double the p."),_c("Which is spelled correctly?",["bakeing","baking","bakking"],1,"Drop the e.")]}
LESSON["spelling_focus"] = "Suffix rules: -ing, -ed"
LESSON["hoard_words"] = list(WORDS)
