"""Stage 2 English, plan week 3, lesson 1: predicting and questioning while reading.
Fully taught from scratch. Videos were found via search and are checked on playback."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W3L1 = build(
    "s2-eng-w03-l1-predicting-and-questioning", "Reading Detective: Predict and Question",
    "Good readers are detectives. Learn to hunt for clues, make smart predictions and ask questions that make you think harder.",
    "Reading: predicting and questioning",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-RECOM-01": "Primary. Predicts what will happen using clues and evidence from the text, checks and revises predictions, and asks thin and thick questions while reading.",
     "EN2-VOCAB-01": "Learns the reading words predict, prediction, clue, evidence, wonder, thin question and thick question.",
     "EN2-SPELL-01": "Applies the rules for adding -ing and -ed (drop the e, double the consonant, change y to i) to reading words."},
    "We are learning to make predictions using clues from the text, to check and change them, and to ask questions that help us understand what we read.",
    ["I can say what a prediction is and why readers make them.",
     "I can find clues in the title, pictures, words and what I already know.",
     "I can write a prediction using 'I predict... because...'.",
     "I can check a prediction and change it when I learn something new.",
     "I can ask questions before, during and after reading.",
     "I can tell a thin question from a thick question."],
    ["predict", "prediction", "clue", "evidence", "wonder", "thin question", "thick question", "revise"],
    ["A story or picture book you have not read before", "Sticky notes or small pieces of paper", "Pencil", "Notebook"],
    "Nothing is assumed. Child can read a short story with a little help. Predicting and questioning are taught from the beginning, and the spelling rules for endings are revisited with examples.",
    "Reading is not just looking at words. Good readers think the whole time they read. Two of the best ways to think while reading are predicting and asking questions.\n\nTo PREDICT means to make a smart guess about what will happen next. It is not a wild guess. A smart prediction uses CLUES, which are small pieces of information from the title, the pictures, the words and what you already know. The clues are your EVIDENCE.\n\nTo ask QUESTIONS means to wonder about the story as you read: who, what, why, how. Some questions are answered later and some make you think deeply.\n\nWhen you predict and question, you stay awake and curious. You also remember more of what you read, because your brain is working on it. In this lesson you will practise both, step by step, using a short story.",
    [
        _step("1", "Readers think while they read",
              "Imagine watching a movie without ever wondering what will happen next. It would be pretty dull! Good readers do not just say the words. They wonder, guess and check as they go.\n\nThere are two main ways to do this. The first is PREDICTING: guessing what will happen next. The second is QUESTIONING: asking about things you do not yet understand or want to know.\n\nBoth are done before reading, during reading and after reading. Before: look at the title and pictures. During: stop at interesting points. After: think about what you learned and what you still wonder.\n\nYou will use a simple routine again and again: STOP, THINK, SAY. Stop at an exciting or puzzling point. Think about the clues. Say your prediction or question.",
              "Title: 'The Locked Gate'. Before reading, a reader thinks: Why is the gate locked? Who locked it? I predict someone is hiding a secret behind it. That is a prediction and two questions already!",
              "Stop, think, say.",
              ("When do good readers predict and ask questions?", ["Before, during and after reading", "Only at the end", "Never"], 0, "Readers think at every stage of reading.")),
        _step("2", "What is a prediction?",
              "A prediction is a smart guess about what will happen next, based on clues. It has two parts: what you think will happen, and the clue that made you think it.\n\nA prediction is different from a wild guess. A wild guess has no reason. 'The dog will turn into a dragon' has no clues behind it in an ordinary story. A smart prediction has a reason: 'The dog will find the lost key because he keeps sniffing near the garden.'\n\nYou do not have to be right. Predictions can be wrong, and that is fine. What matters is that you used clues and thought carefully. In fact, finding out that you were wrong is part of the fun, because it tells you something new about the story.",
              "Wild guess: The girl will fly to the moon. Smart prediction: The girl will find her lost kitten, because the story says she can hear tiny meows from the old shed.",
              "A prediction needs a clue.",
              ("Which is a smart prediction?", ["It will rain soon because dark clouds are rolling in.", "The bus will turn into a banana.", "Something will happen."], 0, "It gives a reason from the text.")),
        _step("3", "Finding clues",
              "Clues are everywhere. Look for these six kinds.\n\n1. The TITLE: it often hints at the main problem.\n2. The COVER and PICTURES: what are the characters doing, and how do they look?\n3. The WORDS: strong words such as 'shadow', 'whispered' or 'trembled' give hints about the mood.\n4. The CHARACTER'S ACTIONS: what they do shows what they are like.\n5. The SETTING: a storm, a dark forest or a busy market all suggest what could happen.\n6. WHAT YOU ALREADY KNOW: you have seen similar things before. If a character is holding an umbrella, you already know it might rain.\n\nCircle or underline clues as you read. They are what you will point to when someone asks, 'Why do you think that?'",
              "Passage: Ben packed his torch, a rope and three biscuits. Dark clouds rolled over the hills and the wind began to howl. Clues: the torch and rope (he is going somewhere hard), dark clouds and howling wind (a storm is coming). What I already know: storms can make a trip dangerous.",
              "Look in the title, pictures, words, actions, setting and your own knowledge.",
              ("Which is a clue that a storm is coming?", ["Dark clouds rolled over the hills", "Ben packed biscuits", "Ben has a torch"], 0, "Dark clouds suggest a storm.")),
        _step("4", "Writing a prediction: 'I predict... because...'",
              "A good prediction has a sentence frame you can always use: 'I predict that ______ because ______.' The first gap says what will happen. The second gap names the clue.\n\nThe word BECAUSE is very important. It forces you to point to evidence. Without it, a prediction is just a guess.\n\nYou can also use other starters: 'I think that...', 'I bet...', 'Maybe...', 'I wonder if...'. But always follow with a clue.\n\nKeep it short and clear. One sentence is enough.",
              "After reading Ben's passage: I predict that Ben will have to find shelter because dark clouds and a howling wind show a storm is coming. Another: I predict that Ben will use the rope because he packed it for a reason.",
              "I predict... because... always includes a clue.",
              ("Which word makes a prediction use evidence?", ["because", "maybe", "what"], 0, "Because leads to the clue.")),
        _step("5", "Checking and changing predictions",
              "After you predict, keep reading and CHECK. Was your prediction right? Partly right? Wrong?\n\nIf it was right, say what clue helped. If it was wrong, do not worry. Say what the text told you instead, and make a NEW prediction. This is called REVISING a prediction, which means changing it after you learn more.\n\nA helpful routine is: 1) Predict. 2) Read on. 3) Check. 4) Revise if you need to.\n\nGood readers often change their minds. That is not a mistake. It shows they are paying attention to new information.",
              "Prediction: Ben will find shelter from the storm. Read on: Ben finds a small hut, but its door is jammed. Check: partly right, because he found a hut but he cannot get in yet. Revise: Ben will use his rope to force the door, because the story said he brought the rope.",
              "Predict, read on, check, revise.",
              ("What should you do if your prediction turns out to be wrong?", ["Make a new prediction from the new clues", "Stop reading", "Pretend it was right"], 0, "Revise using the new information.")),
        _step("6", "Asking questions before, during and after",
              "Readers ask questions to understand more deeply. Start your questions with WHO, WHAT, WHERE, WHEN, WHY and HOW.\n\nBEFORE reading: look at the title and picture. 'Why is the gate locked?'\nDURING reading: stop at puzzling parts. 'Why did Ben bring a rope?' 'How will he get out of the storm?'\nAFTER reading: think about the whole story. 'Why did the author end the story that way?'\n\nDo not ask questions you already know the answer to. The best questions are ones you do not yet know, so your brain has to work. Try to answer your own questions using clues from the text. You may not find an answer every time, and that is okay.",
              "Before: Where is Ben going and why? During: Why did he pack a rope and not a map? After: What might have happened if Ben had stayed at home?",
              "Ask questions you do not already know the answer to.",
              ("Which question word helps you ask a deep question?", ["Why", "Yes", "The"], 0, "Why makes you think about reasons.")),
        _step("7", "Thin and thick questions",
              "There are two kinds of questions.\n\nTHIN questions have short answers that you can find right in the text. 'What colour was Ben's torch?' 'How many biscuits did he pack?' They check facts.\n\nTHICK questions need thinking, and often have more than one possible answer. 'Why do you think Ben went out when a storm was coming?' 'How would the story change if the hut had not been there?' They are about reasons, feelings, ideas and what might happen.\n\nBoth kinds are useful. Thin questions help you understand the facts. Thick questions help you think deeply. Strong readers ask both, but try to ask more thick ones.\n\nTo turn a thin question into a thick one, change it to start with WHY or HOW or WHAT IF.",
              "Thin: What did Ben pack? Thick: Why do you think Ben packed a rope? Thin: Where was the hut? Thick: How might Ben feel when he sees the hut?",
              "Thin = facts in the text. Thick = thinking and reasons.",
              ("Which is a THICK question?", ["Why do you think Ben went out in the storm?", "What colour was the torch?", "How many biscuits did Ben have?"], 0, "It asks for reasons and thinking.")),
        _step("8", "Putting it together: stop, think, say",
              "Now use both skills on a new story.\n\n1. Look at the title and picture. Write one prediction (I predict... because...) and one question.\n2. Start reading. At an exciting or puzzling point, STOP.\n3. THINK about the clues in the words. Make a new prediction or ask a question.\n4. SAY it aloud or write it on a sticky note.\n5. Read on and check. Revise if you need to.\n6. When you finish, write one thin question and one thick question about the whole story.\n\nUse a sticky note for each stop. At the end, put a tick on every question that was answered and a star on every prediction that was right.",
              "Sticky note 1 (before): I predict the gate hides a garden because the title is The Locked Gate. Sticky note 2 (during): Why is there a muddy footprint near the gate? Sticky note 3 (after): thin: Who held the key? thick: Why did the girl keep it a secret?",
              "Use one sticky note for every stop.",
              ("What do you do after you make a prediction?", ["Read on and check it", "Throw it away", "Stop reading"], 0, "Check your prediction as you read.")),
        _step("9", "Spelling reading words with endings",
              "Many reading words end in -ing or -ed. Remember the three spelling rules.\n\nDROP THE E: predict has no e, but 'hope + ing = hoping' and 'bake + ed = baked'. Words with a silent e lose it before -ing.\nDOUBLE THE CONSONANT: stop + ed = stopped, plan + ing = planning. This happens when a short word has one short vowel and one consonant at the end.\nCHANGE Y TO I: carry + ed = carried, cry + ed = cried. But keep the y for -ing: carrying.\n\nWords to practise: predicting, wondered, stopped, asked, jumped, carried. Notice that 'predicting', 'wondered' and 'jumped' just add the ending, because they do not match the three rules.\n\nUse Look, Say, Cover, Write, Check for each word.",
              "plan + ing = planning (double the n). hope + ing = hoping (drop the e). carry + ed = carried (change y to i). jump + ed = jumped (no change).",
              "Check the end of the base word before adding the ending.",
              ("What is stop + ed?", ["stopped", "stoped", "stopt"], 0, "One short vowel and one consonant, so double the p.")),
    ],
    "Short story: The Locked Gate. Mia found an old iron gate at the end of her street. It was covered in ivy and a rusty padlock hung from it. Through the bars she saw a small stone path leading into the trees. A muddy footprint was pressed in the dirt beside it.\n\nPredict: I predict someone has been inside because there is a fresh muddy footprint. Question (thick): Who has the key, and why do they keep the gate locked?\n\nNext part: Mia noticed a small silver key tied to a branch above her head. Check: my prediction was partly right, because someone has been here, and now I see a key. Revise: I predict Mia will use the key to open the gate, because it was hung where she could reach it.\n\nThin question: What was tied to the branch? Thick question: Why do you think the key was left where someone could find it?",
    "1) Choose a story you have not read. 2) Before reading, write one 'I predict... because...' and one question. 3) Read, and stop three times. Each time write a sticky note with a prediction or a question. 4) Check your predictions: tick the right ones and revise the wrong ones. 5) After reading, write one thin question and one thick question. 6) Practise spelling: predicting, wondered, stopped, asked, jumped, carried (Look, Say, Cover, Write, Check).",
    "Read a story you have not seen before. Write a before-reading prediction with a clue, three sticky notes made during reading, and one thin and one thick question after reading. Show how you checked and revised at least one prediction.",
    "Which was easier for you: predicting or questioning? Which clue helped you the most? Did you change any predictions?",
    "Did my predictions use clues and the word because? Did I check and revise them? Did I ask questions I did not already know the answer to? Did I write both a thin and a thick question? Did I spell the ending words correctly?",
    [
        _q("What is a prediction?", ["A smart guess about what will happen next", "A summary of the story", "A word in the title"], 0, "A prediction is a clue-based guess."),
        _q("Which is a clue?", ["A picture of dark clouds on the cover", "The page number", "The price"], 0, "A picture can hint at what happens."),
        _q("Which sentence is a good prediction? ", ["I predict the dog will find the bone because he is digging near the tree.", "I predict something.", "Dogs are nice."], 0, "It uses 'because' and a clue."),
        _q("Read: Ben packed a torch, a rope and three biscuits. Dark clouds rolled in and the wind began to howl. What might happen next?", ["A storm arrives and Ben must find shelter", "Ben goes swimming at the beach", "Ben goes to sleep"], 0, "Dark clouds and wind are clues for a storm."),
        _q("Your prediction was wrong. What should you do?", ["Revise it using the new clues", "Ignore the story", "Stop reading"], 0, "Revise your prediction."),
        _q("Which is a THIN question?", ["What colour was the gate?", "Why do you think the gate was locked?", "What if the key were lost?"], 0, "It has a short answer from the text."),
        _q("Which is a THICK question?", ["How do you think Mia felt when she saw the key?", "How many bars were on the gate?", "What colour was the ivy?"], 0, "It asks for thinking about feelings."),
        _q("Which question word often starts a deep question?", ["Why", "Is", "Did"], 0, "Why asks for reasons."),
        _q("What is carry + ed?", ["carried", "carryed", "carred"], 0, "Change y to i before -ed."),
        _q("What is plan + ing?", ["planning", "planing", "plannning"], 0, "Double the n before -ing."),
    ],
    "Upload a photo of your sticky notes, your thin and thick questions and your spelling words.",
    "Pick a favourite film or book you know well. Say what you would have predicted at the start, and which clues pointed to the real ending.",
    [("predict", "To make a smart guess about what will happen next."), ("prediction", "A smart guess based on clues."), ("clue", "A small piece of information that helps you work something out."),
     ("evidence", "The clues or facts that support your idea."), ("wonder", "To think about something and want to know more."), ("thin question", "A question with a short answer found in the text."),
     ("thick question", "A question that needs thinking and has more than one possible answer."), ("revise", "To change something after you learn more.")],
    [
        _video("Predictions Chart for Kids: Making Predictions While Reading", "aM4KXfdbIyQ",
               "Watch how readers pause and use clues from the story to make a prediction, then check it. Pause the video each time and make your own prediction before the next part.",
               "Write one prediction using 'I predict... because...' about the story in the video.",
               ("What do you use to make a prediction?", ["Clues from the story", "Nothing", "The last page only"], 0, "Predictions use clues.")),
        _video("Asking Questions While You Read", "zdAAdXUneEY",
               "Watch how the readers ask questions as they read a story. Notice what they wonder at each part.",
               "Write three questions you would ask about the story in the video.",
               ("Why do readers ask questions?", ["To think more deeply about the story", "To finish faster", "To skip pages"], 0, "Questions help you think and understand.")),
    ],
    _sort("Detective sorter", "Is each one a prediction, a question or a clue? Tap a group, then Check.",
          ["Prediction", "Question", "Clue"],
          [("I predict the key will open the gate because it was hung nearby", 0), ("I think the storm will pass because the clouds are clearing", 0), ("Why did the girl hide the letter?", 1), ("I wonder who left the footprints", 1), ("Dark clouds and a howling wind", 2), ("A torn map lying on the floor", 2)]),
    [
        _wc("A prediction is a smart ___.", ["guess", "ending", "title"], 0, "A prediction is a smart guess."),
        _wc("Clues in a text are also called ___.", ["evidence", "endings", "titles"], 0, "Clues are evidence."),
        _wc("To revise means to ___.", ["change", "hide", "finish"], 0, "Revise means change after learning more."),
        _wc("A thick question needs ___.", ["thinking", "one word", "no answer"], 0, "Thick questions need thinking."),
        _wc("Which is spelt correctly?", ["stopped", "stoped", "stopt"], 0, "Double the p."),
        _wc("Which is spelt correctly?", ["wondered", "wondred", "wonderred"], 0, "Wonder + ed has no change."),
    ],
    [
        {"key": "predict", "label": "Prediction", "hint": "Write 'I predict... because...' for your story."},
        {"key": "notes", "label": "Sticky notes", "hint": "Three notes you wrote while reading."},
        {"key": "questions", "label": "My questions", "hint": "One thin question and one thick question."},
        {"key": "revise", "label": "My revision", "hint": "Show one prediction you changed and why."},
    ],
    ["Making a wild guess with no clue.", "Forgetting the word because.", "Asking only thin questions.", "Ignoring a prediction that turned out wrong instead of revising it.", "Asking a question you already know the answer to."],
    [{"title": "Prediction Pause", "description": "Read a story aloud to someone and stop twice. Ask them to predict with a clue each time.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check that predictions use 'because' and a clue from the text, that at least one prediction was checked and revised, that the thin question has a short text answer and the thick question needs thinking, and that endings are spelt correctly. Sorter: Predictions: key will open gate; storm will pass. Questions: why hide the letter; who left footprints. Clues: dark clouds and howling wind; torn map.",
)

LESSONS = [W3L1]
