"""Stage 2 English, plan week 3, lesson 2: writing the orientation and complication of a narrative.
Fully taught from scratch. Videos were found via search and are checked on playback."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W3L2 = build(
    "s2-eng-w03-l2-orientation-and-complication", "Story Opener: Orientation and Complication",
    "Learn how a story starts: who, where and when, then the moment that something goes wrong.",
    "Writing: narrative orientation and complication",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Plans and writes the orientation and complication of an imaginative narrative, using a hook, past tense and time connectives.",
     "EN2-VOCAB-01": "Learns and uses the narrative terms orientation, complication, setting, character, hook, problem and connective.",
     "EN2-SPELL-01": "Spells past tense -ed words using the rules: double the consonant, drop the silent e, change y to i."},
    "We are learning to write the opening of a story, introducing who, where and when, and then the problem that starts the action.",
    ["I can name the three parts of a narrative: orientation, complication and resolution.",
     "I can write an orientation that tells who, where and when.",
     "I can use a hook to grab my reader.",
     "I can write a complication that is a real problem for my character.",
     "I can use time connectives such as one morning, suddenly and just then.",
     "I can keep my writing in the past tense and spell -ed words correctly."],
    ["orientation", "complication", "resolution", "setting", "character", "hook", "problem", "connective"],
    ["Paper or notebook", "Pencil", "A story you know well for examples", "Coloured pencils (optional) for planning"],
    "Nothing is assumed. Child can write a few connected sentences. The three parts of a narrative are taught from the beginning, and past tense -ed spelling is revisited with examples.",
    "Every good story is built in parts. The three main parts of a narrative are the ORIENTATION, the COMPLICATION and the RESOLUTION.\n\nThe ORIENTATION is the start. It tells the reader who the characters are, where the story is set, and when it happens. It also gives the mood.\n\nThe COMPLICATION is the problem. Something goes wrong or changes, and the character must deal with it. This is what makes the reader want to keep reading.\n\nThe RESOLUTION is the ending, where the problem is solved. In this lesson we write the first two parts.\n\nYou will plan a story, write a strong opening with a hook, then write the problem that sets the action going. You will keep your story in the past tense, as most narratives are.",
    [
        _step("1", "The shape of a story",
              "A story is not just a list of things that happen. It has a shape. Think of a mountain.\n\nYou start at the bottom with the ORIENTATION, which introduces the characters and setting. The path begins to climb with the COMPLICATION, which is the problem. At the top there is the climax, the most exciting or tense moment. Then you come down with the RESOLUTION, where the problem is solved and the story ends.\n\nThis shape is called a STORY MOUNTAIN. It helps you plan before you write so you do not get lost in the middle.\n\nIn this lesson we climb the first half. Without a clear start and a good problem, the rest of the story has nothing to stand on.",
              "Story mountain for 'The Lost Kite'. Orientation: Sam is flying his new kite in the park on a windy morning. Complication: the string snaps and the kite blows away. Climax: Sam chases it across the creek. Resolution: a neighbour helps him get it down from a tree.",
              "Orientation, complication, climax, resolution.",
              ("What is the complication in a story?", ["The problem", "The title", "The ending"], 0, "The complication is the problem.")),
        _step("2", "The orientation: who, where, when",
              "The orientation answers three questions straight away: WHO is in the story, WHERE are they, and WHEN is it?\n\nWHO: name your main character and say one thing about them. 'Mia, a curious ten-year-old with muddy boots.'\nWHERE: name the setting and add a detail the reader can picture. 'At the edge of a whispering forest.'\nWHEN: say the time of day, season or time in history. 'On a freezing winter morning.'\n\nYou can also set the MOOD with the weather or the light. A grey, windy day feels different from a bright sunny one.\n\nKeep it short. The orientation is only a few sentences. Do not tell the whole story here. Give just enough that the reader can see the scene.",
              "Weak: There was a boy. He went to a place. Strong: On a windy Saturday morning, eight-year-old Sam raced across Pelican Park with his bright red kite tucked under one arm.",
              "Orientation = who + where + when.",
              ("Which question does the orientation NOT answer?", ["How does the story end?", "Who is in the story?", "Where is it set?"], 0, "The ending comes later, in the resolution.")),
        _step("3", "Hooking your reader",
              "A HOOK is a first sentence that grabs the reader, just like a fishing hook catches a fish. It makes them curious and want to read on.\n\nHere are four hooks you can try.\n1. A SOUND: 'Crack! The branch snapped behind her.'\n2. A QUESTION: 'Have you ever heard a house whisper?'\n3. ACTION: 'Sam sprinted across the park with the kite flapping above him.'\n4. DIALOGUE: '\"Don't touch that gate,\" whispered Grandpa.'\n\nAvoid beginning with 'One day there was a boy', because it does not make anyone curious.\n\nAfter your hook, go on to your who, where and when. Your hook and your orientation work together.",
              "Hook: Crack! The old branch snapped. Then orientation: Mia froze at the edge of Whispering Forest, on a gloomy Tuesday afternoon, holding her torch tight.",
              "Hook first, then who, where and when.",
              ("Which is the best HOOK?", ["Crack! The branch snapped behind her.", "One day there was a girl.", "This is a story about a girl."], 0, "A sound makes the reader curious.")),
        _step("4", "The complication: the problem",
              "Now something must go wrong. The COMPLICATION is the problem that your main character must face. Without it there is no story, only a description.\n\nGood problems are connected to what your character WANTS. If Sam wants to fly his kite all day, the problem is that it blows away. If Mia wants to find her lost cat, the problem could be that the cat is trapped.\n\nThere are three common kinds of problem.\n1. A problem with NATURE: a storm, a flood, a fire, getting lost.\n2. A problem with ANOTHER CHARACTER: a bully, a thief, an angry giant.\n3. A problem INSIDE the character: feeling scared, being shy, making a hard choice.\n\nChoose a problem that feels real and is big enough that your character cannot fix it straight away.",
              "Sam wants to fly his kite. Problem: the string snaps and the kite sails away over the trees. Mia wants to find her cat. Problem: she hears faint meowing but the gate to the old garden is locked.",
              "The problem is connected to what the character wants.",
              ("Which is a good complication for a character who wants to cross a river?", ["The bridge collapses", "It is a Tuesday", "She has a blue coat"], 0, "A collapsed bridge is a real problem.")),
        _step("5", "Writing the complication",
              "When you write the complication, show the moment it happens. Use a TIME CONNECTIVE to signal the change. A connective is a word or phrase that joins ideas. Time connectives for the problem include 'suddenly', 'just then', 'without warning', 'all at once' and 'that was when'.\n\nThen show the character's reaction with a feeling and an action. 'Sam's heart sank.' 'Mia gasped and dropped her torch.'\n\nBuild it up with two or three sentences, not just one. Say what happened, how the character reacted, and what they must now do.\n\nFinish the complication with a short sentence that points to what comes next. 'He had to get it back before it was gone for good.'",
              "Suddenly, a strong gust of wind ripped the string from Sam's fingers. His heart sank as the red kite spun up over the trees and disappeared. He had to get it back before it was gone for good.",
              "Connective + problem + reaction + what must happen next.",
              ("Which is a time connective?", ["Suddenly", "Kite", "Happily"], 0, "Suddenly is a time connective.")),
        _step("6", "Past tense and paragraphs",
              "Most stories are written in the PAST TENSE, as if the events have already happened. We say 'Sam raced' not 'Sam races'. Keep every verb in the past tense from start to finish.\n\nMost regular past tense verbs end in -ed: walked, jumped, whispered. Irregular verbs change in other ways: run becomes ran, see becomes saw, go becomes went.\n\nPut the orientation in one paragraph and the complication in a new paragraph. Starting a new paragraph signals a change in the story.\n\nIndent the first line or leave a blank line between paragraphs so the reader can see the break.",
              "Paragraph 1 (orientation): On a windy Saturday morning, Sam raced across Pelican Park... Paragraph 2 (complication): Suddenly, a strong gust of wind ripped the string from his fingers...",
              "One paragraph for the orientation, a new one for the complication.",
              ("Which sentence is in the past tense?", ["Sam raced across the park.", "Sam races across the park.", "Sam will race across the park."], 0, "Raced is past tense.")),
        _step("7", "Spelling past tense -ed words",
              "Many words in your story will end in -ed. Three spelling rules help.\n\nDROP THE E: if the word ends in a silent e, drop the e before -ed. notice becomes noticed. hope becomes hoped.\nDOUBLE THE CONSONANT: if a short word has one vowel and one consonant at the end, double the last letter. stop becomes stopped. trap becomes trapped. drop becomes dropped.\nCHANGE Y TO I: if the word ends in a consonant plus y, change the y to i. hurry becomes hurried. carry becomes carried.\n\nIf none of these apply, just add -ed: walk becomes walked, whisper becomes whispered.\n\nPractise: stopped, trapped, dropped, noticed, hurried, whispered. Use Look, Say, Cover, Write, Check.",
              "stop + ed = stopped (double the p). notice + ed = noticed (drop the e). hurry + ed = hurried (change y to i). whisper + ed = whispered (no change).",
              "Check the end of the word before adding -ed.",
              ("What is hurry + ed?", ["hurried", "hurryed", "hurryd"], 0, "Change y to i.")),
        _step("8", "Planning and writing your opening",
              "Now write your own story opening, step by step.\n\n1. Choose a character, a setting and a time. Write them in a list.\n2. Think of a hook: a sound, a question, action or dialogue.\n3. Think about what your character wants, then choose a problem that gets in the way.\n4. Write paragraph one: the hook, then who, where and when. Use your senses to describe the setting.\n5. Write paragraph two: a time connective, the problem, the character's reaction and what must happen next.\n6. Check that your story is in the past tense.\n7. Read it aloud and fix anything that sounds odd.\n\nYou can write about anything: a lost pet, a haunted house, an unusual machine, a hidden island. Just make sure the problem is a real one.",
              "Plan: Character: Ava, a shy girl with a drawing pad. Setting: a rocky beach. Time: low tide at dawn. Hook: Splash! Something huge slid back into the sea. Want: to draw a sea creature. Problem: the creature is stuck between two rocks and calls for help.",
              "Plan first, then write two paragraphs.",
              ("What do you write in paragraph two?", ["The complication", "The title", "The resolution"], 0, "Paragraph two holds the complication.")),
        _step("9", "Revising your opening",
              "Good writers read their work again and improve it. Check your opening with this list.\n\n- Does it start with a hook?\n- Does the orientation tell who, where and when?\n- Can the reader picture the setting?\n- Is the problem clear and connected to what the character wants?\n- Did I use a time connective to signal the problem?\n- Is everything in the past tense?\n- Are my -ed words spelt correctly?\n- Does it start a new paragraph for the problem?\n\nChange at least two things. Maybe swap a boring word for a stronger one, such as walked to crept, or add one more detail to the setting.",
              "Before: Sam went to the park. Then his kite flew away. After: Sam raced across Pelican Park with his kite tucked under one arm. Suddenly, a gust of wind ripped the string from his fingers.",
              "Revise at least two things.",
              ("What should you check in your opening?", ["Hook, who, where, when, problem, tense, spelling", "Only the title", "Only the last word"], 0, "Check every part of the opening.")),
    ],
    "Model opening: The Lost Kite. Crack! The kite string snapped. On a windy Saturday morning, eight-year-old Sam stood in the middle of Pelican Park, his bright red kite tugging high above him. Fluffy clouds raced across the sky and the flags near the cafe snapped in the wind.\n\nSuddenly, a strong gust ripped the string from his fingers. Sam's heart sank as the kite spun over the trees and disappeared. He had to get it back before it was gone for good.\n\nCheck: Hook (a sound), who (Sam), where (Pelican Park), when (windy Saturday morning), problem (the kite blows away), connective (suddenly), past tense, two paragraphs.",
    "1) Plan: choose a character, setting and time, a hook, what your character wants and a problem. 2) Write paragraph one with a hook and the who, where and when. 3) Write paragraph two with a time connective, the problem, the character's reaction and what must happen next. 4) Check the past tense. 5) Revise using the checklist, changing at least two things. 6) Practise the words stopped, trapped, dropped, noticed, hurried and whispered.",
    "Write a two-paragraph story opening with a hook, an orientation (who, where, when) and a complication. Upload a photo of your plan and your final writing.",
    "Which hook did you choose and why? Is your problem connected to what your character wants? What did you change when you revised?",
    "Does my opening start with a hook? Do I say who, where and when? Is my problem clear? Did I use a time connective? Is it in the past tense? Did I start a new paragraph for the problem? Are my -ed words spelt correctly?",
    [
        _q("What does the orientation tell the reader?", ["Who, where and when", "How the story ends", "Only the title"], 0, "The orientation sets the scene."),
        _q("What is the complication?", ["The problem that starts the action", "The last sentence", "The author's name"], 0, "The complication is the problem."),
        _q("What is a hook?", ["A first sentence that grabs the reader", "A kind of fish", "The ending of the story"], 0, "A hook makes the reader curious."),
        _q("Which is the best hook?", ["Crack! The branch snapped behind her.", "This story is about a girl.", "One day there was a girl."], 0, "A sound hook is exciting."),
        _q("A character wants to cross a river. Which is a good complication?", ["The bridge collapses", "The sun shines", "She has a blue coat"], 0, "The problem stops her getting what she wants."),
        _q("Which word signals the problem?", ["Suddenly", "Always", "Never"], 0, "Suddenly shows a sudden change."),
        _q("Which sentence is past tense?", ["She noticed a footprint.", "She notices a footprint.", "She will notice a footprint."], 0, "Noticed is past tense."),
        _q("What is stop + ed?", ["stopped", "stoped", "stopt"], 0, "Double the p."),
        _q("What is hurry + ed?", ["hurried", "hurryed", "hurred"], 0, "Change y to i."),
        _q("What is notice + ed?", ["noticed", "noticeed", "noticd"], 0, "Drop the e."),
    ],
    "Upload a photo of your plan, your two paragraphs and your spelling practice.",
    "Write a different hook for the same story, using a different type (sound, question, action or dialogue). Which is better and why?",
    [("orientation", "The start of a story that tells who, where and when."), ("complication", "The problem that starts the action in a story."), ("resolution", "The part where the problem is solved."),
     ("setting", "Where and when a story takes place."), ("character", "A person or animal in a story."), ("hook", "A first sentence that grabs the reader."),
     ("problem", "Something that goes wrong for the main character."), ("connective", "A word or phrase that joins ideas, such as suddenly or just then.")],
    [
        _video("How to write a story for kids - beginning", "Rfj4yFosaOw",
               "Watch how a story begins with characters, an action, a time and a place, and how a problem comes into the story. Pause and tell your own character, setting and problem.",
               "Write the character, setting and problem for your own story.",
               ("What does the beginning of a story need?", ["Characters, a time and place, and an action", "Only a title", "The ending"], 0, "The beginning sets up characters, place and action.")),
        _video("Learning Narrative Structure (Orientation, Complication, Resolution)", "JHU_SWuzu28",
               "Watch how a narrative has an orientation, a complication and a resolution. Listen for what each part does.",
               "Say aloud what happens in each of the three parts in a story you know.",
               ("What is the orientation?", ["The part that tells who, where and when", "The ending", "The problem"], 0, "The orientation introduces the story.")),
    ],
    _sort("Story part sorter", "Which part of a story does each sentence belong to? Tap a part, then Check.",
          ["Orientation", "Complication", "Resolution"],
          [("On a windy Saturday morning, Sam stood in Pelican Park.", 0), ("Mia crept to the edge of the whispering forest at dusk.", 0), ("Suddenly, the string snapped and the kite blew away.", 1), ("Just then, the bridge collapsed into the river.", 1), ("A neighbour lifted the kite down from the tree and Sam smiled.", 2), ("At last the rescue boat arrived and everyone was safe.", 2)]),
    [
        _wc("The orientation tells who, where and ___.", ["when", "why not", "never"], 0, "Who, where, when."),
        _wc("The problem in a story is called the ___.", ["complication", "orientation", "title"], 0, "The complication is the problem."),
        _wc("A first sentence that grabs the reader is a ___.", ["hook", "hat", "hill"], 0, "A hook grabs the reader."),
        _wc("Which is a time connective?", ["just then", "purple", "kite"], 0, "Just then shows time."),
        _wc("Which is spelt correctly?", ["trapped", "traped", "trappd"], 0, "Double the p."),
        _wc("Which is spelt correctly?", ["hurried", "hurryed", "huried"], 0, "Change y to i."),
    ],
    [
        {"key": "plan", "label": "My plan", "hint": "Character, setting, time, hook, what they want, problem."},
        {"key": "orientation", "label": "Paragraph 1", "hint": "Your hook and orientation."},
        {"key": "complication", "label": "Paragraph 2", "hint": "Your complication."},
        {"key": "revision", "label": "What I changed", "hint": "Two improvements you made."},
    ],
    ["Starting with 'One day there was...'.", "Giving the problem too late.", "A problem that does not connect to what the character wants.", "Switching between past and present tense.", "Forgetting to start a new paragraph for the problem.", "Spelling -ed words without checking the rules."],
    [{"title": "Story Opener Challenge", "description": "Read your opening aloud to someone and ask them to say who, where, when and what the problem is.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check that the opening begins with a hook, answers who, where and when, includes a clear problem tied to what the character wants, uses a time connective, stays in the past tense, uses two paragraphs, and spells -ed words correctly. Sorter: Orientation: windy Saturday; whispering forest at dusk. Complication: string snapped; bridge collapsed. Resolution: neighbour lifted the kite down; rescue boat arrived.",
)

LESSONS = [W3L2]
