"""Stage 4 placeholder plans for the other 11 subjects (1,100 lessons), each with distinct planned topics.

Uses the subjects, units, outcome codes and lesson generator from lesson_library_s4_plan. This module is
registered BEFORE lesson_library_s4_plan, so these lessons win over that file's numbered fallbacks.
The unit lists below are drafts: sequence, titles and outcome mapping should be checked against the NSW
syllabuses before full lessons are written. Language units use a generic 'target language' scope until a
language is chosen. Aboriginal Languages content must be built with the local Language community.
"""
from lesson_library_s4_plan import SUBJECTS, _make, _t

MORE = {
    ("geography", "Geographical inquiry and skills"): _t("What is geography?; Reading maps and map symbols; Grid references and area references; Latitude, longitude and the globe; Scale and distance; Compass directions and bearings; Aerial photographs and satellite images; Fieldwork: planning a field study; Collecting field data; Graphs and tables in geography; Describing spatial patterns; Choosing the right geographical tool; Asking geographical questions; Perspectives on places; Communicating findings; Geographical skills review"),
    ("geography", "Landscapes and landforms"): _t("What is a landscape?; Landforms of Australia; Mountains and plateaus; Plains and valleys; Coastal landforms; Rivers and floodplains; Deserts and dunes; Glacial landscapes; Volcanic landscapes; Karst and caves; Weathering and erosion; How rivers shape the land; Waves and coastal erosion; Wind and desert processes; Natural hazards: landslides; Natural hazards: floods; Landscapes and First Nations connection; Aboriginal Custodianship of Country; Landscapes and tourism; Threats to landscapes; Managing and protecting landscapes; World Heritage landscapes; Landscape fieldwork case study; Landscapes unit review"),
    ("geography", "Liveability of places"): _t("What is liveability?; Measuring liveability; Factors that shape liveability; Access to services and housing; Transport and accessibility; Safety and community; Environmental quality; Liveability in Australian cities; Liveability in a city overseas; Comparing liveability across places; Urbanisation: why cities grow; Urban settlement patterns; Megacities; Rural places and liveability; Remote communities; Migration and place; Perceptions of place; Place and identity; Improving liveability; Urban planning; Green spaces and sustainability; Community consultation; Liveability fieldwork case study; Liveability unit review"),
    ("geography", "Water in the world"): _t("The water cycle; Water on Earth; Oceans and currents; Rivers and catchments; Groundwater; Water in Australia; Water scarcity; Floods and droughts; Water and First Nations Peoples; Aboriginal management of waterways; Water use in agriculture; Water use in cities; Water quality and pollution; Managing water sustainably; Water infrastructure and dams; Global water inequality; Water conflicts; Climate change and water; Water case study; Water unit review"),
    ("geography", "Interconnections and trade"): _t("What is interconnection?; Global links between places; Trade and goods; Supply chains; Where our food comes from; Where our clothes come from; Transport and trade routes; Technology and communication links; Tourism and travel; Migration flows; Globalisation: benefits and costs; Fair trade and ethical choices; Australia's trading partners; Culture and global links; Interconnections case study; Interconnections and course review"),
    ("pdhpe", "Movement skills and strategies"): _t("Movement skills overview; Fundamental movement review; Locomotor skills in games; Throwing and catching; Striking and fielding skills; Invasion game strategies; Net and court game strategies; Athletics: running skills; Athletics: jumping and throwing; Movement skills assessment; Teamwork and communication in games; Fair play and sportsmanship; Tactics and decision making; Applying feedback to improve; Designing modified games; Gymnastics and body control; Dance and rhythmic movement; Fitness through games; Cooperative challenges; Movement skills reflection"),
    ("pdhpe", "Health and wellbeing through physical activity"): _t("Why physical activity matters; Components of fitness; Cardiovascular fitness; Strength and flexibility; Fitness testing; Setting fitness goals; Planning a training program; Warm-up and cool-down; Preventing injury; First aid basics; Nutrition and energy; Hydration and recovery; Sleep and wellbeing; Screen time and activity balance; Lifelong physical activity; Active transport and community; Stress and movement; Mindfulness and movement; Evaluating a fitness program; Health and activity review"),
    ("pdhpe", "Safe, active and healthy lifestyle choices"): _t("Healthy lifestyle choices; Making decisions about health; Healthy eating guidelines; Reading food labels; Food marketing and influence; Sun safety; Water safety; Road and pedestrian safety; Bike and e-scooter safety; Online safety and digital wellbeing; Social media and wellbeing; Peer influence and decision making; Alcohol, vaping and drugs: the facts; Resisting pressure; Finding reliable health information; Health services and support; Emergency responses; Mental health literacy; Managing stress and emotions; Lifestyle choices review"),
    ("pdhpe", "Respectful relationships"): _t("What makes a respectful relationship?; Communication skills; Active listening; Assertiveness; Conflict resolution; Managing anger; Friendship and belonging; Healthy and unhealthy relationships; Consent and respect; Bullying and cyberbullying; Being an upstander; Gender and respect; Diversity and inclusion; Family relationships; Online relationships; Puberty and body changes; Reproductive health basics; Respectful relationships in sport; Seeking help; Relationships unit review"),
    ("pdhpe", "Identity, belonging and change"): _t("What is identity?; Factors that shape identity; Culture and belonging; First Nations identity and connection; Family and community; Strengths and values; Body image; Media and identity; Self-esteem; Resilience; Dealing with change; Transitions to high school; Setting personal goals; Building support networks; Stereotypes and fairness; Inclusion in sport and community; Pride and belonging; Wellbeing action plan; Reflecting on growth; Identity unit review"),
    ("technology", "Digital and communication technologies"): _t("What is technology?; The design process; Digital safety and privacy; Responsible online behaviour; How computers work; Hardware and software; Networks and the internet; Data and storage; Spreadsheets for data; Creating digital presentations; Digital media and design; Image editing; Audio and video basics; Introduction to coding; Algorithms and flowcharts; Block coding projects; Text-based coding intro; Debugging and testing; Designing an app interface; Data representation and binary; Cybersecurity basics; Artificial intelligence in society; Digital project: planning; Digital project: building and evaluating"),
    ("technology", "Engineering technologies and systems"): _t("Engineering around us; Forces in structures; Strong shapes and bracing; Materials for structures; Bridges and towers; Mechanisms: levers and gears; Pulleys and linkages; Energy and motion; Simple circuits; Switches and control; Sensors and automation; Robotics introduction; Programming a robot; Sketching and orthographic drawing; Isometric drawing; Prototyping with cardboard; Measuring and marking out; Workshop safety; Using hand tools safely; Joining methods; Testing and improving a prototype; Sustainability in engineering; Engineering careers; Engineering project: design brief; Engineering project: build; Engineering project: evaluate"),
    ("technology", "Food and agricultural practices"): _t("Where food comes from; Australian agriculture; Plant growth and soil; Planting and caring for a garden; Animal production; Sustainable farming; First Nations food knowledge; Food technology and processing; Food preservation; Nutrition and food groups; Kitchen safety and hygiene; Reading recipes; Measuring and preparing ingredients; Knife skills; Cooking methods; Baking basics; Meal planning; Healthy snacks; Cultural foods; Food packaging and waste; Food marketing; Food allergies and safety; Designing a food product; Making a food product; Taste testing and evaluation; Food and agriculture review"),
    ("technology", "Materials and production processes"): _t("Properties of materials; Timber types and uses; Metals and alloys; Plastics and polymers; Textiles and fibres; Natural and synthetic materials; Recycling and reuse; Sustainable material choices; Tools for cutting and shaping; Sewing basics; Textile design; Woodwork joints; Metalwork basics; Finishing techniques; Reading working drawings; Planning production steps; Quality control; Costing a project; Workplace health and safety; Design brief for a product; Making the product; Testing the product; Evaluating and improving; Materials unit review"),
    ("visual_arts", "Drawing and painting"): _t("What is art?; The Artworld: artist, artwork, world and audience; Elements of art: line; Shape and form; Tone and shading; Texture; Colour theory; Mixing paints; Drawing from observation; Contour and gesture drawing; Perspective drawing; Composition; Still life; Landscape painting; Portrait drawing; Painting techniques; Mark making; Abstract art; Expressing ideas and mood; Visual diary practice; Drawing and painting project: ideas; Drawing and painting project: developing; Drawing and painting project: finishing; Reflecting on your work"),
    ("visual_arts", "Sculpture and design"): _t("Introducing sculpture; Form and space; Modelling with clay; Pinch and coil techniques; Relief sculpture; Carving basics; Assemblage and found objects; Papier-mache; Wire and structure; Installation art; Public art and monuments; Design and everyday objects; Graphic design basics; Typography; Poster design; Logo design; Packaging design; Printmaking: relief; Printmaking: stencil; Textile and fibre art; Craft traditions; First Nations design and symbols; Sustainable art practice; Sculpture project: planning; Sculpture project: making; Sculpture and design review"),
    ("visual_arts", "Artists and artworks"): _t("Looking at artworks; Describing and interpreting art; Viewpoints: structural, subjective, cultural and postmodern; The artworld and its audiences; Art history timeline; Renaissance art; Impressionism; Modern art movements; Pop art; Australian colonial art; Australian modern art; First Nations art; Art of the Western Desert; Art and Country; Contemporary Australian artists; Art from Asia; Art from the Pacific; Women artists; Public art and street art; Art and protest; Galleries and museums; Writing about art; Researching an artist; Artists and artworks review"),
    ("visual_arts", "Digital and mixed media"): _t("Introducing digital art; Digital drawing tools; Photography basics; Composition in photography; Editing photographs; Digital collage; Animation basics; Stop-motion animation; Video art; Sound and art; Mixed media techniques; Collage and layering; Art journaling; Textural experiments; Combining drawing and painting; Combining digital and traditional media; Art and technology; Ethics: copyright and sharing; Curating an exhibition; Display and presentation; Artist statements; Mixed media project: ideas; Mixed media project: making; Mixed media project: refining; Exhibition and reflection; Stage 4 Visual Arts review"),
    ("music", "Performing"): _t("Music and its elements; Duration: beat and rhythm; Pitch and notation; Dynamics and expression; Tempo; Timbre and instruments; Texture; Structure and form; Reading rhythm notation; Reading pitch notation; Singing with good technique; Singing in tune; Singing in rounds; Playing a classroom instrument; Keyboard basics; Ukulele or guitar chords; Recorder or tuned percussion; Playing by ear; Ensemble playing; Keeping in time together; Performing with dynamics; Performing melodies; Performing accompaniments; Group performance skills; Stage presence; Rehearsal strategies; Performing a song from another culture; Performing Australian songs; Performing First Nations songs with respect; Solo performance; Giving and receiving feedback; Recording a performance; Evaluating a performance; Performing review and concert"),
    ("music", "Listening"): _t("Active listening; Describing music with the elements; Music of the Baroque; Classical period music; Romantic music; Twentieth-century music; Jazz origins; Blues and its influence; Rock and roll; Pop music history; Hip hop; Electronic music; Film music; Music for video games; Programme music; Music and storytelling; Music of Australia; First Nations music and instruments; Music from Asia; Music from Africa; Music from Latin America; Folk traditions; Music and place; Music and identity; Music and social change; Music in advertising; Music and mood; Listening for texture; Listening for structure; Comparing two pieces; Writing about music; Concert listening report; Music technology in listening; Listening review"),
    ("music", "Composing"): _t("What is composing?; Creating rhythm patterns; Composing with ostinato; Creating a melody; Pentatonic scale compositions; Major and minor scales; Chords and harmony; Chord progressions; Writing a song; Writing lyrics; Setting words to music; Structure: verse and chorus; Binary and ternary form; Improvisation basics; Improvising on a scale; Soundscapes; Composing for a mood; Composing for a film scene; Using music software; Notation software; Recording and layering; Looping and beats; Sampling and remixing; Arranging a known song; Composing for instruments; Composing as a group; Cultural respect in composing; Giving feedback on compositions; Refining a composition; Performing your composition; Reflecting on your compositions; Composing and Stage 4 Music review"),
    ("drama", "Making"): _t("What is drama?; Elements of drama; Role and character; Situation and conflict; Focus and tension; Mood and atmosphere; Space and time; Symbol; Voice; Movement; Gesture and facial expression; Improvisation basics; Improvisation games; Freeze frames and tableaux; Mime; Storytelling; Narrative structure in drama; Characters from stories; Creating a character; Hot seating; Role on the wall; Dialogue and monologue; Devising from a stimulus; Devising from a picture; Devising from a poem; Devising from the news; Group devising skills; Shaping a scene; Scripting a scene; Using props and costume; Using sound and light; Process drama; Playbuilding showcase; Making review"),
    ("drama", "Performing"): _t("Performance skills overview; Voice projection; Articulation and pace; Vocal variety; Physical presence; Body language; Eye contact and focus; Working with a partner; Ensemble work; Trust and teamwork; Reading a script aloud; Learning lines; Blocking; Entrances and exits; Pausing and timing; Comedy performance; Physical comedy; Melodrama; Commedia dell'arte; Clowning; Puppetry; Mask work; Playing different ages; Playing emotion; Monologue performance; Duologue performance; Scene performance; Working with an audience; Stage fright strategies; Performing a devised work; Performing a scripted scene; Rehearsal process; Feedback and refining; Performing review and showcase"),
    ("drama", "Appreciating"): _t("What is theatre?; Reading a performance; Describing drama elements; Greek theatre; Medieval theatre; Elizabethan theatre; Shakespeare's Globe; Japanese theatre: Noh and Kabuki; Chinese opera; Indian theatre traditions; Australian theatre; First Nations theatre and storytelling; Contemporary Australian plays; Musical theatre; Physical theatre; Political theatre; Theatre for young audiences; Backstage roles; Stage design; Costume design; Lighting design; Sound design; Directing; Theatre critics and reviews; Writing a performance review; Attending a live performance; Comparing two performances; Drama in film and TV; Drama in the community; Drama and social issues; Reflecting on your drama learning; Stage 4 Drama review"),
    ("dance", "Performing"): _t("What is dance?; Elements of dance: body; Elements of dance: space; Elements of dance: time; Elements of dance: dynamics; Elements of dance: relationships; Safe dance practice; Warm-up and cool-down; Posture and alignment; Balance and stability; Flexibility and strength; Locomotor movements; Non-locomotor movements; Travelling sequences; Jumps and turns; Floor work; Rhythm and counting; Moving to music; Performing a sequence; Memorising choreography; Performance quality; Expression and focus; Partnering; Group formations; Unison and canon; Jazz dance basics; Hip hop basics; Contemporary dance basics; Folk and social dance; Australian bush dance; First Nations dance with respect; Dance technique review; Performing for an audience; Performing review"),
    ("dance", "Composing"): _t("What is choreography?; Finding ideas from a stimulus; Movement vocabulary; Improvising movement; Improvising with space; Improvising with time; Improvising with dynamics; Shaping movement phrases; Motif and development; Repetition and variation; Contrast and transition; Choreographing a solo; Choreographing a duet; Choreographing for a group; Using formations; Canon and unison in choreography; Levels and pathways; Using props; Costume and set ideas; Lighting and staging ideas; Choosing music; Dance without music; Dance and storytelling; Dance and emotion; Dance and social issues; Dance and nature; Dance and technology; Dance on film; Notating movement; Giving feedback; Refining choreography; Teaching your choreography; Performing your choreography; Composing review"),
    ("dance", "Appreciating"): _t("Watching dance; Describing dance works; Elements of dance in works; Dance in context; Dance history timeline; Ballet; Modern dance pioneers; Contemporary dance; Jazz and tap; Musical theatre dance; Hip hop and street dance; Cultural dance traditions; Dance of Asia; Dance of the Pacific; Dance of Africa; Dance of Latin America; Australian dance companies; First Nations dance companies; Dance and identity; Dance and community; Dance and social change; Choreographers and their style; Comparing two dance works; Writing about dance; Dance reviews; Attending a live performance of dance; Dance and film; Technology in dance performance; Careers in dance; Dance and wellbeing; Reflecting on dance learning; Stage 4 Dance review"),
    ("modern_languages", "Introducing myself"): _t("Greetings and farewells; Polite expressions; Saying my name; Spelling my name; Numbers 0 to 20; Saying my age; Where I am from; Countries and nationalities; Languages I speak; Describing myself; Colours; Describing hair and eyes; Personality words; Asking simple questions; Answering questions; Classroom instructions; Alphabet and sounds; Pronunciation practice; Writing a short self-introduction; Introducing myself review"),
    ("modern_languages", "Family and friends"): _t("Family members; Talking about my family; Family tree; Possessives: my and your; Pets and animals; Describing people; Friends and their interests; Hobbies; Sports and games; Likes and dislikes; Numbers to 100; Birthdays and dates; Days and months; Telling the time; Making invitations; Accepting and declining; Writing a message to a friend; Listening to a conversation; Roleplay: meeting a friend's family; Family and friends review"),
    ("modern_languages", "School and daily life"): _t("School subjects; My timetable; Classroom objects; School rooms and places; Opinions about subjects; Daily routine; Morning routine; Meals and mealtimes; Telling the time in detail; Weekend activities; Chores at home; Transport to school; Weather; Seasons; Clothing; School uniform; Describing my school day; Asking for help; Writing about my day; School and daily life review"),
    ("modern_languages", "Food, places and culture"): _t("Food and drink; Fruit and vegetables; Ordering at a cafe; Shopping for food; Prices and money; Meals in the culture; Festival foods; My town; Places in a town; Asking for directions; Giving directions; Public transport; Holidays and travel; Booking accommodation; Festivals and celebrations; Customs and etiquette; Music and media in the culture; Sport in the culture; Cultural comparison with Australia; Food, places and culture review"),
    ("modern_languages", "Review and project"): _t("Revising greetings and introductions; Revising family; Revising school and routines; Revising food and shopping; Revising directions; Reading short texts; Listening practice; Speaking practice; Writing practice; Grammar review; Vocabulary games; Planning a language project; Researching the culture; Making a poster or slide show; Writing a script; Rehearsing a dialogue; Presenting the project; Peer feedback; Language learning reflection; Stage 4 Modern Languages celebration"),
    ("classical_languages", "Reading and forming Latin"): _t("Why learn Latin?; The Latin alphabet and pronunciation; Latin in English words; Nouns and gender; Singular and plural; The nominative case; The accusative case; Verbs and the present tense; Verb endings; Subject and object; Word order in Latin; First declension nouns; Second declension nouns; Adjectives agreeing with nouns; Prepositions; Questions and commands; Numbers in Latin; Simple sentences; Reading short sentences; Translating into English; Vocabulary strategies; Latin derivatives; Reading a short story; Latin forms review"),
    ("classical_languages", "Roman daily life"): _t("Roman families; Roman names; Houses and villas; Roman food and dining; Clothing and fashion; Schools and education; Slaves and freedmen; Roman women; Children and toys; Roman baths; Roman streets and Pompeii; Shops and markets; Roman work and trades; The forum; Roman entertainment; Chariot races; Gladiators; Theatre; Roman religion; Festivals; Latin: the genitive case; Latin: the dative case; Latin: the imperfect tense; Reading about daily life; Comparing Roman and modern life; Roman daily life review"),
    ("classical_languages", "Myth and stories"): _t("What are myths?; Roman and Greek gods; Jupiter and Juno; Venus and Cupid; Mars and Minerva; Apollo and Diana; Mercury and Neptune; Pluto and the underworld; Hercules; Perseus; Theseus and the Minotaur; Orpheus and Eurydice; Pyramus and Thisbe; Romulus and Remus; Aeneas and the founding of Rome; The Trojan War; Latin: the perfect tense; Latin: third declension; Latin: the ablative case; Reading mythological stories; Translating a myth; Myth in art; Myth in modern media; Myth and meaning; Creating a retelling; Myth and stories review"),
    ("classical_languages", "The Roman world and review"): _t("Rome's early history; The Roman Republic; Julius Caesar; Augustus and the Empire; Roman emperors; The Roman army; Roman roads; Roman engineering and aqueducts; Roman law; Roman provinces; Roman Britain; Roman legacy in language; Roman legacy in architecture; Latin: pluperfect and future tenses; Latin: more verbs; Translating longer passages; Latin inscriptions; Latin mottoes; Research project: choosing a Roman topic; Research project: writing; Research project: presenting; Revising Latin grammar; Revising Roman culture; Stage 4 Classical Languages review"),
    ("aboriginal_languages", "Sounds and greetings"): _t("Respect, protocols and Language Custodians; The Language of this Country; Acknowledging Country; Sounds of the language; Vowels; Consonants; Pronunciation practice; Greetings; Saying farewell; Thank you and polite words; Saying my name; Asking someone's name; Numbers; Colours; Body parts; Commands in class; Simple questions; Simple answers; Songs for sounds; Clapsticks and rhythm; Writing the sounds; Reading short words; Names for animals; Names for plants; Greeting practice with Elders or community; Sounds and greetings review"),
    ("aboriginal_languages", "Family and community"): _t("Kinship systems; Words for family; Mother and father; Brothers and sisters; Grandparents and Elders; Skin names and totems where appropriate; Respect for Elders; Community roles; Describing people; Who lives here?; Home and camp; Food in community; Sharing food; Gathering food; Cooking on Country; Tools and objects; Daily activities; Games and play; Songs and dance; Stories from family; Introducing my family; Writing about family; Community visit preparation; Family and community review"),
    ("aboriginal_languages", "Country and place"): _t("What is Country?; Caring for Country; Land and water words; Sky, sun, moon and stars; Seasons on Country; Weather words; Animals of Country; Birds; Fish and sea life; Plants and bush foods; Medicine plants; Seasonal calendars; Places and landmarks; Sacred sites and respect; Directions and travel; Maps of Country; Place names and their meanings; Songlines where appropriate; Fire and land management; Water and rivers; Describing places; Telling where something is; Writing about Country; Country visit or virtual visit; Sharing a place story; Country and place review"),
    ("aboriginal_languages", "Stories and review"): _t("Why stories matter; Dreaming stories and protocols; Listening to a story; Retelling a story; Story words; Storytelling gestures and sign; Stories with animals; Stories of creation; Story and song; Story and art; Reading a short story; Writing a short story; Picture story book; Recording a story; Digital story; Performing a story; Language revival; Language and identity; Revising greetings and sounds; Revising family words; Revising Country words; Presenting what I have learned; Thanking community; Stage 4 Aboriginal Languages review"),
    ("auslan", "Fingerspelling and greetings"): _t("What is Auslan?; Deaf community and culture; Respect and Deaf etiquette; Getting attention; Handshapes; Fingerspelling A to M; Fingerspelling N to Z; Fingerspelling practice; Receptive fingerspelling; Greetings; Farewells; Polite signs; Signing my name; Name signs; Numbers 1 to 10; Numbers 11 to 20; Facial expression and grammar; Yes-no questions; Wh- questions; Fingerspelling and greetings review"),
    ("auslan", "Family and identity"): _t("Family signs; My family; Family tree in Auslan; Describing people; Signing age; Signing where I live; Colours; Clothing; Personality signs; Feelings and emotions; Likes and dislikes; Hobbies; Sport signs; Pets; Friends; Introducing a friend; Time signs; Days of the week; Months; Dates and birthdays; Numbers to 100; Signing space and pointing; Role shift introduction; Classifiers introduction; Asking about someone's family; Deaf identity; Deaf families; Hearing family members of Deaf people; Telling a short signed story; Family and identity review"),
    ("auslan", "Deaf culture and community"): _t("Deaf culture and values; History of Deaf people in Australia; Deaf education history; Auslan recognition; Deaf clubs and community; Deaf events and sport; Deaflympics; Famous Deaf Australians; Deaf Aboriginal and Torres Strait Islander people; Deaf art and theatre; Deaf humour; Technology and Deaf communities; Interpreters and access; Captioning and relay services; Etiquette with Deaf people; Auslan and English differences; Place and travel signs; Food signs; Shopping signs; School signs; Work and jobs; Health and emergencies; Asking for help; Signing a dialogue; Cultural research task; Deaf culture review"),
    ("auslan", "Signed texts and review"): _t("What is a signed text?; Watching signed stories; Understanding a signed story; Retelling a signed story; Signed poetry; Signed songs; Visual vernacular; Narrative structure in Auslan; Describing events; Sequencing and time; Signing directions; Signing a recount; Planning a signed text; Filming a signed text; Editing and sharing; Peer feedback in Auslan; Auslan and English translation; Comparing signed languages; Revising fingerspelling; Revising family and identity; Revising Deaf culture; Signed presentation; Reflecting on Auslan learning; Stage 4 Auslan review"),
}

LESSONS = []
for _skey, _spec in SUBJECTS.items():
    if _spec[3] != 2:
        continue
    for _first, _last, _unit, _codes in _spec[4]:
        _queue = list(MORE.get((_skey, _unit), []))
        if not _queue:
            continue
        _extra = 0
        for _week in range(_first, _last + 1):
            for _slot in range(2):
                if _queue:
                    _text = _queue.pop(0)
                else:
                    _extra += 1
                    _text = "%s: extra planned lesson %d" % (_unit, _extra)
                LESSONS.append(_make(_skey, _week, _slot, _unit, _codes, _text))

if __name__ == "__main__":
    keys = [x["seed_key"] for x in LESSONS]
    assert len(keys) == len(set(keys)), "duplicate seed keys"
    for (_k, _u), _topics in MORE.items():
        _unit = [u for u in SUBJECTS[_k][4] if u[2] == _u][0]
        _slots = (_unit[1] - _unit[0] + 1) * 2
        if len(_topics) != _slots:
            print("COUNT MISMATCH", _k, _u, len(_topics), "topics for", _slots, "slots")
    for _k in {k for k, _u in MORE}:
        _texts = [t for (k, _u), ts in MORE.items() if k == _k for t in ts]
        assert len(_texts) == len(set(_texts)), (_k, "repeated lesson topics")
    print("lessons:", len(LESSONS))
