"""Stage 2 English, Week 2, Lesson 1 (pilot for the 200-lesson plan). Not yet registered in lesson_library.py.
Videos verified by YouTube oEmbed on 2026-10-07. BBC Bitesize sends X-Frame-Options DENY, so it is never embedded."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W2L1 = build(
    "s2-eng-w02-l1-story-elements", "Story Architect: Characters, Setting and Plot",
    "A story has collapsed! Learn the parts every story is built from, then rebuild one from its clues.",
    "Reading: story elements and narrative structure",
    ["EN2-RECOM-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-RECOM-01": "Primary. Identifies characters, setting and plot structure to comprehend a narrative.",
     "EN2-VOCAB-01": "Learns and uses Tier 3 words: exposition, conflict, climax, resolution.",
     "EN2-SPELL-01": "Applies vowel team spelling (ai, ay, ee, ea, oa) to story words."},
    "We are learning to identify the parts of a story and how they fit together.",
    ["I can name the characters and describe the setting of a story.", "I can say what the problem (conflict) is.",
     "I can order the five parts of a plot: exposition, rising action, climax, falling action, resolution.",
     "I can use clues in the text to back up my answers.", "I can spell story words with vowel teams."],
    ["character", "setting", "plot", "conflict", "exposition", "climax", "resolution", "evidence"],
    ["Paper or notebook", "Pencil", "A short story from any book you own"],
    "Child can read a short story. Everything else is taught in this lesson.",
    "Every story is built from the same parts. Characters are who the story is about. The setting is where and when it happens. The plot is the chain of events. The plot has a shape: it starts by introducing characters and setting (exposition), a problem appears (conflict), things get harder (rising action), the most exciting moment arrives (climax), things calm down (falling action) and the problem is solved or changed (resolution).\n\nKnowing the parts helps you read better because you know what to look for, and it helps you write better because you know what to build.\n\nWhen you answer a question about a story, back your answer with evidence: point to the words or action in the text that prove it.",
    [
        _step("1", "Characters: who is in the story?", "Characters are the people, animals or creatures a story is about. The main character is the one the story follows most closely. Other characters help, block or change the main character.\n\nWe learn about characters in four ways: what they do, what they say, what they think and feel, and what others say about them. A character who shares his lunch is kind. You do not need the author to say 'he was kind'.\n\nWhen you meet a character ask two questions: What do they want? What are they like?",
              "In The Three Little Pigs the characters are three pigs and a wolf. The wolf wants dinner. The third pig is clever because he builds with bricks.",
              "Actions show character better than labels do.",
              ("Which tells you a character is brave?", ["She walked into the dark cave to save her friend.", "She had red hair.", "She lived in a town."], 0, "Her action shows bravery.")),
        _step("2", "Setting: where and when?", "The setting is the place and time of a story. Place can be a house, a jungle, a spaceship. Time can be a season, a time of day or a period in history.\n\nSetting is more than a backdrop. A storm, a desert or a crowded city can create the mood and cause the problem.\n\nFind the setting by looking for place words (in the forest), time words (one winter morning) and sensory details (the cold wind bit his cheeks).",
              "Backyard, Sunday afternoon: place and time. 'The fog crept over the silent harbour at dawn' sets a quiet, mysterious mood.",
              "Ask Where? and When? and then How does it feel?",
              ("'One winter morning, snow covered the farm.' What is the time?", ["Winter morning", "The farm", "Snow"], 0, "Winter morning is when. The farm is where.")),
        _step("3", "Conflict: the problem", "Stories need a problem. Without one, nothing happens. The problem is called the conflict. It can be a character against another character, against nature, against themselves or against a situation.\n\nThe conflict gives the character something to want and something in the way. The reader keeps reading to find out how it will be solved.",
              "Wolf versus pigs (character against character). A lost hiker in a blizzard (character against nature). A shy girl who must give a speech (character against herself).",
              "Find the problem by asking What goes wrong?",
              ("A boy is lost in a snowstorm. What kind of conflict is it?", ["Against nature", "Against another character", "There is no conflict"], 0, "The storm is the force against him.")),
        _step("4", "The shape of the plot", "Plot is the order of events, and most plots follow five steps. Exposition introduces characters and setting. Rising action is the series of events as the problem grows. The climax is the most exciting turning point. Falling action shows what happens straight after. The resolution ties it up.\n\nImagine a mountain. You climb (rising action), reach the top (climax) and come down (falling action).\n\nA plot is not just a list of events. Each event causes the next one: because this happened, that happened.",
              "The Three Little Pigs. Exposition: three pigs build houses. Rising action: the wolf blows down two. Climax: the wolf tries the brick house and the chimney. Falling action: the wolf falls into the pot. Resolution: the pigs are safe.",
              "Look for words that signal cause: so, because, then, as a result.",
              ("What is the most exciting part of the plot?", ["The climax", "The exposition", "The resolution"], 0, "The climax is the turning point.")),
        _step("5", "Using evidence from the text", "When a question asks how you know, you need evidence. Evidence is a word, a line or an action from the text that proves your answer.\n\nUse this pattern: My answer. The text says (or shows). That proves it because. For example: Mia was nervous. The text says her hands shook and she kept looking at the door. That shows she was scared of what would happen.\n\nEvidence turns an opinion into a reasoned answer.",
              "Answer: The setting is lonely. Evidence: 'a single light burned in the empty street'. Because: one light and an empty street suggest nobody is around.",
              "If you cannot point to it in the text, it is a guess.",
              ("What is evidence?", ["A line or action from the text that proves your answer", "What you wish happened", "Your favourite part"], 0, "Evidence comes from the text.")),
        _step("6", "Spelling: vowel teams in story words", "Many story words use vowel teams, two vowels that make one sound. ai and ay make the long a: rain, trail, play, stay. ee and ea make the long e: tree, sleep, dream, beach. oa makes the long o: boat, road, coast.\n\nai is usually in the middle of a word and ay at the end (rain, but play). Practise with Look, Say, Cover, Write, Check from Week 1.\n\nThese words are now in your Word Hoard: plain, trail, dream, coast, beach, display.",
              "The brave sailor reached the coast; the trail of rain led to a dream beach.",
              "ay ends a word; ai sits in the middle.",
              ("Which is spelt correctly?", ["playn", "plain", "plane (as in simple)"], 1, "plain has ai in the middle. (plane is an aeroplane.)")),
    ],
    "Story: 'The Lost Kite'. One windy Saturday, Sam flew his red kite at the beach. A gust snapped the string and the kite sailed away over the sea. Sam ran along the sand, then swam out to a small boat and asked the fisher to help. Together they chased the kite and caught it as it dropped on the waves. Sam hugged his kite and promised to hold on tighter.\n\nCharacters: Sam and the fisher. Setting: a windy Saturday at the beach. Conflict: Sam loses his kite (character against nature). Climax: they catch the kite on the waves. Resolution: Sam promises to hold on tighter. Evidence for 'Sam is determined': he ran along the sand, then swam out to the boat.",
    "In your notebook: 1) Read a short story from your own book. 2) List the characters and one trait for each, with the action that shows it. 3) Write the setting (place, time, mood) with a quote. 4) Name the conflict and its type. 5) Fill in a five-part plot mountain. 6) Answer in the evidence pattern: Why is the main character important to the story?",
    "Choose any short story. Draw and label a plot mountain with the five parts, a sentence for each. Add a character card (name, wants, traits, evidence) and a setting card. Then answer: What was the climax, and how do you know?",
    "Which part of the story was hardest to find: characters, setting, conflict or the climax? Why?",
    "Does my plot mountain have five parts? Do I have evidence for a character trait and the setting? Did I name the conflict and its type?",
    [
        _q("What is the setting of a story?", ["Where and when it happens", "Who is in it", "How it ends"], 0, "Setting is place and time."),
        _q("What is the conflict?", ["The problem", "The ending", "The title"], 0, "Conflict is the problem the characters face."),
        _q("Which comes first in a plot?", ["Exposition", "Climax", "Resolution"], 0, "Exposition introduces characters and setting."),
        _q("Which is the most exciting part?", ["Climax", "Exposition", "Falling action"], 0, "The climax is the turning point."),
        _q("'She smiled and shared her cake.' What does this show?", ["She is kind", "She is hungry", "She is late"], 0, "Her action shows kindness."),
        _q("A girl fights a flood. What type of conflict?", ["Against nature", "Against herself", "Against a friend"], 0, "The flood is nature."),
        _q("Which is evidence?", ["'His hands shook as he opened the door.'", "I think he is scared.", "It is a good story."], 0, "Evidence is from the text."),
        _q("Which is spelt correctly?", ["rane", "rain", "rayn"], 1, "rain: ai in the middle."),
        _q("Which is spelt correctly?", ["display", "displai", "displae"], 0, "ay at the end."),
        _q("What happens in the resolution?", ["The problem is solved or changes", "The characters are introduced", "The problem begins"], 0, "Resolution wraps up the story."),
    ],
    "Upload a photo of your plot mountain, character card, setting card and evidence answer.",
    "Take a film or picture book you know and map its plot onto the five-part mountain. Is there more than one climax?",
    [("character", "A person, animal or creature in a story."), ("setting", "Where and when a story happens."), ("plot", "The order of events in a story."),
     ("conflict", "The problem in a story."), ("exposition", "The beginning: characters and setting."), ("climax", "The most exciting turning point."),
     ("resolution", "How the problem is solved or changes."), ("evidence", "Words or actions from the text that prove your answer.")],
    [
        _video("The elements of a story (Khan Academy)", "Zr1xLtSMMLo",
               "Watch how a story has exposition, conflict, rising action, climax, falling action and resolution. Pause to say each part aloud.",
               "Read step 4 aloud and draw the plot mountain.",
               ("What happens at the climax?", ["The most exciting moment", "Characters are introduced", "The story starts again"], 0, "The climax is the high point.")),
        _video("Story Elements: Characters, Setting and Events", "1M0pFLXegG0",
               "Watch how to ask Who? Where? When? What? to find the parts of a story.",
               "Ask Who, Where, When, What about a story from your own book.",
               ("Which question finds the setting?", ["Where and when?", "Who?", "Why?"], 0, "Setting is where and when.")),
        _video("Parts of a Story Song", "urA4PNn9w9Y",
               "Watch the song and notice how character, setting and plot work together.",
               "Sing or say the three parts and give one example of each from a story you know.",
               ("Which is NOT a main story element?", ["Character", "Setting", "Page number"], 2, "Page numbers do not build a story.")),
    ],
    _sort("Story element sorter", "Which story part is each clue? Tap a part, then Check.",
          ["Character", "Setting", "Conflict", "Resolution"],
          [("a clever fox", 0), ("the shy new girl", 0), ("a stormy night in the mountains", 1), ("a deserted space station", 1), ("one winter morning", 1), ("the dragon has stolen the village's water", 2), ("the boy is lost in the forest", 2), ("the team cannot agree", 2), ("the dragon returns the water and becomes a friend", 3), ("they find the way home", 3)]),
    [
        _wc("A character is shown to be kind by their ___.", ["actions", "hair", "address"], 0, "What they do shows what they are like."),
        _wc("Conflict means ___.", ["the problem", "the ending", "the setting"], 0, "Conflict is the problem."),
        _wc("Which word has the long a sound spelt ay?", ["stay", "stain", "star"], 0, "stay ends in ay."),
        _wc("Which word has the long e sound spelt ea?", ["dream", "deck", "drum"], 0, "dream uses ea."),
        _wc("Which word has oa?", ["coast", "cost", "cast"], 0, "coast uses oa."),
        _wc("The ___ is where the story ends up.", ["resolution", "exposition", "setting"], 0, "Resolution is the ending."),
    ],
    [
        {"key": "story", "label": "My story", "hint": "Title and author of the story you read."},
        {"key": "chars", "label": "Characters", "hint": "Names, one trait each, and the action that shows it."},
        {"key": "setting", "label": "Setting", "hint": "Place, time and mood, with a quote."},
        {"key": "plot", "label": "Plot mountain", "hint": "One sentence for each of the five parts."},
    ],
    ["Saying the plot instead of the setting, or the reverse.", "Naming a character trait without evidence.", "Listing events instead of explaining how each causes the next.", "Confusing ai (middle) and ay (end) in spelling."],
    [{"title": "Story Map", "description": "Make a poster plot mountain for a favourite film.", "type": "create", "difficulty": "medium", "evidence_type": "photo"},
     {"title": "Teach It", "description": "Explain the five parts of a plot to a family member using a story they know.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers depend on the story chosen. Check each trait has an action as evidence, the setting has place, time and a quote, the conflict is named with its type, and the plot mountain has all five parts in order. Sort: Character: clever fox, shy new girl. Setting: stormy night, deserted space station, one winter morning. Conflict: dragon steals water, lost boy, team cannot agree. Resolution: dragon returns water, find the way home.",
)

LESSONS = [W2L1]
