"""Stage 2 English, plan week 3, lesson 3: verb tense and adverbs.
Fully taught from scratch. Videos were found via search and are checked on playback."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

W3L3 = build(
    "s2-eng-w03-l3-verb-tense-and-adverbs", "Time Travel Verbs and Adverb Power",
    "Learn how verbs show past, present and future, and how adverbs tell us how, when and where things happen.",
    "Language: verb tense and adverbs",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {"EN2-CWT-01": "Primary. Uses past, present and future tense verbs correctly and consistently, and adds adverbs to give detail about how, when, where and how often.",
     "EN2-VOCAB-01": "Learns the grammar terms verb, tense, past, present, future, adverb and the adverb questions how, when, where, how often.",
     "EN2-SPELL-01": "Spells common irregular past tense verbs and -ly adverbs correctly."},
    "We are learning to use verbs in the right tense and to use adverbs to add detail to our sentences.",
    ["I can say what a verb is and find the verb in a sentence.",
     "I can name and use past, present and future tense.",
     "I can write regular and irregular past tense verbs.",
     "I can keep the same tense through a piece of writing.",
     "I can find adverbs by asking how, when, where and how often.",
     "I can add -ly to adjectives to make adverbs and spell them correctly."],
    ["verb", "tense", "past tense", "present tense", "future tense", "adverb", "irregular", "modify"],
    ["Paper or notebook", "Pencil", "A short story or page from a book", "Coloured pencils (optional)"],
    "Nothing is assumed. Child knows what a sentence is and can write simple sentences. Verbs, tenses and adverbs are taught from the beginning.",
    "A VERB is a word that tells what someone or something does or is. Run, jump, think and is are all verbs. Every sentence needs at least one verb.\n\nVerbs also tell us WHEN something happens. This is called TENSE. The three main tenses are PAST (it already happened), PRESENT (it is happening now) and FUTURE (it will happen later).\n\nAn ADVERB is a word that adds detail to a verb. It tells how, when, where or how often something happens. In 'The dog ran quickly', the word quickly is an adverb because it tells how the dog ran.\n\nIn this lesson you will learn to use verbs in the right tense, keep your tense the same through a story, and make your sentences more interesting with adverbs.",
    [
        _step("1", "What is a verb?",
              "A verb is a doing or being word. Most verbs are ACTION verbs: run, jump, laugh, build, whisper. Some verbs describe being or having: is, was, are, have, seems.\n\nTo find the verb in a sentence, ask yourself: what is happening, or what is someone doing? 'The cat chased the mouse.' The word that tells what the cat did is chased, so chased is the verb.\n\nEvery sentence has at least one verb. If you cannot find one, it is not a full sentence.\n\nChoose strong, exact verbs. 'Walked' is fine, but 'crept', 'strolled' or 'marched' gives a clearer picture.",
              "Sentence: Mia raced down the hill. Verb: raced. Sentence: The lake is calm. Verb: is. Sentence: Ben whispered a secret. Verb: whispered.",
              "Verb = what someone does or is.",
              ("What is the verb in 'The dog barked loudly'?", ["barked", "dog", "loudly"], 0, "Barked tells what the dog did.")),
        _step("2", "Three tenses: past, present, future",
              "TENSE tells us WHEN an action happens. Imagine a timeline.\n\nPAST TENSE: it has already happened. 'Yesterday I walked to school.'\nPRESENT TENSE: it is happening now, or happens regularly. 'I walk to school.' 'She walks to school.'\nFUTURE TENSE: it has not happened yet. 'Tomorrow I will walk to school.' We usually add the word WILL before the verb.\n\nThe verb changes shape to show the tense. Walked, walk and will walk are all forms of the same verb.\n\nTime words are clues: yesterday, last week and long ago point to the past. Now and today point to the present. Tomorrow and next week point to the future.",
              "Past: The kite flew away. Present: The kite flies away. Future: The kite will fly away. Same verb, three tenses, three different times.",
              "Past = did. Present = does. Future = will do.",
              ("Which sentence is in the future tense?", ["Tomorrow we will visit the zoo.", "Yesterday we visited the zoo.", "We visit the zoo."], 0, "Will shows the future.")),
        _step("3", "Past tense: regular and irregular",
              "Most past tense verbs are REGULAR: you add -ed. Walk becomes walked, jump becomes jumped, whisper becomes whispered. Remember the spelling rules: drop a silent e (hope becomes hoped), double the last letter of a short word (stop becomes stopped) and change y to i (hurry becomes hurried).\n\nSome verbs are IRREGULAR. They do not follow the -ed rule and change in their own way. You just have to learn them.\n\nrun becomes ran, see becomes saw, go becomes went, eat becomes ate, take becomes took, come becomes came, make becomes made, say becomes said, give becomes gave, find becomes found.\n\nWe never say 'goed', 'eated' or 'runned'. If a past tense verb sounds odd, check if the verb is irregular.\n\nPractise: ran, saw, went, ate, took, came. Use Look, Say, Cover, Write, Check.",
              "Regular: Sam jumped over the log. Irregular: Sam ran across the park and took a shortcut. Wrong: Sam runned. Right: Sam ran.",
              "Regular add -ed. Irregular change shape.",
              ("What is the past tense of 'go'?", ["went", "goed", "gone-ed"], 0, "Go is irregular: went.")),
        _step("4", "Present tense and the letter s",
              "In the present tense, the verb often changes depending on WHO is doing it.\n\nWith he, she, it, or one person or thing, we usually add -s or -es: 'The cat scratches the chair.' 'She writes in her journal.'\nWith I, you, we, they, or more than one person or thing, we keep the verb as it is: 'The cats scratch the chairs.' 'They write in their journals.'\n\nThis is called agreement: the verb agrees with the subject. If the subject is one, the verb often ends in s. If the subject is more than one, it does not.\n\nRead your sentence aloud. If it sounds odd, check the verb ending.",
              "One: The boy runs. Many: The boys run. One: Mia watches the stars. Many: The girls watch the stars.",
              "One subject: add s. More than one: no s.",
              ("Which is correct?", ["The girls play outside.", "The girls plays outside.", "The girl play outside."], 0, "Girls is plural, so play has no s.")),
        _step("5", "Future tense with 'will'",
              "The future tense tells what has not happened yet. We usually put WILL before the base verb.\n\n'I will help.' 'She will build a castle.' 'They will arrive tomorrow.'\n\nThe verb after 'will' does not change. We say 'He will walk', not 'He will walks' or 'He will walked'.\n\nYou can also show the future with 'going to': 'We are going to swim.' Both are correct. Keep 'will' as your main tool at this stage.\n\nFuture tense is used in plans, predictions and promises. 'Tomorrow it will rain.' 'I will clean my room.'",
              "Past: Ava painted a picture. Present: Ava paints a picture. Future: Ava will paint a picture.",
              "will + base verb, with no change.",
              ("Which is correct?", ["He will walk to school.", "He will walked to school.", "He will walks to school."], 0, "After will, use the plain verb.")),
        _step("6", "Keeping the same tense",
              "When you write a story, choose a tense and keep it the whole way through. Most stories use the PAST tense.\n\nA common mistake is slipping between tenses without meaning to. 'Sam walked to the park. He sees his friend. Then he waved.' Here the middle verb, sees, jumped into the present. It should be saw.\n\nTo check: read your writing and underline every verb. Do they all show the same time? If one is different, change it, unless there is a good reason, such as someone speaking in the present: 'I am hungry,' said Sam.\n\nSpeech can use a different tense, because the speaker is talking about their own time.",
              "Wrong: Mia opened the gate. She steps inside and sees a garden. Right: Mia opened the gate. She stepped inside and saw a garden.",
              "Underline every verb and check the tense.",
              ("Which sentence keeps the same tense?", ["Ben picked up the kite and ran home.", "Ben picks up the kite and ran home.", "Ben picked up the kite and runs home."], 0, "Picked and ran are both past.")),
        _step("7", "What is an adverb?",
              "An ADVERB gives more detail about a verb. It answers one of four questions.\n\nHOW? She walked slowly. (slowly, quickly, carefully, quietly)\nWHEN? We will leave soon. (soon, yesterday, later, now)\nWHERE? The cat stayed inside. (inside, outside, nearby, away, here)\nHOW OFTEN? He visits often. (often, never, always, sometimes, daily)\n\nTo find an adverb, first find the verb, then ask how, when, where or how often. 'The bird flew swiftly.' Verb: flew. How did it fly? Swiftly. So swiftly is the adverb.\n\nAdverbs can go before or after the verb, or at the start of a sentence. 'Quietly, she opened the door.' 'She quietly opened the door.' 'She opened the door quietly.'",
              "The monkey climbed quickly (how). We will meet later (when). The deer strolled nearby (where). The boys visited the zoo frequently (how often).",
              "Find the verb, then ask how, when, where, how often.",
              ("In 'The bird flew swiftly', what is the adverb?", ["swiftly", "bird", "flew"], 0, "Swiftly tells how it flew.")),
        _step("8", "Making adverbs with -ly",
              "Many adverbs of manner (how) are made by adding -ly to an adjective.\n\nquick becomes quickly. slow becomes slowly. careful becomes carefully. quiet becomes quietly.\n\nSome spelling changes are needed.\n- Word ends in y: change y to i, then add -ly. happy becomes happily. angry becomes angrily. easy becomes easily.\n- Word ends in le: drop the e and add y. gentle becomes gently. simple becomes simply.\n- Word ends in l: keep both l's. careful becomes carefully. final becomes finally.\n\nNot all adverbs end in -ly. Soon, here, never, always, fast, late, inside and often are adverbs with no -ly.\n\nBe careful: some words ending in -ly are not adverbs. 'Friendly' and 'lonely' are adjectives.",
              "The dog barked loudly. She skipped happily. He opened the door gently. They finally arrived. Spelling check: happy to happily, gentle to gently.",
              "Add -ly, but check the ending of the word first.",
              ("What is the adverb made from 'happy'?", ["happily", "happyly", "happly"], 0, "Change y to i, then add ly.")),
        _step("9", "Writing with verbs and adverbs",
              "Now use what you have learned in a short piece of writing.\n\nWrite a paragraph of five or six sentences about a character doing something exciting, such as finding a treasure or escaping a storm. Write it in the PAST TENSE.\n\nUse at least:\n- two irregular past tense verbs (ran, saw, took, came...)\n- three adverbs, one each for how, when and where\n- one adverb at the start of a sentence followed by a comma: 'Suddenly, the door creaked.'\n\nThen check. Underline every verb and make sure they are all past tense. Circle every adverb and check the spelling.\n\nFinally, swap a weak verb and adverb for one strong verb. 'Walked slowly' can become 'crept' or 'trudged'.",
              "Quietly, Mia crept down the stairs. She saw a light flicker inside the old shed. Slowly, she took a step forward. Suddenly, the door swung open and a small dog came running out happily.",
              "Past tense, irregular verbs, adverbs and a comma after an opening adverb.",
              ("Which sentence has an adverb at the start with a comma?", ["Quietly, she opened the door.", "She opened the quiet door.", "Quietly she."], 0, "Quietly is an adverb followed by a comma.")),
    ],
    "Model paragraph: Quietly, Mia crept down the stairs. She saw a light flicker inside the old shed. Slowly, she took a step forward, and her heart pounded loudly. Suddenly, the door swung open and a small brown dog came racing out. Mia laughed happily and ran home.\n\nCheck: all verbs in the past tense (crept, saw, took, pounded, swung, came, laughed, ran). Irregular verbs: crept, saw, took, swung, came, ran. Adverbs: quietly (how), slowly (how), loudly (how), suddenly (when), out (where), happily (how). Comma after opening adverbs.",
    "1) Write three sentences with the same verb in the past, present and future tense. 2) Change these irregular verbs to the past tense: run, see, go, eat, take, come. 3) Underline the verb in five sentences from a book. 4) Make five adverbs: quick, happy, gentle, careful, easy. 5) Write a six-sentence paragraph in the past tense with two irregular verbs, three adverbs and one opening adverb with a comma. 6) Practise spelling: ran, saw, went, ate, took, came.",
    "Write a paragraph of five or six sentences in the past tense with at least two irregular verbs and three adverbs. Underline the verbs and circle the adverbs. Upload a photo.",
    "Which tense did you find easiest to use? Which adverb added the most to your writing? Did you slip into a different tense anywhere?",
    "Are all my verbs in the same tense? Did I use two irregular past tense verbs correctly? Did I use at least three adverbs? Did I put a comma after an opening adverb? Did I spell my -ly adverbs and irregular verbs correctly?",
    [
        _q("What is a verb?", ["A doing or being word", "A naming word", "A describing word for nouns"], 0, "A verb tells what someone does or is."),
        _q("Which sentence is in the past tense?", ["She jumped over the log.", "She jumps over the log.", "She will jump over the log."], 0, "Jumped is past tense."),
        _q("What is the past tense of 'see'?", ["saw", "seed", "seen-ed"], 0, "See is irregular: saw."),
        _q("Which is correct?", ["The boys run fast.", "The boys runs fast.", "The boys running fast."], 0, "Boys is plural, so run has no s."),
        _q("Which sentence is in the future tense?", ["Tomorrow it will rain.", "Yesterday it rained.", "It rains."], 0, "Will shows the future."),
        _q("Which sentence keeps the same tense?", ["Sam opened the gate and walked in.", "Sam opened the gate and walks in.", "Sam opens the gate and walked in."], 0, "Opened and walked are both past."),
        _q("In 'The deer strolled nearby', which word is the adverb?", ["nearby", "deer", "strolled"], 0, "Nearby tells where."),
        _q("Which question does an adverb NOT answer?", ["Who?", "How?", "When?"], 0, "Who is answered by a noun."),
        _q("What is the adverb made from 'gentle'?", ["gently", "gentley", "gentlely"], 0, "Drop the e and add y."),
        _q("What is the past tense of 'take'?", ["took", "taked", "taken-ed"], 0, "Take is irregular: took."),
    ],
    "Upload a photo of your paragraph with the verbs underlined and the adverbs circled.",
    "Rewrite your paragraph in the present tense. Which words had to change? Then try the future tense.",
    [("verb", "A word that tells what someone does or is."), ("tense", "The form of a verb that shows when something happens."), ("past tense", "Shows an action that has already happened."),
     ("present tense", "Shows an action happening now."), ("future tense", "Shows an action that has not happened yet."), ("adverb", "A word that tells how, when, where or how often something happens."),
     ("irregular", "A verb that does not follow the usual -ed rule for the past tense."), ("modify", "To add detail to another word.")],
    [
        _video("Verbs Part 3: Simple Verb Tenses (Past, Present, and Future Tense)", "4Rm9l6y3-WY",
               "Watch how verbs change for past, present and future tense, including the irregular verb 'ate' and the use of 'will' for the future. Say each example aloud.",
               "Write one sentence in each tense about your day.",
               ("How do you make the future tense?", ["Add will before the verb", "Add -ed", "Add -ing"], 0, "Will shows the future.")),
        _video("Adverbs for Kids: How, When, Where, and How Often", "Enaeun07_ZQ",
               "Watch how adverbs answer the questions how, when, where and how often. Try to spot each adverb before the video names it.",
               "Write four sentences, each with an adverb that answers a different question.",
               ("Which question does an adverb answer?", ["How, when, where or how often", "Who", "Which colour"], 0, "Adverbs add detail about the verb.")),
    ],
    _sort("Tense sorter", "Is each sentence past, present or future? Tap a tense, then Check.",
          ["Past", "Present", "Future"],
          [("Mia ran to the gate.", 0), ("We ate lunch outside.", 0), ("The dog barks loudly.", 1), ("She writes in her journal.", 1), ("Tomorrow we will visit the museum.", 2), ("I will paint a picture.", 2)]),
    [
        _wc("A verb tells what someone ___.", ["does", "owns", "colours"], 0, "A verb is a doing word."),
        _wc("The past tense of 'go' is ___.", ["went", "goed", "going"], 0, "Went is irregular."),
        _wc("An adverb can tell how, when, ___ or how often.", ["where", "who", "why not"], 0, "Where is one of the adverb questions."),
        _wc("The future tense uses the word ___.", ["will", "was", "were"], 0, "Will shows the future."),
        _wc("Which is spelt correctly?", ["happily", "happyly", "hapily"], 0, "Change y to i."),
        _wc("Which is spelt correctly?", ["gently", "gentley", "gentlely"], 0, "Drop the e and add y."),
    ],
    [
        {"key": "tenses", "label": "Three tenses", "hint": "One sentence in the past, present and future tense."},
        {"key": "paragraph", "label": "My paragraph", "hint": "Five or six sentences in the past tense."},
        {"key": "adverbs", "label": "My adverbs", "hint": "List the adverbs and say how, when or where for each."},
        {"key": "spelling", "label": "Spelling words", "hint": "ran, saw, went, ate, took, came."},
    ],
    ["Switching tense in the middle of a story.", "Writing 'goed', 'runned' or 'eated'.", "Adding s to a verb after 'will'.", "Spelling happily as 'happyly'.", "Thinking every word ending in -ly is an adverb.", "Forgetting the comma after an opening adverb."],
    [{"title": "Tense Time Machine", "description": "Say a sentence about your day in the past, present and future tense. Ask someone to guess which tense each one is.", "type": "speak", "difficulty": "medium", "evidence_type": "audio"}],
    "Answers vary. Check that the paragraph stays in the past tense, includes at least two irregular past tense verbs and three adverbs (how, when, where), puts a comma after an opening adverb, and spells the -ly adverbs and irregular verbs correctly. Sorter: Past: ran to the gate; ate lunch. Present: barks loudly; writes in her journal. Future: will visit; will paint.",
)

LESSONS = [W3L3]
