"""Stage 2 English, Block A (narrative writing), week 7, lessons 1 to 4.
Pass 2 (video pass): lessons at full depth plus videos for L2, L3 and L4. L1 has no video yet.
Video ids came from search and must be checked on playback. The module is not yet registered in lesson_library.py.
Keys use the prefix a7."""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _video, _sort, _wc

CHECK = "Check your work against the checklist before you submit."

A7L1 = build(
    "s2-eng-a7-l1-resolution-and-ending", "Resolution and Ending",
    "Learn how a story solves its problem in a way the reader believes, and how to finish with an ending that stays with them.",
    "Reading and writing: resolution and ending",
    ["EN2-RECOM-01", "EN2-CWT-01", "EN2-VOCAB-01"],
    {"EN2-RECOM-01": "Primary. Identifies how a story resolves its problem, the kind of ending it uses and what the ending shows about the character.",
     "EN2-CWT-01": "Writes an earned resolution and a finished ending with a reflection and a final line.",
     "EN2-VOCAB-01": "Learns the terms resolution, ending, twist, reflection, moral and cliffhanger."},
    "We are learning how a story solves its problem and ends in a way that feels earned and satisfying.",
    ["I can say what a resolution is.", "I can tell an earned resolution from a lucky one.", "I can name four kinds of ending.", "I can show how a character has changed.", "I can write a resolution and ending of my own."],
    ["resolution", "ending", "twist", "reflection", "moral", "cliffhanger"],
    ["Paper or notebook", "Pencil", "Your problem, complication and tense scene from week 6", "A story you are reading (your parent will help you choose)"],
    "Child knows the problem, complication and how to build tension from week 6. Resolution and ending are taught from the beginning.",
    "Every story you have planned so far has a problem and a complication. Now the reader is waiting for the most important question: how does it turn out?\n\nThe RESOLUTION is the part where the problem is solved or settled. The ENDING is how the story finishes and what the reader is left feeling. A great ending makes the reader sigh, smile or think. A weak ending makes them say, 'Is that it?'\n\nIn this lesson you will learn what makes a resolution believable, four kinds of ending, how to show that a character has changed, and how to write a final line. Then you will fix a rushed ending and write one of your own.",
    [
        _step("1", "What is a resolution?",
              "The resolution answers the problem. If the problem was a missing boat, the resolution tells us what happens about the boat. If the problem was a character's fear, the resolution shows what happens to that fear.\n\nIn the plot arc, the resolution comes after the climax, which is the most exciting moment. The climax is the big showdown. The resolution is the part where things settle down.\n\nA resolution does three jobs. It solves or settles the problem. It shows what the characters do next. It ties up loose ends, such as a lost object or a promise.\n\nWhen you read, ask: what was the problem at the start, and how is it dealt with at the end?",
              "Problem: Pip's boat has a hole. Complication: a storm washes the patch away. Resolution: Pip uses a gum leaf and tree sap to seal the hole, and the boat floats.",
              "The resolution answers the problem.",
              ("The resolution is the part where the problem is...", ["solved or settled", "first introduced", "made worse"], 0, "The resolution deals with the problem.")),
        _step("2", "Earned and lucky resolutions",
              "The best resolutions are EARNED. This means the character does something, or uses something they learned earlier, to solve the problem.\n\nA LUCKY resolution happens by chance or by magic with no effort from the character. Readers feel cheated.\n\nLucky: Suddenly the rain stopped and the boat fixed itself.\nEarned: Pip remembered that gum sap sticks to wood. He climbed the gum tree, scraped off the sap and pressed it into the hole.\n\nTo earn a resolution, plant a clue earlier in the story. If Pip mentions the sap in the orientation, the ending feels clever, not random.\n\nAsk: what does my character do to solve it, and did I hint at it earlier?",
              "Lucky: A friendly wizard appeared and fixed everything. Earned: Zara used the torch signal her grandfather had taught her to call the rescue boat.",
              "Let the character solve it, and plant a clue early.",
              ("An earned resolution is one where...", ["the character does something to solve it", "luck solves everything", "the author explains it"], 0, "The character acts.")),
        _step("3", "Four kinds of ending",
              "Stories can end in different ways. Choose the one that suits your story.\n\nHAPPY ending: the problem is solved and the character gets what they want.\nBITTERSWEET ending: the problem is solved, but something is lost or changed. A character may get the prize but lose a friend.\nOPEN ending: the story stops with a question unanswered, so the reader imagines what happens next.\nTWIST ending: a surprise at the very end changes how we see the story, such as the monster turning out to be a lost puppy.\n\nThe ending should match the mood. A funny adventure rarely ends in sadness. A spooky mystery may end with a twist.\n\nA CLIFFHANGER is different. It stops at the most exciting moment and does not give an answer. Cliffhangers suit the end of a chapter, but a single short story usually needs a proper ending.",
              "Bittersweet: Mia lit the lamp and the ships were saved, but the storm had destroyed her old home. Twist: The thief in the story was the family dog.",
              "Pick an ending that suits your mood.",
              ("An ending where something is lost even though the problem is solved is...", ["bittersweet", "happy", "open"], 0, "Bittersweet endings mix joy and loss.")),
        _step("4", "Show the change",
              "Good stories show how the character has CHANGED. At the start, Leo was afraid of the dark cellar. At the end, he walks in without a thought.\n\nShow the change with a REFLECTION, a moment where the character thinks or feels something new. Use thoughts, actions and small details.\n\nTell: Leo was not afraid anymore.\nShow: Leo flicked off the torch and walked down the cellar steps, humming.\n\nA MORAL is the lesson a story teaches, as in a fable. You do not have to write it out. Let the reader discover it. 'Slow and steady wins the race' is more powerful when we feel it than when we are told it.\n\nAsk: how is my character different from the start?",
              "Change: Ella no longer hid from the dog. She sat down on the grass, and the dog rested its head in her lap.",
              "Show the change with actions and a reflection.",
              ("A reflection shows...", ["what the character thinks, feels or learned", "the title", "the setting"], 0, "It shows a change inside the character.")),
        _step("5", "Fix a rushed ending",
              "Rushed endings are the most common mistake. Writers run out of time and write 'Then they went home. The End.'\n\nLook at this rushed ending: 'Zara found the key. She opened the door. Everyone was happy. The End.'\n\nHere is how to improve it in four steps.\n1. Slow down the solution. How did she find the key? What did she see or hear?\n2. Add a small moment of success with detail.\n3. Add a reflection about how she feels or has changed.\n4. Finish with a strong last line, not 'The End'.\n\nImproved: 'Zara knelt and reached into the mossy gap between the stones. Her fingers closed around something cold. The key! The old door groaned open, and golden light spilled across the floor. She smiled. She would never again be afraid of dark places. Outside, the first stars blinked awake.'",
              "Weak line: Everyone was happy. Stronger: Dad laughed so hard he had to sit down on the step.",
              "Slow down, add detail, reflect, finish well.",
              ("What should you add to fix a rushed ending?", ["Detail and a reflection", "More 'The End' lines", "A new problem"], 0, "Detail and a reflection make an ending feel complete.")),
        _step("6", "Write your resolution and ending",
              "Now write 6 to 8 sentences for your own story. Use this plan.\n\n1. Remind the reader of the problem in a few words.\n2. Show what the character does to solve it, using a clue you planted earlier.\n3. Slow down the moment of success with one or two sensory details.\n4. Show how things are different now.\n5. Add a short reflection.\n6. Finish with a strong last line, such as an image from the setting or something that returns to your opening.\n\nRead it aloud. Does the ending answer the problem? Does the reader feel satisfied?\n\nDo not add a brand new problem at the end. Resolve the one you have.",
              "Model: Ella laid the bacon trail from the park gate, one slice at a time. She held her breath and listened. A faint bark rose from the bushes. Out burst the muddy dog, tail wagging wildly. Ella hugged him tight and promised never to let go again. Behind them, the streetlights blinked on, one by one.",
              "Problem, action, detail, change, reflection, last line.",
              ("What should your last line do?", ["Leave the reader with a strong image or feeling", "Start a new story", "Repeat the title"], 0, "A strong last line stays with the reader.")),
    ],
    "Model answers. Resolution: the part where the problem is solved or settled. Earned resolution: the character acts and a clue was planted early. Four endings: happy, bittersweet, open, twist. Reflection: a moment where the character thinks or feels something new. Improved ending: Zara knelt and reached into the mossy gap between the stones. Her fingers closed around something cold. The key! The old door groaned open, and golden light spilled across the floor. She smiled. She would never again be afraid of dark places. Outside, the first stars blinked awake. Own ending: Ella laid the bacon trail from the park gate, one slice at a time. She held her breath and listened. A faint bark rose from the bushes. Out burst the muddy dog, tail wagging wildly. Ella hugged him tight and promised never to let go again. Behind them, the streetlights blinked on, one by one.",
    "1) Match four problems to earned resolutions. 2) Mark three resolutions as earned or lucky and rewrite one lucky one. 3) Name the ending type of three endings your parent reads aloud. 4) Write one sentence that shows a character has changed. 5) Improve a rushed ending in four steps. 6) Write your own 6 to 8 sentence resolution and ending.",
    "Write a 6 to 8 sentence resolution and ending for your story. Show how the character solves the problem, show the change and finish with a strong last line. Upload a photo of your writing.",
    CHECK,
    "Does my ending answer the problem? Does my character solve it by their own actions? Did I slow down the moment of success with detail? Did I show how the character changed? Did I include a reflection? Is my last line strong? Is it 6 to 8 sentences? Did I avoid adding a brand new problem?",
    [
        _q("The resolution is the part where the problem is...", ["solved or settled", "introduced", "made worse"], 0, "The resolution deals with the problem."),
        _q("An earned resolution is one where...", ["the character acts to solve it", "luck fixes it", "the narrator explains it"], 0, "The character earns the solution."),
        _q("Which is a lucky resolution?", ["Suddenly everything fixed itself.", "Pip used gum sap to seal the hole.", "Zara used the torch signal."], 0, "Nothing the character did solved it."),
        _q("A twist ending...", ["surprises the reader", "leaves nothing changed", "repeats the start"], 0, "A twist surprises."),
        _q("An ending where something is lost but the problem is solved is...", ["bittersweet", "open", "happy only"], 0, "Bittersweet mixes joy and loss."),
        _q("A reflection shows...", ["what the character feels or learned", "the title", "the number of pages"], 0, "It shows change."),
        _q("A moral is...", ["a lesson the story teaches", "a spelling rule", "a kind of verb"], 0, "A moral is a lesson."),
        _q("Which is the best way to fix a rushed ending?", ["Slow down and add detail", "Write The End", "Add a new problem"], 0, "Detail and reflection help."),
    ],
    "Upload a photo of your resolution and ending.",
    "Read the ending of a favourite story. What kind of ending is it? Does the character earn the resolution, and how does the character change?",
    [("resolution", "The part of a story where the problem is solved or settled."), ("ending", "How a story finishes and what the reader is left with."), ("twist", "A surprise that changes how we see the story."),
     ("reflection", "A moment where a character thinks or feels something new."), ("moral", "A lesson a story teaches."), ("cliffhanger", "An ending at an exciting point with no answer given.")],
    [],
    _sort("Ending types", "Which kind of ending is each? Tap a group, then Check.",
          ["Happy", "Open", "Twist"],
          [("The dog was home and everyone cheered.", 0), ("The friends hugged, and the problem was solved.", 0), ("She wondered what lay beyond the gate.", 1), ("No one ever found out where the path led.", 1), ("The ghost was the caretaker all along.", 2), ("The mysterious letter had been written by Leo himself.", 2)]),
    [
        _wc("The part where the problem is solved is the ___.", ["resolution", "revolution", "relation"], 0, "The resolution solves the problem."),
        _wc("A surprise ending is a ___.", ["twist", "twig", "twin"], 0, "A twist surprises the reader."),
        _wc("A moment when a character thinks or feels something new is a ___.", ["reflection", "refraction", "reaction"], 0, "A reflection shows change."),
        _wc("Which is spelt correctly?", ["resolution", "resolushun", "resolusion"], 0, "Resolution ends -tion."),
        _wc("Which is spelt correctly?", ["cliffhanger", "clifhanger", "cliffhangar"], 0, "Cliffhanger has ff."),
    ],
    [
        {"key": "matching", "label": "Earned or lucky", "hint": "Three resolutions marked, with one lucky one rewritten."},
        {"key": "change", "label": "Showing change", "hint": "One sentence that shows a character has changed."},
        {"key": "fix", "label": "Fixed rushed ending", "hint": "A rushed ending improved in four steps."},
        {"key": "ending", "label": "My resolution and ending", "hint": "6 to 8 sentences."},
    ],
    ["A sudden lucky solution.", "Rushing the ending in two or three lines.", "An ending that does not answer the problem.", "Adding a brand new problem at the end.", "Only writing The End."],
    [{"title": "Three Endings", "description": "Take one problem and write three different endings for it: happy, open and twist. Say which one suits the story best.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the ending answers the problem, the character earns the resolution, the moment of success has detail, change is shown, a reflection is included, the last line is strong, there is no new problem, and it is 6 to 8 sentences. Sorter: Happy: The dog was home; The friends hugged. Open: She wondered what lay beyond the gate; No one ever found out where the path led. Twist: The ghost was the caretaker; The letter had been written by Leo himself.",
)

A7L2 = build(
    "s2-eng-a7-l2-planning-a-whole-narrative", "Planning a Whole Narrative",
    "Learn to plan a complete story from beginning to end so your writing is organised, balanced and ready to write.",
    "Writing: planning a narrative",
    ["EN2-CWT-01", "EN2-RECOM-01", "EN2-VOCAB-01"],
    {"EN2-CWT-01": "Primary. Plans a whole narrative using a story map and paragraph plan, and chooses where to place the most detail.",
     "EN2-RECOM-01": "Identifies the stages of a narrative in a model text and checks that a plan is complete.",
     "EN2-VOCAB-01": "Revises the terms orientation, complication, resolution, paragraph, plan and scope."},
    "We are learning how to plan a whole story so that the writing is organised and every part has a purpose.",
    ["I can name the stages of a narrative in order.", "I can fill in a story map.", "I can decide what goes in each paragraph.", "I can choose where to put the most detail.", "I can check and improve my own plan."],
    ["orientation", "complication", "resolution", "paragraph", "plan", "scope"],
    ["Paper or notebook", "Pencil", "Your work from weeks 4 to 7: character, opening, problem, tension and ending"],
    "Child has met each stage in earlier lessons. This lesson puts them together into a full plan.",
    "You have learned a lot about stories: characters, openings, setting, problem, complication, tension and endings. Now it is time to use them all at once.\n\nBefore a builder builds a house, they make a plan. A story needs one too. A PLAN stops the story from wandering, stops you running out of ideas halfway, and helps you put your best detail in the right place.\n\nIn this lesson you will name the stages in order, make a story map, plan each paragraph, study a worked example and then plan a story of your own. You will write it in week 8.",
    [
        _step("1", "The stages in order",
              "A narrative has stages that follow a pattern.\n\n1. ORIENTATION: introduce the main character, setting and time. Hook the reader.\n2. PROBLEM: show what the character wants and what goes wrong.\n3. COMPLICATION: make it harder. Build tension.\n4. CLIMAX AND RESOLUTION: the most exciting moment, then the problem is solved.\n5. ENDING: show the change, add a reflection and finish with a strong line.\n\nMany stories give one paragraph to each stage, with extra paragraphs for the exciting parts. A story of five to seven paragraphs is a good size for this stage.\n\nIf you leave out a stage, the story feels incomplete. If the stages are in the wrong order, it can be confusing.",
              "Check a story you know: Orientation (a small pig builds a house), problem (a wolf), complication (the house blows down), resolution (the brick house holds), ending (the wolf runs away).",
              "Five stages, in order.",
              ("Which stage comes first?", ["Orientation", "Resolution", "Complication"], 0, "Orientation introduces the story.")),
        _step("2", "Make a story map",
              "A story map is a simple chart that holds your main ideas on one page.\n\nWHO: the main character, with a name and two traits.\nWHERE and WHEN: the setting and time.\nGOAL: what the character wants.\nPROBLEM: what stands in the way.\nCOMPLICATION: what makes it harder.\nSOLUTION: how the character solves it, and what clue you will plant early.\nCHANGE: how the character is different at the end.\n\nWrite only short notes: words and phrases, not full sentences. The map is for you, not for the reader.\n\nMake sure your ideas link. The problem should fit the setting. The solution should come from the character's traits.",
              "Who: Mia, brave but impatient. Where: old lighthouse, stormy night. Goal: light the lamp. Problem: no matches. Complication: storm blows out her candle. Solution: sparks from a flint (clue: her grandfather's flint in the drawer). Change: more patient.",
              "Short notes in each box, with ideas that link.",
              ("Story map notes should be...", ["short words and phrases", "full paragraphs", "left empty"], 0, "Short notes are quicker to use.")),
        _step("3", "Choose a story you can finish",
              "One of the biggest planning mistakes is choosing a story that is too big. This is called getting the SCOPE wrong. 'A trip around the world in twelve countries' cannot be told well in a few paragraphs.\n\nChoose a small story. A short time, one place and a few characters work best.\n\nToo big: Lena sails across the ocean for three months and visits ten islands.\nJust right: Lena searches the beach for her lost compass during one stormy afternoon.\n\nSmall stories let you add detail, tension and feeling. Big stories end up rushed.\n\nAsk: can I tell this story in six paragraphs with plenty of detail?",
              "Shrink the story: from 'a year at a new school' to 'the first morning at a new school'.",
              "Small stories allow strong detail.",
              ("Which story has the best scope?", ["One afternoon searching a beach", "A trip around the world", "A life story"], 0, "A short time and one place is easier to finish.")),
        _step("4", "Plan each paragraph",
              "After the story map, plan what goes in each paragraph.\n\nParagraph 1: ORIENTATION. A hook, then who, where and when.\nParagraph 2: PROBLEM. The character's goal and what goes wrong.\nParagraph 3: COMPLICATION and TENSION. Slow down. Use senses and a short sentence for effect.\nParagraph 4: CLIMAX and RESOLUTION. The character acts to solve it.\nParagraph 5: ENDING. Change, reflection and a strong last line.\n\nFor each paragraph, write one line of notes. Then mark where you will use the techniques you have learned, such as show, don't tell, strong verbs, adverbial phrases, dialogue and complex sentences.\n\nPut the most detail in the exciting parts: the complication, tension and climax. Keep the orientation and ending shorter.",
              "Para 3 notes: storm hits, wind howls, candle blows out, heart pounding, short sentence: Darkness. Techniques: senses, strong verbs.",
              "One paragraph, one stage, with techniques marked.",
              ("Where should you put the most detail?", ["The exciting parts", "Everywhere equally", "The title only"], 0, "Stretch the key moments.")),
        _step("5", "A worked example",
              "Look at this plan and see how it follows the rules.\n\nTitle idea: The Last Match\nPara 1: Hook with sound (a distant foghorn). Mia, ten, lives in an old lighthouse. A stormy evening.\nPara 2: The lighthouse keeper is ill, so Mia must light the lamp. She finds the matchbox empty.\nPara 3: She tries the stove, but it is cold. Wind blows out her candle. Dark, loud, scary. Short sentence for effect: Darkness.\nPara 4: She remembers her grandfather's flint in the drawer (clue from para 1). She strikes it, and sparks catch the wick. The lamp blazes.\nPara 5: Ships turn safely away from the rocks. Mia feels braver. Last line returns to the foghorn.\n\nNotice the ending links back to the hook. The solution grows from a clue. There is one setting and one night. It is a story that can be finished well.\n\nNow compare a weak plan: 'Mia lives in a lighthouse. She lights the lamp. Everyone is happy.' It has no problem, no complication and no change.",
              "Check list: hook, clue, complication, earned solution, change, last line returns to the start.",
              "A good plan has links between its parts.",
              ("What makes the ending of the worked plan feel earned?", ["The flint was planted as a clue early", "Luck fixed it", "A wizard helped"], 0, "Planting a clue earlier makes the resolution earned.")),
        _step("6", "Plan your own story and check it",
              "Now make your own plan.\n\n1. Fill in a story map: who, where and when, goal, problem, complication, solution (with a clue), change.\n2. Write a one-line plan for each of five or six paragraphs.\n3. Mark where you will use at least four techniques from weeks 4 to 7.\n4. Check with these questions.\n   Does the character have a clear goal?\n   Is the problem clear?\n   Is there a complication?\n   Is there a clue planted for the solution?\n   Does the ending show change?\n   Is the scope small enough to finish?\n5. Fix anything weak now. It is much easier to fix a plan than a finished story.\n6. Keep your plan to use in week 8.",
              "Fix example: no complication, so add 'a gust of wind scatters the map pieces'.",
              "Check each part, then fix.",
              ("When is it easiest to fix a weak part of the story?", ["In the plan", "After it is written", "Never"], 0, "Plans are easy to change.")),
    ],
    "Model answers. Stages in order: orientation, problem, complication, climax and resolution, ending. Story map sample: Who Mia (brave but impatient), where an old lighthouse on a stormy night, goal light the lamp, problem the matchbox is empty, complication the wind blows out her candle, solution sparks from her grandfather's flint (clue in para 1), change more patient. Paragraph plan: five paragraphs, one per stage, with most detail in paragraphs 3 and 4. Scope: choose a short time and one place. Check that the plan has a goal, problem, complication, planted clue, change and last line.",
    "1) Put five stage cards in order. 2) Complete a partly filled story map your parent gives you. 3) Shrink two stories that are too big. 4) Write a one-line plan for five paragraphs. 5) Mark four techniques on your plan. 6) Check your plan with the six questions and fix any weak part.",
    "Make a story map and a five or six paragraph plan for a narrative you will write next week. Mark at least four techniques. Upload a photo of your plan.",
    CHECK,
    "Is there a clear goal? Is there a problem and a complication? Is there a clue planted for the solution? Does the resolution grow from the problem? Is there a change at the end? Is each paragraph planned with a purpose? Are four techniques marked? Is the story small enough to finish?",
    [
        _q("Which stage comes first?", ["orientation", "resolution", "ending"], 0, "Orientation introduces the story."),
        _q("A story map has...", ["short notes", "full essays", "nothing"], 0, "Short notes keep it quick."),
        _q("A paragraph usually covers...", ["one stage or idea", "the whole story", "one word"], 0, "One idea per paragraph."),
        _q("Most detail should go in...", ["the exciting parts", "the title", "the first word"], 0, "Stretch the key moments."),
        _q("A plan helps you...", ["stay organised and finish", "avoid writing", "copy"], 0, "A plan keeps the story on track."),
        _q("A story with good scope is...", ["small enough to finish well", "enormous", "only one line"], 0, "Small stories allow detail."),
        _q("A planted clue helps the resolution feel...", ["earned", "lucky", "rushed"], 0, "A clue makes the solution believable."),
        _q("Which story is too big?", ["A year of travelling the world", "One afternoon on a beach", "One night in a lighthouse"], 0, "It could not be told with detail in a few paragraphs."),
    ],
    "Upload a photo of your story map and paragraph plan.",
    "Pick a short story from a book of your choice and make a story map for it. Check whether it has a planted clue.",
    [("orientation", "The part that introduces character, setting and time."), ("complication", "A new event that makes the problem harder."), ("resolution", "The part where the problem is solved."),
     ("paragraph", "A group of sentences about one idea."), ("plan", "Notes made before writing."), ("scope", "How big or small a story is.")],
    [
        _video("How to Create a Story Map for Kids: Planning Your Narrative Writing", "lcD6ijirN2g",
               "Watch how a story map shows the characters, setting and the plot events in the beginning, middle and end. Pause and say what would go in each box of your own story map.",
               "If the video does not play, make a story map on paper with boxes for characters, setting, beginning, middle and end.",
               ("A story map shows the characters, the setting and...", ["the plot events", "the spelling words", "the page numbers"], 0, "A story map organises the plot events in the beginning, middle and end.")),
    ],
    _sort("Which stage?", "Which stage does each line belong to? Tap a group, then Check.",
          ["Orientation", "Complication", "Resolution"],
          [("A foggy harbour at dawn", 0), ("Mia lived in an old lighthouse", 0), ("A storm blew out the lamp", 1), ("The matches were wet", 1), ("Sparks from the flint lit the wick", 2), ("The ships were guided safely home", 2)]),
    [
        _wc("Notes made before writing are a ___.", ["plan", "plane", "plant"], 0, "A plan is made before writing."),
        _wc("A group of sentences about one idea is a ___.", ["paragraph", "paragram", "parable"], 0, "That is a paragraph."),
        _wc("How big or small a story is is its ___.", ["scope", "scone", "score"], 0, "Scope."),
        _wc("Which is spelt correctly?", ["paragraph", "paragragh", "paragraf"], 0, "Paragraph has ph."),
        _wc("Which is spelt correctly?", ["complication", "complikation", "complicasion"], 0, "Complication ends -tion."),
    ],
    [
        {"key": "map", "label": "Story map", "hint": "Who, where, goal, problem, complication, solution with clue, change."},
        {"key": "plan", "label": "Paragraph plan", "hint": "One line for each paragraph."},
        {"key": "techniques", "label": "Techniques marked", "hint": "At least four techniques marked on the plan."},
        {"key": "check", "label": "Plan check", "hint": "The six questions answered and one fix made."},
    ],
    ["Starting to write with no plan.", "A story too big to finish.", "A plan with no complication.", "A resolution that does not fit the problem.", "Writing full sentences in the plan instead of notes."],
    [{"title": "Plan Swap", "description": "Make a plan, then show it to a parent who tells you one thing to strengthen. Improve it and explain what you changed.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check that the plan has a goal, problem, complication, planted clue, resolution and change, each paragraph has a purpose, at least four techniques are marked, and the story is a manageable size. Sorter: Orientation: A foggy harbour at dawn; Mia lived in an old lighthouse. Complication: A storm blew out the lamp; The matches were wet. Resolution: Sparks from the flint lit the wick; The ships were guided safely home.",
)

A7L3 = build(
    "s2-eng-a7-l3-complex-sentences", "Complex Sentences",
    "Learn how conjunctions join ideas into complex sentences that make your writing flow, build tension and show how events connect.",
    "Language: complex sentences",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-RECOM-01"],
    {"EN2-CWT-01": "Primary. Writes complex sentences using a range of conjunctions and punctuates them correctly.",
     "EN2-VOCAB-01": "Learns the terms clause, conjunction, main clause, subordinate clause, complex sentence and fragment.",
     "EN2-RECOM-01": "Identifies clauses and conjunctions in a text and explains how they link ideas."},
    "We are learning to write complex sentences that join ideas clearly and punctuate them correctly.",
    ["I can say what a clause is.", "I can tell a main clause from a subordinate clause.", "I can use conjunctions of reason, time, condition and contrast.", "I can move the extra clause to the front and add a comma.", "I can write complex sentences for my own story."],
    ["clause", "conjunction", "main clause", "subordinate clause", "complex sentence", "fragment"],
    ["Paper or notebook", "Pencil", "A paragraph from your story"],
    "Child writes simple and compound sentences with and, but and so. Complex sentences are taught from the beginning.",
    "So far you have probably written many short sentences and a few joined with 'and' or 'but'. Good writers also use COMPLEX SENTENCES. These join two ideas so that one depends on the other.\n\n'Mia lit the lamp.' is a simple sentence. 'Mia lit the lamp because the storm was coming.' is a complex sentence. The second gives a reason and shows how events connect.\n\nIn this lesson you will learn what a clause is, how to tell a main clause from a subordinate clause, which conjunctions to use, how to place the clauses and punctuate, and how to fix a common mistake. Then you will write complex sentences for your own story.",
    [
        _step("1", "What is a clause?",
              "A CLAUSE is a group of words that contains a verb and says something about a subject.\n\n'Mia climbed.' Subject Mia, verb climbed. One clause.\n'The storm raged.' One clause.\n'Because the wind howled.' Subject wind, verb howled. It is a clause, but it does not make a full sentence.\n\nThe quick test is to find the verb. Each verb usually belongs to a clause. A sentence with one verb has one clause. A sentence with two verbs in two parts has two clauses.\n\n'Mia climbed the stairs.' One clause.\n'Mia climbed the stairs because she heard a noise.' Two clauses: climbed and heard.",
              "Count clauses: Leo ran and hid. (two verbs, joined) The cat purred. (one) When the bell rang, the children left. (two).",
              "Each clause has a verb.",
              ("A clause always has a...", ["verb", "colour", "capital letter only"], 0, "Every clause has a verb.")),
        _step("2", "Main and subordinate clauses",
              "A MAIN CLAUSE makes sense on its own. It can stand alone as a sentence.\n\n'Mia lit the lamp.' Main clause.\n\nA SUBORDINATE CLAUSE adds extra information but cannot stand alone. It leaves you waiting.\n\n'because the storm was coming' Subordinate clause. Because what? We need the main clause.\n\nA COMPLEX SENTENCE has one main clause and at least one subordinate clause.\n\n'Mia lit the lamp (main) because the storm was coming (subordinate).'\n\nThe subordinate clause begins with a CONJUNCTION. You will meet many in the next step.\n\nQuick test: say the clause alone. If it sounds finished, it is a main clause. If it leaves you hanging, it is subordinate.",
              "Test: 'Although she was scared' leaves us hanging, so it is subordinate. 'She climbed the stairs' sounds finished, so it is main.",
              "Main clause stands alone. Subordinate clause does not.",
              ("Which can stand alone as a sentence?", ["Mia lit the lamp.", "because it was dark", "although she tried"], 0, "The first is a main clause.")),
        _step("3", "A bank of conjunctions",
              "Different conjunctions do different jobs. Choose the one that fits your meaning.\n\nREASON: because, since, as. 'She hurried because the tide was rising.'\nTIME: when, while, after, before, until, as soon as. 'He waited until the storm passed.'\nCONDITION: if, unless. 'If the lamp fails, the ships will be lost.'\nCONTRAST: although, even though, whereas. 'Although he was tired, he kept rowing.'\n\nDo not use only 'and' and 'but'. A range of conjunctions makes writing more interesting and shows how ideas link.\n\nWatch out for 'although ... but'. You should use only one of them in a sentence. 'Although it rained, we played' is correct. 'Although it rained, but we played' is not.",
              "Same idea, three conjunctions: She ran because she was late. She ran when she heard the bell. She ran although her legs ached.",
              "Choose the conjunction that fits the meaning.",
              ("Which conjunction shows contrast?", ["although", "because", "after"], 0, "Although shows contrast.")),
        _step("4", "Move the clause and use a comma",
              "You can put the subordinate clause second or first.\n\nSecond: Mia climbed the stairs although she was scared.\nFirst: Although she was scared, Mia climbed the stairs.\n\nWhen the subordinate clause comes FIRST, put a COMMA after it. When it comes second, you usually do not need one.\n\nWhen the sentence begins with a conjunction like when, if, although or as, check for a comma after the first clause.\n\nPutting the extra clause first builds tension. The reader waits for the main action.\n\n'As the door creaked open, Leo held his breath.'\n'When the lights went out, everything went silent.'\n\nVary where you put the subordinate clause so not every sentence has the same shape.",
              "Move it: He waited until the storm passed. Until the storm passed, he waited.",
              "Clause first needs a comma.",
              ("When the extra clause comes first you need...", ["a comma", "a question mark", "nothing"], 0, "A comma goes after the opening clause.")),
        _step("5", "Fix fragments and combine sentences",
              "A FRAGMENT is a subordinate clause written as if it were a full sentence. It is a common mistake.\n\nFragment: Because the storm was coming.\nFixed: She lit the lamp because the storm was coming.\n\nTo fix a fragment, join it to a main clause, or rewrite it so that it can stand alone.\n\nYou can also combine two short sentences to make one complex sentence.\n\nShort: The wind howled. Mia kept the lamp burning.\nCombined: Although the wind howled, Mia kept the lamp burning.\n\nShort: Leo opened the door. He held his breath.\nCombined: As Leo opened the door, he held his breath.\n\nDo not make a sentence too long. If a sentence has more than two clauses, it can lose the reader. Split it if it becomes hard to follow.",
              "Fix: When the clock struck twelve. Fixed: When the clock struck twelve, the garden gate swung open.",
              "Join fragments to a main clause.",
              ("A fragment is...", ["a subordinate clause written as a sentence", "a complete sentence", "a paragraph"], 0, "It cannot stand alone.")),
        _step("6", "Write complex sentences for your story",
              "Now write complex sentences for the story you planned.\n\n1. Write six complex sentences from different parts of your plan.\n2. Use at least four different conjunctions from the bank.\n3. Put the subordinate clause first in at least two, and add a comma.\n4. Underline the conjunction in each.\n5. Check each main clause makes sense on its own.\n6. Read them aloud. If a sentence is hard to follow, split it.\n\nModel: Although the wind howled, Mia kept the lamp burning. She waited until dawn broke because she knew the ships needed her. When the first light touched the waves, she finally let herself breathe.\n\nSpread complex sentences through your writing. Mix them with short simple sentences for effect.",
              "Check: Although the wind howled (subordinate), Mia kept the lamp burning (main).",
              "Four different conjunctions, commas after fronted clauses.",
              ("How many different conjunctions should you try?", ["A variety", "Only and", "None"], 0, "Variety makes writing flow.")),
    ],
    "Model answers. Clause: a group of words with a verb. Main clause: stands alone. Subordinate clause: needs a main clause. Conjunctions by job: reason (because, since, as), time (when, while, after, before, until), condition (if, unless), contrast (although, even though, whereas). A fronted clause needs a comma. Fixed fragment: She lit the lamp because the storm was coming. Combined: Although the wind howled, Mia kept the lamp burning. Sample sentences: Although the wind howled, Mia kept the lamp burning. She waited until dawn broke because she knew the ships needed her. When the first light touched the waves, she finally let herself breathe.",
    "1) Underline the verbs and count the clauses in six sentences. 2) Sort ten clauses as main or subordinate. 3) Choose the best conjunction for six gaps. 4) Move the clause to the front and add commas in four sentences. 5) Fix three fragments and combine three pairs of short sentences. 6) Write six complex sentences for your story.",
    "Write six complex sentences for your story using at least four different conjunctions. Put the subordinate clause first in at least two with a comma, and underline each conjunction. Upload a photo of your writing.",
    CHECK,
    "Does each sentence have a main clause that stands alone? Did I use at least four different conjunctions? Did I put a comma after the clause at the start? Did I underline each conjunction? Did I avoid fragments? Are the sentences clear and not too long?",
    [
        _q("A clause always contains a...", ["verb", "adjective", "comma"], 0, "Every clause has a verb."),
        _q("A main clause...", ["can stand alone", "cannot stand alone", "has no verb"], 0, "It makes sense on its own."),
        _q("A subordinate clause...", ["needs a main clause", "is a full sentence", "has no words"], 0, "It depends on a main clause."),
        _q("Although shows...", ["contrast", "time", "place"], 0, "Although shows contrast."),
        _q("Because shows...", ["reason", "contrast", "place"], 0, "Because shows reason."),
        _q("When the clause comes first you add a...", ["comma", "colon", "dash"], 0, "A comma follows it."),
        _q("Which is a fragment?", ["Because the storm was coming.", "She lit the lamp.", "The storm was coming."], 0, "It is a subordinate clause on its own."),
        _q("Which sentence is correct?", ["Although it rained, we played.", "Although it rained, but we played.", "Although it rained we, played."], 0, "Use although or but, not both."),
    ],
    "Upload a photo of your six complex sentences.",
    "Find three complex sentences in a book of your choice. Underline the conjunctions, circle the main clauses and say what job each conjunction does.",
    [("clause", "A group of words that contains a verb."), ("conjunction", "A word that joins clauses, such as because or although."), ("main clause", "A clause that makes sense on its own."),
     ("subordinate clause", "A clause that adds information and cannot stand alone."), ("complex sentence", "A sentence with a main clause and at least one subordinate clause."), ("fragment", "A subordinate clause written as if it were a complete sentence.")],
    [
        _video("What Is a Subordinate Clause? KS2 English Concept for Kids", "qxTTQ8t7OcY",
               "Watch how a subordinate clause has a subject and a verb but cannot make sense on its own, and how it usually starts with a subordinating conjunction such as if, since, as, when or although. Pause and say your own example.",
               "If the video does not play, write three main clauses and add a subordinate clause to each using because, when or although.",
               ("A subordinate clause...", ["cannot make sense on its own", "is always a full sentence", "has no verb"], 0, "It depends on a main clause to make a full sentence.")),
    ],
    _sort("Conjunction jobs", "What job does each conjunction do? Tap a group, then Check.",
          ["Reason", "Time", "Contrast"],
          [("because", 0), ("since", 0), ("when", 1), ("until", 1), ("although", 2), ("whereas", 2)]),
    [
        _wc("A group of words with a verb is a ___.", ["clause", "clue", "claws"], 0, "A clause has a verb."),
        _wc("A joining word like because is a ___.", ["conjunction", "connection", "conclusion"], 0, "A conjunction joins clauses."),
        _wc("A clause that cannot stand alone is ___.", ["subordinate", "separate", "simple"], 0, "It depends on a main clause."),
        _wc("Which is spelt correctly?", ["although", "altho", "allthough"], 0, "Although has one l after al."),
        _wc("Which is spelt correctly?", ["conjunction", "conjuntion", "conjuction"], 0, "Conjunction has junc."),
    ],
    [
        {"key": "clauses", "label": "Clauses sorted", "hint": "Ten clauses marked main or subordinate."},
        {"key": "fixes", "label": "Fragments and combining", "hint": "Three fragments fixed and three pairs combined."},
        {"key": "sentences", "label": "Six complex sentences", "hint": "At least four different conjunctions."},
        {"key": "commas", "label": "Commas", "hint": "Two sentences with the clause first."},
    ],
    ["Using only and and but.", "Forgetting the comma after a fronted clause.", "Writing a subordinate clause as a full sentence.", "Very long sentences that lose the reader.", "Using although and but together."],
    [{"title": "Conjunction Swap", "description": "Write one idea three ways using three different conjunctions, then pick the best and say why.", "type": "write", "difficulty": "medium", "evidence_type": "photo"}],
    "Answers vary. Check each sentence has a main clause that can stand alone, at least four conjunctions appear, a comma follows a fronted clause, there are no fragments, conjunctions are underlined, and sentences are clear. Sorter: Reason: because, since. Time: when, until. Contrast: although, whereas.",
)

A7L4 = build(
    "s2-eng-a7-l4-spelling-suffixes-ful-less-ly", "Spelling: Suffixes -ful, -less, -ly",
    "Learn how the suffixes -ful, -less and -ly change a word, and master the rules for spelling them correctly.",
    "Spelling: suffixes",
    ["EN2-SPELL-01", "EN2-VOCAB-01", "EN2-CWT-01"],
    {"EN2-SPELL-01": "Primary. Spells words with the suffixes -ful, -less and -ly accurately, applying the y to i and le to ly rules.",
     "EN2-VOCAB-01": "Uses suffixes to work out and extend word meaning and word class.",
     "EN2-CWT-01": "Uses suffixed words correctly in sentences."},
    "We are learning how the suffixes -ful, -less and -ly change a word and how to spell them using the rules.",
    ["I can say what a suffix is.", "I can say what -ful, -less and -ly mean.", "I can change y to i before a suffix.", "I can change le to ly.", "I can spell ten suffixed words and use them in sentences."],
    ["suffix", "base word", "-ful", "-less", "-ly", "adverb"],
    ["Paper or notebook", "Pencil", "A dictionary (your parent will help)"],
    "Child knows prefixes from week 6. Suffixes -ful, -less and -ly and their spelling rules are taught from the beginning.",
    "Last week you learned that a prefix goes on the start of a word. A SUFFIX goes on the END. It changes the meaning of the word and often its word class too.\n\ncare + ful = careful (full of care)\ncare + less = careless (without care)\nquick + ly = quickly (in a quick way)\n\nThe word you start with is the BASE WORD. Some suffixes need a spelling change when you add them. In this lesson you will learn the three suffixes, the rules for y to i and le to ly, and the common traps. Then you will practise and use the words in sentences.",
    [
        _step("1", "What is a suffix?",
              "A suffix is added to the END of a base word.\n\n-FUL means full of: careful, helpful, joyful, thankful.\n-LESS means without: careless, helpless, fearless, hopeless.\n-LY usually turns an adjective into an ADVERB, a word that tells how something is done: quickly, slowly, bravely.\n\nNotice something about -ful. It has only ONE l. 'Full' has two l's, but the suffix is spelt -ful. So we write 'careful', not 'carefull'.\n\nWhen you meet a long word, look for a suffix at the end and a base word at the start. This helps you read and spell it.",
              "hope + ful = hopeful. hope + less = hopeless. thank + ful = thankful.",
              "-ful has one l.",
              ("How is the suffix -ful spelt?", ["With one l", "With two l's", "With three l's"], 0, "The suffix -ful has one l.")),
        _step("2", "Using -ful and -less",
              "Usually you just add the suffix to the base word and the base word does not change.\n\ncare: careful, careless.\nhelp: helpful, helpless.\nfear: fearful, fearless.\nhope: hopeful, hopeless.\n\nFor base words that end in a silent e, keep the e before -ful and -less.\n\ncare + ful = careful. hope + less = hopeless. use + ful = useful.\n\nMany words come in opposite pairs: careful and careless, hopeful and hopeless, helpful and helpless. Learning one helps you remember the other.\n\nSome words only take one of the suffixes. You can say 'thankful' but not 'thankless' in the same meaning. Check a dictionary if you are not sure.",
              "Opposite pairs: careful, careless. hopeful, hopeless. useful, useless.",
              "Just add the suffix. Keep a silent e.",
              ("Which is spelt correctly?", ["hopeless", "hopless", "hopelss"], 0, "Keep the e in hope.")),
        _step("3", "The y to i rule",
              "When the base word ends in a CONSONANT plus y, change the y to i before adding most suffixes.\n\nbeauty + ful = beautiful.\nmercy + less = merciless.\npity + ful = pitiful.\nplenty + ful = plentiful.\n\nThis rule also applies to -ly.\nhappy + ly = happily.\nangry + ly = angrily.\neasy + ly = easily.\nlucky + ly = luckily.\n\nWhy? Because a y in the middle of a word often turns into an i, as in 'beautiful'. Say the word out loud and listen.\n\nIf the base word ends in a VOWEL plus y, such as 'play' or 'joy', keep the y: playful, joyful, joyless.",
              "Rule: beauty to beautiful, happy to happily. Exception: joy keeps y, so joyful.",
              "Consonant plus y: change y to i.",
              ("Which is spelt correctly?", ["beautiful", "beautyful", "beautifull"], 0, "Beauty changes y to i.")),
        _step("4", "The suffix -ly",
              "-LY turns an adjective into an adverb that tells how something is done.\n\nquick, quickly. slow, slowly. brave, bravely. loud, loudly. quiet, quietly.\n\nMost of the time you just add -ly. If the base word ends in e, keep it: brave, bravely. 'Sure' becomes 'surely'.\n\nSome words end in -ful. For these, add -ly to make -fully, which has two l's: careful, carefully. hopeful, hopefully. thankful, thankfully.\n\nSo -ful has one l, but -fully has two. Say it as 'care-ful-ly'.\n\nAdverbs with -ly add detail to verbs and help create clear pictures: 'She carefully carried the bowl.' 'The door creaked slowly open.'",
              "Careful to carefully: She carried the bowl carefully across the room.",
              "-ful then -ly makes -fully.",
              ("Which is spelt correctly?", ["carefully", "carefuly", "carefuley"], 0, "Careful plus ly makes carefully.")),
        _step("5", "The le to ly rule and traps",
              "If the base word ends in LE, drop the le and add -y.\n\ngentle, gently. simple, simply. terrible, terribly. horrible, horribly. possible, possibly.\n\nDo not write 'gentlely' or 'simpley'.\n\nIf the base word ends in IC, add -ally.\n\nbasic, basically. magic, magically. tragic, tragically.\n\nThere is one common exception: public, publicly.\n\nOther traps to watch for:\n- true, truly (drop the e).\n- whole, wholly.\n- full, fully (one l is dropped).\n- day, daily (y to i).\n\nThese do not follow every rule, so learn them by heart with look, say, cover, write, check.",
              "Rule check: gentle to gently, magic to magically, true to truly.",
              "le to ly. ic to ally. Learn exceptions by heart.",
              ("Which is spelt correctly?", ["gently", "gentlely", "gentley"], 0, "Drop the le and add y.")),
        _step("6", "Practise and use the words",
              "Now practise.\n\n1. Look, say, cover, write, check these twelve words: careful, careless, hopeful, hopeless, beautiful, pitiful, quickly, bravely, happily, easily, gently, carefully.\n2. Underline the suffix in each.\n3. Write the base word beside each.\n4. Write which rule you needed, if any: silent e, y to i, le to ly.\n5. Write four sentences, each using a different suffixed word. Make at least one a -ly adverb that adds detail to a verb.\n6. Read each sentence aloud and check spelling. Ask a parent to test you on ten words.\n\nSample: The mouse crept quietly past the sleeping cat and gently pushed open the door.",
              "Sentence: She carefully carried the beautiful vase across the room.",
              "Find the suffix, check the rule, check the spelling.",
              ("What do you do for words that end in consonant plus y?", ["Change y to i", "Double the y", "Delete the word"], 0, "Change y to i before the suffix.")),
    ],
    "Model answers. -ful: full of (careful, helpful). -less: without (careless, hopeless). -ly: makes an adverb (quickly, slowly). Rules: keep a silent e before -ful and -less (careful, hopeless); consonant plus y changes to i (beautiful, happily, easily); le becomes ly (gently); ful plus ly makes fully (carefully); ic becomes ically (basically). Exceptions: publicly, truly, wholly, fully, daily. Sample sentences: The mouse crept quietly past the sleeping cat and gently pushed open the door. She carefully carried the beautiful vase across the room.",
    "1) Split twelve words into base word and suffix. 2) Add -ful, -less or -ly to ten base words, applying the rules. 3) Match four opposite pairs. 4) Write the rule used for six words. 5) Write four sentences, with at least one -ly adverb. 6) Do a ten word spelling test from a parent using look, say, cover, write, check.",
    "Write four sentences, each with a different suffixed word, and complete a ten word spelling test. Upload a photo of your sentences and your test.",
    CHECK,
    "Did I use one l in -ful? Did I change y to i where needed? Did I use le to ly correctly? Did I write -fully with two l's? Did I use each suffix at least once? Did I use at least one -ly adverb to add detail? Did I check my spelling?",
    [
        _q("A suffix is added...", ["at the end of a word", "at the start", "in the middle"], 0, "Suffixes come last."),
        _q("-ful means...", ["full of", "without", "again"], 0, "Full of."),
        _q("-less means...", ["without", "full of", "again"], 0, "Without."),
        _q("Which is spelt correctly?", ["careful", "carefull", "carful"], 0, "Careful has one l at the end."),
        _q("Which is spelt correctly?", ["beautiful", "beautyful", "beautifull"], 0, "Change y to i."),
        _q("Which is spelt correctly?", ["gently", "gentlely", "gentley"], 0, "Drop the le and add y."),
        _q("Which is spelt correctly?", ["easily", "easyly", "easly"], 0, "Change y to i."),
        _q("Which is spelt correctly?", ["carefully", "carefuly", "carefuley"], 0, "Careful plus ly has two l's."),
    ],
    "Upload a photo of your four sentences and your spelling test.",
    "Look for five more words that end in -ful, -less or -ly in a book of your choice. Split each into base word and suffix and say which rule applies.",
    [("suffix", "Letters added to the end of a word to change its meaning."), ("base word", "The word a suffix is added to."), ("-ful", "A suffix meaning full of."),
     ("-less", "A suffix meaning without."), ("-ly", "A suffix that often makes an adverb."), ("adverb", "A word that tells how, when or where something happens.")],
    [
        _video("Suffixes ful, less, ly, able | English Grammar for Grade 2 (Kids Academy)", "U_6mfwXe3Bo",
               "Watch how the suffix -ful means full of, -less means without, and -ly tells how or how often. Pause after each suffix and think of your own word.",
               "If the video does not play, write one word for each suffix, such as colourful, helpless and quickly, and say what each one means.",
               ("The suffix -less means...", ["without", "full of", "again"], 0, "-less means without, as in helpless.")),
    ],
    _sort("Suffix sorter", "Which suffix does each word end with? Tap a group, then Check.",
          ["-ful", "-less", "-ly"],
          [("careful", 0), ("hopeful", 0), ("careless", 1), ("fearless", 1), ("quickly", 2), ("bravely", 2)]),
    [
        _wc("Letters added to the end of a word are a ___.", ["suffix", "prefix", "syllable"], 0, "A suffix goes at the end."),
        _wc("The word a suffix joins is the ___ word.", ["base", "back", "big"], 0, "The base word."),
        _wc("Which is spelt correctly?", ["hopeless", "hopless", "hopelss"], 0, "Hope plus less."),
        _wc("Which is spelt correctly?", ["angrily", "angryly", "angryily"], 0, "Change y to i."),
        _wc("Which is spelt correctly?", ["simply", "simplely", "simpley"], 0, "Drop le and add y."),
    ],
    [
        {"key": "split", "label": "Base word and suffix", "hint": "Twelve words split into parts."},
        {"key": "rules", "label": "Rules used", "hint": "The rule for six words."},
        {"key": "sentences", "label": "Four sentences", "hint": "Four different suffixed words, with one -ly adverb."},
        {"key": "test", "label": "Spelling test", "hint": "Ten words read out by a parent."},
    ],
    ["Writing carefull with two l's.", "Forgetting to change y to i.", "Writing gentlely instead of gently.", "Dropping the e in careful.", "Writing carefuly instead of carefully."],
    [{"title": "Suffix Pairs", "description": "Make a table of ten base words and write the -ful, -less and -ly forms where they exist. Mark the rule used for each.", "type": "write", "difficulty": "easy", "evidence_type": "photo"}],
    "Answers vary. Check that -ful has one l, silent e is kept, y changes to i after a consonant, le words end in -ly, -fully has two l's, each suffix is used, at least one -ly adverb adds detail, and sentences make sense. Sorter: -ful: careful, hopeful. -less: careless, fearless. -ly: quickly, bravely.",
)

LESSONS = [A7L1, A7L2, A7L3, A7L4]
