"""Stage 2 English, Week 4 Lesson 2: Show, Don't Tell (Writing).
All written work is typed inside the lesson. Spelling (prefixes un-, re-, dis-, mis-) continues from Lesson 1 with new words.
No video is attached: none has been verified for this topic yet. Add one in the video and link run.
"""
from lesson_library_s2_english_w1_w2 import build, _q, _step, _sort, _wc
from spelling_s2_w1 import _w, _c

WORDS = ["unfair", "unsafe", "rewrite", "retell", "dislike", "misread"]

MODEL = (
    "The Big Race (telling version)\n"
    "Kofi was nervous. The race was about to start. He was determined to win. When he lost, he was upset.\n\n"
    "The Big Race (showing version)\n"
    "Kofi's fingers twisted the hem of his shirt. His stomach fluttered as the whistle rose to the referee's lips. 'Just run,' he whispered, and dug his toes into the dusty track. "
    "The whistle shrieked, and he shot forward, arms pumping, lungs burning, chin lifted. He crossed the line a heartbeat too late. Kofi stared at the ground, blinking hard. 'Next time,' he muttered, but his voice cracked."
)

LESSON = build(
    "s2-eng-w04-l2-show-dont-tell",
    "Show, Don't Tell",
    "Strong writers let readers work out feelings and moods for themselves. Learn how to replace plain telling sentences with showing sentences that use actions, body language, senses and speech.",
    "Writing: show, don't tell",
    ["EN2-CWT-01", "EN2-VOCAB-01", "EN2-SPELL-01"],
    {
        "EN2-CWT-01": "Primary. Plans, creates and revises imaginative writing by showing feelings and settings through actions, body language, senses, speech and precise word choices.",
        "EN2-VOCAB-01": "Chooses precise verbs, adjectives and adverbs, and uses vocabulary such as show, tell, body language and sensory detail.",
        "EN2-SPELL-01": "Spells words with the prefixes un-, re-, dis- and mis-, keeping the base word unchanged (week 4 spelling focus).",
    },
    "We are learning to show feelings and settings through actions, body language, senses and speech, instead of telling them.",
    ["I can explain the difference between showing and telling.", "I can show a feeling using body language and actions.", "I can show a setting using at least two senses.", "I can use speech to show what a character is like.", "I can rewrite a telling sentence as a showing paragraph.", "I can spell words with the prefixes un-, re-, dis- and mis-."],
    ["show", "tell", "body language", "sensory detail", "precise verb", "dialogue", "revise", "prefix"],
    ["This lesson (everything you need is inside it)"],
    "Child can use nouns, verbs and adjectives, the five senses and a story mountain (Weeks 2 and 3), and has met inference (Week 4 Lesson 1).",
    (
        "Why this matters. A telling sentence states a fact and stops there: 'Kofi was nervous.' A showing sentence lets the reader see, hear and feel it and work out the feeling themselves: 'Kofi's fingers twisted the hem of his shirt.' Showing is the writer's side of inference. Last lesson you worked out what authors left unsaid. Today you write the clues that let your reader do the same.\n\n"
        "Telling versus showing. Telling gives the label (nervous, angry, cold, spooky). Showing gives the evidence (twisting a shirt hem, slamming a door, breath puffing in the air, a floorboard creaking in the dark). The reader joins your clues and feels the idea as their own.\n\n"
        "Four ways to show. 1. Body language and actions: what the body does (clenched fists, a trembling lip, hunched shoulders). 2. The senses: what can be seen, heard, felt, smelled or tasted. 3. Speech: what a character says and how (whispered, snapped, stammered). 4. Precise verbs and well-chosen adjectives: shrieked instead of said loudly, trudged instead of walked slowly.\n\n"
        "A recipe for showing. Pick the telling sentence. Ask: what would I see, hear or feel if this were really happening? Write two or three details. Choose strong verbs. Do not use the telling word itself, such as scared or angry.\n\n"
        "A warning. Showing does not mean longer is always better. Use showing for the most important moments: the feelings, the turning points and the setting. A story made only of showing becomes slow, so mix them. Tell the small things quickly and show the big ones.\n\n"
        "Spelling focus. Continue with the prefixes un-, re-, dis- and mis-. Un-: unfair, unsafe. Re-: rewrite, retell. Dis-: dislike. Mis-: misread. Add the prefix to the whole base word with no letters lost or doubled."
    ),
    [
        _step("1", "Telling versus showing", "A telling sentence gives the label: 'Kofi was nervous.' A showing sentence gives the evidence, so the reader works out the feeling: 'Kofi's fingers twisted the hem of his shirt.'\n\nShowing makes readers feel part of the story.", "Telling: The room was cold. Showing: Goosebumps rose on Ana's arms, and her breath curled in the air.", "Telling states it; showing proves it.", ("Which sentence shows?", ["Kofi was nervous.", "Kofi's fingers twisted the hem of his shirt.", "Kofi felt a bit worried."], 1, "It gives actions as evidence.")),
        _step("2", "Show feelings with the body", "Think about what a feeling does to the body: face, hands, voice, eyes, stomach, legs.\n\nAvoid the label word. Use two or three details.", "Angry: Her jaw tightened and her fists clenched at her sides. Excited: He bounced on his toes and could not stop grinning.", "Describe what the body does.", ("Which shows being scared without saying it?", ["Her knees shook and she gripped the door handle.", "She was scared.", "She felt very scared."], 0, "The body language shows the feeling.")),
        _step("3", "Show a setting with the senses", "Use at least two senses to show a place or weather. Sight, sound, smell, touch and taste all help.\n\nThis connects to your work on describing a setting.", "Telling: It was a stormy night. Showing: Rain hammered the tin roof, and the wind whistled through the gaps in the window.", "Use the senses to show the setting.", ("Which sentence shows a hot day?", ["It was hot.", "The sun beat down, and the road shimmered like water.", "It was a very hot day."], 1, "It uses sight and feeling.")),
        _step("4", "Show with speech", "What a character says, and how they say it, shows who they are and how they feel. Use verbs like whispered, snapped, stammered, cheered.\n\nDo not use 'said angrily'. Show the anger in the words.", "'Get out,' she snapped, slamming the book shut.", "Speech shows character and feeling.", ("Which verb shows anger best?", ["said", "snapped", "asked"], 1, "Snapped carries the feeling.")),
        _step("5", "Use precise verbs", "Replace weak verbs (went, said, looked) with precise ones (trudged, muttered, glared). One strong verb can replace a verb and an adverb.\n\nThis shows the action in one word.", "Weak: He walked slowly. Strong: He trudged. Weak: She said quietly. Strong: She whispered.", "One strong verb does the work of two weak words.", ("Which verb replaces 'walked slowly'?", ["trudged", "ran", "jumped"], 0, "Trudged means walking slowly and heavily.")),
        _step("6", "Spelling focus: more prefixes", "Add the prefix to the whole base word. Un-: unfair, unsafe. Re-: rewrite, retell. Dis-: dislike. Mis-: misread.\n\nNo letters are lost or doubled, but watch for words such as dissatisfied, which is a different pattern.", "un + fair = unfair, re + write = rewrite, dis + like = dislike, mis + read = misread.", "Add the prefix to the whole base word.", ("Which is spelled correctly?", ["unfair", "unfare", "onfair"], 0, "un + fair.")),
        _step("7", "Revise: show the big moments", "After you draft, find the telling sentences about the big feelings and moments. Rewrite those with showing details. Leave the small, quick facts as telling.\n\nRead both versions aloud and notice the difference.", "Keep 'Kofi walked to the track' as telling. Show the moment before the whistle.", "Show the important moments, tell the rest.", ("Which part should you show?", ["The most important feeling or moment", "Every single sentence", "Nothing at all"], 0, "Showing is for key moments.")),
    ],
    (
        "Study the model, 'The Big Race', in its two versions. The telling version: 'Kofi was nervous. The race was about to start. He was determined to win. When he lost, he was upset.' It is short and clear but flat. "
        "The showing version replaces the feelings with evidence. Nervous becomes 'fingers twisted the hem of his shirt' and 'stomach fluttered' (body language). Determined becomes 'dug his toes into the dusty track' and 'Just run' (action and speech). "
        "The race itself becomes 'the whistle shrieked' with 'arms pumping, lungs burning' (precise verbs and senses). Upset becomes 'stared at the ground, blinking hard' and 'his voice cracked'. The label words nervous, determined and upset never appear, yet we feel all three. "
        "Now rewrite one together: 'The old house was creepy.' A showing version: 'The front door groaned as it opened, and a musty smell crept out of the dark. Dust coated the stair rail, and somewhere above, a floorboard creaked.' We used sound, smell, sight and a precise verb, and avoided the word creepy."
    ),
    (
        "Type your answers in the practice boxes. Part A: read these telling sentences and type a showing version of each (use body language or senses, and no label word): 'Mia was embarrassed.' 'The kitchen was warm.' 'Dad was tired.' Part B: type a stronger verb for each: walked slowly, said quietly, looked angrily, ate quickly. Part C: type the correct word: un + fair, re + write, dis + like, mis + read, un + safe, re + tell. Your parent can check your answers against the answer key."
    ),
    (
        "Read the model, then write your own. Everything you write goes in the boxes.\n\n" + MODEL + "\n\n"
        "Stage 1 (spot it): type three things in the showing version that replaced a label word, and name the label each one replaced.\n"
        "Stage 2 (feelings): choose three feelings from this list: jealous, proud, frightened, disappointed, excited, lonely. For each, type a showing sentence of at least ten words that uses body language or an action. Do not use the label word.\n"
        "Stage 3 (setting): choose a place from this list: a busy playground, a quiet library, a beach at dawn, a thunderstorm at night. Type a showing paragraph of three to four sentences that uses at least two senses. Do not name the mood.\n"
        "Stage 4 (speech): type four to six lines of dialogue between two characters in which one is secretly worried. Show the worry through what they say and do, not by naming it.\n"
        "Stage 5 (revise a story): type a telling paragraph of four sentences about a character who feels something big. Then type your revised showing version. Then type the three biggest changes you made.\n"
        "Stage 6 (spell): type your six spelling words and the prefix in each."
    ),
    "Which showing sentence are you proudest of, and which label word did it replace?", "Did I avoid label words, use body language and senses, use precise verbs, show only the big moments and spell my six prefix words correctly?",
    [_q("What is the difference between showing and telling?", ["Telling gives the label; showing gives the evidence", "Showing is shorter", "Telling uses senses", "There is no difference"], 0, "Showing gives evidence so the reader works it out."), _q("Which sentence shows?", ["Leo was angry.", "Leo slammed the door and stomped up the stairs.", "Leo felt very angry.", "Leo had an angry day."], 1, "Actions are evidence for the feeling."), _q("Which is a way to show?", ["Body language", "A long list of adjectives with no actions", "Using the feeling word three times", "Skipping the setting"], 0, "Body language and actions are evidence."), _q("Which sentence uses senses to show a setting?", ["It was a creepy cave.", "Water dripped in the darkness, and a damp smell clung to the stone.", "The cave was very creepy.", "I was in a cave."], 1, "It uses sound, smell and touch."), _q("Which precise verb replaces 'said quietly'?", ["whispered", "yelled", "ran", "sang"], 0, "Whispered says it in one word."), _q("Which moments should you usually show?", ["The most important ones", "Every sentence", "The title", "None"], 0, "Show the key moments and feelings."), _q("In the model, which detail shows Kofi was upset?", ["His voice cracked", "He was upset", "The whistle", "The dusty track"], 0, "His voice cracking and blinking hard show the feeling."), _q("What does the prefix re- mean?", ["Again", "Not", "Wrongly", "Before"], 0, "Re- means again."), _q("Which is spelled correctly?", ["unsafe", "unsaif", "onsafe", "unsaf"], 0, "un + safe."), _q("Which is spelled correctly?", ["misread", "misreed", "missread", "mysread"], 0, "mis + read.")],
    "Type your answers in the practice boxes and submit them.", "Extension: take a page from a story you enjoy. Find one telling sentence and rewrite it as showing, then compare it with what the author wrote.",
    [("show", "To give evidence so the reader works out a feeling or idea"), ("tell", "To state a feeling or fact directly"), ("body language", "What a body does to show a feeling"), ("sensory detail", "Details that use the five senses"), ("precise verb", "A strong, exact action word"), ("dialogue", "The words characters say aloud"), ("revise", "To improve writing after a first draft"), ("prefix", "Letters added to the start of a word that change its meaning")],
    [],
    _sort("Is it showing or telling?", "Sort each sentence as showing or telling.", ["Telling", "Showing"], [("Sam was nervous.", 0), ("Sam's knees wobbled, and he gripped the edge of the desk.", 1), ("The beach was beautiful.", 0), ("Warm sand trickled between her toes as waves hissed on the shore.", 1), ("Priya was proud.", 0), ("Priya stood tall and held the trophy high above her head.", 1), ("It was a stormy night.", 0), ("Thunder cracked, and rain hammered the window.", 1)]),
    [_wc("Which shows excitement?", ["He bounced on his toes and grinned.", "He was excited.", "He felt excited."], 0, "It gives evidence."), _wc("Which is a precise verb for 'walked slowly'?", ["trudged", "went", "did"], 0, "Trudged is exact."), _wc("Which shows a cold day?", ["Her breath puffed in the air.", "It was cold.", "The day was cold."], 0, "It gives a visual detail."), _wc("Which is correct?", ["unfair", "unfare", "onfair"], 0, "un + fair."), _wc("Which is correct?", ["rewrite", "reright", "rewrit"], 0, "re + write."), _wc("Which is correct?", ["dislike", "dislik", "dyslike"], 0, "dis + like."), _wc("Which is correct?", ["misread", "missread", "misreed"], 0, "mis + read."), _wc("Which means 'to tell again'?", ["retell", "mistell", "untell"], 0, "re- means again.")],
    [{"key":"partA","label":"Part A: show it","hint":"Rewrite: Mia was embarrassed. The kitchen was warm. Dad was tired."}, {"key":"partB","label":"Part B: precise verbs","hint":"walked slowly, said quietly, looked angrily, ate quickly."}, {"key":"partC","label":"Part C: prefixes","hint":"un+fair, re+write, dis+like, mis+read, un+safe, re+tell."}, {"key":"stage1","label":"Spot it","hint":"Three showing details in the model and the labels they replaced."}, {"key":"stage2","label":"Three feelings","hint":"Three showing sentences of at least ten words, no label word."}, {"key":"stage3","label":"A setting","hint":"Three or four sentences with at least two senses."}, {"key":"stage4","label":"Dialogue","hint":"Four to six lines where one character is secretly worried."}, {"key":"stage5a","label":"Telling paragraph","hint":"Four telling sentences about a big feeling."}, {"key":"stage5b","label":"Showing version","hint":"Your revised showing paragraph and the three biggest changes."}, {"key":"spelling","label":"Spelling words","hint":"Type six words and the prefix in each."}],
    ["Naming the feeling instead of showing it (using words such as scared or angry)", "Showing every sentence so the story drags", "Using only one sense", "Using said angrily instead of showing the anger", "Losing or doubling letters when adding a prefix"],
    ["Spot a telling sentence in a book you are reading and rewrite it as showing.", "Describe a feeling to a family member using only body language and ask them to name it."],
    "Part A: accept any showing sentence with evidence and no label word, for example Mia's cheeks burned and she stared at her shoes; sweat beaded on his forehead and the kitchen air pressed against him; Dad's eyelids drooped and he rubbed his face with both hands. Part B: trudged or strolled, whispered or murmured, glared or scowled, gobbled or gulped. Part C: unfair, rewrite, dislike, misread, unsafe, retell. Main task: look for evidence-based details with no label words, at least two senses in the setting, speech that reveals worry without naming it, and a real revision that keeps the quick facts as telling. Quiz answers: telling gives the label, showing gives the evidence; Leo slammed the door and stomped up the stairs; body language; water dripped in the darkness and a damp smell clung to the stone; whispered; the most important ones; his voice cracked; again; unsafe; misread.",
)

LESSON["spelling"] = {"focus":"More prefixes: un-, re-, dis-, mis-", "teaching":"Add the prefix to the whole base word. Nothing is lost or doubled. Un-: unfair, unsafe. Re-: rewrite, retell. Dis-: dislike. Mis-: misread. Un-, dis- and mis- often give an opposite or wrong meaning; re- means again.", "words":[_w("unfair","un-fair","un + fair"),_w("unsafe","un-safe","un + safe"),_w("rewrite","re-write","re + write"),_w("retell","re-tell","re + tell"),_w("dislike","dis-like","dis + like"),_w("misread","mis-read","mis + read")], "check":[_c("Which means 'to write again'?",["rewrite","miswrite","unwrite"],0,"Re- means again."),_c("Which is spelled correctly?",["dislik","dislike","dyslike"],1,"dis + like.")]}
LESSON["spelling_focus"] = "Prefixes: un-, re-, dis-, mis- (more words)"
LESSON["hoard_words"] = list(WORDS)
