// DRAFT COPY - review before launch.
export const CONTACT_EMAIL = "support@sidequestlearning.app";
export const PRIVACY_EMAIL = "support@sidequestlearning.app";
export const LAST_UPDATED = "11 October 2026";

export const GROUPS = [
  { id: "legal", title: "Legal", blurb: "The rules and the fine print, in plain language." },
  { id: "support", title: "Support", blurb: "Help when you need a hand." },
  { id: "privacy", title: "Account & privacy requests", blurb: "You are in control of your family's information." },
  { id: "trust", title: "Trust", blurb: "How Side Quest looks after your family's data." },
];

export const PAGES = {
  "privacy-policy": {
    group: "legal", title: "Privacy Policy", public: true,
    summary: "What I collect, why, who sees it, how long I keep it, and your rights.",
    sections: [
      { h: "In short", items: [
        "Side Quest is a home learning hub built by a parent for their own children, and shared with other families.",
        "I collect only what is needed to run your family's account and learning features.",
        "I do not sell personal information and there is no advertising for children.",
        "You can see, correct or delete your family's information at any time.",
      ] },
      { h: "Who I am", p: "Side Quest (sidequestlearning.app) is a personal project run by one parent in Australia, who is also homeschooling. It began as a tool for my own children and is not a registered business or company. In this policy, \"Side Quest\", \"I\", \"me\" and \"my\" mean the parent who runs sidequestlearning.app. You can contact me at support@sidequestlearning.app." },
      { h: "About this policy", p: "I handle personal information in line with the spirit of the Privacy Act 1988 (Cth) and the Australian Privacy Principles, even where the law may not strictly require it of a personal project. This policy applies to the Side Quest website and app, including the parent hub and the child area." },
      { h: "Information I collect from parents", items: [
        "Account details: your name, your email address and your sign-in credentials. Your email address is also used to help you get back into your account if you forget your password.",
        "Settings and preferences you choose in the parent hub.",
        "Records you create: lesson plans, learning plans, calendar entries, resources you save and notes.",
        "Messages you send me by email or through the contact and request pages.",
      ] },
      { h: "Information I collect about children", items: [
        "Profile details a parent enters: first name or nickname, year level and avatar or pet choices.",
        "A username and PIN code set up by the parent so the child can enter their own area.",
        "PIN requests: if a child forgets their PIN and asks for help, a request is recorded with the time and the child's profile, and shown to their parent on the parent dashboard.",
        "Learning information: lessons completed, progress against learning outcomes, achievements, reading log and word hoard entries.",
        "Evidence a parent uploads, such as photos or work samples, which may show a child or their work.",
      ] },
      { h: "Children's information", p: "Child profiles are created and managed by a parent or guardian, who is responsible for the information entered. Children do not sign up with an email address. They sign in with the username and PIN their parent sets. The child area has no advertising, no public profiles and no open messaging. I encourage parents to use first names or nicknames only, to choose a PIN that is not used elsewhere, and to avoid uploading images or details that are not needed for learning." },
      { h: "Technical information", p: "When you use Side Quest, Cloudflare, the hosting provider, may automatically record technical data such as IP address, browser and device type, pages requested, error logs and the time of requests. This is used to keep the service running, secure and fast, and to fix problems." },
      { h: "How I collect information", items: [
        "Directly from you when you create an account, add a child, upload evidence or contact me.",
        "From your child's activity in the child area, such as completing a lesson or asking for help with their PIN.",
        "Automatically through the hosting systems.",
      ] },
      { h: "Why I use information", items: [
        "To create and run your account and your children's learning spaces.",
        "To show progress, build learning plans and keep records you can use for home education reporting.",
        "To provide features such as lessons, the reading log, life learning records and rewards.",
        "To help you and your children get back into their accounts if a password or PIN is forgotten.",
        "To provide help and support, and to respond to requests and complaints.",
        "To keep Side Quest secure, prevent misuse and fix faults.",
        "To meet my legal obligations.",
      ] },
      { h: "I do not sell your information", p: "I do not sell or rent personal information, and I do not use children's information for advertising or marketing profiles. I will not use your information for an unrelated purpose unless you consent or the law allows it." },
      { h: "AI features", p: "Some features use AI to give short hints, suggest links between activities and learning outcomes, or draft lesson ideas. These run on Cloudflare's platform. I aim to send only the text needed for the task and to leave out names and other identifying details. AI output is a suggestion only and a parent reviews it. See the AI Use page for more." },
      { h: "Who I share information with", p: "I share information only with service providers who help run Side Quest, and only as needed for them to do that work." },
      { h: "Service providers", items: [
        "Cloudflare: hosting, network security, the database, file storage, AI features and the email routing for the support address.",
        "Google (Gmail): emails you send to support@sidequestlearning.app are forwarded by Cloudflare to a Gmail inbox that is used only for Side Quest.",
        "I do not use third-party advertising services or add separate analytics trackers.",
      ] },
      { h: "Other disclosures", p: "I may disclose information if required or authorised by law, to protect someone's safety, or to respond to a lawful request from a court or authority." },
      { h: "Overseas disclosure", p: "Cloudflare and Google operate global networks, so information may be stored or processed outside Australia, including in the United States and other countries. I choose providers that publish security and privacy commitments." },
      { h: "Cookies and similar technology", p: "I use cookies or similar browser storage only where needed to keep you signed in and keep the service secure. I do not use advertising cookies." },
      { h: "Storage and security", p: "I take reasonable steps to protect personal information from misuse, loss and unauthorised access. This includes encrypted connections (HTTPS), login protection for parent accounts and PIN protection for child access, restricting access to the site, and monitoring logs for problems. No online service is completely secure, so please use a strong, unique password and keep it private." },
      { h: "How long I keep information", items: [
        "I keep account and child information while your account is active.",
        "PIN requests are kept while the account is active, and are removed when the child's profile or the account is deleted.",
        "When you delete a child profile or your account, I delete the related information, except where I must keep something by law. The hosting provider may keep short-term backups for a limited time before they are removed.",
        "Technical and security logs are kept only for the short period the hosting provider retains them, then deleted.",
        "Emails you send me are kept as long as needed to deal with your request.",
      ] },
      { h: "Data breaches", p: "If a data breach is likely to cause serious harm, I will act quickly to contain it and will tell affected families, and the Office of the Australian Information Commissioner where required." },
      { h: "Accessing and correcting your information", p: "You can ask to see the personal information I hold about you and your children, and ask me to correct anything that is wrong, incomplete or out of date. You can also edit most details yourself in the parent hub. Use the Request Your Data and Request a Correction pages, or email support@sidequestlearning.app. I will confirm your identity first and aim to respond within 30 days. There is no charge for making a request." },
      { h: "Deleting your information", p: "You can delete your account at any time from the Trust & Support page or the sidebar. This removes your account and your children's profiles and learning records." },
      { h: "Complaints", p: "If you are unhappy with how your information has been handled, email support@sidequestlearning.app and I will look into it and reply in writing. You may also contact the Office of the Australian Information Commissioner at oaic.gov.au." },
      { h: "Changes to this policy", p: "I may update this policy as Side Quest grows or the law changes. The date at the top shows when it was last updated. If I make an important change I will let families know through the app or by email." },
      { h: "Contact", p: "Side Quest, support@sidequestlearning.app" },
    ],
  },
  "terms": {
    group: "legal", title: "Terms of Use", public: true,
    summary: "The agreement between you and Side Quest.",
    sections: [
      { h: "In short", items: [
        "Side Quest is a free, personal project built by a parent for home learning and shared with a small circle of homeschooling families.",
        "You are responsible for your account, your children's use of it, and what you upload.",
        "Be kind, be safe, and do not misuse the service.",
        "I do my best to keep it running, but it is provided as is, so keep your own copies of anything important.",
      ] },
      { h: "Agreeing to these terms", p: "By creating an account or using Side Quest you agree to these terms and to the Privacy Policy. If you do not agree, please do not use the service. In these terms, \"Side Quest\", \"I\", \"me\" and \"my\" mean the parent who runs sidequestlearning.app as a personal project in Australia. It is not a registered business or company." },
      { h: "What Side Quest is", p: "Side Quest is a home learning hub. Parents can plan lessons, track progress, record life learning, log reading and give children their own area with lessons, rewards and a learning pet. It is a planning and record-keeping tool only. See the Educational Disclaimer for what it is not." },
      { h: "Who can use Side Quest", p: "Accounts are for parents and guardians aged 18 or over. Children may use their own area only under the supervision of the parent or guardian who created their profile. Side Quest is shared with a small circle of homeschooling families, and I may decline or remove access at any time." },
      { h: "Your account", items: [
        "Give accurate information and keep it up to date.",
        "Keep your password private and choose a strong, unique one.",
        "You are responsible for activity on your account, including children signing in with the username and PIN you set for them.",
        "Tell me promptly at support@sidequestlearning.app if you think someone has accessed your account without permission.",
        "Do not share your account with other families. Each family should have its own account.",
      ] },
      { h: "Children and supervision", p: "You are responsible for supervising your children's use of Side Quest and for deciding what is suitable for them. Check any AI-generated or saved content before your child relies on it. Use first names or nicknames and choose a PIN that is not used elsewhere." },
      { h: "Your content", p: "Your content includes the plans, notes, photos, work samples and other material you add. You own it. You give me permission to store, process and display it to you and your family so the service works, and nothing more. I do not use your content for advertising, and I do not publish it." },
      { h: "What you must not upload", items: [
        "Anything unlawful, harmful, abusive or sexual.",
        "Photos or details of other people's children without their parent's permission.",
        "Content you do not have the right to share, including copyrighted material you do not own or have permission to use.",
        "Sensitive information that is not needed for learning, such as health records, government ID numbers or full home addresses.",
      ] },
      { h: "Acceptable use", items: [
        "Do not try to break, probe, overload or gain unauthorised access to the service or other families' data.",
        "Do not use bots, scrapers or automated tools without my permission.",
        "Do not reverse engineer, copy or resell the service.",
        "Do not use Side Quest to harass or harm anyone.",
      ] },
      { h: "AI features", p: "Some features use AI to suggest hints, outcome links and lesson ideas. AI can be wrong. Suggestions are for you to review and are not advice, a grade or an official assessment. Please do not enter more personal information into AI features than is needed. See the AI Use page for details." },
      { h: "Learning content and curriculum", p: "Lessons, learning outcomes and mappings are provided as a guide. I do not guarantee they are complete, current or accepted by any education authority. You are responsible for meeting the home education requirements that apply to your family. See the Educational Disclaimer." },
      { h: "Free service", p: "Side Quest is currently free. If that ever changes, I will tell you first and you will not be charged without agreeing to it." },
      { h: "Availability, changes and backups", p: "I aim to keep Side Quest running, but it is run by one person, so I cannot promise it will always be available, error free or kept forever. I may change, pause or remove features, or close the service, with notice where I reasonably can. Please keep your own copies of anything important, such as photos and records you need for reporting." },
      { h: "Suspending or ending access", p: "You can stop using Side Quest and delete your account at any time from the Trust & Support page. I may suspend or end an account if these terms are breached, if it puts others at risk, or if I close the service. When an account is deleted, its data is removed as described in the Privacy Policy." },
      { h: "Intellectual property", p: "The Side Quest name, design, code, artwork and original lesson content belong to me or are used with permission. You may use them through the service for your own family's learning, but not copy or redistribute them. Other resources you link to or save remain the property of their owners." },
      { h: "Third-party services", p: "Side Quest relies on providers such as Cloudflare and may link to outside websites and resources. I am not responsible for those, and their own terms apply. See the Third-Party Services page." },
      { h: "Limits on my responsibility", p: "Side Quest is provided as is. To the extent the law allows, I am not liable for loss or damage arising from your use of the service, including lost data, interruptions, inaccurate content, or decisions you make based on it. Nothing in these terms excludes or limits any right or remedy that you have under the Australian Consumer Law or other law that cannot be excluded." },
      { h: "Changes to these terms", p: "I may update these terms from time to time. The date at the top shows the latest version. If I make an important change I will let you know through the app or by email. Continuing to use Side Quest after a change means you accept it." },
      { h: "Governing law", p: "These terms are governed by the laws of Australia. If any part is found unenforceable, the rest still applies." },
      { h: "Contact", p: "Side Quest, support@sidequestlearning.app" },
    ],
  },
  "disclaimer": {
    group: "legal", title: "Educational Disclaimer", public: true,
    summary: "Side Quest supports home learning. It does not replace your responsibilities.",
    sections: [
      { h: "In short", items: [
        "Side Quest is a planning and record-keeping tool for home educating families.",
        "It is not a school, a teacher, a curriculum provider or an education authority.",
        "You remain responsible for your child's education and for meeting the requirements that apply where you live.",
        "Always check anything important, including outcome links, against official sources.",
      ] },
      { h: "What Side Quest is", p: "Side Quest helps parents plan lessons, record learning, track progress and give children a motivating space to work in. It supports your teaching. It does not replace it." },
      { h: "What Side Quest is not", items: [
        "A registered school, teacher or accredited education provider.",
        "An approving body, regulator or assessment authority.",
        "A source of official curriculum, legal, regulatory or professional advice.",
      ] },
      { h: "Home education requirements", p: "Side Quest is currently built around the New South Wales curriculum. In NSW, home education is registered and overseen by the NSW Education Standards Authority (NESA). Requirements in other states and territories differ. Side Quest does not know your family's circumstances and does not guarantee that anything it produces will be accepted by NESA or any other regulator. Check the current requirements with the relevant authority and keep whatever records they ask for." },
      { h: "Curriculum and learning outcomes", p: "Side Quest currently links activities to NSW curriculum outcomes. Those links are a guide to help you plan and record. They may be incomplete, simplified or out of date, and they are not an official statement of what a child has achieved. Side Quest is not affiliated with or endorsed by NESA or the NSW Department of Education. Check outcomes against the official NSW syllabus documents before using them for reporting. Families outside NSW should not assume the outcomes match their own state's curriculum." },
      { h: "Progress, rewards and assessment", p: "Progress bars, achievements, points and pet rewards are there to motivate children and give you a snapshot. They are not formal assessments, grades or measures of ability, and should not be used as the only evidence of how your child is going. You know your child best." },
      { h: "AI-generated content", p: "Hints, suggestions and draft lessons created with AI may contain mistakes, gaps or unsuitable ideas. A parent should review them before use. AI does not judge your child's work or make educational decisions. See the AI Use page for more." },
      { h: "No guarantee of results", p: "I cannot promise that using Side Quest will improve your child's learning, results or progress, or lead to any particular outcome. Every child learns differently." },
      { h: "Not professional advice", p: "Side Quest does not give advice about learning difficulties, disability, health, wellbeing or development. If you have concerns about your child, speak to a qualified professional such as a doctor, psychologist or specialist educator." },
      { h: "Safety during activities", p: "Some lessons or activities may involve hands-on, outdoor or online tasks. Parents and guardians are responsible for supervising children and for judging whether an activity is safe and suitable for their child, including any equipment, materials or websites involved." },
      { h: "Other resources and links", p: "Side Quest may link to books, videos, websites and other resources made by others. I do not control or endorse them and cannot guarantee that they are accurate, appropriate or still available. Preview anything before sharing it with your child." },
      { h: "Parent supervision", p: "Parents and guardians remain responsible for supervising children, reviewing any content, and deciding what is right for their family." },
      { h: "Changes and corrections", p: "Side Quest is a small personal project and its content changes over time. If you spot something wrong or out of date, please tell me through Report a Problem so I can fix it." },
      { h: "Contact", p: "Side Quest, support@sidequestlearning.app" },
    ],
  },
  "ai-use": {
    group: "legal", title: "AI Use & Limitations", public: true,
    summary: "Where AI helps, where it doesn't, and why a parent always stays in charge.",
    sections: [
      { h: "In short", items: [
        "AI in Side Quest is a helper for parents and a gentle nudge for children. It is never the teacher.",
        "AI can be wrong, so a parent reviews anything that matters.",
        "AI does not grade, assess or make decisions about your child.",
        "I aim to send AI only what it needs for the task, without names or identifying details.",
        "There is no AI on/off setting, but AI features only run when someone uses them, so you can simply choose not to.",
      ] },
      { h: "Where AI is used", items: [
        "Pet hints: when a child is stuck during a lesson, their learning pet can offer a short, encouraging nudge in the right direction.",
        "Lesson building: when the ready-made lessons aren't a good fit, a parent can ask AI to draft a lesson to suit their child. The parent reviews and edits it before it is used.",
        "Outcome links: AI may suggest which NSW curriculum outcomes a lesson or life-learning activity could relate to, to save you time recording learning.",
      ] },
      { h: "How pet hints work", p: "Pet hints are designed to guide, not to hand over the answer. A hint appears only when a child asks for help or gets stuck. It is a short prompt based on the question the child is working on. Hints are generated automatically, so a parent isn't reviewing each one as it appears. Because of this, I recommend sitting with younger children and checking in on how hints are going. If a hint is wrong, confusing or unsuitable, please tell me through Report a Problem." },
      { h: "How lesson building works", p: "When you ask AI to build a lesson, it drafts content from the topic, year level and details you provide. Nothing is added to your child's area until a parent has seen it and chosen to use it. You are the editor. Check facts, difficulty, wording and suitability for your child, and change or discard anything that isn't right." },
      { h: "What AI does not do", items: [
        "It does not grade, mark or assess your child's work or ability.",
        "It does not decide what your child learns, or change their plan without a parent.",
        "It does not chat openly with children. Hints are limited to the lesson task.",
        "It does not give advice about learning difficulties, health or wellbeing.",
        "It does not publish anything or share it with other families.",
      ] },
      { h: "Accuracy and limits", p: "AI can make mistakes. It can state wrong facts with confidence, misunderstand a question, give a hint that is too easy or too hard, or suggest an outcome that doesn't really match. It may also reflect bias or gaps in the material it learned from. Treat everything it produces as a draft or a suggestion, and check anything important, especially facts and curriculum outcome links, against reliable sources. See the Educational Disclaimer for how outcome links should be used." },
      { h: "Safety measures", p: "I keep AI use narrow and tied to learning tasks. Children don't have an open chat with AI, and AI features are not used for advertising or to build profiles of children. Despite my care, AI may occasionally produce something unexpected or unsuitable. Parents should supervise, especially with younger children. If you see anything concerning, stop using the feature and report it to me straight away." },
      { h: "What data is sent to AI", p: "AI features run on Cloudflare's platform. I aim to send only the minimum text needed for a task, such as the lesson question for a hint or the topic and year level for a lesson draft, and to leave out names and other identifying details. Photos and work samples are not sent to AI. Please avoid typing names, addresses or other personal details into any box that is sent to AI, such as lesson-building requests." },
      { h: "How AI data is handled", p: "I do not use your family's information to advertise to you or to build marketing profiles, and I do not sell it. The AI provider processes requests to produce a response, and its handling of data is covered by its own terms. See the Third-Party Services page and the Privacy Policy. Because Cloudflare operates globally, processing may take place outside Australia." },
      { h: "Your choices", items: [
        "There is currently no setting to switch AI off. AI features only run when someone chooses to use them, such as asking the pet for a hint or asking for a lesson to be built.",
        "If you and your children don't use those features, they aren't triggered. Side Quest works fully with the ready-made lessons and your own plans.",
        "Let your children know they don't have to ask for hints, and tell them to come to you if something seems off.",
        "Review and edit anything AI drafts before your child sees it, and delete AI-drafted lessons or outcome links you don't want.",
        "Tell me if something isn't right using Report a Problem.",
      ] },
      { h: "Changes to AI features", p: "AI tools change quickly. I may add, change or remove AI features, or switch the technology behind them, as Side Quest grows. If a change affects how information is used, I will update this page and the Privacy Policy." },
      { h: "Contact", p: "Questions or concerns about AI in Side Quest? Email support@sidequestlearning.app." },
    ],
  },
  "contact": {
    group: "support", title: "Contact Us", contact: "general",
    summary: "Send a message to base camp. A real person is on the other end.",
    sections: [
      { h: "Hello from base camp", p: "Side Quest is made by one parent who is also homeschooling, usually somewhere between a maths lesson and a snack break. Anything you send goes straight to the Side Quest inbox and I read every message myself." },
      { h: "Send a message", p: "Email support@sidequestlearning.app. Questions, ideas, bugs, a lesson you wish existed, a quest that went sideways: all welcome." },
      { h: "How long will I wait?", p: "I'll reply as soon as I can, usually within a few days. It might take a little longer when it's busy at home or during school holidays. If something is urgent, email isn't the fastest route." },
      { h: "Good things to send", items: [
        "Questions about how something works.",
        "Ideas for new lessons, pets or features.",
        "Something that's broken or confusing.",
        "Trouble signing in or a missing child profile.",
      ] },
      { h: "Make it a quick quest", items: [
        "Email from the address on your Side Quest account so I can find you.",
        "Tell me what you were trying to do and what happened.",
        "Let me know your device and browser if something isn't working.",
        "Use your child's first name or nickname only.",
      ] },
      { h: "Pack light", p: "Please don't email passwords, your child's PIN, home addresses, ID numbers, health details or photos of children. I will never ask you for a password or PIN. If someone claiming to be Side Quest does, don't share it and let me know." },
      { h: "Grown-ups only, please", p: "This inbox is for parents and guardians. If your child has a question or a great idea, they can tell you and you can send it along. I'd love to hear it." },
      { h: "For real emergencies", p: "I can't respond to emergencies. If someone is in danger, call 000. If something in Side Quest worries you, stop using it and let me know." },
      { h: "Other paths", p: "For data, correction, complaint or account deletion requests, the Account & privacy requests pages will get you there fastest." },
    ],
  },
  "help": {
    group: "support", title: "Help & FAQ",
    summary: "Your quest guide: quick answers for parents, and a few for adventurers.",
    sections: [
      { h: "Welcome, adventurer", p: "Side Quest turns home learning into a quest: lessons to complete, a learning pet to look after, and a place for you to keep track of it all. Here are the answers to the questions I get asked most. If yours isn't here, send it to base camp on the Contact Us page." },
      { h: "Setting up camp", items: [
        "Add a child: go to Children in the sidebar and choose to add a new child profile. You can use a first name or nickname.",
        "Choose a username and PIN for them. Pick a PIN that isn't used anywhere else. You can change it later from the parent dashboard.",
        "Children sign in on the child login page with that username and PIN. They don't need an email address.",
        "Each family gets its own account. Please don't share one account between families.",
      ] },
      { h: "What's a learning pet?", p: "Each child has a pet that goes along on the quest. Your child can pick their pet and avatar, and the pet is there to cheer them on. If your child gets stuck during a lesson, their pet can offer a short nudge in the right direction." },
      { h: "What if my child is stuck?", p: "The pet gives a hint, not the answer. Hints are made with AI, so they're not checked by a person as they appear, and they can occasionally be off. If you can, sit with younger children, and tell me if a hint ever seems wrong or confusing. You can read more on the AI Use & Limitations page." },
      { h: "The ready-made lessons don't suit my child", p: "You can ask Side Quest to help draft a lesson to suit your child instead. It's a first draft only. Nothing goes into your child's area until you've read it and chosen to use it, and you can change anything that isn't right." },
      { h: "Where do I see how they're going?", p: "The Dashboard and each child's overview show progress, evidence and reading. Progress bars, achievements and pet rewards are there to keep things fun and give you a snapshot. They're not grades or formal assessments." },
      { h: "Reading log, word hoard and life learning", items: [
        "Reading log: keep track of what your child has been reading.",
        "Word hoard: collect new and interesting words along the way.",
        "Life learning: record the learning that happens outside of lessons, like cooking, building, or a trip to the park.",
        "Evidence: you can upload photos or work samples. Please only upload what you need, and avoid anything with other people's children in it.",
      ] },
      { h: "What are curriculum outcomes?", p: "Side Quest is currently built around the NSW curriculum, and it links activities to NSW outcomes to help you plan and record. Some of those links are suggested with AI, so they're a guide only. Please check them against the official NSW syllabus before you use them for reporting, and check the requirements with the relevant authority." },
      { h: "Is it safe for my child?", p: "Children only reach their own area, which you set up and manage. There are no ads, no public profiles, and no messaging between users. Read more on the Safety Overview page. You're still the one in charge, so keep an eye on how they're getting on." },
      { h: "Can I use it if I'm outside NSW?", p: "You can, but the outcomes and requirements are for NSW, and other states and territories differ. Treat the outcome links as a general guide, not as your state's curriculum." },
      { h: "Something's broken", p: "Tell me through Report a Problem. What you were trying to do, what you expected, what happened, and the device or browser you used all help me find it quickly." },
      { h: "I forgot my password", p: "On the main sign-in page, choose \"Forgot password?\" and follow the steps. If it doesn't work for you, email me at support@sidequestlearning.app from the address on your account and I'll help. I'll never ask for your password or your child's PIN." },
      { h: "My child forgot their PIN", p: "On the child sign-in page, your child can choose \"Forgot my PIN\". This sends a prompt to your parent dashboard. Open the \"View\" area to see the details and set a new PIN for them. Pick one that isn't used anywhere else, and let your child know. The request only goes to you, and children can't use it to message anyone else." },
      { h: "Your information", items: [
        "Want a copy of what's held about your family? Use Request Your Data.",
        "Something wrong or out of date that you can't edit yourself? Use Request a Correction.",
        "Want to leave? Use Delete account from the Account & privacy requests page or the sidebar. It removes your account, your children's profiles and their learning records.",
      ] },
      { h: "Is Side Quest free?", p: "Yes, it's free right now. If that ever changes, I'll tell you first. It's a small project run by one parent, so keep your own copies of anything important, like photos and records you need for reporting." },
      { h: "Still stuck?", p: "Head to the Contact Us page and send a message to base camp. I read every one." },
    ],
  },
  "report-problem": {
    group: "support", title: "Report a Problem", contact: "problem",
    summary: "Something broken or not right? Tell me.",
    sections: [
      { h: "What to include", p: "What you were doing, what you expected, what happened, and the device or browser you used. Please do not include children's full names or sensitive details." },
    ],
  },
  "request-access": {
    group: "privacy", title: "Request Your Data", contact: "access",
    summary: "Ask for a copy of the information I hold about your family.",
    sections: [
      { h: "How it works", p: "Send a request from your account email. I will confirm your identity and aim to respond within 30 days." },
    ],
  },
  "request-correction": {
    group: "privacy", title: "Request a Correction", contact: "correction",
    summary: "Tell me if something I hold is wrong or out of date.",
    sections: [
      { h: "Quick fixes", p: "You can edit most details yourself in Children and your account. Use this request for anything you can't change directly." },
    ],
  },
  "privacy-complaint": {
    group: "privacy", title: "Privacy Complaint", contact: "complaint",
    summary: "Concerned about how your information was handled?",
    sections: [
      { h: "Contact me first", p: "Tell me what happened and I will investigate and reply in writing." },
      { h: "Still not resolved?", p: "You may also contact the Office of the Australian Information Commissioner at oaic.gov.au." },
    ],
  },
  "data-handling": {
    group: "trust", title: "How I Handle Data", public: true,
    summary: "The short version of how your family's information is treated.",
    sections: [
      { h: "Minimal by design", p: "I collect what the learning features need and no more." },
      { h: "Parent controlled", p: "Parents create child profiles and can delete them or the whole account." },
      { h: "No ads, no selling", p: "I do not sell personal information, and there is no advertising for children." },
      { h: "Security", p: "Data is transmitted over HTTPS, hosted on Cloudflare, and access is protected by parent login and child PINs." },
    ],
  },
  "third-parties": {
    group: "trust", title: "Third-Party Services", public: true,
    summary: "The providers that help run Side Quest.",
    sections: [
      { h: "Hosting & infrastructure", p: "Cloudflare provides hosting, the database, file storage, AI features and security." },
      { h: "Email", p: "Cloudflare Email Routing forwards messages sent to support@sidequestlearning.app to a Gmail inbox (Google) used only for Side Quest." },
      { h: "Advertising and analytics", p: "I do not use advertising services or add separate analytics trackers." },
    ],
  },
  "safety": {
    group: "trust", title: "Safety Overview", public: true,
    summary: "How Side Quest is kept a safe space for children.",
    sections: [
      { h: "Parent in charge", p: "Children can only reach content within their own profile, set up and managed by a parent. They sign in with a username and PIN, not an email address." },
      { h: "No open chat", p: "Side Quest has no public profiles and no messaging between users." },
      { h: "PIN requests", p: "If a child forgets their PIN, they can send a prompt to their own parent's dashboard. It only reaches the parent who set up their profile. It is not a message between users, it carries no typed text from the child, and it does not let children contact anyone else. The parent decides whether to set a new PIN." },
      { h: "Reporting", p: "If something concerns you, use Report a Problem and I will look into it promptly." },
    ],
  },
};
