// DRAFT COPY - review before launch.
export const CONTACT_EMAIL = "support@sidequestlearning.app";
export const PRIVACY_EMAIL = "support@sidequestlearning.app";
export const LAST_UPDATED = "11 October 2026";

export const GROUPS = [
  { id: "legal", title: "Legal", blurb: "The rules and the fine print, in plain language." },
  { id: "support", title: "Support", blurb: "Help when you need a hand." },
  { id: "privacy", title: "Account & privacy requests", blurb: "You are in control of your family's information." },
  { id: "trust", title: "Trust", blurb: "How Side Quest looks after your family's data." },
];

export const PAGES = {
  "privacy-policy": {
    group: "legal", title: "Privacy Policy", public: true,
    summary: "What I collect, why, who sees it, how long I keep it, and your rights.",
    sections: [
      { h: "In short", items: [
        "Side Quest is a home learning hub built by a parent for their own children, and shared with other families.",
        "I collect only what is needed to run your family's account and learning features.",
        "I do not sell personal information and there is no advertising for children.",
        "You can see, correct or delete your family's information at any time.",
      ] },
      { h: "Who I am", p: "Side Quest (sidequestlearning.app) is a personal project run by one parent in Australia, who is also homeschooling. It began as a tool for my own children and is not a registered business or company. In this policy, \"Side Quest\", \"I\", \"me\" and \"my\" mean the parent who runs sidequestlearning.app. You can contact me at support@sidequestlearning.app." },
      { h: "About this policy", p: "I handle personal information in line with the spirit of the Privacy Act 1988 (Cth) and the Australian Privacy Principles, even where the law may not strictly require it of a personal project. This policy applies to the Side Quest website and app, including the parent hub and the child area." },
      { h: "Information I collect from parents", items: [
        "Account details: your name, your email address and your sign-in credentials. Your email address is also used to help you get back into your account if you forget your password.",
        "Settings and preferences you choose in the parent hub.",
        "Records you create: lesson plans, learning plans, calendar entries, resources you save and notes.",
        "Messages you send me by email or through the contact and request pages.",
      ] },
      { h: "Information I collect about children", items: [
        "Profile details a parent enters: first name or nickname, year level and avatar or pet choices.",
        "A username and PIN code set up by the parent so the child can enter their own area.",
        "PIN requests: if a child forgets their PIN and asks for help, a request is recorded with the time and the child's profile, and shown to their parent on the parent dashboard.",
        "Learning information: lessons completed, progress against learning outcomes, achievements, reading log and word hoard entries.",
        "Evidence a parent uploads, such as photos or work samples, which may show a child or their work.",
      ] },
      { h: "Children's information", p: "Child profiles are created and managed by a parent or guardian, who is responsible for the information entered. Children do not sign up with an email address. They sign in with the username and PIN their parent sets. The child area has no advertising, no public profiles and no open messaging. I encourage parents to use first names or nicknames only, to choose a PIN that is not used elsewhere, and to avoid uploading images or details that are not needed for learning." },
      { h: "Technical information", p: "When you use Side Quest, Cloudflare, the hosting provider, may automatically record technical data such as IP address, browser and device type, pages requested, error logs and the time of requests. This is used to keep the service running, secure and fast, and to fix problems." },
      { h: "How I collect information", items: [
        "Directly from you when you create an account, add a child, upload evidence or contact me.",
        "From your child's activity in the child area, such as completing a lesson or asking for help with their PIN.",
        "Automatically through the hosting systems.",
      ] },
      { h: "Why I use information", items: [
        "To create and run your account and your children's learning spaces.",
        "To show progress, build learning plans and keep records you can use for home education reporting.",
        "To provide features such as lessons, the reading log, life learning records and rewards.",
        "To help you and your children get back into their accounts if a password or PIN is forgotten.",
        "To provide help and support, and to respond to requests and complaints.",
        "To keep Side Quest secure, prevent misuse and fix faults.",
        "To meet my legal obligations.",
      ] },
      { h: "I do not sell your information", p: "I do not sell or rent personal information, and I do not use children's information for advertising or marketing profiles. I will not use your information for an unrelated purpose unless you consent or the law allows it." },
      { h: "AI features", p: "Some features use AI to give short hints, suggest links between activities and learning outcomes, or draft lesson ideas. These run on Cloudflare's platform. I aim to send only the text needed for the task and to leave out names and other identifying details. AI output is a suggestion only and a parent reviews it. See the AI Use page for more." },
      { h: "Who I share information with", p: "I share information only with service providers who help run Side Quest, and only as needed for them to do that work." },
      { h: "Service providers", items: [
        "Cloudflare: hosting, network security, the database, file storage, AI features and the email routing for the support address.",
        "Google (Gmail): emails you send to support@sidequestlearning.app are forwarded by Cloudflare to a Gmail inbox that is used only for Side Quest.",
        "I do not use third-party advertising services or add separate analytics trackers.",
      ] },
      { h: "Other disclosures", p: "I may disclose information if required or authorised by law, to protect someone's safety, or to respond to a lawful request from a court or authority." },
      { h: "Overseas disclosure", p: "Cloudflare and Google operate global networks, so information may be stored or processed outside Australia, including in the United States and other countries. I choose providers that publish security and privacy commitments." },
      { h: "Cookies and similar technology", p: "I use cookies or similar browser storage only where needed to keep you signed in and keep the service secure. I do not use advertising cookies." },
      { h: "Storage and security", p: "I take reasonable steps to protect personal information from misuse, loss and unauthorised access. This includes encrypted connections (HTTPS), login protection for parent accounts and PIN protection for child access, restricting access to the site, and monitoring logs for problems. No online service is completely secure, so please use a strong, unique password and keep it private." },
      { h: "How long I keep information", items: [
        "I keep account and child information while your account is active.",
        "PIN requests are kept while the account is active, and are removed when the child's profile or the account is deleted.",
        "When you delete a child profile or your account, I delete the related information, except where I must keep something by law. The hosting provider may keep short-term backups for a limited time before they are removed.",
        "Technical and security logs are kept only for the short period the hosting provider retains them, then deleted.",
        "Emails you send me are kept as long as needed to deal with your request.",
      ] },
      { h: "Data breaches", p: "If a data breach is likely to cause serious harm, I will act quickly to contain it and will tell affected families, and the Office of the Australian Information Commissioner where required." },
      { h: "Accessing and correcting your information", p: "You can ask to see the personal information I hold about you and your children, and ask me to correct anything that is wrong, incomplete or out of date. You can also edit most details yourself in the parent hub. To see your information, use the Request Your Data page. To correct it, email support@sidequestlearning.app with \"Correct my information\" in the subject line. I will confirm your identity first and aim to respond within 30 days. There is no charge for making a request." },
      { h: "Deleting your information", p: "You can delete your account at any time from the Trust & Support page or the sidebar. This removes your account and your children's profiles and learning records." },
      { h: "Complaints", p: "If you are unhappy with how your information has been handled, use the Privacy Complaint page or email support@sidequestlearning.app and I will look into it and reply in writing. You may also contact the Office of the Australian Information Commissioner at oaic.gov.au." },
      { h: "Changes to this policy", p: "I may update this policy as Side Quest grows or the law changes. The date at the top shows when it was last updated. If I make an important change I will let families know through the app or by email." },
      { h: "Contact", p: "Side Quest, support@sidequestlearning.app" },
    ],
  },
  "terms": {
    group: "legal", title: "Terms of Use", public: true,
    summary: "The agreement between you and Side Quest.",
    sections: [
      { h: "In short", items: [
        "Side Quest is a free, personal project built by a parent for home learning and shared with a small circle of homeschooling families.",
        "You are responsible for your account, your children's use of it, and what you upload.",
        "Be kind, be safe, and do not misuse the service.",
        "I do my best to keep it running, but it is provided as is, so keep your own copies of anything important.",
      ] },
      { h: "Agreeing to these terms", p: "By creating an account or using Side Quest you agree to these terms and to the Privacy Policy. If you do not agree, please do not use the service. In these terms, \"Side Quest\", \"I\", \"me\" and \"my\" mean the parent who runs sidequestlearning.app as a personal project in Australia. It is not a registered business or company." },
      { h: "What Side Quest is", p: "Side Quest is a home learning hub. Parents can plan lessons, track progress, record life learning, log reading and give children their own area with lessons, rewards and a learning pet. It is a planning and record-keeping tool only. See the Educational Disclaimer for what it is not." },
      { h: "Who can use Side Quest", p: "Accounts are for parents and guardians aged 18 or over. Children may use their own area only under the supervision of the parent or guardian who created their profile. Side Quest is shared with a small circle of homeschooling families, and I may decline or remove access at any time." },
      { h: "Your account", items: [
        "Give accurate information and keep it up to date.",
        "Keep your password private and choose a strong, unique one.",
        "You are responsible for activity on your account, including children signing in with the username and PIN you set for them.",
        "Tell me promptly at support@sidequestlearning.app if you think someone has accessed your account without permission.",
        "Do not share your account with other families. Each family should have its own account.",
      ] },
      { h: "Children and supervision", p: "You are responsible for supervising your children's use of Side Quest and for deciding what is suitable for them. Check any AI-generated or saved content before your child relies on it. Use first names or nicknames and choose a PIN that is not used elsewhere." },
      { h: "Your content", p: "Your content includes the plans, notes, photos, work samples and other material you add. You own it. You give me permission to store, process and display it to you and your family so the service works, and nothing more. I do not use your content for advertising, and I do not publish it." },
      { h: "What you must not upload", items: [
        "Anything unlawful, harmful, abusive or sexual.",
        "Photos or details of other people's children without their parent's permission.",
        "Content you do not have the right to share, including copyrighted material you do not own or have permission to use.",
        "Sensitive information that is not needed for learning, such as health records, government ID numbers or full home addresses.",
      ] },
      { h: "Acceptable use", items: [
        "Do not try to break, probe, overload or gain unauthorised access to the service or other families' data.",
        "Do not use bots, scrapers or automated tools without my permission.",
        "Do not reverse engineer, copy or resell the service.",
        "Do not use Side Quest to harass or harm anyone.",
      ] },
      { h: "AI features", p: "Some features use AI to suggest hints, outcome links and lesson ideas. AI can be wrong. Suggestions are for you to review and are not advice, a grade or an official assessment. Please do not enter more personal information into AI features than is needed. See the AI Use page for details." },
      { h: "Learning content and curriculum", p: "Lessons, learning outcomes and mappings are provided as a guide. I do not guarantee they are complete, current or accepted by any education authority. You are responsible for meeting the home education requirements that apply to your family. See the Educational Disclaimer." },
      { h: "Free service", p: "Side Quest is currently free. If that ever changes, I will tell you first and you will not be charged without agreeing to it." },
      { h: "Availability, changes and backups", p: "I aim to keep Side Quest running, but it is run by one person, so I cannot promise it will always be available, error free or kept forever. I may change, pause or remove features, or close the service, with notice where I reasonably can. Please keep your own copies of anything important, such as photos and records you need for reporting." },
      { h: "Suspending or ending access", p: "You can stop using Side Quest and delete your account at any time from the Trust & Support page. I may suspend or end an account if these terms are breached, if it puts others at risk, or if I close the service. When an account is deleted, its data is removed as described in the Privacy Policy." },
      { h: "Intellectual property", p: "The Side Quest name, design, code, artwork and original lesson content belong to me or are used with permission. You may use them through the service for your own family's learning, but not copy or redistribute them. Other resources you link to or save remain the property of their owners." },
      { h: "Third-party services", p: "Side Quest relies on providers such as Cloudflare and may link to outside websites and resources. I am not responsible for those, and their own terms apply. See the Third-Party Services page." },
      { h: "Limits on my responsibility", p: "Side Quest is provided as is. To the extent the law allows, I am not liable for loss or damage arising from your use of the service, including lost data, interruptions, inaccurate content, or decisions you make based on it. Nothing in these terms excludes or limits any right or remedy that you have under the Australian Consumer Law or other law that cannot be excluded." },
      { h: "Changes to these terms", p: "I may update these terms from time to time. The date at the top shows the latest version. If I make an important change I will let you know through the app or by email. Continuing to use Side Quest after a change means you accept it." },
      { h: "Governing law", p: "These terms are governed by the laws of Australia. If any part is found unenforceable, the rest still applies." },
      { h: "Contact", p: "Side Quest, support@sidequestlearning.app" },
    ],
  },
  "disclaimer": {
    group: "legal", title: "Educational Disclaimer", public: true,
    summary: "Side Quest supports home learning. It does not replace your responsibilities.",
    sections: [
      { h: "In short", items: [
        "Side Quest is a planning and record-keeping tool for home educating families.",
        "It is not a school, a teacher, a curriculum provider or an education authority.",
        "You remain responsible for your child's education and for meeting the requirements that apply where you live.",
        "Always check anything important, including outcome links, against official sources.",
      ] },
      { h: "What Side Quest is", p: "Side Quest helps parents plan lessons, record learning, track progress and give children a motivating space to work in. It supports your teaching. It does not replace it." },
      { h: "What Side Quest is not", items: [
        "A registered school, teacher or accredited education provider.",
        "An approving body, regulator or assessment authority.",
        "A source of official curriculum, legal, regulatory or professional advice.",
      ] },
      { h: "Home education requirements", p: "Side Quest is currently built around the New South Wales curriculum. In NSW, home education is registered and overseen by the NSW Education Standards Authority (NESA). Requirements in other states and territories differ. Side Quest does not know your family's circumstances and does not guarantee that anything it produces will be accepted by NESA or any other regulator. Check the current requirements with the relevant authority and keep whatever records they ask for." },
      { h: "Curriculum and learning outcomes", p: "Side Quest currently links activities to NSW curriculum outcomes. Those links are a guide to help you plan and record. They may be incomplete, simplified or out of date, and they are not an official statement of what a child has achieved. Side Quest is not affiliated with or endorsed by NESA or the NSW Department of Education. Check outcomes against the official NSW syllabus documents before using them for reporting. Families outside NSW should not assume the outcomes match their own state's curriculum." },
      { h: "Progress, rewards and assessment", p: "Progress bars, achievements, points and pet rewards are there to motivate children and give you a snapshot. They are not formal assessments, grades or measures of ability, and should not be used as the only evidence of how your child is going. You know your child best." },
      { h: "AI-generated content", p: "Hints, suggestions and draft lessons created with AI may contain mistakes, gaps or unsuitable ideas. A parent should review them before use. AI does not judge your child's work or make educational decisions. See the AI Use page for more." },
      { h: "No guarantee of results", p: "I cannot promise that using Side Quest will improve your child's learning, results or progress, or lead to any particular outcome. Every child learns differently." },
      { h: "Not professional advice", p: "Side Quest does not give advice about learning difficulties, disability, health, wellbeing or development. If you have concerns about your child, speak to a qualified professional such as a doctor, psychologist or specialist educator." },
      { h: "Safety during activities", p: "Some lessons or activities may involve hands-on, outdoor or online tasks. Parents and guardians are responsible for supervising children and for judging whether an activity is safe and suitable for their child, including any equipment, materials or websites involved." },
      { h: "Other resources and links", p: "Side Quest may link to books, videos, websites and other resources made by others. I do not control or endorse them and cannot guarantee that they are accurate, appropriate or still available. Preview anything before sharing it with your child." },
      { h: "Parent supervision", p: "Parents and guardians remain responsible for supervising children, reviewing any content, and deciding what is right for their family." },
      { h: "Changes and corrections", p: "Side Quest is a small personal project and its content changes over time. If you spot something wrong or out of date, please tell me through Request a Correction so I can fix it." },
      { h: "Contact", p: "Side Quest, support@sidequestlearning.app" },
    ],
  },
  "ai-use": {
    group: "legal", title: "AI Use & Limitations", public: true,
    summary: "Where AI helps, where it doesn't, and why a parent always stays in charge.",
    sections: [
      { h: "In short", items: [
        "AI in Side Quest is a helper for parents and a gentle nudge for children. It is never the teacher.",
        "AI can be wrong, so a parent reviews anything that matters.",
        "AI does not grade, assess or make decisions about your child.",
        "I aim to send AI only what it needs for the task, without names or identifying details.",
        "There is no AI on/off setting, but AI features only run when someone uses them, so you can simply choose not to.",
      ] },
      { h: "Where AI is used", items: [
        "Pet hints: when a child is stuck during a lesson, their learning pet can offer a short, encouraging nudge in the right direction.",
        "Lesson building: when the ready-made lessons aren't a good fit, a parent can ask AI to draft a lesson to suit their child. The parent reviews and edits it before it is used.",
        "Outcome links: AI may suggest which NSW curriculum outcomes a lesson or life-learning activity could relate to, to save you time recording learning.",
      ] },
      { h: "How pet hints work", p: "Pet hints are designed to guide, not to hand over the answer. A hint appears only when a child asks for help or gets stuck. It is a short prompt based on the question the child is working on. Hints are generated automatically, so a parent isn't reviewing each one as it appears. Because of this, I recommend sitting with younger children and checking in on how hints are going. If a hint is wrong, confusing or unsuitable, please tell me through Report a Problem." },
      { h: "How lesson building works", p: "When you ask AI to build a lesson, it drafts content from the topic, year level and details you provide. Nothing is added to your child's area until a parent has seen it and chosen to use it. You are the editor. Check facts, difficulty, wording and suitability for your child, and change or discard anything that isn't right." },
      { h: "What AI does not do", items: [
        "It does not grade, mark or assess your child's work or ability.",
        "It does not decide what your child learns, or change their plan without a parent.",
        "It does not chat openly with children. Hints are limited to the lesson task.",
        "It does not give advice about learning difficulties, health or wellbeing.",
        "It does not publish anything or share it with other families.",
      ] },
      { h: "Accuracy and limits", p: "AI can make mistakes. It can state wrong facts with confidence, misunderstand a question, give a hint that is too easy or too hard, or suggest an outcome that doesn't really match. It may also reflect bias or gaps in the material it learned from. Treat everything it produces as a draft or a suggestion, and check anything important, especially facts and curriculum outcome links, against reliable sources. See the Educational Disclaimer for how outcome links should be used." },
      { h: "Safety measures", p: "I keep AI use narrow and tied to learning tasks. Children don't have an open chat with AI, and AI features are not used for advertising or to build profiles of children. Despite my care, AI may occasionally produce something unexpected or unsuitable. Parents should supervise, especially with younger children. If you see anything concerning, stop using the feature and report it to me straight away." },
      { h: "What data is sent to AI", p: "AI features run on Cloudflare's platform. I aim to send only the minimum text needed for a task, such as the lesson question for a hint or the topic and year level for a lesson draft, and to leave out names and other identifying details. Photos and work samples are not sent to AI. Please avoid typing names, addresses or other personal details into any box that is sent to AI, such as lesson-building requests." },
      { h: "How AI data is handled", p: "I do not use your family's information to advertise to you or to build marketing profiles, and I do not sell it. The AI provider processes requests to produce a response, and its handling of data is covered by its own terms. See the Third-Party Services page and the Privacy Policy. Because Cloudflare operates globally, processing may take place outside Australia." },
      { h: "Your choices", items: [
        "There is currently no setting to switch AI off. AI features only run when someone chooses to use them, such as asking the pet for a hint or asking for a lesson to be built.",
        "If you and your children don't use those features, they aren't triggered. Side Quest works fully with the ready-made lessons and your own plans.",
        "Let your children know they don't have to ask for hints, and tell them to come to you if something seems off.",
        "Review and edit anything AI drafts before your child sees it, and delete AI-drafted lessons or outcome links you don't want.",
        "Tell me if something isn't right using Report a Problem.",
      ] },
      { h: "Changes to AI features", p: "AI tools change quickly. I may add, change or remove AI features, or switch the technology behind them, as Side Quest grows. If a change affects how information is used, I will update this page and the Privacy Policy." },
      { h: "Contact", p: "Questions or concerns about AI in Side Quest? Email support@sidequestlearning.app." },
    ],
  },
  "contact": {
    group: "support", title: "Contact Us", contact: "general",
    summary: "Send a message to base camp. A real person is on the other end.",
    sections: [
      { h: "Hello from base camp", p: "Side Quest is made by one parent who is also homeschooling, usually somewhere between a maths lesson and a snack break. Anything you send goes straight to the Side Quest inbox and I read every message myself." },
      { h: "Send a message", p: "Email support@sidequestlearning.app. Questions, ideas, bugs, a lesson you wish existed, a quest that went sideways: all welcome." },
      { h: "How long will I wait?", p: "I'll reply as soon as I can, usually within a few days. It might take a little longer when it's busy at home or during school holidays. If something is urgent, email isn't the fastest route." },
      { h: "Good things to send", items: [
        "Questions about how something works.",
        "Ideas for new lessons, pets or features.",
        "Something that's broken or confusing.",
        "Trouble signing in or a missing child profile.",
      ] },
      { h: "Make it a quick quest", items: [
        "Email from the address on your Side Quest account so I can find you.",
        "Tell me what you were trying to do and what happened.",
        "Let me know your device and browser if something isn't working.",
        "Use your child's first name or nickname only.",
      ] },
      { h: "Pack light", p: "Please don't email passwords, your child's PIN, home addresses, ID numbers, health details or photos of children. I will never ask you for a password or PIN. If someone claiming to be Side Quest does, don't share it and let me know." },
      { h: "Grown-ups only, please", p: "This inbox is for parents and guardians. If your child has a question or a great idea, they can tell you and you can send it along. I'd love to hear it." },
      { h: "For real emergencies", p: "I can't respond to emergencies. If someone is in danger, call 000. If something in Side Quest worries you, stop using it and let me know." },
      { h: "Other paths", p: "For data, complaint or account deletion requests, the Account & privacy requests pages will get you there fastest. If a lesson or fact is wrong or out of date, use Request a Correction." },
    ],
  },
  "help": {
    group: "support", title: "Help & FAQ",
    summary: "Your quest guide: quick answers for parents, and a few for adventurers.",
    sections: [
      { h: "Welcome, adventurer", p: "Side Quest turns home learning into a quest: lessons to complete, a learning pet to look after, and a place for you to keep track of it all. Here are the answers to the questions I get asked most. If yours isn't here, send it to base camp on the Contact Us page." },

      { h: "The basics" , p: "First things first: what Side Quest is, and who it's for." },
      { h: "What is Side Quest?", p: "It's a home learning hub made by a parent who is also homeschooling. Parents plan lessons, track progress and keep records. Children get their own area with lessons, rewards and a learning pet." },
      { h: "Is Side Quest a school or a curriculum?", p: "No. It's a planning and record-keeping tool that supports your teaching. It doesn't replace it, and it isn't a school, a teacher or an education authority. You stay in charge of your child's education." },
      { h: "Who is it for?", p: "Parents and guardians aged 18 or over, and their children. Children use their own area under the supervision of the parent who set up their profile. Side Quest is currently shared with a small circle of homeschooling families." },
      { h: "Who makes it?", p: "One parent, in Australia, who built it for their own children and then shared it. It's a small personal project, not a company, so replies can take a few days." },
      { h: "Is Side Quest free?", p: "Yes, it's free right now. If that ever changes, I'll tell you first and you won't be charged without agreeing to it." },
      { h: "What do I need to use it?", p: "A parent account and a device with a web browser. Children don't need an email address. They sign in with the username and PIN you set up for them." },

      { h: "Setting up camp", items: [
        "Add a child: go to Children in the sidebar and choose to add a new child profile. You can use a first name or nickname.",
        "Choose a username and PIN for them. Pick a PIN that isn't used anywhere else. You can change it later from the parent dashboard.",
        "Children sign in on the child login page with that username and PIN. They don't need an email address.",
        "Each family gets its own account. Please don't share one account between families.",
      ] },
      { h: "Can I add more than one child?", p: "Yes. Each child gets their own profile with their own username, PIN, year level, avatar and pet, so their progress and rewards stay separate." },
      { h: "My children are in different year levels", p: "That's fine. The year level is part of each child's profile, so you can set it for each child separately." },
      { h: "Should I use my child's real name?", p: "A first name or nickname is plenty. Please avoid full names, and avoid putting other personal details in profiles or notes." },
      { h: "How do I choose a good PIN?", p: "Pick something your child can remember but that isn't used for anything else, like a phone, a bank card or a door code. Please don't email it to me. I'll never ask for it." },
      { h: "Can another grown-up use my account?", p: "Another parent or guardian in your own family can, as long as you keep your password private and look after who has it. Please don't share one account between different families, because each family should have its own." },

      { h: "Pets, hints and rewards" , p: "The fun part of the quest." },
      { h: "What's a learning pet?", p: "Each child has a pet that goes along on the quest. Your child can pick their pet and avatar, and the pet is there to cheer them on. If your child gets stuck during a lesson, their pet can offer a short nudge in the right direction." },
      { h: "What if my child is stuck?", p: "The pet gives a hint, not the answer. Hints are made with AI, so they're not checked by a person as they appear, and they can occasionally be off. If you can, sit with younger children, and tell me if a hint ever seems wrong or confusing." },
      { h: "Does my child have to use the hints?", p: "No. A hint only appears when a child asks for help or gets stuck, so they can try the question themselves first. Let them know they can always come and ask you instead." },
      { h: "Can my child chat with the pet or with AI?", p: "No. The pet only gives short hints about the lesson question. There is no open chat, and children can't type messages to anyone through Side Quest." },
      { h: "What are achievements and pet rewards?", p: "They're there to keep learning fun and motivating, and to give you a snapshot of how things are going. They're not grades or formal assessments, so please don't treat them as the only evidence of how your child is doing." },

      { h: "Lessons and learning" , p: "Finding, building and tracking the learning." },
      { h: "The ready-made lessons don't suit my child", p: "You can ask Side Quest to help draft a lesson to suit your child instead. It's a first draft only. Nothing goes into your child's area until you've read it and chosen to use it, and you can change anything that isn't right." },
      { h: "Can I trust an AI-drafted lesson?", p: "Treat it like a draft from a helpful friend. Check the facts, the difficulty and the wording, and change or delete anything that isn't right before your child sees it." },
      { h: "A lesson or fact is wrong or out of date", p: "Use Request a Correction and tell me which lesson, what's wrong and what it should say. I'll check it and fix it where I can." },
      { h: "Where do I see how they're going?", p: "The Dashboard and each child's overview show progress, evidence and reading. You'll also find achievements and rewards there." },
      { h: "Reading log, word hoard and life learning", items: [
        "Reading log: keep track of what your child has been reading.",
        "Word hoard: collect new and interesting words along the way.",
        "Life learning: record the learning that happens outside of lessons, like cooking, building, or a trip to the park.",
        "Evidence: you can upload photos or work samples. Please only upload what you need, and avoid anything with other people's children in it.",
      ] },
      { h: "What should I upload as evidence?", p: "Work samples and photos that show learning, like a finished page, a project or a drawing. Please avoid other people's children, full home addresses, ID numbers and health details. Photos and work samples are not sent to AI." },
      { h: "What are curriculum outcomes?", p: "Side Quest is currently built around the NSW curriculum, and it links activities to NSW outcomes to help you plan and record. Some of those links are suggested with AI, so they're a guide only. Please check them against the official NSW syllabus before you use them for reporting. If a link or outcome looks wrong or out of date, use Request a Correction." },
      { h: "Can I use it for my home education reporting?", p: "It can help you keep records, but I can't promise that anything it produces will be accepted by NESA or any other regulator. Check the current requirements with the relevant authority and keep whatever records they ask for. See the Educational Disclaimer." },
      { h: "Can I use it if I'm outside NSW?", p: "You can, but the outcomes and requirements are for NSW, and other states and territories differ. Treat the outcome links as a general guide, not as your state's curriculum." },

      { h: "Signing in" , p: "Getting back into camp." },
      { h: "I forgot my password", p: "On the main sign-in page, choose \"Forgot password?\" and follow the steps. If it doesn't work for you, email me at support@sidequestlearning.app from the address on your account and I'll help. I'll never ask for your password or your child's PIN." },
      { h: "My child forgot their PIN", p: "On the child sign-in page, your child can choose \"Forgot my PIN\". This sends a prompt to your parent dashboard. Open the \"View\" area to see the details and set a new PIN for them. Pick one that isn't used anywhere else, and let your child know. The request only goes to you, and children can't use it to message anyone else." },
      { h: "I think someone else has used my account", p: "Email me straight away at support@sidequestlearning.app from your account address, and change your password. Keep your password private and use one you don't use anywhere else." },
      { h: "Someone asked me for my password or my child's PIN", p: "Don't share it. I will never ask you for a password or PIN, by email or any other way. If someone claiming to be Side Quest does, let me know." },

      { h: "Safety and privacy" , p: "How your family's information is looked after." },
      { h: "Is it safe for my child?", p: "Children only reach their own area, which you set up and manage. There are no ads, no public profiles, and no messaging between users. Read more on the Safety Overview page. You're still the one in charge, so keep an eye on how they're getting on." },
      { h: "Can other families see my child's work?", p: "No. Nothing is published or shared with other families. Your family's information stays in your account." },
      { h: "Do you sell my information or show ads?", p: "No. I don't sell or rent personal information, and there is no advertising for children." },
      { h: "Does the AI see my child's name?", p: "I aim to send AI only the minimum text it needs, like the lesson question for a hint, and to leave out names and other identifying details. Please avoid typing names or personal details into anything that's sent to AI, like a lesson-building request. See the AI Use & Limitations page." },
      { h: "Can I switch the AI off?", p: "There's no on/off setting right now. AI features only run when someone uses them, such as asking the pet for a hint or asking for a lesson to be built. If you don't use those, they aren't triggered, and Side Quest still works fully with the ready-made lessons and your own plans." },
      { h: "Who looks after the data?", p: "Side Quest runs on Cloudflare, which provides hosting, the database, file storage, AI features and security. Support emails are forwarded to a Gmail inbox used only for Side Quest. Because these providers operate globally, information may be processed outside Australia. See the Third-Party Services page." },

      { h: "Your information and account" , p: "You're in control of your family's data." },
      { h: "Can I see what you hold about my family?", p: "Yes. Use Request Your Data. I'll confirm your identity first and aim to reply within 30 days. It's free." },
      { h: "My own details are wrong or out of date", p: "You can edit most details yourself in Children and your account. If it's something you can't change directly, email support@sidequestlearning.app from your account address with \"Correct my information\" in the subject line." },
      { h: "Can I delete one child's profile?", p: "Yes. Deleting a child profile removes that child's information and learning records, except where something must be kept by law. Keep your own copy of anything you need, like photos or records for reporting, first." },
      { h: "How do I delete my account?", p: "Use Delete account from the Account & privacy requests page or the sidebar. It removes your account, your children's profiles and their learning records. The hosting provider may keep short-term backups for a limited time before they're removed." },
      { h: "I'm not happy with how my information was handled", p: "Use the Privacy Complaint page or email me. I'll look into it and reply in writing. You can also contact the Office of the Australian Information Commissioner at oaic.gov.au." },

      { h: "When things go wrong" , p: "Bugs, glitches and feedback." },
      { h: "Something's broken", p: "Tell me through Report a Problem. What you were trying to do, what you expected, what happened, and the device or browser you used all help me find it quickly." },
      { h: "A hint or lesson looks wrong or unsuitable", p: "Stop using it and tell me through Report a Problem. AI can make mistakes, and I want to know when it does so I can fix it." },
      { h: "Can I suggest a lesson, a pet or a feature?", p: "Please do! Ideas are welcome on the Contact Us page. I read every message, though I can't promise to build everything." },
      { h: "Will my work be lost if Side Quest changes?", p: "I do my best to keep it running, but it's run by one person, so I can't promise it'll always be available. Features may change or be removed. Please keep your own copies of anything important, like photos and records you need for reporting." },
      { h: "Is there anything urgent I should know?", p: "I can't respond to emergencies. If someone is in danger, call 000." },

      { h: "Still stuck?", p: "Head to the Contact Us page and send a message to base camp. I read every one, and I'll reply as soon as I can, usually within a few days." },
    ],
  },
  "report-problem": {
    group: "support", title: "Report a Problem", contact: "problem",
    summary: "Found a bug, a wrong hint or something that just isn't right? Send it to base camp.",
    sections: [
      { h: "Spotted something odd?", p: "Every good quest has the odd glitch, and I'd rather hear about it than have you quietly work around it. Tell me what happened and I'll look into it. Reports go straight to the Side Quest inbox and I read every one myself." },
      { h: "What to include", items: [
        "What you were trying to do, for example finishing a lesson or adding a child.",
        "What you expected to happen, and what happened instead.",
        "Where it happened: the page or screen, and which child area or parent area you were in.",
        "Your device and browser, for example an iPad using Safari or a laptop using Chrome.",
        "Roughly when it happened, and whether it happens every time or only sometimes.",
        "Your child's first name or nickname only, if you need to mention them.",
      ] },
      { h: "Different kinds of problem", items: [
        "Something is broken or won't load: tell me the steps that led to it. Refreshing the page or signing out and back in sometimes clears a glitch, but please still let me know.",
        "A hint or lesson looks wrong or unsuitable: stop using it and tell me what the question was and what the pet or lesson said. AI can make mistakes and I want to fix them.",
        "A fact, lesson or curriculum outcome looks wrong or out of date: use Request a Correction so it goes to the right place.",
        "Trouble signing in: try \"Forgot password?\" on the sign-in page, or the \"Forgot my PIN\" option for children, first. If that doesn't work, tell me what happened.",
        "Something doesn't look right on the screen: let me know the device and screen size if you can.",
        "A safety concern: stop using the feature involved and tell me straight away.",
      ] },
      { h: "Pack light", p: "Please don't include passwords, your child's PIN, full names, home addresses, ID numbers, health details or photos of children. I will never ask you for a password or PIN. If someone claiming to be Side Quest does, don't share it and let me know." },
      { h: "Screenshots", p: "A screenshot can help a lot, but please crop or blur names and faces first, and don't send photos of children. If you can describe what you saw in words, that works just as well. I may reply and ask for more detail." },
      { h: "What happens next", items: [
        "I'll read your report and reply as soon as I can, usually within a few days. It may take longer when it's busy at home or during school holidays.",
        "I might ask you a question or two to help track the problem down.",
        "I can't promise how quickly something will be fixed, or that every report will lead to a change, but each one helps make Side Quest better.",
        "Please keep your own copies of anything important in the meantime, like photos and records you need for reporting.",
      ] },
      { h: "Not a bug?", p: "For questions about how something works, the Help & FAQ page might have the answer. For ideas or general messages, use Contact Us. For wrong or out of date lessons and facts, use Request a Correction. For data or deletion requests, or a privacy complaint, use the Account & privacy requests pages." },
      { h: "Grown-ups only, please", p: "This is for parents and guardians. If your child spots a problem, they can tell you and you can send it along." },
      { h: "For real emergencies", p: "I can't respond to emergencies. If someone is in danger, call 000." },
    ],
  },
  "request-access": {
    group: "privacy", title: "Request Your Data", contact: "access",
    summary: "Ask for a copy of the information I hold about your family.",
    sections: [
      { h: "Your family, your information", p: "You have the right to see what Side Quest holds about you and your children. There's no secret vault and no catch. Ask, and I'll gather it up for you. It's free, and you don't need to give a reason." },
      { h: "What you can ask for", items: [
        "A copy of the personal information I hold about you, as the parent or account holder.",
        "A copy of the information I hold about each of your children.",
        "A description of what I hold and why, if you'd like to understand more than the data itself.",
      ] },
      { h: "What's usually in there", items: [
        "Your account details: name, email address and account settings. Your password is stored in a protected form and is not something I can read or send you.",
        "Each child's profile: first name or nickname, year level, username, avatar and pet choices. A child's PIN is protected the same way.",
        "PIN requests: the time and the child profile they came from.",
        "Learning records: lessons completed, progress against outcomes, achievements, reading log and word hoard entries.",
        "Records you created: lesson plans, learning plans, calendar entries, saved resources, life learning entries and notes.",
        "Evidence you uploaded, such as photos or work samples.",
        "Emails you've sent me, kept as long as needed to deal with your request.",
      ] },
      { h: "How to ask", items: [
        "Email support@sidequestlearning.app from the address on your Side Quest account, so I can match it to you.",
        "Put \"Request Your Data\" in the subject line so it doesn't get lost among the questions and quests.",
        "Say whether you'd like everything, or just certain things, for example one child's reading log.",
        "If you're asking about a child, use their first name or nickname only.",
      ] },
      { h: "Pack light", p: "Please don't send your password, your child's PIN, ID documents, home addresses, health details or photos of children with your request. I will never ask you for a password or PIN. If someone claiming to be Side Quest does, don't share it and let me know." },
      { h: "Checking it's really you", p: "Before I share anything, I need to be sure it's the right person asking, because this is your family's private information. Sending your request from your account email is usually enough. If something doesn't match, I may ask you a simple question or two that only the account holder would know. I'll only ask for what's needed to confirm who you are." },
      { h: "What happens next", items: [
        "I'll reply to confirm I've got your request and, if needed, check who you are.",
        "I aim to respond within 30 days. I'll often be quicker, but I'm one person, so it can take longer when it's busy at home or in school holidays.",
        "I'll send your information to the email address on your account, so please make sure it's one you can still use. If you want it a different way, tell me when you ask.",
        "If I can't give you something, I'll tell you what and why in writing.",
      ] },
      { h: "Things to know", items: [
        "Only the account holder, or a parent or guardian authorised to act for the family, can make a request about the account and its child profiles.",
        "Children can't make this request themselves. If your child is curious, they can ask you.",
        "Technical and security logs kept by the hosting provider are held only briefly, so they may not be included.",
        "I can only share what I hold. Anything you've already deleted may be gone, apart from short-term backups kept by the hosting provider for a limited time.",
        "I can't share personal information about other people, including other families.",
      ] },
      { h: "Do it yourself", p: "A lot of your information is already visible in your parent hub, including children, lessons, evidence, reading logs and your account. If you only want to check one thing or keep a photo or record, you may be able to find it there straight away." },
      { h: "Related requests", items: [
        "Something in your own information is wrong: edit it in your parent hub, or email support@sidequestlearning.app with \"Correct my information\" in the subject line.",
        "A lesson or fact on the site is wrong or out of date: use Request a Correction.",
        "You'd like it all gone: use Delete Account on this page or in the sidebar. You may want to request a copy of your data first, because deleting is permanent.",
        "You're unhappy with how your information was handled: use Privacy Complaint.",
      ] },
      { h: "More about your information", p: "The Privacy Policy explains what I collect, why, who sees it and how long I keep it. How I Handle Data has the short version." },
      { h: "Grown-ups only, please", p: "This is for parents and guardians. If your child has a question about their information, they can tell you and you can ask me." },
    ],
  },
  "request-correction": {
    group: "support", title: "Request a Correction", contact: "correction",
    summary: "Found a typo in the map? Tell me, and I'll fix it.",
    sections: [
      { h: "The quest behind the quest", p: "Side Quest began on my couch. I went looking for something that did all of this for my own children, couldn't find it, and decided to build it myself. That turned into a quest of its own, with a lot of late nights, a few dead ends and plenty of trial and error. It's still a one-person adventure." },
      { h: "Even maps have mistakes", p: "One adventurer can't spot every wrong turn. Some lessons, facts, outcome links or hints will be wrong, and some will drift out of date as the world changes. When you notice one, please tell me. You're not being picky. You're helping me redraw the map for every family on the journey." },
      { h: "What's worth flagging", items: [
        "A fact that's wrong or has changed.",
        "A question with a wrong answer, or two right ones.",
        "A curriculum outcome link that doesn't fit the lesson or the current NSW syllabus.",
        "A year level or difficulty that seems off.",
        "A resource that's out of date or broken.",
        "A typo or confusing instruction.",
        "A pet hint that sent your child down the wrong path.",
        "A line on the legal or help pages that's no longer true.",
      ] },
      { h: "What helps me fix it", items: [
        "Where you found it: the lesson, subject and year level, or the page.",
        "What it says now, and what's wrong with it.",
        "What it should say, if you know.",
        "A source if you have one, like the NSW syllabus.",
      ] },
      { h: "Send a message to base camp", p: "Email support@sidequestlearning.app with \"Request a Correction\" in the subject line. If it's about a child's work, use their first name or nickname only. A screenshot can help, but please crop or blur names and faces first. Please don't include passwords, PINs or photos of children, and I will never ask you for them." },
      { h: "What happens next", p: "Every message reaches me. I'll reply as soon as I can, usually within a few days, and let you know when the map has been fixed. If I think it's right as it is, I'll explain why rather than leaving you without an answer. I can't promise it will be quick, because I'm squeezing this quest in around family life." },
      { h: "A word of caution from the trail", p: "Side Quest is a guide, not an official source. For anything that matters, like reporting, check against the NSW syllabus and NESA. See the Educational Disclaimer." },
      { h: "Wrong path?", items: [
        "Something is broken: use Report a Problem.",
        "An idea for a new lesson, pet or feature: use Contact Us.",
        "Your own account details are wrong: edit them in the parent hub, or email support@sidequestlearning.app with \"Correct my information\" in the subject line.",
        "A copy of your information: use Request Your Data.",
      ] },
      { h: "For young adventurers", p: "If your child finds a mistake in a lesson, that's a real win. They can tell you, and you can send it along." },
    ],
  },
  "privacy-complaint": {
    group: "privacy", title: "Privacy Complaint", contact: "complaint",
    summary: "Unhappy with how your family's information was handled? Tell me. I'll take it seriously.",
    sections: [
      { h: "I want to hear about it", p: "Your family trusts me with their information, and I take that seriously. If you think I've handled it badly, you're entitled to say so, and you won't be treated any differently for doing it. A complaint gives me the chance to put things right and to do better for every family." },
      { h: "What you can complain about", items: [
        "Information about you or your children being collected, used or shared in a way you didn't expect or agree to.",
        "Someone gaining access to your account or your children's information who shouldn't have.",
        "A request to see, correct or delete your information that was ignored, delayed or handled badly.",
        "Information kept longer than the Privacy Policy says, or not removed when you deleted it.",
        "Something in a lesson, hint or AI feature that revealed or mishandled personal information.",
        "Anything else about how your family's information has been looked after that doesn't sit right with you.",
      ] },
      { h: "Quicker routes first", p: "Some things don't need a formal complaint and can be fixed faster another way. You can edit most details yourself in the parent hub. You can ask for a copy of your information on Request Your Data, and you can delete a child profile or your account at any time. If any of those didn't work, or you'd rather make a complaint anyway, that's completely fine." },
      { h: "How to complain", items: [
        "Email support@sidequestlearning.app from the address on your Side Quest account, so I can match it to you.",
        "Put \"Privacy Complaint\" in the subject line so it doesn't get lost among the questions and quests.",
        "Tell me what happened, when you noticed it, and what information you think was involved.",
        "Tell me what you'd like me to do about it, if you know.",
        "If it involves a child, use their first name or nickname only.",
      ] },
      { h: "Pack light", p: "Please don't include passwords, your child's PIN, ID documents, home addresses, health details or photos of children in your complaint. If I need something more, I'll tell you exactly what and why. I will never ask you for a password or PIN. If someone claiming to be Side Quest does, don't share it and let me know." },
      { h: "Checking it's really you", p: "Because a complaint can involve your family's private information, I'll need to be sure it's the right person writing before I share details or change anything. Writing from your account email is usually enough. If something doesn't match, I may ask a simple question or two that only the account holder would know." },
      { h: "What happens next", items: [
        "I'll reply to confirm I've got your complaint, as soon as I can and usually within a few days.",
        "I'll look into what happened, which may include checking logs and records and asking you for more detail.",
        "I aim to give you a full answer in writing within 30 days. If it's going to take longer, I'll tell you why and when to expect it.",
        "My answer will say what I found, what I'm doing about it, and the reasons if I disagree with you.",
        "If something went wrong, I'll fix what I can, say sorry where it's owed, and change how I do things so it's less likely to happen again.",
      ] },
      { h: "If your information may be at risk", p: "If you think your account or your children's information is at risk right now, change your password straight away, reset your children's PINs from the parent dashboard, and email me with \"Urgent privacy\" in the subject line. If I find a data breach that's likely to cause serious harm, I'll act quickly to contain it and tell affected families, and the Office of the Australian Information Commissioner where required, as set out in the Privacy Policy." },
      { h: "Not happy with my answer?", p: "You can take your complaint to the Office of the Australian Information Commissioner (OAIC) at oaic.gov.au. The OAIC generally expects you to have raised the complaint with the organisation first and to have allowed a reasonable time for a reply. You're welcome to contact them at any point if you feel you need to." },
      { h: "Things to know", items: [
        "Only the account holder, or a parent or guardian authorised to act for the family, can make a complaint about the account and its child profiles.",
        "Children can't make a complaint themselves. If your child is worried about something, they can tell you and you can write to me.",
        "Side Quest is a small personal project run by one person. That doesn't change how seriously I take privacy, but it can affect how quickly I can reply.",
        "I keep your complaint and my reply for as long as needed to deal with it, in line with the Privacy Policy.",
      ] },
      { h: "Not quite a privacy complaint?", items: [
        "Something is broken or not working: use Report a Problem.",
        "A lesson or fact is wrong or out of date: use Request a Correction.",
        "You'd like to see what I hold about your family: use Request Your Data.",
        "A general question or idea: use Contact Us.",
      ] },
      { h: "More about your information", p: "The Privacy Policy explains what I collect, why, who sees it and how long I keep it. How I Handle Data has the short version." },
      { h: "For real emergencies", p: "I can't respond to emergencies. If a child is in danger, call 000." },
      { h: "Grown-ups only, please", p: "This is for parents and guardians. If your child has a worry about their information, they can tell you and you can bring it to me." },
    ],
  },
  "data-handling": {
    group: "trust", title: "How I Handle Data", public: true,
    summary: "The short version of how your family's information is treated, in plain language.",
    sections: [
      { h: "The short version", items: [
        "I collect what the learning features need, and no more.",
        "You're in charge. Parents create child profiles and can edit or delete them, or the whole account, at any time.",
        "I don't sell personal information, and there is no advertising for children.",
        "Your family's information stays in your account. Nothing is published or shared with other families.",
        "I'm one person, so I keep things simple and use trusted providers rather than building my own.",
      ] },
      { h: "Minimal by design", p: "Side Quest only asks for what it needs to run your account and the learning features. Children don't need an email address, and a first name or nickname is plenty for a profile. I'd rather hold less of your family's information than more." },
      { h: "What I hold", items: [
        "Parent account: your name, email address and sign-in details.",
        "Child profiles: first name or nickname, year level, username, avatar and pet choices.",
        "Learning records: lessons completed, progress, achievements, reading log, word hoard and life learning entries.",
        "Things you add: lesson plans, calendar entries, saved resources, notes, and any photos or work samples you upload.",
        "PIN requests: when a child asks for help with a forgotten PIN, the time and which profile it came from.",
        "Emails you send to support, kept as long as needed to deal with them.",
      ] },
      { h: "Parent in charge", p: "Parents set up and manage their children's profiles. Children sign in with the username and PIN their parent sets, and can only reach their own area. A parent decides what to upload, can change a child's PIN, and can delete a child profile or the whole account. The Privacy Policy has the detail." },
      { h: "Where it lives", p: "Side Quest runs on Cloudflare, which provides hosting, the database, file storage, AI features and security. Support emails are forwarded to a Gmail inbox used only for Side Quest. Because these providers run global networks, information may be stored or processed outside Australia. See the Third-Party Services page." },
      { h: "Who can see it", items: [
        "You and your family, through your own account.",
        "Me, only when I need to run the service, fix a fault, or help with a request or complaint you've sent me.",
        "The providers who help run Side Quest, only as needed to do that work.",
        "No other families, no advertisers, and no data brokers.",
      ] },
      { h: "How I look after it", p: "Data travels over encrypted connections (HTTPS). Parent accounts are protected by sign-in, and children's areas by their PIN. Passwords and PINs are stored in a protected form, so I can't read them or send them to you. I restrict access to the site and keep an eye on logs for problems. No online service is completely secure, so please use a strong, unique password and keep it private." },
      { h: "AI and your information", p: "Some features use AI for pet hints, lesson drafts and outcome suggestions. I aim to send only the minimum text needed for the task and to leave out names and other identifying details. Photos and work samples are not sent to AI. Please avoid typing personal details into anything that's sent to AI. See the AI Use & Limitations page." },
      { h: "What I don't do", items: [
        "I don't sell or rent personal information.",
        "I don't show ads or use advertising services.",
        "I don't add separate analytics trackers.",
        "I don't use children's information to build marketing profiles.",
        "I don't publish your family's work or share it with other families.",
        "I don't give children an open chat, with AI or with anyone else.",
      ] },
      { h: "Keeping and deleting", p: "I keep your information while your account is active. If you delete a child profile or your account, I delete the related information, except where I must keep something by law. The hosting provider may keep short-term backups for a limited time before they're removed, and technical logs are held only briefly. Keep your own copy of anything you need first, like photos and records for reporting, because deleting is permanent." },
      { h: "Your controls", items: [
        "Edit most details yourself in the parent hub.",
        "Ask for a copy of your information with Request Your Data.",
        "Delete a child profile, or your whole account, at any time.",
        "Ask me to correct anything that's wrong by emailing support@sidequestlearning.app with \"Correct my information\" in the subject line.",
        "Raise a concern or complaint with Privacy Complaint.",
      ] },
      { h: "If something goes wrong", p: "If a data breach is likely to cause serious harm, I'll act quickly to contain it and tell affected families, and the Office of the Australian Information Commissioner where required. If you ever think your account has been accessed by someone else, change your password, reset your children's PINs, and email me straight away." },
      { h: "The honest bit", p: "Side Quest is a small personal project run by one parent, not a company with a security team. I take reasonable steps and choose providers with published security commitments, but I can't promise nothing will ever go wrong. That's also why I keep what I collect small, and why I'd suggest keeping your own copies of anything important." },
      { h: "Want the full detail?", p: "This page is the short version. The Privacy Policy covers everything I collect, why, who sees it, how long I keep it and your rights. If something here doesn't match what you see, tell me through Report a Problem, or use Request a Correction if the wording is wrong." },
    ],
  },
  "third-parties": {
    group: "trust", title: "Third-Party Services", public: true,
    summary: "The outside providers that help run Side Quest, what each one does, and what it can see.",
    sections: [
      { h: "The short version", items: [
        "Side Quest runs on two outside providers: Cloudflare and Google.",
        "Cloudflare hosts the site and holds your family's data. Google only receives the emails you send to support.",
        "I don't use advertising services, analytics trackers or data brokers.",
        "I don't sell your information to anyone, and providers only get what they need to do their job.",
      ] },
      { h: "Why I use outside providers", p: "Side Quest is built and run by one parent. Rather than build my own servers, storage and security, I use established providers who do it at a scale and standard I couldn't match on my own. It also keeps things simple, so there are fewer places your family's information can end up." },
      { h: "Cloudflare", p: "Cloudflare is the main provider behind Side Quest. It's a global internet infrastructure company, and it runs most of what makes the site work." },
      { h: "What Cloudflare does for Side Quest", items: [
        "Hosting: serves the Side Quest website and app to you.",
        "Database: stores account details, child profiles, learning records and the things you add.",
        "File storage: holds photos and work samples you upload as evidence.",
        "AI features: processes the requests behind pet hints, lesson drafts and outcome suggestions.",
        "Security: helps protect the site from attacks and misuse, and keeps connections encrypted.",
        "Email routing: passes emails sent to support@sidequestlearning.app on to my inbox.",
      ] },
      { h: "What Cloudflare can see", p: "Because Cloudflare hosts Side Quest, your family's information is stored on its systems and it also records some technical data automatically, such as IP address, browser and device type, pages requested, error logs and the time of requests. Cloudflare uses this to run and secure its service, under its own terms and privacy commitments. I don't use Cloudflare's tools to track you across other websites or to build advertising profiles." },
      { h: "Google (Gmail)", p: "Google runs Gmail. Emails you send to support@sidequestlearning.app are forwarded by Cloudflare to a Gmail inbox that I use only for Side Quest. That inbox is where I read and reply to your messages." },
      { h: "What Google can see", p: "Google only sees what's in the emails you send and the replies I write, plus the usual technical details of email delivery. It doesn't have access to your Side Quest account or your children's learning records. That's another reason to keep emails light: please don't send passwords, PINs, ID documents or photos of children." },
      { h: "AI and the AI provider", p: "AI features run on Cloudflare's platform. When someone asks for a hint, a lesson draft or an outcome suggestion, the minimum text needed for that task is sent for processing, and I aim to leave out names and other identifying details. Photos and work samples are not sent to AI. The provider's handling of that data is covered by its own terms. See the AI Use & Limitations page for what AI does and doesn't do." },
      { h: "What I don't use", items: [
        "No advertising services or ad networks.",
        "No separate analytics or tracking tools.",
        "No social media plugins, like buttons or tracking pixels.",
        "No data brokers, and no one I sell or rent information to.",
      ] },
      { h: "Cookies", p: "I only use cookies or similar browser storage where needed to keep you signed in and keep the service secure. I don't use advertising cookies. See the Privacy Policy for more." },
      { h: "Outside Australia", p: "Cloudflare and Google both run global networks, so your information may be stored or processed outside Australia, including in the United States and other countries. I choose providers who publish security and privacy commitments, but I can't control exactly where their systems process data." },
      { h: "Links to other websites", p: "Some lessons and resources link to outside websites, videos or books. Those aren't part of Side Quest, and I don't control them or what they collect. Their own terms and privacy policies apply once you click through. Preview links before sharing them with your child, and see the Educational Disclaimer." },
      { h: "If I change providers", p: "Providers may change as Side Quest grows, or if a better or safer option comes along. If a change affects how your information is handled, I'll update this page and the Privacy Policy, and let families know if it's an important change." },
      { h: "Your information and the providers", p: "If you delete a child profile or your account, I delete the related information from Side Quest's systems. Cloudflare may keep short-term backups and technical logs for a limited time before they're removed. Emails you've sent me are kept in my support inbox as long as needed to deal with your request. See the Privacy Policy for the full detail." },
      { h: "Questions?", p: "If you'd like to know more about who handles your information, or something here doesn't look right, email support@sidequestlearning.app. If the wording is out of date, use Request a Correction." },
    ],
  },
  "safety": {
    group: "trust", title: "Safety Overview", public: true,
    summary: "How Side Quest is kept a safe space for children.",
    sections: [
      { h: "Parent in charge", p: "Children can only reach content within their own profile, set up and managed by a parent. They sign in with a username and PIN, not an email address." },
      { h: "No open chat", p: "Side Quest has no public profiles and no messaging between users." },
      { h: "PIN requests", p: "If a child forgets their PIN, they can send a prompt to their own parent's dashboard. It only reaches the parent who set up their profile. It is not a message between users, it carries no typed text from the child, and it does not let children contact anyone else. The parent decides whether to set a new PIN." },
      { h: "Reporting", p: "If something concerns you, use Report a Problem and I will look into it promptly." },
    ],
  },
};
