INSERT OR IGNORE INTO lessons (id, family_id, seed_key, title, stage, learning_area, unit_id, status, data, created_at, updated_at) VALUES (
  'seed-s2-maths-place-value-01', NULL, 's2-maths-place-value-01', 'Place Value Detectives', 'S2', 'Mathematics', NULL, 'approved',
  '{"year_level":"Year 3","subject":"Number and Algebra","child_mission":"Become a place value detective by reading, building and comparing numbers to tens of thousands.","duration_minutes":60,"outcome_codes":["MA2-RWN-01"],"materials":["Paper","Pencil","Dice or number cards"],"steps":[{"title":"Warm up","detail":"Roll four dice and make the largest and smallest number you can."},{"title":"Learn","detail":"Watch the place value video and practise reading each number."},{"title":"Build","detail":"Use drawings or a place value chart to build 24,375."},{"title":"Compare","detail":"Make three large numbers and order them from smallest to largest."},{"title":"Apply","detail":"Write a short detective story using three large numbers."}],"resources":[{"type":"video","title":"Place value video","url":"https://www.youtube.com/results?search_query=place+value+for+kids"},{"type":"game","title":"Place value game","url":"https://www.abcya.com/games/place_value_hockey"}],"quiz":[{"question":"In 45,208, what is the value of the 5?","type":"multiple_choice","options":["5 ones","5 tens","5 thousands","5 ten-thousands"],"correct_index":2,"explanation":"The 5 is in the thousands place."}],"reflection_prompts":["What helped you compare large numbers?"],"evidence_instructions":"Upload a photo of your work and explain how you compared your numbers.","parent_notes":"Ask your child to read each number aloud before comparing.","extension":"Create five numbers and challenge someone to order them."}',
  '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z'
);

INSERT OR IGNORE INTO lessons (id, family_id, seed_key, title, stage, learning_area, unit_id, status, data, created_at, updated_at) VALUES (
  'seed-s2-english-persuasive-writing-01', NULL, 's2-english-persuasive-writing-01', 'Convince Me: Persuasive Writing', 'S2', 'English', NULL, 'approved',
  '{"year_level":"Year 3","subject":"Writing","child_mission":"Plan, write and improve a persuasive text for your family.","duration_minutes":60,"outcome_codes":["EN2-CWT-01","EN2-SPELL-01"],"materials":["Paper or device","Pencil"],"steps":[{"title":"Choose","detail":"Choose something you want to convince your family to do."},{"title":"Learn","detail":"Watch the persuasive writing video."},{"title":"Plan","detail":"Write your opinion, three reasons and an ending."},{"title":"Draft","detail":"Write your persuasive text."},{"title":"Edit","detail":"Check spelling, punctuation and persuasive language."}],"resources":[{"type":"video","title":"Persuasive writing video","url":"https://www.youtube.com/results?search_query=persuasive+writing+for+kids"},{"type":"game","title":"Spelling and grammar game","url":"https://www.topmarks.co.uk/english-games/7-11-years/spelling-and-grammar"}],"quiz":[{"question":"What should a persuasive text begin with?","type":"multiple_choice","options":["A clear opinion","A spelling list","A random story","A picture only"],"correct_index":0,"explanation":"A persuasive text needs a clear opinion."}],"reflection_prompts":["Which reason was strongest?"],"evidence_instructions":"Upload or type your finished persuasive text.","parent_notes":"Ask your child to identify the opinion, reasons and ending.","extension":"Turn your writing into a poster or short advertisement."}',
  '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z'
);
